### ISSUE TITLE
Immediately dispose a provider when one of its dependencies is known to have changed

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/river_pod#100]
Currently when using `ref.watch`, if the value listened changes, the state of the provider is destroyed only the next time the provider is read.
This works most of the time, but in some situations, the provider may never be read again.

We could change the current behavior such that rather than waiting for the next read, the provider is disposed _immediately_ when any of the dependency is known to have changed.

**Comment by rrousselGit** [comment]
Closing as this probably wouldn't do what we'd expect:
Some residuals would still be in memory

We probably need an external way to force the disposal of a provider.

**Comment by scopendo** [comment]
Hi @rrousselGit – was forcing disposal ever implemented?  I saw another comment where `context.disposeProvider()` was mentioned, but I don't see that in the docs so perhaps it was just an idea.

**Comment by rrousselGit** [comment]
There's some pending work about it.

**Comment by a-marenkov** [comment]
> There's some pending work about it. 

Any update on this?

**Comment by rrousselGit** [comment]
Not yet
I'm busy with other things like non-nullable types
