### ISSUE TITLE
AsyncInitial AsyncValue.initial

### ISSUE THREAD

**Issue by theweiweiway** [rrousselGit/river_pod#1002]
**Is your feature request related to a problem? Please describe.**
It would be helpful to have an `AsyncInitial` state, especially for POST requests with a form field and button. A common use case i am thinking of is: 

- initial state could render empty form field and button

after user fills out the field and presses the button:

- loading state could disable form field and button
- data state could show a success indicator, or redirect the user
- error state could show a snack bar

**Describe the solution you'd like**
It'd be nice to have something like this:
```
watch(something.state).when(
  initial: () => InitialWidget(),
  data...
  error...
  loading...
)
```

I understand that it won't be as nice because an initial state is not needed most of the times, and adding this initial state could clutter things. So maybe a new `EnhancedAsyncValue<T>` would work? 

Not sure if this is a good idea.. Open to suggestions!

**Comment by davidmartos96** [comment]
Why not model this with the data state?
You could make the data T model the empty form and the form with data

**Comment by theweiweiway** [comment]
ya it's actually pretty easy to just do this myself, probably not worth a whole new feature request
