### ISSUE TITLE
Why StateProvider update() is not notifying listeners in all cases?

### ISSUE THREAD

**Issue by ebelevics** [rrousselGit/river_pod#1006]
The problem lies when state.update() can't update the same mutable object. Only when state object changes, then it rebuilds. I expected that state.update() will work similar as stream.add() or notifyListeners() regardless of value differences.

I'm not using StateNotifier as it requires immutable objects (and working with immutable objects in dart is pain). Second reason I want to manage multiple states like state, error, controllers and others in one class.

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() {
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) => MaterialApp(home: Home());
}

final counterBlocProvider = Provider.autoDispose((ref) => CounterBloc(ref: ref));

class CounterBloc {
  final AutoDisposeRef ref;
  CounterBloc({required this.ref});

  late final _state = ref.watch(state.notifier);
  final state = StateProvider.autoDispose<CounterState>((ref) => CounterState());

  void increment() {
    //DOESN'T REBUILD
    _state.state = _state.state..count = _state.state.count + 1;
    _state.update((s) => s..count = s.count + 1);
    //DOES REBUILD
    //_state.update((s) => CounterState()..count = s.count + 1);
  }

  void decrement() => _state.update((s) => s..count = s.count--);
}

class CounterState {
  int count = 0;
}

class Home extends ConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final _bloc = ref.watch(counterBlocProvider);
    final _state = ref.watch(_bloc.state);

    return Scaffold(
      appBar: AppBar(title: const Text('Counter example')),
      body: Center(
        child: Text('${_state.count}'),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => _bloc.increment(),
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

Why I put state inside class, because I don't want that my bloc class is recreated if some dependency is changed in provider.
For example `ref.watch(otherProvider.notifier)` will recreate StateNotifier which will recreate important values inside StateNotifier class, which I don't want. Also this approach is making mounted exception as instance is no longer present.

```dart
final stateProvider = Provider.autoDispose<StateNotifier>(
  (ref) => StateNotifier(
    otherProvider: ref.watch(otherProvider.notifier),
  ),
 dependencies:[otherProvider],
);
```

**Comment by ebelevics** [comment]
Just noticed that `state =` and `state.update()` is relied on StateController which extends StateNotifier. So no workaround :(

**Comment by rrousselGit** [comment]
If you don't want this, create a `ChangeNotifier` and make your own using ChangeNotifierProvider.

Filtering identical values is something people explicitly asked for, and is how `ValueNotifier` works too.

**Comment by ebelevics** [comment]
I noticed that state notifier is made by Remi, there's reason why it's used in Riverpod as default state notifier. Sorry for my ignorance.
