### ISSUE TITLE
Comment error :'/// ref.read(provider).update((state) => state + 1);'

### ISSUE THREAD

**Issue by sweatfryash** [rrousselGit/river_pod#1007]
https://github.com/rrousselGit/river_pod/blob/15d9e1a4e8e68fb77987aa7bca695a58cc6089e8/packages/riverpod/lib/src/state_provider.dart#L35

A little thing,following above comment will get error,should like this;
` ref.read(provider.state).update((state) => state+1); `

**Comment by tbm98** [comment]
it should closed by [this commit](https://github.com/rrousselGit/river_pod/commit/6a3b2ec00621ff101086af61e893899aba93467a)

**Comment by rrousselGit** [comment]
Thanks!
