### ISSUE TITLE
[Web] Adding flutter_riverpod: ^1.0.3 is stucks at main() 

### ISSUE THREAD

**Issue by zahidshaikh08** [rrousselGit/river_pod#1019]
flutter_riverpod: ^1.0.3

**To Reproduce**
runApp(ProviderScope(child: new App()));

**Expected behavior**
Should run app as usual 

**Actual behavior**

**App gets stuck at main() in (tried web only, other platforms not tried)**. 
After removing same dep app just started working fine as before.

**Comment by rrousselGit** [comment]
This was a bug in Dart, which caused an error

Try upgrading your Dart/Flutter SDK and the issue should go away
