### ISSUE TITLE
Broken Link in Reading a Provider

### ISSUE THREAD

**Issue by md-weber** [rrousselGit/river_pod#102]
**Describe what scenario you think is uncovered by the existing examples/articles**
The first sentence of [Reading a Provider](https://riverpod.dev/docs/concepts/reading), the Link to Providers is broken it should link to 
https://riverpod.dev/docs/concepts/providers 
but it refers to
https://riverpod.dev/docs/concepts/provider.
```
Before reading this guide, make sure to read about Providers first.
```

**Comment by rrousselGit** [comment]
Good catch, done!

**Comment by md-weber** [comment]
Thank you, that was super fast 👍

**Comment by md-weber** [comment]
Same in the following pages:
https://riverpod.dev/docs/concepts/combining_providers
https://riverpod.dev/docs/concepts/modifiers/family

**Comment by rrousselGit** [comment]
Eh thanks a lot, will fix

**Comment by rrousselGit** [comment]
Done, thanks again!
