### ISSUE TITLE
The argument type 'AutoDisposeStreamProvider<Set<String>>' can't be assigned to the parameter type 'ProviderListenable<Set<String>>'.

### ISSUE THREAD

**Issue by MyElementApps** [rrousselGit/river_pod#1024]
Hello,

I am new to RiverPod and a beginner in Flutter/Dart. I am trying to use a `StreamProvider` from RiverPod for a paginated set of simple objects. When trying to watch my created StreamProvider, I get this build error (here for a simple example with a String object):
`The argument type 'AutoDisposeStreamProvider<Set<String>>' can't be assigned to the parameter type 'ProviderListenable<Set<String>>'.`

I am using flutter_riverpod 1.0.3, Flutter 2.8.1 and Dart 2.15.1.

### Simple Example Code:

Paginator from a local source, in this case simply a set of Strings with the value "Test  $pageIndex".

```
import 'dart:async';

class Paginator {
  final controller = StreamController<int>();
  final _previousResults = <String>{};

  late Stream<Set<String>> resultStream;

  int page = 0;

  Paginator() {
    resultStream = controller.stream.asyncMap((int pageIndex) async {
      return next(pageIndex);
    });
  }

  Future<Set<String>> next(int pageIndex) async {
    try {
      page++;

      final latestResults = await _fetchNext(pageIndex);
      _previousResults.addAll(latestResults);

      return _previousResults;
    } catch (exception) {
      page--;

      rethrow;
    }
  }

  Future<Set<String>> _fetchNext(int pageIndex) async {
    await Future.delayed(const Duration(seconds: 2));

    return {"Test $pageIndex"};
  }
}
```

The providers to access the Paginator and to provide the StreamProvider. These Providers as well as the Paginator are based on this [Reddit post](https://www.reddit.com/r/flutterhelp/comments/q2723t/how_to_use_riverpod_streamprovider/).

```
import 'package:flutter_riverpod/flutter_riverpod.dart';

final paginatorProvider = Provider((ref) => Paginator());

final pageStreamProvider = StreamProvider.autoDispose(
  (ref) => ref.watch(paginatorProvider).resultStream,
);
```
The build errors appear with and without the autoDispose modifier.

The Widget is separated in a ConsumerStatefulWidget and ConsumerState, the same error happens also in ConsumerWidget.

```
import 'package:flutter/src/widgets/framework.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

class Widget extends ConsumerStatefulWidget {
  @override
  _State createState() => _State();
}

class _State extends ConsumerState<Widget> {
  var _set = <String>{};

  @override
  Widget build(BuildContext context) {
    _set = ref.watch(pageStreamProvider);

    return Widget();
  }
}
```

I hope you can help me and show me what I have implemented wrong.

Furthermore, it would be very helpful for me to hear, whether you think a FutureProvider would have been maybe the better option here instead and why? I saw this [Twitter post](https://twitter.com/remi_rousselet/status/1307728661169266692/photo/1) of @rrousselGit but was unsure on how to implement this for a local list without the Dio package, I assume that I would still need the Paginator class here.

Thanks!

**Comment by rrousselGit** [comment]
The error you have is, `ref.watch(pageStreamProvider)` returns an `AsyncValue<Set<String>>`, yet you're trying to assign that to a `Set<String>`

Try:

```dart
ref.watch(pageStreamProvider).when(
  loading: ...,
  error: ...,
  data: (pages) => _set = pages,
)
```

**Comment by MyElementApps** [comment]
Ah, a rookie mistake of mine. Thanks a lot!
