### ISSUE TITLE
Clarification on how to use StateNotifierProvider without Freezed

### ISSUE THREAD

**Issue by bagintz** [rrousselGit/river_pod#1025]
In the example of using select to filter rebuilds (https://riverpod.dev/docs/concepts/reading#using-select-to-filter-rebuilds), it would be helpful to see how the Provider handling the User object would update the `name` value using the state_notifier package, but without using the freezed package.  It seems like the only way to do this using a StateNotifer is to create a new User() object and to assign all the values, which seems to be a lot of code for a small update.

```
class UserController extends StateNotifier<User> {
  AppController() : super(User());

  void updateUserName(String newName) {
    var temp = User();
    temp.age = state.age;
    //Insert new code here any time the User class changes???
    temp.name = newName;
    state = temp;
  }
}
```

**Comment by rrousselGit** [comment]
You should define a clone method on your object

```dart
class User {
...

  User copyWith({String? name, int? age}) {
    return User(name: name ?? this.name, age: age ?? this.age);
  }
}
```


then do

```dart
state = state.copyWith(name: newName);
```
