### ISSUE TITLE
powerful package but too difficult to learn: trying to have persistent user state using shared preferences

### ISSUE THREAD

**Issue by giacomok** [rrousselGit/river_pod#1026]
This package seems amazing, but I spent all day trying to figure out howto do something I did with redux easily, without successing.

I need to have a persistent user state (I use shared_preferences, while there is flutter_redux for redux) that I reload in splash screen anytime I start the app.

I read everything I found out on the web (StateNotifierProvider with AsyncValue are my last discover), but I am not still able to code it. I am sure it's me, but imho the learning curve is too high.

**Comment by iamarnas** [comment]
> This package seems amazing, but I spent all day trying to figure out howto do something I did with redux easily, without successing.

If you can not do it with Riverpod then it is not true that you can do it with Redux 🙂

@giacomok

**Comment by giacomok** [comment]
@iamarnas I didn't say that, at all

**Comment by gustav3d** [comment]
Can you share your code ?, i could try to help you.

**Comment by giacomok** [comment]
What I tried is:

- I have a `User` model I want to use to save state
- I created `Authentication` StateNotifier (definied as `StateNotifier<User>`)
- I created a StateNotifiedProvider in this way:

```
    final authenticationProvider = StateNotifierProvider<Authentication, User>((ref) {
            return Authentication(User.fromZero()); // <-- HERE I need to get info from sharedpreferences
    });
```

In the splash screen I need to get the state from sharedpreferences and create a User model from that (and using with provider).  
What I am using right now is:

```
void _initApp() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    final _authentication = Authentication(User.fromSharedPreferences(prefs));
}
```
I do not know howto "pass" this object to provider.

**Comment by esDotDev** [comment]
This is oddly cludgy, but I think the recommended approach is something like:
```dart
final userProvider = Provider<User>((_) => User.fromZero());

final authenticationProvider = StateNotifierProvider<Authentication, User>((ref) {
            return Authentication(ref.watch<User>());
    });

void main() {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    runApp(ProviderScope(overrides: [
       userProvider.overrideWithProvider(Provider((_) 
            => User.fromSharedPreferences(prefs)))], child: MyApp()));
}
``` 
More here: https://github.com/rrousselGit/river_pod/issues/329

**Comment by richardjharris** [comment]
Hello,

https://github.com/bizz84/starter_architecture_flutter_firebase is a very good starter project that uses Riverpod and FirebaseAuth. Even if you use your own authentication code, you could probably copy the way they do the login/onboarding as it is quite good. There is also code that uses shared preferences.
