### ISSUE TITLE
How to avoid provider new instance and still listen to changes

### ISSUE THREAD

**Issue by RobinLbt** [rrousselGit/river_pod#1027]
I have a StreamProvider exposing the Firebase Auth stream and an exposed DataService waiting for the stream first value and then using it to make Firestore operations:

```dart
final userProvider =
    StreamProvider<User?>((ref) => ref.watch(authProvider).authStateChanges);

final dataProvider = ChangeNotifierProvider<DataService>((ref) {
  final dataService = DataService();
  dataService.initDataService(null);
  ref.watch(userProvider).whenData(
    (user) {
      dataService.updateAuthState(user);
    },
  );
  return dataService;
});
```

Unfortunately, the code is not working well because a DataService() instance is recreated every time the user state changes (log out, log in)

How can I still listen to the stream initial and current value, updating the DataService without recreating a new instance?

**Comment by rrousselGit** [comment]
It looks like you're confused about what `whenData` does. It's not a `.then`, it's not "listening" to something.

Use `ref.listen` instead:

```dart
ref.listen<AsyncValue<User?>>(userProvider, (previousUser, newUser) {
  newUser.when(
    loading: () {},
    error: (err, stack) {},
    data: dataService.updateAuthState,
  );
});
```
