### ISSUE TITLE
Simplifying family params

### ISSUE THREAD

**Issue by oodavid** [rrousselGit/river_pod#1028]
**Is your feature request related to a problem? Please describe.**

I don't like having to pass props everywhere to access family providers.

# What I know, and use:

There are pros and cons to each of these, I'm sure you're aware of both.

<details>
<summary>
1. With Riverpod I have to pass params down (boo)

_This gets tiresome, especially as the widget tree grows_
</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

class MyParams {
  MyParams({
    required this.jobId,
    required this.reportId,
    required this.sectionKey,
  });
  final String jobId;
  final String reportId;
  final String sectionKey;
}

class MyClass extends ChangeNotifier {
  MyClass({
    required this.params,
  }) {
    computedValue = 'Depends on params';
  }
  MyParams params;
  late String computedValue;
}

final myClassProvider =
    ChangeNotifierProvider.family<MyClass, MyParams>((ref, params) {
  return MyClass(params: params);
});

class MyRoute extends ConsumerWidget {
  const MyRoute({
    Key? key,
    required this.params,
  }) : super(key: key);

  final MyParams params;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // This route has access to the param, easy
    final myClass = ref.watch(myClassProvider(params));
    return Column(
      children: [
        // Access the MyClass instance
        Text(myClass.computedValue),
        // Pass params down my widget tree. ugh
        DeeplyNestedChild(params: params),
      ],
    );
  }
}

class DeeplyNestedChild extends ConsumerWidget {
  const DeeplyNestedChild({
    Key? key,
    required this.params,
  }) : super(key: key);

  final MyParams params;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final myClass = ref.watch(myClassProvider(params));
    return Text('Nested also ${myClass.computedValue} - pass them down!');
  }
}
```
</details>

<details>
<summary>
2. With Provider, nested widgets don't need params

_We create MyClass with params, then access directly via its type_
</summary>

```dart
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

class MyParams {
  MyParams({
    required this.jobId,
    required this.reportId,
    required this.sectionKey,
  });
  final String jobId;
  final String reportId;
  final String sectionKey;
}

class MyClass extends ChangeNotifier {
  MyClass({
    required this.params,
  }) {
    computedValue = 'Computed Value Depends on Params';
  }
  MyParams params;
  late String computedValue;
}

class MyRoute extends StatelessWidget {
  const MyRoute({
    Key? key,
    required this.params,
  }) : super(key: key);

  final MyParams params;

  @override
  Widget build(BuildContext context) {
    // Create the provider with the params
    return ChangeNotifierProvider.value(
      value: MyClass(params: params),
      child: Column(
        children: [
          // Access the MyClass instance
          Builder(builder: (context) {
            final myClass = context.watch<MyClass>();
            return Text(myClass.computedValue);
          }),
          // No need to pass params down
          const DeeplyNestedChild(),
        ],
      ),
    );
  }
}

class DeeplyNestedChild extends StatelessWidget {
  const DeeplyNestedChild({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final myClass = context.watch<MyClass>();
    return Text(
      '${myClass.computedValue} - no need to pass params down!',
    );
  }
}
```
</details>

# What I'd love to see:

I'd love to be able to access Providers without having to pass params everywhere because it's needed by `family`.

What I've concluded, is that I'd like to take advantage of the riverpods re-compute logic in order to modify other, simpler providers. Something like this:

```dart
final myClassProvider = ChangeNotifierProvider<MyClass>((ref) {
  return MyClass();
});

final dataProvider = StreamProvider.family<SomeData, Params>((ref, params) {
  return SomeDataStream(params);
});

final filterProvider = StateProvider<Filter>((ref) => Filter.all);

final myProviderLogic =
    ProviderLogic.family<MyParams>((ref, params) {
  // There may be a lot of providers here
  final data = ref.watch(dataProvider(params));
  final filter = ref.watch(filterProvider);
  // Perform logic here
  final results = blah(myData, myFilter);
  // Modify the provider
  final myClass = ref.read(myClassProvider);
  myClass.results = results; 
});
```

What I'd like to do is:

1. Use `ref.run(myProviderLogic(params))` in my root widget
2. Use `ref.watch(myClassProvider())` in my nested widgets

**Comment by TimWhiting** [comment]
This is already possible using nested provider scoping and overrides:

<details>
<summary>
With families:
You just create a provider that provides the family argument and override it for the subtree. - No parameter passing necessary
</summary>
```dart
/// A simple Todo class
class Todo {
  Todo(this.todo);
  final String todo;
}
/// Provides a list of [Todo]s.
final todoListProvider = StateProvider<List<Todo>>(
    (ref) => [Todo('this'), Todo('that'), Todo('the other')]);
/// Provides the index for a todo in a particular portion
/// of the widget tree
final todoItemIndexProvider = Provider<int>((ref) =>
    throw UnimplementedError('Todo index not set'));
/// Widget for the whole todo list
class TodoListWidget extends ConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final length = ref.watch(todoListProvider.select((list) => list.length));
    print('Build List');
    return ListView.builder(
      itemCount: length,
      itemBuilder: (context, index) {
        // Overrides the todoItemIndexProvider
        // for everything below this in the tree
        return ProviderScope(
          overrides: [
            todoItemIndexProvider.overrideWithValue(index),
          ],
          // Using this approach, TodoWidget can now be constant
          // since no index needs to be passed down
          child: const TodoWidget(),
        );
      },
    );
  }
}
/// Provides a single todo, so you can watch them individually
///
/// This way you will only be notified if the particular todo you
/// were watching was updated
final todoProvider = Provider.family<Todo, int>(
    (ref, index) => ref.watch(todoListProvider).state[index]);
/// A widget to show a single todo
class TodoWidget extends ConsumerWidget {
  const TodoWidget();
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // Gets the index of this particular Todo
    final index = ref.watch(todoItemIndexProvider);
    print('Building Item $index');
    // Watches a single todo item
    final todoItem = ref.watch(todoProvider(index));
    // Display it!
    return Text(todoItem.todo);
  }
}
void main() {
  runApp(
    ProviderScope(
      child: MaterialApp(
        home: Scaffold(
          body: TodoListWidget(),
          floatingActionButton: Consumer(builder: (context, ref, child) {
            return FloatingActionButton(
              onPressed: () {
                ref
                    .read(todoListProvider)
                    .update((state) => [Todo('New Todo'), ...state.sublist(1)]);
              },
              child: Icon(Icons.add),
            );
          }),
        ),
      ),
    ),
  );
}
```
</details>

<details>
<summary>
Without families:
You just create a provider that listens to a provider that provides the arguments. Then override the provider that overrides the arguments directly. Each subtree will have a different instance of both providers.
</summary>
```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() {
  runApp(
    ProviderScope(
      child: MaterialApp(
        home: Scaffold(
          body: TodoListWidget(),
          floatingActionButton: Consumer(builder: (context, ref, child) {
            return FloatingActionButton(
              onPressed: () {
                ref.read(todoListProvider.notifier).update(
                      (state) => [
                        Todo('New Todo'),
                        ...state.sublist(1),
                      ],
                    );
              },
              child: Icon(Icons.add),
            );
          }),
        ),
      ),
    ),
  );
}

/// A simple Todo class
class Todo {
  Todo(this.todo);
  final String todo;
}

/// Provides a list of [Todo]s.
final todoListProvider = StateProvider<List<Todo>>(
    (ref) => [Todo('this'), Todo('that'), Todo('the other')]);

/// Provides the index for a todo in a particular portion
/// of the widget tree
final todoItemIndexProvider =
    Provider<int>((ref) => throw UnimplementedError('Provider Not Set'));

/// Widget for the whole todo list
class TodoListWidget extends ConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final length =
        ref.watch(todoListProvider.select((controller) => controller.length));
    print('Build List');
    return ListView.builder(
      itemCount: length,
      itemBuilder: (context, index) {
        // Overrides the todoItemIndexProvider
        // for everything below this in the tree
        return ProviderScope(
          overrides: [
            todoItemIndexProvider.overrideWithValue(index),
            todoProvider
          ],
          // Using this approach, TodoWidget can now be constant
          // since no index needs to be passed down
          child: const TodoWidget(),
        );
      },
    );
  }
}

/// Provides a single todo based on the todoItemIndexProvider
final todoProvider = Provider<Todo>(
    (ref) => ref.watch(todoListProvider)[ref.watch(todoItemIndexProvider)]);

/// A widget to show a single todo
class TodoWidget extends ConsumerWidget {
  const TodoWidget();
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // Watches a single todo item
    final todoItem = ref.watch(todoProvider);
    // Display it!
    return Text(todoItem.todo);
  }
}
```
</details>

**Comment by oodavid** [comment]
Amazing, thank you. I'll put that into action tomorrow and close once I'm happy.

I use overrides in my main method, didn't think to use it here. I can see that being a great approach for my per-screen providers.

**Comment by oodavid** [comment]
In your second example, why do you need to include dependencies:?

```
/// Provides a single todo based on the todoItemIndexProvider
final todoProvider = Provider<Todo>(
    (ref) => ref.watch(todoListProvider)[ref.watch(todoItemIndexProvider)],
     dependencies: [todoListProvider, todoItemIndexProvider]
);
```

**Comment by rrousselGit** [comment]
Listing `dependencies` tell riverpod to automatically scope the provider when one of its dependencies is overridden

**Comment by oodavid** [comment]
Thanks both.

NGL, I'm still struggling with a few of the concepts in Riverpod. It's a fairly steep learning curve, even coming from Provider. A few follow-up-questions:

1. What is automatic scoping?
2. How is it related to overrides?
3. Why do we need it here?

**Comment by rrousselGit** [comment]
Provider has the same issue, it's just that providers aren't very easily composable like with Riverpod, so they don't even try to use this solution.

Say you were using provider instead of riverpod and did:


```dart
Provider<int>(
  create: (ctx) => 0,
  child: Provider<String>(
    create: (ctx) => ctx.read<int>().toString(),
    child: ...
  ),
)
```

then inside a page you did:

```dart
return Provider<int>.value(
  value: 42,
  child: Builder(builder: (context) {
    print(context.read<String>());
  }
)
```

The expected behavior would be to print `42`, but the actual behavior is that it's going to print `0`.

The reasoning is, while `Provider<int>` was scoped and the previously defined `Provider<String>` depends on `Provider<int>`, the string provider is higher in the hierarchy than the scoped int provider. So the string provider has access to the non-scoped integer



The same thing would happen in Riverpod if you removed this `dependencies`.

Automatic scoping means that when `Provider<int>` is scoped, the string provider will be scoped too such that it now has access to the new int.

**Comment by oodavid** [comment]
Thanks, I'm still learning - I'll sit on this for a while and see how it shakes out.

**Comment by oodavid** [comment]
OKAY, I've implemented these changes, it's working correctly. V. good so far.

However, in doing so, I'm having to list more dependencies than I'd expect. A little hard to type out, so I've recorded a quick video:

[Video - Riverpod - dependencies everywhere?](https://www.loom.com/share/2fc2205661034646b56f17872cc4652b)

PS: I'm sponsoring now :)

**Comment by rrousselGit** [comment]
> PS: I'm sponsoring now :)

Thanks :heart:

> However, in doing so, I'm having to list more dependencies than I'd expect

This is in fact expected.

The reason is, while you did not override the direct dependency of those providers, you did override a transitive dependency

You basically have a tree, such that:

```dart
final a = Provider(() = throw)

final b = Provider((ref) => ref.watch(a), dependencies: [a]);

final c = Provider((ref) => ref.watch(b), dependencies: [b]);
```



So if you're overriding `a`, you need to also override `b` (as mentioned in my previous message) – which `dependencies` does for you. All fine so far.  
But the thing is, now `b` is overridden too, so for the same reason, `c` needs to be overridden since it's depending on `b` which depends on `a`

It's a bit cumbersome, but a necessary step. 

Always listing `dependencies` like you're suggesting "You're almost considering" is fine. There's nothing wrong with that besides the boilerplate (and that's it's a bit error-prone, as it's easy to forget to list one dependency).


Do keep in mind though that once Dart has metaprogramming (code-generation build in the language), this `dependencies` variable will be automatically generated for you, so that boilerplate will go away.

**Comment by oodavid** [comment]
Got it.

I'll see if I can trim out the transitive dependencies by using a family parameter instead of using an overridden provider.

Assuming [metaprogramming](https://github.com/dart-lang/language/issues/1482) is available, how do you expect Riverpod will change? Will you default to the behaviour we're discussing, have a boolean flag (`scoped: true`), or something else?

**Comment by rrousselGit** [comment]
With Metaprogramming, Riverpod will always fill that "dependencies" list.

Specifying this param is never bad if it's automatically generated.

The syntax for defining providers will likely change a bit though, but I'll share more about that at a later date

**Comment by HaijunWei** [comment]
So whether the combination provider should always specify dependencies, the documentation does not explain this, I am very confused.

**Comment by shilangyu** [comment]
Has anything changed in this space in the past 2 years? Having to create these auxiliary providers just to be able to have reasonable DX with scoped providers is very cumbersome.
