### ISSUE TITLE
Preserve AsyncData/AsyncError between provider rebuild

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/river_pod#1036]
An issue when using FutureProvider combined with ref.watch is, when the provider rebuilds, for a the state will go back to "loading"

This is undesired, as the expected behavior would be to keep seeing the old data/error until the new state is obtained

**Comment by rrousselGit** [comment]
This would be a solution to #930 

The idea being, instead of accessing the previous data/error from a loading state, we wouldn't have a loading state to begin with but rather the data/error directly.

And those data/error states would contain an "isRefreshing" flag, which would help determine that a provider is being rebuilt

**Comment by rrousselGit** [comment]
Implemented in e71fd3811f8b6e2903898e327825de6b14087b0d

**Comment by oodavid** [comment]
Does this solve #471 too?
