### ISSUE TITLE
How to perform .when for multiple providers?

### ISSUE THREAD

**Issue by oodavid** [rrousselGit/river_pod#1041]
`AsyncData.when` is great for single provider values:

```dart
@override
Widget build(BuildContext context, WidgetRef ref) {
  final data = ref.watch(dataProvider);
  return data.when(
    loading: () => const CircularProgressIndicator(),
    error: (err, stack) => Text('$err'),
    data: (data) {
      return Text('We have data!');
    }
  )
}
```

But how should we render that state with multiple providers?

```dart
@override
Widget build(BuildContext context, WidgetRef ref) {
  final a = ref.watch(dataProviderA);
  final b = ref.watch(dataProviderB);
  final c = ref.watch(dataProviderC);
  // How to render a.when AND b.when AND c.when ?
}
```

I can think of a few approaches, they all feel boilerplatey:

## 1 - Nesting

```dart
@override
Widget build(BuildContext context, WidgetRef ref) {
  final a = ref.watch(dataProviderA);
  final b = ref.watch(dataProviderB);
  final c = ref.watch(dataProviderC);
  return a.when(
    loading: () => const CircularProgressIndicator(),
    error: (err, stack) => Text('$err'),
    data: (a) {
      return b.when(
        loading: () => const CircularProgressIndicator(),
        error: (err, stack) => Text('$err'),
        data: (b) {
          return c.when(
            loading: () => const CircularProgressIndicator(),
            error: (err, stack) => Text('$err'),
            data: (c) {
              return Text('We have a, b and c!');
            }
          );
        }
      );
    }
  );
}
```

## 2 - A new provider and data model

This would really start to sprawl when the providers use `.family` and have complex params as we'd need an `ParamsABC` class to wrap the params.

```dart
class ModelABC{
  ModelABC({
    required this.a,
    required this.b,
    required this.c,
  })
  ModelA a;
  ModelB a;
  ModelB a;
}
final dataProviderABC = Provider<ModelABC>((ref) {
  final a = ref.watch(dataProviderA);
  final b = ref.watch(dataProviderB);
  final c = ref.watch(dataProviderC);
  if(a != null && b != null && c!= null){
    return ModelABC(a: a, b: b, c: c);
  }
});
@override
Widget build(BuildContext context, WidgetRef ref) {
  final data = ref.watch(dataProviderABC);
  return data.when(
    loading: () => const CircularProgressIndicator(),
    error: (err, stack) => Text('$err'),
    data: (data) {
      return Text('We have a, b and c!');
    }
  )
}
```

## 3 - Something else

Below I am proposing a `MultiWhen` widget that accepts a List of providers, and acts in a smilar way to `AsyncData.when`.

```dart
@override
Widget build(BuildContext context, WidgetRef ref) {
  final a = ref.watch(dataProviderA);
  final b = ref.watch(dataProviderB);
  final c = ref.watch(dataProviderC);
  return MultiWhen(
    [a, b, c],
    loading: () => const CircularProgressIndicator(),
    error: (err, stack) => Text('$err'),
    data: (/* Params TBD */) {
      return Text('We have a, b and c!');
    }
  );
}
```

There's an implementation decision to make around the `.data` signature:

* It supplies no parameters.
  _Use `a.value!` etc. as they're still in scope_
* It supplies an array matching the input params
  _Use `final a = data[0]`_
* Both of the above
  _We can choose to ignore the array_
* Something similar to [ProxyProvider2](https://pub.dev/documentation/provider/latest/provider/ProxyProvider2-class.html) ... [ProxyProvider6](https://pub.dev/documentation/provider/latest/provider/ProxyProvider6-class.html)
  _Personally I've never liked these_
* Something else

My preference would be to have no params returned. Keeps it simple.

**Comment by rrousselGit** [comment]
This is a known issue, so I'll close this is favor of the existing one https://github.com/rrousselGit/river_pod/issues/67

The fact is that I'm not satisfied with any of the possible solution. So I'm still searching for a different possibility
