### ISSUE TITLE
Widget rebuild (useProvider) not triggered in profile or release build, but works in debug mode

### ISSUE THREAD

**Issue by funwithflutter** [rrousselGit/river_pod#105]
**Describe the bug**
Bit of weird issue. If you take the example Todo app, do a debug build then no issue. But on profile/release the
```dart
final todo = useProvider(_currentTodo);
```
does not trigger a rebuild in the TodoItem widget when you check/uncheck an item (checkbox).

**To Reproduce**

Use the example Todo app and build to profile or release. Error occurred on an Android build (not tested on iOS). No changes made to the example. In the picture below, you can see one item is left, however, none of the items are checked. If you navigate to a different filter and back a build is forced and the items will then be checked.

![todoapp_error](https://user-images.githubusercontent.com/45597490/91633666-7916bc00-ea14-11ea-9802-27a36249399a.jpg)

I attempted to isolate the issue by creating a stripped down version of the example, but I couldn't reproduce the issue. Guessing it's something with ScopedProvider or overrideWithValue.

**Expected behavior**
Expect the TodoItem widget to rebuild when filteredTodos updates, forcing the checkbox to update its status.

**Comment by rrousselGit** [comment]
What version are you using? This was fixed in 0.7.1

**Comment by funwithflutter** [comment]
Sorry was on 0.7.0 😅. I should learn to read closed issues. Thanks for the quick response.
