### ISSUE TITLE
Change in Provider doesn't trigger rebuild

### ISSUE THREAD

**Issue by samderlust** [rrousselGit/river_pod#1050]
**Describe the bug**
I have a `Provider` that watch change of a attribute in  `StateNotifier`. Using `ProviderObserver` I still see the change in state. But it does not trigger rebuild in my widget build method which I use `ref.watch`.
But if I change from `Provider` to `StateProvider`, rebuild is trigger.

**To Reproduce**
my providers
```
final selectedAppointment = Provider<Appointment?>((ref) {
  final aptState = ref.watch(appointmentProvider);
  return aptState.appointments[aptState.selectedAppointment];
});

final appointmentProvider =
    StateNotifierProvider<AppointmentNotifier, AppointmentState>(
  (ref) => AppointmentNotifier(ref.read),
);
```
my state
```
class AppointmentState with _$AppointmentState {
  factory AppointmentState({
    @Default({}) Map<String, Appointment> appointments,
    String? selectedAppointment,
    DateTime? selectedDate,
    @Default(false) bool isLoadingAppointment,
  }) = _AppointmentState;
}

```
my model
```
class Appointment with _$Appointment {
  factory Appointment({
    required String id,
    DateTime? time,
    String? technicianId,
    String? customerId,
    @Default({}) Set<String> services,
    String? storeId,
  }) = _Appointment;
````

in my Widget 
```    final appointment = ref.watch(selectedAppointment);```

change in `selectedAppointment` does not trigger rebuild

If I change to 

```

final selectedAppointment = StateProvider<Appointment?>((ref) {
  final aptState = ref.watch(appointmentProvider);
  return aptState.appointments[aptState.selectedAppointment];
});
```
rebuild trigger

flutter 2.5.3
```

environment:
  sdk: ">=2.12.0 <3.0.0"

  hooks_riverpod: ^1.0.2
```

**Comment by rrousselGit** [comment]
`Provider` filter rebuilds if the new value returned is == to the previous one, when `StateProvider` does not.

That's most likely your issue.

**Comment by samderlust** [comment]
That's what I think of too. The only change that I make is removing an item from the `Set` of `services` in the model. 

I've just tried again with a different way to "purely" remove the item. and Provider works. 
Thanks for your response
