### ISSUE TITLE
StreamProvider<int> behaves unexpected compared to Provider<Stream<int>>

### ISSUE THREAD

**Issue by jeduden** [rrousselGit/river_pod#1059]
**Describe the bug**
I expect StreamProvider to provide a stream that is equivalent to the wrapped stream, but the returned stream is not done when the inner stream ends.

**To Reproduce**
Run these three unit-tests:

```dart
import 'dart:async';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
    final ProviderContainer ref = ProviderContainer();
    test("stream test via streamprovider", () async {
      final sProvider = StreamProvider<int>((_) async* {
        yield 1;
        yield 2;
        yield 3;
      });
      final s = ref.read(sProvider.stream);
      await expectLater(s, emitsInOrder([equals(1),equals(2),equals(3),emitsDone]));
    });
    test("stream test via streamprovider without emitsDone", () async {
      final sProvider = StreamProvider<int>((_) async* {
        yield 1;
        yield 2;
        yield 3;
      });
      final s = ref.read(sProvider.stream);
      await expectLater(s, emitsInOrder([equals(1),equals(2),equals(3)]));
    });
    test("stream test via provider", () async {
      final sProvider = Provider<Stream<int>>((_) async* {
        yield 1;
        yield 2;
        yield 3;
      });
      final s = ref.read(sProvider);
      await expectLater(s, emitsInOrder([equals(1),equals(2),equals(3),emitsDone]));
    });
}
```

"stream test via streamprovider" times out, while "stream test via provider" and "stream test via streamprovider without emitsDone" pass.

**Expected behavior**

"stream test via streamprovider"  should pass.

**Comment by rrousselGit** [comment]
`.stream` does not return the original stream. It returns a new stream that won't emit a `done` until the provider is closed.

**Comment by jeduden** [comment]
Ok. good to know ! I missed that piece of information in the documentation.

**Comment by rrousselGit** [comment]
The dartdoc of ".stream" mentions that the stream obtained is different from the stream created

**Comment by jeduden** [comment]
@rrousselGit It would be great if the docs could express that  `done` is handled differently by the stream that is returned.
currently the docs only mention that the stream is different, in the sense that it is a broadcast stream.
