### ISSUE TITLE
Best scenario for paged chat based on Firestore streams

### ISSUE THREAD

**Issue by arnoutvandervorst** [rrousselGit/river_pod#106]
**Describe what scenario you think is uncovered by the existing examples/articles**
Currently have a chat app using paging to get first 10 messages and based on a scrollcontroller get 10 more every time. This uses a streambuilder setup and I can't figure out how to properly convert this to a provider setup, can you help?

My current setup, if you can give me a hint on how to approach I'd be very happy!

`class GroupMessagePage extends StatefulHookWidget {
  final String groupId;
  final String groupName;

  GroupMessagePage({
    Key key,
    @required this.groupId,
    @required this.groupName,
  }) : super(key: key);

  @override
  _GroupMessagePageState createState() => _GroupMessagePageState();
}

class _GroupMessagePageState extends State<GroupMessagePage> {
  ScrollController _scrollController;
  Stream<List<GroupMessage>> _groupMessagesStream;
  int _documentLimit;

  @override
  void initState() {
    super.initState();

    _documentLimit = groupMessagesFetchLimit;
    _getDocuments();

    _scrollController = ScrollController();
    _scrollController.addListener(_scrollListener);
  }

  @override
  void dispose() {
    _scrollController.dispose();
    _groupMessagesStream = null;
    super.dispose();
  }

  void _scrollListener() {
    if (_scrollController.offset >=
            _scrollController.position.maxScrollExtent &&
        !_scrollController.position.outOfRange) {
      _documentLimit = _documentLimit + groupMessagesFetchLimit;
      _getDocuments();

      setState(() {
        Util.showShortToast('Ophalen nieuwe berichten');
      });
    }
  }

  void _getDocuments() {
    _groupMessagesStream = GroupMessages().streamList(
      widget.groupId,
      _documentLimit,
    );
  }

  @override
  Widget build(BuildContext context) {
    final _user = useProvider(ExtendedUser.current);
    final _groupsUpdatedFor =
        useProvider(ExtendedUser.groupsUpdatedFor(_user.uid));

    final _groupsUpdatedForScoped =
        _groupsUpdatedFor.where((g) => g.id == widget.groupId).toList();

    if (_groupsUpdatedForScoped.isNotEmpty) {
      GroupMessages().markAsRead(
        widget.groupId,
        _user.uid,
      );
    }

    return CustomScaffold(
      title: widget.groupName,
      padding: EdgeInsets.zero,
      body: Column(
        children: <Widget>[
          Expanded(
            child: StreamBuilder<List<GroupMessage>>(
              stream: _groupMessagesStream,
              builder: (BuildContext context, AsyncSnapshot snapshot) {
                final _groupMessages = snapshot.data;

                if (_groupMessages == null) {
                  return Splash();
                }

                return ListView.builder(
                  controller: _scrollController,
                  padding: AppTheme.defaultBodyPadding,
                  itemCount: _groupMessages.length,
                  reverse: true,
                  itemBuilder: (BuildContext context, int index) {
                    final _groupMessage = _groupMessages[index];
                    return GroupMessageWidget(
                      groupMessage: _groupMessage,
                    );
                  },
                );
              },
            ),
          ),
          Padding(
            padding: const EdgeInsets.only(bottom: 10.0),
            child: GroupMessageInputWidget(
              groupId: widget.groupId,
            ),
          ),
        ],
      ),
    );
  }
}`

**Comment by rrousselGit** [comment]
There's already an example using pagination https://github.com/rrousselGit/river_pod/blob/06b4a4fb8063c44280bf774170a867662397c74e/examples/marvel/lib/src/screens/home.dart#L27

It's using families. You can read about it here https://riverpod.dev/docs/concepts/modifiers/family
