### ISSUE TITLE
re.onDispose() getting called twice in .autoDispose provider

### ISSUE THREAD

**Issue by PSanJuanS** [rrousselGit/river_pod#1064]
**Describe the bug**
I've found that the ref.onDIspose() method is getting called twice in my .autoDispose provider. I'm not sure if that is a bug or an expected behaviour.  Provider version 1.0.3.

**To Reproduce**

The snippet below is a `stateNotifierProvider` that Provides a ViewModel which is a `StateNotifier<EditorState>`. `EditorState` is a `Freezed` sealed union.

```
final viewModelProv =
    StateNotifierProvider.autoDispose<ViewModel, EditorState>((ref) {
  final navState = ref.watch(NavProv);
  final item = navState.whenOrNull(view: (item) => item);
  final notifier =  ref.watch(tNavProv.notifier);
  ref.onDispose(() {
    print("disposing viewModelProv");
   notifier.viewItem(pageActive: false);
  });

  return ViewModel(ref.read, item!);
});
```
Here the provider watches another `StateNotifierProvider` `NavProv` which is another `freezed` sealed union to obtain the `Item` contained in one of its states to create the ViewModel. This provider is only watched by UI created when `NavProv` state is on view state, so Item is never null. The function `notifier.viewItem(pageActive: false)` changes `NavProv` state from `NavState.view(Itrem) `to `NavState.list() `(another state).

When the UI watching the `viewModelProv` gets removed, `onDispose` gets called twice resulting in:

`Bad state: Tried to use ViewModel after `dispose` was called.`

**Probably my problem is that the function executed in onDispose() changes the state of NavProv( a StateNotifier watched by the viewModelProv) and maybe I shouldn't do that.**

If i should be able to do that without an error,  i will extract a minimaal  example to reproduce.

**Expected behavior**
After my UI widget exits the widget tree the viewModelProv gets disposed and the NavProv state is `navState.list()` with no errors.

**Comment by rrousselGit** [comment]
Thanks for the report. I'll need a proper way to reproduce the issue though, otherwise it'll be very difficult for me to find out what the problem is.

**Comment by PSanJuanS** [comment]
Thank you for your response @rrousselGit  and sorry for the delay.
Find in this link a minimal working proyect showing the issue:
https://gitlab.com/P.SanJuan/riverpodissue1064

To simplify the code I removed all the freezad sealed unions and used simple types in the statenotifiers. The code producing the errors is the onDispose of the provider in viewModel.dart.

Steps to reproduce, execute the app, press navigate to item, then press back button or back arrow in the appbar. You will get:
` Unhandled Exception: Bad state: Tried to use ViewModel after `dispose` was called.`

If you comment lines 10 and 14 of viewModel.dart and uncomment line 13, you get instead:
` Failed assertion: line 645 pos 7: '_debugDidChangeDependency == false': Cannot use ref functions after the dependency of a provider changed but before the provider rebuilt`

Both errors are expresions of the onDispose being called twice.

Thank you in advance.

**Comment by sperochon** [comment]
Hi,

I don't know if that's the same issue that I had but it appeared that in my project, I was using an autodispose provider and was calling in initState
`ref.read(provider.notifier).mymethod()`
and not calling immediately
`ref.watch(provider)`
in the build method

And since mymethod make an async call to my DB, it lets time to the autodispose to destroy the first provider (since nobody listen to it) and then after recreate another one when it arrives on the watch.

I lost few hours to debug this...

You can print the hashCode of objects (provider, ...) to see if they are the same.

If it helps...

**Comment by PSanJuanS** [comment]
@sperochon  it's not the same issue, I'm not calling any provider methods in initstate. Im using only stateless widgets.

**Comment by PSanJuanS** [comment]
@rrousselGit could you test my minimal example?

**Comment by rrousselGit** [comment]
Thanks for the example, I can reproduce the issue. I'll investigate and try to fix it this week-end.

**Comment by PSanJuanS** [comment]
Thank you @rrousselGit

**Comment by PSanJuanS** [comment]
Great, thank you Remi
