### ISSUE TITLE
Add ref.listenSelf

### ISSUE THREAD

**Issue by tbm98v3** [rrousselGit/river_pod#1079]
**Is your feature request related to a problem? Please describe.**
I'm having a StateProvider and I want to know when its value changed.

**Describe the solution you'd like**
Add a callback called `onChanged` to know when its value changed.

**Describe alternatives you've considered**
Create another provider to watch it.

**Comment by Hamza-Imran75** [comment]
I think this is what you are after:

https://riverpod.dev/docs/concepts/reading/#using-reflisten-to-react-to-a-provider-change

**Comment by rrousselGit** [comment]
This is already a thing: ref.listen

**Comment by tbm98** [comment]
> 

Yes. Provider listen itself

**Comment by rrousselGit** [comment]
Fair enough. I'll probably name it "listenSelf" though

And add "refreshSelf" too

**Comment by tbm98** [comment]
Glad to see it. Thanks!

**Comment by gazialankus** [comment]
Do you remember why you decided not to implement refreshSelf? 

If I have a Notifier whose provider is only read and not watched, invalidateSelf would not actually force it to be rebuilt unless I do another read, right?

**Comment by rrousselGit** [comment]
Correct. Because that's generally how it's meant to behave

**Comment by gazialankus** [comment]
If we had refreshSelf though, it would be immediately rebuilt even if it's not watched or read. Could be useful when you would prefer to have the new state in the next line.

**Comment by rrousselGit** [comment]
Reading `ref.state` would trigger the rebuild anyway

**Comment by gazialankus** [comment]
Oh wow so this is what I want, right?

```
void refreshSelf() {
  invalidateSelf();
  state;
}
```

because of the `_element.flush()` in `get state`, I see. Didn't give it a try but makes sense. Thanks!
