### ISSUE TITLE
Add BuildContext parameter to ProviderListener#onChange

### ISSUE THREAD

**Issue by HeavenOSK** [rrousselGit/river_pod#108]
**Is your feature request related to a problem? Please describe.**
I have encountered several situations where I wanted to use BuildContext to show SnackBar on Scaffold in the same build method.

**Describe the solution you'd like**
I’d like to be able to access the BuildContext in the onChange method as follows.

```dart 
return  Scaffold(
      body: ProviderListener(
        provider: multipleOfTen,
        onChange: (BuildContext context, bool value) {
          if (value) {
            Scaffold.of(context).showSnackBar(
                SnackBar(content: Text('value is multiple of 10'),
            );
          }
        },
        child: Center(
          child: Text(count.toString()),
        ),
      ),
    );
```
( https://gist.github.com/HeavenOSK/fbe25f8472ea9f44b575343218c2c7ce )

**Comment by rrousselGit** [comment]
Done in #110
