### ISSUE TITLE
Add ref.attach/ref.detach

### ISSUE THREAD

**Issue by tbm98v3** [rrousselGit/river_pod#1081]
**Is your feature request related to a problem? Please describe.**
I have a `HomePage` that has a `Button`. when `HomePage` initState I call ref.read to update the value of `ButtonProvider`. But ButtonProvider is autoDispose so that disposed before Button can read value.

**Describe the solution you'd like**
I want to attach ref of `HomePage` to `ButtonProvider` to keep `ButtonProvider` alive along with `HomePage`.

**Describe alternatives you've considered**
Current. I am using ref.listen in the build method of `HomePage` to keep `ButtonProvider` alive, but I don't need to listen to its value.

**Comment by rrousselGit** [comment]
I don't like the idea

The only benefit this seem to have is to reduce the boilerplate by a negligible amount.

Using "ref.listen" here is fine IMO

**Comment by tbm98** [comment]
But use ref.listen. I always have to write a comment to explain for a listener but do nothing.

**Comment by rrousselGit** [comment]
You're free to make an extension:

```dart
typedef Detach = ...

extension on Ref {
  Detach attach(ProviderBase p) => listen(p, (_, __) {});
}
```

**Comment by tbm98** [comment]
Good idea.
I'll use extension for this case. Thanks!

**Comment by rrousselGit** [comment]
Nice! I'll close this then, as I don't plan on adding that to Riverpod yet and there's a workaround :)

**Comment by tbm98** [comment]
Hi @rrousselGit . I just tried but it now works because WidgetRef is not a subtype of Ref (use in Consumer widget).
is this work as expected or your mistake?

**Comment by tbm98** [comment]
and also. I got ProviderBase<T> can't be assigned to parameter type AlwaysAliveProviderListenable<T>
![Screen Shot 2022-01-25 at 07 44 44](https://user-images.githubusercontent.com/52562340/150889474-f078dea2-faab-49bd-a1dc-e6537645e499.png)

**Comment by scopendo** [comment]
I've had a similar issue a couple of times, where I want the provider to auto-dispose but not before navigation has had a chance to kick in.

For example, custom logic on screen A wants to wait for an async operation to load a dependency before navigating to screen B, where the loaded dependency is used.  This is particularly relevant when the "loading" UI should be shown on screen A, without any interim loading state shown on screen B.

```dart
onPressed: () {
  final navigator = Navigator.of(context);
  setState(() => processing = true);
  await ref.read(autoDisposingPod);
  navigator.pushNamed(ScreenB.routeName);  
}
```

This won't work with an `autoDispose` provider as the provider is disposed of before ScreenB gets a chance to watch the provider.  Of course, this can be worked around by not using an auto-disposing provider but that can result in too much memory being used, especially where the provider is part of a family.

It might be useful if we could specify a duration that Riverpod should wait before disposing of an auto-disposing provider that is no longer referenced.

**Comment by scopendo** [comment]
Just realised that this is closed.  Will raise a discussion instead.

**Comment by scopendo** [comment]
Added a related discussion for being able to wait before auto-disposing #1155
