### ISSUE TITLE
Choose type of error in AsyncError

### ISSUE THREAD

**Issue by DrgOv** [rrousselGit/river_pod#1084]
I think it would be nice to have a way to define your own type of error that AsyncError has. 

Right now, error is generic type Object and every time I want to do something with the error I have to cast it to my custom error.

Is there already a way, that I don't know about, to specify the error type or this is not currently possible?

**Comment by rrousselGit** [comment]
There's no way to do that with the Dart type system.
We're need union types to properly do that, which Dart does not have. 

Also keep in mind that if your code has an unexpected error, it likely wouldn't match the type of your custom errors
