### ISSUE TITLE
Exceptions while disposing provider aborts disposal of other providers in auto dispose queue

### ISSUE THREAD

**Issue by Sese-Schneider** [rrousselGit/river_pod#1086]
### **Describe the bug**
I found an issue while disposing providers. A provider wasn't disposed after the widget had been destroyed.

After digging deeper, I investigated [packages/riverpod/lib/src/framework/auto_dispose.dart](https://github.com/rrousselGit/river_pod/blob/af7a28a14754cf4443872c2832b262c1a9ea3a90/packages/riverpod/lib/src/framework/auto_dispose.dart)
(for newer versions: [packages/riverpod/lib/src/framework/scheduler.dart](https://github.com/rrousselGit/river_pod/blob/master/packages/riverpod/lib/src/framework/scheduler.dart)).

Debugging revealed, that the provider was correctly added to the `_stateToDispose` LinkedList.
In my case, the list was around 100 items long.

A provider which was _before_ the provider I cared about, threw an exception in `entry.value.container._disposeProvider` while disposing!
This caused the *whole loop* in `void _performDispose()` to abort, and subsequent disposals are effectively "canceled".

The execution resumed in the `finally` part of `void scheduleDispose`, **clearing** the disposal queue.
**Every provider after the faulty one will _never_ get disposed.**

<sub>By the way: Why is the disposal queue a `LinkedList`? Debugging is super painful and it took me ages to figure out the issue because of this :D</sub>

### **To Reproduce**

Until now, I wasn't able to create a MRS due to time constraints.
Multiple independant providers would have to be created, and disposal of one should throw an exception.

This will cause providers which are at a later point in the list not to be disposed of.

### **Expected behavior**
Every provider in the `_stateToDispose` LinkedList should be disposed, even if previous disposals fail and throw an exception.

I'm not sure if this behavior is intentional or a bug, because for sure there is a reason behin the `try-catch` of the disposal micotask.

My suggestion to fix this would be to wrap every `entry.value.container._disposeProvider(entry.value._origin);` in a seperate `try-catch`, to be able to continue the disposal of the `next` provider of the list.

**Comment by rrousselGit** [comment]
This is weird, because there should be no way for the dispose function to throw as errors are caught already (cd `runUnaryGuarded` & co)

Could you share the exception you got? that would help quite a bit.

**Comment by rrousselGit** [comment]
What `void dispose()` are you referring to? There's no such method publicly available on providers. Folks only have access to `ref.dispose` – which catches exceptions

**Comment by rrousselGit** [comment]
Gentle bump. Could you at least share me the exception+stacktrace that broke the dispose queue?

Because the only execution of `onDispose` callbacks is here: https://github.com/rrousselGit/river_pod/blob/e6084926e23fcfa522c2049674b01c4cb194d6de/packages/riverpod/lib/src/framework/provider_base.dart#L838

And that `runGuarded` catches any exception within the callback, so I'm at lost on what the problem you found is.

**Comment by Sese-Schneider** [comment]
@rrousselGit sorry for not answering sooner.
I'm having difficulties to create a minimal sample here.

Our app is quite large and the issue was caused by a `late StreamSubscription` not being initialized, and disposed of in the `@override void dispose()` part of a `ChangeNotifier`.

There was no stacktrace, which is the reason why it took ages for me to find the issue.
It might be an uderlying flutter issue where the `runGuarded` doesn't catch/log null and initialize related exceptions?

I can try to create a sample later this month, but this issue is primarily to notify you this bug occured.
I would be okay with you closing it.

**Comment by rrousselGit** [comment]
I'll close this then, since there's nothing I can do atm
