### ISSUE TITLE
StateProvider value update doesnt work

### ISSUE THREAD

**Issue by niklasbartsch** [rrousselGit/river_pod#1094]
I am trying to do the simplest of everything.
I just want to update the state of a StateProvider.
It is working in all other projects.
I don't know what I am doing wrong.

```dart
final myHomepageIndex = StateProvider((ref) => 0);

final newIndex = 1;
ref.watch(myHomepageIndex.notifier).update((state) => newIndex);
```

I alos tried it like this:
```dart
final myHomepageIndex = StateProvider((ref) => 0);

final newIndex = 1;
ref.watch(myHomepageIndex.state).state = newIndex;
```

The ProviderScrope is set up:
```dart
runApp(const ProviderScope(child: MyApp()));
```

I expect it to update the value to 1, but its staying at 0

**Comment by iamarnas** [comment]
I think it should be like that:
```dart
ref.watch(myHomepageIndex.notifier).update((prev) => prev +  newIndex);
```

**Comment by rrousselGit** [comment]
There was a bug in a recent StateNotifier version. Make sure to run `pub upgrade`. This should fix your issue

**Comment by niklasbartsch** [comment]
Thank you so much @rrousselGit 
I spend so much time on this 😅
