### ISSUE TITLE
Is there a difference between using ConsumerWidget and Consumer?

### ISSUE THREAD

**Issue by AhmedLSayed9** [rrousselGit/river_pod#1095]
If I've one item or few items that needs to update when provider's state change, I can 1. Use `StatelessWidget` and wrap those items with `Consumer` 2. Use `ConsumerWidget` and declare variable to that provider inside build using ref.watch and use it easily with the items. I like the second approach as it's more readable code, but is there any difference between them in terms of performance?

I've tried to find an answer in the riverpod dev docs but couldn't.

**Comment by rrousselGit** [comment]
There's no difference. Consumer is a ConsumerWidget

**Comment by AhmedLSayed9** [comment]
On docs it's said that `Consumer can be used to listen to providers inside a StatefulWidget or to rebuild as few widgets as possible when a provider updates.`
While on ConsumerWidget class doc it's said `for performance optimizations, see Consumer.` What's meant with that performance optimization? Does using Consumer just around widgets that need to be updated instead of using ConsumerWidget better for performance?

Thank you!

**Comment by rrousselGit** [comment]
It's because Consumer is convenient for rebuilding only a single widget:

```dart
Scaffold(
  body: Consumer(
    builder: (context, ref, child) {
      final value = ref.watch(provider);
      return Text('$value');
    },
 ),
);
```

Doing this will rebuild only the `Text`  not the `Scaffold`


You could do the same with `ConsumerWidget`. But it's less convenient as you'd need to define a new widget just for the Text

**Comment by AhmedLSayed9** [comment]
Thanks you!
