### ISSUE TITLE
Already created provider doesn't rebuild

### ISSUE THREAD

**Issue by AlexanderFarkas** [rrousselGit/river_pod#1098]
**Describe the bug**
If a provider is not used directly after its creation, it doesn't rebuild and its ref.listen doesn't trigger.
`riverpod: ^1.0.3`

**To Reproduce**

UserRepository watches Api provider. When tokenPair changes, UserRepository should update userProvider. But it doesn't happen.

Note, that UserRepository.provider is initialized, its provider fires ones (but it should twice due to Api rebuild).
"Recreated" is printed only once.
```
import 'package:flutter_test/flutter_test.dart';
import 'package:riverpod/riverpod.dart';


class TokenPair {}
class User {}

class SecureStorage {
  final Reader read;
  static final tokenPairProvider = StateProvider<TokenPair?>((ref) => null);
  static final provider = Provider<SecureStorage>((ref) => SecureStorage(ref.read));

  SecureStorage(this.read);

  void change() {
    read(tokenPairProvider.notifier).state = TokenPair();
  }
}

class Api {
  static final provider = StateProvider<Api>((ref) => Api());
}

class UserRepository {
  final Reader read;
  final Api api;

  static final userProvider = StateProvider<User?>((ref) {
    return;
  });

  static final provider = Provider<UserRepository>((ref) {
    print("Recreated");
    final repository = UserRepository(ref.watch(Api.provider), ref.read);
    ref.onDispose(ref.listen<TokenPair?>(
      SecureStorage.tokenPairProvider,
      (previous, next) {
        repository.update(next);
      },
      fireImmediately: true,
    ));
    return repository;
  });

  UserRepository(this.api, this.read);
  void update(TokenPair? pair) {
    read(userProvider.state).state = pair == null ? null : User();
  }
}

Future<void> main() async {
  test("should update userProvider with new User, when tokenPair changes", () {
    final container = ProviderContainer();
    addTearDown(container.dispose);

    container.read(UserRepository.provider);
    expect(container.read(UserRepository.userProvider), equals(null));
    container.read(Api.provider.state).state = Api();
    container.read(SecureStorage.provider).change();
    expect(container.read(UserRepository.userProvider), isNotNull);
  });
}
```

**Expected behavior**
I suppose the test shouldn't fail.

P.S. Double checked version, latest - 1.0.3.

**Comment by rrousselGit** [comment]
This is in fact expected

Providers voluntarily are not recreated if they are not active, and even if they rebuild, they do so asynchronously (unless you read them).

So if you're expecting the "recreated" print to be shown, you should either:

- listen to the provider then call `container.pump()` (to await provider rebuilds)

  ```dart
  container.listen(UserRepository.provider, (prev, value) {});
  container.read(Api.provider.state).state = Api();
  await container.pump(); // will rebuild UserRepository.provider
  ```

- re-read the UserRepository.provider:
  ```dart
  container.read(UserRepository.provider);
  container.read(Api.provider.state).state = Api();
  container.read(UserRepository.provider); // forces UserRepository.provider specifically to rebuild
  ```


Note that in both cases you will now have an exception when the UserRepository rebuilds. 
But this is expected, at it is doing something that is not allowed:

Due to the `fireImmediately` parameter, when `UserRepository` rebuilds, it'll modify another provider. This is not allowed. The initialization of a provider should not modify other providers.

**Comment by AlexanderFarkas** [comment]
Well, avoidance of rebuild is reasonable. But why listen is also not triggered? I mean the actual callback passed to ref.listen.

**Comment by rrousselGit** [comment]
The listen is not triggered because the provider listened did not change.
It is related to the anti-pattern I mentioned. 

To begin with, you could simplify most of your code into:

```dart
final userProvider = Provider<User?>((ref) {
  final pair = ref.watch(SecureStorage.tokenPairProvider);
  return pair  == null ? null : User();
});
```

**Comment by AlexanderFarkas** [comment]
But tokenPairProvider does get changed. By SecureStorage.change method.

**Comment by AlexanderFarkas** [comment]
Now I see. 

In my opinion, there should be some way to keep providers alive, because sometimes we want to listen/rebuild, even if a provider is currently not used. I suppose, that it's a common enough use case in projects with large codebases.

**Comment by rrousselGit** [comment]
I've already explained how to do that. You should watch or listen the provider. See my previous answer

**Comment by AlexanderFarkas** [comment]
Thank you for your time. I will definitely try to do some refactoring.
