### ISSUE TITLE
Auto import Riverpod when using Riverpod snippets

### ISSUE THREAD

**Issue by FXschwartz** [rrousselGit/river_pod#1104]
**Is your feature request related to a problem? Please describe.**
No problem just would be nice if when I used a snippet like a FutureProvider that I didn't have to do an additional step to import Riverpod.

**Describe the solution you'd like**
It would be nice if when generating a code snippet, the correct import also was added

**Describe alternatives you've considered**
None

**Additional context**
None

https://user-images.githubusercontent.com/16527593/150356908-a122f8b3-df17-4157-9475-9d32cb446626.mov

**Comment by rrousselGit** [comment]
I'm not responsible for the code-snippets, so not much I can do.

I also don't think that's doable, at least not with what I know from how snippets works in VSCode

**Comment by FXschwartz** [comment]
@rrousselGit Ah my bad, I assumed you were responsible for the snippets

Well, I appreciate the quick response!
