### ISSUE TITLE
Riverpod version should be 9.0

### ISSUE THREAD

**Issue by juanpare** [rrousselGit/river_pod#111]
**Describe the bug**
Can't update hooks_riverpod to version 9.0

**To Reproduce**

In `pubspec.yaml` add:

`hooks_riverpod: ^0.9.0`

You get the error:

`Because hooks_riverpod >=0.9.0 depends on riverpod ^0.9.0 which doesn't match any versions, hooks_riverpod >=0.9.0 is forbidden.`

**Expected behavior**

The `flutter pub get` command should work.

**Comment by rrousselGit** [comment]
Eh, sorry for that. I'll fix it in 10 minutes

**Comment by rrousselGit** [comment]
Done, sorry for that.
