### ISSUE TITLE
Add updateShouldNotify parameter to Provider

### ISSUE THREAD

**Issue by nogaten** [rrousselGit/river_pod#1117]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to notify even if it is equivalent to previous value.

**Describe the solution you'd like**
Please add updateShouldNotify parameter to Provider or allow ProviderBase to extend.
```dart
  Provider(
    (ref) {...},
    updateShouldNotify: (previous, next) => next != previous,
  );
```

**Comment by rrousselGit** [comment]
> Sometimes I want to notify even if it is equivalent to previous value.

Why?

**Comment by nogaten** [comment]
I want to notify a huge iterable (List, Set, Map).
It takes too much time to shallow copy.

**Comment by rrousselGit** [comment]
But how is this related to Provider?

**Comment by nogaten** [comment]
In the following example, it would take more than one second.

```dart
import 'dart:async';

import 'package:riverpod/riverpod.dart';

void main() {
  final controller = StreamController<int>();
  final provider = Provider<Set<int>>((ref) {
    ref.state = {};
    controller.stream.forEach((i) {
      ref.state = {...ref.state, i};
      //ref.state.add(i);  I want to do this.
    });
    return ref.state;
  });
  final container = ProviderContainer();
  container.listen(
    provider,
    (previous, next) {},
  );
  final stopWatch = Stopwatch()..start();
  for (var i = 0; i < 10000; i++) {
    controller.sink.add(i);
  }
  stopWatch.stop();
  print('time: ${stopWatch.elapsedMicroseconds}');
}
```

**Comment by rrousselGit** [comment]
To be fair anything executed 10000 times would be slow


Try using StateNotifier. It has an updateShouldNotify

**Comment by nogaten** [comment]
I understand.
Thank you for your quick reply.

**Comment by esenmx** [comment]
@nogaten take a look at my repo: [collection_notifiers](https://github.com/esenmx/collection_notifiers)
SetNotifier is complete, others are on the way.

**Comment by esenmx** [comment]
For anyone who struggles with collections, can safely use [collection_notifiers](https://pub.dev/packages/collection_notifiers).
