### ISSUE TITLE
FutureProvider not working properly.

### ISSUE THREAD

**Issue by tbm98** [rrousselGit/river_pod#112]
**To Reproduce**
I have futureProvider is 
```dart
final currentProfileProvider = FutureProvider<Profile>((ref) async {
  final currentMSV = await SharedPrefs.instance.getCurrentMSV();

  return ref.read(profileRepositoryProvider).getUserByMSV(currentMSV);
});
```

usage:
```dart
            final currentProfile = context.read(currentProfileProvider);

            currentProfile.whenData((profile) {
              print(profile.toJson());
              print('data is ${profile.toJson()}');
              showAlertMessage(context, profile.Token);
            });
```

in the first click: nothing happens.
second click: dialog show with data.
third click: dialog show with data.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/52562340/92071416-d924ae00-edd8-11ea-9fe7-c7105797dffc.gif)

**Comment by rrousselGit** [comment]
`whenData` does not wait for the future to resolve. It's a synchronous operation, and if the future isn't completed, nothing happens.

What you want is to await the future instead:

```dart
final profile = await context.read(currentProfileProvider.future);

print(profile.toJson());
print('data is ${profile.toJson()}');
showAlertMessage(context, profile.Token);
```

**Comment by tbm98** [comment]
It worked. Thank you a lot!
