### ISSUE TITLE
Obtains the [StateNotifier] associated with this [StateNotifierProvider], while listening to it

### ISSUE THREAD

**Issue by altrr2** [rrousselGit/river_pod#1127]
At the moment both ref.watch(provider.notifier) and ref.read(provider.notifier) would not trigger rebuild when provider state is updated. It would be nice and more consistent to be able to access the notifier while listening to the provider's changes.

Consider a simple example of app theme, where you have 3 options (System, Light, Dark) and 2 ThemeData values which you would need to pass to the MaterialApp, depending on the user's choice and platform brightness.

You can generally either:
- create 2 providers one for the option state, and another for the theme data
- or create an immutable class which holds both option and the theme data, and a single state notifier provider, where state would be of this class
- or create one state  notifier provider for the option state, where a notifier exposes a getter for the theme data

The first two options are a bit of overkill for such trivial example. 

To get the third option to work you'd need to watch the state  notifier provider,  discard it's value and then get the actual data from the getter. 

It would be more consistent if something like
final themeData = ref.watch(themeOptionProvider.notifier).getThemeData();
would also listen to the provider's changes (as opposed to ref.read).

I also found this pattern quite recurring when refactoring an app which uses Provider's ChangeNotifier.

Sorry, if this came up before.

**Comment by rrousselGit** [comment]
> or create one state notifier provider for the option state, where a notifier exposes a getter for the theme data


This isn't a valid option. Getters on the notifier are an anti-pattern. 
The other two solutions you proposed are the correct ones.

It sounds to me like your trying to use StateNotifier like a ChangeNotifier, when they are different. 
Making an immutable class that holds all your properties is the basis of how StateNotifier is supposed to be used. If you don't like that, you can keep using ChangeNotifier instead

**Comment by altrr2** [comment]
Understood. Thanks a lot for the prompt reply

**Comment by rrousselGit** [comment]
No problem, have a nice day!

**Comment by altrr2** [comment]
I didn't realise there's a ChangeNotifierProvider in riverpod up until after following your reply. Interesting. Thanks again.
