### ISSUE TITLE
listen StateNotifierProvider don't work in somecase but addListener work

### ISSUE THREAD

**Issue by MrMagloire** [rrousselGit/river_pod#1141]
Hello, in my app, when i use ref.listen it's don't work but but when i use addListener to this provider it's work

This is my code
```
import 'package:flutter_riverpod/flutter_riverpod.dart';

class Booking {
  String? from;
  String? to;

  Booking({
    this.from,
    this.to,
  });
}

class BookingDataNotifier extends StateNotifier<Booking> {
  BookingDataNotifier() : super(Booking());

  void add(Booking item) {
    state = item;
  }
}

final bookingProvider =
    StateNotifierProvider<BookingDataNotifier, Booking>((ref) {
  return BookingDataNotifier();
});
```

For make change when i use 
```
final booking = ref.read(bookingProvider.notifier);
booking.add(Booking(
    from: 'Chicago')
);
```
It's work in 'ref.listen' and 'ref.watch(provider.notifier).addListener' below
```
ref.listen<Booking>(bookingProvider, (Booking? previous, Booking current) {
    print('listen booking  work...');
});

... 

ref.watch(bookingDataProvider.notifier).addListener((value) {
    print('listen booking  work...');
});
```

But if for make change i use
```
final booking = ref.read(bookingProvider.notifier);
Booking newBooking = ref.read(bookingProvider);
newBooking.from = ''Chicago;
booking.add(newBooking);
```
In 'ref.listen' we are no change in listen function but in addListener we are change

**Comment by rrousselGit** [comment]
Could you add a minimal reproducible example?

Since I can't execute your code, it's pretty hard to know what's the issue

**Comment by MrMagloire** [comment]
I will create the code but to answer the question `what's the issue`
I want to change only one thing relying on the existing state of the model so I use `ref.read` to retrieve and change the `from` 
```
Booking newBooking = ref.read(bookingProvider);
newBooking.from = ''Chicago;
booking.add(newBooking);
```
but in this case in the `ref.listen` nothing happens in the function as if the state of the model has not changed but in the `addListener` the function is executed but in this one I do not have the possibility of having the `previous` and the `current`.
In my case I want to compare `previous.from` and `current.from` in `ref.listen` function this is how I found that the `ref.listen` does not react when you use `ref.read` to have the current value in order to modify it.
But when i make
```
final booking = ref.read(bookingProvider.notifier);
booking.add(Booking(
    from: 'Chicago')
);
```
It `ref.listen` work but in this case I would overwrite all existing values.

**Comment by rrousselGit** [comment]
It doesn't make sense that addListener is invoked but ref.listen isn't, since ref.listen is transmitting what addListener emits

Hence why I'd like an example, because I need to play around with the code. As I don't see how that's possible otherwise

**Comment by MrMagloire** [comment]
Hello, this is a minimal code :
https://gist.github.com/MrMagloire/a7aeb80b92fead63f65dbeb2d95d0469

**Comment by rrousselGit** [comment]
Oh, I see what happens

Your confusion stems from the fact that `addListener` by defaults immediately calls the listener with the current value, while `ref.listen` doesn't.
If you did `addListener(..., fireImmediately: false)`, the listener wouldn't be triggered.


The real reason why your listeners aren't triggered is that you're modifying your StateNotifier before ref.listen is executed


If do you:

```dart
  void initState() {
    super.initState();
    Future(() {
      ref.read(bookingProvider.notifier).add(Booking(to: 'My Garage'));
    });
  }
```

then you'll see the listener being called

**Comment by rrousselGit** [comment]
As a sidenote, modifying providers inside `initState` is discouraged/anti-pattern.

Consider doing your `add` within the StateNotifierProvider itself:

```dart
final bookingProvider =
    StateNotifierProvider<BookingDataNotifier, Booking>((ref) {
  return BookingDataNotifier()
    ..add(Booking(to: 'My garage'));
});

```

**Comment by MrMagloire** [comment]
Thank you @rrousselGit 
On other hand I see in doc :
```
// The state of our StateNotifier should be immutable.
// We could also use packages like Freezed to help with the implementation.
```
When I use `copyWith` from instance of my model class everything work fine:
```
final booking = ref.read(bookingProvider.notifier);
booking.add(ref.read(bookingProvider).copyWith(from: 'Chicago'));
```
