### ISSUE TITLE
ConsumerWidget is a StatelessWidget or StatefullWidget?

### ISSUE THREAD

**Issue by Shahmirzali-Huseynov** [rrousselGit/river_pod#1142]
First of all, thank you for riverpod. I wonder ConsumerWidget is a StatelessWidget? Because it is extends from ConsumerStatefulWidget  and  ConsumerStatefulWidget extends StatefulWidget ? so ConsumerWidget is Stateless or StatefulWidget ?

**Comment by rrousselGit** [comment]
The answer doesn't matter and could change between versions.

There's no reason to care about how ConsumerWidget works under the hood 😄

**Comment by Shahmirzali-Huseynov** [comment]
but there is a difference between stateless and stateful widgets 🙂? isn't it?

**Comment by Shahmirzali-Huseynov** [comment]
and also in the 0.14.3 version we have to use context.read in the stateless widget but in 1.0.3 version we don't have ref.read, yeah I know we can with ConsumerWidget.


```
class Home extends StatelessWidget {
  Home({Key? key,  }) : super(key: key);
  
  @override
  Widget build(BuildContext context) {
    return Scaffold(
           body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text('You have pushed the button this many times:'),
            Consumer(
              builder: (BuildContext context, WidgetRef ref, Widget? child) {
 
               final count = ref.watch(counterProvider.state).state;
 
                return Row(
                  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                  children: <Widget>[
                    Text('$count'),
                    child!,
                  ],
                );
              },

           child: Text('Good job!'),
            )
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.plus_one),

 ------->>>>>>       onPressed: () => r**ef.read(**counterProvider.state).state++,
      ),
    );
  }
}
```

**Comment by rrousselGit** [comment]
> but there is a difference between stateless and stateful widgets 🙂? isn't it?

The difference is in how you use them, not how they work. StatelessWidgets and StatefulWidgets are pretty much the same thing internally
