### ISSUE TITLE
A provider that has the ability to be disposed and can provide values that implement given interface

### ISSUE THREAD

**Issue by KristianBalaj** [rrousselGit/river_pod#1144]
I have a use case where I need to do cleanup on object dispose and this object is provided by a provider.

I'm using `ChangeNotifierProvider` where the object extends the `ChangeNotifier` just to have the cleanup ability build-in.

However, I do not need any of the `ChangeNotifier` functionality, just the dispose mechanism.

I would like to see something like a `DisposableProvider` where the returned value could be only something that implements a specific interface that has the `dispose` method.
Also to make using this more safe, I would like to see other Providers forbid to return a value that implements the interface, to not forget to return the object in a bad provider that does not disposes the state.

**Comment by rrousselGit** [comment]
All providers offer "ref.onDispose" for adding cleanup logic

There's no need for something as specific as a DisposeableProvidrr

**Comment by rrousselGit** [comment]
I'll close this since this is already supported in a more generic way. Here's an example in the docs https://riverpod.dev/docs/concepts/modifiers/auto_dispose/#example-canceling-http-requests-when-no-longer-used
