### ISSUE TITLE
Watching the last value of a StreamProvider in a Provider without waiting for the first value to be emitted

### ISSUE THREAD

**Issue by johynpapin** [rrousselGit/river_pod#116]
Hello, 

I want to write a provider whose value depends on another provider. Here is the provider I want it to depends on:

```dart
final userStreamProvider = StreamProvider<User>((ref) {
  final authService = ref.watch(authServiceProvider);

  return authService.userStream;
});
```

The provider I want to write uses the last value of this provider, but this value is not essential: I don't want to wait for the first value to be emitted. So I want to write something like this:

```dart
final dataServiceProvider = Provider<DataService>((ref) {
  final user = ref.watch(userStreamProvider); // Invalid code

  return DataService(userId: user?.userId);
});
```

The only way I found to write this Provider is to turn it into a FutureProvider. Is there another solution? I'm a beginner, so it's really possible that what I'm trying to do is not a good practice.

Thank you in advance, and thank you for this very great project.

**Comment by rrousselGit** [comment]
You need to handle the loading scenario in some way.

In your case, it appears that you just want to use `null` if there's no user (although be aware that you could silently swallow user errors this way), so you can do:

```dart
final dataServiceProvider = Provider<DataService>((ref) {
  final user = ref.watch(userStreamProvider).data?.value;

  return DataService(userId: user?.userId);
});
```

**Comment by johynpapin** [comment]
Thank you very much, this is exactly what I wanted.
