### ISSUE TITLE
docs: update package status on README.md

### ISSUE THREAD

**Issue by marcossevilla** [rrousselGit/river_pod#1160]
**Describe what scenario you think is uncovered by the existing examples/articles**
A clear and concise description of the problem that you want explained.

Right now the README.md explains some good statements about this package, but they're outdated. It still says it's on an ["experimental"](https://github.com/rrousselGit/river_pod#is-it-safe-to-use-in-production) status when it's now stable. Also, I think it's safe to assume the community likes this package, this [section](https://github.com/rrousselGit/river_pod#is-it-safe-to-use-in-production) says otherwise, maybe that claim can be rewritten too. This other [section](https://github.com/rrousselGit/river_pod#is-it-safe-to-use-in-production) also can be updated with the stable status.

**Comment by rrousselGit** [comment]
Fair enough, I've updated the section
