### ISSUE TITLE
Restore state upon app being moved back to foreground

### ISSUE THREAD

**Issue by Lingareddyvinitha** [rrousselGit/river_pod#1168]
**Problem:** Upon minimizing a riverpod Flutter app to the background, the entire state of the app is reset.

The solution I'd like: Restoration of state after the app is brought back to the foreground.

I am not aware of restoration state support for the RiverPod

**Comment by iamarnas** [comment]
Flutter have build in restoration mechanism. Example [RestorationMixin](https://api.flutter.dev/flutter/widgets/RestorationMixin-mixin.html) and you can restore most of things with it.

**Comment by rrousselGit** [comment]
Riverpod has no built-in support for state persistence.

If you want to restore the state of a provider, you will have to store their state in a database somewhere on your own

**Comment by rrousselGit** [comment]
Closing in favour of https://github.com/rrousselGit/river_pod/issues/1032

**Comment by North101** [comment]
@Lingareddyvinitha I have just published a package that will restore provider state after being killed:
https://pub.dev/packages/flutter_riverpod_restorable
