### ISSUE TITLE
Family Autodispose provider getting disposed on show dialog only with stateless widgets

### ISSUE THREAD

**Issue by denes16** [rrousselGit/river_pod#1170]
**Describe the bug**
I have an ChangeNotifierProvider with family and autodispose. Ony has one listener, and stateless widgets screen. When i show a dialog using showDialog, the provider gets disposed, when the modal is closed i got an error about try to read an already disposed provider. But when i change to an stataful widget it works. It's necessary to do this?  Theres a hook to solve this?
Im using the riverpod hooks version.

**To Reproduce**

````

import 'package:flutter/material.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

class TestProvider extends ChangeNotifier {
  final int id;
  TestProvider({required this.id});
}

final testProvider =
    ChangeNotifierProvider.autoDispose.family<TestProvider, int>((ref, id) {
  return TestProvider(id: id);
});

class TestWidget extends HookConsumerWidget {
  const TestWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final provider = ref.watch(testProvider(1));
    print('TestWidget: ${provider.id}');
    return ElevatedButton(
      onPressed: () {
        showDialog(
          context: context,
          builder: (BuildContext context) {
            return AlertDialog(
              title: const Text('Alert Dialog title'),
              content: const Text('Alert Dialog body'),
              actions: [
                ElevatedButton(
                  child: const Text('Close'),
                  onPressed: () {
                    Navigator.of(context).pop();
                  },
                ),
              ],
            );
          },
        );
      },
      child: Text('id: ${provider.id} Show dialog'),
    );
  }
}

````
**Expected behavior**
The providers marked as autodispose, should not be disposed when show a modal

**Comment by XuanTung95** [comment]
I cannot reproduce the bug. Please provide which version is used.

**Comment by denes16** [comment]
Thanks for the quick response.
flutter_hooks: ^0.18.0
hooks_riverpod: ^1.0.0-dev.7

**Comment by denes16** [comment]
Sorry, i cannot the issue on a clean flutter project, but on my project is still happening, does anyone know what i have to check?

**Comment by denes16** [comment]
Sorry, i have found the problem, i was catching the error on a previous disposed provider, not in the current one, so, in the catch block i add a check for a dispose property before show the modal, an it works. Thanks
