### ISSUE TITLE
Understanding about ConsumerWidget

### ISSUE THREAD

**Issue by zgramming** [rrousselGit/river_pod#118]
I'm curious about how to ConsumerWidget work , as my understanding it will give us option to use "conventional" Consumer or ConsumerWidget . In docs [example](https://riverpod.dev/docs/concepts/reading#consumerwidget) about ConsumerWidget  said: 

> This example will make our UI listen to counterProvider and rebuild a Text (and only that Text) when the counter changes.

But when i try make simple example to increase number when button click with **ConsumerWidget**  , then i see whole tree rebuild when number change. 

But when i change to "conventional" Consumer , i don't get this issue . Question is , whether using ConsumerWidget will make whole tree rebuild ? 

### ConsumerWidget

![tanya riverpod](https://user-images.githubusercontent.com/38829404/92712829-68573600-f384-11ea-8395-d4badb05a3e7.gif)

```
final providerCount = StateProvider.autoDispose((ref) => 0);

class TestConsumer extends ConsumerWidget {
  @override
  Widget build(BuildContext context, ScopedReader watch) {
    print('this whole tree will rebuild ? ');
    final count = watch(providerCount).state;
    return Scaffold(
      body: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Text('With Consumer Widget'),
          Text(count.toString()),
          Center(child: OutlineButton(onPressed: () => context.read(providerCount).state++)),
        ],
      ),
    );
  }
}

``` 

### Without Consumer

![tanya riverpod 2](https://user-images.githubusercontent.com/38829404/92712841-6ee5ad80-f384-11ea-8351-3b213af5b7e5.gif)

```
final providerCount = StateProvider.autoDispose((ref) => 0);

class TestWithoutConsumer extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    print('this whole tree will rebuild ? ');

    return Scaffold(
      body: Column(
        children: [
          Text('Without Consumer Widget'),
          Consumer(builder: (context, watch, _) {
            final count = watch(providerCount).state;
            return Text(count.toString());
          }),
          Center(child: OutlineButton(onPressed: () => context.read(providerCount).state++)),
        ],
        mainAxisAlignment: MainAxisAlignment.center,
      ),
    );
  }
}

```

**Comment by iamarnas** [comment]
@zgramming Like I understand ConsumerWidget work like StatefulWidget, on state changes rebuild all context in the widget. Consumer rebuild only own child.

**Comment by zgramming** [comment]
@iamarnas but if work like that , is opposite with docs said : 

> This example will make our UI listen to counterProvider and rebuild a Text (and only that Text) when the counter changes.

So i want confirm it , is this how ConsumerWidget work

**Comment by iamarnas** [comment]
> @iamarnas but if work like that , is opposite with docs said : 
> 
> > This example will make our UI listen to counterProvider and rebuild a Text (and only that Text) when the counter changes.
> 
> So i want confirm it , is this how ConsumerWidget work or i missed read in documentation

I have tested it before to understand how it works and I had same result like you. I think Remi need correct his documentation.

**Comment by rrousselGit** [comment]
> I have tested it before to understand how it works and I had same result like you. I think Remi need correct his documentation.


What do you think needs to change?

**Comment by rrousselGit** [comment]
```dart
Scaffold(
  body: Consumer(builder: (context, watch) {
    final count = watch(countProvider).state;
    return Text('$count');
  });
);
```

is strictly equivalent to:

```dart
Scaffold(
  body: Count(),
);

class Count extends ConsumerWidget {
  @override
  Widget build(context, watch) {
    final count = watch(countProvider).state;
    return Text('$count');
  }
}
```

**Comment by iamarnas** [comment]
>  > I have tested it before to understand how it works and I had same result like you. I think Remi need correct his documentation.
> 
> 
> What do you think needs to change?

Consumer Widget exempel Home Widget in the documentation it would rebuild everything down from Scaffold? But docs say it rebuild a Text (and only that Text). Of course maybe I'm wrong.

**Comment by rrousselGit** [comment]
It may be an outdated doc. Do you have the link to it?

**Comment by zgramming** [comment]
Sure if it's only miss understanding

**Comment by iamarnas** [comment]
Sure. Close it.
