### ISSUE TITLE
AsyncValue.fromFuture(Future future)

### ISSUE THREAD

**Issue by hamishjohnson** [rrousselGit/river_pod#1196]
**Is your feature request related to a problem? Please describe.**
I like using `AsyncValue.when` to build UIs. Currently (correct me if I'm wrong) the only way to make an AsyncValue is from a StreamProvider or FutureProvider, but then it gets provided. There also seems to be an indirect way of doing it from AsyncValue.guard, but then it's wrapped in a Future that needs to be awaited, which isn't usable directly in a build method.

**Describe the solution you'd like**
I'd like an AsyncValue.fromFuture() method to have a quick way of creating an AsyncValue from a Future (or even a stream)

**Describe alternatives you've considered**
Making an AsyncValue using FutureProvider, but I don't want to provide the future, and it's more verbose.

**Comment by rrousselGit** [comment]
I do not understand what exactly you want. Could you show an example of how this would work?

**Comment by hamishjohnson** [comment]
Something like this:

import 'package:flutter/widgets.dart';

```
class Widget extends StatelessWidget {
  const Widget({Key? key}) : super(key: key);

  Future someFuture () => Future.delayed(Duration(seconds: 1));

  @override
  Widget build(BuildContext context) {
    return AsyncValue.fromFuture(someFuture()).when(
      data: () => ..., 
      error: (error) => ..., 
      loading: () => ...
    );
  }
}
```

**Comment by rrousselGit** [comment]
It sounds like you're misunderstanding what AsyncValue does.

It's not a listenable object. AsyncValue is just a different syntax for Flutter's AsyncSnapshot.
You'll need either a provider of something like FutureBuilder to listen to the Future.
