### ISSUE TITLE
Test  StateNotifier and wiget test with StateNotifierProvider

### ISSUE THREAD

**Issue by rddewan** [rrousselGit/river_pod#1206]
Test state notifier and test widget on state change are not included in test doc.

**Comment by rrousselGit** [comment]
I don't understand what this is about. Could you expand?

**Comment by rddewan** [comment]
how do we test the state of the widget ? when using the state notifier and state notifier provider

**Comment by rrousselGit** [comment]
Pretty much the same way.


I'd suggest looking into the flutter_riverpod tests if you're looking for more examples

https://github.com/rrousselGit/river_pod/blob/master/packages/flutter_riverpod/test/listen_test.dart
