### ISSUE TITLE
LoadingState on AsyncValues

### ISSUE THREAD

**Issue by joanofdart** [rrousselGit/river_pod#121]
Hello 👋🏼 
Sorry to bother you all with this kind of question but I'd like to know if I can force a Loading on the AsyncValue?
Given the current situation, even if a null value is passed onto the Stream (e.g a Snapshot from firestore), the stream.when(data()) will be the one to render.

I'm wondering about this since I'd like to perhaps show a loading state on data change.

**Comment by rrousselGit** [comment]
You mean "push a loading status after a valid value was emitted"?

**Comment by joanofdart** [comment]
Yup, I guess. Does that make sense? or is it just trying to do something that its not meant to be done? 🤔

**Comment by rrousselGit** [comment]
It's fine. It's just not really supported by StreamProvider at the moment.

I think I'll add a separate constructor that is expected to create a `Stream<AsyncValue<T>>` instead of `Stream<T>`


Then you should be able to write:

```dart
StreamProvider.merge<int>((ref) async* {
  yield AsyncValue.data(42);
  yield AsyncValue.loading();
})
```

**Comment by joanofdart** [comment]
Thanks @rrousselGit 
So basically, the current when(loading) only fires the first time any stream is being listened to? Oh!

**Comment by rrousselGit** [comment]
It can fire multiple times (typically when using ref.watch or context.refresh)
But usually, yes it fires only the first time.

I will add support for this though

**Comment by rrousselGit** [comment]
It's a bit tedious to implement and low priority for me as I'm a bit busy

Make sure to :+1: if you want this. If many people want this, I can reconsider.
Or maybe even open a PR :smile:

**Comment by joanofdart** [comment]
Hey @rrousselGit !
Oh I totally understand! You do what you gotta do, I was just asking about this because I thought it was not working as expected.
I'd love for this to be implemented but I can be patient and mean while, see how to get around it (or make said PR, but I gotta learn fully how would this be needed to be done 😄 )

And as always, thank you for your reply.

**Comment by KristianBalaj** [comment]
@rrousselGit @joanofdart Hey, I have a possible workaround for this issue.

To have more control of the `AsyncValue` states coming from a stream you could use the `StateNotifierProvider`.

Here is the sample usage from my app (you can implement your specific state behaviour in the `load` method of the `StateNotifier`):
```
class OrderDetailPageViewModel extends StateNotifier<AsyncValue<OrderModel>> {
  OrderDetailPageViewModel(this._providerRef)
      : super(const AsyncValue.loading());

  final ProviderReference _providerRef;

  final List<StreamSubscription> _subscriptions = [];

  @override
  void dispose() {
    super.dispose();
    Future.wait(_subscriptions.map((e) => e.cancel()));
  }

  void load(String orderUniqueId) {
    final stream = _providerRef
        .read(ordersServiceProvider)
        .singleOrderStream(orderUniqueId);

    _subscriptions.add(
      stream.listen(
        (event) {
          state = AsyncValue.data(event);
        },
        onError: (e, st) => state = AsyncValue.error(e, st),
      ),
    );
  }
}

final orderDetailPageOrderStreamProvider = StateNotifierProvider.autoDispose(
  (ref) => OrderDetailPageViewModel(ref),
);
```

For the sample usage of this provider you can check the sample usage in my open source Flutter app [here](https://github.com/cloudis-dev/bottleshop_admin/blob/0a17923978b30c70d0c53f4649ecd29c6ae88fb5/lib/ui/activities/app_activity/pages/order_detail_page/order_detail_page.dart). 

FYI. The master branch in this repo is still using classical `provider` package, this referenced commit is in the branch that has a full refactor from the `provider` to `riverpod`.

**Comment by rrousselGit** [comment]
Note that this is now possible by doing:

```dart
StreamProvider<User>((ref) async* {
  yield User();

  ref.state = AsyncValue.loading();
});
```
