### ISSUE TITLE
Listen dependent streams with riverpod

### ISSUE THREAD

**Issue by sokolej79** [rrousselGit/river_pod#1216]
We use streams with Hasura subscriptions a lot.
How to listen dependent streams if first stream resolve true listen other two streams otherwise dont listen other two. Detail below.

Streams:
-stream A permission true or false
-stream B subscribe to events, list of events
-Stream C listen network state changes, is network or not
All three streams can change realtime.

Scenarios:
-if A true subscribe to B and C parallel
-if A false dont subscribe other two streams, if are already subscribed unsubscribe them and on widget show nothing
-if C no network show error but keep listening B stream events, it will reconnect again automatically when network up again

How to handle scenario with riverpod if possible with Statenotifier for all 3 streams and not 3 separated StreamProviders.

**Comment by rrousselGit** [comment]
We've discussed this on Discord I believe.
For reference, Riverpod apps be structured in a way such that the order in which providers are modified does not matter.

If you want to do what you've described, you can do it manually using `stream.listen` and merging the streams in the desired way. Riverpod doesn't deal with those cases as this doesn't match Riverpod's architecture
