### ISSUE TITLE
Add filter method similar to select that filters ref.watch updates based on a condition

### ISSUE THREAD

**Issue by eli1stark** [rrousselGit/river_pod#1217]
**Problem**
Sometimes there is a need to tell `ref.watch()` to refresh the parent provider based on a certain condition. It would be nice if we had something like the example below, it will allow us to create providers with complex logic. I agree that it can seem like a rare case but this is because we don't have this feature yet, hence, we don't consider filtering while modeling providers.

There 2 use cases:
1. When we want to create a condition based on the provider's value
2. When we want to provide a condition that doesn't depend on the provider's value

**Solution (Use case 1)**
```dart
final providerA = Provider<Model>(
  (ref) {
    // if (value > 10), ref.watch will refresh providerA else it won't
    ref.watch(providerB).filter((value) {
      return value > 10; // condition that returns bool
    });

    return Model;
  },
);
```

**Solution (Use case 2)**
```dart
final providerA = Provider<Model>(
  (ref) {
    ref.watch(providerB).filter((_) {
      return customConditionThatReturnsBool;
    });

    return Model;
  },
);

```

**Comment by rrousselGit** [comment]
Why exactly would this be desirable? I don't understand when the examples you gave would be useful.

>  I agree that it can seem like a rare case but this is because we don't have this feature yet, hence, we don't consider filtering while modeling providers

What does this means?


____


Overall unless there's a very good reason to do that, I'm against the idea. You should be able to do everything with `select`, in a way that is not error-prone (when such a filter operation could be very error-prone).

**Comment by eli1stark** [comment]
Sorry if I was not clear enough, here's a more concrete example.
It's usually useful when we have for example StateNotifierProvider that is dependent let's say on the database box.
```dart
final providerA = StateNotifierProvider.family<Notifier, State, int>(
  (ref, id) {
    // On every object change ref.watch() will refresh providerA, which is desirable
    // I'm listening here to a single database object
    ref.watch(databaseBox(id)).filter((value) {
      return value != null; // when value was deleted from the database for example I don't want providerA to refresh
    });
    
    // Inside Notifier I have some logic that is fetching database with id and works with the object.
    // It also assumes that Notifier will be recreated if the object will be updated in the database
    return Notifier(ref.read, id);
  },
);
```

Without this feature, I need to move this logic inside the build method of a widget which feels a little bit weird, not maintainable, and also error-prone when feature-widget grows in complexity.
```dart
  Widget build(BuildContext context, WidgetRef ref) {
    ref.listen(
      databaseBox(id),
      (value) {
        if (value != null) {
          ref.refresh(providerA(id));
        }
      },
    );
   ...
  }
```

**Comment by TimWhiting** [comment]
Listen should be able to do what you want.

```dart
final providerA = StateNotifierProvider.family<Notifier, State, int>(
  (ref, id) {
    ref.listen<PutYourTypeHere>(databaseBox(id), (last, current){
        if (current != null && current != last){
           // You need to create some update method that will reinitialize your notifier.
           ref.notifier.update(current);
        } 
    }); 
    return Notifier(ref.read, id);
  },
);
```

This is where a `ref.refreshSelf` would come in handy.

**Comment by eli1stark** [comment]
Thanks, Tim for your answer. This was my first thought to put listener inside `providerA` but I got compile-time error:
**The type of 'providerA' can't be inferred because it depends on itself through the cycle: [providerA].
Try adding an explicit type to one or more of the variables in the cycle in order to break the cycle.**

**Comment by TimWhiting** [comment]
```dart
final StateNotifierProviderFamily<Notifier, State, int> providerA = StateNotifierProvider.family<Notifier, State, int>(
  (ref, id) {
    ref.listen<PutTheStateTypeOfYourDatabaseBoxProviderHere>(databaseBox(id), (last, current){
        if (current != null && current != last){
           // You need to create some update method that will reinitialize your notifier.
           ref.refresh(providerA(id));
        } 
    }); 
    return Notifier(ref.read, id);
  },
);
```
Not sure if this actually would work, but this would get rid of the type inference error.

Anyways, closing the issue, watch the other issue to be notified when `ref.listenSelf` is implemented.
