### ISSUE TITLE
Is it ok that we wrap `StateNotifierProvider` in order to take any provider depending on the provider state?

### ISSUE THREAD

**Issue by takassh** [rrousselGit/river_pod#1218]
**Describe what scenario you think is uncovered by the existing examples/articles**
N/A

**Describe why existing examples/articles do not cover this case**
N/A

**Additional context**
This is just a question about how to use the `StateNotifierProvider`.
I want to get any provider depending on the provider state.
To achieve this, I wrote the following code.

<details>
<summary>Example Code</summary>

```
final profileProvider = _ProfileProviderBuilder();

class _ProfileProviderBuilder {
  var _myProfileStateNotifierProvider =
      StateNotifierProvider<ProfileStateNotifier, ProfileState>(
    (ref) => ProfileStateNotifier(ref.read, null),
  );

  final _othersProfileStateNotifierProvider =
      Provider.family<ProfileStateNotifier, String>(
    (ref, name) => ProfileStateNotifier(ref.read, name),
  );

  StateNotifierProvider<ProfileStateNotifier, ProfileState> call(String? name) {
    return StateNotifierProvider.family<ProfileStateNotifier, ProfileState,String?>(
      (ref, name) {
        if (name == null ||
            name == ref.read(_myProfileStateNotifierProvider).user?.name) {
          return ref.read(_myProfileStateNotifierProvider.notifier);
        } else {
          return ref.read(_othersProfileStateNotifierProvider(name));
        }
      },
    ).call(name);
  }
}
```

</details>

**explanation**
`ref.read(_myProfileStateNotifierProvider).user?.name` can be changed.
If `name` is null or equals `ref.read(_myProfileStateNotifierProvider).user?.name`, it returns `ref.read(_myProfileStateNotifierProvider.notifier)`. Therefore, `profileProvider(null)` returns `ref.read(_myProfileStateNotifierProvider.notifier)`

actually, the above code works well as expected, but I am concerned if this is an unintended behavior of `riverpod`.
or if you have another way to achieve that, I'd like to know about it. 

Thank you.

**Comment by rrousselGit** [comment]
That's not something I would recommend doing as it's unclear whether this will forever keep working.

If your "_ProfileProviderBuilder" is only used once on profileProvider, your code should be alright.

But you should update the `call` to store the `StateNotifierProvider.family` as a field of the class
