### ISSUE TITLE
How to overriding providers works

### ISSUE THREAD

**Issue by hamishjohnson** [rrousselGit/river_pod#1220]
**Describe what scenario you think is uncovered by the existing examples/articles**
Overrides are not covered at all in the docs, but they are in the todo example.

**Additional context**
I'd like to have an initial provider that provides a non-nullable user to the rest of my app. I'm doing this by overriding a provider like so:

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final providerContainer = rp.ProviderContainer();

  setupLocator();

  final purchaseService = providerContainer.read(purchaseServiceProvider);

  await Future.wait([
    initFirebase(),
    purchaseService?.setup() ?? Future(() {}),
  ]);

  runApp(rp.ProviderScope(child: AuthGate()));
}

class AuthGate extends rp.ConsumerWidget {
  const AuthGate({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, rp.WidgetRef ref) {
    final authService = ref.watch(authServiceProvider);

    return StreamBuilder<AppUser?>(
      stream: authService.userStream,
      builder: (context, snapshot) {
        if (snapshot.hasError)
          return MaterialApp(home: Scaffold(body: ErrorView()));

        if (snapshot.connectionState == ConnectionState.waiting)
          return Center(child: CircularProgressIndicator());

        final user = snapshot.data;

        // User is not signed in
        if (user == null) {
          return MaterialApp(
            home: SignInScreen(
              providerConfigs: [
                EmailProviderConfiguration(),
              ],
              footerBuilder: (_, action) => ElevatedButton(
                onPressed: authService.signInAnonymously,
                child: Text('Continue as guest'),
              ),
            ),
          );
        }

        return ProviderScope(
          overrides: [
            userProvider.overrideWithValue(user),
          ],
          child: MyApp(user),
        );
      },
    );
  }
}
```
        
Then, down the widget tree, I call another provider that depends on userProvider:

```
final promptsProvider = StateNotifierProvider<PromptStore, List<Prompt>>(
  (ref) => PromptStore(ref.read, ref.watch(userProvider)),
);

class PromptStore extends StateNotifier<List<Prompt>> {
  final Reader _reader;

  Stream<List<Prompt>>? _stream;

  PromptStore(this._reader, AppUser user) : super([]) {
    if (_stream == null) {
      _stream = _reader(promptsServiceProvider).stream(user)
        ..listen((prompts) {
          state = prompts;
        });
    }
  }
}
```

This doesn't work, and I get an error "Tried to read Provider<List<Prompt>>#f79a5 from a place where one of its dependencies were overridden but the provider is not."

I tried adding a dependency like so:

```
final promptsProvider = StateNotifierProvider<PromptStore, List<Prompt>>(
    (ref) => PromptStore(ref.read, ref.watch(userProvider)),
    dependencies: [userProvider]);
```

But that didn't work. I thought that since promptsProvider is read after userProvider has been overridden, that it would be readable.

**Comment by TimWhiting** [comment]
Why didn't this work? Any details?
```dart
final promptsProvider = StateNotifierProvider<PromptStore, List<Prompt>>(
    (ref) => PromptStore(ref.read, ref.watch(userProvider)),
    dependencies: [userProvider]);
```
I'm assuming you are reading other providers in `PromptStore` with your ref.read that you pass in, you need to make sure each of those providers are also in the dependencies list.

**Comment by hamishjohnson** [comment]
I tried passing promptsServiceProvider(theres no others)... do I also have to add any that the depencies depend on? 

i edited my post with the actually main function. you can see that I use 2 ProviderScopes... would that make a difference?

**Comment by hamishjohnson** [comment]
> Why didn't this work? Any details?

It just has the same message: 

Tried to read Provider<List<Prompt>>#4a026 from a place where one of its dependencies were overridden but the provider is not.

To fix this error, you can add add "dependencies" to Provider<List<Prompt>>#4a026 such that we have:

```
final a = Provider(...);
final b = Provider((ref) => ref.watch(a), dependencies: [a]);
```

**Comment by TimWhiting** [comment]
No you don't have to add any transitive dependencies in the list for promptsProvider, but you might have to add them to the dependency list of promptsServiceProvider. Once you start using the parameter it requires being more explicit about dependencies. Adding a name for the providers will help you debug so you can see what provider is the issue rather than just seeing `Provider<List>#4a026`

```dart
final b = Provider((ref) => ref.watch(a), dependencies: [a], name: 'bProvider');
```
Multiple provider scopes should not matter.
