### ISSUE TITLE
Question: Nesting Providers

### ISSUE THREAD

**Issue by fabriciovergara** [rrousselGit/river_pod#1222]
**Describe what scenario you think is uncovered by the existing examples/articles**

I would like to understand downside of nesting providers. 

By reading the source code as far I understood the value of a provider is held in the ProviderContainer, which I would suppose that if **authFeature** in my example changes due to a **buildInfo** modification, then the **authenticator**  value from the previous **authFeature** will stay inside the **ProviderContainer** forever. 

Is this right?

**Describe why existing examples/articles do not cover this case**
```dart
      
final authFeature = Provider<AuthFeature>((ref) {
  final buildInfo = ref.watch(buildInfo); 
  return AuthFeature(buildInfo);
});

class AuthFeature extends AppFeature {
  
  final authenticator = Provider<Interceptor>((ref) {
    return Authenticator()
  });

}

final httpClient = Provider<Dio>((ref) {
  final authenticator = ref.watch(ref.watch(authFeature).authenticator);
  final dio = Dio();
  dio.interceptors.add(authenticator);
  return dio;
});

```

**Additional context**

I'm just trying to build a skeleton project using **Riverpod** and **Melos** in order to create a mult feature module project. 

packages
|_app ->  minimal native and dart code
|_app_impl -> the actual app code
|_feature_auth -> API module for auth feature
|_feature_auth_impl -> Impl for the auth feature

If you think of it, this nesting would be a great replacement for MobX 🙂

**Comment by rrousselGit** [comment]
Providers should **always** be static or gobals.  
By doing what you're doing here, you're exposing yourself to memory leaks.
