### ISSUE TITLE
autoDispose even if there is a listener next screen

### ISSUE THREAD

**Issue by robpot95** [rrousselGit/river_pod#1228]
**Describe the bug**
I'm setting the `counterState = 10` and next page the `counterState = 0` Due to `autoDispose` it cause the `stateProvider` dispose. Even tho you switch page directly after you set the state. Which seems weird if you ask me, since we listen to the `stateProvider` at next screen, so why dispose it even before checking if there is still a listener.

**To Reproduce**
```
final counterProvider = StateProvider.autoDispose<int>((_) => 0);

class Screen1 extends ConsumerWidget {
  const Screen1({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Center(
      child: ElevatedButton(
        child: const Text("Press me"),
        onPressed: () {
          ref.read(counterProvider.state).state = 10;
          Navigator.push(context, MaterialPageRoute(builder: (context) => const Screen2()));
        },
      ),
    );
  }
}

class Screen2 extends ConsumerWidget {
  const Screen2({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final counter = ref.watch(counterProvider);
    return Center(
      child: Text(counter.toString()),
    );
  }
}
```

**Expected behavior**
Counter should be 10 and not dispoed so Quick when there is still a listener on the other screen

**Comment by robpot95** [comment]
What happens if the route does not load in e.g 5 seconds and if you fetch data from website and you would like it to dispose immediately after it's unused. But set it before you switch route, what can you do then?

**Comment by rrousselGit** [comment]
I do not understand the case you're referring to. Can you make an example?

But I'd suggest trying cacheTime. You should be able to see for yourself if it solves your issue

**Comment by robpot95** [comment]
We had the discussion about this on Discord, cacheTime solve the issue, but you told me it was not meant for this and you had something else on mind to fix this.

This is a simple example, but there is cases where i would like to fetch things from an API on one screen through initState and pass the value to the `stateProvider` then switch screen immediately after to the new screen with that value being used. But autoDispose clear the value, even tho screen2 is listening for the provider

**Comment by rrousselGit** [comment]
> We had the discussion about this on Discord, cacheTime solve the issue, but you told me it was not meant for this and you had something else on mind to fix this.

The scenario we discussed before was different.

This one is solved by cacheTime.

**Comment by robpot95** [comment]
Ah okay, but i opened issue, just to have it as a reminder for you. What should i write, so i can remind you about this situationen we talked about in discord

**Comment by rrousselGit** [comment]
There's no need for a reminder. It's part of my 2.0.0 todo-list, so it'll come.

**Comment by robpot95** [comment]
Oh okay, sorry for wasting your time here. I really appreciate your work
