### ISSUE TITLE
Todo example is confusing without implementing Equatable

### ISSUE THREAD

**Issue by dgaedcke** [rrousselGit/river_pod#1233]
I'm confused by this line:
final _currentTodo = Provider<Todo>((ref) => throw UnimplementedError());

in this Todo example:
https://github.com/rrousselGit/river_pod/blob/7322869b914b74d005fe98e1adb7f91358769afc/examples/todos/lib/main.dart#L239

Since the Todo model does not implement Equatable, how can the provider know when properties of the value have changed??   If it were a state-provider, and you replaced the whole state, I could see that working, but if you just edit some property on the Todo record, I'm baffled as to how RP can detect that change and rebuild the row???

Thanks for any clarification you can provide.

**Comment by dgaedcke** [comment]
Oh, from studying 
class TodoList extends StateNotifier<List<Todo>> {}

it seems clear it is not rebuilding the row alone ... it's rebuilding the whole list
so this logic:
`child: ProviderScope(
                  overrides: [
                    _currentTodo.overrideWithValue(todos[i]),
                  ],
                  child: const TodoItem(),`
is getting a brand new value when that entire list rebuilds

I'm guessing if I wanted ONLY the edited row to rebuild, I would need to use Provider.family for each todo.id ... is that correct??

**Comment by rrousselGit** [comment]
There's rarely a need to override == in the models exposed by a provider.

Since models are immutable, the content of an instance change.
So unless you're explicitly cloning a Todo, the reference on a Todo instance won't change.

Meaning that the previous and new Todo would be "identical" if their content is the same

So no need for overriding ==

**Comment by rrousselGit** [comment]
> it seems clear it is not rebuilding the row alone ... it's rebuilding the whole list

That isn't the case.

Only the item changed rebuild. The snippet given is here for filtering changes on todos that are not modified using the logic previously mentioned.

**Comment by dgaedcke** [comment]
I'm trying really hard to understand and follow your points (I hope I'm not a pain), so let me play back what I understand so far:

I believe you meant to say:
_Since models are immutable, the content of an instance **CANNOT** change._

And since you are saying we don't need to implement ==, that tells me that RP must be using the object reference, and not the object contents for comparison.

If thats true, then we'd always need to REPLACE the "watch()ed" object with a new one (not counting notifier providers) to force a rebuild.  Is that correct??

Thats what you are doing (replacing the Todo) in this line of code ...
https://github.com/rrousselGit/river_pod/blob/7322869b914b74d005fe98e1adb7f91358769afc/examples/todos/lib/todo.dart#L57

But since you are RE-ASSIGNING the TodoList state, that must be firing a rebuild of the whole TodoList since it's a StateNotifier<List<Todo>>

In this line of code
https://github.com/rrousselGit/river_pod/blob/7322869b914b74d005fe98e1adb7f91358769afc/examples/todos/lib/main.dart#L239
that NEW (just added) Todo is NOT the one being watched ... the one being watch is the old Todo which is now pending garbage collection
https://github.com/rrousselGit/river_pod/blob/7322869b914b74d005fe98e1adb7f91358769afc/examples/todos/lib/main.dart#L121

I guess you saying it's the garbage collection (reference invalidation) that's forcing rebuild of the row ... is that correct??   If not, can you describe how RP knows this old Todo has "changed"??

And I still don't understand how you can say the WHOLE list is not being rebuild when you are re-assigning the state in that object on EVERY edit.

I hope this is clear and I hope a deeper understanding will reduce support tickets in the future ...

**Comment by rrousselGit** [comment]
I'd suggest running the code and putting prints in the TodoItem

**Comment by dgaedcke** [comment]
yes of course ... I trust that you are right ... you are vastly more experienced than me.
I'm trying to get UNDERSTANDING of how it works ... WHY are you right, given the assignment of state to the list container upon edit???

**Comment by dgaedcke** [comment]
I've been testing and debugging, and one thing has become clear, but the rest of this behavior is still quite baffling to me.

What is clear is that the "const TodoItem" constructor is doing a lot of the work here.  It does prevent other rows from rebuilding.  
I'm guessing thats due to the change in value stored at " _currentTodo.overrideWithValue(todos[i]) " ... so the provider is watching the reference!!  Is that correct??

What's completely baffling is that each time we edit (replace) a Todo instance, we RE-ASSIGN the whole list-state ... and yet this print inside that StateNotifier provider never fires ...
 I thought that was the whole point of a StateNotifier was to rebuild when it's state was re-assigned???

`final todoListProvider = StateNotifierProvider<TodoList, List<Todo>>((ref) {
  print('**** rebuilding todoListProvider  (this never fires)');
  return TodoList(const [
    Todo(id: 'todo-0', description: 'hi'),
    Todo(id: 'todo-1', description: 'hello'),
    Todo(id: 'todo-2', description: 'bonjour'),
  ]);
});`

Please tell me what I'm missing here ... the suspense is killing me!!

**Comment by TimWhiting** [comment]
The provider never rebuilds but the notifier does. Otherwise it would recreate a new TodoList. Personally I would have called it TodoListNotifier instead of TodoList. Anyways, watching the todoListNotifier listens to the StateNotifier created by the provider. That gets it's state reassigned (take a look at todo.dart)

**Comment by dgaedcke** [comment]
Thanks Tim!
If I'm tracking you correctly, you are saying that:
     final todos = ref.watch(todoListProvider);
is paying attention ONLY to the notifier object inside the StateNotifierProvider ... and so a StateNotifierProvider won't really ever rebuild unless someone calls "refresh" on it  (or after its g-collected and then re-listened) ...  Do I have that right??

But since a new Todo was created during edit, I would suspect that:
    final todos = ref.watch(filteredTodos);
should be returning a DIFFERENT list ... and I would think that would cause everything under that line to rebuild.   And when I remove the "const" constructor on TodoItem, that's what happens ... the whole list rebuilds.  So it seems it's the "const" doing the work here ... and not Riverpod??

So we are re-running this loop after each edit of a Todo record:
   for (var i = 0; i < todos.length; i++) ...[
But because of the cons constructor, only one row has to repaint

Can you clarify (if you know) ... is this line 
  final todo = ref.watch(_currentTodo);
tracking the:
a) reference to a Todo instance  (my guess is yes)
b) copy of the Todo value itself  (seems impossible given Todo is not equatable)
c) index position in the list of todos (from where the overrideWithValue() occurs)
`     child: ProviderScope(
                  overrides: [
                    _currentTodo.overrideWithValue(todos[i]),
                  ],
                  child: const TodoItem(),`

And when that Todo instance reference gets invalidated (replaced in the list or garbage collected), then the "class TodoItem extends HookConsumerWidget " marks itself and dirty and needs repainting ... is that right??

In the other rows, the fact that their observed references come back same/intact, means that no repaint is scheduled.

I'm really struggling to understand and hoping I'm getting most of this right ... please advise!!

**Comment by TimWhiting** [comment]
Yes the const does a lot of the work. The watch of `_currentTodo` listens to the overridden provider in the `ProviderScope` which will notify the widget to rebuild when the overridden provider's value changes so when `todos[i]` is a different value (i.e. reference).

Yes, const widgets if created using the const constructor do not rebuild unless something internal marks as dirty. Riverpod allows you to seemingly have 'different' instances of the same 'const' widget. In reality their widget is basically a const 'blueprint' with no mutable state, but the `ConsumerWidget` has a stateful widget under the hood in which riverpod manages the subscriptions (but then delegates to the consumer widget's build method). So they do in actuality have different state objects. Does that make sense?

**Comment by dgaedcke** [comment]
Yes, this is really helpful!!
The key takeaways are:
1. that RP is watching references, not values / Equatable
2. re-assignment of state DOES cause a full rebuild of the tree below it ... but
3.  const don't repaint until self-requested 
4. I should study the RP source ... although it seems the Flutter bits might be harder to follow if I first didn't understand the base library

Really appreciate your help here!!

**Comment by rrousselGit** [comment]
> that RP is watching references, not values / Equatable

Riverpod uses ==

It's just that by default == is a reference comparison – which works for most cases.

**Comment by dgaedcke** [comment]
Thanks Remi ... and for the future, when talking to noobs, it might help to call out the distinctions involved between tree re-evaluation, and repainting when const widgets are involved

In our first discourse, I misinterpreted you to be saying that the list-build-loop was not re-running when that list-state was re-assigned.  And of course it was, it's just that Flutter was smart enough not to re-evaluate rows that declined to mark themselves dirty.

That distinction cleared everything up for me ... hope it saves you time in the future when chatting with slow people like me :-)
