### ISSUE TITLE
Install hooks_riverpod problem

### ISSUE THREAD

**Issue by anas-aw** [rrousselGit/river_pod#124]
flutter_hooks: ^0.14.0
  hooks_riverpod: ^0.10.1

pub get ---->
 
output : 
Because riverpod depends on hooks_riverpod ^0.10.1 which depends on riverpod ^0.10.0, riverpod ^0.10.0 is required.
So, because riverpod is 1.0.0+1, version solving failed.
pub get failed (1; So, because riverpod is 1.0.0+1, version solving failed.)

**Comment by rrousselGit** [comment]
Did you name your application "riverpod"?

**Comment by mahmoudalaa97** [comment]
I was have same problem because,  i make the name of app `riverpod` by mistake and when i change the name it work good thank you 😃
