### ISSUE TITLE
why is the variable is printed anew value but not rendered it?

### ISSUE THREAD

**Issue by Abouassi98** [rrousselGit/river_pod#1246]
![image](https://user-images.githubusercontent.com/53384802/155961105-d3b9faba-722c-4384-a4ad-e41dc09e4061.png)
![image](https://user-images.githubusercontent.com/53384802/155958969-3f5b44ad-6e89-44a3-b8c0-3c5133ea1895.png)
![image](https://user-images.githubusercontent.com/53384802/155959024-68029afe-58e4-451a-8916-0c96bcd9aa3e.png)
![image](https://user-images.githubusercontent.com/53384802/155959071-d369520c-d273-4a6f-8b77-4a0d515f8de6.png)

hooks_riverpod: ^2.0.0-dev.4

**Comment by rrousselGit** [comment]
The state of a StateProvider should be immutable

Your problem is that you mutated it. Instead do a clone
