### ISSUE TITLE
Using state and .notifier in the same widget

### ISSUE THREAD

**Issue by sderungs99** [rrousselGit/river_pod#1248]
Suppose I have a counter widget, which has a button that increments the counter, and also shows the number of times the button has been clicked. And suppose that I have created a StateNotifierProvider `myStateNotifierProvider`, which holds the number of times the button has been pressed as state, as well as the method to increment the counter.

In such a case, what is the recommended method to show the state and also get a reference to the StateNotifierProvider for the increment method?

In my code, I currently do something like this:

```dart
@override
  Widget build(BuildContext context, WidgetRef ref) {
    final vmState =
        ref.watch(myStateNotifierProvider);
    final vm = ref.watch(myStateNotifierProvider.notifier),
    );
return Column(
  children: [
    Text(vmState),
    ElevatedButton(
      onPressed: () {
        vm.increment();
      },
      child: Text('Increment'),
    )
  ],
);
}
```
Am I doing something completely wrong here, or is this ok? It doesn't "feel" right to me :-)

**Comment by rrousselGit** [comment]
This is ok. There's nothing wrong here :)
