### ISSUE TITLE
Read a provider with .family modifier without adding a parameter

### ISSUE THREAD

**Issue by snorreks** [rrousselGit/river_pod#125]
**Describe what scenario you think is uncovered by the existing examples/articles**
Is there a way to read a provider with .family modifier without adding a parameter, instead getting the exiting provider instance? If it is not possible is there a better way to tell my app if it is in development or not? I would prefer not initializing stuff in the main() function.

**Describe why existing examples/articles do not cover this case**
Did not found a solution for this case, probably because this is not the right use case for .family modifier.

**Additional context**
Setting the isDevelopment value:
![image](https://user-images.githubusercontent.com/36089469/93303480-cb6d2080-f7fb-11ea-8f31-43332636c508.png)

Creating the applicationProvider:
![image](https://user-images.githubusercontent.com/36089469/93303571-fc4d5580-f7fb-11ea-95f6-4f181f8581eb.png)

Inside my search service, trying to read the applicationProvider:
![image](https://user-images.githubusercontent.com/36089469/93303753-3f0f2d80-f7fc-11ea-8e0c-0d25ef990183.png)

**Comment by snorreks** [comment]
I found a solution where I didn't use the .family modifier, instead I set the isDevelopment after initialization:
![image](https://user-images.githubusercontent.com/36089469/93309428-d035d280-f803-11ea-9e81-0cd98245d839.png)

**Comment by EdwynZN** [comment]
is this good practice tho? I read in the ConsumerWidget `Do not modify any state or start any http request inside [build]` so I don't really know if I should do that in the first place, or maybe I misunderstood the documentation
