### ISSUE TITLE
What happened to BuildContextX?

### ISSUE THREAD

**Issue by nlfiedler** [rrousselGit/river_pod#1256]
Looks like BuildContextX was made to disappear, leaving not a trace. No mention in changelog. Upgraded from 0.14.0+3 and I have no idea what to do now. Any guidance would be much appreciated.

**Comment by rrousselGit** [comment]
See https://riverpod.dev/docs/migration/0.14.0_to_1.0.0/

**Comment by nlfiedler** [comment]
Thanks for writing a tool to make the changes, that was quite unexpected.

As for the doc issue, might it make sense to update the CHANGELOG? I'm referring to `BuildContextX` specifically, which went away without a single trace.

**Comment by nlfiedler** [comment]
BTW, the tool changed a parameter name from `state` to `ref` but did not change the references. What's more, these parameters are for types defined in the `flutter_bloc` package, not riverpod code. Should I file a bug, or is this considered a part of #1193?
