### ISSUE TITLE
AutoDispose Family Provider excessive rebuilding

### ISSUE THREAD

**Issue by davebound** [rrousselGit/river_pod#1267]
Hi All,

flutter_riverpod: ^0.14.0+3

I have a scenario like this:

2 Providers:

1 - apiDataProvider - an autoDispose ChangeNotifierProvider that reads a list of rows from API

2 - chartDataProvider - an autodispose family provider that watches apiDataProvider + does expensive number crunching on it according to the params passed when instantiating the family to produce data for a chart.

The chartDataProvider is consumed (watched) in several chart-drawing widgets: (each using different family parameters to cause number crunching particular to that chart):
- chartWidget1 - watches chartDataProvider (params1)
- chartWidget2 - watches chartDataProvider (params2)
- chartWidget3 - watches chartDataProvider (params3)

These are hosted in a Row widget on the screen.

It all works as expected except that when I resize the screen (its a web build), the 3 family instances of the chartDataProvider provider get disposed + recreated - which causes the expensive number crunching to be redone , even though the data in apiDataProvider didn't change.

I only want chartDataProvider to rebuild when apiDataProvider changes

Hope that makes sense.

Its almost as though I shouldn't be using autoDispose and yet the docs for family say I should.

What am I doing wrong?

Many thanks.

**Comment by rrousselGit** [comment]
Chances your family's parameter class does not override ==. See https://riverpod.dev/docs/concepts/modifiers/family#parameter-restrictions

**Comment by davebound** [comment]
Thank you Remi, you are a genius! I was overriding == but there was a bug in my code. Now using Equatable and all working :-)
