### ISSUE TITLE
Grammar fixes

### ISSUE THREAD

**Issue by albertodev01** [rrousselGit/river_pod#128]
Missing "to" in the [Getting started](https://riverpod.dev/docs/getting_started)

  > A way **to** use both...

In the same page, you should then add "it":

> And if **it's** not clear enough....

---

In [Performing actions before the state destruction](https://riverpod.dev/docs/concepts/providers#performing-actions-before-the-state-destruction) you should change

 > This is done by using the ref object that is passed to the callback of all providers; using its onDispose method

to

> This is done using the `ref` object, which is passed to the callback of all providers, using its onDispose method.

**Comment by rrousselGit** [comment]
Thanks, done :smile:
