### ISSUE TITLE
StateNotifierProvider unable to use async and await for FutureProvider

### ISSUE THREAD

**Issue by rddewan** [rrousselGit/river_pod#1283]
Unable to call the FutureProvider inside StateNotifierProvider there is no option for sync and await 
```
final settingControllerProvider = StateNotifierProvider.autoDispose<SettingController,SettingState>((ref) {

  final settingService = ref.watch(settingServiceProvider.future);

  final controller =  SettingController(settingService: settingService, state: const SettingState())
  controller..getThemeMode()
    ..getLanguageCode();

  return controller;
  
});
```

**Comment by rrousselGit** [comment]
You should await the future instead your StateNotifier

see https://github.com/rrousselGit/river_pod/issues/57

**Comment by rddewan** [comment]
@rrousselGit  sorry that is not related  to my question .How can we `await` the future in `StateNotifierProvider` 
`StateNotifierProvider.autoDispose<SettingController,SettingState>` i have passed `SettingController` and `SettingState`. I want to await the `FutureProvider` in `StateNotifierProvider`

**Comment by xxmn** [comment]
also noticed this problem. Although it can be solved by other methods, it is the easiest and clearest to use it directly.

**Comment by rddewan** [comment]
@xxmn  how did you do it, i found  `FutureProvider` is useless with `StateNotifierProvider` it does not work , if you want to use `StateNotifierProvider` then only option is to use `Provider` which is not always the case  like with shared preference. If you have a solution please post it here
