### ISSUE TITLE
Why watching future goes to the loading state first?

### ISSUE THREAD

**Issue by terryl1900** [rrousselGit/river_pod#1292]
**Describe the bug**
I just switched my app from flutter_bloc to river_pod and I'm pretty happy. Thank you for the wonderful work.

However, I did notice one issue. I'm chaining a lot of stream providers and find that using `await ref.watch(stream_provider.future)` goes to the loading state first, even though the data is already available. See the below simple repro.

**To Reproduce**
<details><summary>Code</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

class Logger extends ProviderObserver {
  @override
  void didUpdateProvider(
    ProviderBase provider,
    Object? previousValue,
    Object? newValue,
    ProviderContainer container,
  ) {
    debugPrint('${provider.name}, $newValue');
  }
}

Stream<String> text() async* {
  yield 'hello';
  await Future.delayed(const Duration(seconds: 1));
  yield 'hello again';
}

final textProvider = StreamProvider((ref) => text(), name: 'text');

final firstProvider = StreamProvider((ref) async* {
  final text = await ref.watch(textProvider.future);
  yield 'first $text';
}, name: 'first');

final secondProvider = StreamProvider((ref) async* {
  final text = await ref.watch(firstProvider.future);
  yield 'second $text';
}, name: 'second');

void main() {
  runApp(ProviderScope(observers: [Logger()], child: const MyApp()));
}

class MyApp extends ConsumerWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final text = ref.watch(secondProvider);
    debugPrint('MyApp: ${text.toString()}');
    return Container();
  }
}
```

</details>

<details><summary>Log output</summary>

```
flutter: MyApp: AsyncLoading<String>()
flutter: text, AsyncData<String>(value: hello)
flutter: first, AsyncData<String>(value: first hello)
flutter: second, AsyncData<String>(value: second first hello)
flutter: MyApp: AsyncData<String>(value: second first hello)
flutter: text.future, Instance of 'Future<String>'
flutter: text, AsyncData<String>(value: hello again)
flutter: first.future, Instance of 'Future<String>'
flutter: first, AsyncData<String>(isLoading: true, value: first hello)
flutter: second, AsyncData<String>(isLoading: true, value: second first hello)
flutter: MyApp: AsyncData<String>(isLoading: true, value: second first hello)
flutter: first, AsyncData<String>(value: first hello again)
flutter: second, AsyncData<String>(value: second first hello again)
flutter: MyApp: AsyncData<String>(value: second first hello again)
```

</details>

As you can see from the log. Even though we got `hello again`, `firstProvider` and `secondProvider` went to loading state first, which in my mind is totally unnecessary. They should have the data already.

This is problematic that the app might show an unnecessary progress indicator if it responds to `isLoading` field.

Related question, what's the difference between `isLoading` in `AsyncData` vs `AsyncLoading`?

**Comment by rrousselGit** [comment]
> even though the data is already available.

It isn't

Streams/Futures emit their value asynchronously. Riverpod doesn't have access to the value


See:

```dart
print('before');
Stream.value(42).listen((value) {
  print('got value $value');
});
print('after');
```


For Riverpod to be able to send the data immediately, the logs should be:

```
before
got value 42
after
```

but the logs are instead

```
before
after
got value 42
```

**Comment by rrousselGit** [comment]
> Related question, what's the difference between isLoading in AsyncData vs AsyncLoading?



isLoading will be false within an AsyncData. It's here for the same of being able to do:

```dart
AsyncValue value;
if (value.isLoading) {

}
```

**Comment by terryl1900** [comment]
Thanks for the quick reply. I understand the async nature of stream/future. Though I thought `watch(stream_provider.future)` could be more synchronized than today.

Take a step back, I thought my use case is quite common. Say I have a stream from some data source (firebase, API), like `loading, data_1, data_2, ...`. Then I need a bunch of providers to transform the data into other data models like `loading, transformed_data_1, transformed_data_2, ...`. I don't want an extra loading state when dealing with transformed data.

The way I do it now is to use `await watch(stream_provider.future)` then `yield`. Do you have other suggestions on how to achieve the goal?

I'm reading the source code. I feel that perhaps `AsyncValueAsFutureProvider` should be designed to work with stream specific, rather than a general AsyncValue. I could be totally wrong since I'm still actively reading.

**Comment by terryl1900** [comment]
Actually, I think I might be silly. It seems just using `watch(stream_provider.stream)` then `yield` could work.

```
final firstProvider = StreamProvider((ref) async* {
  await for (final text in ref.watch(textProvider.stream)) {
    yield 'first $text';
  }
}, name: 'first');
```

**Comment by terryl1900** [comment]
Actually I think I can achieve my goal just using `watch(stream_provider.stream)`. Though I still feel `stream_provider.future` should work, meaning it reads the last value of a stream, then continuous feeding new values as they come.

For example, I'm combing two streams to generate a new stream. I can do:
```
final thirdProvider = StreamProvider((ref) async* {
  await for (final a in ref.watch(firstProvider.stream)) {
    await for (final b in ref.watch(secondProvider.stream)) {
      yield '$a with $b';
    }
  }
}, name: 'third');
```

**Comment by rrousselGit** [comment]
You can already do that (although a FutureProvider is more appropriate). I don't see the problem

**Comment by terryl1900** [comment]
The problem is the [above](https://github.com/rrousselGit/river_pod/issues/1292#issuecomment-1073407155) example, `thirdProvider` generate a lot `isLoadind` states. What I want is just data state whenever `firstProvider` or `secondProvide` has a new value. How can I achieve that? And what do you mean by a FutureProvider is more appropriate?

**Comment by rrousselGit** [comment]
Right, but `await Future.value(42)` isn't synchronous. So you'll have to go through a loading state

**Comment by terryl1900** [comment]
Hmm, but a `StreamBuilder` calls build N+2 times for a stream with N data, not 2N+2 times.

**Comment by terryl1900** [comment]
Reading from the source code, I guess my question is equivalent to:

Why don't we put this [subscription](https://github.com/rrousselGit/river_pod/blob/2af0f87099c9dadac1081928c0acc0d87b43d5bb/packages/riverpod/lib/src/stream_provider.dart#L76) in ProviderElementBase and re-use it, and avoid `return AsyncValue<State>.loading();` when data is already available.

**Comment by rrousselGit** [comment]
StreamProvider vs StreamBuilder when using the same stream rebuild the same number of times.

Your issue is that you're using a different stream/future mechanism, where instead of a single stream that emits a new value when dependents updates, you create a new stream/future whenever a dependency changes.


As proof, if you were to not use a stream/future at all, this is issue wouldn't be a thing:

```dart
final thirdProvider = Provider<AsyncValue<String>>((ref) {
  final a = ref.watch(firstProvider);
  final b = ref.watch(secondProvider);
  if (a.isLoading || b.isLoading) return AsyncLoading();

  return '${a.value!} with ${b.value!}';
}, name: 'third');
```

**Comment by rrousselGit** [comment]
> Why don't we put this [subscription](https://github.com/rrousselGit/river_pod/blob/2af0f87099c9dadac1081928c0acc0d87b43d5bb/packages/riverpod/lib/src/stream_provider.dart#L76) in ProviderElementBase and re-use it, and avoid `return AsyncValue<State>.loading();` when previous state is a data state.

Reusing it doesn't make sense. The stream wouldn't emit new values, it's done

**Comment by terryl1900** [comment]
Oh, I misunderstood the future mechanism. Thanks for the explanation! 

Though I'm now confused why `stream_provider.future` exists?

The example in the doc
```
final productsProvider = FutureProvider<Products>((ref) async {
  final configs = await ref.watch(configsProvider.future);

  final response = await httpClient.get('${configs.host}/products');
  return Products.fromJson(response.data);
});
```

Isn't it always better to use this since FutureProvider has a default loading state anyway.
```
final productsProvider = Provider<AsyncValue<Products>>((ref) async {
  final configs = await ref.watch(configsProvider);
  if (configs.isLoading) return AsyncLoading();

  final response = await httpClient.get('${configs.host}/products');
  return AsyncData(Products.fromJson(response.data));
});
```

**Comment by rrousselGit** [comment]
You cannot use `async/await` if you use the `Provider<AsyncValue>` approach, so that's fairly restricting.

And the extra rebuilds caused by the FutureProvider+async/await variant hardly matters. They aren't causing extraneous network requests, it's just a few unnecessary rebuilds.

**Comment by terryl1900** [comment]
I see. I still need `async/await` in most cases, so I need to use Future/StreamProvider. I found that I can avoid extra loading by changing the provider_base [here](https://github.com/rrousselGit/river_pod/blob/2af0f87099c9dadac1081928c0acc0d87b43d5bb/packages/riverpod/lib/src/framework/provider_base.dart#L294) to:

```
    if (newState is AsyncValue && previousResult != null) {
      final previousState = previousResult.requireState as AsyncValue;
      if (newState.isLoading && previousState.isLoading) {
        return;
      }
      if (newState.isLoading && previousState.hasValue) {
        return;
      }
      if (newState.hasValue &&
          previousState.hasValue &&
          newState.value == previousState.value) {
        return;
      }
      newResult = Result<State>.data(
        newState.copyWithPrevious(previousState) as State,
      );
    } else {
      newResult = Result.data(newState);
    }
```

Then this example works properly:

```
Stream<String> text() async* {
  yield 'hello';
  await Future.delayed(const Duration(seconds: 1));
  yield 'bye';
}

final textProvider = StreamProvider<String>((ref) => text(), name: 'text');

final firstProvider = FutureProvider((ref) async {
  final text = await ref.watch(textProvider.future);
  return 'first $text';
}, name: 'first');

final secondProvider = FutureProvider((ref) async {
  final text = await ref.watch(textProvider.future);
  return 'second $text';
}, name: 'second');

final thirdProvider = FutureProvider((ref) async {
  final a = await ref.watch(firstProvider.future);
  final b = await ref.watch(secondProvider.future);
  return '$a with $b';
}, name: 'third');
```

I probably missed some details, but how do you like this change at high level?

**Comment by rrousselGit** [comment]
Widgets rebuilding to have a loading state is expected. It shouldn't be removed
You've effectively removed the ability for widgets to show a progress indicator while a future is recomputed

That's not the proper solution. What we really want is a synchronous future.

The closest feature is Flutter's SynchronousFuture. The problem is, SynchronousFuture isn't composable.

While doing:

```dart
final value = await SynchronousFuture(42);
```
indeed makes the await synchronous

The real problem is, the future created using `async` will **not** be synchronous. So this actually doesn't change anything

I've requested a bunch of times for a Dart update to fix this but to no avail.

**Comment by terryl1900** [comment]
> removed the ability for widgets to show a progress indicator while a future is recomputed

Perhaps we don't want to remove the ability for all FutureProvider, but it definitely makes more sense for StreamProvier, StreamProvider.future or other FutureProvider baked by streams. In most cases, streams are generated independent of user interaction, and showing a progress indicator would be weird. 

As a user, when I write `await ref.watch(streamProvider)` or `await ref.watch(streamProvider.future)`, I'm expecting `loading, data1, data2, data3...` rather than `loading, data1, loading, data2, loading, data3...`.

It would be nice to add an option to allow users to configure this.

**Comment by rrousselGit** [comment]
You can do that if you want by making a single stream (implicitly meaning you won't use ref.watch)

I don't think I can agree with your suggestion.

To begin with, the difference between streamprovider vs futureprovider vs ... is meant to disappear.
As soon as we have metaprogramming, we'll have only a single kind of provider instead of so many variants.

**Comment by terryl1900** [comment]
> implicitly meaning you won't use ref.watch

Not following this, do you mean using vanilla stream rather than rivperpod?

> difference between streamprovider vs futureprovider vs ... is meant to disappear

Sounds to me that riverpod's philosophy is to model state as a stream of data, in this case, a stream of AsyncValue. As a user, I hope to control how my data is generated, regardless the data is int, string, or AsyncValue.

I think I have made my points clear. If you are still not convinced. I'm happy to close the issue and just maintain my own fork.

**Comment by rrousselGit** [comment]
Well, we agree on the problem. What we disagree on is the solution and the importance of the problem
I see this as a fairly minor inconvenience. And skipping loading state sounds quite harmful to me.


And Riverpod isn't expressing a stream of data. It's a different mechanism that is not event based and where a value can already be synchronously obtained. It's voluntarily different from streams.
For example in Riverpod something like `ref.watch(provider.where(...))` would not make sense.

**Comment by rrousselGit** [comment]
:wave: @terryl1900 

Coming back to this, is it fair to say that your issue is that you don't want widgets to rebuild during `AsyncValue.isRefreshing`?

**Comment by terryl1900** [comment]
It is not a state-change in my mind if we were thinking of a stream of data. When I listen to a provider A, its dependencies should be abstracted away from the user. One of its dependency changes, why do I care and need to force to look at a `loading` state?

**Comment by rrousselGit** [comment]
It depends on how you do it. You're fusing all the pages into a single big list. I typically wouldn't do that (cf Marvel/StackOverflow examples).

If you're fusing all pages into one big list, you'd probably be using StateNotifier or something similar too. So you would be able to do what you want with the loading state

**Comment by gruvw** [comment]
Hey, sorry to bump this, but I am running into this exact issue right now.

I did not find a solution to this problem and the select clause proposed in https://github.com/rrousselGit/riverpod/issues/1292#issuecomment-1142345462 (`.select((value) => value.asData)`) does not really solve the problem as it still emits `null` when it is in the loading state.

> I'm expecting loading, data1, data2, data3... rather than loading, data1, loading, data2, loading, data3....

This is exactly what I am looking for.
Another way to say it is that I would like the provider to cache the old data while loading for the new one.

This makes perfect sense from a UI perspective, as you don't might want to keep showing the old data to users while fetching an update (instead of wiping everything and showing a spinner for a few seconds).

Is there a solution to this problem ? ty

**Comment by artahc** [comment]
I've also encountered this issue today. Basically i have provider A which will do a network polling every few seconds and updates its state, and also I have provider B which `watch` the provider A's future. But every time provider A updates its state, the provider B state will become `AsyncLoading` before receives its value. 

I would suggest adding a option in `ref.watch` as in `AsyncValue.when` for skipLoadingOnRefresh & skipLoadingOnReload for the users to decide. Is this viable?

**Comment by v21** [comment]
I just ran into this issue as well - I'm using a FutureProvider to handle access to some data generated by a FutureOr<> function - in the case where the function returns synchronously, the FutureProvider means I still get a frame of loading state before the result gets returned. This wouldn't be too much of a problem - except this means that Hero animations aren't working, because they need their destination target to be in place on the first frame. I suspect this is also why some CachedNetworkImages look a little janky - I set them up so that they do a transition from a loading spinner to displaying the real image, and the frame of loading state triggers the transition.

**Comment by gruvw** [comment]
Letting you know that https://github.com/rrousselGit/riverpod/pull/4409 now solves this issue:

> this enables combining asynchronous providers in a synchronous manner

```dart
final thirdProvider = FutureProvider<String>((ref) {
  final a = ref.watch(firstProvider).requireValue;
  final b = ref.watch(secondProvider).requireValue;
  return "$a with $b";
});
```

> I'm expecting loading, data1, data2, data3... rather than loading, data1, loading, data2, loading, data3....

We can now have `loading, data1, data2, data3` using `.requireValue` 🚀

See https://github.com/rrousselGit/riverpod/issues/4009 for more details, thought it might interest those who posted here too.

**Comment by AlexeyKatsuro** [comment]
@gruvw 
> final thirdProvider = FutureProvider<String>((ref) {
>   final a = ref.watch(firstProvider).requireValue;
>   final b = ref.watch(secondProvider).requireValue;
>   return "$a with $b";
> });

I think this approach may be a bit inefficient in some cases — for example, if `firstProvider` or `secondProvider` are not yet ready, you’ll immediately get an error.


In the approach I proposed in https://github.com/rrousselGit/riverpod/issues/4009#issuecomment-3007899688, you can safely combine asynchronous providers while keeping full flexibility. Each dependency may or may not be ready yet, and you can still perform additional synchronous or asynchronous operations inside your provider.
At the same time, if the entire chain is already resolved, the value can be returned synchronously.

Here’s how your example could look using pattern with `watchSync` and `ref.returns`:

```dart
final thirdProvider = FutureProvider<String>((ref) async {
  final a = await ref.watchSync(firstProvider);
  final b = await ref.watchSync(secondProvider);
  // additional async work here if needed or sync return as below
  return ref.returns('$a with $b');
}
```

This way, you can safely build a chain of asynchronous providers that can still resolve synchronously if all dependencies are already ready.

Note: The code above is not just a concept — these are fully working extensions (for Riverpod v2.6.1).
You can find their implementation in my [original comment](https://github.com/rrousselGit/riverpod/issues/4009#issuecomment-3007899688).
