### ISSUE TITLE
[question] How to get an initialized provider every time user open a page?

### ISSUE THREAD

**Issue by HeavenOSK** [rrousselGit/river_pod#13]
## Question
Would you like to tell me how to dispose Provider when a page is popped, or any solution to get an initialized provider every time user open a page?

I knew Provider is disposed when its owner is disposed, and tried to prepare multi `ProviderScope`s and wrapped a destination page with it. but it’s not working.

```dart
@hwidget
Widget secondPageWithScope() {
  return ProviderScope(
    key: ValueKey('2nd Scope'),
    child: SecondPage(),
  );
}
```
Full code is here:
https://gist.github.com/HeavenOSK/74cb5eb0a3cc01d4d897198e15193986

**Comment by rrousselGit** [comment]
Use AutoDisposeProvider

**Comment by HeavenOSK** [comment]
Thank you. Sorry, I didn't understand.

**Comment by rrousselGit** [comment]
You can remove the extra ProviderScope too

**Comment by HeavenOSK** [comment]
Thank you so much. I removed that.
 
I found that AutoDisposeProvider disposes only if there are no listeners.Very cool feature!
