### ISSUE TITLE
Other way to scope a provider

### ISSUE THREAD

**Issue by XuanTung95** [rrousselGit/river_pod#1300]
**Is your feature request related to a problem? Please describe.**

- **Use case**:  To create a State that only depend on that specific sub-tree, if the sub-tree is removed, the state is also be removed. The sub-tree can use the top-level `ProviderScope` as normal. It's just like you use the `provider package` in that sub-tree.
- Solution 1, using multiple `ProviderScope`: it feels like wrapping the sub-tree in a box and preventing it from reading top-level ProviderScope.
- Solution 2, using `family`: When combine with `autoDispose` it hard to manage when the state is disposed. The state should be disposed with the sub-tree but now it's more complex.

**Describe the solution you'd like**
I was thinking about a feature that make Riverpod works like `provider package`.
Specify a type in ProviderScope
```
ProviderScope(
    type: () => CustomContainer(),
    child: Foo(),
)
```
Instead of creating `UncontrolledProviderScope`, it create `CustomContainer` and store ProviderContainer there
Usage is same as `provider package`:
```
ref.watch<CustomContainer>(myProvider); // find the specific ProviderScope 
ref.watch(myProvider); // find the top-level ProviderScope 
```

**Comment by rrousselGit** [comment]
Why not scope providers the normal way?

**Comment by XuanTung95** [comment]
> Why not scope providers the normal way?

I cannot use the state of the top-level ProviderScope if there are multiple.

**Comment by rrousselGit** [comment]
Why would you need it? If a provider is scoped, why would you need to also access it in the root level?

**Comment by XuanTung95** [comment]
> Why would you need it? If a provider is scoped, why would you need to also access it in the root level?

It's my use case. Some states are global and should be accessed everywhere. Other states are local in a specific sub-tree.
For example, there is a list of users, when click, it open multiple user detail screen, the state inside user detail should be local for each user.

**Comment by rrousselGit** [comment]
Providers that are not scoped will be in located in the root container

So if that's not your case, then you scoped the providers in some way

**Comment by XuanTung95** [comment]
> So if that's not your case, then you scoped the providers in some way

I'm not getting your point.

I'm trying to access the state through multiple ProviderScope, is that possible?

**Comment by rrousselGit** [comment]
That's the current behaviour.

If a provider is not scoped, it will be stored in the root scope.

**Comment by XuanTung95** [comment]
> If a provider is not scoped, it will be stored in the root scope.
I think it's not my case.

I'm looking for more control when using ProviderScope

**Comment by rrousselGit** [comment]
> it's very hard to archive what we want by something that auto. The state can be destroyed and recreated but that maybe not the intention of the developer.

What does that mean exactly? What's the difficulty concretely?



> ProviderScope can be useful to bind the state with the sub-tree. But ProviderScope does not allow to access the state outside.

But you can. Why do you think you can't?

**Comment by XuanTung95** [comment]
> But you can. Why do you think you can't?

I don't know how to do it, could you give an example?

**Comment by rrousselGit** [comment]
Could you rather show an example of your problem instead? Because you haven't shared code related to the problem

**Comment by tbm98** [comment]
@XuanTung95 your problem may be related to this issue #1081.

**Comment by XuanTung95** [comment]
@tbm98 
I don't think so, this is a FR to allow access state between multiple ProviderScope. Not a problem of the current implementation.

**Comment by XuanTung95** [comment]
@rrousselGit 
In v2.0, I can use `invalidate()` method to manually dispose a provider. I can use this to fulfill my needs, which is to control the life-cycle of the state clearly and easily.
I may not need nested ProviderScope anymore.

I close this.

Anyway, I still think autoDispose is a mistake, just like GetX with the auto manage Controller feature. It will cause headaches just to find why the state is disposed and how to keep it alive.

**Comment by rrousselGit** [comment]
> Anyway, I still think autoDispose is a mistake, 

Why? You haven't explained the problem with it yet

**Comment by XuanTung95** [comment]
I used to use GetX for a while. As you may know, it auto manage the controller, it will dispose when think there is no use of controller anymore, like autoDispose. The problem is: the need to use a Controller and the need to keep it in the memory are not the same. When the controller is auto disposed but that's not what I want, I usually move the controller to the upper level to keep it alive longer. That's ambiguous code, it's not clear why I put it there, there is no use of it but it has to be there for a reason. So I rather manage it manually than use auto feature.

Do people usually face the same problem in the issues you closed?

**Comment by rrousselGit** [comment]
Could you expand on when that's a problem? When would a provider be disposed when it shouldn't?
