### ISSUE TITLE
Publish stable version documentation instead of the under development one.

### ISSUE THREAD

**Issue by angelcervera** [rrousselGit/river_pod#1303]
Could you publish the documentation of the stable version instead of the one in the development process?

I had the same issue when you were working on version 1dev. It's difficult to find the right documentation for the stable version 1.0.3 from the website.

Ex. when I see that the [Getting started](https://riverpod.dev/docs/getting_started#installing-the-package) says that I need to add `flutter_riverpod: ^2.0.0-dev.5`, I'm not sure if the rest of the documentation is compatible with the stable version `riverpod: ^1.0.3`

**Comment by rrousselGit** [comment]
The 2.0 doc is compatible with the 1.0 too, so don't worry about it.
