### ISSUE TITLE
Allow executing custom logic on ref.refresh

### ISSUE THREAD

**Issue by DevNico** [rrousselGit/river_pod#1307]
I would like to execute custom logic when `ref.refresh` is called on a `StreamProvider`.

The following example should make my use case clear
```dart
final userProvider = StreamProvider.autoDispose.family<User>((ref, userId) {
  final userRepository = ref.watch(userRepositoryProvider);
  
  ref.onRefresh(() => userRepository.refreshUserById(userId));

  return userRepository.watchUserById(userId);
});
```

The `ref.onRefresh` would take something like `FutureOr<void> Function()`.

Please let me know what you think or if you have a better solution for my problem.

**Comment by rrousselGit** [comment]
Maybe you want to call a method on the `userRepositoryProvider` instead, and have its `watchUserById` stream emit an update

**Comment by DevNico** [comment]
As far as I can tell I basically have a few options already:

- Write a `StateNotifierProvider` that has a `User` as its state and internally watches the stream from my repository as well as exposing a refresh method. This is a lot of boilerplate code just to add the desired refresh functionality.
- Doing a `ref.read(userRepositoryProvider).refreshUserById(42)` in the UI, which just doesn't feel right since I don't really want my repository to be called directly from my UI code
- Implicitly doing the refresh whenever `watchUserById` is called in the repository. (AFAIK the ref.refresh disposes of the `StreamSubscription` and then re-listens to the stream? So this should also theoretically work?) But I may not always want to refresh the data.

The approach described above seems like the best solution to my problem with the least boilerplate code.

**Comment by rrousselGit** [comment]
Boilerplate isn't really a concern.

Both the StateNotifier and invoking functions on the repository are valid. Not the last one though, that's anti pattern.


I'd pick one of those and move on.  The repository one is probably the best currently. 
You can move the logic outside of the UI by creating a function that the UI will invoke, abstracting the repository from the UI 





The StateNotifier variant is probably the way forward. That's what the official solution will be once we have Metaprogramming.

**Comment by DevNico** [comment]
I am not really satisfied with that solution but I guess it works. Thanks for your input.

**Comment by rrousselGit** [comment]
Do note that once we have Metaprogramming, the syntax for the StateNotifier variant will be significantly better than what it would currently require.

So that is the true solution, in a way that would be satisfying.
