### ISSUE TITLE
Add some kind of "transitions" concept on Riverpod

### ISSUE THREAD

**Issue by ldasilva-net** [rrousselGit/river_pod#131]
Hi!
On some inmutable states managements with reactive Event / Action approach they have the possibility for catch all the state changes (in [flutter_bloc](https://bloclibrary.dev) lib they called [Transitions](https://bloclibrary.dev/#/coreconcepts?id=transitions) ) only listening on one specific place. On `flutter_bloc` for example, you can override `onTransition` function on every bloc you have or in a main listener (`BlocObserver`) all state changes for every bloc in your app.
This approach is beatiful for Log / Analytics / reproduce errors for example.

I guess I can solve this by integrating `flutter_bloc` with Riverpod  but I prefeer the built-in providers state solutions with StateNotifier or simple State.
Can we make some similar feature without the need of  `watch` all `Providers` changes?
I think on a new `follow` modifier that "mark" the Provider and `ProviderContainer` or other Riverpod coordinator object watch this marked Providers and fire some callback.

Example:

```dart
final myFollowedProvider = 
	StateProvider.follow<String>(
		key: "providerLogKey", /* a key for identifie provider */ 
		(ref) => "follow me!"
);

void main() {
  runApp(
    ProviderScope(
      child: MyApp(),
      mainTransitions: (ProviderTransition transition) => {
	    /*
	      transitions examples      

	      Example 1
	      {
	        "provider": "providerLogKey",
	        "currentValue": "",
	        "nextValue": "follow me!"
	      }

	    */
      }
    ),
  );
}

```

**Comment by rrousselGit** [comment]
Are you looking for `ProviderObserver`?

```dart
class Logger extends ProviderObserver {
  @override
  void didUpdateProvider(ProviderBase provider, Object newValue) {
    print('''
{
  "provider": "${provider.name ?? provider.runtimeType}",
  "newValue": "$newValue"
}''');
  }
}

void main() {
  runApp(
    ProviderScope(
      observers: [Logger()],
    ),
  );
}

final provider = StateProvider((ref) => 'hello world');
```

**Comment by ldasilva-net** [comment]
Amazing! Yes!
Can we have some way to assign an id for uniquely identify a provider? It is some difficult to detect specific providers by type, especially if we have more than one with the same structure.

**Comment by ldasilva-net** [comment]
Amazing! Thanks a lot Remi!
