### ISSUE TITLE
Document ProviderObserver / How to do Logging with Riverpod

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/river_pod#132]
Related to https://github.com/rrousselGit/river_pod/issues/131

**Comment by yiss** [comment]
Hi @rrousselGit  I can add this to documentation. Can you specify where do you cant it exactly ?

**Comment by rrousselGit** [comment]
There are two steps:

Creating a markdown file in /website/docs
Adding that file to /website/sidebar.js
