### ISSUE TITLE
`MarvelRepository` class in the Marvel example still uses `read()` instead of `watch()`.

### ISSUE THREAD

**Issue by NoahAndrews** [rrousselGit/river_pod#1334]
[File in question](https://github.com/rrousselGit/river_pod/blob/893673c312a17c9f0b983e3594bf08edd595aaac/examples/marvel/lib/src/marvel.dart)

See https://github.com/rrousselGit/river_pod/issues/569 for context.

**Comment by rrousselGit** [comment]
This code is normal.

It _could" be refactored to use watch, but using read this way isn't wrong per say.
