### ISSUE TITLE
The docs site references `ref.keepAlive()`, which does not exist in the latest stable version

### ISSUE THREAD

**Issue by NoahAndrews** [rrousselGit/river_pod#1335]
[Page in question](https://riverpod.dev/docs/concepts/modifiers/auto_dispose#refkeepalive)

For now, the `autoDispose` page should reference `ref.maintainState`.

**Comment by rrousselGit** [comment]
The documentation uses the dev release. So this is expected

**Comment by NoahAndrews** [comment]
Wouldn't it be more helpful to display the docs for the latest stable version?

**Comment by rrousselGit** [comment]
It's also significantly harder for me to maintain
