### ISSUE TITLE
Provider dispose managed by Flutter scope

### ISSUE THREAD

**Issue by rich-j** [rrousselGit/river_pod#1337]
On the Flutter side of our app we basically have global providers and what are effectively Flutter scoped providers (i.e. support the current dialog/view). The end of the "scope" is a user finalizing action such as closing a dialog or navigating to another view. A time-based solution is not reliable since we don't know when the user will "get a coffee". 

One problem task flow for us is a prompted multi-card dialog that supports a "go back" feature. Prior provider states are needed when going back. We currently manage these provider lifetimes using `keepAlive` (we're migrating to 2.0-dev), storing the `keepAliveLink`s in a scope-aware data structure,  and `close()` the links on the user finalizing action.

For us, a Flutter "scoped" `autoDispose` would handle the provider lifetime management that we currently need to code. Yes, there would need to be another form/mode of `ProviderScope` to be added to the Flutter tree that manages these provider lifetimes. The providers that want to be so managed would need to indicate this. Possibly something like `Provider.scopedDispose()` instead of the 3 lines of `keepAlive` code we currently add.

This request is inspired by the lively discussion in #1329 which has many references to Flutter-based user actions and screens.

**Comment by rrousselGit** [comment]
Hello!

Could you show some code? It's unclear to me what you're expecting and what you're currently doing (I have no idea what keepAlive has to do with this)

**Comment by rich-j** [comment]
We use `keepAlive` to maintain `StateNotifierProvider`s for previous "cards" that are no longer displayed (i.e. unmounted) that the user can "go back" to. Our cards collect input/choices from users and progress to other cards/decks. The current card display and "back" history is maintained by a top-level "board". 

Each card's state is created with something like

```dart
final createDeckStateProvider = StateNotifierProvider.autoDispose((ref) {
  final notifier = CreateDeckNotifier();
  final commonBoardNotifier = ref.read(commonBoardProvider.notifier);
  final keepAliveLink = ref.keepAlive();
  commonBoardNotifier.addKeepAliveLink(keepAliveLink);
  return notifier;
});
```

The common board notifier has a method to collect all `keepAliveLink`s in use

```dart
  /// Riverpod keep alive links are collected here and all closed when this board is disposed.
  /// Future for Riverpod assert "Providers are not allowed to modify other providers during their initialization."
  void addKeepAliveLink(KeepAliveLink keepAliveLink) =>
      Future(() => state = state.copyWith(keepAliveLinks: state.keepAliveLinks.prependElement(keepAliveLink)));
```

The common board is a provider created with an `onDispose` to call all of the collected link `close()` functions

```dart
final commonBoardProvider = StateNotifierProvider.autoDispose((ref) {
  final notifier = CommonBoardNotifier();
  ref.onDispose(() {
    _logger.info("Common board disposing ${notifier.currentState.keepAliveLinks.length()} links");
    notifier.currentState.keepAliveLinks.forEach((a) => a.close());
  });
  return notifier;
});
```

**Comment by rrousselGit** [comment]
>   commonBoardNotifier.addKeepAliveLink(keepAliveLink);


This line is anti-pattern. Neither should the KeepAlive link leave the provider it belongs to nor is it allowed to modify other providers during the initialization of a provider.
You shouldn't do such a thing.


And what is it that this issue is requesting?

**Comment by rich-j** [comment]
>And what is it that this issue is requesting?

...definitive provider lifetime management. We want providers to live throughout the lifetime of a given display and not beyond - i.e. "scoped". Time-based solutions are not deterministic. Several of the comments in #1329 show concern with the provider behavior combined with users opening/closing/transitioning screens. We've had to watch out on some of our asynchronous processing that display a busy screen. During a few frames of a transition display Riverpod will dispose of our providers. Also the above mentioned previous cards (i.e. valid for "go back") are held in an unmounted state.

At the "top" of each of our displays we have a `ProviderScope` that overrides a few display specific providers. For us, this is the beginning of a display "scope". All of our U/I state providers are created "under" this scope. When the display is completed this "scope" is disposed. Yes `watch` mostly handles this but we have encountered edge cases.

Thanks for the feedback about the above "anti-pattern". How about if we reverse the "event flow" and have the top-level board provide an event such as a future that is completed when closed. Something like

```dart
  final keepAliveLink = ref.keepAlive();
  ref.listen(commonBoardClosingNotifier, (_, __) => keepAliveLink.close());
```

Hey - that gets it down to 2 lines. Yes, it would be better if we didn't need to manage provider lifetime.

**Comment by rrousselGit** [comment]
> ...definitive provider lifetime management. 

But what would that look like exactly?

Your explanation is fairly abstract. I'd like to see some concrete examples about what you're like. Otherwise I'm not sure how to resolve this issue.

**Comment by rich-j** [comment]
We need two additional concepts: a mechanism to define the managed lifetime scope and an opt-in for the providers to use the scoped lifetime.

Establishing a scope could be an option on `ProviderScope` such as `isScoped: true`. We generally have one at the top of each of our widget trees that injects additional context with provider overrides.

```dart
Widget build(BuildContext context, WidgetRef ref) {
  // Currently this is the provider that manages lifetime with its onDispose
  final commonBoardState = ref.watch(commonBoardProvider);
  return ProviderScope(
    overrides: [profileProvider.overrideWithValue(profile)],
    isScoped: true, // <-- proposed top of the flutter scoped managed lifetime for providers that opt-in
    child: CommonBoard(context, ref, commonBoardState),
  );
}
```

Provider opt-in to managed lifetime would be somewhere in the provider declaration. It could be `Provider.scopedDispose`, a parameter to `.autoDispose`, an additional method on `ref` such as `ref.scopedDispose()`, a parameter to an existing method such as `ref.keepAlive(isScoped: true)`, or even a method on the `keepAliveLink` such as `keepAliveLink.closeOnScopeDispose()`.

```dart
final createDeckStateProvider = StateNotifierProvider.autoDispose((ref) {
  final keepAliveLink = ref.keepAlive();
  keepAliveLink.closeOnScopeDispose();  // <-- opt-in this provider's lifetime to that of the "scope"
  return CreateDeckNotifier();
});
```

If the above scoped provider is not used in a context that has a "scope" defined it will fall back to standard `.autoDispose` behavior.

Generally we like the way `.autoDispose` providers work - i.e. disposed when no longer "in use". We would prefer that any other lifetime behavior be "opt-in". In comment https://github.com/rrousselGit/river_pod/issues/1329#issuecomment-1086834827 you are proposing `cacheTime` default of a few minutes <-- please don't. This would have hidden our card lifetime issue from us in early development (i.e. "go back" failed - oh, they're unmounted and therefore disposed).

For me, a "time-based" solution is an anti-pattern. Caching data is a valid time-based use case but it should be opt-in and applied as an optimization.

**Comment by rrousselGit** [comment]
What you're describing is already available.
You can scope providers (although it's not recommended)

```dart
final a = Provider(...);

...

ProviderScope(
  overrides: [a],
)
```

This will create a new `a` instance for this tree and when the scope is removed, `a` will be disposed.

**Comment by rich-j** [comment]
We already use `ProviderScope(overrides: ...)` to handle static scoped providers. We need to manage the lifetime of dynamically added state notifier family providers as the user progresses forward and backward through our cards. Each card is (mostly) independent of other cards so no big master state is feasible.

**Comment by rrousselGit** [comment]
What's preventing you from using `overrides: [family(123)]`?

**Comment by rich-j** [comment]
At the time we create the `ProviderScope` we don't know the providers that will be needed.

**Comment by rrousselGit** [comment]
I'm sure you should be able to figure out the list

Scoping all providers is not reasonable.

**Comment by rich-j** [comment]
We agree that "Scoping all providers is not reasonable." and didn't ask for that.

We have a workable solution using `keepAlive` with lifetime managed by listening to a named provider.
