### ISSUE TITLE
.notifier in consumer widget not update but it update without using notifier ?

### ISSUE THREAD

**Issue by user97116** [rrousselGit/river_pod#1338]
Following code shows when I am using .notifier then it not rebuild widget, but when I reload app it updated and in 2nd code it works fine without using notifier.

1st
```
 Consumer(
  builder: (context, ref, child) {
    var cart = ref.watch(cartItemsNotifierProvider.notifier);
    return Text("Total item selected \$${cart.totalPrice}");
  },
)
```
2nd
```
Consumer(
  builder: (context, ref, child) {
    ref.watch(cartItemsNotifierProvider);
    return Text(
        "Total item selected \$${ref.read(cartItemsNotifierProvider.notifier).totalPrice}");
  },
)
```
and In 2nd case I have to use multiple times ref. how to avoid this?

**Comment by rrousselGit** [comment]
That's expected.

See its documentation. It explains clearly that ".notifier" does not listen to the state
