### ISSUE TITLE
Need to clarify the use of watch

### ISSUE THREAD

**Issue by jonny7737** [rrousselGit/river_pod#135]
**Describe what scenario you think is uncovered by the existing examples/articles**
A clear and concise description of the problem that you want explained.

In the 'Reading a provider' section of the online documentation, a diagram is provided to help in determining the appropriate way to access a provider (EXCENT idea, wish more docs included this feature).  In that diagram, 'watch' appears exactly once.  Watch should be used when inside another provider (other conditions apply).

Under the heading of 'Deciding what to read', 'watch' is used in several snippets of widget build() and in a full ConsumerWidget.  Where does this type of usage fit in the 'provider access decision' diagram?

**Comment by rrousselGit** [comment]
The part of the graph mentioning "watching" clearly says "ProviderReference.watch"



 The "watch" in builds methods is coming from `Consumer`/`ConsumerWidget`

**Comment by jonny7737** [comment]
Yes, I see that.  Thank you.
I was only suggesting a clarification in the diagram explicitly showing the Consumer.watch case.

**Comment by rrousselGit** [comment]
I'll keep this open as a reminder to add `ConsumerWidget` next to `Consumer`

**Comment by rrousselGit** [comment]
Since the diagram doesn't exist anymore, I'll close this
