### ISSUE TITLE
Cannot ref.watch on StateNotifierProvider.autoDispose.family

### ISSUE THREAD

**Issue by edisonywh** [rrousselGit/river_pod#1353]
**Describe the bug**
I have a StateNotifierProvider like so:

```dart
final subscriptionIssuesController = StateNotifierProvider.autoDispose
      .family<InboxNotifier, AsyncValue<List<Issue>>, String>((ref, id) {
    final repo = ref.watch(inboxRepoProvider);

    return InboxNotifier(
      ref: ref,
      repo: repo,
      type: InboxType.subscription(IssueStatus.unread, id),
    )..getIssues();
  });
  
final inboxRepoProvider = Provider.autoDispose<InboxRepo>((ref) {
  return InboxRepo(ref: ref);
});
```

However when I try to watch this value inside my build method:

`final issues = ref.watch(subscriptionIssuesController);`

`subscriptionIssuesController` have some squiggly line and I get the error message:

> The argument type 'AutoDisposeStateNotifierProviderFamily<InboxNotifier, AsyncValue<List<Issue>>, String>' can't be assigned to the parameter type 'ProviderListenable<dynamic>'

I'm not sure if I'm doing something wrong here or if it's a bug within Riverpod

**To Reproduce**

I don't know how to share DartPad but this should illustrate the issue, just copy paste in dartpad.dev

```dart
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:flutter/material.dart';

Widget main() {
  return MyWidget();
}

class MyNotifier extends StateNotifier<AsyncValue<int>> {
  MyNotifier() : super(AsyncValue.data(0));
}

class MyRepo {
  Ref ref;
  MyRepo({required this.ref});
}

final controller = StateNotifierProvider.autoDispose
      .family<MyNotifier, AsyncValue<int>, String>((ref, id) {
    final repo = ref.watch(repoProvider);

    return MyNotifier();
  });
  
final repoProvider = Provider.autoDispose<MyRepo>((ref) {
  return MyRepo(ref: ref);
});

class MyWidget extends StatefulHookConsumerWidget {
  const MyWidget({Key? key}) : super(key: key);

  @override
  ConsumerState<ConsumerStatefulWidget> createState() => _MyWidgetState();
}
class _MyWidgetState extends ConsumerState<MyWidget> {
  @override
  Widget build(BuildContext context) {
    final items = ref.watch(controller);
    return Container();
  }
}
```

**Expected behavior**
I expect to be able to `ref.watch` on StateNotifierProvider.autoDispose.family

**Comment by edisonywh** [comment]
Oh my god it's a `.family` and I forgot to pass in the parameter...

```diff
class _MyWidgetState extends ConsumerState<MyWidget> {
  @override
  Widget build(BuildContext context) {
-    final items = ref.watch(controller);
+    final items = ref.watch(controller(id));
    return Container();
  }
}
```

The error was pretty cryptic so I thought it was something wrong with the provider, forgot to check the call site :(

**Comment by rrousselGit** [comment]
Hello!

When using `family`, you need to specify the unique key to watch it

The syntax is:

```dart
final items = ref.watch(controller(someKey));
```

**Comment by rrousselGit** [comment]
Ha, you were faster than me!

**Comment by edisonywh** [comment]
Haha yeah I was scratching my head the whole day and the answer popped up as soon as I posted this.. But thanks a lot for the prompt reply!

Is there a way to make the error message a little more obvious? Happy to contribute!

**Comment by rrousselGit** [comment]
Not really. It's the Dart compile that controls the error, not Riverpod.
