### ISSUE TITLE
Update StateNotifierProvider inside FutureProvider

### ISSUE THREAD

**Issue by campanagerald** [rrousselGit/river_pod#136]
StateNotifierProvider does not get updated inside the FutureProvider.

```dart
final countryListProvider =
    FutureProvider.autoDispose<List<CountryEntity>>((ref) async {
  final countries = await ref.read(countryRepositoryProvider).getAllCountries();

  ref.read(selectedNationalityProvider).state = countries[0]; // update selectedNationalityProvider state

  return countries;
});

final selectedNationalityProvider =
    StateProvider.autoDispose<CountryEntity>((ref) => null);
```

```dart
Consumer(builder: (_, watch, child) {
      final selectedNationality = watch(selectedNationalityProvider).state // this is still null;

      return DropdownButtonFormField(
        value: selectedNationality,
        items: watch(countryListProvider)
            .data
            .value
            .map((e) => DropdownMenuItem(value: e, child: Text(e.name)))
            .toList(),
        onChanged: (value) =>
            context.read(selectedNationalityProvider).state = value,
      );
    }
```

I am expecting that the selectedNationalityProvider will have the updated state.

**Comment by rrousselGit** [comment]
Providers should not update other providers (at least not synchronously like that).

The reason why the update isn't performed is that the code you gave triggers an exception, as updating providers here is not allowed.

**Comment by campanagerald** [comment]
Is there a correct way to do that? I would like to initialize the state of selectedNationalityProvider after fetching all countries.

**Comment by rrousselGit** [comment]
Actually ignore my previous statement, I answered a bit too fast. 

Is the line that updates your provider reached, or do you have an exception?

**Comment by campanagerald** [comment]
Yup, I tried to wrap it in a try-catch, does not show any exception.

```
final countryListProvider =
    FutureProvider.autoDispose<List<CountryEntity>>((ref) async {
  final countries = await ref.read(countryRepositoryProvider).getAllCountries();
  
  try {
    ref.read(selectedNationalityProvider).state = countries[0];
  } catch(e) {
    print(e);
  }

  return countries;
});

```

**Comment by rrousselGit** [comment]
the exception may be the `await` instead

Maybe your `getAllCountries` failed

**Comment by rrousselGit** [comment]
But in general I would suggest moving that logic to the `StateProvider` instead:

- have the `FutureProvider` do nothing but the fetching
- have the `StateProvider` listen to the `FutureProvider`:

```dart
final countryListProvider =
    FutureProvider.autoDispose<List<CountryEntity>>((ref) async {
  final countries = await ref.read(countryRepositoryProvider).getAllCountries();


  return countries;
});

final selectedNationalityProvider = StateProvider.autoDispose<CountryEntity>((ref) {
  final countries = ref.watch(countryListProvider);

  if (countries.data == null) return null;

  return countries.data.first;
});
```

**Comment by campanagerald** [comment]
> the exception may be the `await` instead
> 
> Maybe your `getAllCountries` failed

not failed because I was able to get the List

![image](https://user-images.githubusercontent.com/19565694/93494950-2c9e0c80-f940-11ea-9c01-a715040e0ea4.png)

the problem is it was not able to pre populate the dropdown value

![image](https://user-images.githubusercontent.com/19565694/93495042-46d7ea80-f940-11ea-9d18-30cdf9bbe268.png)

**Comment by rrousselGit** [comment]
Have you tried my second message about moving the logic to the
StateNotifier?

**Comment by campanagerald** [comment]
It worked! Thanks! :-)

**Comment by rrousselGit** [comment]
I see

My guess is that your previous code didn't work because of "autoDispose"

The StateProvider wasn't listened by any widget at the time of the `ref.read(...).state = `, so it was created and immediately disposed.
Then when the UI connects, the StateProvider is re-created, starting from `null` again

By moving the logic to the StateNotifier, this removes the issue as it is initialized with the correct value directly.

**Comment by campanagerald** [comment]
> But in general I would suggest moving that logic to the `StateProvider` instead:
> 
> * have the `FutureProvider` do nothing but the fetching
> * have the `StateProvider` listen to the `FutureProvider`:
> 
> ```dart
> final countryListProvider =
>     FutureProvider.autoDispose<List<CountryEntity>>((ref) async {
>   final countries = await ref.read(countryRepositoryProvider).getAllCountries();
> 
> 
>   return countries;
> });
> 
> final selectedNationalityProvider = StateProvider.autoDispose<CountryEntity>((ref) {
>   final countries = ref.watch(countryListProvider);
> 
>   if (countries.data == null) return null;
> 
>   return countries.data.first;
> });
> ```

but i notice if I do this the dropdown is slow when showing the items.

**Comment by campanagerald** [comment]
> I see
> 
> My guess is that your previous code didn't work because of "autoDispose"
> 
> The StateProvider wasn't listened by any widget at the time of the `ref.read(...).state = `, so it was created and immediately disposed.
> Then when the UI connects, the StateProvider is re-created, starting from `null` again (since the future already completed)
> 
> By moving the logic to the StateNotifier, this removes the issue as it is initialized with the correct value directly.

I hope there is a way to dispose a provider explicitly.

**Comment by rrousselGit** [comment]
What do you mean by "it's slow"?

**Comment by TimWhiting** [comment]
@rrousselGit 
I'm guessing that it is because it is lazily loaded when the dropdown button gets clicked, so the future provider doesn't run until the button is clicked.

**Comment by campanagerald** [comment]
> What do you mean by "it's slow"?

@rrousselGit I mean it takes time before the dropdown show

**Comment by campanagerald** [comment]
> @rrousselGit
> I'm guessing that it is because it is lazily loaded when the dropdown button gets clicked, so the future provider doesn't run until the button is clicked.

@TimWhiting I am calling the future before showing the form. I am expecting that time that the future is already loaded. 

```dart
class __StepperFormState extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Consumer(builder: (_, watch, __) {
      final countryList = watch(countryListProvider);

      if (countryList is AsyncLoading) {
        return Center(child: CircularProgressIndicator());
      } else {
        return Stepper(
          currentStep: _currentStep,
          onStepContinue: () => _onStepContinue(),
          onStepCancel: () => _onStepCancel(),
          steps: _steps(),
        );
      }
    });
  }
```
