### ISSUE TITLE
Instance of 'CircularDependencyError'

### ISSUE THREAD

**Issue by tbm98** [rrousselGit/river_pod#14]
I got `Instance of 'CircularDependencyError'` but I don't know the reason for this error.
I have 2 providers that use each other
```
final calendarStateNotifier = StateNotifierProvider((ref) {
  return CalendarStateNotifier(
      ref.read(scheduleStateNotifier).value, ref.read(mainStateNotifier).value);
});
```
and 
```
final scheduleStateNotifier = StateNotifierProvider((ref) {
  return ScheduleStateNotifier(ref.read(calendarStateNotifier).value);
});
```

**Comment by rrousselGit** [comment]
Providers cannot somehow depend on themselves.

Your calendar depends on the schedule, but the schedule depends on the calendar. 

You cannot have both. One of them must go away

**Comment by tbm98** [comment]
Yes.  😅
