### ISSUE TITLE
Recommended file structure or architecture

### ISSUE THREAD

**Issue by campanagerald** [rrousselGit/river_pod#148]
What is the recommended architecture or folder structure for riverpod?

**Comment by iamarnas** [comment]
I would say the same as Provider.  But you can use any structure, it up to you. Until you can read your code.

**Comment by campanagerald** [comment]
I saw this in medium https://medium.com/@mxiskw/flutter-pragmatic-architecture-using-riverpod-123ae11a8267

**Comment by rrousselGit** [comment]
I don't believe in recommending a specific folder architecture.

For me:
- that changes over time
- depends on your team

Do what you like.


At least, as opposed to with `provider`, you can place your providers absolutely everywhere, so you have a lot more freedom.

**Comment by rrousselGit** [comment]
Closing as there's nothing specific to Riverpod here 😄
