### ISSUE TITLE
Read a provider outside widgets

### ISSUE THREAD

**Issue by edmbn** [rrousselGit/river_pod#151]
I'm trying to read a provider from outside a widget. The documentation says to use ProviderContainer but when using it I get and instance of my StateNotifierProvider with the default state (maybe a new instance). 

I'm using it as the documentation:

`ProviderContainer().read(myStateNotifierProvider.state)`

Is it possible that the documentation is missing something? For example I see in the API reference that ProviderContainer accept parent as a parameter but I can't find where it is explained or why it is used for. I don't know if this is the problem but I couldn't find more information about how to read properly providers outside widgets apart from official docs using it on tests, and this way I get always a new instance of the StateNotifierProvider.

Thank you for your time.

**Comment by rrousselGit** [comment]
You can't just create a `ProviderContainer` and read the state.
Two different containers have a completely independent state from each other

I need to know more about your use-case to answer correctly.

**Comment by edmbn** [comment]
Well, in my case I have dart-only files holding `stateNotifiers` and dart-only files holding `providers`. I was trying to access a `provider` inside the `stateNotifier`. If `ProviderContainer `doesn't hold the global `providers` state maybe would be a better idea to pass this data to the function living inside the `stateNotifier` class instead of trying to access this data in the function itself.

**Comment by rrousselGit** [comment]
Could you share some code of what you're trying to do?

**Comment by edmbn** [comment]
I have a `signInFormProvider` that holds the `singIn` form data in a `stateNotifier` class. I want to access this `provider` state inside the `signIn` function of this new `stateNotifierProvider`:

```
class SignInNotifier extends StateNotifier<AsyncValue<Unit>> {
  SignInNotifier() : super(null);

  Future<void> signIn() async {
    state = const AsyncValue.loading();
    final signInForm =
        ProviderContainer().read(signInFormNotifierProvider.state);
    final email = signInForm['identifier']; // Always ""
    final password = signInForm['password']; // Always ""
    state = await AsyncValue.guard(() => ProviderContainer()
        .read(authRepositoryProvider)
        .signInWithEmailAndPassword(email: email, password: password));
  }
}
```

**Comment by rrousselGit** [comment]
You can do:

```dart
final myProvider = StateNotifierProvider((ref) => MyNotifier(ref))
```

The use that "ref" object to read other objects

**Comment by edmbn** [comment]
Yes! That is the best way, thank you so much. Hopefully it helps to others too.
