### ISSUE TITLE
Consumer rebuilds entire widget tree

### ISSUE THREAD

**Issue by humbertoadan** [rrousselGit/river_pod#16]
This is more of a question than an actual bug report. I'm trying to do the counter example using flutter_hooks, but I have noticed that when using hooks and consumer, when the state changes the entire widget tree is rebuilt. 
```dart
class MyHomePage extends HookWidget {
  @override
  Widget build(BuildContext context) {
    final count = useProvider(counterProvider).state;
    debugPrint("Rebuild");
    return Scaffold(
      appBar: AppBar(
        title: Text("Counter Example"),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Consumer((context, read) => Text(
                  "$count",
                  style: Theme.of(context).textTheme.headline4,
                )),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => counterProvider.read(context).state++,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), 
    );
  }
}
```
When I used Consumer from the provider package, it used to rebuild only the consumer widget. Is this a bug or am I missing something to make this work?

**Comment by rrousselGit** [comment]
Hooks rebuild the widget that used the hook, so here MyHomePage

If you want to rebuild only the Text, either extract the text in a separate HookWidget or don't use hooks and use a Consumer directly

**Comment by rrousselGit** [comment]
Alternatively you can use HookBuilder and call the hook inside its builder parameter

**Comment by humbertoadan** [comment]
I see, thank you for the answer.
