### ISSUE TITLE
Add useProviderListener

### ISSUE THREAD

**Issue by quangson91** [rrousselGit/river_pod#163]
**Describe what scenario you think is uncovered by the existing examples/articles**
How do we reduce the nested of `ProviderListener` when I want to trigger multiple providers?
Example:
```dart
    ProviderListener(
      onChange: null,
      provider: provider1,
      child: ProviderListener(
        onChange: null,
        provider: provider2,
        child: ProviderListener(
          onChange: null,
          provider: provider3,
          child: null,
        ),
      ),
    );
```

Is there something like `MultipleProviderListener`?
also, is that possible to create a hooks like: `useProviderListener(Function(Argument))` for listening provider?

**Comment by rrousselGit** [comment]
Closing in favor of #335
