### ISSUE TITLE
Simulator hot reload doesn't work with ConsumerWidget

### ISSUE THREAD

**Issue by Chojecki** [rrousselGit/river_pod#164]
When I'm changing ConsumerWidget and save, the Simulator doesn't reload.

**To Reproduce**

Create any ConsumerWidget. Put a Text in a center. Run iOS Simulator. Change text in editor and save. The Simulator won't reload.

**Expected behavior**
The Simulator should refresh content with new text. Or am I understand ConsumerWidget wrong? The issue doesn't appear when I use Consumer.

**Comment by rrousselGit** [comment]
That should be fixed in flutter_riverpod/hooks_riverpod 0.11.1

**Comment by Chojecki** [comment]
Great. Correct me if I'm wrong, but is ConsumerWidget part od flutter_hooks? I didn't have this issue with HookWidget btw

**Comment by rrousselGit** [comment]
It's not

**Comment by softronaut** [comment]
I have exactly same issue. Hot reload is not updating UI. Using `0.12.1` version.

**Comment by rrousselGit** [comment]
@softronaut Are you sure that you are having _this_ issue and not #200?

This is for updating the code of `Consumer`. #200 is for updating the code of providers.

This issue should be fixed.
If hot-reload does not work for updating Consumers, please make a new issue

**Comment by softronaut** [comment]
@rrousselGit it's not #200, right now it's working but I'm sure it was not working before, because I couldn't able to change like scaffold body padding, button text etc. I'll watch on it if I encounter again and open issue with present element tree.
