### ISSUE TITLE
Website logo height issue

### ISSUE THREAD

**Issue by ycherniavskyi** [rrousselGit/river_pod#165]
**Describe the bug**
On Safari Version 14.0 (15610.1.28.1.9, 15610) I see the next main page:
![Screenshot 2020-09-30 at 11 41 04](https://user-images.githubusercontent.com/552025/94663244-1c0f6e00-0312-11eb-9eb4-93e4195df0cb.png)

**To Reproduce**
Open https://riverpod.dev with Safari Version 14.0.

**Expected behavior**
I want to see the next main page on Safari as on Chrome:
![riverpod dev_](https://user-images.githubusercontent.com/552025/94663795-c2f40a00-0312-11eb-9ba4-6e6ae25d565f.png)

**Comment by rrousselGit** [comment]
Thanks for the report!
