### ISSUE TITLE
Can you create a provider from the BuildContext?

### ISSUE THREAD

**Issue by aliak00** [rrousselGit/river_pod#171]
**Describe what scenario you think is uncovered by the existing examples/articles**
I have to create my `ThemeData` using the `BuildContext` and I want to be able to change the theme data from wherever. So the first time wen creating the `MaterialApp` I need to be able to do something like:

```dart
class App extends ConsumerWidget {
  @override
  Widget build(BuildContext context, ScopedReader watch) {
    return MaterialApp(
      ...
      theme: watch(themeProvider).state, // ???
      ...
    )
  }
}
```

**Describe why existing examples/articles do not cover this case**
I've read a lot of the docs and watched a few youtube vids but can't seem to figure this out.

**Additional context**
I'm a flutter n00b .. like, super n00b. So please forgive this if the answer is really obvious 🙏 🙂

**Comment by rrousselGit** [comment]
You probably don't need to interact with the context at all:

```dart
final themeProvider = StateProvider((ref) => Theme.light());
```

**Comment by aliak00** [comment]
So what I do is I derive the settings from the current `textTheme` and just make adjustments. I'm using `GoogleFonts.xxxTextTheme(...)` which you can either provide a `textTheme` to or else it uses `ThemeData.light().textTheme` as the default.

For some reason, the size of the font in the `AppBar` changed depending on whether I used that `ThemeData.light().textTheme` (resulted in smaller text) or `Theme.of(context).textTheme`. And my assumption was that accessibility settings may change the current textTheme and the default `ThemeData.light().textTheme` is a static thing?

**Comment by rrousselGit** [comment]
That is correct.

But to begin with, why do you want to store the theme in a provider?

**Comment by aliak00** [comment]
> But to begin with, why do you want to store the theme in a provider?

I want the theme to be modifiable from various parts of the UI because there're a lot of dynamics involved with theme colors, that can be triggered from various widgets. So I thought that provider is one way to do global state?

(It's actually a class called `AppState` which is supposed to be accessible from everywhere - when appstate changes, there's a chance the theme also changes).

**Comment by rrousselGit** [comment]
Rather than storing the Theme, it may be more logical to store some "state", like the color:


```dart
final primaryColorProvider = StateProvider((ref) => Colors.red);

...

MaterialApp(
  theme: ThemeData(
    primaryColor: watch(primaryColorProvider).state,
  ),
);
```

**Comment by aliak00** [comment]
Sorry, I'm not actually storing the `Theme`, it's the `AppState` that's stored which I'm watching in a top-level widget:

```dart
Widget build(BuildContext context, ScopedReader watch) {
    final appState = watch(appStateNotifierProvider.state);
    return MaterialApp(
      // ...
    );
```

`AppState` has a non-trivial function named `getTheme` which computes the theme based on a number of state variables inside the `AppState` object:

Snippet:
```dart
ThemeData getTheme(BuildContext context) {
  // ...
  // Computations based on AppState variables (screen/score/auth/difficulty/weather/etc)
  // ...
  return ThemeData(
      buttonTheme: ButtonThemeData(
        colorScheme: colorScheme,
        splashColor: colorScheme.secondaryVariant,
      ),
      dialogTheme: DialogTheme(
        backgroundColor: colorScheme.background,
      ),
      colorScheme: colorScheme,
      textTheme: newTextTheme,
      primaryTextTheme: newTextTheme,
      bottomNavigationBarTheme: BottomNavigationBarThemeData(
        backgroundColor: Colors.blueGrey[900],
      ),
      primarySwatch: primarySwatch,
      scaffoldBackgroundColor: colorScheme.background,
      textButtonTheme: TextButtonThemeData(
        style: ButtonStyle(
          textStyle: MaterialStateProperty.resolveWith<TextStyle>(
            (Set<MaterialState> states) {
              return newTextTheme.bodyText2.copyWith(fontWeight: FontWeight.bold);
            },
          ),
          foregroundColor: MaterialStateProperty.resolveWith<Color>(
            (Set<MaterialState> states) {
              return colorScheme.onPrimary;
            },
          ),
        ),
      ),
    );
}
```

**Comment by rrousselGit** [comment]
Then what's wrong?

**Comment by aliak00** [comment]
I didn't know how to create an app-level state object based on non-static data that is only available after the application starts.

But as of my understanding now, I can either:

1. Create a proxy type, and configure it in the build method (which is what I did with "`AppState`"):
  ```dart
  Widget build(BuildContext context, ScopedReader watch) {
    auto thing = watch(thingProvider.state);
    thing.configure(context);
    return MaterialApp(...);
  }
  ```
2. Use a `ScopedProvider`? Will that work too?
  ```dart
  Widget build(BuildContext context) {
    val thing = Thing(context);
    ProviderScope(
      overrides: [
        thingProvider.overrideWithValue(thing),
      ],
      child: MaterialApp(...),
    );
  }
  ```
For 2, I'm not sure if it would work with custom `class`es.
