### ISSUE TITLE
Merge BuildContext with ScopedReader

### ISSUE THREAD

**Issue by szotp** [rrousselGit/river_pod#172]
**Is your feature request related to a problem? Please describe.**
IDE does not seem to play nicely with typedefs, so when overiding build method of consumer widget it would generate this ugly code:
```dart
  Widget build(BuildContext context, T Function<T>(ProviderBase<Object, T> provider) watch) {
    // TODO: implement build
    throw UnimplementedError();
  }
``` 

**Describe the solution you'd like**
It looks like any class implementing method named "call" can act as function, so this seems possible:
```dart
abstract class WatchingContext extends BuildContext {
  T call<T>(ProviderBase<Object, T> base);
}

/// assuming ConsumerWidget was changed to use WatchingContext
class HomePage extends ConsumerWidget {
  @override
  Widget build(WatchingContext context) {
    final value = context(_state);
    return _buildSomething(context, value.text);
  }

  Widget _buildSomething(BuildContext context, String value) => Text(value);
}
```
which does not require any typedefs, and looks less noisy.

**Describe alternatives you've considered**
I can probably write my own solution on top of river_pod, but it would be nicer to have it main package.

**Additional context**
Close if it's too silly.

**Comment by rrousselGit** [comment]
I'd suggest making a custom auto-complete for this instead.

I don't like using context here, because:
- it confuses people into thinking that they can't obtain a provider without a BuiltContext
- people would forget to replace BuildContext with WhateverContext and would wonder why they don't have access to the method

**Comment by szotp** [comment]
After playing with this more, it seems to be dart analyzer issue, as it only happens with typedefs that look like this:
```
typedef Closure = T Function<T>(T input);
```
so I will report this to dart issues, but hard to say if/when they will fix it.

Anyway, snippet will work, at least for this example. There may be other cases where I'm overriding a method that involves ScopedReader, but I don't have any concrete examples yet, so closing for now.

**Comment by szotp** [comment]
FYI https://github.com/dart-lang/sdk/issues/43667
