### ISSUE TITLE
Have a discord channel for riverpod

### ISSUE THREAD

**Issue by campanagerald** [rrousselGit/river_pod#173]

**Comment by joanofdart** [comment]
I can set this up, but its up to @rrousselGit if he's okay with it.

**Comment by rrousselGit** [comment]
Sure go ahead

**Comment by joanofdart** [comment]
https://discord.gg/Bbumvej 

here it is @rrousselGit  sorry I've been busy.
I was wondering if perhaps this could be used for all your stuff? provider/freezed/state_notifier/flutter_portal? if so, let me know and I'll change the name.

**Comment by erf** [comment]
Maybe the discord URL could be added to README ?

**Comment by rrousselGit** [comment]
It is in the readme already :smile:

**Comment by erf** [comment]
Ah. I missed the little link button at the top. Then this could be closed perhaps?

**Comment by pishguy** [comment]
> It is in the readme already 😄

I don't see, please check again
