### ISSUE TITLE
Add an option in Consumer when to build, when using StateNotifier

### ISSUE THREAD

**Issue by campanagerald** [rrousselGit/river_pod#176]
**Is your feature request related to a problem? Please describe.**

Inside a consumer I have a widget that i don't want to rebuild when certain condition is met.

**Describe the solution you'd like**

I would suggest if Consumer will also have buildWhen like flutter_bloc.

```dart
Consumer(
  buildWhen: (prevState, currentState) {
  // check condition
  },
  builder: (context, watch, child) {
  // ...
};
```

I don't know if StateNotifier track the previous state. This is just a suggestion. : - )

**Comment by rrousselGit** [comment]
There is no thing such as previous/next state with Consumer

The syntax will instead be:

```dart
Consumer(
  builder: (context, watch, child) {
    final name = watch(myProvider.select((model) => model.name));
  } 
)
```

**Comment by campanagerald** [comment]
> There is no thing such as previous/next state with Consumer
> 
> The syntax will instead be:
> 
> ```dart
> Consumer(
>   builder: (context, watch, child) {
>     final name = watch(myProvider.select((model) => model.name));
>   } 
> )
> ```

So there is no way no compare the previous and current state? Anyway thanks! I'll try this syntax.

**Comment by campanagerald** [comment]
Hi @rrousselGit,

How do I select a field from a StateNotifier? I tried the code below but it shows a warning like 'The member 'state' can only be used within instance members of subclasses of 'package:state_notifier/state_notifier.dart''.

```dart
Consumer(
  builder: (context, watch, child) {
    final name = watch(myStateNotifierProvider.select((myStateNotifierProvider) => myStateNotifierProvider.state.name));
  } 
);
```

**Comment by rrousselGit** [comment]
This is not yet implemented

**Comment by iamarnas** [comment]
I think alternatively it works if you combine AsyncValue with StateNotifier. Then inside `Consumer`. 
```dart
 final user = watch(userProvider).whenData((user) => user.name);
});
```

Inside providers it works.

**Comment by campanagerald** [comment]
@iamarnas  ohhh. thanks! I'll try it.

**Comment by rrousselGit** [comment]
`when`/`whenData` does not filter rebuilds.

**Comment by iamarnas** [comment]
> `when`/`whenData` does not filter rebuilds.

Is the only way to filter rebuilds is with the Hooks selector?

**Comment by rrousselGit** [comment]
There are currently two ways:
- `useProvider(myProvider.select(...))`
- extracting the value you want to listen in a separate `Provider`


```dart
final todoList = StateNotifierProvider(...)

final todosCount = Provider((ref) {
  return ref.watch(todoList.state).length;
});

...

final count = watch(todosCount)
```

**Comment by quantosapplications** [comment]
Hello @rrousselGit, is https://github.com/rrousselGit/river_pod/issues/176#issuecomment-705213959 going to rebuild only when `model.name`change?

**Comment by yuhangang** [comment]
> Hi @rrousselGit,
> 
> How do I select a field from a StateNotifier? I tried the code below but it shows a warning like 'The member 'state' can only be used within instance members of subclasses of 'package:state_notifier/state_notifier.dart''.
> 
> ```dart
> Consumer(
>   builder: (context, watch, child) {
>     final name = watch(myStateNotifierProvider.select((myStateNotifierProvider) => myStateNotifierProvider.state.name));
>   } 
> );
> ```

Any update?

**Comment by rrousselGit** [comment]
Closing in favor of #335  which will implement this (and should be available by the end of April)
