### ISSUE TITLE
Reading a StateProvider outside Widgets with ProviderContainer -> State not provided

### ISSUE THREAD

**Issue by cmarpert** [rrousselGit/river_pod#179]
**Describe the bug**
I have created a StateProvider of type bool, which I toggle with a button from the UI.
The UI is updating, so consumption via ComsumerWidget is running as expected.
But in a different file I do some logic depending on the state, but the current state is not provided.
My mistake?

**To Reproduce**
//1: creating provider in provider.dart:
final is_running_Provider = StateProvider<bool>((ref) => false); 

//2: updating provider in UI menu.dart:
class menu extends ConsumerWidget {
  @override
  Widget build(BuildContext context, ScopedReader watch) {
    final is_running = watch(is_running_Provider);
.........
// update state on button press:
onPressed: () {is_running.state = !is_running.state;}

//3: read in another file (no widget)
void start() {
    final container = ProviderContainer();
    final is_running = container.read(is_running_Provider);
    print('start: ${is_running.state}');   //ERROR -> state stays at "false" as initialized
}

**Expected behavior**
I was expecting the to read the current state in the start method

**Comment by smiLLe** [comment]
You are creating a `ProviderContainer` in your `start` method. `container.read` will create an new instance of `is_running_Provider` which by default (your code) returns `false`

**Comment by rrousselGit** [comment]
Creating a new `ProviderContainer` means creating a new state for your providers.
That's not what you want. Instead, you want to reuse an existing state


For that, you will need to pass as parameter o your `start` either:
- a `BuildContext`
- a `ProviderReference
- an existing instance of `ProviderContainer`


It's hard to answer as I don't know your requirements and how that `start` method is called

**Comment by cmarpert** [comment]
Am pretty new to that stuff so apologies for stupid questions ;)

Anyway thks a lot for the fast responses.

Works for me, appreciated!
