### ISSUE TITLE
StateNotifier is missing from package ?

### ISSUE THREAD

**Issue by simoneTheNewBlack** [rrousselGit/river_pod#18]
**Describe the bug**
Trying to import StateNotifier from **flutter_riverpod.dart**

**To Reproduce**
```
import 'package:flutter_riverpod/flutter_riverpod.dart';
class Counter extends StateNotifier<int> {
	Counter(): super(0);
}
```

seems like the riverpod has not included the StateNotifier, do we need to install this package on our own from state_notifier?
thanks

**Comment by rrousselGit** [comment]
Yes, you need to install state notifier as a separate package
