### ISSUE TITLE
Usage of watch. Documentation shows 2 different usage of watch

### ISSUE THREAD

**Issue by tberghuis** [rrousselGit/river_pod#180]
Documentation shows 2 different usage of watch:
 `watch(xxxProvider.state)` and `watch(xxxProvider).state` , is there any difference? clarify when to use which?

**Comment by iamarnas** [comment]
>  Documentation shows 2 different usage of watch:
>  `watch(xxxProvider.state)` and `watch(xxxProvider).state` , is there any difference? clarify when to use which?

If I am right. In this way you use when you want initialize. 
`final counter = watch(xxxProvider.state);`

Second when you want watch you value in the UI without initialize.

`Text('${watch(xxxProvider).state}' ), `

But anyway you should get compile warning if you use it wrong.

**Comment by smiLLe** [comment]
Lets say you have a `StateNotifierProvider`,
Using `final notifier = watch(xxxProvider);` will return the StateNotifier instance but not its `state`. It will only rebuild the widget when the instance of `notifier` has been chaned.
Using `final state = watch(xxxProvider.state);` will create the `StateNotifier` and return the `state` of the `StateNotifier`. It will rebuild the widget whenever `state` has been changed.

**Comment by rrousselGit** [comment]
That depends on the provider you are listening

With StateNotifierProvider, do `watch(stateNotifierProvider.state)`
With StateProvider do `watch(stateProvider).state`


I wish this could be improved. The issue here is the language.
