### ISSUE TITLE
Why add flutter_hooks to dependencies

### ISSUE THREAD

**Issue by suragch** [rrousselGit/river_pod#181]
The [documentation](https://riverpod.dev/docs/getting_started) says when using hooks_provider to add the following two dependencies to `pubspec.yaml`:

```
dependencies:
  flutter_hooks: ^0.14.0
  hooks_riverpod: ^0.11.1
```

However, `hooks_riverpod` already depends on `flutter_hooks` internally. It seems to me that it's unnecessary to tell people they need to add `flutter_hooks`. Am I missing something?

**Comment by rrousselGit** [comment]
Riverpod does not export hooks, so it's a bad practice to not specify hooks in your pubspec (as riverpod could technically remove the dependency, even if unlikely)

**Comment by suragch** [comment]
Got it. Thank you.
