### ISSUE TITLE
context.read NoSuchMethodError 

### ISSUE THREAD

**Issue by tberghuis** [rrousselGit/river_pod#183]
this works
```
@override
Widget build(BuildContext context) {
  return RaisedButton(
    onPressed: () => callRead(context.read),
    child: Text('increment'),
  );
}
callRead(read){
  read(counterProvider).state++;
}
```

this throws exception `NoSuchMethodError (NoSuchMethodError: Class '_StatelessHookElement' has no instance method 'read'.`
```
@override
Widget build(BuildContext context) {
  return RaisedButton(
    onPressed: () => callContextRead(context),
    child: Text('increment'),
  );
}
callContextRead(context){
  context.read(counterProvider).state++;
}
```

Not sure if this is intended or a bug.

**Comment by rrousselGit** [comment]
Make sure to import `package:flutter_riveprod/flutter_riverpod.dart`

**Comment by tberghuis** [comment]
I'm using hooks_riverpod and importing it. I don't mind doing it the way it works, however it tripped me up for a while.

**Comment by tberghuis** [comment]
Same error happens when importing flutter_riverpod.

**Comment by tberghuis** [comment]
To be clear the issue is calling context.read will work if called directly in the onPressed closure, but if passing context to another function, context.read will get `NoSuchMethodError` . I have no problem if this is the indented behaviour because I can pass context.read to other function.

**Comment by rrousselGit** [comment]
Ah you didn't type the variable

```dart
callRead(BuildContext context)
```

**Comment by tberghuis** [comment]
Yes that worked, thanks.
