### ISSUE TITLE
Creating a "Scoped" StateNotifierProvider

### ISSUE THREAD

**Issue by fpabl0** [rrousselGit/river_pod#188]
Hi Remi, sorry if this is a newbie question. What is the correct way to create a "Scoped" StateNotifierProvider? I mean, my app has an "AuthStateNotifier" that needs to be alive the whole app, however the notifiers after the user logs in must be available only for that widget tree. I am trying to accomplish it doing this:
```dart
final authNotifierProvider = StateNotifierProvider((ref) => AuthNotifier());

final otherNotifierProvider = StateNotifierProvider<OtherNotifier>((ref) {
  final authState = ref.watch(authNotifierProvider.state);
  return authState.maybeWhen(
    authenticated: () => OtherNotifier(),
    orElse: () => null,
  );
});
```
But I am not sure if it is the correct way to do it. Is there a way to combine the StateNotifierProvider with ScopedProvider?
This library is amazing, thank you for all your time.

**Comment by rrousselGit** [comment]
>  however the notifiers after the user logs in must be available only for that widget tree.

There is no such thing in Riverpod. It's not very useful to begin with.
Just make your provider available for the whole app – it doesn't matter

**Comment by rrousselGit** [comment]
Yes, that's fine

**Comment by fpabl0** [comment]
Perfect. Thanks for your help.
