### ISSUE TITLE
How to properly create a provider from a TickerProvider and where to place it?

### ISSUE THREAD

**Issue by dungnv2602** [rrousselGit/river_pod#191]
As the title already tells, I have a StateNotifier which takes TickerProvider as a param, and I don't know how to create it in riverpod. The docs provide no example like this case since TickerProvider is only available from inside a StatefulWidget with TickerProviderStateMixin.

**Comment by rrousselGit** [comment]
What is the use-case for this?

**Comment by dungnv2602** [comment]
Driving Animation inside a Notifier. Furthermore, I don't think your question is necessary since a provider should be achievable from any external params, isn't it?

**Comment by rrousselGit** [comment]
That is not the responsibility of a Notifier or provider to drive animations.
This is exclusively the role of widgets, and should not be extracted out of the widget tree as it would otherwise break some features.

**Comment by dungnv2602** [comment]
> That is not the responsibility of a Notifier or provider to drive animations.
> This is exclusively the role of widgets, and should not be extracted out of the widget tree as it would otherwise break some features.
I'm not saying my Notifier uses it to solely drive animation alone, it is more than that. For example, based on AnimationStatus & animation value to change other states.

**Comment by rrousselGit** [comment]
Still, notifiers should not drive animations _at all_.

**Comment by dungnv2602** [comment]
> Still, notifiers should not drive animations _at all_.

Then how do you change state based on Animation, when that state is provided downed to widget tree?

**Comment by rrousselGit** [comment]
You don't change state based on animations. You change animations based on state

Like with `TweenAnimationBuilder`:

```dart
final counter = StateProvider((ref) => 0);

...

return TweenAnimation<double>(
  tween: Tween(end: watch(counter).state.toDouble()),
  duration: Duration(seconds: 2),
  builder: (context, value, child) {
    return Text('$value'),
  },
)
```

**Comment by dungnv2602** [comment]
I assume you don't get what I was trying to say. This is a relatively simple notifier that I'm using for widgets that can open-close & mix with others Notifier to achieve some animation.
```
/// AnimationController wrapper especially designed for open-close widget
class OpenableController extends ChangeNotifier {
  OpenableController({
    @required TickerProvider vsync,
    Duration duration,
  })  : assert(vsync != null),
        _controller = AnimationController(
            duration: duration ?? MotionDurations.d650, vsync: vsync) {
    _controller
      ..addListener(notifyListeners)
      ..addStatusListener((status) {
        status.when<void>(
          onForward: (_) => _state = OpenableState.opening,
          onCompleted: (_) => _state = OpenableState.opened,
          onReverse: (_) => _state = OpenableState.closing,
          onDismissed: (_) => _state = OpenableState.closed,
        );
        notifyListeners();
      });
  }

  Animation<double> get animation => _controller.view;
  double get value => _controller.value;
  double get reverseValue => 1 - _controller.value;
  final AnimationController _controller;

  OpenableState get state => _state;
  OpenableState _state = OpenableState.closed;

  void open() => _controller.forward();

  void close() => _controller.reverse();

  void toggle() {
    if (state.isClosed) {
      open();
    } else if (state.isOpened) {
      close();
    }
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }
}
```
Image more complicated situations that have a Notifier that has several other states based on AnimationStatus for example.

**Comment by rrousselGit** [comment]
My statement does not change

Your notifier should only have a boolean (like "isOpened"), and the animation should be driven by the widget

**Comment by dungnv2602** [comment]
If I understand you correctly, so you would say in a situation that needs several states you would define several Notifiers that hold one value (same as ValueNotifier)?

**Comment by dungnv2602** [comment]
> My statement does not change
> 
> Your notifier should only have a boolean (like "isOpened"), and the animation should be driven by the widget
I have to disagree, please explain the AnimationController class in that view.

**Comment by rrousselGit** [comment]
That's like https://github.com/rrousselGit/river_pod/issues/191#issuecomment-709059724 but replace the counter with your "isOpened" flag

The tween could be anything, like opacity/size/color

**Comment by dungnv2602** [comment]
Pardon my poor explaining skill, I need to clarify some points:

- This is started to go beyond the scope of what I was asking about. Can you please tell me at the moment can a provider be created from a TickerProvider in Riverpod? If not, then do you support it in the future?

- What we are arguing is lean on how to properly define & use a Notifier. I think this is a matter of preference, I generally tend to create a Notifier by UI features. What I mean by that is a model that holds several properties that can change over time, maybe properties depending on other properties as well (in that case that property is a Listenable itself). Then in Widgets I can make it listen to one or several properties depending on circumstances. 

- Actually, I have a repo that is created recently to evaluate some State Management approaches in UI implementation. And I'm stuck in Riverpod, that's why I raise this issue. If you have time, please take look and give me some lights on how to implement it in Riverpod and of course how to properly define Notifiers as well because honestly I'm still don't understand why it is wrong in your eyes.

**Comment by rrousselGit** [comment]
> Can you please tell me at the moment can a provider be created from a TickerProvider in Riverpod? If not, then do you support it in the future?

No and no, for the reasons I mentioned previously.

TickerProvider is not something that should be passed to providers.
Doing so can break some features of the TickerProvider, which overall decrease the performances of the app. This is a no-go

**Comment by dungnv2602** [comment]
> > Can you please tell me at the moment can a provider be created from a TickerProvider in Riverpod? If not, then do you support it in the future?
> 
> No and no, for the reasons I mentioned previously.
> 
> TickerProvider is not something that should be passed to providers.
> Doing so can break some features of the TickerProvider, which overall decrease the performances of the app. This is a no-go

Thank you, I'll think about it.

**Comment by gazialankus** [comment]
Since information about this is scarce I would like to ask it here: is there anything wrong with setting Riverpod state in a ticker?

**Comment by Marflage** [comment]
Is there a way to use SingleTickerProviderMixin in Riverpod without StatefulWidgets?
