### ISSUE TITLE
Is it possible to open `BuildlessAutoDisposeAsyncNotifier`/`BuildlessAsyncNotifier` for public consumption outside of 'riverpod_generator'?

### ISSUE THREAD

**Issue by abigotado** [rrousselGit/river_pod#1957]
### In continuation of the discussed in https://github.com/rrousselGit/riverpod/discussions/1953

Hello!

I have made a mixin on `AutoDisposeAsyncNotifier` to reuse code in my `AsyncNotifier`s with list pagination logics.

```dart
/// Mixin for pagination screens.
mixin PaginationMixin<T>
    on AutoDisposeAsyncNotifier<PaginationState<T>> {
  /// Fetch list and manage states.
  Future<PaginationState<T>> fetchList({
    final bool isRefresh = false,
    final bool isSocketUpdate = false,
    final String? search,
    final EvaluationStatus? filter,
  }) async {
    if (isSocketUpdate || isRefresh || !(state.value?.isEnd ?? false)) {
      PaginationState<T> pagination = state.value != null
          ? state.value!.copyWith(
              page: isRefresh ? null : state.value!.page,
              items: isRefresh ? null : state.value!.items,
              search: search ?? state.value!.search,
              filter: filter ?? state.value!.filter,
            )
          : PaginationState<T>();

      if (!isSocketUpdate) state = AsyncLoading<PaginationState<T>>();

      debugPrint('isSocketUpdate $isSocketUpdate');

      final int nextPage = (pagination.page ?? 0) + 1;
      state = await AsyncValue.guard(() async {
        final List<T>? list = await getList(
          isSocketUpdate ? 1 : nextPage,
          length: isSocketUpdate ? (state.value?.page ?? 1) * 20 : null,
          isRefresh: isRefresh,
          search: state.value?.search ?? '',
          filter: state.value?.filter ?? EvaluationStatus.all,
        );
        if (list != null) {
          pagination = pagination.copyWith(
            isEnd: list.length < 20,
            items: <T>[
              if (!isSocketUpdate) ...pagination.items ?? <T>[],
              ...list,
            ],
            page: isSocketUpdate ? pagination.page : nextPage,
            search: search ?? pagination.search,
            filter: filter ?? pagination.filter,
          );
        }
        return pagination;
      });
    }
    return state.value ?? PaginationState<T>();
  }

  /// Load list from repository.
  Future<List<T>?> getList(
    final int page, {
    required final EvaluationStatus filter,
    final int? length,
    final bool isRefresh = false,
    final String? search,
  });
}
```

It works well, when I am using `AsyncNotifier` with no additional arguments. But if there are arguments (similar to `family`), generator creates `BuildlessAutoDisposeAsyncNotifier`, not general `AutoDisposeAsyncNotifier`. So the mixin has class mismatch.

This one works well:
```dart
/// The controller of EventsScreen states.
@riverpod
class EventsController extends _$EventsController
    with PaginationMixin<EventModel> {
  @override
  FutureOr<PaginationState<EventModel>> build() {
    return fetchList();
  }

  @override
  Future<List<EventModel>?> getList(
    final int page, {
    required final EvaluationStatus filter,
    final int? length,
    final bool isRefresh = false,
    final String? search,
  }) {
    return ref.read(eventsRepositoryProvider).fetchList(
          page,
          length: length,
          isRefresh: isRefresh,
          search: search,
          filter: filter,
        );
  }
}
```

And this one won't work because of `id` argument:
```dart
/// The controller of [ParticipantsScreen] states.
@riverpod
class ParticipantsController extends _$ParticipantsController
    with PaginationMixin<AccessModel> {
  @override
  FutureOr<PaginationState<AccessModel>> build(final int id) {
    return fetchList();
  }

  @override
  Future<List<AccessModel>?> getList(
    final int page, {
    required final EvaluationStatus filter,
    final int? length,
    final bool isRefresh = false,
    final String? search,
  }) {
    // debugPrint('event controller id: $id');
    return ref.read(participantsRepositoryProvider(id)).fetchList(
          page,
          isRefresh: isRefresh,
          search: search,
          filter: filter,
          length: length,
        );
  }
}
```

The problem would be solved, if there's a possibility to make mixin on `BuildlessAutoDisposeAsyncNotifier` (which is only for internal use now), rather than `AutoDisposeAsyncNotifier`.

So, is it possible to open `BuildlessAutoDisposeAsyncNotifier` for public consumption outside of 'riverpod_generator'? Or maybe here can be another solution?

**Comment by rrousselGit** [comment]
That's not reasonable. It isn't meant to be used

You don't need the `on` clause on mixins for them to work. You can instead do:

```dart
mixin PaginationMixin<T> {
  State<AsyncValue<T>> get state;
  set state(State<AsyncValue<T> value);
  Ref<AsyncValue<T>> get ref;
}
```

If you end up needing this often, you can make an interface

```dart
abstract class AsyncNotifierInterface<T> {
  State<AsyncValue<T>> get state;
  set state(State<AsyncValue<T> value);
  Ref<AsyncValue<T>> get ref;
}

mixin MyMixin<T> implements AsyncNotifierInterface<T> {

}
```

**Comment by rrousselGit** [comment]
I'll maybe expose it in the future, but I'm a bit skeptical about it for now.

It's not something that was designed to be exposed. I'd need to carefully review it before exposing it.  
Considering there's a decent workaround, it's not too important to me.

**Comment by abigotado** [comment]
@rrousselGit Well, I've just thought that it could be possible to expose both Buildless and general Notifiers, if one had already been exposed, but I understand your skepsis about it. Anyway your workaround functions excellent, thank you!

And I just want to specify one more thing concerning the the `Ref` in a workaround:

 If I try to use it like that:
```dart
mixin PaginationMixin<T> {
  Ref<PaginationState<T>> get ref;
```
There is and error, if I try to use the mixin: `'BuildlessAutoDisposeAsyncNotifier.ref' ('AutoDisposeAsyncNotifierProviderRef<PaginationState<AccessModel>> Function()') isn't a valid concrete implementation of 'PaginationMixin.ref' ('Ref<PaginationState<AccessModel>> Function()')`

It is solved, if I create mixin this way:
```dart
mixin PaginationMixin<T> {
  AutoDisposeAsyncNotifierProviderRef<PaginationState<T>> get ref;
```

So it is necessary to specify type of ref, isn't it?

**Comment by rrousselGit** [comment]
> So it is necessary to specify type of ref, isn't it?

Depends on what your mixin needs.

Generally `AutoDisposeRef<T>` vs `Ref<T>` is enough

**Comment by rrousselGit** [comment]
> Concerning passing a provider to a class as an argument:


Providers shouldn't be passed as parameter at all. So I would argue that's asking the wrong question.
