### ISSUE TITLE
Prevent StreamProvider.family continuously fetching with parameter that does not have consistent ==

### ISSUE THREAD

**Issue by Nolence** [rrousselGit/river_pod#196]
Hello!

I just ran into the same situation twice by accident and I'm curious if there's something that should be put in place to prevent future users from my mistake.

In one scenario I created a `StreamProvider.family` with a list of document ID's to fetch from firebase. The problem is that list's don't have default equality comparison so the `StreamProvider.family` kept fetching... and fetching... and fetching. It was only a couple minutes later and I was up to 70 thousand reads on the firebase console. Thankfully that's pretty cheap a price but it could've been worse.

I just want to keep others from making the same mistake.

Would you consider adding anything in place to StreamProviders/FutureProviders that could catch a scenario like this? I can imagine counting the times fired within a period and then warning the user or something similar in debug mode?

I did the same thing by accident with a freezed object that was provided by a different provider weirdly enough and I thankfully caught that one too before long. Not sure how that one happened though but it was related to a consistent ==.

**Describe why existing examples/articles do not cover this case**
This [note in the documentation](https://riverpod.dev/docs/concepts/modifiers/family/#parameter-restrictions) is very clear but I think it'd be worth it to prevent the user in another way too as this could be a costly mistake for some users.

**Comment by rrousselGit** [comment]
That is not the correct solution

Instead, use a list that has a consistent hascode/==. 
One of those could be the "ktlist" package

**Comment by Nolence** [comment]
I understand from a practical point of view why the StreamProvider wasn't working and kept fetching. My concerns are more about the consequences for users who don't put something that overrides hash/equality by mistake or just out of ignorance of the riverpod api. Streams and futures are often tied to paid APIs and the only reason I caught my recurrently calling StreamProvider was that I put a break point inside it

**Comment by rrousselGit** [comment]
The requirement on consistent ==/hashCode is necessary.
There's no way to work around it.

**Comment by Nolence** [comment]
Closing as I don't see anything actionable to do here. I think having just discussed the behavior in an issue is good enough
