### ISSUE TITLE
Discord Invite invalid

### ISSUE THREAD

**Issue by muhajirdev** [rrousselGit/river_pod#199]
I clicked the discord url in README. It's says invalid when I try to join 

<img width="759" alt="image" src="https://user-images.githubusercontent.com/12745166/97405384-22e9ca80-192a-11eb-9993-2fe73583c867.png">

**Comment by rrousselGit** [comment]
The invite works for me.

Can you try again? Is there anyone else with the same issue?

**Comment by muhajirdev** [comment]
Hi @rrousselGit , I just tried again. it's working now for some reason. 
Thanks for answering and sorry bothering :)
