### ISSUE TITLE
Code inside provider closure not updated on hot reload

### ISSUE THREAD

**Issue by muhajirdev** [rrousselGit/river_pod#200]
Hi @rrousselGit , thanks for creating this library. Really like it so far.
I just found one thing. I am not sure if this is the intended behavior or not.

So here's is the code

```dart
import 'package:flutter/material.dart';
import 'package:hooks_riverpod/all.dart';

final futureProvider = FutureProvider((ref) async {
  return 1;
});

final computedProvider = FutureProvider((ref) async {
  final num = await ref.watch(futureProvider.future);

  print('computedProvider run');

  return num + 2;
});

class CounterExample extends ConsumerWidget {
  @override
  Widget build(BuildContext context, ScopedReader watch) {
    final text = watch(computedProvider);

    return text.when(
        data: (text) =>
            Text(text.toString(), style: TextStyle(color: Colors.white)),
        loading: () => Text("loading", style: TextStyle(color: Colors.white)),
        error: (_, a) => Text("error", style: TextStyle(color: Colors.white)));
  }
}
```

I use hot reload heavily.  So in this code I was trying to update `return num + 2` into `return num + 5`. But the code is not updated. I am not really sure what happen.

Is this related to https://github.com/flutter/flutter/issues/59899 ?

```dart
import 'package:flutter/material.dart';
import 'package:hooks_riverpod/all.dart';

final futureProvider = FutureProvider((ref) async {
  return 1;
});

final computedProvider = FutureProvider(_computedProvider);

Future<int> _computedProvider(ref) async {
  final num = await ref.watch(futureProvider.future);

  print('computedProvider run');

  return num + 3;
}

class CounterExample extends ConsumerWidget {
  @override
  Widget build(BuildContext context, ScopedReader watch) {
    final text = watch(computedProvider);

    return text.when(
        data: (text) =>
            Text(text.toString(), style: TextStyle(color: Colors.white)),
        loading: () => Text("loading", style: TextStyle(color: Colors.white)),
        error: (_, a) => Text("error", style: TextStyle(color: Colors.white)));
  }
}
```

I have tried avoid anonymous function. But I still can't get the hot reload to be working. 

I even sometime get this error:

<img width="352" alt="image" src="https://user-images.githubusercontent.com/12745166/97419016-1e2e1200-193c-11eb-8963-d7e5e5ee627a.png">

---

I also tried the example ini https://pub.dev/packages/provider/example . I was trying to verify if the behavior is also the same in `provider` package. Turns out the `provider` package doesn't have this problem.

**Comment by iamarnas** [comment]
@muhajirdev  Hi. Problem is that you forget to use types. Your providers would look like this:
```dart
final futureProvider = FutureProvider<int>((ref) async {
  return 1;
});

final computedProvider = FutureProvider<int>(_computedProvider);

Future<int> _computedProvider(ref) async {
  final number = await ref.watch(futureProvider.future);

  print('computedProvider run');

  return number + 3;
}
```
Tips one: Avoid use `num` because that is reserved by system.
Tips two: I recommend activate lints, for example use the Pedantic package. It will help you to avoid red screen as in your picture :)

**Comment by muhajirdev** [comment]
Hi @iamarnas , thanks alot for the quick response! And thanks for the tips.

So I tried to use types like you suggest, but it doesn't solve the hot reloading issue yet. 

I just recorded it here : 
https://www.loom.com/share/8fdde38e711745ebbf2ecfe92f6c2a5a?from_recorder=1

**Comment by rrousselGit** [comment]
It's not a bug but simply not supported
Dart does not support hot reload on such syntax.

**Comment by rrousselGit** [comment]
> Is this related to flutter/flutter#59899 ?

Yes

I made this issue for that reason. But it appears the Dart team does not want to work on it.

**Comment by muhajirdev** [comment]
Ooo okay, got it.

Is there any workaround for this @rrousselGit ? is it possible to use other syntax ?

What's the current recommnded workflow? I guess just the restart the app?

**Comment by rrousselGit** [comment]
There is no way to change the implementation of providers with hot-reload at the moment. Just restart the app

**Comment by softronaut** [comment]
@rrousselGit do you think it's possible to fix this in near future? Because this is kinda deal breaker for me. Imagine having long flow and there you have multiple inputs, there was an assertion error and bam! restart the whole app...

**Comment by rrousselGit** [comment]
@softronaut This is not feasible at the moment.

I am thinking of changing the syntax from:

```dart
final provider = Provider((ref) {
  return Counter();
});
```

to:

```dart
Counter provider(ProviderReference ref) {
  return Counter();
}
```

for the sake of hot-reload

But that requires more thinking and some discussion with the community.

**Comment by AAverin** [comment]
Is this still the case for Riverpod 2.0 or was already addressed?
Trying out riverpod with a very simple FutureProvider setup, but nothing gets updated unless I restart the app, which really slows down development.

I am using `HookConsumerWidget` and do `ref.watch().when()` on a FutureProvider.

**Comment by AlexanderFarkas** [comment]
@AAverin it's fixed if you use code generation. If not - it cannot be fixed. Lambdas cannot be updated during hot reload, since it's very complicated from the Dart VM's point of view.

**Comment by rrousselGit** [comment]
I think the Dart team just doesn't want to do it. We could instead reload the final variable

**Comment by AlexanderFarkas** [comment]
@rrousselGit Out of curiosity - is there a way to force reload final variable in Dart VM?
