### ISSUE TITLE
Initialization of provider dynamically based on a parameter.

### ISSUE THREAD

**Issue by KristianBalaj** [rrousselGit/river_pod#203]
### This is the example of how to initialize a provider dynamically and possible problems connected with it that make me not so comfortable with riverpod.

When opening some screen I want to **be able to create a provider based on some parameter** comming to the screen and then use this provider in any child widgets. 
After that I want to use the initialized provider in all the widgets under the screen.

<details><summary>Let's see some example code</summary>
<p>

```
class MyChangeNotifier extends ChangeNotifier {
  final SomeType parameter;
  MyChangeNotifier(this.parameter);

  bool isChanged = false;

  void smth() {
    ///
  }
}

final myScreenParameterProvider = StateProvider.autodispose<SomeType>((_) => null);

final myProvider = ChangeNotifierProvider.autodispose<MyChangeNotifier>((ref) {
  final value = ref.watch(myScreenParameterProvider);
  if (value == null) return null;
  return MyChangeNotifier(value);
});

class MyScreen extends ConsumerWidget {
  final SomeType parameter;
  MyScreen(this.parameter);

  @override
  Widget build(BuildContext context, ScopedReader watch) {
    // initialization of the myScreenParameterProvider. 
    // It is in the `useEffect` witch second parameter constant to initialize the myScreenParameterProvider only once.
    useEffect(() {
      Future.microtask(
          () => context.read(myScreenParameterProvider).state = this.parameter);
      return;
    }, []);

    final notifier = watch(myScreenParameterProvider);

    if (notifier != null) {
      return const Body();
    } else {
      return const CircularProgressIndicator();
    }
  }
}

class Body extends ConsumerWidget {
  const Body();

  @override
  Widget build(BuildContext context, ScopedReader watch) {
    // This value can be null
    final isChanged =
        useProvider(myProvider.select((value) => value?.isChanged));

    // Now I know the isChanged here is not null,
    // because I've handled the null case in the `MyScreen`.
    // So I don't want to handle the null case here once again.
    if (isChanged != null) {
      return Container();
    } else {
      return CircularProgressIndicator();
    }
  }
}
```

</p>
</details>

## Code description
`myProvider` is the provider I want to initialize based on some incomming parameter, until uninitialized it will provide a null value. `myProvider` is initialized base on `myScreenParameterProvider`.

`myScreenParameterProvider` is initialized in the `useEffect` with second parameter constant to initialize the provider value only once when opening the `MyScreen`.

`MyScreen` is the parent widget. `Body` is the const widget that is listening to specific changed in the `myProvider` value.

`Body` is listening to the specific field in the `myProvider` value. I need to do null check in the `Body` widget build method although `myProvider` shouldn't be null there (checked already in the `MyScreen`).

## Questions
How to **ensure not null of the provider value in the child widget**, in my case in the `Body` widget? 
(Also this can be any provider at all - it can be also provider with `AsyncValue` there, not just nullable value. In that case I don't want to check in the children if the `AsyncValue` has data, because I've handled the case in the parent already.)

**Am I just too paranoid that I want to solve this?** (just assert in the child widget would be enough?)

**Is this showed approach of initializing a provider based on some incomming parameter good? Is there any other - more prefered solution?**

## Possible solution/feature proposal?

One possible solution in my opinion would be to use an extra provider of type`ScopedProvider` (I would set override after the null check in `MyScreen`) but **the problem** is that I cannot do `.select` on the `ScopedProvider` which is essential to prevent useless rebuilds.
`ScopedProvider` would have the same value as the provider from which the value is overriden in the `ScopedProvider` so in that case doing changes to the value provided by the `ScopedProvider` would also reflect changes in the incomming provider. So theoretically it should be reliable 🤔

**Comment by rrousselGit** [comment]
Sorry for the late answer

It appears to me that you want to use `family` instead

So you'd have:

```dart
class MyChangeNotifier extends ChangeNotifier {
  MyChangeNotifier(this.parameter);

  final SomeType parameter;
}

final myProvider = ChangeNotifierProvider.autodispose.family<MyChangeNotifier, SomeType>((ref, parameter) {
  if (parameter == null) return null;
  return MyChangeNotifier(parameter);
});

class MyScreen extends ConsumerWidget {
  MyScreen(this.parameter);

  final SomeType parameter;

  @override
  Widget build(BuildContext context, ScopedReader watch) {
    final notifier = watch(myScreenParameterProvider(parameter));

    if (notifier != null) {
      return const Body();
    } else {
      return const CircularProgressIndicator();
    }
  }
}

**Comment by KristianBalaj** [comment]
@rrousselGit looking back on this and you are actually right, `family` is actually the right solution.
