### ISSUE TITLE
useProviderListener pr: fork with 100% test coverage

### ISSUE THREAD

**Issue by 0biWanKenobi** [rrousselGit/river_pod#204]
**What it is this about?**
About [this pull request](https://github.com/rrousselGit/river_pod/pull/168), I forked yiss' repo and tried to complete code coverage, [adding a couple tests](https://github.com/yiss/river_pod/pull/1). 

**Where do we go from here?**
This was done in hope that useProviderListener could hopefully be merged and relesed. Please note, this is my first experience with Codecov, and even if I'm reasonably sure coverage is complete, I may be wrong 😟

**Comment by rrousselGit** [comment]
Closing as per my comment on the PR https://github.com/rrousselGit/river_pod/pull/168#issuecomment-739956629

If you want to use this PR, use a git dependency instead.
I don't think promoting hooks is a good solution and am working on a unified syntax
