### ISSUE TITLE
What should I do to pass events from provider to view?

### ISSUE THREAD

**Issue by tbm98** [rrousselGit/river_pod#21]
What should I do to pass events from provider to view? For example from the provider I want to pass an event that displays a dialog or a snackbar.

**Comment by rrousselGit** [comment]
Could you expand on this? I don't understand the question.

**Comment by tbm98** [comment]
In a real world example, when the user clicks the login button, I will call the login (username, password) function of the provider. and provider after processing will display the result of success or failure, View will display a dialog message to the user. But in this case, the provider cannot directly display the dialog message.

**Comment by rrousselGit** [comment]
It is not the role of providers to display dialogs.

Make your provider return the result, and have the UI process that result to display things

**Comment by tbm98** [comment]
I think if you do that, the view will have to handle a bit of logic. As with MVP architecture, View will only provide an interface to the presenter and the View will not implement any logic.

**Comment by rrousselGit** [comment]
Showing a modal is not business logic but UI logic.
The business logic is to set the error message.

**Comment by tbm98** [comment]
in some special cases, an intermittent process and it needs to show the message while it has not finished running. For example, the process of loading my data consists of 5 parts, and after the download is complete, each part will display a message and continue to download the next part, if processed in View, there will need 5 separate functions or At least logic view will have to call at 5 times.
like this
```
void loadDataClicked() async{
 final aResult = await notifier.load(a);
 if(aResult.isSuccess()){
   showDialog(aResult);
 }else{
 return;
 }

 final bResult = await notifier.load(b);
 if(bResult.isSuccess()){
   showDialog(bResult);
 }else{
 return;
 }

 final cResult = await notifier.load(c);
 if(cResult.isSuccess()){
   showDialog(cResult);
 }else{
 return;
 }

 final dResult = await notifier.load(d);
 if(dResult.isSuccess()){
   showDialog(dResult);
 }else{
 return;
 }

 final eResult = await notifier.load(e);
 if(eResult.isSuccess()){
   showDialog(eResult);
 }else{
 return;
 }
}
```

**Comment by tbm98** [comment]
It would be simpler to write like this:
```
  void showDialog(...){
    // notifier will call it or notifier send event to View => View call it
  }

  void loadDataClicked() {
    notifier.load(a,b,c,d,e);
  }
```

**Comment by rrousselGit** [comment]
Maybe expose a Stream and have the UI listen to it to call `showDialog`.

**Comment by tbm98** [comment]
but how can I listen stream (for user not use hook)?

```
  @override
  Widget build(BuildContext context) {
    Consumer((_, read) {
      print('state is ${read(counterProvider).state}'); //not work
    });
  .....
```
```
  @override
  Widget build(BuildContext context) {
    print('state is ${counterProvider.read(context).state}'); // can't read in build 
    ......
```

**Comment by rrousselGit** [comment]
stream.listen(...) or StreamBuilder

**Comment by tbm98** [comment]
Can you write a simple example about listen stream from View ?

**Comment by rrousselGit** [comment]
myProvider.read(context).myStream.listen(...)

**Comment by tbm98** [comment]
But it throw Exception when use in build.
where should I put it into if I use stateless ?

**Comment by rrousselGit** [comment]
You need a StatefulWidget for this, or hooks. You cannot listen to an object inside StatelessWidgets.

**Comment by tbm98** [comment]
> You need a StatefulWidget for this, or hooks. You cannot listen to an object inside StatelessWidgets.

I think it is a best option for now.
