### ISSUE TITLE
Documentation not showing links on small size

### ISSUE THREAD

**Issue by wottpal** [rrousselGit/river_pod#211]
When I press on the menu button on smaller sizes on https://riverpod.dev/docs/getting_started it shows only "Docs" and no nested menu options. I attached an image showing what I mean. 

Unfortunately this issue was the reason that for almost 1 week I thought the "Getting started" page is the only documentation Riverpod has… Which is a big shame as all the things you have written there are awesome and super helpful!

Regards from Germany 

<img width="1090" alt="Bildschirmfoto 2020-11-06 um 13 08 36" src="https://user-images.githubusercontent.com/3930150/98364541-43eca280-2031-11eb-9181-798a61762827.png">
<img width="1414" alt="Bildschirmfoto 2020-11-06 um 13 08 40" src="https://user-images.githubusercontent.com/3930150/98364552-46e79300-2031-11eb-9261-e30e502f906d.png">

**Comment by iamarnas** [comment]
@wottpal Hi.
![IMG_20201106_162528.png](https://user-images.githubusercontent.com/42679871/98383467-cfbff800-204c-11eb-88bc-7ab18cc1c7f2.png)

**Comment by rrousselGit** [comment]
@iamarnas is correct. The button is on the bottom right

**Comment by wottpal** [comment]
Oh ok, never mind. My brain might not be used to menu buttons on the bottom right..
