### ISSUE TITLE
StateNotifier without documentation to handle multiple values

### ISSUE THREAD

**Issue by andrefedev** [rrousselGit/river_pod#212]
The StateNotifier examples show how to handle a variable, how it could handle multiple variables, change state, listen to only one value. For example I have a form with multiple fields:

    final productNotifierProvider = StateNotifierProvider((ref) => ProductNotifier());

    class ProductNotifier extends StateNotifier<Map<String, String>> {
        ProductNotifier() : super(Map());

        void update(String key, String myValue) {
            state.update(key, (value) => myValue);
        }

        void get clear => state.clear();
     }

Widget

    TextEditingController _controller;

    @override
    initState() {
      super.initState();
      // Initial value pass
      _controller = TextEditingController();
      _controller.addListener(() {
        if (_controller.text.length > 1) {
          context.read(draftNotifierProvider).update('firstName', _controller.text);
        }
      });
    }

    @override
    Widget build(BuildContext context, ScopedReader watch) {
      // Obtains Counter without listening to Counter.state.
      // Will not cause the button to rebuild when the counter changes.
      final draft = watch(draftNotifierProvider);

      return Scaffold(
        appBar: AppBar(),
        body: Column(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            TextField(
              controller: _controller,
            ),
            ElevatedButton(
              onPressed: () => context.read(draftNotifierProvider).clear,
              child: Text('Reset'),
            ),
          ],
        ),
      );
    }

StateNotifierProvider is equal to ChangeNotifierProvider? and StateNotifier replaces ChangeNotifier?

**Comment by iamarnas** [comment]
@andrefedev To handle multiple variables with `StateNotifier` you need put them to the class.

```dart
class Member {
  const Member({
    this.admin = const {},
    this.moderator = const {},
    this.user = const {},
  });

  final Map<String, String> admin;
  final Map<String, String> moderator;
  final Map<String, String> user;

  Member copyWith({
    Map<String, String> admin,
    Map<String, String> moderator,
    Map<String, String> user,
  }) {
    return Member(
      admin: admin ?? this.admin,
      moderator: moderator ?? this.moderator,
      user: user ?? this.user,
    );
  }
}
```
Then you can handle inside `StateNotifier` like that.

```dart
class MemberNotifier extends StateNotifier<Member> {
  MemberNotifier() : super(Member());

  void updateAdmin(String id, String name) {
    final admin = state.admin.update(
      id,
      (_) => name,
      ifAbsent: () => name,
    ) as Map<String, String>;

    state = state.copyWith(admin: admin);
  }

  void updateModerator(String id, String name) {
    final moderator = state.moderator.update(
      id,
      (_) => name,
      ifAbsent: () => name,
    ) as Map<String, String>;

    state = state.copyWith(moderator: moderator);
  }

  void updateUser(String id, String name) {
    final user = state.user.update(
      id,
      (_) => name,
      ifAbsent: () => name,
    ) as Map<String, String>;

    state = state.copyWith(user: user);
  }

  void removeAdmin(String id) {
    state.admin.remove(id);
  }

  void removeModerator(String id) {
    state.moderator.remove(id);
  }

  void removeUser(String id) {
    state.user.remove(id);
  }
}
```
`StateNotifier` maybe looks more advanced like `ChangeNotifier` but by using `StateNotifier` you are forced create safer code. But in practice you can do same things with both.

**Comment by venkatd** [comment]
Hi I would like to mention that if you create a class, you will need to properly implement `==` and `hashCode` to avoid unnecessary rebuilds. Otherwise, Flutter and other libraries may think that the data has updated when it hasn't. For this you can use a package like freezed to generate value objects or equatable if you're just looking to implement `==`

**Comment by iamarnas** [comment]
@venkatd It depends on your needs but often yes, especially if you are writing tests then it must be. I prefer Equatable package + Dart Data Class Generator extension over Freezed. Frezzed leave many unused lines in the background.

**Comment by rrousselGit** [comment]
Closing as this was correctly answered by others :smile:

**Comment by spike04** [comment]
> @andrefedev To handle multiple variables with `StateNotifier` you need put them to the class.
> 
> ```dart
> class ValidationItem {
>   final String value;
>   final String error;
> 
>   const ValidationItem(this.value, this.error);
> }
> 
> class ValidationItems {
>   final ValidationItem email;
>   final ValidationItem password;
> 
>   ValidationItems({
>     this.email = const ValidationItem(null, null),
>     this.password = const ValidationItem(null, null),
>   });
> 
>   ValidationItems copyWith({
>     ValidationItem email,
>     ValidationItem password,
>   }) {
>     return ValidationItems(
>       email: email ?? this.email,
>       password: password ?? this.password,
>     );
>   }
> }
> ```
> 
> Then you can handle inside `StateNotifier` like that.
> 
> ```dart
> class ValidationNotifier extends StateNotifier<ValidationItems> with Validator {
>   ValidationNotifier() : super(ValidationItems());
> 
>   void updateEmail(String value) {
>     if (emailValidator.isValid(value)) {
>       state = state.copyWith(email: ValidationItem(value, null));
>     } else {
>       final error = emailValidator.error(value);
>       state = state.copyWith(email: ValidationItem(null, error));
>     }
>   }
> 
>   void updatePassword(String value) {
>     if (passwordValidator.isValid(value)) {
>       state = state.copyWith(password: ValidationItem(value, null));
>     } else {
>       final error = passwordValidator.error(value);
>       state = state.copyWith(password: ValidationItem(null, error));
>     }
>   }
> 
>   void validate() {
>     if (!passing) return; 
>     debugPrint('''
>     User saved in the DB.
>     User: ${state.email.value}
>     Password: ${state.password.value}
>     ''');
>   }
> 
>   bool get passing {
>     if (!emailValidator.isValid(state.email.value) ||
>         !passwordValidator.isValid(state.password.value)) {
>       return false;
>     } else {
>       return true;
>     }
>   }
> }
> ```
> 
> `StateNotifier` maybe looks more advanced like `ChangeNotifier` but by using `StateNotifier` you are forced create safer code. But in practice you can do same things with both.
> 
> For example if you are interested in how handle multiple `Map` variables. Then look at this example.
> 
> ```dart
> class Member {
>   const Member({
>     this.admin = const {},
>     this.moderator = const {},
>     this.user = const {},
>   });
> 
>   final Map<String, String> admin;
>   final Map<String, String> moderator;
>   final Map<String, String> user;
> 
>   Member copyWith({
>     Map<String, String> admin,
>     Map<String, String> moderator,
>     Map<String, String> user,
>   }) {
>     return Member(
>       admin: admin ?? this.admin,
>       moderator: moderator ?? this.moderator,
>       user: user ?? this.user,
>     );
>   }
> }
> ```
> 
> ```dart
> class MemberNotifier extends StateNotifier<Member> {
>   MemberNotifier() : super(Member());
> 
>   void updateAdmin(String id, String name) {
>     final admin = Map<String, String>.from(state.admin); // Convert it to editable Map.
>     admin.update(id, (_) => name, ifAbsent: () => name); // Update map.
> 
>     state = state.copyWith(admin: admin); // Update state.
>   }
> 
>   void updateModerator(String id, String name) {
>     final moderator = Map<String, String>.from(state.moderator);
>     moderator.update(id, (_) => name, ifAbsent: () => name);
> 
>     state = state.copyWith(moderator: moderator);
>   }
> 
>   void updateUser(String id, String name) {
>     final user = Map<String, String>.from(state.user);
>     user.update(id, (_) => name, ifAbsent: () => name);
> 
>     state = state.copyWith(user: user);
>   }
> 
>   void removeAdmin(String id) {
>     state.admin.remove(id);
>   }
> 
>   void removeModerator(String id) {
>     state.moderator.remove(id);
>   }
> 
>   void removeUser(String id) {
>     state.user.remove(id);
>   }
> }
> ```
> 
> Safe state data handling from the internet with StateNotifier
> The simple counter app which simulate data loading on click.
> 
> **Create data state which represent state handling**
> 
> ```dart
> enum CounterStatus { loading, success, failured }
> 
> class CounterState {
>   const CounterState({this.status = CounterStatus.success, this.number = 0});
>   const CounterState.loading() : this(status: CounterStatus.loading);
>   const CounterState.success(int number)
>       : this(status: CounterStatus.success, number: number);
>   const CounterState.failure() : this(status: CounterStatus.failured);
> 
>   final CounterStatus status;
>   final int number;
> }
> ```
> 
> **Create StateNotifier which hold the data state**
> 
> ```dart
> class CounterNotifier extends StateNotifier<CounterState> {
>   CounterNotifier() : super(const CounterState());
> 
>   int _count = 0;
> 
>   void increment() async {
>     state = const CounterState.loading();
>     try {
>       // Imitate data loading...
>       await Future.delayed(Duration(milliseconds: 300)); // Fetch data.
>       state = CounterState.success(_count += 1);
>     } on Exception {
>       state = const CounterState.failure();
>     }
>   }
> 
>   void decrement() async {
>     state = const CounterState.loading();
>     try {
>       await Future.delayed(Duration(milliseconds: 300));
>       state = CounterState.success(_count -= 1);
>     } on Exception {
>       state = const CounterState.failure();
>     }
>   }
> }
> ```
> 
> **Display state in the widget tree**
> 
> ```dart
> //...
> body: Center(
>         // ignore: missing_return
>         child: Consumer(builder: (context, watch, child) {
>           final counter = watch(counterNotifier.state);
>           final status = counter.status.toString().split('.').last;
> 
>           switch (counter.status) {
>             case CounterStatus.loading:
>               return Text(
>                 '$status...',
>                 style: Theme.of(context).textTheme.headline4,
>               );
>               break;
>             case CounterStatus.success:
>               return Text(
>                 '${counter.number} $status',
>                 style: Theme.of(context).textTheme.headline4,
>               );
>               break;
>             case CounterStatus.failured:
>               return Text(
>                 'Status $status',
>                 style: Theme.of(context).textTheme.headline4,
>               );
>           }
>         }),
>       ),
> //...
> ```
> 
> But if you read this tutorial that mean you using Riverpod. Then you no need create state class for simple data handling Riverpod have one union class `AsyncValue` which will do the same thing with few code lines.
> 
> And here is ends my little tutorial. Hope it helps to someone :)

Hi can you also post the code for Validator mixin as well

**Comment by iamarnas** [comment]
@andrefedev sure. [Login validation](https://gist.github.com/iamarnas/ac1aca37a4b27b2543674933335e071a)

**Comment by Meshkat-Shadik** [comment]
If we can use freezed unions to make a data state, then how can we change the state.

I've a Data state class
```dart
@freezed
abstract class LocationDataState with _$LocationDataState {
  const factory LocationDataState.initial() = _LocationInitial;
  const factory LocationDataState.loading() = _LocationLoading;
  const factory LocationDataState.success(Position position) =
      _LocationSuccess;
  const factory LocationDataState.error([String? message]) = _LocationLoadedError;
}```

and the stateNotifier class is

```dart
class LocationStateNotifer extends StateNotifier<LocationDataState> {
  final LocationRepository locationRepository;
  LocationStateNotifer(this.locationRepository)
      : super(LocationDataState.initial());

  Future<void> getCoordinates() async {
   //work
  }

  Future<Placemark> getLocationName(double longitude, double latitude) async {
  //work  
 }
}```

Now, how can I use the two separate states for representing coordinates and LocationName?

**Comment by Meshkat-Shadik** [comment]
If we can use freezed unions to make a data state, then how can we change the state.

**I've a Data state class**

```dart
@freezed
abstract class LocationDataState with _$LocationDataState {
  const factory LocationDataState.initial() = _LocationInitial;
  const factory LocationDataState.loading() = _LocationLoading;
  const factory LocationDataState.success(Position position) =
      _LocationSuccess;
  const factory LocationDataState.error([String? message]) = _LocationLoadedError;
}

```


**and the stateNotifier class is**

```dart
class LocationStateNotifer extends StateNotifier<LocationDataState> {
  final LocationRepository locationRepository;
  LocationStateNotifer(this.locationRepository)
      : super(LocationDataState.initial());

  Future<void> getCoordinates() async {
   //work
  }

  Future<Placemark> getLocationName(double longitude, double latitude) async {
  //work  
 }
}

```

Now, how can I use the two separate states for representing coordinates and LocationName?

**Comment by Meshkat-Shadik** [comment]
@iamarnas brother I've a query

If we use freezed unions to make a data state, then how can we change the state.

**I've a Data state class**

```dart
@freezed
abstract class LocationDataState with _$LocationDataState {
  const factory LocationDataState.initial() = _LocationInitial;
  const factory LocationDataState.loading() = _LocationLoading;
  const factory LocationDataState.success(Position position) =
      _LocationSuccess;
  const factory LocationDataState.error([String? message]) = _LocationLoadedError;
}

```


**and the stateNotifier class is**

```dart
class LocationStateNotifer extends StateNotifier<LocationDataState> {
  final LocationRepository locationRepository;
  LocationStateNotifer(this.locationRepository)
      : super(LocationDataState.initial());

  Future<void> getCoordinates() async {
   //state1 for coordinate
  }

  Future<void> getLocationName(double longitude, double latitude) async {
  //state 2 for cityName
 }
}

```

Now, how can I use the two separate states for representing coordinates and LocationName?

**Comment by iamarnas** [comment]
@Meshkat-Shadik Hi. It should look like something like that:

```dart
class LocationStateNotifer extends StateNotifier<LocationDataState> {
  final LocationRepository locationRepository;
  LocationStateNotifer(this.locationRepository)
      : super(const LocationDataState.initial());

  Future<void> getCoordinates() async {
    state = const LocationDataState.loading();
    //state1 for coordinate
    try {
      // Data handling from the locationRepository.
      state = LocationDataState.success(data);
    } catch (e) {
      state = const LocationDataState.error();
    }
  }

  Future<void> getLocationName(double longitude, double latitude) async {
    state = const LocationDataState.loading();
    //state 2 for cityName
    try {
      // Data handling from the locationRepository.
      state = LocationDataState.success(data);
    } catch (e) {
      state = const LocationDataState.error();
    }
  }
}
```

**Comment by Meshkat-Shadik** [comment]
> @Meshkat-Shadik Hi. It should look like something like that:
> 
> ```dart
> class LocationStateNotifer extends StateNotifier<LocationDataState> {
>   final LocationRepository locationRepository;
>   LocationStateNotifer(this.locationRepository)
>       : super(const LocationDataState.initial());
> 
>   Future<void> getCoordinates() async {
>     state = const LocationDataState.loading();
>     //state1 for coordinate
>     try {
>       // Data handling from the locationRepository.
>       state = LocationDataState.success(data);
>     } catch (e) {
>       state = const LocationDataState.error();
>     }
>   }
> 
>   Future<void> getLocationName(double longitude, double latitude) async {
>     state = const LocationDataState.loading();
>     //state 2 for cityName
>     try {
>       // Data handling from the locationRepository.
>       state = LocationDataState.success(data);
>     } catch (e) {
>       state = const LocationDataState.error();
>     }
>   }
> }
> ```

Aren't the state used in two separate methods are the same state? 
Can I use 2 different state?
If any condition arise where I've to use 2 different state from a single StateNotifier class,  can it be possible? With freezed union classes obviously!

**Comment by iamarnas** [comment]
@Meshkat-Shadik In your case `LocationDataState` update only `Position`. If you want update more objects in your `Freezed` class you need add one more class by parameters.

```dart
@freezed
abstract class LocationDataState with _$LocationDataState {
  const factory LocationDataState.initial() = _LocationInitial;
  const factory LocationDataState.loading() = _LocationLoading;
  const factory LocationDataState.coordinates(Position position) =
      _LocationSuccess;
LocationDataState.location(Location location) =
      _LocationSuccess;
  const factory LocationDataState.error([String? message]) = _LocationLoadedError;
} 
```
But you can merge both to one class and use only `success`

**Comment by Meshkat-Shadik** [comment]
> @Meshkat-Shadik In your case `LocationDataState` update only `Position`. If you want update more objects in your `Freezed` class you need add one more class by parameters.
> 
> ```dart
> @freezed
> abstract class LocationDataState with _$LocationDataState {
>   const factory LocationDataState.initial() = _LocationInitial;
>   const factory LocationDataState.loading() = _LocationLoading;
>   const factory LocationDataState.coordinates(Position position) =
>       _LocationSuccess;
>   const factory LocationDataState.location(Location location) =
>       _LocationSuccess;
>   const factory LocationDataState.error([String? message]) = _LocationLoadedError;
> } 
> ```
> 
> But you can merge both to one class and use only `success`

Ok brother, 
You previously showed an example of Member class,  in that Member had 3 properties, admin, moderator, user.

If I want to make that type of approach with Freezed Union classes, then how it be look like?

N:B: this is my last query, I'm sorry for asking too much questions. ❤️

**Comment by iamarnas** [comment]
@Meshkat-Shadik OK, here is a little example of how to handle `Member` class state with union Freezed classes.

```dart
/// The union class which provide state of the `Member` class from the previously showed example.
@freezed
class MemberState with _$MemberState {
  const factory MemberState.initial() = _MemberStateInitial;
  const factory MemberState.loading() = _MemberStateLoading;
  const factory MemberState.success(Member member) = _MemberStateSuccess;
  const factory MemberState.error([Object? error]) = _MemberStateError;
}
```
```dart
/// The `StateNotifier` which handle state of the [MemberState].
class MemberStateNotifier extends StateNotifier<MemberState> {
  MemberStateNotifier() : super(const MemberState.initial());

  void updateUser(String id, String name) {
    // The state union classes with Freezed has several state method as when, maybeWhen, map, maybeMap.
    // you can use any of them, it depends on which data and how you want handle your data.
    // In my case, I don't need to fetch data from the DB 
    // and I choose a simple method that doesn't require handle loading state and errors.
    state = state.maybeWhen(
        success: (member) {
          final user = Map<String, String>.from(member.user);
          user.update(id, (_) => name, ifAbsent: () => name);
          member.copyWith(user: user);
          return MemberState.success(member);
        },
        orElse: () => const MemberState.initial());
  }

  void removeUser(String id) {
    state = state.maybeWhen(
        success: (member) {
          if (member.user[id] != null) {
            member.user.remove(id);
          }
          return MemberState.success(member);
        },
        orElse: () => const MemberState.initial());
  }
}
```

**Comment by Meshkat-Shadik** [comment]
> @Meshkat-Shadik OK, here is a little example of how to handle `Member` class state with union Freezed classes.
> 
> ```dart
> /// The union class which provide state of the `Member` class from the previously showed example.
> @freezed
> class MemberState with _$MemberState {
>   const factory MemberState.initial() = _MemberStateInitial;
>   const factory MemberState.loading() = _MemberStateLoading;
>   const factory MemberState.success(Member member) = _MemberStateSuccess;
>   const factory MemberState.error([Object? error]) = _MemberStateError;
> }
> ```
> 
> ```dart
> /// The `StateNotifier` which handle state of the [MemberState].
> class MemberStateNotifier extends StateNotifier<MemberState> {
>   MemberStateNotifier() : super(const MemberState.initial());
> 
>   void updateUser(String id, String name) {
>     // The state union classes with Freezed has several state method as when, maybeWhen, map, maybeMap.
>     // you can use any of them, it depends on which data and how you want handle your data.
>     // In my case, I don't need to fetch data from the DB 
>     // and I choose a simple method that doesn't require handle loading state and errors.
>     state = state.maybeWhen(
>         success: (member) {
>           final user = Map<String, String>.from(member.user);
>           user.update(id, (_) => name, ifAbsent: () => name);
>           member.copyWith(user: user);
>           return MemberState.success(member);
>         },
>         orElse: () => const MemberState.initial());
>   }
> 
>   void removeUser(String id) {
>     state = state.maybeWhen(
>         success: (member) {
>           if (member.user[id] != null) {
>             member.user.remove(id);
>           }
>           return MemberState.success(member);
>         },
>         orElse: () => const MemberState.initial());
>   }
> }
> ```

Thanks and lot of love from bottom of my heart ❤️
You're my savior!

**Comment by Meshkat-Shadik** [comment]
@iamarnas 

**This is My StateNotifier Class**

```dart
class LocationStateNotifer extends StateNotifier<LocationDataState> {
  final LocationRepository locationRepository;
  LocationStateNotifer(this.locationRepository)
      : super(const LocationDataState.initial());

  Future<void> getCoordinates() async {
    try {
      Position data = await locationRepository.getCoordinates();
      print(data);
      state = state.maybeWhen(
         loading: () {
         print("loading\n");
         return LocationDataState.loading();
         },
        success: (address) {
          print("success\n");
          address.copyWith(position: data);
          return LocationDataState.success(address);
        },
        orElse: () {
          print("or else\n");
          return LocationDataState.initial();
        },
      );
    } catch (e) {
      state = LocationDataState.error("$e");
    }
  }
}
```

This is in my UI class

```dart
 Consumer(
                        builder: (context, watch, child) {
                          final locationState =
                              watch(locationStateNotifierProvider);

                          return locationState.maybeWhen(
                            loading: () => CircularProgressIndicator(),
                            success: (data) =>
                                buildSuccessLocation(data!.position, context),
                            error: (e) => Text(
                              e.toString(),
                              style: TextStyle(color: Colors.white),
                            ),
                            orElse: () => TextButton(
                              onPressed: () {
                                context
                                    .read(
                                        locationStateNotifierProvider.notifier)
                                    .getCoordinates();
                              },
                              child: Text(
                                "Hello",
                                style: bigTitleStyle.copyWith(fontSize: 24),
                              ),
                            ),
                          );
                        },
                      ),
```

I always stuck at the orElse method. I don't understand why this is happening. I was forced to spend 2 hours and checking all things by printing, but I couldn't solve it yet!

The output from debug console
```dart
I/flutter (13194): Latitude: 22.85370663, Longitude: 89.53441124
I/flutter (13194): or else
```

**Comment by iamarnas** [comment]
@Meshkat-Shadik

> I always stuck at the orElse method.

Or else mean that you have error in your data handling. Try debug and read error state.

**Comment by iamarnas** [comment]
@Meshkat-Shadik

I would recommend use [AsyncValue](https://github.com/rrousselGit/river_pod/blob/0542abbd06674c6e57fe16b0a6759232fe5f3d15/packages/riverpod/lib/src/common.dart#L65) if you want only handle loading and error state. 

```dart
  class MyNotifier extends StateNotifier<AsyncValue<MyData> {
     MyNotifier(): super(const AsyncValue.loading()) {
       _fetchData();
     }
  
     Future<void> _fetchData() async {
       state = const AsyncValue.loading();
       try {
         final response = await dio.get('my_api/data');
         final data = MyData.fromJson(response);
         state = AsyncValue.data(data);
       } catch (err, stack) {
         state = AsyncValue.error(err, stack);
       }
     }
  }
```

**Comment by Meshkat-Shadik** [comment]
As I've no experience with AsyncValue I can't implement it. But I can understand that

```dart
class LocationStateNotifer extends StateNotifier<LocationDataState> {
  final LocationRepository locationRepository;
  LocationStateNotifer(this.locationRepository)
      : super(const LocationDataState.initial());

  Future<void> getCoordinates() async {
    try {
      Position data = await locationRepository.getCoordinates();
      print(data);
      state = state.maybeWhen(
         loading: () {
         print("loading\n");
         return LocationDataState.loading();
         },
        success: (address) {
          print("success\n");
          address.copyWith(position: data);
          return LocationDataState.success(address);
        },
        orElse: () {
          print("or else\n");
          return LocationDataState.initial();
        },
      );
    } catch (e) {
      state = LocationDataState.error("$e");
    }
  }
}
```
success is not called for not getting the value, because the value is asynchronous. 

I tried to make it like this, but this is not possible.

```dart
 success: (address) async{
          print("success\n");
          await  address.copyWith(position: data);
          return LocationDataState.success(address);
        },
```

though it looks like fun, I'm done with that! 
Need a bit of sleep, all day with this problem.

Thanks for replying to my queries to live the stubbornness of myself with flutter.

**Comment by iamarnas** [comment]
@Meshkat-Shadik

Good morning. I feel like I gave you a bad example and I'm very sorry for that. It happens when you do not have a computer nearby and do not programming  `Dart` for a long time.
 In your case, your `LocationDataState` inside `StateNotifier` would look like this:
```dart
final locationStateNotifierProvider =
    StateNotifierProvider<LocationStateNotifer, LocationDataState>((ref) {
  final locationRepository = LocationRepository();
  return LocationStateNotifer(locationRepository);
});

class LocationStateNotifer extends StateNotifier<LocationDataState> {
  final LocationRepository locationRepository;
  LocationStateNotifer(this.locationRepository)
      : super(const LocationDataState.initial());

  Future<void> getCoordinates() async {
    try {
      state = const LocationDataState.loading();
      final data = await locationRepository.getCoordinates();
      final position = Position(position: data);
      state = LocationDataState.success(position);
    } catch (e) {
      state = LocationDataState.error("$e");
    }
  }
}
```
And put the `LocationDataState` to the UI.
```dart
//.....
Consumer(
  builder: (context, watch, child) {
    final locationState = watch(locationStateNotifierProvider);

    return locationState.maybeWhen(
       loading: () => const CircularProgressIndicator(),
       success: (data) => Text(data.position.toString()),
       orElse: () => TextButton(
          onPressed: () {
              context
                .read(locationStateNotifierProvider.notifier)
                .getCoordinates();
          },
          child: const Text("Hello"),
       ),
    );
  },
),
//.....
```
I hope this makes your new day more enjoyable.

**Comment by Meshkat-Shadik** [comment]
> @Meshkat-Shadik
> 
> Good morning. I feel like I gave you a bad example and I'm very sorry for that. It happens when you do not have a computer nearby and do not programming `Dart` for a long time.
> In your case, your `LocationDataState` inside `StateNotifier` would look like this:
> 
> ```dart
> final locationStateNotifierProvider =
>     StateNotifierProvider<LocationStateNotifer, LocationDataState>((ref) {
>   final locationRepository = LocationRepository();
>   return LocationStateNotifer(locationRepository);
> });
> 
> class LocationStateNotifer extends StateNotifier<LocationDataState> {
>   final LocationRepository locationRepository;
>   LocationStateNotifer(this.locationRepository)
>       : super(const LocationDataState.initial());
> 
>   Future<void> getCoordinates() async {
>     try {
>       state = const LocationDataState.loading();
>       final data = await locationRepository.getCoordinates();
>       final position = Position(position: data);
>       state = LocationDataState.success(position);
>     } catch (e) {
>       state = LocationDataState.error("$e");
>     }
>   }
> }
> ```
> 
> And put the `LocationDataState` to the UI.
> 
> ```dart
> //.....
> Consumer(
>   builder: (context, watch, child) {
>     final locationState = watch(locationStateNotifierProvider);
> 
>     return locationState.maybeWhen(
>        loading: () => const CircularProgressIndicator(),
>        success: (data) => Text(data.position.toString()),
>        orElse: () => TextButton(
>           onPressed: () {
>               context
>                 .read(locationStateNotifierProvider.notifier)
>                 .getCoordinates();
>           },
>           child: const Text("Hello"),
>        ),
>     );
>   },
> ),
> //.....
> ```
> 
> I hope this makes your new day more enjoyable.

A great morning for me.
In the model class  
```dart
final position = Position(position: data);
```
This Position can't be initialized, because it needs at least 7/8 parameters. (because it is from geolocator package)
So, I turned in a custom Position Class that solves the issue.

Thanks a lot, brother. <3
