### ISSUE TITLE
Conflict between flutter_bloc using context.read and river_pod context.read

### ISSUE THREAD

**Issue by mario202k** [rrousselGit/river_pod#214]
Now context.bloc is deprecated, it's context.read or context.watch. How to force using the context.read of river_pod?

**Comment by maxzod** [comment]
use `hide`  keyword after the un-wanted package import line 
example if you want to use read and watch from the ``riverpod`` package 
```dart
import 'package:flutter_bloc/flutter_bloc.dart' hide ReadContext;
```
this should fix
