### ISSUE TITLE
Provider.autoDispose.family build error - flutter web

### ISSUE THREAD

**Issue by MOPineyro** [rrousselGit/river_pod#215]
**Describe the bug**
Using flutter web, creating a provider and combing `autoDispose` and `family` modifiers will work in debug mode but on building a release will error.

**To Reproduce**
sample repo:
https://github.com/MOPineyro/test_riverpod

Run:
`flutter run -d chrome`
You will see the test string provider working

Then Run:
`flutter run -d chrome --release`

The console will produce the following error:
```
Unsupported operation: Unknown ProviderListenable minified:ht<dynamic>#00002(from: Instance of 'minified:mU<dynamic, dynamic>', argument: TEST STRING)
```

**Comment by edmbn** [comment]
Maybe duplicated of #71 ?

**Comment by rrousselGit** [comment]
Duplicate of #71
