### ISSUE TITLE
Interaction between multiple StateNotifierProvider and initState

### ISSUE THREAD

**Issue by SandroMaglione** [rrousselGit/river_pod#218]
Hi Remi,

I recently started using riverpod and I am trying to refactor a project of mine from Bloc to riverpod. I'm having some difficulties in handling a slightly complex usecase.

I have a provider that must be initialized when the route is opened with some parameters coming from the screen widget:
```dart
class MyScreen extends HookWidget {
  final Param param;

  const MyScreen({
    @required this.param,
  });
}
```
`param` must be passed to the provider and the provider should be initialized (asynchronously) as soon as the route is opened.

I cannot use a `FutureProvider` because I need some custom states, and not just loading, error, and data. `FutureProvider` cannot work also because then my state will change again to another custom state when a function is called.

I'm having problems also with `family`. I would like to be able to pass the `param` only when the provider is initialized and then access it (`watch`) without passing any parameter.

```dart
  @override
  Widget build(BuildContext context) {
    // I should initialize the provider here passing 'param'
    // but then call 'watch' without passing any parameter after it is initialized
    final initSomeProvider = useProvider(someProvider(Params(param)));
```

The correct provider should be `StateNotifierProvider`, but I also here I have problems with `family` for the same reason above.
***
I am also having another issue with `StateNotifierProvider`. Ideally, I would need to update a provider when the computation (async) of another provider is completed:
```dart
class SomeProvider extends StateNotifier<Data> {
  SomeProvider() : super(null);

  Future<void> add() async {
    final String value = await someFun();
    // Here I want to send the result of the function (value) to update AnotherProvider
    // Calling the update function of AnotherProvider passing 'value'
  }
}

class AnotherProvider extends StateNotifier<Data> {
  AnotherProvider() : super(null);

   void update(String value) {}
}
```
I am not sure how (and if) I can do this.

Is it possible to solve in some other way this usecase? How can I initialize the provider (I cannot use the provider in `initState`, correct?) passing only the first time some parameters?

**Comment by rrousselGit** [comment]
>  I would like to be able to pass the param only when the provider is initialized and then access it (watch) without passing any parameter.

you can't and shouldn't

You need to change your model such that the parameter is something like an ID

> Ideally, I would need to update a provider when the computation (async) of another provider is completed:

Since that other provider exposes a `StateNotifier`, its state should expose a `Future` that you can await
