### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by DevNico** [rrousselGit/river_pod#220]
Null safety is in the second technical preview stage with flutter core support it's therefore time to start migrating packages. I'd be happy to open a PR for Null Safety if it isn't already in the works.

**Comment by gaetschwartz** [comment]
I agree, we should now really start the migration as null safety will be ready for apps to migrate early 2021. Moreover, `riverpod` won't be straightforward to migrate so we'd better off starting as early as possible.

I would have happily provided my help but I unfortunately have exams soon. 

![image](https://user-images.githubusercontent.com/25441359/102784401-a1983c80-439c-11eb-9c34-c124b23a0cc6.png)

**Comment by DevNico** [comment]
@rrousselGit Do you already have something in the works or would you be fine with me taking a look at migrating this package?

**Comment by rrousselGit** [comment]
I haven't started on that area (partly because of #246)

But I'd be happy to review a pull request

**Comment by DevNico** [comment]
Just looked into it and this is blocked by `mockito`, `trotter` and `freezed` /  `freezed_annotation` / `json_annotation`. As suggested by the dart migration guide we should probably wait for those dependencies to have migrated.

**Comment by SteveAlexander** [comment]
json_annotation is null-safe already: 4.0.0-nullsafety.0 is available from pub: https://pub.dev/packages/json_annotation/versions/4.0.0-nullsafety.0

freezed is fine for null-safety as a build dependency: https://pub.dev/packages/freezed#non-nullable

mockito is fine for null-safety as a build dependency: https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md

trotter needs looking at!

So I'd suggest that once trotter is made null-safe, it might be okay to unblock working on null safety for riverpod

**Comment by rrousselGit** [comment]
trogger/freezed/mockito are dev dependencies

Riverpod can be migrated without these being migrated

**Comment by DevNico** [comment]
I will start migrating then and keep you guys posted / ask your opinion @rrousselGit when something requires a decision to be made.

**Comment by gaetschwartz** [comment]
@DevNico Any updates ? I'd gladly help if needed !

**Comment by duttaoindril** [comment]
@DevNico Any updates? Need any help?

**Comment by DevNico** [comment]
Unfortunately I really haven't had much time because of work / exams. Sorry about that. You can go ahead and work on it @duttaoindril or @gaetschwartz.

**Comment by duttaoindril** [comment]
> Unfortunately I really haven't had much time because of work / exams. Sorry about that. You can go ahead and work on it @duttaoindril or @gaetschwartz.

Want to share everything so far in a branch so we can launch off of that?

**Comment by rrousselGit** [comment]
I'm finishing the migration of Freezed this weekend, and I'll migrate Riverpod (as it depends on Freezed).

**Comment by duttaoindril** [comment]
Awesome!

Thank you!

Thank you,
Sincere Regards,
Oindril Dutta

**Comment by rrousselGit** [comment]
0.13.0-nullsafety.0 is now available 🎉
