### ISSUE TITLE
API referene link is throwing a 404 error on riverpod.dev/docs

### ISSUE THREAD

**Issue by KhalidWar** [rrousselGit/river_pod#221]
**Describe what scenario you think is uncovered by the existing examples/articles**
**API referene** link in the last line of "What to read" section is throwing a 404 error.

**Link**: https://riverpod.dev/docs/concepts/reading#deciding-what-to-read

**Describe why existing examples/articles do not cover this case**
It's a broken link

**Additional context**
Tried it on Chrome jus tto make sure and it's still thorwing 404 error.

**Comment by rrousselGit** [comment]
Thanks for the report!
