### ISSUE TITLE
ReplayProvider for saving latest values

### ISSUE THREAD

**Issue by softronaut** [rrousselGit/river_pod#224]
**What I need?**
A `ReplayProvider` that behaves similar to `StateProvider` but also saves the last `X` values.

**Why?**
In many cases I need to compare latest 2-3 values. Best example would be stock/currency prices change animations(usually green flash if goes up, red if down). Or during animating `BottomNavigationBar` pages, you choose the animation depending on the last index and current index.

**Similar Concepts**
`RxDart` has `ReplaySubject` as most of you know, which is behaves exactly I want. But I don't want to use that bloated inorganic library.

**Comment by rrousselGit** [comment]
That isn't the responsibility of the providers.

Instead, consider making a custom StateNotifier:


```dart
abstract class ReplayStateNotifier<T> extends StateNotifier<T> {
  ReplayStateNotifier({@required T initialValue, @required this.historyLength}):
      _history = [initialValue],
      super(initialValue);

  final int historyLength

  List<T> _history;

  @override
  set state(T value) {
    _history = [value, ...history];
    if (_history.length > historyLength)
      _history.removeLast();
  }
}

**Comment by softronaut** [comment]
@rrousselGit I gout your point, yea `Riverpod` shouldn't be bloated also 😄  I'm using a similar solution, but I think I should make a library for more opinionated usages of Riverpod.

**Comment by rrousselGit** [comment]
Indeed

I've seen many people argue that Riverpod already _is_ bloated, so I want to avoid adding too niche features.

**Comment by softronaut** [comment]
Hey @rrousselGit, please be my first code reviewer 😄 
```
abstract class ReplayStateNotifier<T> extends StateNotifier<T> {
  ReplayStateNotifier({@required T initialValue, this.capacity = 2})
      : assert(capacity != null, "Capacity cannot be null"),
        assert(capacity > 1,
            "Capacity must be greater than 1, if it's not consider using `StateNotifier` itself"),
        _queue = ListQueue<T>(capacity)..add(initialValue),
        super(initialValue);

  final int capacity;
  final ListQueue<T> _queue;
  int _size = 1;

  @protected
  @override
  set state(T value) {
    if (_size == capacity) {
      _queue.removeLast();
    } else {
      _size++;
    }
    _queue.addFirst(value);
    state = value;
  }

  List<T> get replay {
    if (_size == capacity) return _queue.toList();
    return _queue.take(_size).toList();
  }

  List<T> take(int count) {
    assert(count > 1, 'Count must be greater than 1, otherwise consider using `state`');
    if (_size < count) throw StateError('Few elements to take');
    if (_size == capacity && count == capacity) return _queue.toList();
    return _queue.take(count).toList();
  }

  T get second => _queue.elementAt(1);

  T get last {
    if (_size == capacity) return _queue.last;
    return _queue.elementAt(_size);
  }
}
```

After writing tests, I'll publish this and gonna update time to time with new classes.
