### ISSUE TITLE
Question, How watch works

### ISSUE THREAD

**Issue by sm2017** [rrousselGit/river_pod#227]
Can you show me the source code of `watch`, I'm willing to know how it works internally
I see source of `Provider` packages and understand that it is base on `context.dependOnInheritedElement`, But I cannot found watch source in river_pod

**Comment by rrousselGit** [comment]
See the source code of `ConsumerWidget`, more specifically the `_reader` method

https://github.com/rrousselGit/river_pod/blob/81bf22343ad483b4ffd603d4e3fa8adaf090d807/packages/flutter_riverpod/lib/src/consumer.dart#L313

**Comment by sm2017** [comment]
@rrousselGit Thanks for your response, the key is `markNeedsBuild`, Right?

**Comment by rrousselGit** [comment]
Yes
That's just a setState

**Comment by sm2017** [comment]
@rrousselGit Why you told `That's just a setState` ?? may be we are in a `StatelessWidget`

>Marks the element as dirty and adds it to the global list of widgets to rebuild in the next frame.
>
>Since it is inefficient to build an element twice in one frame, applications and widgets should be structured so as to only mark widgets dirty during event handlers before the frame begins, not during the build itself.

**Comment by sm2017** [comment]
@rrousselGit Can you please reply

**Comment by rrousselGit** [comment]
markNeedsBuild and setState are the same thing  and all widgsts have it

**Comment by sm2017** [comment]
> all widgsts have it

Can you please refer me to official doc?
AFAIK , only `StatefulWidget` has setState

https://api.flutter.dev/flutter/widgets/State/setState.html

**Comment by sm2017** [comment]
@rrousselGit Can you please help me, I read source code of flutter_hooks too and I see that you contributed to that project too

I want to add an `Extension` to `BuildContext`, I want to listen to a stream, But I don't know how can I cancel listening when `Element` is removed


```dart
extension WatchStreamContext on BuildContext {
   void watchStream(int id){
        final stream = GetStreamFromServiceLocator(id);
        final streamSubscription = stream.listen((value) {
            (this as Element).markNeedsBuild();
        });
       //streamSubscription.cancel();
   }
}
```

**Comment by rrousselGit** [comment]
> I want to add an Extension to BuildContext, I want to listen to a stream, But I don't know how can I cancel listening when Element is removed

This is not possible
