### ISSUE TITLE
More and simplified control in listening/rebuilding/filtering state changes

### ISSUE THREAD

**Issue by ianjaspersantos** [rrousselGit/river_pod#228]
**Is your feature request related to a problem? Please describe.**
- I have this scenario where I want to listen to every state changes and make some action in a filtered manner. BTW I'm using StateNotifier here... The problem while I'm using ProviderListener I can't really get what state really changes.

Example in Bloc:
1. If the leftCount state changes in the CounterCubit it will show a dialog for left counter notifying that it was changed
2. If the rightCount state changes in the CounterCubit it will show a dialog for right counter notifying that it was changed
```dart
class CounterPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiBlocListener(
      listeners: [
        BlocListener<CounterCubit, CounterState>(
          listenWhen: (previous, current) => previous.leftCount != current.leftCount,
          listener: (context, state) {
            showDialog(
              context: context,
              builder: (context) {
                return AlertDialog(
                  title: Text('A Side Effect'),
                  content: Text('Left Counter Incremented'),
                  actions: [
                    TextButton(
                      onPressed: () => Navigator.of(context).pop(),
                      child: Text('OK'),
                    ),
                  ],
                );
              },
            );
          },
        ),
        BlocListener<CounterCubit, CounterState>(
          listenWhen: (previous, current) => previous.rightCount != current.rightCount,
          listener: (context, state) {
            showDialog(
              context: context,
              builder: (context) {
                return AlertDialog(
                  title: Text('A Side Effect'),
                  content: Text('Right Counter Incremented'),
                  actions: [
                    TextButton(
                      onPressed: () => Navigator.of(context).pop(),
                      child: Text('OK'),
                    ),
                  ],
                );
              },
            );
          },
        ),
      ],
      child: ...,
    );
  }
}
```

Example using Riverpod's StateNotifier: (Same Goal)
```dart
class CounterPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ProviderListener<CounterStateNotifier>(
      provider: counterProvider,
      onChange: (context, value) {
        // How to know if the left count changes (over) or the right count changes? (Main Problem)
        // Would you suggest we manually keep track of the previous values of the state or flags?
        // And if I'm trying to access the state it says
        // The member 'state' can only be used within instance members of
      },
      child: ...,
    );
  }
}

```

**Describe the solution you'd like**
- Want to have a full control in listening/filtering state changes to make filtered actions.

**Describe alternatives you've considered**
- For this example/scenario, previous value/state is useful when you want to know if left count changes or the right count changes
- Im taking this from the provider example
```dart
// This code rebuild widget only if p.name changes
Widget build(BuildContext context) {
  final name = context.select((Person p) => p.name);
  return Text(name);
}

// This code will trigger only if listened state changes
context.listen((CounterState state) => state.leftCount, (state) {
  // This will only trigger when leftCount changes
  // showDialog for leftCount here...
});

// This code will trigger only if listened state changes
context.listen((CounterState state) => state.rightCount, (state) {
  // This will only trigger when rightCount changes
  // showDialog for rightCount here...
});

// Furthermore, listening in more fine grained manner
context.listenWhen<CounterState>((previous, current) => previous.leftCount < current.leftCount, (state) {
  // This will only trigger when leftCount incremented
  // showDialog for leftCount incremented here...
});

// Furthermore, listening in more fine grained manner
context.listenWhen<CounterState>((previous, current) => previous.leftCount > current.leftCount, (state) {
  // This will only trigger when leftCount decremented
  // showDialog for leftCount decremented here...
});
```

**Additional context**
<img src="https://user-images.githubusercontent.com/57083058/100497943-aa309500-3199-11eb-9ecb-f1009d245fd4.png" height="320">
<img src="https://user-images.githubusercontent.com/57083058/100497948-aef54900-3199-11eb-8323-4d92caa315a1.png" height="320">
<img src="https://user-images.githubusercontent.com/57083058/100497952-b3216680-3199-11eb-9a55-35cbb47729a2.png" height="320">
<img src="https://user-images.githubusercontent.com/57083058/100497954-b6b4ed80-3199-11eb-8fbb-1d878352c4ea.png" height="320">
<img src="https://user-images.githubusercontent.com/57083058/100497956-bae10b00-3199-11eb-962f-2aa050452029.png" height="320">

**Comment by xbrny** [comment]
> The problem while I'm using ProviderListener I can't really get what state really changes.

I had the same issue with ProviderListener when using StateNotifierProvider, the onChange is not triggered at all when the state changes. However onChange does trigger when using StateProvider. Did I miss something about ProviderListener+StateNotifierProvider?

**Comment by TimWhiting** [comment]
@xbrny 
Your problem might be that you are listening to the provider and not the state?

Remember for StateNotifierProvider you need to do myNotifierProvider.state when you want to listen to state changes and not changes in the provider itself.

**Comment by xbrny** [comment]
@TimWhiting 
You're right, thank you! I'm still not familiar with the generic type of this package. Also I'm sorry OP, just realized that my problem is different than yours.

**Comment by rrousselGit** [comment]
Closing in favor of #335 which adds support for `ref.watch(provider.select(...))`
