### ISSUE TITLE
ScopedStateNotifierProvider missing?

### ISSUE THREAD

**Issue by eggnstone** [rrousselGit/river_pod#229]
There are ScopedProvider and StateNotifierProvider but no combination of them i.e. a ScopedStateNotifierProvider.

Use case:
I want to have a viewmodel for a screen that is scoped to that screen, e.g. a LogInOrRegister screen that does not retain its values when the user enters the screen again after logging out.

I tried ScopedProvider<Class_That_Extends_StateNotifier> but the compiler complains when using context.read(provider):
`error: The argument type 'ScopedProvider<LoginOrRegisterNotifier>' can't be assigned to the parameter type 'RootProvider<Object, dynamic>'. (argument_type_not_assignable)`

**Comment by rrousselGit** [comment]
There is no such thing. It is not possible to implement due to how scoped providers work.

**Comment by rrousselGit** [comment]
> I want to have a viewmodel for a screen that is scoped to that screen, e.g. a LogInOrRegister screen that does not retain its values when the user enters the screen again after logging out.

Such scenario is a use-case for `autoDispose` instead

See https://riverpod.dev/docs/concepts/modifiers/auto_dispose
