### ISSUE TITLE
Missing documentation on ScopedProvider / package:provider use cases

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [rrousselGit/river_pod#231]
## Problems

1. So I had this page long issue written out on how `package:provider` features are needed in many cases, just to find out that `ScopedProvider` has already been added 😅

### 1. Why it was it hard to find

So I just stumbled across it by coincidence when reading through all of #6, where I feel like there should be an earlier encounter than that.

### 1. Use cases

Basically, I am missing a section that describes how some patterns that were easily possible using `package:provider` can be solved in Riverpod. It does not even have to be a `package:provider` <> `flutter_riverpod` section because that is just confusing.

Instead, it would be useful to cover some of these topics (where I feel like `ScopedProvider` is the solution to all of them):

* Recursive providers.
* Using different instances of a provider in different parts of an app (e.g. when reusing the same widget).
* Making providers mirror the widget tree.

### 1. Assumption

I assume that the _only_ way to do these things in `flutter_riverpod` properly (without passing values down the widget tree manually, e.g. when you would just pass an ID and then use provider families) is using `ScopeProvider`:

```dart
children: [
  ProviderScope(
    overrides: [
      idProvider.overrideWithValue(1),
    ],
    child: SomeWidget(),
  ),
  ProviderScope(
    overrides: [
      idProvider.overrideWithValue(2),
    ],
    child: SomeWidget(),
  ),
]
````

## Problems

2. The second problem with `ScopedProvider` for me is that there is no documentation on how to use it in regular providers.

If `ScopedProvider` can only be used with `Consumer`, i.e. inside of the widget tree, and not by regular providers, then this problem bounces back to 1.: how do we actually cover recursive providers / ones that follow a tree (widget tree) structure.

**Comment by creativecreatorormaybenot** [comment]
So I just saw your example:

```dart
final appIdProvider = ScopedProvider<int>();
final appProvider = StateNotifierProvider.family<App, int>((ref, id) {});

...
final appId = useProvider(appIdProvider);
final app = useProvider(appProvider(appId));
```

And this kind of makes me think that `ScopedProvider` is actually not a solution to the problems because we need to use **global** (not scoped) provider families again. We could also just pass the ID down the widget tree without Riverpod - so `ScopedProvider` does not really seem to interact with the package 🤔

**Comment by creativecreatorormaybenot** [comment]
So let me put it like this - I want to do something like this:

```dart
final idProvider = ScopeProvider<int>();
final logicProvider = StateNotifierProvider((ref) {
  return Logic(ref.watch(idProvider));
});
final subLogicProvider = StateNotifierProvider((ref) {
  final logic = ref.watch(logicProvider);

  return SubLogic(logic.sub);
});

...
return Row(
  children: [
    ProviderScope(
      overrides: [
        idProvider.overrideWithValue(1),
      ],
      child: SomeWidget(),
    ),
    ProviderScope(
      overrides: [
        idProvider.overrideWithValue(1),
      ],
      child: SomeWidget(),
    ),
  ],
);
```

---

It seems like `ScopedProvider` might not allow to do this at all - in that case, the title is misleading because I am missing documentation for how to work with the cases I put forward in the original comment.

### Example

How would you handle the recursive logic when dealing with file trees / any kind of trees?

![](https://blog.clibu.com/wp-content/uploads/2019/04/clibu_tree_dnd1.gif)

**Comment by rrousselGit** [comment]
What is wrong with having a "global" provider? What is the purpose of scoping it?

If the goal is "destroy the state when no-longer-used", that's what `autoDipose` is for, which is better than scoping providers IMO

Riverpod is a different take on things. My realization with Provider is that scoping providers, while fancy on paper, in practice doesn't work.

`family` and `autoDispose` are here to provide an alternate path to these problems that do not suffer from the limitations of scoping (such as passing state between routes).

___ 



ScopedProvider is really niche and is there more as a performance optimization, to make some widgets "const" for easy build reduction.  
But the doc is already scary. I'm not sure how to introduce it without making things worse, and you can do just fine without it.

**Comment by rrousselGit** [comment]
> So let me put it like this - I want to do something like this:

It appears to me that you want a family:

```dart
final logicProvider = StateNotifierProvider.family<Logic, int>((ref, id) {
  return Logic(id);
});
final subLogicProvider = StateNotifierProvider.family<SubLogic, int>((ref, id) {
  final logic = ref.watch(logicProvider(id));

  return SubLogic(logic.sub);
});
```

**Comment by rrousselGit** [comment]
A not immediately obvious benefit of using family over scoping is:
As apps grow, you are bound to want to access a scoped provider from outside the scope.

With families, that's straightforward: If you have the ID, you can read the provider. 

This also removes the complexity if having to know where you are in the widget tree (and potentially having to deal with "ProviderNotFoundException")

**Comment by creativecreatorormaybenot** [comment]
I actually thought about it in the same way as well.  
In the case that brought the whole thing up for me, I realized that `autoDispose` and `family` would indeed solve it 😄 

But then again, it would not be clean.

The issue I have is that we can have providers that depend on providers and nesting logic just does not seem to scale:

```dart
// The int is the logic ID.
final logicProviderFamily = StateNotifierProvider.autoDispose.family<Logic, int>(..);

// In the logic, we can have sub logic, where that sub logic is associated
// with some part of the main logic via ID again.
final subLogicProviderFamily = StateNotifierProvider.autoDispose.family<SubLogic, SubLogicID>((ref, id) {
  final mainLogic = ref.watch(logicProviderFamily(id.mainLogicID));

  final subLogicData = mainLogic.dataForSubLogicID(id.subLogicID);
 
  ..
});

class SubLogicID {
  final mainLogicID;
  final subLogicID;
  // And now add in ==, hashCode, etc.
}
```

In my case, this is all i would need to handle (no deeper nesting), but it already seems scuffed. If the following worked, it would be so much cleaner:

```dart
final idProvider = ScopeProvider<int>();
final logicProvider = StateNotifierProvider((ref) {
  return Logic(ref.watch(idProvider));
});
final subLogicProvider = StateNotifierProvider((ref) {
  final logic = ref.watch(logicProvider);

  return SubLogic(logic.sub);
});
```

---

However @rrousselGit, I bet that I am just not thinking the right way here. This is where scoping in general would be great to have in the docs because the `.family` docs do not cover a case with nested providers 🤔 

And the docs [also state](https://riverpod.dev/docs/concepts/combining_providers):

> But the reality is, in many situation a provider will want to read the state of another provider.

**Comment by creativecreatorormaybenot** [comment]
# Recursion

So the **Nested logic** section was just about something that is not ideal (where docs would be great but it is doable).  
However, I realized that recursion seems to not be doable.

So coming back to:

![](https://camo.githubusercontent.com/0d31bf91475102d381f57fbfa79aa0a979a3f1d16e8b20ef41d240d7c48455c8/68747470733a2f2f626c6f672e636c6962752e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031392f30342f636c6962755f747265655f646e64312e676966)

I actually implemented a **tree** feature using `Provider`. The tree did allow recursion because expanding nodes was an asynchronous operation.

I am totally lost regarding how that would be managable at all using Riverpod. I assume it is just not doable and I woud have to fallback to `StatefulWidget`s (losing separation of concerns). Would pass the data down the tree using parameters.  
I am not saying this is something that Riverpod needs to solve - I was just wondering.

**Comment by rrousselGit** [comment]
> If the following worked, it would be so much cleaner:

It is not possible to implement.

> The issue I have is that we can have providers that depend on providers and nesting logic just does not seem to scale:

I don't see a scaling/"clean" issue here.  What is your issue?

The only potentially boring part is the hashcode/== for complex parameters.

But my experience is that this is _very_ rare. And even then, you can use Freezed/equatable. And Dart will likely update to have better immutability support in the future

**Comment by creativecreatorormaybenot** [comment]
@rrousselGit 

> It appears to me that you want a family:

Yeah, the `family` docs itself are great - thanks for that ❤️ 

---

What I am missing is nesting (which is why I brought up scoping because I thought it would be a solution).
How do I deal with a case, where something **inside some other thing that is associated via ID** is _also associated **via ID**_. And 3 levels deep might not be realistic, but how do we go deeper?

Do we just add to our immutable (`equatable` / `freezed` / w/e) object:

```
IdObject
 - id
 - subId
 - subSubId
```

And access the families like that?

**Comment by rrousselGit** [comment]
> I am totally lost regarding how that would be managable at all using Riverpod.

I don't understand your problem tbh.

I'm sure a family would work, where each node of the tree has a unique ID.

**Comment by creativecreatorormaybenot** [comment]
> The only potentially boring part is the hashcode/== for complex parameters.

>But my experience is that this is very rare. And even then, you can use Freezed/equatable. And Dart will likely update to have better immutability support in the future

@rrousselGit I did not see your answer before posting - I guess we were thinking the same thing 😃

Yeah, I suppose I will just go with that. In that case, I feel like the docs are also (mostly) sufficient because one can come up with that easily given the information there.  
Just a side note: the concept is so intuitive that I even knew it was the way to go before reading the `family` docs 😂 (I mean I guess it is so obvious because of how comparing immutable objects works).

**Comment by rrousselGit** [comment]
Maybe your issue is with how you modeled your data.  
One of my recommendations would be to normalize your models.

For instance, instead of:

```dart
class Node {
  String id;
  List<Node> children;
}
```

I would suggest having:

```dart
class Node {
  String id;
  List<String> childrenIds;
}
```

That scales much better with `family` from my experience

**Comment by creativecreatorormaybenot** [comment]
@rrousselGit Actually, regarding the recursion problem, you just helped me switch up my mindset regarding the connection between `riverpod` and Flutter because I was probably stuck in the `InheritedWidget` mindset 😅

The model is actually:

```dart
class Node {
  String id;
  List<String> parentIds;
}
```

So yeah, so much about that 😂 (the provider will pull in the children; maybe you also implied that)

---

But anyway, here is what I mean with my wrong mindset:

The `package:provider` implementation simply did this:

```dart
  const NodeWidget({
    Key? key,
  }) : super(key: key);
```

So there are no parameters, I simply used `Provider`s to tell that node widget what it was supposed to do.

However, you are right - the recursion _can_ easily be handled using families and it even scales better because I now do not even need to ensure that I do no fetch data multiple times if a node appears multiple times (because the same provider handles it ✨).

So the switch up would be as simple as:

```dart
  const NodeWidget({
    Key? key,
    this.id,
  }) : super(key: key);

  final String id;
```

And then refer to a family with that ID.

**Comment by creativecreatorormaybenot** [comment]
If you ever took a look at [`stacked`](https://pub.dev/packages/stacked), that is what they got completely wrong IMO.

They did not understand what **you did understand**: how the widget tree works.  
In that package, nesting was actually impossible because I think they did not really understand how `package:provider` worked.

Anyway, regarding the Riverpod docs: it is your call what to include judging from these conversations.

---

I am sure you had a lot of these on GitHub, however, from my experience, solutions **in GitHub issues** are hilariously difficult to find - I just do not know any good way of searching for that 🤷

**Comment by creativecreatorormaybenot** [comment]
@rrousselGit 

+ another learning from this: it might be worth pointing out that when using Riverpod with Flutter, the **comfort** of the scoped nature of `package:provider` **will be lost** 😂 Not having to pass parameters is actually super addicting 🥴

**Comment by rrousselGit** [comment]
That's nice to hear!

This issue is a good example of why I separated provider and riverpod btw.

While I believe family/autoDispose are better solutions overall, as you've said yourself that's a different mindset

**Comment by e200** [comment]
Thank you @creativecreatorormaybenot and @rrousselGit, I learned a lot from this issue.

**Comment by larssn** [comment]
@rrousselGit 

So I've read the entire thread, but like the OP, I can't see how `family` is a good substitute for a scoped provider. The problem, as I see it, is that if your providers are heavily nested, once a non-family provider starts depending on a family provider, there's a good chance it too will become a family provider.

### Small repository example:

Lets say I have a Customer repository, and lets say that repository depends on a single variable, `organizationId`, in order to find the correct path to an organization's customers.

```dart
class CustomerRepository {
  const CustomerRepository(this.organizationId);

  final String /*!*/ organizationId;

  String get collection => 'organizations/$organizationId/customers';

  // ... remaining repo methods
}
```

A naive first implementation of a provider might look something like this:

```dart
final customerRepoProvider = Provider.autoDispose.family<CustomerRepository, String>((ref, organizationId) => CustomerRepository(ref.read, organizationId));
```

But this doesn't scale (as the OP suggested), as now any provider that were to depend on this provider would have to find an `organizationId` in order to use said provider, which might not even be possible for that provider, unless that provider were to be a family provider itself, and then deferring that responsibility to the consumer (annoying, boilerplatey and you're not solving the problem, you're simply moving it).

Now a second implementation might try to bypass this problem by introducing a provider that should provide the `organizationId`:

```dart
final customerRepoProvider = Provider<CustomerRepository>((ref) {
  final organizationId = ref.watch(organizationIdProvider);
  
  return CustomerRepository(organizationId);
});
```

But what if the user isn't logged in? Then there's no active organization, and thus no ID.
I guess we'd have to check for that:

```dart
final customerRepoProvider = Provider<CustomerRepository?>((ref) {
  final organizationId = ref.watch(organizationIdProvider);

  if (organizationId == null) return null;
  
  return CustomerRepository(organizationId);
});
```

But now we've changed the contract and the consumer might end up NOT getting the repository he's looking for.
You could call this a side effect to providers being global: they can be accessed by anyone from anywhere which can lead to unfortunate code like the above (providers being global has a very similar feel to `static` code, in many aspects).

This is something the old `provider` package handled better. Yes you could get ProviderNotFound exceptions, but you had the **safety** of **scope**.

I'm not sure how to solve the above, and I do not want to tell my devs to be careful of when they access providers in the global scope, because a provider might depend on a variables that isn't ready yet.

If you wan't to keep the contract, and not use a family provider, you'd have to do a compromise of the above, like so:

```dart
final customerRepoProvider = Provider<CustomerRepository>((ref) {
  final organizationId = ref.watch(organizationIdProvider)!; // <-- notice the bang operator
  
  return CustomerRepository(organizationId);
});
```

However this would obviously crash if you were to access that provider too early...

### Conclusion
After mulling over this for a few days, I'm very close to scrapping riverpod. 😭
It is so very close to perfection! But the choice to make providers global... I dunno man, it just doesn't feel right. It feels like I'm back to calling static methods, from potentially everywhere in the app, which is not a good programming practise IMO.

As I see it, it doesn't fix the ProviderNotFound exceptions exibited in the original provider package, it only **moves** that particular problem, which then bleeds into the consumers business logic, as demonstrated in the above contracts.

Thanks for reading
