### ISSUE TITLE
Shortcut to auto import context extension

### ISSUE THREAD

**Issue by ToniTornado** [rrousselGit/river_pod#233]
I stumbled across this article and wondered if this would be a temporary solution for Riverpod as well until Dart supports automatic imports for extensions?

https://felixblaschke.medium.com/auto-import-for-dart-extension-methods-e425170de225

(very short Medium article by the developer of supercharged)

**Comment by rrousselGit** [comment]
What exactly do you expect Riverpod to do for this?

You could type `Consumer` and the IDE would try to import `flutter_riverpod`, which comes with the `context` extensions.

**Comment by rrousselGit** [comment]
Closing this since there's nothing Riverpod can do
