### ISSUE TITLE
Clarity on how to use riverpod with "local" state

### ISSUE THREAD

**Issue by pstromberg98** [rrousselGit/river_pod#234]
Is it appropriate to use riverpod for "local" state management? 

And by local I mean a provider that is meant to be used exclusively by a sub section of the app or specific widget and is not accessible to the entire app. In other words, providers that manage state that shouldn't be accessible to every widget, but could otherwise be shared with relevant widgets. I modified the counter example to try to illustrate a simple example of my confusion.

```
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

// A Counter example implemented with riverpod

void main() {
  runApp(
    // Adding ProviderScope enables Riverpod for the entire project
    const ProviderScope(child: MyApp()),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: Home());
  }
}

/// Providers are declared globally and specifies how to create a state
final counterProvider = StateProvider((ref) => 0);

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Counter example')),
      body: Center(
        // Consumer is a widget that allows you reading providers.
        // You could also use the hook "useProvider" if you uses flutter_hooks
        child: Column(
          children: [
            Counter(),
            Counter(),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        // The read method is an utility to read a provider without listening to it
        onPressed: () {},
        child: const Icon(Icons.add),
      ),
    );
  }
}

class Counter extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: Column(
        children: [
          Consumer(builder: (context, watch, _) {
            final count = watch(counterProvider).state;
            return Text('$count');
          }),
          FloatingActionButton(
            // The read method is an utility to read a provider without listening to it
            onPressed: () => context.read(counterProvider).state++,
            child: const Icon(Icons.add),
          ),
        ],
      ),
    );
  }
}
```

Assuming that there are multiple widgets using the same provider (like `Counter`) and that it doesn't make sense to have them share state, the correct solution isn't apparent. Should you not use riverpod in this case? One solution is to move the counterProvider into the `Counter` as a private member, but the documentation is unclear if that is okay as it always shows provider declarations in the global scope. Is the solution to use `ScopedProvider`/`ProviderScope`? If so then the documentation for it are scarce and don't reference an issue like this.

I am new to riverpod so maybe the solution is apparent, I apologize if it is. Obviously this example is intentionally simple and there are more examples I could give if necessary but hopefully it conveys the general confusion.

**Comment by rrousselGit** [comment]
That is not a good idea, no.

You could run into issues where a state does not reset properly when the widget is destroyed. Or if you use that widget in multiple places, those different instances may not want to share state

Providers aren't made for local state

What are you trying to solve by doing that?

**Comment by pstromberg98** [comment]
> Providers aren’t made for local state

Yeah that’s all I needed to know. Like I said riverpod didn’t seem to fit in the scenario that I am painting but I was making sure of that.

The reason I asked was for two reasons. First, the way you can compose and combine providers is handy and could be useful in constructing local state behavior. Second, I got the feeling that riverpod was meant for global state but wasn’t ever explicitly mentioned in the docs. The reason I didn’t assume it was for global state only and just move on was because “state management” is such a broad term, especially in the Flutter community. Sometimes “state management” libraries are exclusively for local/emphermal state, some are for global, and some are even for both. Perhaps there is value in clarifying that that in the docs

**Comment by PiN73** [comment]
If you can distinguish local scopes by some key, maybe [family](https://riverpod.dev/docs/concepts/modifiers/family) can help?

**Comment by rrousselGit** [comment]
If you're looking for local composable state, [flutter_hooks](https://github.com/rrousselGit/flutter_hooks) is more fitting (but more advanced)
