### ISSUE TITLE
Unable to implement custom provider

### ISSUE THREAD

**Issue by scopendo** [rrousselGit/river_pod#236]
**Is your feature request related to a problem? Please describe.**

Mostly as an exercise to understand Riverpod internals better but also to reduce boilerplate, I have tried to create my own type of provider.  I may well be taking the wrong approach; however, at the moment I feel that I am blocked by Riverpod not exporting the abstract `ProviderStateBase` class.

I have a number of providers for accessing API service classes that all need to be passed in an HTTP client object.  The type of the HTTP object isn't important, just that they all need it.  All of the API service classes extend a common base API class.

```dart
final httpProvider = Provider<CustomHttpClient>(
  (ref) => CustomHttpClient(...),
);

final userApiProvider = Provider<UserApi>((ref) {
  final http = ref.watch(httpProvider);
  return UserApi(http);
});

final searchApiProvider = Provider<SearchApi>((ref) {
  final http = ref.watch(httpProvider);
  return SearchApi(http);
});

// And so on for each of the dozen or so API classes...
```

**Describe the solution you'd like**

I'd like to implement my own `ApiProvider` that reduces the boilerplate so that I can instead use the following syntax:

```dart
final httpProvider = Provider<CustomHttpClient>(
  (ref) => CustomHttpClient(...),
);

final userApiProvider = ApiProvider((ref, http) => UserApi(http));

final searchApiProvider = ApiProvider((ref, http) => SearchApi(http));
```

To do this, I tried to model `ApiProvider` on `Provider`, ignoring the `autoDispose` and `family` capabilities.

```dart
typedef CreateApi<API extends MyApi> = API Function(ProviderReference ref, CustomHttpClient http);

@sealed
class ApiProvider<API extends MyApi> extends AlwaysAliveProviderBase<API, API> {
  ApiProvider(CreateApi createApi) : super(_create(createApi), null);

  // Returns a provider-compatible [Create] function that internally watches the HTTP
  // client and then calls the passed-in function to create the API service object.
  static Create _create(CreateApi create) {
    return (ref) {
      final http = ref.watch(httpProvider).state;
      return create(ref, http);
    };
  }

  @override
  _ApiProviderState<API> createState() => _ApiProviderState();
}

@sealed
class _ApiProviderState<API> = ProviderStateBase<API, API> with _ApiProviderStateMixin<API>;

mixin _ApiProviderStateMixin<API> on ProviderStateBase<API, API> {
  @override
  void valueChanged({API previous}) {
    if (createdValue != exposedValue) {
      exposedValue = createdValue;
    }
  }
}
```

This approach doesn't seem to be possible as the `createState` method must return a `ProviderStateBase` but that class is not exported by Riverpod.

Is there any documentation for how to implement a custom provider type?  Apologies if I have missed this.

**Comment by iamarnas** [comment]
Maybe you looking for that? [own StateNotifier](https://github.com/rrousselGit/river_pod/issues/224#issuecomment-731584669)

**Comment by scopendo** [comment]
Thanks @iamarnas.  I don't think so – these classes don't encapsulate any state and so making them StateNotifier's feels, to me, to be the wrong approach.

I also don't see how that would let me avoid duplication of passing through the HTTP dependency unless the StateNotifier subclass were to pass the ProviderReference to the API superclass.

**Comment by scopendo** [comment]
Whilst I'm still curious about implementing a custom provider type, for this specific example, I've decided it's easier just to use a function as a pseudo-provider class.

```dart
Provider<API> ApiProvider<API extends MyApi>(API Function (CustomHttpClient http) create) {
  return Provider<API>((ref) {
    final http = ref.watch(httpProvider);
    return create(http);
  });
}
```

**Comment by rrousselGit** [comment]
As said on Discord, there is no official way to make custom providers at the moment.  
Mainly because I don't understand the problem yet. So I do not want to expose a half baked API, as changing it in the future is difficult

As you found yourself, in general, my recommendation would be to instead _compose_ providers, using functions

If you want to implement the entire spectrum of features (family/autoDispose), there's a bit more work. But you can do that using extension methods
