### ISSUE TITLE
Listening to a provider without a Widget

### ISSUE THREAD

**Issue by MarcinusX** [rrousselGit/river_pod#238]
I have a stream provider returning data from firestore.
```
final homeViewProvider = StreamProvider<HomeDataModel>((ref) => SomeStreamFromFirebase());
```
I'd like to call a service (let's say save user data) on every event from that provider.
I know I can do it inside the homeViewProvider but I don't think it should be a part of it.
I could listen the the provider in a widget and call the service, but then the logic would depend on the widget which doesn't really make sense as well.

Is there a way to listen to events from provider without any widget for it?

**Comment by rrousselGit** [comment]
You mean you want to listen to a provider from another provider?

**Comment by MarcinusX** [comment]
Yes, but I don't want to use that provider in any widget nor return anything important. I just want it to listen and do requests.

**Comment by rrousselGit** [comment]
As you looking for this? https://github.com/rrousselGit/river_pod/pull/168#issuecomment-739956629
This syntax isn't available yet, but may be what you want.

In the mean time, you could do something like:

```dart
final stateNotifierProvider = StateNotifierProvider<Notifier>(...);

final another = Provider((ref) {
  final notifier = ref.watch(stateNotifierProvider);

  ref.onDispose(
    notifier.addListener((state) => print('new state for notifier: $state'),
  );
});
```

**Comment by MarcinusX** [comment]
Not exactly , as this would still require me to use `another` somewhere in the app, right?
 Actually I almost managed to do it with ProviderObserver:
```
class WiredashObserver extends ProviderObserver {
  @override
  void didUpdateProvider(ProviderBase provider, Object newValue) {
    if (provider == homeViewProvider && newValue is AsyncValue<HomeDataModel>) {
      //TODO: Wish I had ProviderReference here
      final wiredashUtils = GetIt.I.get<IWiredashUtils>();
      //TODO: Add logic based on newValue
    }
  }
}
```
This I way I can do some logic on new event from `homeViewProvider`. The only thing I wish to have is ProviderReference in Observer methods.

**Comment by rrousselGit** [comment]
Why would you have nothing but a listener?

I don't understand thr use-case

**Comment by MarcinusX** [comment]
The exact code is this:
```
class WiredashObserver extends ProviderObserver {
  @override
  void didUpdateProvider(ProviderBase provider, Object newValue) {
    if (provider == homeViewProvider && newValue is AsyncValue<HomeDataModel>) {
      //Im not super happy with this implementation,
      //see https://github.com/rrousselGit/river_pod/issues/238
      final wiredashUtils = GetIt.I.get<IWiredashUtils>();
      newValue.maybeWhen(
        data: (data) => wiredashUtils.setUserData(
          userId: data.profileDataModel.id,
          email: data.profileDataModel.email,
        ),
        orElse: () => wiredashUtils.setUserData(
          userId: '',
          email: '',
        ),
      );
    }
  }
}
```

When I get data from `homeViewProvider` which is a `StreamProvider`, I want to set email and id in `Wiredash`.  
Other scenario could be setting those things in `Crashlyics`.

**Comment by rrousselGit** [comment]
Why isn't Wiredash in a provider? It could then use the code I gave above

**Comment by MarcinusX** [comment]
I've tried to use your example but if I understand correctly, without actually using the wiredashProvider anywhere in the code, it will never be initialized (which seems right).
```
final wiredashProvider = Provider<void>((ref) {
  print('initializingWiredashProvider'); //this is never called
  final homeView = ref.watch(homeViewProvider.stream);
  ref.onDispose(() {
    homeView.listen((event) {
      print(event); //neither is this
    });
  });
});
```

**Comment by rrousselGit** [comment]
Yes but why is that an issue?

**Comment by MarcinusX** [comment]
Because I do not want to listen to `wiredashProvider` anywhere, I just want to always make those calls to `WiredashUtils` when `homeViewProvider` emits new events. My understanding is that in order to make `wiredashProvider` work, I would need to add it somewhere in a widget tree, which I just don't like because it's not related to any widget. :D

**Comment by rrousselGit** [comment]
But you'll have your UI reading that object anyway right?

**Comment by MarcinusX** [comment]
Not really, I send it and never care about it.

**Comment by rrousselGit** [comment]
I don't understand

**Comment by MarcinusX** [comment]
1. I have a provider that I use for downloading some data.
2. Whenever I obtain the data, I want to make an action, but this action will never affect the UI (e.g. let's say I want to send to analytics "hey, this user successfully downloaded this data, take a note on that"). It won't affect the user in any way. And it's not strictly connected to any widget. It's just an extra side effect called on new data from provider that I don't want to put in neither provider emitting that action, nor any widget, as neither of them should know about its existence.

**Comment by rrousselGit** [comment]
To begin with, I don't understand why you would need to trigger an action after a FutureProvider completes.

Providers are meant to be declaratively combined.
This is very imperative-ish

**Comment by MarcinusX** [comment]
To be honest I'm not sure how I can describe it in other way 😅
If it's such non-typical scenario maybe let's just put that on hold until more common use case will occur.

**Comment by iamarnas** [comment]
@MarcinusX What's wrong with if you create a class which holds you functions and tell to `ProviderListener` to do something in the background?

**Comment by MarcinusX** [comment]
@iamarnas Can you give an example on that?
Basically I can say that my only "problem" is that if I created a `Provider` that is `ref.watching` for events from another `StreamProvider` and doing some actions, I need to use that provider somewhere in a widget tree even though it's not related  with any widget.

**Comment by iamarnas** [comment]
@MarcinusX Right now I'm not at home and have not my pc. But I will share you my example how I do actions when I listen to connections it's also based on Streams.

**Comment by iamarnas** [comment]
@MarcinusX  Hi,

Here's example with connectivity listener:

```dart 
final _connectivityProvider = StreamProvider<ConnectivityResult>((ref) {
  return Connectivity().onConnectivityChanged;
}, name: 'connectivity');

enum ConnectivityState { none, wifi, mobile, loading }

final connectivityProvider = Provider<ConnectivityState>((ref) {
  final connectivity = ref.watch(_connectivityProvider).data?.value;

  final results = <ConnectivityResult, ConnectivityState>{
    ConnectivityResult.none: ConnectivityState.none,
    ConnectivityResult.wifi: ConnectivityState.wifi,
    ConnectivityResult.mobile: ConnectivityState.mobile,
  };

  return results[connectivity] ?? ConnectivityState.loading;
});
```
Then you can create your own widget which observes your providers.

```dart
class ConnectivityStateObserver extends StatelessWidget {
  const ConnectivityStateObserver({this.child});

  final Widget child;

  @override
  Widget build(BuildContext context) {
    return ProviderListener<ConnectivityState>(
      provider: connectivityProvider,
      onChange: (context, value) {
        if (value == ConnectivityState.none) {
          // You can add how many providers you want.
          context.read(someProvider).saveState();
        } else if (value == ConnectivityState.wifi) {
          context.read(someProvider).uploadWifiOnly();
        } else if (value != ConnectivityState.none) {
          // Refresh some provider to check state and do something.
          context.refresh(someProvider);
        }
      },
      child: child,
    );
  }
}
```
then put it on the top, you can decide where you want dispose it and start you service.

```dart
// Your widget tree...
return MaterialApp(
        child: AppStateObserver(
          child: HomePage(),
//....
```
Multiple providers not supported yet with `ProviderListener` but you can do like this.

```dart
class AppStateObserver extends StatelessWidget {
  const AppStateObserver({this.child});

  final Widget child;

  @override
  Widget build(BuildContext context) {
    return ProviderListener<ConnectivityState>(
      provider: connectivityProvider,
      onChange: (context, value) {
        // Do something with connection.
      },
      child: ProviderListener<LifecycleState>(
        provider: lifecycleProvider.state,
        onChange: (context, value) {
          // Do something with lifecycle.
        },
        child: child,
      ),
    );
  }
}
```
Here are simple examples and easiest way to do actions on state changed. But if you want more advanced you can create your own `StateNotifier` which keep you State class. Then you can tell more to `ProviderListener` what to do everywhere from your app `context.read(stateNotifier);`. 
 This way is better that you have more control for you providers lifecycle and you decide where and when they will start service and dispose. I hope you understand what I mean.

**Comment by MarcinusX** [comment]
What I meant was to not be forced to add it into the widget (in your case `AppStateObserver` but I guess there's no avoiding it then.

**Comment by iamarnas** [comment]
@MarcinusX I understand that you want without context. But I explained why is better with context and it's just one line more in your widgets tree.

**Comment by isanimu** [comment]
Isn't that doable using ProviderContainer?

```dart
final container = ProviderContainer();
final provider = container.read(homeViewProvider);
provider.addListener((state) {
  print(state);
});
```

**Comment by venkatd** [comment]
@MarcinusX it could be thought of that your deps are actually needed by your root widget, the app. If you close your app, you would want these deps to be cleaned up right?

In our app, we've got certain logic like connectivity and so on that's an app-level dependency. Even though they don't show up in the UI, you are still declaring a dependency between your application and these app-level dependencies.

**Comment by MarcinusX** [comment]
>So to summarize "provider without any widget for it" actually means "provider for the app level widget".

Wow, you're right. Thinking this way, it totally makes sense. :D  
I guess that satisfies me enough to close the issue. :)

**Comment by rrousselGit** [comment]
Be careful with listening to things in your main.

Consider using `ProviderListener` instead of `addListener`:

```dart

final provider = WhateverProvider(...);

void main() {
  runApp(
    ProviderScope(
      child: ProviderListener<Value>(
        provider: provider,
        onChange: (context, value) {}
      ),
    ),
  );
}
```

Because with `addListener` you have to bear in mind that the object could be destroyed and recreated

**Comment by iamarnas** [comment]
And in the end, I was right 😄.  Your Flutter app is based on the widget tree and everything goes over the trunk (context). Simple rules...
