### ISSUE TITLE
FutureStateNotifierProvider

### ISSUE THREAD

**Issue by matejdro** [rrousselGit/river_pod#240]
**Is your feature request related to a problem? Please describe.**

I want to create a StateNotifier that keeps mutable state (similar to the [TodoProvider](https://pub.dev/documentation/riverpod/latest/all/StateNotifierProvider-class.html) from docs), but I want to initialize that state with asynchronous method.

**Describe the solution you'd like**

So essentially I want a combination of FutureProvider and StateNotifierProvider - FutureStateNotifierProvider. A StateNotifierProvider that accepts async lambda for creator.

**Describe alternatives you've considered**

1. Just use empty state and load data in the background

This can work in most cases, but in my case I want that provider to be usable from regular widgets as well as from imperative code where I'm not watching it, but I only want the read value (e.g I want to be able to type in something like `container.read(todosProvider.state)` and get actual state, not a placeholder value.). 

2. Use null as initial state and then wait in your imperative code for value to be non-null

This works but it brings on additional hassle of having to deal with null values. Ideally, everything should be non-nullable.

Example use case for this would be todo list app where todos are loaded from disk asynchronously. But additionally, sync with server is performed in another isolate where data is loaded from the provider and then sent to the server imperatively.

**Comment by iamarnas** [comment]
@matejdro Combination of FutureProvider and StateNotifierProvider is equal to 
```dart
class UserNotifier extends StateNotifier<AsyncValue<User>>{
   UserNotifier() : super(const AsyncValue.loading) ;
   //.... 
}
```

**Comment by funwithflutter** [comment]
What @iamarnas said works great! I actually recored a tutorial video on this today that I'll upload to YouTube soon. Will post the link here.

**Comment by rrousselGit** [comment]
Indeed the solution is as @iamarnas said

This is better because that means that inside onClicks you don't have to deal with `UserNotifier` being asynchronously created.

**Comment by matejdro** [comment]
Thanks to you both. This solution works great!

**Comment by scopendo** [comment]
@rrousselGit – it might be worth updating the Todos example to show how the TodoList example would work with async data.

**Comment by scopendo** [comment]
Actually, the video by @funwithflutter is helpful for this: https://www.youtube.com/watch?v=2vcjEuIkU0g
