### ISSUE TITLE
[RFC] Change on the syntax for listening providers

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/river_pod#246]
Hello!  
This issue is an open discussion for a potential change on how to consume/combine providers.

The goal of these changes are:
- offer a uniformized way to listen to providers (no-longer have `ref.watch` vs `useProvider` vs `watch`)
- add an equivalent to `ProviderListener` that works inside providers too
- revamp `ProviderListener` not to involve nesting
- support a `ConsumerStatefulWidget`
- support `useProvider(myProvider.select((user) => user.name))` in all the places that may want to listen to a provider

## The problem

At the moment, there are many similar but slightly different syntax for listening to a provider:

- providers wanting to listen to another provider may use `ref.watch(myProvider)`:
  ```dart
  final provider = Provider((ref) {
    final value = ref.watch(anotherProvider);
  });
  ```
- `HookWidget` may use `useProvider(myProvider)`:
  ```dart
  class Example extends HookWidget {
    @override
    Widget build(BuildContext context) {
      final value = useProvider(anotherProvider);

    }
  }
  ```
- `ConsumerWidget` & `Consumer` may use `watch(myProvider)`:
  ```dart
  class Example extends ConsumerWidget {
    @override
    Widget build(BuildContext context, ScopedReader watch) {
      final value = watch(anotherProvider);
    }
  }
  ...
  Consumer(
    builder: (context, watch, child) {
      final value = watch(anotherProvider);
    }
  )
  ```
- all widgets can use `ProviderListener` but not providers
    ```dart
  class Example extends StatelessWidget {
    @override
    Widget build(BuildContext context) {
      return ProviderListener<Something>(
        provider: anotherProvider,
        onChange: (context, value) {}
      );
    }
  }
  ```

This works fine but is slightly confusing. While in practice, there's only one solution on how to listen to a provider depending on where you are, the fact that the syntax isn't the same everywhere confuses newcomers.

On top of that, due to how `ConsumerWidget`/`Consumer` works, it is inconvenient to add new ways to listen to providers (such as a simplification of `ProviderListener` that does not involve nesting) because that would require adding parameters to the `build` method.

This also means that it is impossible to listen to providers inside `StatefulWidget,` as it is impossible to add extra parameters to `State.build`. This requires developers to use `Consumer`, which decreases readability.

## Proposal

This proposal is about fusing all of these methods for listening providers into two static functions:

- `watch`, the equivalent of `ref.watch`/`useProvider`/...
- `listen`, the equivalent of `ProviderListener`

These two functions would work in all providers and inside `ConsumerWidget`, `Consumer`, and two new additions:
- `ConsumerHookWidget`
- `ConsumerStatefulWidget`

Long story short, here is how both functions would look like in practice:

```dart
final a = Provider<A>(...);

final b = Provider((ref) {
  A value = watch(a);
  listen<A>(a, (value) {
  });
});

Consumer(
  builder: (context) {
    A value = watch(a);
    listen<A>(a, (value) {
    });
  },
);

class StatelessExample extends ConsumerWidget {
  @override
  Widget build(BuildContext context) {
    A value = watch(a);
    listen<A>(a, (value) {
    });

  }
}

class HooksExample extends ConsumerHookWidget {
  @override
  Widget build(BuildContext context) {
    A value = watch(a);
    listen<A>(a, (value) {
    });

  }
}

class StatefulExample extends ConsumerStatefulWidget {
   @override
  _StatefulExampleState createState() => _StatefulExampleState();
}

class _StatefulExampleState extends State<StatefulExample> {
  @override
  Widget build(BuildContext context) {
    A value = watch(a);
    listen<A>(a, (value) {
    });

  }
}
```

____

This change would involve:
- deprecating `useProvider` in favor of `ConsumerHookWidget` + `watch`
- deprecating `ProviderListener` in favor of `listen`
- deprecating `ref.watch` in favor of `watch`
- removing the extra parameter of `ConsumerWidget.build`

This change would have no impact on `<ref/context>.read`

## The downside

The main issue with this change is, we lose some of the "compilation safety". 

More specifically, there are two cases that currently purposefully do not compile but would now compile (and throw) after this change:

- reading a `ScopedProvider` inside a non-scoped provider:
  ```dart
  final scoped = ScopedProvider(...)

  final provider = Provider((ref) {
    watch(scoped);
  });
  ```

- reading an `.autoDispose` provider inside a provider that is not marked with `.autoDispose`:
  ```dart
  final autoDispose = Provider.autoDispose(...)

  final provider = Provider((ref) {
    watch(autoDispose);
  });
  ```
Since these would now throw exceptions instead of compilation errors, this would make refactoring more difficult.

The bright side is, there is an alternate solution for these: custom lint rules.
Instead of relying on the Dart compiler to have a compilation error, we could extend the Dart analyzer to add support for these scenarios.

This is a separate project on its own but is feasible. 

## Closing word

That's it~

What do you think of the proposed change, and what do you think about the downsides?

Feel free to comment or vote on this issue to express your opinion:

- vote 🚀  if you want this change even without the analyzer plugin (the analyzer plugin would still come but after the release of such change)
- vote 🎉 if you want this change, but only if we have the analyzer plugin (this would lock the release of such change until the analyzer plugin is ready)
- for 👎  if you don't want this change at all
- leave a comment for any other opinion

**Comment by gaetschwartz** [comment]
I overall like the proposal but I have a few concerns.

1. Would `Consumer` actually lose their `child` attribute as indicated here 
![image](https://user-images.githubusercontent.com/25441359/102007445-702ec980-3d29-11eb-86eb-d7e40da6691c.png)
or is it just a typo?

2. Although I like the syntax, I feel like in the case of Providers, `ref.watch` is actually clearer as it clearly indicates that it is the reference that is watching and will thus rebuild the provider whereas `watch` is a little obscure as to what actually watches `a` (in the example).

**Comment by softronaut** [comment]
I don't agree with these changes mostly.

`listen` inside pods is unneeded imo. Because it's usage heavily related with context where navigation or showing snackbar-dialog etc. needed, which is not a normal case inside a pod. And nesting for `ProviderListener` is very okay because the functionality you get is totally worth.

I'm not sure about `watch` but I can easily say it makes `ProviderReference`s irrelevant from developer side, imagine having two different scope(I know it's unlikely but possible), `watch` function may confuse in that scenario.
Also I'm not fan of occupying generic names at top level namespace.
I can't say much about changes related to `hook` because I don't use it.

I think you are trying to over-simplify the riverpod. It's already pretty easy and versatile way to manage state, imo it's best so far. Yes, it may be hard to empathize with newcomers but what I like about you packages, you use everything in their proper place without breaking patterns, riverpod shouldn't go in that way.

**Comment by rrousselGit** [comment]
> Would Consumer actually lose their child attribute as indicated here or is it just a typo

Just a typo

**Comment by rrousselGit** [comment]
> listen inside pods is unneeded imo

It has been requested numerous times

The use-case is to perform an action on `StateNotifier`/`ChangeNotifier` when another provider updates, without destroying the provider state:

```dart
final provider = StateNotifierProvider((ref) {
  final notifier = MyNotifier();

  listen<Something>(anotherProvider, (value) {
    notifier.doSomething();
  });

  return notifier;
});
```

>  And nesting for ProviderListener is very okay because the functionality you get is totally worth.

**Comment by rrousselGit** [comment]
> listen inside pods is unneeded imo

It has been requested numerous times

The use-case is to perform an action on `StateNotifier`/`ChangeNotifier` when another provider updates, without destroying the provider state:

```dart
final provider = StateNotifierProvider((ref) {
  final notifier = MyNotifier();

  listen<Something>(anotherProvider, (value) {
    notifier.doSomething();
  });

  return notifier;
});
```

>  And nesting for ProviderListener is very okay because the functionality you get is totally worth.

If we can do the same without nested, why not?

> I'm not sure about watch but I can easily say it makes ProviderReferences irrelevant from developer side, imagine having two different scope(I know it's unlikely but possible), watch function may confuse in that scenario.

Do you have an example?

> Yes, it may be hard to empathize with newcomers but what I like about you packages, you use everything in their proper place without breaking patterns, riverpod shouldn't go in the other way.

What pattern would this break?

**Comment by gaetschwartz** [comment]
> It has been requested numerous times

I agree with @rrousselGit here, I needed that feature a few days ago and still do.

**Comment by iamarnas** [comment]
I personally like as is 😊

**Comment by gaetschwartz** [comment]
Another question, would we still be able to do something like this ? 

```dart
final a = Provider<A>(...);
final b = Provider((ref) {
  return MyClass(ref);
});
class MyClass {
  final ProviderReference ref;
  MyClass(this.ref) {
    final val = ref.watch(a);
    // Logic here
  }
}
```

**Comment by rrousselGit** [comment]
> Another question, would we still be able to do something like this?

No. That's a bad practice to begin with.
Even without this change, a linter would warn you to not do that

It decreases the readability of providers quite a bit. It's harder to see what can cause the provider to "rebuild"

**Comment by gaetschwartz** [comment]
Alright that's true, I agree. The new `watch` would then actually be better I do agree. Thought for a moment `ref.read` would be impacted but no. Sunday mornings 😅

LGTM then 👍🏼

**Comment by lohanidamodar** [comment]
> 2. Although I like the syntax, I feel like in the case of Providers, `ref.watch` is actually clearer as it clearly indicates that it is the reference that is watching and will thus rebuild the provider whereas `watch` is a little obscure as to what actually watches `a` (in the example).
> 

I agree with this. I believe it's better than having a top level watch which might be confusing as well.

**Comment by MarcinusX** [comment]
> The use-case is to perform an action on `StateNotifier`/`ChangeNotifier` when another provider updates, without destroying the provider state:
> 
> ```dart
> final provider = StateNotifierProvider((ref) {
>   final notifier = MyNotifier();
> 
>   listen<Something>(anotherProvider, (value) {
>     notifier.doSomething();
>   });
> 
>   return notifier;
> });
> ```

Is it possible right now? If so, how?

**Comment by rrousselGit** [comment]
> Is it possible right now? If so, how?

It's not~
That would be a new feature.

Your best bet, for now, is to use `ChangeNotifier.addListener` / `Stream.listen` combined with `ref.onDispose`, and potentially a create a separate `Provider` to filter rebuilds

**Comment by softronaut** [comment]
> Do you have an example?
After my comment, I thought more about this, it's actually confused me a little. What I was considering, say we have a game/app inside your application but as I thought more about this, actually there is no problem.

> What pattern would this break?
Top level functions without context(I mean the general meaning of the context as used in many prog lang, not only `BuildContext` or `ProviderReference`), that's an anti-pattern, but clearly there is a benefit here by using just `watch` and `ProviderReference` is still relevant in that case, which makes everything optional.

As long as I think about the proposal, it makes sense but meantime I'm confused, okay I'm neutral now 😄

**Comment by rrousselGit** [comment]
> Top level functions without context that's an anti-pattern

It's not really without a context.
You can think of it more as Kotlin's "this" parameter, where instead of:

```dart
Class((this) {
  this.doSomething();
});
```

you just do:

```dart
Class(() {
 doSomething();
});
```

The only difference is that it relies on a workaround to work

**Comment by gaetschwartz** [comment]
Out of curiosity what would that workaround be ?

I feel like even though the code would be more concise it might be less clear to newcomers what the effect of watch would be and why it would (/not) work in different cases. The fact that this method becomes accessible _everywhere_ but actually doesn't work _everywhere_ might be confusing. 
A well written doc would be needed but I know for a fact that yours docs are always really well written so I'm not really worried 😊

**Comment by rrousselGit** [comment]
This would rely on Zone parameters

**Comment by scopendo** [comment]
I wouldn't like to see useProvider deprecated as it would prevent hook composition. I prefer to have consistency of code within a build method.

```dart
final tabController = useTabController(...);
final brand = useBrand();

...

BrandData useBrand() => useProvider(brandProvider);
```

**Comment by rrousselGit** [comment]
> I wouldn't like to see useProvider deprecated as it would prevent hook composition

`watch` would work inside hooks too

**Comment by creativecreatorormaybenot** [comment]
How are you planning to implement this change? Set the provider context before calling the callbacks?

I feel like this might be a dangerous move, but I have not thought about it enough yet 🤔 

---

Also, I would not want the change just for the sake of changing or just because some function names do not look nice. If there is any comprimise connected to it, it does not feel worth it because we lose quality just for having more consistent function naming.

**Comment by woelmer** [comment]
**Things I like**
1. With an AsyncValue I may want to build a widget for loading and error states but trigger a navigation event when data comes in. In that case I would have to have a ProviderListener in one place in the build tree and the Consumer or useProvider in another. I like that this syntax will put this code a little closer together instead of spread across the build tree.
2. I like that this eliminates the nesting of the ProviderListener
3. This will help with adoption for new people. Consistency of syntax is an improvement. 
**Thing I don't like**
1. I make the mistake of mixing auto dispose providers with others all the time. It is nice that the compiler helps find those issues. The linter improvement would help, but is not a perfect solution.

**Comment by rrousselGit** [comment]
> I make the mistake of mixing auto dispose providers with others all the time. It is nice that the compiler helps find those issues. The linter improvement would help, but is not a perfect solution.

Why isn't the linter a perfect solution?

It would likely be more helpful than the compiler, because instead of a weird error message like "Cannot assign RootProvider to AutoDisposeProvider" we'd get a proper error message akin to "Cannot listen to a provider marked with `autoDispose` in a provider not marked with `autoDispose`"

**Comment by rrousselGit** [comment]
> How are you planning to implement this change? Set the provider context before calling the callbacks? (zone parameters would be one way, e.g. Zone.current[#_providerContext])

Yes this would be using the Zone. We can't just use a static variable because of `FutureProvider`/`StreamProvider` that may call "watch" after some delay.

The Zone fixes that

**Comment by creativecreatorormaybenot** [comment]
Feels like a hack all in all 🤔

**Comment by woelmer** [comment]
> > I make the mistake of mixing auto dispose providers with others all the time. It is nice that the compiler helps find those issues. The linter improvement would help, but is not a perfect solution.
> 
> Why isn't the linter a perfect solution?
> 
> It would likely be more helpful than the compiler, because instead of a weird error message like "Cannot assign RootProvider to AutoDisposeProvider" we'd get a proper error message akin to "Cannot listen to a provider marked with `autoDispose` in a provider not marked with `autoDispose`"

Not everyone on my team checks the linter for warnings and errors unfortunately which is why it is not ideal. I know there are things I can do to force compile errors when the linter has an error, but I haven't set that up yet.

**Comment by kranfix** [comment]
I like the Idea of ConsumerHookWidget

**Comment by smiLLe** [comment]
> Unfortunately, not everyone checks the linter for warnings and errors which is why it is not ideal. I know there are things I can do to force compile errors when the linter has an error, but I haven't set that up yet.

I totally agree. I think the majority of developers, especially new flutter developers don't care that much about warnings.
For me, riverpod is compile safe and it should stay that way.

**Comment by davidmartos96** [comment]
@smiLLe But people should be aware of warnings nonetheless. They exists for a reason.
In any case warnings can be turned into an error. Like the required parameter lint.

**Comment by scopendo** [comment]
Putting aside `ProviderListener` the main syntax difference appears to be between the `watch` and `useProvider` functions.  Might it be that introducing `ConsumerHookWidget` and removing `useProvider` is enough, either with `watch` being a method of `ConsumerWidget`/`ConsumerHookWidget` or an additional param passed to the build method?

Following on, I'm not sure that I appreciate the necessity for passing `ref` to provider "create" functions, as opposed to just passing the `watch` function, so that we instead write:

```dart
final httpProvider = Provider((_) => HttpClient());

final apiProvider = Provider<ApiService>((watch) {
  final http = watch(httpProvider);
  return ApiService(http);
});
```

I seem to recall in earlier days using `ref.read` but believe that guidance became to always use `ref.watch`.  I _think_ I recall seeing a comment recently that passing `ref` through to say a `StateNotifier` is frowned upon, preferring now to watch the provider values in the create function and pass them through to the notifier's constructor.  If that is true, then I'm not sure what need there is for passing in `ref` over `watch`.

**Comment by ldasilva-net** [comment]
I think using Lint is a must for any development... If the documentation makes it clear which Lint rules to use I don't see any problem, it would even be an improvement for the error message as Remi says.

Two things:
1) Would the "ref" param still make sense? 

2) I think that we should also add "read" as static function.

**Comment by rrousselGit** [comment]
> Following on, I'm not sure that I appreciate the necessity for passing ref to provider "create" functions, as opposed to just passing the watch function, so that we instead write:

`ref` is necessary for things like `onDispose`,  `read`, `maintainState` and more. It's also a placeholder for adding features without requiring a breaking change.  
For example there's an issue about having providers receive their previous value. This would likely be done with a `ref.previousValue`

We could also add a `listen` through `ref`:

```dart
final provider = Provider((ref) {
  ref.listen<A>(anotherProvider, (value) {

  });
});
```

`read` is no less useful after this change. The discussion you found is referring to bad practices that the linter would highlight

**Comment by rrousselGit** [comment]
An alternate solution to this issue could be to update `ConsumerWidget` and `HookWidget` to receive a pseudo `ref`:


```dart
class Example extends ConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetReference ref) {
    final value = ref.watch(provider.state);

    return RaisedButton(
      onPressed: () => ref.read(provider).increment();
    );
  }
}
```

The downside is:
- this is more verbose
- this doesn't allow a `ConsumerStatefulWidget` (unless we can somehow to it with a mixin on `State`?)

**Comment by rrousselGit** [comment]
>  I think that we should also add "read" as static function.

This is sadly not feasible for `read`.

**Comment by scopendo** [comment]
> ref is necessary for things like onDispose, read, maintainState and more. It's also a placeholder for adding features without requiring a breaking change.

👍 

> An alternate solution to this issue could be to update ConsumerWidget and HookWidget to receive a pseudo ref:

I think I'd probably prefer to just use the watch function as-is, combined with a ConsumerHookWidget.  I could live without `useProvider` and apply `watch` everywhere.

Is there a strong need for `ConsumerStatefulWidget` that isn't addressed by `ConsumerHookWidget` or by adding a `Consumer` to the stateful widget's sub-tree?

As an aside, if one were to introduce a static `watch` method then we could nicely add extension methods to have `myProvider.watch()` and `myProvider.read(context)`, which does feel a bit more natural and hides the static method implementation detail.

**Comment by rrousselGit** [comment]
> As an aside, if one were to introduce a static watch method then we could nicely add extension methods to have myProvider.watch() and myProvider.read(context), which does feel a bit more natural and hides the static method implementation detail.

That is not possible, because `read` is based on a different object depending on where we are.
Inside providers we do `ref.read`, and inside widgets we do `context.read`. 

The objects being different means that we can't have a single `provider.read`.

**Comment by rrousselGit** [comment]
> Is there a strong need for ConsumerStatefulWidget that isn't addressed by ConsumerHookWidget or by adding a Consumer to the stateful widget's sub-tree?

No. The goal is to not require the dependency on hooks, nor require an unnecessary Consumer inside StatefulWidgets

**Comment by scopendo** [comment]
> That is not possible, because read is based on a different object depending on where we are. Inside providers we do ref.read, and inside widgets we do context.read.

Yeah, I was assuming context.read, which for me at least tends to be the primary use of read.

**Comment by rrousselGit** [comment]
Yet another solution would be to subclass BuildContext to make it implement a common interface with `ref`

That would allow `myProvider.read(context)` vs `myProvider.read(ref)`

**Comment by TimWhiting** [comment]
My opinion: 

It seems like this proposal is actually two things:
- A proposed syntax change unifying `ref.watch`, `useProvider` from hooks and `watch` from ConsumerWidget.
- A proposal for new features:
  - add an equivalent to ProviderListener that works inside providers too
  - revamp ProviderListener not to involve nesting
  - support a ConsumerStatefulWidget
  - support useProvider(myProvider.select((user) => user.name)) in all the places that may want to listen to a provider
  - support ConsumerHookWidget
 
I think most developers are in support of all the new features
The most conflict is around the syntax change for watching

I agree that a unified syntax for watching is nice, but that it doesn't feel right given that there wouldn't be a uniform way to read a provider, to me it makes sense for the watch to be coming from the ref. A `watch` parameter in the build of ConsumerHookWidget would make the `useProvider` mostly obsolete except for composing hooks, which would unify much of the syntax. (Only having `watch` / `ref.watch`). And if you did like you mentioned and give something like a ref to the ConsumerWidgets then you would unify it by only having `ref.watch`.

My questions are: 
Can we have the new features without the new syntax, or is it not feasible? 
What features would not be feasible without the new syntax?

**Comment by rrousselGit** [comment]
> Can we have the new features without the new syntax, or is it not feasible?
Which features would not be feasible without the new syntax?

We can likely have those features in one way or another

As I mentioned before, it is entirely feasible to add a `ref` parameter to `ConsumerWidget.build`  (and somehow use mixins for StatefulWidgets)

We could then have:

```dart
Widget build(BuildContext context, WidgetsReference ref) {
  ref.watch(myprovider);
  ref.read(myprovider);
  ref.listen<A>(myprovider, (value) {});
}
```

This could be a solution. My worry would be:
"Do people care about `listen` enough so that it is worth to have `ref.watch` instead of `watch`?"

**Comment by scopendo** [comment]
Is it strictly necessary to pass `watch` or `ref` through to the Consumer*Widget build method?  Could it not be a method of the widget?  That way the developer decides whether to use `watch` or `ref`.

**Comment by rrousselGit** [comment]
Widgets are immutable

A method on a widget cannot do anything

**Comment by ldasilva-net** [comment]
I really like this approach of `ref` as `ConsumerWidget` build parameter. Its a very nice solution. But in this approach how we use Hooks? Some `useProviderRef`?
I dont know if people use a lot of listens but with this we have all functionallity accesible and it's clear from where `watch` function comes.

**Comment by TimWhiting** [comment]
> This could be a solution. My worry would be:
> "Do people care about `listen` enough so that it is worth to have `ref.watch` instead of `watch`?"

I think changing `watch` to `ref.watch` is a much preferred change than making watch global. And it still accomplishes unifying the syntax to avoid confusion for beginners.

Personally my vote on order of features would be:
1. Change the watch parameter to a ref, or subclass `BuildContext` as `ProviderBuildContext` and only have the `ProviderBuildContext` parameter. (i.e. `Widget build(BuildContext context, WidgetsReference ref);` or `Widget build(ProviderBuildContext context);`)
2. Create the `ConsumerStatefulWidget` and `ConsumerHookWidget`
3. Add `listen` functionality
4. Update the `.select` functionality to work in all contexts
5. Update `ProviderListener` to not involve nesting
6. Add linter for enforcing best practices

After the new features, ask the community again if they would like the watch to be global. (I don't necessarily like this idea). If the goal is to unify the syntax then `ref.watch` seems like the best option to me, especially since it mirrors the `ref.read` and `ref.listen` syntax.

**Comment by TimWhiting** [comment]
> But in this approach how we use Hooks? Some `useProviderRef`?
@ldasilva-net 
That is why we would have a ConsumerHookWidget. But I think hook functions for the same purpose could be made accessible like you suggested.

**Comment by woelmer** [comment]
> This could be a solution. My worry would be:
> "Do people care about `listen` enough so that it is worth to have `ref.watch` instead of `watch`?"

Would using ref in this way still have the two downsides of compilation safety? If so, I don't care enough to have `ref.watch` instead of `watch`.

**Comment by TimWhiting** [comment]
> Would using ref in this way still have the two downsides of compilation safety? If so, I don't care enough to have `ref.watch` instead of `watch`.

No, as I understand it `ref.watch` would be essentially the same as `watch` is currently in a ConsumerWidget. i.e. No downsides of the proposal at the top of this issue, except adding the `ref.`.

**Comment by rrousselGit** [comment]
Indeed, `ref.watch` would be compile safe.

The downside is, we wouldn't have a `ConsumerStatefulWidget`

**Comment by TimWhiting** [comment]
> An alternate solution to this issue could be to update `ConsumerWidget` and `HookWidget` to receive a pseudo `ref`:
> The downside is:
> 
> * this is more verbose
> * this doesn't allow a `ConsumerStatefulWidget` (unless we can somehow to it with a mixin on `State`?)

@rrousselGit 
In your previous comment you mentioned that there might be a way to do it with a mixin on `State`? Or is the `ConsumerStatefulWidget` not at all possible with this approach? As @scopendo mentioned most developers can workaround not having a `ConsumerStatefulWidget` by using `Consumer` in their build method, or separating out that part into a separate widget.

**Comment by woelmer** [comment]
I would type `ref.` all.... day..... long..... if it means we could get type safety back. As to the loss of `ConsumerStatefulWidget` I don't personally need it because I use flutter hooks. I realize others need it, so if there was a way to accomplish it with a mixin that would be a win win.

**Comment by vo9312** [comment]
This is interesting
@rrousselGit when will this change be applied to river_pod?

**Comment by rrousselGit** [comment]
It'll take a bit of time. I need to make another RFC with one of the suggested alternative. It wouldn't be fair to not evaluable all possibilities, especially considering the opinions on this one are mixed.

**Comment by erf** [comment]
Maybe slight of topic, but when `watch` a provider, the returned value is depended on which type of provider we are watching, and i was wondering if it would make sense to make a more uniform API for getting a value from `watch`?

E.g. for `Provider` we get the value (Object) directly, for `StateProvider` we have to access it through the `.state` getter, for `FutureProvider` or `StreamProvider` we receive an `AsyncValue` object.

I understand the point of `AsyncValue` as means to listen for various state changes, i just wonder if this API could become more uniform in some way..

I noticed this when i was trying to [combine](https://github.com/erf/combined_provider), a set of providers using a provider and get the result back as values. I had to check for various provider types to get the correct value back.

I'm not really sure how such a solution would look like, and maybe being specific here makes more sense, but making a API more uniform is always nice, and one could perhaps simplify the code in some cases. 

The problem now i guess is `ChangeNotifier` which doesn't have a standard way to get a state, but perhaps `Riverpod` could consider to drop support for it..?

BTW perhaps, you could add an optional `state` parameter to the `watch` method, to only trigger when E.g. data is ready for AsyncData?

**Comment by neiljaywarner** [comment]
I'm just coming to riverpod and really architecture besides built in state. i agree that it's a bit confusing to have so many different ways but it feels like the cons of switching outweight the pros

The hooks example seems so nice and to have it consistent with the rest of hooks seems like an asset.  

Plus it feels like we are *adding* boilerplate/complexity in the hooks example... even if only a very little.

**Comment by erf** [comment]
Regarding the main RFC issue:

Having `ref.watch` makes sense to me if we can maintain compile safety. 

I'm all for keeping it minimal, so i would drop all `Widgets` except `Consumer` widget.

You could then summarize the use cases to:

```dart
final a = Provider<A>(...);

final b = Provider((ref) {
  A value = ref.watch(a);
  ref.listen<A>(a, (value) {
  });
});

Consumer(
  builder: (context, ref, child) {
    A value = ref.watch(a);
    ref.listen<A>(a, (value) {
    });
  },
);
```

**Comment by rrousselGit** [comment]
Closing this as I won't proceed forward with _this_ variant.

The opinions are fairly biased, and a good alternative has been proposed.

**Comment by rrousselGit** [comment]
I've opened a new RFC with the alternate syntax proposed https://github.com/rrousselGit/river_pod/issues/335
