### ISSUE TITLE
ref.watch doesn't work if initialized by context.read?

### ISSUE THREAD

**Issue by negitorogithub** [rrousselGit/river_pod#247]
I have a question about ref.watch.

**Describe the bug**
When I use ref.watch to StateNotifier, it seems not working if initialized by context.read.

**To Reproduce**

Here's brief code
```
class CounterStateController extends StateNotifier<CounterState> {
  CounterStateController() : super(CounterState());

  void inc() {
    state = state.copyWith.call(count: state.count + 1);
  }
}
```

```
final counterStateControllerProvider = StateNotifierProvider((ref) => CounterStateController());

StateNotifierProvider bazStateControllerProvider = StateNotifierProvider((ref) {
  print('watch in bazStateControllerProvider: ${ref.watch(counterStateControllerProvider.state)}');
  return BazStateController(ref: ref);
});

Provider barProvider = Provider((ref) {
  print('watch in barProvider: ${ref.watch(counterStateControllerProvider.state)}');
});
```

```
class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // initialize
    context.read(bazStateControllerProvider);
    context.read(barProvider);
    context.read(counterStateControllerProvider);
...
```

and here's [repo](https://github.com/negitorogithub/riverpod_testing).

**Expected behavior**
barProvider and bazStateControllerProvider listen counterStateControllerProvider.state inside create function.Then, call inc() of counterStateController, and 'watch in barProvider:' and  'watch in bazStateControllerProvider:' expected, but there wasn't.When I initialize them by watch of Consumer, it worked.Is this a bug or expected behavior? If expected, it should be noted on document because I couldn't find such documentation.

**Comment by rrousselGit** [comment]
This is the expected behavior

When a dependency of a provider changes, the provider isn't re-executed until the next time you try to read it

Since `read` isn't making widgets rebuild when providers change and none of your widgets are watching the providers, nothing is trying to read the providers, and therefore they aren't re-executed

Overall you should not use `read` inside the build method. Use `watch`
