### ISSUE TITLE
Access `state` within a `ProviderListener` using a `StateNotifier`?

### ISSUE THREAD

**Issue by emme1444** [rrousselGit/river_pod#248]
When using a `ProviderListener`, listening to changes on a `StateNotifierProvider`, accessing state requires interfacing through the `@protected` `state` property. 

I have enabled lints to disallow accessing `@protected` properties in my codebase, and would want to keep it that way. 

Here's is an example:

```dart
import "package:flutter/material.dart";
import 'package:hooks_riverpod/all.dart';

class Counter extends StateNotifier<int> {
  Counter([int startCount]) : super(startCount ?? 0);

  void increment() => state++;
}

final stateNotifierProvider = StateNotifierProvider(
  (_) => Counter(),
);

class TestWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) => ProviderListener<Counter>(
        provider: stateNotifierProvider,
        onChange: (context, counter) {
          counter.state; // The member 'state' can only be used within instance members of subclasses of 'package:state_notifier/state_notifier.dart'.
        },
        child: Container(),
      );
}
```

I guess what I could do, is use the `BuildContext` given to me by the `onChange` function to `read` the same provider I'm listening to, but eh I don't know. 

- What would be the best way to accomplish this, or am I simply missing something?  
- Am I typing the `ProviderListener` wrong?  
- Should the getter really be protected? Or maybe you can't protect the getters and setters differently? But what?  

Also, this `ProviderListener` is not firing at all when changing the `state`, internally, of the `StateNotifier`. But that's another problem. I might update you on this though.  

Thanks in advance!

**Comment by iamarnas** [comment]
@emme1444 Change to this snippet.
```dart
class​ ​TestWidget​ ​extends​ ​StatelessWidget​ {
  ​@override​
  ​Widget​ ​build​(​BuildContext​ context) ​=>​ ​ProviderListener​<​Counter​>​(
        provider​:​ stateNotifierProvider.state, // <- listen to state. 
        onChange​:​ (context, counter) {
            print('$counter');
        },
        child​:​ ​Container​(),
      );
}
```

**Comment by emme1444** [comment]
> @emme1444 Change to this snippet.
> 
> ```dart
> class​ ​TestWidget​ ​extends​ ​StatelessWidget​ {
>   ​@override​
>   ​Widget​ ​build​(​BuildContext​ context) ​=>​ ​ProviderListener​<​Counter​>​(
>         provider​:​ stateNotifierProvider.state, // <- listen to state. 
>         onChange​:​ (context, counter) {
>             print('$counter');
>         },
>         child​:​ ​Container​(),
>       );
> }
> ```

Aaah! OMG! Of course listen to the `state` of the `StateNotifier`. Omg, and I thought I had that part down everywhere. Apparently not in this part of the package. Dumb me. 

Thank you @iamarnas so much! I can finally fall asleep!
