### ISSUE TITLE
StateNotifier refers real instance though the dependency is overridden in testing

### ISSUE THREAD

**Issue by shunei4517** [rrousselGit/river_pod#251]
## Describe the bug
I think StateNotifier is reading the real instance of dependency though the overridden instance is provided.

For example I have repository class handling some networking tasks and read it from StateNotifier.
```dart
class Repository {
  Future<int> fetchSomething() async {
    // Will handle http connection in real case
    await Future.delayed(const Duration(seconds: 1));
    return Future.value(10);
  }
}

@freezed
abstract class CounterState with _$CounterState {
  const factory CounterState({
    @Default(0) int counter,
  }) = _CounterState;
}

class CounterStateNotifier extends StateNotifier<CounterState> {
  CounterStateNotifier(this.repository) : super(const CounterState()) {}

  final Repository repository;

  Future<void> incrementCounter() async {
    final fetchedCount = await repository.fetchSomething();
    state = state.copyWith(counter: fetchedCount);
  }
}

final repository = Provider((ref) => Repository());
final counterProvider = StateNotifierProvider(
  (ref) => CounterStateNotifier(
    ref.read(repository),
  ),
);
```

When I want to test the widgets depends on the `CounterStateNotifier`, I should use `overrides` property on `ProviderScope` right ?

So the code is going to be like this
```dart
class MockRepository extends Mock implements Repository {}

final mockRepository = MockRepository();

await tester.pumpWidget(
  ProviderScope(
    child: MaterialApp(
    // ...
    overrides: [
      repository.overrideWithProvider(Provider((ref) => mockRepository)),
    ],
  ),
);

when(mockRepository.fetchSomething()).thenAnswer(
  (realInvocation) => Future<int>.value(2),
);

// some tests
```

But when I execute the test, `CounterStateNotifier` was reading the real instance of `Repository` class(I printed the runtime type on console, also stubbed function was not called)

The full example is on this [repo](https://github.com/shunei4517/riverpod_testing_issue_repro.git)(Just the simple example using riverpod on default flutter counter app)

## Expected behavior
StateNotifier reads mocked instance inside the test environment and the stubbed function will be called

**Comment by rrousselGit** [comment]
I think you got confused

What your tests overrides in your repo is `test/widget_test.dart`'s `repository`. But what the application uses is `lib/main.dart`'s `repository`

Instead, remove the providers from your test files and import the providers from your main.

**Comment by shunei4517** [comment]
@rrousselGit I understood my mistake now
Thank you so much for your quick response and wonderful package !
