### ISSUE TITLE
Can't context.read ScopedProvider?

### ISSUE THREAD

**Issue by negitorogithub** [rrousselGit/river_pod#257]
Hi.

I'm using ProviderScope and ScopedProvider to pass arguments to a provider.
However, context.read needs RootProvider and ScopedProvider doesn't extends it, so I can't context.read ScopedProvider.
Could you tell me why I can't do it?

Thank you.

**Comment by negitorogithub** [comment]
I came up with the idea that ScopedProvider is only available in UI because ScopedProvider needs ProviderScope.
Is this true?

**Comment by iamarnas** [comment]
> I came up with the idea that ScopedProvider is only available in UI because ScopedProvider usually needs ProviderScope.
> Is this true?

It's true.

**Comment by negitorogithub** [comment]
Thank you!

**Comment by matuella** [comment]
@negitorogithub I don't know if I actually understood what you meant with the idea of "only available in UI", but you can read the `ScopedProvider`, although not through the frequently used `context.read`. To achieve this, you have to call the `ProviderScope.containerOf(context).read, which seems to accept this type.

**Comment by negitorogithub** [comment]
@matuella  I didn't know that. Thank you.
