### ISSUE TITLE
pub get error when adding hooks_riverpod: ^0.12.1

### ISSUE THREAD

**Issue by erwinagpasa** [rrousselGit/river_pod#258]
**Describe the bug**
So, because riverpod is 1.0.0+1, version solving failed.
pub get failed (1; So, because riverpod is 1.0.0+1, version solving failed.)
exit code 1

**To Reproduce**
When adding the hooks_riverpod
  flutter_hooks: ^0.15.0
  hooks_riverpod: ^0.12.1

**Expected behavior**
0

**Comment by rrousselGit** [comment]
Do you still have the problem?

**Comment by rrousselGit** [comment]
Closing since this issue is stale
