### ISSUE TITLE
Infinite loop ... heap space exhausted

### ISSUE THREAD

**Issue by dgaedcke** [rrousselGit/river_pod#261]
**Describe the bug**
Probably user error, but I can't get this simple example to work without heap-exhaust/crash

Using: 1.25.0-8.1.pre • channel beta
Seems similar to:
https://github.com/rrousselGit/river_pod/issues/243

**To Reproduce**

`import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() {
  runApp(
    ProviderScope(
      child: MyApp(),
    ),
  );
}

Future<List<String>> _getList(int secs) async {
  await Future.delayed(Duration(seconds: secs));
  return [
    'a',
    'b',
    'c',
  ];
}

final secsStateProvider = StateProvider<int>((ref) {
  ref.onDispose(() {
    print('secsStateProvider being disposed');
  });
  return 2;
});

final apiResultsProvider = FutureProvider<List<String>>((ref) async {
  //
  ref.onDispose(() {
    print('apiResultsProvider being disposed');
  });
  //
  var secs = ref.watch(secsStateProvider).state;
  var l = await _getList(secs);
  for (var x = 0; x <= secs; 1) {
    l.add('$x');
  }
  return l;
});

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Riverpod Practice',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage('Riverpod..'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  MyHomePage(this.title) : super();
  final String title;

  @override
  Widget build(BuildContext context) {
    //
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'Press btn to change list',
            ),
            Consumer(builder: (ctx, watch, child) {
              // added this watch of secsStateProvider
              // due to Remi's suggestion from
              // https://github.com/rrousselGit/river_pod/issues/243
              var toRetainObj = watch(secsStateProvider);
              var dataLst = watch(apiResultsProvider);

              return dataLst.when(data: (strLen) {
                print('rendering ');
                return Center(
                  child: Container(
                    height: 120,
                    child: ListView.builder(
                      itemCount: strLen.length,
                      itemBuilder: (context, idx) {
                        var rec = strLen[idx];
                        return Container(
                          height: 60,
                          width: 80,
                          child: Text(
                            rec,
                          ),
                        );
                      },
                    ),
                  ),
                );
              }, loading: () {
                print('loading ');
                return CircularProgressIndicator();
              }, error: (err, st) {
                print('err ');
                return Text(
                  'Err: $err',
                  style: Theme.of(ctx).textTheme.headline4,
                );
              });
            }),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          context.read(secsStateProvider).state++;
        },
        tooltip: 'Extend List',
        child: Icon(Icons.add),
      ),
    );
  }
}
`

**Comment by rrousselGit** [comment]
Your "for" is an infinite loop

**Comment by dgaedcke** [comment]
oh, that's embarrassing ... but I'm 99% sure I had the same problem before I added that loop ... will check again.  Thanks for your reply!!

**Comment by dgaedcke** [comment]
You are 100% correct ... terribly sorry for the interruption!!  Happy New Year
