### ISSUE TITLE
Can we use ProviderContainer to get multiple provider ?

### ISSUE THREAD

**Issue by chinkysight** [rrousselGit/river_pod#262]
I have some providers like `firstProvider` and `secondProvider` and I want to access it inside a pure dart class. e.g : 
```dart
class MainViewMode{ } 
```
So my question is that can we use a single instance of `ProviderContainer` to access multiple providers, e.g : 

```dart
class MainViewModel{

  final container = ProviderContainer();
  var first = container.read(firstProvider);
  var second = container.read(secondProvider);

}
```
I got this doubt as its mentioned in the docs not to reuse the instance of `ProviderContainer` between tests. So I thought does the above example works or not.

**Comment by rrousselGit** [comment]
I'm not sure what's the purpose of this code

**Comment by chinkysight** [comment]
> I'm not sure what's the purpose of this code

I use MVVM pattern where view depends on it's respective view model only. So if I have multiple services like Api service and data base services then my view model should depend on them. So I need  inject the dependencies into the view model. As of now I had used get_it for this, but I want to use RiverPod as it stated it can be read without any context and on.

**Comment by ldasilva-net** [comment]
> > I'm not sure what's the purpose of this code
> 
> I use MVVM pattern where view depends on it's respective view model only. So if I have multiple services like Api service and data base services then my view model should depend on them. So I need inject the dependencies into the view model. As of now I had used get_it for this, but I want to use RiverPod as it stated it can be read without any context and on.

What do you need is to use a Provider for the ViewModel, then you can access to all the dependencies it has.
Example:

`dart
class MainViewModel{
  final First first;
  final Second second;

  MainViewModel(this.first, this.second);
}

final mainViewModelProvider = Provider<MainViewModel>(
  (ref) => MainViewModel(
    first: ref.watch(firstProvider),
    second: ref.watch(secondProvider),
  ),
);
`

**Comment by rrousselGit** [comment]
I see little to no value in such object.

I'd recommend straight-up reading the providers in your view. Your providers _are_ your ViewModel

**Comment by chinkysight** [comment]
> > > I'm not sure what's the purpose of this code
> > 
> > I use MVVM pattern where view depends on it's respective view model only. So if I have multiple services like Api service and data base services then my view model should depend on them. So I need inject the dependencies into the view model. As of now I had used get_it for this, but I want to use RiverPod as it stated it can be read without any context and on.
> 
> What do you need is to use a Provider for the ViewModel, then you can access to all the dependencies it has.
> Example:
> 
> `
> class MainViewModel{
>   final First first;
>   final Second second;
> 
>   MainViewModel(this.first, this.second);
> }
> 
> final mainViewModelProvider = Provider<MainViewModel>(
>   (ref) => MainViewModel(
>     first: ref.watch(firstProvider),
>     second: ref.watch(secondProvider),
>   ),
> );
> `

Why we are injecting the dependencies using constructor although RiverPod works like a service locator. I would inject the dependencies directly inside the view model.

**Comment by chinkysight** [comment]
> I see little to no value in such object.
> 
> I'd recommend straight-up reading the providers in your view. Your providers _are_ your ViewModel

😅 We going off topic, I needed to only that can we use a single instance of `ProviderContainer` to read multiple `Providers` ?

**Comment by ldasilva-net** [comment]
> Why we are injecting the dependencies using constructor although RiverPod works like a service locator. I would inject the dependencies directly inside the view model.

Inject dependencies through constructor is a common DI pattern. In this case is the better way to keep classes as agnostic as possible. If you didn't like this, you can send as parameter only the `ref` object and then use it for access dynamically to all Providers do you need.
