### ISSUE TITLE
How to get context inside StateNotifier?

### ISSUE THREAD

**Issue by rodion-m** [rrousselGit/river_pod#268]
Hello! I want to show `snackbar` in `StateNotifier`s action - it requires a build context. Is it possible to get context inside `StateNotifier<>`? If it's not, how to properly show snackbar/toast?

**Comment by iamarnas** [comment]
@rodion-m It possible and very easy. 
```dart
final navigatorKey = GlobalKey<NavigatorState>();

// Here is global `context` 
// need put this to the MaterialApp. Example:
// MaterialApp... 
// navigatorKey: watch(navigatorKeyProvider), 
final navigatorKeyProvider = Provider((_) => navigatorKey) ;
```
Then you can use navigatorKeyProvider with Riverpod everywhere.

```
navigatorKey.currentContext;
```
I write from my mobile.  Then sorry if my code may be wrong.

**Comment by rodion-m** [comment]
@iamarnas Thanks for your response! I know that it's possible with `navigatorKey`, but I thought that this method is a little overhead and it's possible to get current context using some more elegant way. Perhaps someone else knows.

**Comment by rrousselGit** [comment]
As suggested by @smiLLe, I'd recommend against putting navigation logic inside your `StateNotifier` and instead use `ProviderListener`
