### ISSUE TITLE
Does not maintain state after reload page in flutter web

### ISSUE THREAD

**Issue by chessasuke** [rrousselGit/river_pod#269]
**Describe the bug**
After reloading a page the app doesn't maintain state (flutter web)

**To Reproduce**

The same counter app example can be used to reproduce it. Reloading the page set the count to 0 again.

**Expected behavior**
Maintain state, after clicking 3 times for example and reload maintain 3 in the counter.

**Comment by fremfi** [comment]
I'm having a similar problem, i was wondering if this is supported? is there a setting I need to turn on?
Thanks

**Comment by chessasuke** [comment]
> I'm having a similar problem, i was wondering if this is supported? is there a setting I need to turn on?
> Thanks

Are u using navigation 2.0?

**Comment by chessasuke** [comment]
Hello, this is not related to riverpod, Flutter web doesn't support hot reload.

**Comment by fremfi** [comment]
wouldn't it be possible for riverpod to preserve state on local storage? and when you restart to load state from there if exists? / provide some caching mechanism to invalidate the state. 
Is my only option to query user data whenever a page is refreshed on the web and update the states?

**Comment by chessasuke** [comment]
well, normally when u refresh the page is because u do want to update the state. In any case, I guess u could implement your use case using shared preferences + riverpod
