### ISSUE TITLE
Add a getter `value` to AsyncValue

### ISSUE THREAD

**Issue by erf** [rrousselGit/river_pod#270]
**Is your feature request related to a problem? Please describe.**

If i know that a `FutureProvider` has a data value, i can get it using `asyncValue.data.value`. This can become a bit tedious to type.

**Describe the solution you'd like**

I would like to propose to add a `value` getter on `AsyncValue`, which would return the value of data as above if it exists or `null` if it doesn't. E.g. `final myValue = asyncValue.value`. Which is basically as shorthand for `asyncValue.data?.value`.

**Comment by smiLLe** [comment]
You should be able to create  a small `extension` doing this

**Comment by erf** [comment]
I know, but i thought it might be a nice addition to `AsyncValue`

**Comment by erf** [comment]
Here it is as an extension:

```
import 'package:flutter_riverpod/flutter_riverpod.dart';

/// shorthand for `AsyncValue.data?.value`
extension AsyncValueExt<T> on AsyncValue<T> {
  T get value => this.data?.value;
}
```

**Comment by rrousselGit** [comment]
Closing as there is now an `AsyncValue.value`

**Comment by mono0926** [comment]
@rrousselGit 

> Closing as there is now an AsyncValue.value

Current implementation of [AsyncValue.value](https://pub.dev/documentation/riverpod/1.0.0-dev.10/riverpod/AsyncValueX/value.html) is this: 

```dart
  T get value {
    return _map(
      data: (d) => d.value,
      // ignore: only_throw_errors
      error: (e) => throw e.error,
      loading: (l) => throw AsyncValueLoadingError(),
    );
  }
```

I prefer this:

```dart
  T? get value {
    return asData?.value;
  }
```

---

With the current implementation, it's easy to do this kind of mistake:

```dart
  final v = AsyncValue<String>.loading();
  v.value; // AsyncValueLoadingError
```

With my suggested implementation, it is hard to mistake:

```dart
  final v = AsyncValue<String>.loading();
  v.value; // null (String?)
  v.value!; // error
```

**Comment by mono0926** [comment]
@rrousselGit 

> I don't mind returning null during loading, but I do think errors should still throw

I agree with that combination 👍

**Comment by ebelevics** [comment]
> The problem with `value => asData?.error` is errors are swallowed and likely mixed with loading states.
> 
> I don't mind returning `null` during loading, but I do think errors should still throw

Can you give some usecase where this would be appropriate? I do understand that it distincts value from loading and error state, but I'm not sure where this should be applicable. For example I have chat now. All chat messages are fetched using `when` map. But I have some segments in chat (chat send message bar) where I'm not using `when` but `value` instead, because I have to check if value is empty. And by receiving throw instead of null, then it seems I have to always wrap value with try catch. Atleast T? get value => asData?.value; does get the result.
