### ISSUE TITLE
Add Result type to river_pod

### ISSUE THREAD

**Issue by Nolence** [rrousselGit/river_pod#271]
Hi!

I found the [Result](https://github.com/rrousselGit/river_pod/blob/0ba3e28bba005f6be06bf269049a6e762e71998e/examples/marvel/lib/src/result.dart) type created inside the marvel example was really useful and was surprised it wasn't in `riverpod`. Compared to `dartz`'s `Either` `Result` seems more practical and user friendly for typical apps so I'm curious why it wasn't included? I also think it complements `AsyncValue`'s usage nicely.

The current alternative was just to copy the Result implementation myself into my own models. I feel like if it were included in `riverpod` though it would encourage better practices around `Futures` and encourage users to look more towards functional solutions.

**Comment by rrousselGit** [comment]
I didn't include it in riverpod mainly because it's not used by any provider

`AsyncValue` is depended on by `FutureProvider`/`StreamProvider`, but `Result` is purely a bonus.

**Comment by Nolence** [comment]
At first I wondered if there were enough special union/sealed classes to warrant another library for just these types but I couldn't find many others.

In any case, I can see how `Result` isn't necessary to library and might be more clutter than anything. Personally I'd still like to see it in the library solely for the value it adds to writing cleaner code. Feel free to close this or leave open for further comments/votes from others

Thanks Remi!

**Comment by RandalSchwartz** [comment]
Maybe at least include it as an example.  Oh wait, it already is, yes?

**Comment by Nolence** [comment]
Meh, I've personally changed my own opinion on this. Closing as there's already an implementation in the example and I feel like that's good enough.
