### ISSUE TITLE
Overriding StateNotifierProvider

### ISSUE THREAD

**Issue by MarcinusX** [rrousselGit/river_pod#273]
Hey, I am having hard times trying to properly mock StateNotifierPorvider. I'm not sure if I'm missing something or if it's not supported.

Let's say I have a widget that listens to a state notifier provider:

```
class ExampleWidget extends HookWidget {
  @override
  Widget build(BuildContext context) {
    final x = useState(exampleProvider.state);
    return Text(x.toString());
  }
}

final exampleProvider = StateNotifierProvider((ref) => ExampleStateNotifier());

//This is connecting to API and should be mocked for tests.
class ExampleStateNotifier extends StateNotifier<bool> {
  ExampleStateNotifier() : super(false);
}
```

How can I write a test that will: 
* Mock exampleProvider to emit a given state.
* Verify in widgetTest that for example text is correct.

Overriding `exampleProvider` with a mock doesn't seem to solve the problem, especially that the state is either protected (in StateNotifier) or it's an extension method on real provider (in StateNotifierProvider).

Also the similar problem occurs also when trying to listen in `ProviderListener`.

Please tell me, am I missing something?

**Comment by rrousselGit** [comment]
The problem isn't riverpod but mockito here.  
Mockito is not what you want to use for "mocking" a StateNotifier (if you even want that).

Methods like `addListener` need to keep working.


You could do:

```dart
class MockExampleStateNotifier extends StateNotifier<bool> implements ExampleStateNotifier {
  MockExampleStateNotifier() : super(false);
}
```

Then using the override methods on `exampleProvider` combined with `ProviderScope` should work as expected.

**Comment by rrousselGit** [comment]
Overall I would say that it's pretty unlikely you'll want to mock a StateNotifier.

If your goal is to mock http requests & co, consider extracting these in a separate class (maybe Repository pattern?) and mock that.  
What you _can_ mock StateNotifierProvider, it usually mocks too many things, decreasing the value of your test.

**Comment by MarcinusX** [comment]
I ended up doing exactly same thing so I guess (as usual regarding my issues 🙈 ) - it can be closed :)

**Comment by nilsreichardt** [comment]
I invested also some hours to figure this out. Would be nice to have some mentions of this in the documentation.
