### ISSUE TITLE
Provider.value

### ISSUE THREAD

**Issue by serhii-k** [rrousselGit/river_pod#278]
Hello,

I'm trying to migrate from provider to riverpod. And there is one very basic pattern that I'm trying to implement.

```
final valueNotifier = any ValueNotifier<int or other type>; // we get it from whatever place

ChangeNotifierProvider.value(
  value: valueNotifier,
  child: Consumer<ValueNotifier<int>>(
    builder: (context, valueNotifier, _) {
      return ...;
    }
  ),
)
```

So the goal is simply to react to any changes in some ChangeNotifier that is obtained from other place.

Is there any obvious pattern to implement this with riverpod?

**Possible solution**

I've tried to implement it this way:

```
final testProvider =
    ChangeNotifierProvider.family<ChangeNotifier, ChangeNotifier>((ref, valueNotifier) {
  return valueNotifier;
});
```

And then used it:
```
final valueNotifier = ...;

Consumer(builder: (context, watch, _) {
  watch(testProvider(valueNotifier));
  return ...;
});
```

That works fine, but I also need to dispose the provider state when this notifier is no longer listened.
After adding the `autoDispose` modifier when the provider state is disposed, riverpod disposes the valueNotifier... Which I don't want to be disposed at this stage.

Well, I just need the behaviour of the ChangeNotifierProvider.value(value: valueNotifier) from the provider package, where I can control the lifecycle of the valueNotifier.

A workaround I see is to create another ChangeNotifier that would `addListener` to the given 'family' notifier, and then `removeListener` in its `onDispose`.

**Possible suggestion**

If there is a very simple solution to this pattern, please let me know it. As a suggestion, maybe a new modifier `value` can be used to put any value into any provider state.

For example:
```
final testProvider = ChangeNotifierProvider.autoDispose.value((ref, valueNotifier) {
  return valueNotifier;
});
```

So that when used with the `autoDispose` modifier the given valueNotifier will not be disposed.

**Comment by smiLLe** [comment]
What is the point of passing a Provider into a riverpod?

**Comment by serhii-k** [comment]
@smiLLe I'm not sure if I understand the question correctly.

I'm not passing a Provider into a riverpod. I just need a way to react (in a widget tree) to changes in some predefined ChangeNotifier. So the goal is to (temporarily) put this ChangeNotifier into the ProviderScope, and then consume its changes with the Consumer (riverpod).

I'm going to altogether move away from the provider package.

**Comment by serhii-k** [comment]
`A workaround I see is to create another ChangeNotifier that would addListener to the given 'family' notifier, and then removeListener in its onDispose.`

Here is its implementation:

```
final watcherProvider = ChangeNotifierProvider.autoDispose
    .family<_ChangeNotifierWatcher, ChangeNotifier>((ref, valueNotifier) {
  return _ChangeNotifierWatcher(valueNotifier);
});

class _ChangeNotifierWatcher extends ChangeNotifier {
  final ChangeNotifier notifier;

  _ChangeNotifierWatcher(this.notifier) {
    notifier.addListener(notifyListeners);
  }

  @override
  void dispose() {
    notifier.removeListener(notifyListeners);
    super.dispose();
  }
}
```

Then we can use it in a widget:
```
valueNotifier can be any ChangeNotifier we want to watch

Consumer(builder: (context, watch, _) {
  watch(watcherProvider(valueNotifier));
  return ...based on valueNotifier.value...;
});
```

So, this way the valueNotifier will not be disposed when the Consumer is removed.

**Comment by serhii-k** [comment]
Maybe...

```
Consumer(builder: (context, watch, _) {
  final notifier = watch(someProvider, initialValue: valueNotifier); // only sets the initialValue if someProvider is not yet created
  return ...;
});
```

There should be a way to give the initial value to any type of a provider. If that is possible/relevant.

And maybe some sort of `ref.maintainValue` (like `ref.maintainState`) that will tell the `autoDispose` to not dispose the given notifier.

**Comment by rrousselGit** [comment]
You probably don't want to use a provider in that case.

It appears to me that you only want to use `provider` to remove the nesting for listening the notifier.
In that case, the solution is a friend of `riverpod`: `fluttter_hooks`


```dart
final valueNotifier = any ValueNotifier<int or other type>; // we get it from whatever place


....

class Example extends HookWidget {
  @override
  Widget build(context) {
    final value = useValueListenable(valueNotifier);

    return Text('$value');
  }
}
```

**Comment by serhii-k** [comment]
@rrousselGit Oh, that is exactly what I needed. Thank you very much, Remi!
