### ISSUE TITLE
StreamProvider based on other StreamProvider misses first value on refresh

### ISSUE THREAD

**Issue by Nolence** [rrousselGit/river_pod#281]
Hi !

When you have a StreamProvider such as this

```dart
final numberProvider = StreamProvider.autoDispose<int>((ref) async* {
  yield 1;
  await Future.delayed(Duration(seconds: 1));
  yield 2;
  await Future.delayed(Duration(seconds: 1));
  yield 3;
});
```

and then watch it

```dart
useProvider(numberProvider).when(
  data: (number) {
    print(number);
    return Text(number.toString());
  },
  loading: () => Text('Loading...'),
  error: (_, __) => Text('Error'),
),
```

You'll correctly get printed `1 2 3`. However if you introduce a second StreamProvider that listens to the first and then try to refresh the first provider using `context.refresh(numberProvider)` it'll miss the first value for some reason:

```dart
final stringProvider = StreamProvider.autoDispose<String>((ref) async* {
  final numberStream = ref.watch(numberProvider.stream);

  await for (final number in numberStream) {
    yield number.toString();
  }
});

class MyApp extends HookWidget {
  @override
  Widget build(BuildContext context) {
    final stringValue = useProvider(stringProvider);

    return MaterialApp(
      home: Scaffold(
        floatingActionButton: FloatingActionButton(
          child: Icon(Icons.restore),
          onPressed: () => context.refresh(numberProvider),
        ),
        body: Center(
          child: stringValue.when(
            data: (data) {
              print(data); // Prints 1,2,3 on first run and then 2, 3 every time onRefresh
              return Text(data);
            },
            loading: () => Text('Loading...'),
            error: (_, __) => Text('Error'),
          ),
        ),
      ),
    );
  }
}
```

If you try to refresh `stringProvider` then you'll get stuck in the `loading` case.

My expectation was that we get the same values as we first do when the app is run on `refresh`

Context. I was actually looking into a separate issue that is difficult to reproduce but I think happens when a `StreamProvider` yields a stream that another `StreamProvider` watches. The second `StreamProvider` does not catch onto the events produced by the first and is stuck in loading. Will get back to you on this one

Thanks !

[EDIT]

Thanks to @smiLLe  I think I understand that my "separate" issue is actually related to this. What happens is that the first `StreamProvider` is listened to in an initial page. When I then navigate to a different page and listen to a `StreamProvider` that is dependent on the first `StreamProvider` it is stuck in the loading state because the first has already been listened to and it does not emit old values to new listeners

**Comment by smiLLe** [comment]
> If you try to refresh stringProvider then you'll get stuck in the loading case.
> My expectation was that we get the same values as we first do when the app is run on refresh

I think what is happening here is that you are basically `.listen()` to the stream of `numberProvider` on every `.refresh()` and looking at your code, you implicitly create `numberProvider` in your widget because you listen to `stringProvider`.
This will update your `stringProvider` after the initial create.

And since StreamController won't  emit its values to new subscribers your `stringProvider` is stuck in `loading`, after  you `.refresh()` until `numberProvider` will emit a new value

**Comment by Nolence** [comment]
I think that makes sense although I'm stilla little hazy on the details. Does that mean this is the intended behavior? What would replacing the internal `StreamController.broadcast` inside the `StreamProvider` state with something like a `ReplaySubject` produce or is there a way to "pre subscribe" to`numberProvider` before the initial create?

**Comment by smiLLe** [comment]
Wait, maybe i am wrong. I first thought ( sorry i didin't read your code correctly ) that you would `.refresh()` the `stringProvider`... but you refresh the `numberProvider`. I think this could be a "bug" in riverpod on how providers are (re)created.

Do you use a lot of Stream features? Or is there a chance to use StateNotifier instead? It is so much easier to use and understand compared to the weird stream behaviour.

**Comment by Nolence** [comment]
Yes refreshing the `stringProvider` led to just a loading state with no value being emitted. Refreshing the `numberProvider` was what partially worked for me except for producing the first value. I think you're right though about the stream being listened to at first and then no longer emitting events to dependents.

I actually use streams a lot thanks to Firebase. Because of this issue though, instead of async/generator syntax I've had to replace it with a slightly more verbose `.when` statement to produce the streams-based-on-streams I want. (Image a user stream that then creates a profile stream that then creates a "favorites" stream).

```dart
final profileProvider = StreamProvider.autoDispose<Profile>((ref) {
  return ref.watch(userProvider).when(
        error: (error, stackTrace) => Stream.error(error, stackTrace),
        loading: () => Stream.empty(),
        data: (user) {
          if (user == null) return Stream.empty();

          return profilesCollection.doc(user.uid).snapshots().map(
            (snapshot) {
              return Profile.fromSnapshot(snapshot);
            },
          );
        },
      );
});
```

This works for me but doesn't look as good as the generator syntax

**Comment by rrousselGit** [comment]
That's streams for you~

Long story short, I'd recommend against manipulating streams directly. In your case, you probably want to do `ref.watch(streamProvider.last)`

There's an bit of doc on the `.last` property that explains why it is needed

```dart
final stringProvider = FutureProvider.autoDispose<String>((ref) async {
  final number = await ref.watch(numberProvider.last);

  return '$number';
});
```

**Comment by Nolence** [comment]
Hi @rrousselGit, thank you for the code !

Just to be clear, is there no way to return a StreamProvider based on another StreamProvider safely?

Expanding on your code (which worked great btw), I tried:

```dart
final stringProvider = StreamProvider.autoDispose<String>((ref) async* {
  final number = await ref.watch(numberProvider.last);
  print('This is continuously called');

  yield '$number';
});
```

But the code continuously runs and is stuck in the loading state. I guess I'm just curious at this point to see if I can get StreamProvider of a StreamProvider without creating a BehaviorSubject -- which will be my next option.

**Comment by rrousselGit** [comment]
That's logical. Is there anything wrong with that?

The behaviour is the same to what you originally did: it stringifies all values pushed to the stream

**Comment by Nolence** [comment]
Yes, for that example I posted the behavior is the same. My personal use case was listening to a firebase user stream and turning that into a profile stream based from a snapshot listener on a firebase collection. Personally, I don't mind creating the `BehaviorSubject` and doing it that way now that I know the details of why and how things work. Thank you for the help

**Comment by rrousselGit** [comment]
I still don't see why the refresh would be an issue

**Comment by Nolence** [comment]
Sorry, I didn't mean to keep going on a closed issue but I'm confused about your comment. Are you referring to the `context.refresh` in the initial example? Can you elaborate?

**Comment by rrousselGit** [comment]
I was referring to the ".last"

I don't understand why it causing a provider refresh would be an issue

**Comment by Nolence** [comment]
Oh! I think I get your meaning. No, you're right. There is no issue when refreshing the `FutureProvider` with `.last` as you explained in code. Everything works as it should.

I might've just caused confusing by being too insistent on "What about with StreamProvider" nonsense but I think I'm resolved in that.

Will leave this issue alone
