### ISSUE TITLE
StereamProvider not rebuilding the widget tree when AyncValue got changed

### ISSUE THREAD

**Issue by andyalex234** [rrousselGit/river_pod#284]
I am to listening firebase` authstatechage` stream and provide the stream with `steamProvider`  to change the view based on the stream value. And I did this:
`class AuthService {
  final FirebaseAuth _auth = FirebaseAuth.instance;

  Stream<User> get currentUser => _auth.authStateChanges();
}`

`final userStream = StreamProvider.autoDispose((ref) => AuthService().currentUser);

class AuthenticationWrapper extends ConsumerWidget {
  @override
  Widget build(BuildContext context, ScopedReader watch) {
    final user = watch(userStream);
    print('AutenticationWrapper build method got called');
    return user.when(
        data: (data) {
          if (data?.uid == null) {
            print('I am currently Logged out 😔');
            return LogInPage();
          } else {
            print('I am logged in user😁');
            return HomePage();
          }
        },
        loading: () => CircularProgressIndicator(),
        error: (e, s) => Text('Oops'));
  }
}`
I was expecting to have LogIn page to be rendered when the AyncValue of the streamProvider gets changed The above  code didn't work as expected infact it prints the message but it doesn't return the Widget it supposed to return. But when I hot restart the app It will render the right Widget based on the stream value. 

Why the build method does not re-render when this: `final user = watch(userStream);` got change?

**Comment by rrousselGit** [comment]
> it doesn't return the Widget it supposed to return.

What does it return? Loading, error?

If it's an error, could you print the stacktrace?

**Comment by andyalex234** [comment]
@rrousselGit I figured why it doesn't behaved they way I wanted it. I've made a stupid mistake somewhere in my code now everything works perfectly... I'm sorry for wasting your time. Thanks for your quick response🙏 you're the best.
