### ISSUE TITLE
extract AsyncValue to separate package

### ISSUE THREAD

**Issue by jinyus** [rrousselGit/river_pod#285]
I think this class is useful outside the scope of this project and it'd be nice to have it as a standalone package.

**Comment by rrousselGit** [comment]
You can make your own using Freezed

**Comment by jinyus** [comment]
I did, but I saw that you had a todo in the source and wanted to get any future updates that you make to the class.

**Comment by huang12zheng** [comment]
@jinyus  I am kind of agree, but I'm still confused
* 1.
Having only one AsyncValue seems like a bit partly. It's just a result of REST,
Maybe viewState will also need it. in other word. the package would be a kind of weird

* 2.
I have reviewed myself, maybe because I actually need other packages, so I need AsyncValue. But maybe RiverPod is a good choice? I wonder if you are in the same case

> The new state management is hard for me to recode, because they are already a bit too much. Triple_pattern, mbox, bloc, provider, redux...

> https://pub.dev/packages/async_value
> I did publish it before find this issue, however,  This maybe not a good attempt
> In particular, Nullsafe is going on

**Comment by venkatd** [comment]
We have a need for using AsyncValue separately. We have our own GraphQL library which we use internally and we wouldn't want to introduce riverpod as a dependency just to use AsyncValue.

And we'd like the public api to be compatible with other parts of our code that use AsyncValue. We could easily create our own but then our codebase would have to deal with two incompatible versions of AsyncValue.

**Comment by iamarnas** [comment]
@venkatd 👋

What is wrong to create your own state class with Freezed? Flutter also has a similar class as `AsyncValue` called `AsyncSnapshot` and uses with `Stream` and `Future` as Riverpod.

**Comment by KristianBalaj** [comment]
+1 it's a nice Future wrapper and there can be a project that does not need the whole riverpod package

**Comment by rrousselGit** [comment]
`riverpod` (not `flutter_riverpod`) is written in pure Dart. So importing it to get AsyncValue  is harmless, since tree-shaking will remove what you don't use.


I'm not fond of extracting AsyncValue. It was built specifically for Riverpod and will keep changing to fit Riverpod needs.

**Comment by KristianBalaj** [comment]
Yup, makes sense 🙌

**Comment by rrousselGit** [comment]
Closing since I don't plan on doing that
