### ISSUE TITLE
Implement bloc kind of Approach with riverpod

### ISSUE THREAD

**Issue by pythonhubpy** [rrousselGit/river_pod#286]
Hello, @rrousselGit I tried to implement resocoders Flutter Domain Driver Design with the help of river pod.

https://www.youtube.com/watch?v=RMiN59x3uH0&list=PLB6lc7nQ1n4iS5p-IezFFgqP6YvAJy84U

This is the video I followed to implement it.

This is my satenotifiers code

```
class SignInStateNotifier extends StateNotifier<SignInFormStates> {
  SignInStateNotifier(this._authFacade) : super(SignInFormStates.initial());

  final IAuthFacade _authFacade;

  Stream<SignInFormStates> mapEventToState(SignInFormEvents events) async* {
    yield* events.map(emailChanged: (value) async* {
      yield state.copyWith(
        emailAddress: EmailAddress(value.email),
        authFailureOrSuccess: none(),
      );
    }, passwordChanged: (value) async* {
      state.copyWith(
        password: Password(value.password),
        authFailureOrSuccess: none(),
      );
    }, signInWithEmailAndPasswordPressed: (value) async* {
      Either<AuthFailure, Unit> failureOrSuccess;
      if (state.emailAddress.isValid() && state.password.isValid()) {
        yield state.copyWith(
          isSubmitting: true,
          authFailureOrSuccess: none(),
        );
        failureOrSuccess = await _authFacade.signInWithEmailAndPassword(
          emailAddress: state.emailAddress,
          password: state.password,
        );
      }
      yield state.copyWith(
        isSubmitting: false,
        showErrorMessage: true,
        authFailureOrSuccess: optionOf(failureOrSuccess),
      );
    });
  }
}

```

I want to map the different events based on user interactions how can I do that?

My Form Widget

```
Form(
              child: Column(
                children: [
                  TextFormField(
                    autovalidateMode: AutovalidateMode.onUserInteraction,
                    onChanged: (value) => state
                        .mapEventToState(SignInFormEvents.emailChanged(value)),
                    validator: (_) => state2.emailAddress.validatedObject.fold(
                            (l) => l.maybeMap(
                            orElse: () => null,
                            invalidEmail: (_) => "Invalid Email"),
                            (_) => null),
                  ),
                  FlatButton(
                      onPressed: () {
                        state.mapEventToState(SignInFormEvents
                            .signInWithEmailAndPasswordPressed());
                      },
                      child: Text("Hello World"))
                ],
              )
            );
```

Give me a solution, please. I am exploring riverpod.

Thanks in advance.

**Comment by smiLLe** [comment]
If you want to use bloc, go with the bloc package. There is also a bloc provider. 
As for riverpod there is a StreamProvider.
The way you are using your StateNotifier is certainly not the way you should use it :)


You want something like this: 
You can even create a simple`mapEventToState` if that is what you prefer :)
```dart
class SignInStateNotifier extends StateNotifier<SignInFormStates> {
  SignInStateNotifier(this._authFacade) : super(SignInFormStates.initial());

  final IAuthFacade _authFacade;

  void emailChanged(String email) {
    state = state..copyWith(
        emailAddress: EmailAddress(value.email),
        authFailureOrSuccess: none(),
      )
  }

  void passwordChanged( ... ) {
    state = state..copyWith(
        password: Password(value.password),
        authFailureOrSuccess: none(),
      )
  }
}

final signInProvider = StateNotifierProvider<SignInStateNotifier >((_) => SignInStateNotifier ());
```

**Comment by pythonhubpy** [comment]
> If you want to use bloc, go with the bloc package. There is also a bloc provider.
> As for riverpod there is a StreamProvider.
> The way you are using your StateNotifier is certainly not the way you should use it :)
> 
> You want something like this:
> You can even create a simple`mapEventToState` if that is what you prefer :)
> 
> ```dart
> class SignInStateNotifier extends StateNotifier<SignInFormStates> {
>   SignInStateNotifier(this._authFacade) : super(SignInFormStates.initial());
> 
>   final IAuthFacade _authFacade;
> 
>   void emailChanged(String email) {
>     state = state.copyWith(
>         emailAddress: EmailAddress(value.email),
>         authFailureOrSuccess: none(),
>       )
>   }
> 
>   void passwordChanged( ... ) {
>     state = state.copyWith(
>         password: Password(value.password),
>         authFailureOrSuccess: none(),
>       )
>   }
> }
> 
> final signInProvider = StateNotifierProvider<SignInStateNotifier >((_) => SignInStateNotifier ());
> ```
Thanks and this worked really fine.

You said that I can create a `mapEventToState` can you please elaborate on how can I do that?

**Comment by smiLLe** [comment]
Assuming  SignInFormEvents  is a freezed class:

```dart
class SignInStateNotifier extends StateNotifier<SignInFormStates> {
  SignInStateNotifier(this._authFacade) : super(SignInFormStates.initial());

  final IAuthFacade _authFacade;

  void mapEventToState(SignInFormEvents ev) {
    state = ev.when(foo: (val) => state.copyWith(prop: val), bar: (val) => state.copyWith( .. ));
  }
}
```

**Comment by pythonhubpy** [comment]
Yes, you are right it is a freezer class.

Thanks a lot.

**Comment by pythonhubpy** [comment]
Everything works fine but the state does not change while I type in something in the field.

```
Consumer(
          builder: (context, watch, child) {
            final providerState = watch(signInProvider);
            final stateNotifierState = watch(signInStateNotifierProvider.state);
            return Form(
                child: Column(
              children: [
                TextFormField(
                  autovalidateMode: AutovalidateMode.onUserInteraction,
                  onChanged: (value) => providerState
                      .mapEventToState(SignInFormEvents.emailChanged(value)),
                  validator: (_) =>
                      stateNotifierState.emailAddress.validatedObject.fold(
                          (l) => l.maybeMap(
                              orElse: () => null,
                              invalidEmail: (_) => "Invalid Email"),
                          (_) => null),
                ),
                FlatButton(
                    onPressed: () {
                      providerState.mapEventToState(
                          SignInFormEvents.signInWithEmailAndPasswordPressed());
                    },
                    child: Text("Hello World"))
              ],
            ));
          },
        ),
```

**Comment by pythonhubpy** [comment]
```
void mapEventToState(SignInFormEvents signInFormEvents) {
    state = signInFormEvents.when(
        emailChanged: (value)  => state.copyWith(
              emailAddress: EmailAddress(value),
              authFailureOrSuccess: none(),
            ),
        passwordChanged: (value)  => state.copyWith(
              password: Password(value),
              authFailureOrSuccess: none(),
            ),
        signInWithEmailAndPasswordPressed: () async* {
          yield* _performActionOnAuthFacade(
              _authFacade.signInWithEmailAndPassword);
        });
  }
```

This is my `mapEventToStateFunction` but for the particular state `signInWithEmailAndPasswordPressed` I want to yield a set of values from the `_performActionOnAuthFacade` function how can I achieve that?

```
 Stream<SignInFormStates> _performActionOnAuthFacade(
    Future<Either<AuthFailure, Unit>> Function({
      @required EmailAddress emailAddress,
      @required Password password,
    })
        forwardCall,
  ) async* {
    Either<AuthFailure, Unit> failureOrSuccess;
    if (state.emailAddress.isValid() && state.password.isValid()) {
      yield state.copyWith(
        isSubmitting: true,
        authFailureOrSuccess: none(),
      );
      failureOrSuccess = await _authFacade.registerWithEmailAndPassword(
          emailAddress: state.emailAddress, password: state.password);
    }
    yield state.copyWith(
        isSubmitting: false,
        showErrorMessage: true,
        authFailureOrSuccess: optionOf(failureOrSuccess));
  }

```
This is my `_performActionOnAuthFacade` function

I get this error in the above code

`The argument type 'Stream<SignInFormStates> Function()' can't be assigned to the parameter type 'SignInFormStates Function()'.`

**Comment by smiLLe** [comment]
Your error is here.
```dart
     signInWithEmailAndPasswordPressed: () async* {
          yield* _performActionOnAuthFacade(
              _authFacade.signInWithEmailAndPassword);
        });
```
you want to return a `SignInFormStates` instead of a `Stream` instance 😄

**Comment by pythonhubpy** [comment]
Yeah how can I do that because I am yielding two values from the function.

**Comment by smiLLe** [comment]
I don't have access to an IDE right now so i am writing this without linting etc. :)

I highly recommend you to just forget about Streams for now and just focus on Futures, StateNotifier and Riverpod.
Or otherwise, just go with the bloc package solution and forget about StateNotifer and Riverpod.
You are not going to do yourself a favor by copy/paste some bloc/streams tutorials stuff and mix it with other libraries like StateNotifier and/or Riverpod. 

```dart
void mapEventToState(SignInFormEvents signInFormEvents) {
     signInFormEvents.when(
        emailChanged: (value)  => state = state.copyWith(
              emailAddress: EmailAddress(value),
              authFailureOrSuccess: none(),
            ),
        passwordChanged: (value)  => state = state.copyWith(
              password: Password(value),
              authFailureOrSuccess: none(),
            ),
        signInWithEmailAndPasswordPressed: ()  {
            if (state.emailAddress.isValid() && state.password.isValid()) {
                state = state.copyWith(
                 isSubmitting: true,
                 authFailureOrSuccess: none(),
                );
             } 
              failureOrSuccess = await _authFacade.registerWithEmailAndPassword(
                emailAddress: state.emailAddress, password: state.password);
              state = state.copyWith(
                isSubmitting: false,
                showErrorMessage: true,
                authFailureOrSuccess: optionOf(failureOrSuccess));
          });
  }
```

**Comment by pythonhubpy** [comment]
Thanks for your great help @smiLLe.

I have got out of streams now and I have used the code that you sent me above. I also understand that it's so tough to move on from one library to another seeing a youtube video.

But one some doubt
```

 signInWithEmailAndPasswordPressed: ()  {
            if (state.emailAddress.isValid() && state.password.isValid()) {
                state = state.copyWith(
                 isSubmitting: true,
                 authFailureOrSuccess: none(),
                );
             } 
              failureOrSuccess = await _authFacade.registerWithEmailAndPassword(
                emailAddress: state.emailAddress, password: state.password);
              state = state.copyWith(
                isSubmitting: false,
                showErrorMessage: true,
                authFailureOrSuccess: optionOf(failureOrSuccess));
          });
```

How can I use await without async function it will give an error right?

**Comment by smiLLe** [comment]
Either mark the function as async (which should work) or use the Future.then() 
```dart
await _authFacade.registerWithEmailAndPassword(
                emailAddress: state.emailAddress, password: state.password).then((val) {
  state = state.copyWith(
                isSubmitting: false,
                showErrorMessage: true,
                authFailureOrSuccess: optionOf(failureOrSuccess));
});

```

**Comment by smiLLe** [comment]
@pythonhubpy please close the issue if everything is working  :)

**Comment by pythonhubpy** [comment]
Yeah sure. Everything is working fine. Thanks for your help.

**Comment by pythonhubpy** [comment]
Hey, @smiLLe thanks for your continuous help but again I have ended up in an error.

How can I do something like this in riverpod

```
BlocConsumer<SignInFormBloc, SignInFormState>(
      listener: (context, state) {
        state.authFailureOrSuccessOption.fold(
          () {},
          (either) {
            either.fold(
              (failure) {
                FlushbarHelper.createError(
                  message: failure.map(
                    // Use localized strings here in your apps
                    cancelledByUser: (_) => 'Cancelled',
                    serverError: (_) => 'Server error',
                    emailAlreadyInUse: (_) => 'Email already in use',
                    invalidEmailAndPasswordCombination: (_) =>
                        'Invalid email and password combination',
                  ),
                ).show(context);
              },
              (_) {
                Router.navigator.pushReplacementNamed(Router.notesOverviewPage);
                context
                    .bloc<AuthBloc>()
                    .add(const AuthEvent.authCheckRequested());
              },
            );
          },
        );
      },
```
Here there is a BlocConsumer widget I tried to find something similar to this in riverpod I could not do that. 

Please give a solution.

**Comment by pythonhubpy** [comment]
> Either mark the function as async (which should work) or use the Future.then()
> 
> ```dart
> _authFacade.registerWithEmailAndPassword(
>                 emailAddress: state.emailAddress, password: state.password).then((val) {
>   state = state.copyWith(
>                 isSubmitting: false,
>                 showErrorMessage: true,
>                 authFailureOrSuccess: optionOf(failureOrSuccess));
> });
> ```

I cannot make the function ```async``` and ```.then()``` is also not working fine.

I want to assign a value to the ```failureOrSuccess``` but when I make the function ```async``` I get this error

```The argument type 'Future<AuthFormStates> Function()' can't be assigned to the parameter type 'AuthFormStates Function()'.```

When I used .then() the value is not getting assigned to ```failureOrSuccess``` it is printing ```null```

Please give a solution @smiLLe @rrousselGit.

Thanks in advance.

**Comment by pythonhubpy** [comment]
I found a solution for this from StackOverflow

Link: https://stackoverflow.com/questions/65861814/return-a-stream-from-a-function/65888784?noredirect=1#comment116518262_65888784

Instead of a ```stream``` we can use ```Future``` and this works perfectly fine.

Can you please add this to documentation in some way @rrousselGit. It will be useful for someone migrating from Bloc

**```
class SignInFormStateNotifier extends StateNotifier<SignInFormState> {
  final IAuthFacade _authFacade;

  SignInFormStateNotifier(this._authFacade) : super(SignInFormState.initial());

  Future handleEvent(SignInFormEvent event) async {
    event.map(
      // email changed
      emailChanged: (event) {
        state = state.copyWith(
          emailAddress: EmailAddress(event.email),
          authFailureOrSuccessOption: none(),
        );
      },
      // password changed
      passwordChanged: (event) {
        state = state.copyWith(
          password: Password(event.password),
          authFailureOrSuccessOption: none(),
        );
      },
      // register with email and password
      registerWithEmailAndPassword: (event) async {
        await _performActionWithEmailAndPassword(
          _authFacade.registerWithEmailAndPassword,
        );
      },
      // sign in with email and password
      signInWithEmailAndPassword: (event) async {
        await _performActionWithEmailAndPassword(
          _authFacade.signInWithEmailAndPassword,
        );
      },
      // sign in with Google
      signInWithGoogle: (event) async {
        state = state.copyWith(
          isSubmitting: true,
          authFailureOrSuccessOption: none(),
        );
        final result = await _authFacade.signInWithGoogle();

        state = state.copyWith(
          isSubmitting: false,
          authFailureOrSuccessOption: some(result),
        );
      },
    );
  }

  Future _performActionWithEmailAndPassword(
    Future<Either<AuthFailure, Unit>> Function({
      @required EmailAddress emailAddress,
      @required Password password,
    })
        action,
  ) async {
    Either<AuthFailure, Unit> result;
    final isEmailValid = state.emailAddress.isValid();
    final isPasswordValid = state.password.isValid();

    if (isEmailValid && isPasswordValid) {
      state = state.copyWith(
        isSubmitting: true,
        authFailureOrSuccessOption: none(),
      );

      result = await action(
        emailAddress: state.emailAddress,
        password: state.password,
      );

      state = state.copyWith(
        authFailureOrSuccessOption: some(result),
      );
    }
    state = state.copyWith(
      isSubmitting: false,
      showErrorMessages: true,
      authFailureOrSuccessOption: optionOf(result),
    );
  }
}
```**
