### ISSUE TITLE
[problem with VisibilityDetector?] Bad state: No ProviderScope found. Error thrown during a task callback.

### ISSUE THREAD

**Issue by peterweb2005** [rrousselGit/river_pod#2907]
only found in crash report, which i cant reproduce

## error log

Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Bad state: No ProviderScope found. Error thrown during a task callback.
       at ProviderScope.containerOf(framework.dart:107)
       at ConsumerStatefulElement.read(consumer.dart:613)
       at _ListHeaderWidget.build.<fn>(xx_page.dart:278)
       at VisibilityDetectorLayer._fireCallback(visibility_detector_layer.dart:263)
       at VisibilityDetectorLayer._processCallbacks(visibility_detector_layer.dart:222)
       at _TaskEntry.run(binding.dart:92)
       at SchedulerBinding.handleEventLoopCallback(binding.dart:515)
       at SchedulerBinding._runTasks(binding.dart:490)
       at TickerFuture.whenCompleteOrCancel.thunk(ticker.dart:420)

purpose of this code is to detect if the progress view container is visible, which this view is in a "list header"
else show center progress view

```dart
              // consume progress
              SizedBox(
                width: 24,
                height: 24,
                child: VisibilityDetector(
                  key: _progressViewVisiblityKey,
                  onVisibilityChanged: (VisibilityInfo visibilityInfo) {
                    log.finest('visibilityInfo: ', visibilityInfo);
                    final visible = visibilityInfo.visibleBounds != Rect.zero;
                    log.finest('visible: ', visible);
                    ref.read(progressViewVisibleProvider.notifier).state =
                        visible;
                  },
                  child: Consumer(builder: (context, ref, child) {
                    final progress =
                        ref.watch(requestProvider.select((e) => e.progress));
                    log.finest('progress: ', progress);
                    if (progress) {
                      final visible = ref.watch(progressViewVisibleProvider);
                      log.finest('visible: ', visible);
                      if (visible) {
                        return CircularProgressIndicator(
                            valueColor: AlwaysStoppedAnimation(
                                StyleUtil.getColorScheme().fg1));
                      }
                    }
                    return Container();
                  }),
                ),
              ),
```

**Comment by peterweb2005** [comment]
i guess, is that the view as a item in listview, is disposed? so no scope?

**Comment by rrousselGit** [comment]
if your widget got disposed, ref.read will throw, yes.

**Comment by rrousselGit** [comment]
It's similar to how using BuildContext throws on unmounted widgets

**Comment by peterweb2005** [comment]
no crash log,
but sorry, i think still need to notify the change event (as it really happened), otherwise lost

any tips?

**Comment by peterweb2005** [comment]
Sorry, forgot to tell how I resolved

1. keep notifier on init
2. on dispose, use that notifier,  so no need the ref
