### ISSUE TITLE
watch empty streamProvider.last throws exception

### ISSUE THREAD

**Issue by erf** [rrousselGit/river_pod#301]
**Describe the bug**

I get the following exception when i try to listen to `stream.last` of a `StreamProvider` which returns `Stream.empty`.

```
Exception has occurred.
StateError (Bad state: The stream was closed before emitting a value)
```

Example 1:

```
final myStreamProvider = StreamProvider<List>((ref) async* {
  yield* Stream.empty();
});

final myFutureProvider = FutureProvider<List>((ref) async {
  // THIS THROWS EXCEPTION
  return await ref.watch(myStreamProvider.last);
});
```

I also got the following error when trying to return a Firestore stream, which mapped to an empty list.

```
Exception has occurred.
StateError (Bad state: The provider was disposed the stream could emit a value)
```

Example 2:

```
final plansProvider = StreamProvider<List<Plan>>((ref) async* {
  final user = await ref.watch(userProvider.last);
  if (user == null) {
    yield [];
  } else {
    yield* FirebaseFirestore.instance
        .collection(Plan.collection)
        .where('userId', isEqualTo: user.uid)
        .snapshots()
        .asyncMap((snap) {
         // NOTE just for testing
        return <Plan>[];
    });
  }
});

final activePlanProvider = FutureProvider<Plan>((ref) async {
  // THIS THROWS EXCEPTION
  List<Plan> plans = await ref.watch(plansProvider.last);
  return plans == null || plans.isEmpty
      ? null
      : plans.firstWhere((plan) => plan.active, orElse: () => plans.first);
});
```

Note: I'm using the latest version `flutter_riverpod: ^0.13.0-nullsafety.1 ` which should have the `.last` fix.

Related to #272 and 9cfa39053ca96f49e85c5f5d22469d5851e92a93

**To Reproduce**

See examples above.

**Expected behavior**

I would expect a null value instead of an exception in the first example. 

In the second example i would except an empty list.

** Flutter doctor **

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.26.0-17.1.pre, on macOS 11.1 20C69 darwin-arm, locale en-NO)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by rrousselGit** [comment]
That's logical.
You yielded _nothing_. 

`.last` has nothing to return since the stream is closed and nothing was emitted.

**Comment by rrousselGit** [comment]
Instead of having your Stream never emit anything then close, have it emit `null`.

```dart
final myStreamProvider = StreamProvider<List>((ref) async* {
  yield null;
});
```

Then `last` will just return `null`, which you can gracefully handle

**Comment by erf** [comment]
That solves the first example. Do you know how to solve the second example (Firestore snapshot) without throwing an exception?

Not sure why it fails, because it should return a stream with an empty list, but i get the exception:

```
StateError (Bad state: The provider was disposed the stream could emit a value)
```

**Comment by rrousselGit** [comment]
> That solves the first example. Do you know how to solve the second example (Firestore snapshot) without throwing an exception?

It appears that your `where` causes your stream to emit nothing

You could do something like:

```dart
bool didEmit = false;
await for (final value in Firebase.instance...) {
  didEmit = true;
  yield value;
}

if (!didEmit) {
  yield null;
}
```

**Comment by davidmartos96** [comment]
@rrousselGit Is the error message formed as intended or is there a typo? From that message I wouldn't know what is really going on.
​StateError (Bad state: The provider was disposed the stream could emit a value)

**Comment by rrousselGit** [comment]
There's a typo. I forgot the word "before"

**Comment by erf** [comment]
I think I'd rather watch the provider for an `AsyncValue` in  my case, as your example seem a bit verbose and i usually get the Firebase stream using a helper method. 

It would not be possible to change the behavior of the Provider to avoid exceptions when streams emit nothing, to return a `null` value`?

Here is my solution that works, not using a generator function:

```
final plansProvider = StreamProvider<List<Plan>>((ref) {
  final userAsync = ref.watch(userProvider);
  return userAsync.when(
    data: (user) => StoreService.instance.subscribeToPlans(user.uid),
    loading: () => Stream.value([]),
    error: (error, stack) => Stream.value([]),
  );
});
```

**Comment by rrousselGit** [comment]
> It would not be possible to change the behavior of the Provider to avoid exceptions when streams emit nothing, to return a null value?

That would be bothersome with null-safety

**Comment by erf** [comment]
Ok, i can see you'd like to avoid null values with null-safety. I guess my `AsyncValue` solution is fine. Or just add a `try/catch` over the `watch`

**Comment by amitkot** [comment]
> > That solves the first example. Do you know how to solve the second example (Firestore snapshot) without throwing an exception?
> 
> It appears that your `where` causes your stream to emit nothing
> 
> You could do something like:
> 
> ```dart
> bool didEmit = false;
> await for (final value in Firebase.instance...) {
>   didEmit = true;
>   yield value;
> }
> 
> if (!didEmit) {
>   yield null;
> }
> ```

@rrousselGit would you recommend adding this code to every StreamProvider based on a source that might not yield values (i.e. basically all Firestore queries)?

**Comment by rrousselGit** [comment]
I would recommend not having a stream that doesn't emit

Firestore queries emit a snapshot even if there's no result.

**Comment by amitkot** [comment]
Why would the `where` call, in the second example, be a problem in this case then?
