### ISSUE TITLE
Create `whenDataAsync` on AsyncValue

### ISSUE THREAD

**Issue by Nolence** [rrousselGit/river_pod#303]
Hello !

I was wondering what you think about this being added to `AsyncValue` and as a way for users to get streams from them?

```dart
extension StreamMixin<T> on AsyncValue<T> {
  Stream<R> whenDataAsync<R>(Stream<R> Function(T data) cb) {
    return when(
      data: (value) {
        try {
          return cb(value);
        } catch (err, stack) {
          return Stream.error(err, stack);
        }
      },
      loading: () => Stream.empty(),
      error: (err, stack) => Stream.error(err, stack),
    );
  }
}
```
I found it useful in messing about with Streams for my own use. I personally don't think it would look out of place in the AsyncValue API too much considering it matchs almost one for one with `whenData`, and it would be of value to users who really need a stream from an AsyncValue.

One alternative is having a user `.when`  themselves and map each value to the appropriate Stream but that's personally bothersome I think. Other alternatives might deal with generator syntax (possibly using `.stream` or `.last` on a watched value) but those don't look as good IMHO or have subtle gotchas around Streams.

**Comment by rrousselGit** [comment]
That seem to be what `AsyncValue.guard` does:

```dart
AsyncValue.guard(() async {
  return await something();
}).asStream();
```

**Comment by Nolence** [comment]
By my understanding `guard` just wraps a `Future` and calling `asStream` transforms that single event `Future` into a `Stream`. I can use it to turn a `FutureProvider<T>` into a  `Stream<AsyncValue<T>>`

```dart
final intProvider = StreamProvider.autoDispose<int>((ref) {
  return intStream();
});

final addOneStreamProvider = Provider.autoDispose<Stream<AsyncValue<int>>>(
  (ref) {
    final lastInt = ref.watch(intProvider.last);

    return AsyncValue.guard(() async {
      final value = await lastInt;

      return value + 1;
    }).asStream();
  },
);
```

but `whenDataAsync` would instead be: given a `StreamProvider<T>` it returns `Stream<T>`. This transformation is the one I think I've wanted

```dart
final addOneStreamProvider = StreamProvider.autoDispose<int>((ref) {
  final value = ref.watch(intProvider);

  return value.whenDataAsync((value) => value + 1);
});
```

**Comment by cek-cek** [comment]
I am trying to figure out the solution for a similiar use case as in @Nolence's last example `addOneStreamProvider`, which is a provider providing transformed values from another `StreamProvider` (basically a genuine `Stream.map()`).

At least from the examples in the documentation, it seems that the `AsyncValue.*map` and `AsyncValue.*when` methods are intended for utilization in the UI and there's no straighforward way to retrieve simple `Stream` with all benefits & risks. I am aware of `StreamProvider.stream` but it types to `*ProviderBase`, from which I am not able to retrieve the actual stream.

If there is a way to achieve using the `AsyncValue.guard` or any other way, an example pattern would be greatly appreciated.

**Comment by Nolence** [comment]
Personally found this not helpful. I'm personally just avoiding most streams nowadays
