### ISSUE TITLE
Null Safety 

### ISSUE THREAD

**Issue by supposedlysam-bb** [rrousselGit/river_pod#305]
**Is your feature request related to a problem? Please describe.**
I would like to use `flutter_riverpod` with null safety on the beta channel.

**Describe the solution you'd like**
Create a prerelease version of `flutter_riverpod` by [migrating to null safety](https://dart.dev/null-safety/migration-guide)

**Describe alternatives you've considered**
I haven't really considered other alternatives.

**Additional context**
None

**Comment by rrousselGit** [comment]
There's already a null-safety version of flutter_riverpod published: 0.13.0-nullsafety.1
