### ISSUE TITLE
How many providers are needed? How to split them?

### ISSUE THREAD

**Issue by thomasthiebaud** [rrousselGit/river_pod#306]
Hej, first of all thanks a lot for your work: provider and riverpod are very accessible for someone new to flutter.

I'm building my first flutter app and I'm a bit struggling on how many providers I need. Let's consider an app with 2 screens:
- the first one is a list of items
- the second one is a detailed view of one of the item

I can create a Provider for my list of items like that

```
class _ListItemProvider with ChangeNotifier {
  List<Item> items = [];

  _ListItemProvider();

  Future<void> load() async {
    items = await getItems();
    notifyListeners();
  }

  Future<void> addItem(Item item) async {
    items.add(item);
    notifyListeners();
  }

  Future<void> deleteItem(Item item) async {
    //...
  }
}

final listItemProvider = ChangeNotifierProvider<_ListItemProvider>((ref) {
  return _ListItemProvider()..load();
});
```

Now if I click on an item I go the details screen where I can do some advance actions, for example add a description. I could create a function `addDescription` in  my `listItemProvider`, but that does not seems scalable because that means that all operations related to my items will be in the same provider. Alternatively I could create an `itemProvider` but if I add a function `addDescription` there, how do I make sure that the change is reflected in the list too?

It seems that BLOC is able to do it [like that](https://github.com/felangel/bloc/blob/master/examples/flutter_todos/lib/blocs/filtered_todos/filtered_todos_bloc.dart#L21-L25). 
In Redux I would dispatch an `UpdateDescriptionAction` action and catch it in two reducers, one for the details and one for the list.

I'm really not sure how to do that with provider/riverpod and the examples do not seem to cover that case. If this is not clear I can provide more details/more pseudo code.

**Comment by rrousselGit** [comment]
I'd suggest looking at the marvel example, which does such thing

TL:DR instead of storing a List<Item>, it stores a List<String> and use `family` to join the list of ids and the individual items.
