### ISSUE TITLE
Are getter Providers on instance models an anti-pattern?

### ISSUE THREAD

**Issue by Nolence** [rrousselGit/river_pod#319]
Hello !

I want to create providers on classes. The reason is that the specific instance has fields required by the provider. Not only that, but they are semantically related. Take for example I have a profile specific database.

```dart
class Database {
  final String path;

  const Database(this.path);

  void saveString(String value) {
    //
  }
}
```

I want to place the database provider on an instance of profile because the instance contains the path.

```dart
@freezed
abstract class Profile implements _$Profile {
  const Profile._();
  const factory Profile({
    required String displayName,
    required String databasePath,
  }) = _Profile;

  AutoDisposeProvider<Database> get dbProvider {
    return Provider.autoDispose<Database>(
      (ref) {
        // This already has access to databasePath
        return Database(databasePath);
      },
    );
  }

  // As I understand, this is the preferred way but requires I use a family
  // static final altDBProvider = Provider.autoDispose.family<Database, String>(
  //   (ref, path) {
  //     return Database(path);
  //   },
  // );
}
```

I've actually tried it and it does work but I'm curious if this breaks things in way that isn't immediate obvious with this small contrived example. As it's a getter, I don't think it's cached or is it? If this isn't a good thing to do, is `.family` the preferred alternative?

**Comment by rrousselGit** [comment]
Yes, this is anti-pattern.  

As you've said, getters aren't cached. That means you'll be creating the providers multiple times, which will point to different `Database` instances.

To begin with, storing a provider as property of `Profile` doesn't make sense. Might as well store the `Database` instance itself.

If you don't want to use `family` and have a single DB instance in your application, you can rely on overrides:

```dart
final dbProvider = Provider.autoDispose<Dabatase>((ref) => throw UnimplementedError());

Future<void> main() {
  runApp(
    ProviderScope(
      dbProvider.overrideWithValue(Dabatase('path')),
    ),
  );
}
```

**Comment by Nolence** [comment]
Yeah, sorry. Didn't really think that example through. My actual use case was for a `DocumentReference` from `Firestore` and the providers were just taking that reference and branching off it in order to get the correct `collection`:

```dart
// Inside Profile class
AutoDisposeStreamProvider get userBadgesProvider {
  return StreamProvider.autoDispose<Iterable<UserBadge>>(
    (ref) {
      return reference
          .collection('badges')
          .snapshots()
          .map<Iterable<UserBadge>>(
        (snapshot) {
          return snapshot.docs
              .map<UserBadge>((snapshot) => UserBadge.fromSnapshot(snapshot));
        },
      );
    },
  );
}
```

In any case, I think I'll just keep to `.family` and pass through the string path now that I know better.

Thanks Remi !
