### ISSUE TITLE
How to read Provider from pure dart classes without creating a new thread of providers

### ISSUE THREAD

**Issue by DebkanchanSamadder** [rrousselGit/river_pod#322]
In Riverpod Docs it says to read a provider from a flutter independent code we should use `ProviderContainer()` just like the test example shown.

But based off of [this](https://github.com/rrousselGit/river_pod/issues/310#issuecomment-774539840_) comment on issue #310 Creating an instance of `ProviderContainer()` will create a new 'thread' of Providers.

So how can we overcome this problem and share the same 'thread' of providers and work with them.

It can be useful for certain cases. For example `StateProvider` and we have to mutate it's state from a pure Dart service class.

**Comment by rrousselGit** [comment]
Was this closed on purpose?

Do you mind explaining the Dart service use-case? 

You should be able to obtain a ProviderReference instead.

**Comment by DebkanchanSamadder** [comment]
This was closed on purpose after successfully finding the answer that ProviderReference can be used for service use case.

If that doesn't suffice a global `ProviderContainer()` with `UncontrolledProviderScope` will do the trick.

**Comment by rrousselGit** [comment]
> If that doesn't suffice a global `ProviderContainer()` with `UncontrolledProviderScope` will do the trick.

I wouldn't recommend doing that

You should always rely on a ProviderReference/BuildContext. `ProviderContainer` is for low-level usages and rarely destined to be used directly.
