### ISSUE TITLE
A MultiProviderListener widget

### ISSUE THREAD

**Issue by e200** [rrousselGit/river_pod#325]
**Is your feature request related to a problem? Please describe.**
Adding 2 or more nested  **ProviderListener**s to the code to listen to multiple providers is becoming too verbose.

```dart
return ProviderListener<T>(
  provider: provider1.state,
  onChange: (context, value) {},
  child: ProviderListener<T>(
    provider: provider2.state,
    onChange: (context, value) {},
    child: ProviderListener<T>(
      provider: provider3.state,
      onChange: (context, value) {},
      child: child,
    ),
  ),
);
```

**Describe the solution you'd like**
Would be useful to have the **ProviderListener** child property made optional and to provide a new **SingleChildWidget** that accepts an array of ProviderListeners, like this:

```dart
MultiProviderListener(
  listeners: [
    ProviderListener<T>(
      provider: provider1.state,
      onChange: (context, value) {},
    ),
    ProviderListener<T>(
      provider: provider2.state,
      onChange: (context, value) {},
    ),
    ProviderListener<T>(
      provider: provider3.state,
      onChange: (context, value) {},
    ),
  ],
  child: Scaffold(),
);
```

This way we can fold the array to focus on the child making the code easy to follow.

**Comment by rrousselGit** [comment]
No

But https://github.com/rrousselGit/river_pod/issues/335 is in WIP and would lead to an even better solution.

**Comment by rrousselGit** [comment]
Closing in favor of #335
