### ISSUE TITLE
Document how context-dependent parameters should be passed to a provider constructor

### ISSUE THREAD

**Issue by derolf** [rrousselGit/river_pod#331]
Consider the following OLD Provider example, where some `context-dependent` parameter has to be passed to the constructor of some `Auth`-BLoC.

```Dart
Widget configureApp({required String authUrl}) {
  final auth = Auth(authUrl);

  return Provider.value(
    authUrl,
    child:  MyApp();
  );
}
```

Another one:

```Dart
class SomeWidget extends Widget {
  Widget build(BuildContext context) {
    final foo = Foo(some-value-that-depends-context); // could be as like Theme.of()
    return Provider.value(
      foo,
      child: BarWidget(),
    );
  }
}
```

How would that work with Riverpod?

**Comment by PoolTechnologie** [comment]
You could do something like this :

    void main() {
      runApp(ProviderScope(child: Myapp()));
    }
    /// your initial value
    final colorProvider = ScopedProvider<Color>((_) => Colors.black);
    
    class Myapp extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        return MaterialApp(
          home: Scaffold(
            body: ProviderScope(
              /// override your initial value with the context dependent value
              overrides: [colorProvider.overrideWithValue(Theme.of(context).primaryColor)],
              child: Myapp2(),
            ),
          ),
        );
      }
    }
    
    class Myapp2 extends ConsumerWidget {
      @override
      Widget build(BuildContext context, watch) {
        return Center(
          child: Container(
            height: 100,
            width: 100,
            /// this will be blue not black
            color: watch(colorProvider),
          ),
        );
      }
    }

**Comment by derolf** [comment]
Thanks!
