### ISSUE TITLE
UI doesn't rebuild when using select to watch a providers list

### ISSUE THREAD

**Issue by kjmj** [rrousselGit/river_pod#334]
**Describe the bug**
When using `select` to watch a providers list, the UI does not rebuild when adding an item to the list and calling `notifyListeners`.

**To Reproduce**
- There is a hacky solution of making a copy of the list, clearing it, and calling `notifyListeners` before adding the new item to the list.
- The UI rebuilds correctly when watching the entire provider without using `select`

```
import 'package:flutter/material.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:flutter_hooks/flutter_hooks.dart';

class ListProvider with ChangeNotifier {
  List<int> list = [];
  void add(int i) {
    /// uncomment the following lines and it works
    // List<int> copy = List.from(list);
    // list = [];
    // notifyListeners();
    // list = copy;

    list.add(i);
    notifyListeners();
  }
}

final listProvider = ChangeNotifierProvider<ListProvider>((ref) {
  return ListProvider();
});

void main() {
  runApp(
    const ProviderScope(child: MyApp()),
  );
}

class MyApp extends StatelessWidget {
  const MyApp();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: Home());
  }
}

class Home extends HookWidget {
  @override
  Widget build(BuildContext context) {
    /// note how useProvider without select works as expected
    // final List<int> list = useProvider(listProvider).list;
    final List<int> list = useProvider(listProvider.select((value) {
      return value.list;
    }));

    return Scaffold(
      appBar: AppBar(title: const Text('List example')),
      body: Center(
        child: Text(list.toString()),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => context.read(listProvider).add(1),
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

**Expected behavior**
I would expect for the UI to rebuild when watching a providers list using `select` without having to do anything "hacky".

I might be doing something totally wrong/missing something simple, but I can't figure out what might be happening here. Spent a few too many hours debugging with no luck.

**Comment by rrousselGit** [comment]
"select" relies on immutability to work.


If you want to trigger rebuilds with it, you need to clone the list instead of mutating it (like with provider)

**Comment by kjmj** [comment]
Got it. Do you have a preferred method of cloning the list?

**Comment by rrousselGit** [comment]
You can do:

```dart
list = [...list, newValue];
```
