### ISSUE TITLE
Migration Tooling

### ISSUE THREAD

**Issue by TimWhiting** [rrousselGit/river_pod#336]
A main problem developers seem to have with #335 is the breaking change that requires a lot of refactorings of code. I myself have a lot of libraries and applications that use riverpod. Developers can just stay on a previous version of riverpod until they have time to do the refactorings which will probably be because of necessity of some new feature of riverpod. However, the migration is a pretty straightforward and repetitive process, and should be able to be easily automated.

It would also help with the breaking changes that are being made in #302

@rrousselGit 
TLDR I'm willing to help create a migration tool so that you can spend more time with your devtool and the work required by these changes, but would like some guidance on your preferences on what solution to use for migration tooling.

There are several ways to create a migration tool.

- An easy way seems to be the [codemod package](https://pub.dev/packages/codemod) which provides an analysis context, and maybe some tools to do a migration with.
- Another option is to create an analyzer plugin as mentioned [here](https://github.com/rrousselGit/functional_widget/issues/14). This would probably be the best in terms of being able to use for other quick fixes and refactorings besides migration, but it isn't exactly tailored towards migration.
- The third way would be to use a new upcoming undocumented feature of dart seen recently in the dart sdk and flutter sdk. See for [example](https://github.com/flutter/flutter/pull/74866)(you have to expand the fix_data.yaml to see the magic) that seems to make breaking changes less breaking or provide migration tooling? I'm guessing/speculating we might hear more about this feature at Flutter Engage?

I'm still working on the documentation by the way, it turns out to be much harder than I thought to create good documentation. But I'll have a PR for documentation soon.

**Comment by rrousselGit** [comment]
That would be awesome! Thanks for the proposal

I would lean toward codemod. But the third option may be easier (assuming it is usable and flexible enough)

cc @filip @redbrogdon

**Comment by rrousselGit** [comment]
Closing since we have the tool now :clap:
