### ISSUE TITLE
Get Riverpod State Outside of Riverpod

### ISSUE THREAD

**Issue by searchy2** [rrousselGit/river_pod#337]
**Is your feature request related to a problem? Please describe.**
There is no way to get the state of Riverpod state objects globally or outside of the Riverpod method #335 
For example, with the boolean state below, is it possible to get the value in my own class?
```
final StateProvider<bool> premiumUser = StateProvider<bool>((ref) {
  return true;
});
```
In my class, I should be able to read the value.
```
class PremiumUserManager {
    bool isPremium;
    PremiumUserManager() {
        isPremium = premiumUser.state;
    }
}
```

**Describe the solution you'd like**
If the providers are declared globally, there should be a way to access their state without a context.

**Additional context**
This is an ancillary issue to my request to be able to get all app state.
The biggest painpoint with Riverpod and migrating to Riverpod is not having a context when a context is needed because context is no longer passed to the global Riverpod state when with Provider, context could be passed into the constructor of a ChangeNotifier.

**Comment by rrousselGit** [comment]
This is anti-pattern.

It is voluntary that the state of providers is not accessible globally. 

You could instead either:
- have your class receive `isPremium` as parameter
- pass `ProviderReference` to your class

**Comment by searchy2** [comment]
Thanks, that makes sense, I can close this issue. 
However, I would like an easy way to observe all the state at any point in time, not just the last notify change.

**Comment by rrousselGit** [comment]
I need to know more about what you're trying to do, as it may already be feasible

**Comment by searchy2** [comment]
Thanks Remi, please allow me to check my knowledge and see if I'm missing anything.

1. With context, getting the state is easy with context.read.
2. Inside providers, getting the state is easy with (ref).
3. However, refs must be passed explicitly through the constructor. If a ChangeNotifier is broken into 20 different ValueNotifiers, those 20 value notifiers need to be passed into the constructor of the ChangeNotifier. 
4. Outside of context and ref, there's no way to get a provider's value.

Is that correct? Thank you very much for your time sir.

**Comment by rrousselGit** [comment]
> However, refs must be passed explicitly through the constructor. If a ChangeNotifier is broken into 20 different ValueNotifiers, those 20 value notifiers need to be passed into the constructor of the ChangeNotifier.


I'm not sure what that means. If you pass `ProviderReference` to the class that wants to read provider, you have only a single parameter in the class constructor

> Outside of context and ref, there's no way to get a provider's value.


Correct

> * With context, getting the state is easy with context.read.
> * Inside providers, getting the state is easy with (ref).

Correct

**Comment by searchy2** [comment]
I was not aware that a ref could or should be passed as a constructor argument. 
That solves a lot of problems, thanks!
So instead of 
```
final ChangeNotifierProvider<PremiumPageParentModel> premiumPageParentChangeProvider =
    ChangeNotifierProvider<PremiumPageParentModel>((ref) {
  final optionalValueA = ref.watch(optionalAStateProvider);
  final optionalValueB = ref.watch(optionalBStateProvider);
  final optionalValueC = ref.watch(optionalCStateProvider);
  return PremiumPageParentModel(a: optionalValueA, b: optionalValueB, c: optionalValueC);
});
```
I can just pass a reference instead.
```
final ChangeNotifierProvider<PremiumPageParentModel> premiumPageParentChangeProvider =
    ChangeNotifierProvider<PremiumPageParentModel>((ref) {
  return PremiumPageParentModel(ref);
});

class PremiumPageParentModel extends ChangeNotifier {
    val optionalValueA;
    PremiumPageParentModel(ref) {
        value = ref.watch(optionalAStateProvider);
    }
}
```

Does the previous approach offer any advantages?

**Comment by TimWhiting** [comment]
You need to be careful not to use `ref.watch` except synchronously during the construction of the model. But you can use `ref.read` at any point in the model as long as you pass that in.

```dart

final ChangeNotifierProvider<PremiumPageParentModel> premiumPageParentChangeProvider =
    ChangeNotifierProvider<PremiumPageParentModel>((ref) {
// Do your ref.watches here
  return PremiumPageParentModel(ref.read);
});

class PremiumPageParentModel extends ChangeNotifier {
    Reader read;
    PremiumPageParentModel(this.read);
    
    Future<void> doSomething() async {
      // Gets the latest config from myConfigProvider
      final someConfig = read(myConfigProvider);
      // Do some async work / call an api using config
    }
}
```

**Comment by searchy2** [comment]
Thank you @TimWhiting for clarifying the incorrect usage. 
So watch should be inside the provider while reads can be passed into the model. :ok_hand:

**Comment by searchy2** [comment]
Related usage clarification: https://github.com/rrousselGit/river_pod/issues/295#issuecomment-770368812
