### ISSUE TITLE
Get All Riverpod State

### ISSUE THREAD

**Issue by searchy2** [rrousselGit/river_pod#338]
**Is your feature request related to a problem? Please describe.**
There is no way to get the entire app state at a point in time. ProviderObserver is not enough as it only tracks providers that emit a change.
For example, I have a ChangeNotifier class with a few transient values.
```
class SettingsPageModel extends ChangeNotifier {
    int sliderValueTemporary = 0;

    void setSliderValueTemporary(int value) {
        sliderValueTemporary = value;
    }
}
```
NotifyListeners is never called because the `sliderValueTemporary` is transient. SettingsPageModel is accessible through a ChangeNotifierProvider so that state is somewhere. The value of `sliderValueTemporary` can be accessed with `context.read(settingsPageChangeProvider).sliderValueTemporary`.
Can it be made more accessible?

Also, ProviderObservers doesn't expose the entire app state and trying to use it to track app state involves saving all the state to a map manually. Instead, the app state is already somewhere inside Riverpod so it should be made accessible.

**Describe the solution you'd like**
There should be a way to iterate through a list of all Riverpod states.
Ideally, this list could be pulled internally from Riverpod without any manual list population. 
The API would be a method called `getAllStates()` and return a map of all state models and values.

**Additional context**
Related to #337

**Comment by rrousselGit** [comment]
What is the use-case?

**Comment by searchy2** [comment]
100% observability for the entire app. Being able to load and save state snapshots.
Very helpful for analytics, troubleshooting, and error reporting.

For example, if an error is thrown, I can automatically take a snapshot of the app states leading up to the error.
If a user is experiencing an error, I can snapshot their app state and clone it to my app to help them troubleshoot. 

For development and debugging, snapshots of screens are automatically saved to our storyboard and can be viewed to show the different states a page could be in. 

Analytics, for finegrained usage stats and syncronizing heatmaps / taps with app state.

**Comment by rrousselGit** [comment]
> Being able to load and save state snapshots.

How would you know which state is associated to which provider inside your snapshot?

> , if an error is thrown, I can automatically take a snapshot of the app states leading up to the error.

How would you detect that a provider threw an error?

> For development and debugging, snapshots of screens are automatically saved to our storyboard and can be viewed to show the different states a page could be in

For development, there is `ProviderContainer` that has a few debug-only properties exposing the current state

**Comment by searchy2** [comment]
> How would you know which state is associated to which provider inside your snapshot?
Providers have a name parameter that can be used right?

> How would you detect that a provider threw an error?
By running the code in a zone, when an error is thrown, I can go in and fetch the state.

> For development, there is ProviderContainer that has a few debug-only properties exposing the current state
The reporting capability should be available in production.

**Comment by rrousselGit** [comment]
You can use `ProviderContainer.getAllProviderElements` so this can be closed

**Comment by searchy2** [comment]
Amazing @rrousselGit !!
