### ISSUE TITLE
Add an equivalent to ProviderListener that works inside providers

### ISSUE THREAD

**Issue by derolf** [rrousselGit/river_pod#339]
Use-case: A Provider wants to do some work whenever another Provider changes. I came up with following solution:

```Dart
final dateTimeProvider = Provider<DateTime>((ref) => DateTime.now());

void refreshDateTimeProvider(ProviderReference ref) => ref.container.refresh(dateTimeProvider);

final sendDateTimeProvider = Provider.family((ref, String target) async {
  final ws = await WebSocket.connect(target);
  final sub = ref.container.listen<DateTime>(dateTimeProvider, mayHaveChanged: (sub) {
    ws.add(sub.read().toString());
  });
  ref.onDispose(sub.close);
});
```

Is that the proper approach?

**Comment by rrousselGit** [comment]
There's no official solution for listening a provider from another provider yet.

`ProviderContainer.listen` works but is more of a workaround. There are separate WIP (https://github.com/rrousselGit/river_pod/pull/302 for example) that adds a `ref.listen`

**Comment by derolf** [comment]
Okay, I was unsure since it indeed looks a bit esoteric to me right now...

**Comment by rrousselGit** [comment]
Closing in favor of #335
