### ISSUE TITLE
The argument type 'ProviderListenable<bool>' can't be assigned to the parameter type 'ProviderBase<Object, dynamic>'.

### ISSUE THREAD

**Issue by hejunbinlan** [rrousselGit/river_pod#347]
@override
  Widget build(BuildContext context, ScopedReader watch) {
    final isAdult = watch(personProvider.select((p) => p.age >= 18));
    return Text('$isAdult');
  }

compile error:
The argument type 'ProviderListenable<bool>' can't be assigned to the parameter type 'ProviderBase<Object, dynamic>'.

**Comment by rrousselGit** [comment]
This is expected. `watch(provider.select)` is not implemented yet. Only `useProvider(provider.select)` is supported at the moment.

**Comment by t1ooo** [comment]
Any updates?

**Comment by rrousselGit** [comment]
This works on the dev release.
