### ISSUE TITLE
How to debounce provider chains/"processing pipelines"

### ISSUE THREAD

**Issue by davebound** [rrousselGit/river_pod#352]
Hi Remi - thanks for this excellent library. I've been using it for several months now but there's one thing I just can't seem to figure out.

There is an example in 

[https://felixblaschke.medium.com/riverpod-simplified-an-introduction-to-flutters-most-advanced-state-management-package-c698b4d5a019](url)

that shows how two providers can be set up in a chain whereby one provider in the chain "greeting" can behave as a "combiner" of two "source" providers - name and age.

How would one go about debouncing such that the output of combiner changes at most once per second even though name or age changed many times per second

**Comment by rrousselGit** [comment]
Why would you debounce the combination? You probably should debounce the name/age update instead.

**Comment by davebound** [comment]
Well, yes, that would probably be better, but its not the main concern of my question. A little more detail....

In my case, **name**, **age** and **combiner** are all ChangeNotifierProviders. (**name** and **age** hold the state of some UI)

So if **name** or **age** providers change, they call  notifyListeners(). The UI is listening and updates immediately, which is what I want.

However, the **combiner** provider is dependent on both **age** and **name** providers and therefore also rebuilds immediately when notifyListeners() is called and I don't want that because **combiner** fetches data from server api

It feels like I need to insert an intermediate provider in the chain somewhere to do some debouncing?

**Comment by TimWhiting** [comment]
Feels like your chain needs inverting. Why can't the combiner provider just read * not watch * the states of age and name at the moment it needs them? Or that server fetching needs to move to someplace higher in the chain.

**Comment by davebound** [comment]
Thanks Tim, but I'm not sure what you mean. Combiner is definitely dependent on age and name. (In reality, **age** and **name**  have  UI that specify filter options (checkboxes/text fields) for what the combiner should fetch from server).

I might be missing something but I can't see how this would work the other way up?

**Comment by davebound** [comment]
![image](https://user-images.githubusercontent.com/18735591/109349112-53f0f200-786d-11eb-9196-85049173ac64.png)

**Comment by TimWhiting** [comment]
Okay, I see. In that case can you do something like this:
```dart

final dataFetcher = Provider((ref) => DataFetcher());

class DataFetcher {
  Future<Object> fetchData(String name, int age) {}
}

final combiner = ChangeNotifierProvider((ref) => Combiner(ref.read));

class Combiner extends ChangeNotifier {
  Combiner(this.read) {
    resetTimer();
  }
  int _age = 20;
  String _name = 'Dave';
  Timer _timer;
  Object apiResult;
  Reader read;

  void resetTimer() {
    _timer.cancel();
    _timer = Timer(const Duration(seconds: 1), _callApi);
  }

  set name(String name) {
    _name = name;
    notifyListeners();
  }

  String get name => _name;

  set age(int age) {
    _age = age;
    notifyListeners();
    resetTimer();
  }

  int get age => _age;

  Future<void> _callApi() async {
    apiResult = await read(dataFetcher).fetchData(_name, _age);
  }
}

final ageProvider = Provider((ref) => ref.watch(combiner).age);
final nameProvider = Provider((ref) => ref.watch(combiner).name);

```

**Comment by rrousselGit** [comment]
If it's a debounce that you want, you could do:

```dart
class CancelledError implements Error {}


final provider = FutureProvider<User>((ref) async {
  final completer = Completer<void>();
  ref.onDispose(() {
    if (!completer.isCompleted) completer.completerError(CancelledError());
  });
  
  Future<void>.delayed(Duration(seconds: 1)).then((value) {
    if (!completer.isCompleted) completer.completer();
  });

  await completer.future;

  final name = ref.watch(whatever).name;
  final age = ref.watch(whatever).age;

  final something = await fetchSomething(user, name);
  return something;
}
```


that should implement a debounce

**Comment by rrousselGit** [comment]
You could even extract the setup in a reusable function:

```dart
Future<void> denounce(Duration duration, ProviderReference ref) {
  final completer = Completer<void>();
  ref.onDispose(() {
    if (!completer.isCompleted) completer.completerError(CancelledError());
  });
  
  Future<void>.delayed(Duration(seconds: 1)).then((value) {
    if (!completer.isCompleted) completer.completer();
  });

  return completer.future;
}

final provider = FutureProvider<User>((ref) async {
  await debounce(Duration(seconds: 1), ref);

  final name = ref.watch(whatever).name;
  final age = ref.watch(whatever).age;

  final something = await fetchSomething(user, name);
  return something;
}
```

**Comment by davebound** [comment]
> Okay, I see. In that case can you do something like this:
> 
> ```dart
> final dataFetcher = Provider((ref) => DataFetcher());
> 
> class DataFetcher {
>   Future<Object> fetchData(String name, int age) {}
> }
> 
> final combiner = ChangeNotifierProvider((ref) => Combiner(ref.read));
> 
> class Combiner extends ChangeNotifier {
>   Combiner(this.read) {
>     resetTimer();
>   }
>   int _age = 20;
>   String _name = 'Dave';
>   Timer _timer;
>   Object apiResult;
>   Reader read;
> 
>   void resetTimer() {
>     _timer.cancel();
>     _timer = Timer(const Duration(seconds: 1), _callApi);
>   }
> 
>   set name(String name) {
>     _name = name;
>     notifyListeners();
>     resetTimer();
>   }
> 
>   String get name => _name;
> 
>   set age(int age) {
>     _age = age;
>     notifyListeners();
>     resetTimer();
>   }
> 
>   int get age => _age;
> 
>   Future<void> _callApi() async {
>     apiResult = await read(dataFetcher).fetchData(_name, _age);
>     notifyListeners();
>   }
> }
> 
> final ageProvider = Provider((ref) => ref.watch(combiner).age);
> final nameProvider = Provider((ref) => ref.watch(combiner).name);
> final apiResultProvider = Provider((ref) => ref.watch(combiner).apiResult);
> ```
> 
> (This is what I meant about inverting dependencies).
> I've found it best to have my server APIs at the top of the tree. I'm not sure if that is what Remi recommends though.

Ha! Thanks Tim - first thing I did when I saw your code was to turn it the other way up lol. And as for age 20.....well I wish!

Looks like it might work but it feels like Combiner is now the "home" of age and name, but in reality they are existing providers in their own right. Will give it some more thought but I learnt quite a bit from your example, so thanks for that.

**Comment by TimWhiting** [comment]
@davebound 
I think that Remi's latest solution is more close to what you want, but glad you learned something from my code.

**Comment by davebound** [comment]
> You could even extract the setup in a reusable function:
> 
> ```dart
> Future<void> debounce(Duration duration, ProviderReference ref) {
>   final completer = Completer<void>();
>   ref.onDispose(() {
>     if (!completer.isCompleted) completer.completerError(CancelledError());
>   });
>   
>   Future<void>.delayed(Duration(seconds: 1)).then((value) {
>     if (!completer.isCompleted) completer.completer();
>   });
> 
>   return completer.future;
> }
> 
> final provider = FutureProvider<User>((ref) async {
>   await debounce(Duration(seconds: 1), ref);
> 
>   final name = ref.watch(whatever).name;
>   final age = ref.watch(whatever).age;
> 
>   final something = await fetchSomething(user, name);
>   return something;
> }
> ```

Thanks Remi - neat - my first experience of Completer - but it isn't quite the debounce I need. 

fetchSomething() gets called 1 second after the *first* change of name or age, but I need it to get called 1 sec after the *last* change to name or age. How to do that?

**Comment by rrousselGit** [comment]
> fetchSomething() gets called 1 second after the first change of name or age, but I need it to get called 1 sec after the last change to name or age. How to do that?

That's what my snippet should do

**Comment by davebound** [comment]
It works if I put the call to debounce() *after* the ref.watch calls.

Without that, onDispose() never gets called during the debounce interval (should age or name change) and therefore the completer doesn't get cancelled when name or age change.

Makes sense to me or am I misunderstanding something?

**Comment by davebound** [comment]
Here's my working code:

`
// ---------------------------------------------------------------------------
// Notifies when request search options change
// ---------------------------------------------------------------------------
final gProvReqSearchOptions = ChangeNotifierProvider<ReqSearchOptionsNotifier>(
  (ref) {
    if (glog) gl.i('CREATING PROVIDER gProvReqSearchOptions');

    ref.onDispose(() {
      if (glog) gl.c('DISPOSING PROVIDER gProvReqSearchOptions');
    });

    final ret = ReqSearchOptionsNotifier();
    if (glog) gl.o();
    return ret;
  },
);

// ---------------------------------------------------------------------------
// Notifies when selected ReqType chips changes
// ---------------------------------------------------------------------------
final gProvSelectedReqTypes = ChangeNotifierProvider<SelectedReqTypesNotifier>(
  (ref) {
    if (glog) gl.i('CREATING PROVIDER gProvSelectedRequestTypes');

    ref.onDispose(() {
      if (glog) gl.c('DISPOSING PROVIDER gProvSelectedRequestTypes');
    });

    final ret = SelectedReqTypesNotifier();
    if (glog) gl.o();
    return ret;
  },
);

// -----------------------
// Combiner Filter Provider 
// -----------------------
class CancelledError implements Error {
  @override
  StackTrace get stackTrace => null;
}

final gProvFilterCombiner = FutureProvider<ReqPageFilterCombinerNotifier>(
  (ref) async {
    if (glog) gl.i('CREATING PROVIDER gProvFilterCombiner');

    final notifReqSearchOptions = ref.watch(gProvReqSearchOptions);
    final notifSelectedReqTypes = ref.watch(gProvSelectedReqTypes);

    // DEBOUNCE
    //await debounce(Duration(milliseconds: 5000), ref);
    {
      final completer = Completer<void>();

      // Want it to dispose after every filter options change
      ref.onDispose(() {
        if (!completer.isCompleted) {
          completer.completeError(CancelledError());
        }
      });

      Future<void>.delayed(Duration(seconds: 5)).then((value) {
        if (!completer.isCompleted) {
          completer.complete();
        }
      });

      await completer.future;
    }

    ReqPageFilterCombinerNotifier ret = ReqPageFilterCombinerNotifier(ref.read, notifReqSearchOptions, notifSelectedReqTypes, true);
    if (glog) gl.o();
    return ret;
  },
);

`

**Comment by rrousselGit** [comment]
Oh you're right, you need to watch the providers before the debounce

**Comment by davebound** [comment]
Thanks Remi and @TimWhiting
