### ISSUE TITLE
Error running pub get with flutter_riverpod: ^0.13.0

### ISSUE THREAD

**Issue by dean1walsh** [rrousselGit/river_pod#360]
I get this error when running pub get.

-- [projectname] flutter pub get
Running "flutter pub get" in [projectname]                 
Because every version of integration_test from sdk depends on meta 1.3.0-nullsafety.6 and flutter_riverpod >=0.13.0 depends on meta ^1.3.0, integration_test from sdk is incompatible with flutter_riverpod >=0.13.0.

So, because [projectname] depends on both flutter_riverpod ^0.13.0 and integration_test any from sdk, version solving failed.
pub get failed (1; So, because [projectname] depends on both flutter_riverpod ^0.13.0 and integration_test any from sdk, version solving failed.)
exit code 1 --

Can you please help me. I cannot install riverpods

**Comment by joanofdart** [comment]
flutter_riverpod 0.13++ is null safe, which means, you are required to enable null-safety.

**Comment by rrousselGit** [comment]
Do you still have the problem?

**Comment by rrousselGit** [comment]
Closing in the lack of an answer
