### ISSUE TITLE
[proposal] allow `hooks_riverpod` to wider access to `flutter_hooks` and `riverpod` classes and functions

### ISSUE THREAD

**Issue by iapicca** [rrousselGit/river_pod#362]
I don't know if this is intended, but 
`hooks_riverpod: ^0.13.1` requires `flutter_hooks: ^0.16.0` to access
- `HookWidget`
- `useEffect`
- `StateController`

and probably many more,
it would be convenient to have these accessible from a single package

(sorry, for the wrong labels)

**Comment by kranfix** [comment]
It could be easier to use, but not modular.
