### ISSUE TITLE
How do use didChangeAppLifecycleState with Riverpod ?

### ISSUE THREAD

**Issue by vppysk** [rrousselGit/river_pod#363]
I'm using `didChangeAppLifecycleState` to call the function when `AppLifecycleState state == AppLifecycleState.resumed.`
Also, I’m using MVVM architecture with riverpod.

Currently, my code is as follows

home.dart(View)
```
class _HomeScreenState extends State<HomeScreen> with WidgetsBindingObserver {

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) async {
    if (state == AppLifecycleState.resumed) {
      await context.read(homeViewModelProvider).setData();
    }
  }

```

home_view_model.dart(ViewModel)
```
final homeViewModelProvider = Provider<HomeViewModel>((ref) {
  return HomeViewModel();
});

class HomeViewModel {

  Future<void> setData() async {
     // abbreviation
    );
  }

}
```

But, I'm getting the following error at `context.read`
`A member named 'read' is defined in extensions 'BuildContextX' and 'ReadContext' and neither is more specific.
Try using an extension override to specify the extension you want to to be chosen`

<img width="821" alt="スクリーンショット 2021-03-09 19 27 33" src="https://user-images.githubusercontent.com/33174374/110457002-87edd200-810d-11eb-8b3e-5e26e72cba2e.png">

I can't find this solution in the documentation or other articles.
Could you please help me ? Thank you in advance.

**Comment by rrousselGit** [comment]
It seems like you have imported both provider and riverpod at the same time

Remove the provider import and that should fix the issue

**Comment by vppysk** [comment]
@rrousselGit Thank you for your answer !

Yes, I'm using provider as old_provider.
My product is in the process of migrating from provider to riverpod, and I need to use old_provider.

Is there any way to solve this problem without remove the provider ?

**Comment by rrousselGit** [comment]
You can do:

```dart
import 'package:provider/provider.dart' as old_provider hide ReactContext;
```

**Comment by vppysk** [comment]
It's fixed!
In my case, I needed to write the following
```dart
import 'package:provider/provider.dart' as old_provider hide ReadContext;
```

Thank you so much !
