### ISSUE TITLE
Change state without context

### ISSUE THREAD

**Issue by rahuldange09** [rrousselGit/river_pod#364]
**Describe the bug**
How can I change the StateNotifierProvider state without context?
For eg. I have a Cart Page and I want to update it when the address changes but I don't have access to BuildContext there.
So how can I update the state of cartProvider?

```dart
final providerContainer = ProviderContainer();
    if (isCheckout) {
      await providerContainer.read(cartProvider).updateCartItem();
}
```

  
I tried ProviderContainer but I guess it doesn't help in changing the state.

Please help me with this.

**Comment by smiLLe** [comment]
Can you provide more code so that we can understand where you want to access the cartProvider?

**Comment by rrousselGit** [comment]
You cannot and should not change state without a variable obtained from somewhere else.

You will either need a BuildContext or a ProviderReference.

It is very rare that you should create a ProviderContainer yourself.
