### ISSUE TITLE
Add simple way to read a ProviderListenable

### ISSUE THREAD

**Issue by derolf** [rrousselGit/river_pod#365]
`select` provides a handy way to get a subset of state:

```Dart
final openTodos = todos.select((_) => _.where((_) => _.isOpen));`
```

The following should work:

```Dart
ProviderContainer c = ...
final openTodos = c.read(openTodos);
```

Ugly workaround:

```Dart
extension ProviderContainerExt on ProviderContainer {
  Result readListenable<Result>(ProviderListenable<Result> listenable) {
    final sub = listen(listenable);
    try {
      return sub.read();
    } finally {
      sub.close();
    }
  }
}
```

**Comment by rrousselGit** [comment]
I wouldn't recommend reusing `.select`

Instead make a provider for it if you want to reuse it.

**Comment by derolf** [comment]
What's the downside of using `select` as a shorthand for creating a full provider?

**Comment by rrousselGit** [comment]
the computation of `select` is not shared between widgets. So if two widget read the same select, that performs the `where` twice
But with a provider, that computation is shared and the where would be performed once.

**Comment by derolf** [comment]
I understand your concerns, but there might be also benefits of using a lightweight select instead of a full provider.

Is there a better way to read a listenable than may workaround?

**Comment by rrousselGit** [comment]
There is no reading to "read" a `select`

What you're doing is no different from:

```dart
container.read(todos).where((t) => t.isOpen);
```

There's no reason to use `select` here.


If you want to share code, consider extending your state object instead:

```dart
extension on List<Todo> {
  Iterable<Todo> open() => this.where((t) => t.isOpen);
}

container.read(todos).isOpen;
```

**Comment by rrousselGit** [comment]
Closing in favor of #335 which will deal with this
