### ISSUE TITLE
Error: setState() or markNeedsBuild() called during build.

### ISSUE THREAD

**Issue by Patrick386** [rrousselGit/river_pod#366]
I want to save the state according to the stream result, and change the ui.

I want to change the floatingActionButton's icon according to its state. However, the problem arises because the state cannot be changed while using the stream. Is there any way?

**StreamProvider:**
```
final AutoDisposeStreamProvider companyDBStreamProvider =
    StreamProvider.autoDispose<DocumentSnapshot>(
        (ref) => companyCollectionRef.doc(userCompanyID).snapshots());
```
**StateNotifier:**
```
  setStreamToMode(DocumentSnapshot doc) {
    if (doc.data() == null) 
    {
       state = DataIsEmpty();
    } else {
       state = DataLoaded();  // **<<< state change**
    }
  }


  getStreamCompanyData() {
    final steam = read(companyDBStreamProvider);
    try {
      steam.when(
          data: (data) => data == null ? print('null') : setStreamToMode(data),
          loading: () => print('Loading...getStreamCompanyData'),
          error: (err, stack) => print('error'));
      return state;
    } on DataException catch (e) {
      print('Company fetch data error: $e');
      state = DataError(e.toString());
    } on Error catch (e) {
      print('Company error : $e');
      state = DataError(e.toString());
    }
  }
```

**Screen**
class CompanyMainScreen extends HookWidget {
  final GlobalKey<ScaffoldState> _scaffoldKey = new GlobalKey<ScaffoldState>();

  bool _dataOn = false;

  @override
  Widget build(BuildContext context) {
  
    final _state =
        useProvider(CompanyDataNotifierProvider).getStreamCompanyData();

    return Scaffold(
        key: _scaffoldKey,
        endDrawer: DrawerShow(_dataOn),
        body: Container(
          color: Colors.white,
          child: Padding(
            padding: const EdgeInsets.all(40.0),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Container(
                    color: Colors.white,
                    child: useProvider(companyDBStreamProvider).when(
                      data: (doc) {
                          try {
                          var data = CompanyModel.fromSnapshot(doc);
                          useProvider(CompanyDataNotifierProvider)
                              .setDataState(data);
                          _dataOn = true;                     
                          return DataShow(data,  _scaffoldKey); 
                        } on Error catch (e) {
                                                
                          _dataOn = false;
                          Future.delayed(Duration.zero, () async {
                            showWarningSnackBar(context, e.toString());
                          });
                          return IsNotCompanyData( _scaffoldKey); 
                        }
                      },
                      loading: () => Center(
                          child: Container(
                        child: CircularProgressIndicator(),
                        width: 50,
                        height: 50,
                      )),
                      error: (err, stack) =>
                          showWarningSnackBar(context, err.toString()),
                    ) // provider when end

                   ),

               ],
            ),
          ),
        ),
        floatingActionButton: CustomFloatingActionButton(_scaffoldKey));
  }
}

class CustomFloatingActionButton extends HookWidget {
  GlobalKey<ScaffoldState> _scaffoldKey;
  CustomFloatingActionButton(this._scaffoldKey);
  @override
  Widget build(BuildContext context) {
    final _state = useProvider(CompanyDataNotifierProvider.state); //**<<< error setState()**
    return FloatingActionButton(
      child: _state is DataLoaded ? Icon(Icons.mode_outlined) : Icon(Icons.add),
      backgroundColor: Colors.grey,
      onPressed: () {   
        _scaffoldKey.currentState!.openEndDrawer();
      },
    );
  }
}

**Comment by rrousselGit** [comment]
This is not how StateNotifier is supposed to be used.

Do not expose functions/getters to access its state. Do `useProvider(stateNotifierProvider.state)`

**Comment by Patrick386** [comment]
Thank you for the quick answer. Is the method of checking the state and storing the data in StateNotifier correct?

**Comment by rrousselGit** [comment]
All your state should be stored exclusively inside `StateNotifier.state`. You should not have state outside of this `state` property

**Comment by Patrick386** [comment]
It works very well. ^^ If so, can you recommend using stream inside StateNotifier? I want to store the stream result and keep all state as one.
