### ISSUE TITLE
How to spin off demon/background processes that operate on providers?

### ISSUE THREAD

**Issue by derolf** [rrousselGit/river_pod#368]
Simple (abstracted) example:

`final weatherProvider = ... listens to position and provides current weather at position`

How would I implement and launch a demon that watches the `weatherProvider` and calls the TTS plugin to speak the weather whenever the weather changes?

**Comment by rrousselGit** [comment]
You should have a `Stream` built from EventChannel/MethodChannel somewhere that interact with native code

You should be able to plug that stream on a StreamProvider

**Comment by rrousselGit** [comment]
I'll close this since this is a bit too broad and lacks activity
