### ISSUE TITLE
Quickstart Guide for Marvel example

### ISSUE THREAD

**Issue by neiljaywarner** [rrousselGit/river_pod#369]
**Describe what scenario you think is uncovered by the existing examples/articles**
The Marvel example seems like it will be really amazingly good for what people actually need, but it doesn't seem to "just work" - I think it has somethign to do with freezd maybe since getting 
"lib/src/fake_marvel.dart:5:6: Error: Error when reading 'lib/src/fake_marvel.g.dart': No such file or directory
part 'fake_marvel.g.dart';
     ^
lib/src/marvel.dart:19:6: Error: Error when reading 'lib/src/marvel.freezed.dart': No such file or directory
part 'marvel.freezed.dart';
**Describe why existing examples/articles do not cover this case**
Explain which examples/articles you have seen before making this request, and
why they did not help you with your problem.

**Additional context**
Add any other context or screenshots about the documentation request here.

**Comment by AlexHartford** [comment]
Did you run the generator? Freezed generates files using build_runner. Try running this command from the root of the project:

`flutter pub run build_runner build`

You may have to reload your editor to help the linter catch up.

**Comment by neiljaywarner** [comment]
I'm sure that will work I'm just saying mains documentation could clear that up if someone is new to dart/flutter/code gen like that
