### ISSUE TITLE
[Question] How can I overrideWithProvider a StateProvider?

### ISSUE THREAD

**Issue by ManuLpz4** [rrousselGit/river_pod#381]
Hi guys, hope you are doing well :)

I've been working on an ID verification flow and I achieved it, but now I want to clean the code with the help of riverpod and I'm facing the following issue:

### What I want
```dart
final fileProvider = StateProvider<XFile>((_) {
  throw UnimplementedError('XFile not provided.');
});

final frontFileProvider = StateProvider<XFile>((_) => null);

final backFileProvider = StateProvider<XFile>((_) => null);

final selfieFileProvider = StateProvider<XFile>((_) => null);

// ...

ProviderScope(
  overrides: [
    fileProvider.overrideWithProvider(frontFileProvider),
  ],
  child: const FrontPage(),
);

```

### Why I want this approach
I want this approach because I have a front/back/videoSelfie page and a CameraShutter widget that reads the fileProvider and works with that information.
**MAYBE** I'm not understanding or covering the problem correctly, I am open to new ideas of course.
Please and thank you so much :)

### The exception
```
Unsupported operation: Cannot override providers on a non-root ProviderContainer/ProviderScope
```

**Comment by TimWhiting** [comment]
Use a family https://riverpod.dev/docs/concepts/modifiers/family

The argument to family will be an enum probably for (Front/Back/Selfie)

**Comment by ManuLpz4** [comment]
@TimWhiting thank you for the response. Sadly, I read the documentation and tried implementing it but I don't understand what the logic would be like. How does (for example) the CameraShutter know what enum is on top of it?

**Comment by TimWhiting** [comment]
If you want to not have it auto dispose then just don't add the auto dispose modifier. (I don't think keeping up to 3 XFiles around for the duration of the app will take up much memory). Looks like you are headed the right direction. 👍

**Comment by ManuLpz4** [comment]
Great! So for people who are facing the same problem I will leave the code that I'm using so that they understand the solution.
Thank you so much for the help, @TimWhiting 💙

### Parent page
```dart
final kycMediaTypeProvider = ScopedProvider<KycMediaType>((_) {
  throw UnimplementedError('KycMediaType not provided.');
});

final fileProvider = StateProvider.family.autoDispose<XFile, KycMediaType>(
  (_, type) {
    switch (type) {
      case KycMediaType.front:
        return null;
      case KycMediaType.back:
        return null;
      case KycMediaType.videoSelfie:
        return null;
      default:
        throw UnsupportedError('$type not supported.');
    }
  },
);

// ...

Consumer(
  builder: (_, ScopedReader watch, __) {
    // Watching every KycMediaType to avoid unwanted early disposing because
    // there was no watch(fileProvider) in this file.
    for (final KycMediaType type in KycMediaType.values) {
      watch(fileProvider(type));
    }
  
    return PageView(
      controller: watch(pageControllerProvider),
      physics: const NeverScrollableScrollPhysics(),
      children: const [
        PreVerificationPage(),
        FrontPage(),
        BackPage(),
        SelfiePage(),
      ],
    );
  },
),
```

### Each "children" page
```dart
ProviderScope(
  overrides: [
    // You can do this override dynamically if you need.
    kycMediaTypeProvider.overrideWithValue(KycMediaType.front),
  ],

// ...
```

**Comment by JoseGeorges8** [comment]
Sorry but this doesn't really make sense to me? how's the solution even using the state provider? It just listens to it but there's no use of the value
