### ISSUE TITLE
Alternative to provider.when...

### ISSUE THREAD

**Issue by wazini-john** [rrousselGit/river_pod#382]
Looking for an alternative to 

```

@override
  Widget build(BuildContext context) {
     final _user = useProvider(MyUserProvider);
       ...
return _user.when(data: data, loading: loading, error: error)
```
for most of my components

I want to use sth like

```
final _user = useProvider(MyUserProvider);
// then
return Text(_user.name)
```
directly because the firebase user data stream is already in the tree and can never be `null` or have an error.

**MyUserProvider is a Stream**

1. Can I use a ChangeNotifier to achieve this ?
2. How else can I achieve this ?

**Comment by rrousselGit** [comment]
You could do:

```dart
final user = useProvider(myProvider).data?.value;
```


where `data` will be null during load/errors.
