### ISSUE TITLE
ChangeNotifierProvider nullable generic type

### ISSUE THREAD

**Issue by KristianBalaj** [rrousselGit/river_pod#386]
This is the code sample:
```
class MyChangeNotifier extends ChangeNotifier {...}

final myProvider = ChangeNotifierProvider<MyChangeNotifier?>(......)
```

It cannot be used this way. The type parameter of the ChangeNotifierProvider needs to be non-nullable obviously. 

Is there any semantical/architectural purpose in this constraint? Or is it just a bug?

**Comment by rrousselGit** [comment]
This isn't supported because it makes the implementation easier and slightly more performant.

Why would you need to return a `null` changenotifier?

**Comment by KristianBalaj** [comment]
Okay then, I'm ok with that :) 
I was initializing the ChangeNotifier when an async task finished, until then it was null. But it's just a matter of design, it is changeable easily.

**Comment by rrousselGit** [comment]
In general I would instead recommend creating your notifier immediately, then awaiting the async task inside your notifier
