### ISSUE TITLE
Do context.refresh only works with FutureProvider ?

### ISSUE THREAD

**Issue by 2shrestha22** [rrousselGit/river_pod#388]
My StateNotifierProvider is:
```
final homepageStateNotifierProvider =
    StateNotifierProvider<HomepageStateNotifier>((ref) {
  final homepageRepo = ref.watch(homepageRepoRrovider);
  return HomepageStateNotifier(homepageRepo);
});
```
and I want to refresh this provider using pull to refresh so my widget is:
```
 RefreshIndicator(
        onRefresh: () => context.refresh(homepageStateNotifierProvider),
        child: MyChildWidget()
}
```
but I am not able to do this and gives error:
```
The argument type 'StateNotifierProvider<HomepageStateNotifier>' can't be assigned to the parameter type 'RootProvider<Future<void>, Object>'.
```
Is context.refresh only available for FutureProviders or there is another way to do this?

**Comment by rrousselGit** [comment]
`context.refresh` works with everything. The problem isn't  `context.refresh`, but `RefreshIndicator`, which wants a `Future` to keep the indicator visible while the data refreshes.


Assuming your `StateNotifier` uses `AsyncValue` like so:

```dart
class MyNotifier extends StateNotifier<AsyncValue<Model>> {
  MyNotifier(): super(const AsyncValue.loading());
}
```

you can do:

```dart
 RefreshIndicator(
  onRefresh: () => context.refresh(stateNotifierProvider).stream.firstWhere((value) => value is! AsyncLoading),
  child: MyChildWidget()
}
```

**Comment by 2shrestha22** [comment]
You assumed exact what I was doing. Thank you very much.

**Comment by derolf** [comment]
@rrousselGit 
> `context.refresh` works with everything.

Does it work with `Provider.autoDispose.family`? I am getting the error:

```
The argument type 'AutoDisposeProvider<String?>' can't be assigned to the parameter type 'RootProvider<dynamic, Object>'.```

**Comment by 2shrestha22** [comment]
@derolf, Yes it works, would you provide some code snippet what you are trying to do and how?
