### ISSUE TITLE
Widget rebuilds even if state remains the same

### ISSUE THREAD

**Issue by dario-digregorio** [rrousselGit/river_pod#397]
First of all I want to thank you for this great package you provide.

I am currently facing a issue. I can't find a way to let `CounterWidget` only rebuild when the `counterstepProvider` has a different value. As far as I read in the documentation `counterStepProvider` should only rebuild if the state it self changes. You can see that even if `CounterState` changes from `1.6` to `1.8` the `counterStepProvider` still notifies its Listeners even if the value remains `1`.

Is this behavior wanted? And if so how to prevent widget rebuild. I tryed with select but it did not work either.

```
import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

final counterStepProvider = Provider<int>((ref) => ref.watch(counterProvider.state).floor());

final counterProvider = StateNotifierProvider<CounterState>((ref) {
  return CounterState();
});

class CounterState extends StateNotifier<double> {
  CounterState() : super(0);

  add() {
    state = state + 0.2;
  }

  remove() {
    state = state - 0.2;
  }
}

void main() {
  runApp(ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
          child: Column(
        children: [
          CounterWidget(),
          Row(
            children: [
              IconButton(
                icon: Icon(Icons.add),
                onPressed: () => context.read(counterProvider).add(),
              ),
              IconButton(
                icon: Icon(Icons.remove),
                onPressed: () => context.read(counterProvider).remove(),
              ),
            ],
          )
        ],
      )),
    );
  }
}

class CounterWidget extends HookWidget {
  @override
  Widget build(BuildContext context) {
    final counterStep = useProvider(counterStepProvider);
    return Text(counterStep.toString());
  }
}

```

**Comment by rrousselGit** [comment]
Hello!

I am not quite sure what the problem is. From my test, `CounterWidget`'s `build` method is only called when the provider state changes.

**Comment by JurgenDJ** [comment]
I ran into the same problem:
In the code from dario-digregorio, the counterstepprovider should only trigger updates when the counter.floor() value is updated, so once every 5 increments of 0.2 in the parent counterprovider.

in my example below, I only want to listen to one property of my parent provider, so I did as explained in the docs:

``` dart
final sqlTextProvider = Provider<String>((ref){
  return  ref.watch(modelDefinitionProvider).sqlStatement;
});
```
(...)

``` dart
Consumer(
  builder: (context, watch, _) {
    var sqlText = watch(sqlTextProvider2);
    print("updated the sql statement"); // this is happening too often
    return Text(sqlText);
  },
)
```

expected behavior: consumer on sqlTextProvider is only updated when the sqlText field is changed.
current behavior: consumer is refreshing the widget on every update of ModelDefinitionProvider, regardless whether sqlStatement field changed or not.

**Comment by dario-digregorio** [comment]
Like @JurgenDJ says I think that the widget should rebuild if it's state changes. So it would rebuild every 5th increment. 

Right now it rebuilds everytime the provider it depends on changes.

**Comment by rrousselGit** [comment]
But I've tried your code and the build method is called only once out of 5

**Comment by JurgenDJ** [comment]
Ok, I checked again.

For my own case, I discovered a ```useprovider(modelDefinitionProvider) ``` statement higher up the widgettree which caused all others down to rebuild as well.

Also tested the example from dario-digregorio in varous flavours (hooks, statenotifier/changenotifier, ... etc) but couldn't reproduce the unneeded rebuilds either.

thanks for the great work on this package.

**Comment by dario-digregorio** [comment]
Hmm I could not recreate it again for some reason. I will close the issue.
