### ISSUE TITLE
autoDispose when another object is responsible for the dispose

### ISSUE THREAD

**Issue by venkatd** [rrousselGit/river_pod#404]
I have the following code:

```dart
final _websocketProvider = Provider.autoDispose<PhoenixWebSocket>((ref) {
  return PhoenixWebSocket(
     /// ... args irrelevant to discussion
  );
});

final connectionStateProvider = StateNotifierProvider.autoDispose((ref) {
  ref.maintainState = true; // needed to prevent an unwanted dispose
  return ref.watch(_websocketProvider).connectionState;
}).state;
```

The goal: I want to make a provider which has convenient access to the connection state which is a very commonly used property.

The problem is that, I don't want `StateNotifierProvider.autoDispose` to be responsible for disposing `connectionStateProvider` because `PhoenixWebSocket` already disposes `connectionState` in its `dispose()` method.

The workaround I landed on was using `ref.maintainState = true` but not sure if that's the preferred way.

Something else I tried was using `StateNotifierProvider` without the `autoDispose` but that's not possible because `_websocketProvider` is marked as `autoDispose`.

Any thoughts on the best way to accomplish this?

**Comment by rrousselGit** [comment]
The problem is your architecture

Don't:

```dart
final connectionStateProvider = StateNotifierProvider.autoDispose((ref) {
  ref.maintainState = true; // needed to prevent an unwanted dispose
  return ref.watch(_websocketProvider).connectionState;
}).state;
```

do:

```dart
final connectionStateProvider = StateNotifierProvider.autoDispose((ref) {
  return MyWebSocket(_websocketProvider);
}).state;
```

**Comment by venkatd** [comment]
Ok, I understand! So I should be injecting the dependencies in which means their lifecycle is managed by riverpod rather than the object itself?

**Comment by rrousselGit** [comment]
Yes

Providers should always create a new state. They shouldn't reuse an existing state

**Comment by venkatd** [comment]
Ok thanks for the clarification. That makes things a lot cleaner.
