### ISSUE TITLE
Incorrect code examples in the documentation. [await AsyncValue]

### ISSUE THREAD

**Issue by nailgilaziev** [rrousselGit/river_pod#411]
Thanks for this great library! 

_combining_providers_
https://riverpod.dev/docs/concepts/combining_providers#my-provider-updates-too-often-what-can-i-do

```
final configsProvider = StreamProvider<Configuration>(...);

/// A provider that exposes only the current host
final _hostProvider = Provider<AsyncValue<String>>((ref) {
  return ref.watch(configsProvider).whenData((configs) => configs.host);
});
final p
roductsProvider = FutureProvider<List<Product>>((ref) async {
  // Listens only to the host. If something else in the configurations
  // changes, this will not pointlessly re-evaluate our provider.
  final host = await ref.watch(_hostProvider);     //<----------- Problem HERE

  return dio.get('$host/products');
});
```

`final host = await ref.watch(_hostProvider);`

Produces warning: 
**'await' applied to 'AsyncValue', which is not a 'Future'**
and misleads users. For example this SO [question](https://stackoverflow.com/questions/66411312/riverpod-how-to-await-using-futureprovider-on-asyncvalue-not-in-widget)). 

You can't use `await` on `AsyncValue`.
so `host` variable will be AsyncValue and dio won't be possible to fetch.
How should this documentation example be rewritten to work correctly?

**Comment by nailgilaziev** [comment]
In my case Backend give me the list of items. 
```
final listFutureProvider = FutureProvider<List<Item>>((ref) {
  final backend = ref.watch(backendProvider);
  return backend.getList(name, (json) => Item.fromJson(json));
}); 
```
Some widgets consumes `listFutureProvider` to display list of items but another widgets consumes only by one item;
So I want to create a family provider for them like this:
```
final itemFutureProvider = FutureProvider.family<Item?,int>((ref, id) async {
  final list = await ref.watch(listFutureProvider); 
  return list.firstWhere((e)=>e.id = id);
});
```
_// FutureProvider here used because when deep linking, listFutureProvider will be uninitialized, because nobody listens him before_

But awaiting on `FutureProvider<List<Item>>` is not allowed... or I don't understand how to :) overcome this:
**'await' applied to 'AsyncValue', which is not a 'Future'**

Currently my item widgets listens `listFutureProvider` and do filtering on their side. 
<details>
  <summary>(Ugly but working)</summary>
  
```
class _CarBody extends HookWidget {
  @override
  Widget build(BuildContext context) {
    final id = useProvider(idScopedProvider);
    final list = useProvider(carsListFutureProvider);
    return list.when(
      loading: () => ProgressView(),
      error: (Object error, StackTrace? stackTrace) =>
          ErrorDetails(error, stackTrace),
      data: (List<Car> list) {
        final item = list.firstWhereOrNull((e) => e.id == id);
        if (item == null) {
          return NotFoundBody(message: 'Item with id $id not found');
        } else {
          return buildBody(item);
        }
      },
    );
  }
  
  Widget buildBody(Car item){
    return Center(child: Text(item.model));
  }
}
```
</details>

**Comment by nailgilaziev** [comment]
I understood how to use `await`. You need to use `provider.future`. In my case:
```
final carFutureProvider = FutureProvider.family<Car?,int>((ref,id) async {
  final list = await ref.watch(carsListFutureProvider.future);
  return list.firstWhereOrNull((e) => e.id == id);
});
```

But issue is still actual, because documentation contains this incorrectness :)

**Comment by AlexHartford** [comment]
Hi, I just tweaked the example in this PR: https://github.com/rrousselGit/river_pod/pull/414
Check it out and let me know if it solves your issue.
