### ISSUE TITLE
How to overrideWithValue Statenotifier in ^0.14.0+

### ISSUE THREAD

**Issue by Chojecki** [rrousselGit/river_pod#417]
Im just trying to migrate our App to Flutter 2.0 and Riverpod 0.14.0. We have some tests where we do something like

```dart
//...
authContollerProvider.overrideWithValue(const AuthState.unauthenticated()),
//...
```

Because in new version StateNotiferPorvider has different value, we can't do it anymore.

Would someone advise me how overwrite StateNotifierProvider with some state now?

**Comment by rrousselGit** [comment]
Could you clarify what is `authControllerProvider`?

**Comment by Chojecki** [comment]
Sure its `StateNotifierProvider<AuthController, AuthState>` and this `AuthController` is `StateNotifier<AuthState>`

**Comment by rrousselGit** [comment]
I see

Were you previously overriding `provider.state`?

**Comment by Chojecki** [comment]
In `ProviderScope` overwrites

**Comment by rrousselGit** [comment]
I see, that's a bad practice.

I'd suggest instead either override the creation of the StateNotifier itself to change its initial state, or expose a method to set the state from outside:

```dart
class AuthController extends StateNotifier<AuthState> {
  AuthController([AuthState? initialState]): super(initialState ?? MyDefaultState());
}

...
provider.overrideWithProvider(
  StateNotifierProvider((ref) => AuthController(const AuthState.unauthenticated()),
)
```

**Comment by Chojecki** [comment]
thanks for response. I've read in other issue that you are considering is as bad practice and since I've seen this we are not using that, but as always I'm not only one who write the code and refactor legacy code has always lower priority. Will try your approach. Happy to close the issue.
