### ISSUE TITLE
Can no longer override a StateProvider in riverpod: ^0.14.0

### ISSUE THREAD

**Issue by TimWhiting** [rrousselGit/river_pod#418]
**Describe the bug**
overrideWithProvider / overrideWithValue not available on StateProvider

**To Reproduce**

```dart
final selectedAddress = StateProvider<String>((ref) => '');

void main() {
  runApp(ProviderScope(
      overrides: [
        selectedAddress.overrideWithProvider(
            StateProvider((_) => 'http://localhost:8080')),
      ],
      child: MaterialApp(),
    ));
}
```

**Expected behavior**
No analysis / compile error.

I'm guessing you removed it for a reason, if you did I'll let you know more about my use case. I've also noticed overriding is missing on a few other types. It seems to only be available for StateNotifier / ChangeNotifier and Families. Is there a reason for that, and if so it should be in the Changelog.

**Comment by rrousselGit** [comment]
It was removed by mistakes from refactoring, let's add it back
