### ISSUE TITLE
Riverpod Migration tool cannot open file

### ISSUE THREAD

**Issue by EdwynZN** [rrousselGit/river_pod#422]
While using the migration tool after typing 'y' it throws an exception:
```
file:///e:/workspace_android/timlid/lib/provider/client/client_detail_provider.dart:9
Accept change (y = yes, n = no [default], A = yes to all, q = quit)?
y
```

```
Unhandled exception:
FileSystemException: Cannot open file, path = '/e:/workspace/myproject/lib/provider/client_detail_provider.dart' (OS Error: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos., errno = 123)
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:604:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:628:5)
#4      applyPatchesAndSave (package:codemod/src/util.dart:79:29)
#5      _runInteractiveCodemod (package:codemod/src/run_interactive_codemod.dart:314:9)
<asynchronous suspension>
```

I believe the error is related to the path or the Disk (my project is not in C: but in E:, maybe removing the first '/' before e). Also I think there is an error in the documentation 
```
You should now be able to do:
riverpod --help
```
Should be `riverpod_cli --help` and `riverpod_cli migrate`

**Comment by TimWhiting** [comment]
Seems to be an issue with the codemod package. I have submitted an issue there. Follow it for updates, if nothing happens for a few days, then I'll try to fix it myself. Feel free to figure out how to fix it if you want to migrate soon, otherwise, probably just wait.

```
riverpod --help
riverpod migrate
```
Works for me.

**Comment by EdwynZN** [comment]
Thank you, it worked almost all the project, except almost at the end 2 files it stopped with
```
[SEVERE] Suggestor.generatePatches() threw unexpectedly.
type 'DynamicTypeImpl' is not a subtype of type 'InterfaceType' in type cast
```
Maybe because I didn't cast them, anyway I changed them myself and updated to 14.0.0 without a problem

**Comment by TimWhiting** [comment]
Okay yeah, that is an unrelated issue. I can look into it.

**Comment by EdwynZN** [comment]
I used it now with another project (just starting, not so much code) and it worked flawlessly, still I had to use `run riverpod_cli migrate`, I know its unrelated to the main problem maybe its just my environment variable of pub messing because there is a bin in `AppData `folder and one inside flutter folder somewhere else

**Comment by TimWhiting** [comment]
Hmm, that seems strange, maybe you don't have $HOME\pub-cache\bin on your PATH?

**Comment by EdwynZN** [comment]
I have it like `$HOME\flutter\bin\cache\dart-sdk`, maybe thats part of the problem, sometimes I also experience `Could not find 'bin\riverpod.dart' in package 'riverpod'` and closing the cmd and opening it again fixes it, weird

**Comment by TimWhiting** [comment]
When you run `dart pub global activate riverpod_cli` does it have any warning / info message about setting your PATH environment variable to something in particular?

**Comment by EdwynZN** [comment]
It says to move it to the one in ` C:/Users/AppData/...` but doing that gives me always another error `Could not find a file named "pubspec.yaml" in "E:\Programs\flutter\bin\cache\dart-sdk\bin\hosted\pub.dartlang.org\_fe_analyzer_shared-12.0.0".`, on the other hand it lets me run `run riverpod --help` without `_cli`

**Comment by rrousselGit** [comment]
Is this still an issue with the new version?

**Comment by TimWhiting** [comment]
I don't think this is an issue any longer, this can be closed. @EdwynZN if you still are running into trouble with your PATH variable open a different issue.

**Comment by sourabhmahale** [comment]
> It says to move it to the one in ` C:/Users/AppData/...` but doing that gives me always another error `Could not find a file named "pubspec.yaml" in "E:\Programs\flutter\bin\cache\dart-sdk\bin\hosted\pub.dartlang.org\_fe_analyzer_shared-12.0.0".`, on the other hand it lets me run `run riverpod --help` without `_cli`

I also get this error if anyone has an answer then help me

**Comment by TimWhiting** [comment]
Try running flutter pub cache repair
