### ISSUE TITLE
Import location

### ISSUE THREAD

**Issue by mellowcello77** [rrousselGit/river_pod#423]
pub.dev says -->  import 'package:riverpod/riverpod.dart';

but working location is -->  import 'package:flutter_riverpod/flutter_riverpod.dart';

flutter_riverpod: ^0.13.1+1

Wasted time figuring this out, no auto import appeared in vscode.

**Comment by mellowcello77** [comment]
No idea why the package is not recognised, or where I got "flutter_riverpod".
But, also with a clean Flutter install, not recognised.
Could be issue on my side, but all other packages import fine.

import 'package:riverpod/riverpod.dart';

void main() {
  runApp(ProviderScope(child: MyApp()));
}

**The function 'ProviderScope' isn't defined.
Try importing the library that defines 'ProviderScope', correcting the name to the name of an existing function, or defining a function named 'ProviderScope'**

**Comment by rrousselGit** [comment]
> pub.dev says --> import 'package:riverpod/riverpod.dart';

Where does pub say that?

**Comment by mellowcello77** [comment]
![Screenshot 2021-04-07 at 20 32 58](https://user-images.githubusercontent.com/60788896/113916642-808b1880-97e0-11eb-89b5-59cad5963ec4.png)

On the package install page sorry.

**Comment by mellowcello77** [comment]
Just a little more clarity re what's happening:

1. I don't know what the difference is between these two, or where I even got "flutter_dev" from as it's not the package name indicated in pub.dev - https://pub.dev/packages/riverpod/install
Both of these install as a dependency in my pubspec file fine with exit code 0

flutter_riverpod: ^0.14.0+1
riverpod: ^0.14.0+1

2. With "flutter_riverpod:" as dependency, and importing with:
import 'package:flutter_riverpod/flutter_riverpod.dart';
It works fine. 

3. When I use "riverpod:" as dependency, and import with:
import 'package:riverpod/riverpod.dart';
The message "The function 'ProviderScope' isn't defined." appears

**Comment by rrousselGit** [comment]
That's expected

As per the [installation guide](https://riverpod.dev/docs/getting_started), if you want to you want to use riverpod with Flutter, flutter_riverpod is the way to go

**Comment by mellowcello77** [comment]
Off course! Thanks Remi
