### ISSUE TITLE
context.read returns state instead of the StateNotifier class

### ISSUE THREAD

**Issue by Sadmansamee** [rrousselGit/river_pod#427]
**Describe the bug**
I want to call the function of change notifier class on button click, but context.read is returning state.

**To Reproduce**

Here's the provider and StateNotifier class
```
final onboardingViewModelProvider =
    StateNotifierProvider<OnboardingViewModel, bool>((ref) {
  return OnboardingViewModel();
});

class OnboardingViewModel extends StateNotifier<bool> {
  OnboardingViewModel() : super(false);

  Future<void> completeOnboarding() async {
    state = true;
  }

  bool get isOnboardingComplete => state;
}
```

Another function from a tap 
```
Future<void> onGetStarted(BuildContext context) async {
    final onboardingViewModel = context.read(onboardingViewModelProvider);
    await onboardingViewModel.completeOnboarding(); //I'm getting issue here, here onboardingViewModel is the state value which is bool
  }
```
**`await onboardingViewModel.completeOnboarding();`** 
I'm getting issue here, here onboardingViewModel is the state value which is bool, but it shouldn't be

**Expected behavior**

**Comment by rrousselGit** [comment]
With 0.14.0, the syntax changed

See https://riverpod.dev/docs/migration/0.13.0_to_0.14.0

**Comment by Sadmansamee** [comment]
thanks
