### ISSUE TITLE
In riverpod, can I get the provider from a higher note or same level in the widget tree?

### ISSUE THREAD

**Issue by tbm98** [rrousselGit/river_pod#43]
like this. Can I get provider 2 or 3 from 1 ?
<img width="324" alt="Screen Shot 2020-07-10 at 3 30 47 PM" src="https://user-images.githubusercontent.com/52562340/87134103-67415400-c2c2-11ea-91bb-c13c2482fc52.png">

**Comment by rrousselGit** [comment]
What do you mean by "in the widget tree"?

**Comment by tbm98** [comment]
my widget tree
<img width="371" alt="Screen Shot 2020-07-10 at 4 29 40 PM" src="https://user-images.githubusercontent.com/52562340/87139730-a1165880-c2ca-11ea-8362-6be4a34e70cd.png">

in above image. 
Am I able to get provider of `RestClient` from `NavigatorStore`?

**Comment by rrousselGit** [comment]
If RestClient doesn't depend on NavigatorStore, yes. Otherwise no.

**Comment by tbm98** [comment]
Yep. Thanks
