### ISSUE TITLE
Use StateNotifier or StateProvider to store app's settings values

### ISSUE THREAD

**Issue by jimmys888** [rrousselGit/river_pod#431]
I'm currently using StateNotifier to store the app's setting and then update the UI accordingly.

The model:
```
class Settings {
  final bool showLastBookmark;
  final bool isDarkMode;

  Settings({
    this.showLastBookmark = true,
    this.isDarkMode = false,
  });

  Settings copy({
    bool showLastBookmark,
    bool isDarkMode,
  }) =>
      Settings(
        showLastBookmark: showLastBookmark ?? this.showLastBookmark,
        isDarkMode: isDarkMode ?? this.isDarkMode,
      );
}
```
And then:
```
final settingsProvider =
    StateNotifierProvider<SettingsNotifier>((ref) => SettingsNotifier());

class SettingsNotifier extends StateNotifier<Settings> {
  SettingsNotifier() : super(Settings());

  void updateShowLastBookmark(bool showLastBookmark) {
    final newState = state.copy(showLastBookmark: showLastBookmark);
    state = newState;
  }

  void updateIsDarkMode(bool isDarkMode) {
    final newState = state.copy(isDarkMode: isDarkMode);
    state = newState;
  }
}
```
This works fine without any problems, and it's convenient because I can use the methods to update the state. However I'm curious, am I'm doing it the right way? Or should I just use StateProvider instead? If I have more settings, say 10 parameters, is it fine to have lots of StateProviders?

Thanks

**Comment by iamarnas** [comment]
I would use also `StateNotifier` in your situation becouse `StateNotifier` is safer and better for bigger values. `StateProvider` I use it for single values.

**Comment by jimmys888** [comment]
Thank you @iamarnas 

It turns out that using StateNotifier like I do above, each time I update a parameter, all other widgets that are watching other parameters are being updated as well. I guess it's because of the copy method where all the parameters are being copied to a new state.

Is there any way to just update 1 parameter in the state, and not copy the whole thing to a new state?

Thanks

**Comment by AlexHartford** [comment]
To avoid rebuilding when unrelated parts of your state are updated, don't change how you're writing the state, but rather how you're reading it. You could create extra providers that only expose a certain value of your state, for example. [Example from docs](https://riverpod.dev/docs/concepts/combining_providers#my-provider-updates-too-often-what-can-i-do)

**Comment by jimmys888** [comment]
@AlexHartford you're right, I didn't realize that. Thank you!
