### ISSUE TITLE
Strange error with flutter web for AutoDisposeFutureProvider

### ISSUE THREAD

**Issue by sirjasiu** [rrousselGit/river_pod#435]
**Describe the bug**
When I'm trying to use Future provider, build from the family I get:
Unsupported operation: Unknown ProviderListenable AutoDisposeFutureProvider<dynamic>#0000e(from: Instance of 'AutoDisposeFutureProviderFamily<dynamic, dynamic>', argument: [here argument])

Does not happen in debug mode, happens only in profile or release web mode.

**To Reproduce**

```
//service
final apiService = Provider((ref) => ApiService());

final entryProvider = FutureProvider.autoDispose.family<Entry?, String>((ref, id) async {
      try {
        final val = await ref.watch(apiService).read(id);
        if (val != null) {
          ref.maintainState = true;
        }
        return val;
      } catch (e) {
        return null;
      }
    });

//in widget
class SimpleWidget extends ConsumerWidget {
  final String id;

  SimpleWidget(this.id);

  @override
  Widget build(BuildContext context, ScopedReader watch) {
    //here error
    var provider = watch(entryProvider(id));
   //...
  }
}
```

**Expected behavior**
I just want to get proper AsyncValue<Entry?> ;)

**Comment by sirjasiu** [comment]
It seems that problem is with autodispose. Using just FutureProvider.family works.

**Comment by rrousselGit** [comment]
Possibly a duplicate of https://github.com/rrousselGit/river_pod/issues/71

Try doing `AutoDisposeFutureProvider` instead of `FutureProvider.autoDispose`

**Comment by sirjasiu** [comment]
Thanks, works

**Comment by jaredweinfurtner** [comment]
> Possibly a duplicate of #71
> 
> Try doing `AutoDisposeFutureProvider` instead of `FutureProvider.autoDispose`


This doesn't work for `AutoDisposeStreamProviderFamily` or `StreamProvider.family.autoDispose` in:

```
Flutter 3.3.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision eb6d86ee27 (9 days ago) • 2022-10-04 22:31:45 -0700
Engine • revision c08d7d5efc
Tools • Dart 2.18.2 • DevTools 2.15.0
```

The only thing that appears to work is removing the `autoDispose` entirely which is severely restricting.  Is there any workaround for StreamProvider?
