### ISSUE TITLE
ChangeNotifierProvider always reconstruct when calling ref.watch on its constructor

### ISSUE THREAD

**Issue by mingosnunes** [rrousselGit/river_pod#436]
Hi! 

I'm using a ModelView-View approach when a single Provider controls the state of a single view (widget). In this example, I want just to rebuild the widget just when a user ID is changed.
I encounter a strange behaviour when calling `ProviderReference.watch()` inside a ChangeNotifier constructor for this purpose. 

```
final rootUserProvider = StreamProvider<UserModel>((ref) {
  UserRepository _userRepository = ref.read<UserRepository>(userRepoProvider);
  AuthRepository _authRepository = ref.read<AuthRepository>(authRepoProvider);

  return _userRepository.streamUser(_authRepository.user.uid);
});

final homeViewModelProvider = ChangeNotifierProvider<HomeViewModel>((ref) {

  print("provider");
  return HomeViewModel(ref);
});

class HomeViewModel extends ChangeNotifier{

  final ProviderReference _ref;
  String userID;

  HomeViewModel(this._ref){
    print("constructor");
    watchUserID();
  }

  void watchUserID(){
    final userStream = _ref.watch(rootUserProvider);

    print("watch");

    userStream.whenData((user) {
      print("update");
      if(userID != user.id){
        userID = user.id;
        notifyListeners();
      }
    });
  }
}
```
With this code, every time the users' data updates (not only the ID), rootUserProvider reacts and HomeViewModel run his constructor again.

console output (when user data is updated):
```
provider 
constructor
watch
update
```

I already found a workaround for this. If I use `Provider<Stream<UserModel>>` instead of `StreamProvide<UserModel>` I can get the behaviour that I'm expecting. 

```
final rootUserProvider = Provider<Stream<UserModel>>((ref) {
  UserRepository _userRepository = ref.read<UserRepository>(userRepoProvider);
  AuthRepository _authRepository = ref.read<AuthRepository>(authRepoProvider);

  return _userRepository.streamUser(_authRepository.user.uid);
});

final homeViewModelProvider = ChangeNotifierProvider<HomeViewModel>((ref) {

  print("provider");
  return HomeViewModel(ref);
});

class HomeViewModel extends ChangeNotifier{

  final ProviderReference _ref;
  String userID;

  HomeViewModel(this._ref){
    print("constructor");
    watchUserID();
  }

  void watchUserID(){
    final userStream = _ref.read(rootUserProvider);

    print("watch");

    userStream.listen((user) {
      print("update");
      if(userID != user.id){
        userID = user.id;
        notifyListeners();
      }
    });
  }
}
```

console output (when user data is updated):
```
update
```

This can be normal behaviour or a small bug but if I can't figure out why this is happening maybe others can't as well.
Thanks for the hard work,
Domingos Nunes

**Comment by iamarnas** [comment]
It's all about how you handle rebuilding. And I think you can find your answer here 👉 #431

**Comment by rrousselGit** [comment]
This is expected

`watch` means "rebuild the provider when the value changes"
`read` + `stream.listen` is indeed what you want.
