### ISSUE TITLE
ConsumerWidget breaks Hot Reload

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [rrousselGit/river_pod#440]
## Bug

When using `ConsumerWidget` or `Consumer` and changing something in `build` or `builder` respectively, then reloading to apply the changes, the widgets are not updated.

When replacing the `ConsumerWidget` with a `StatelessWidget` (when not listening to providers), hot reload will apply the changes again.

## Cause

I think the source of this error is this line of code: https://github.com/rrousselGit/river_pod/blob/8e71527b0d1fcb6ac385102bebf88324e486955e/packages/flutter_riverpod/lib/src/consumer.dart#L288

## Related issues

I found a few issues that seem related but all do not quite touch the same issue (and are all closed):

* #164
* #200
* #327

**Comment by TimWhiting** [comment]
If you look at the code just above the line you link it will mark the widget for recomputing the build method if there is a `reassemble` call which happens for hot-reload. So I don't think it is a problem with riverpod.

**Comment by creativecreatorormaybenot** [comment]
@TimWhiting thanks, looks like it was added.

**Comment by rrousselGit** [comment]
If you have this problem on the latest version, then maybe this is a regression.

In any case, the code you linked in an implementation detail of how Riverpod filters rebuild when the providers a widget depends on haven't changed.
