### ISSUE TITLE
Local variable 'authNotifierProvider' can't be referenced before it is declared when trying to get both state and notifier.

### ISSUE THREAD

**Issue by SalahAdDin** [rrousselGit/river_pod#444]
**Describe the bug**
I am trying to follow the documentation's advices related to [`context.read`](https://riverpod.dev/docs/concepts/reading/#contextreadmyprovider); in my widget I'm using a notifier to get its state and I'm using `context.read(StateNotifierProvider)` to get its methods as we require it to be called on buttons.

So, I wanna replace that `context.read(StateNotifierProvider)` by `userProvider(StateNotifierProvider.notifier)` but i get the following error on the IDE(Android Studio): `Local variable 'authNotifierProvider' can't be referenced before it is declared. `.

![image](https://user-images.githubusercontent.com/5034215/115223404-6b818400-a114-11eb-89ee-bc5105c2e596.png)

![image](https://user-images.githubusercontent.com/5034215/115223245-40973000-a114-11eb-888a-8513003d2519.png)

**To Reproduce**
```dart
  @override
  Widget build(BuildContext context) {
    final AuthState authScreenState = useProvider(authNotifierProvider);

    final authNotifierProvider = useProvider(authNotifierProvider.notifier);
```

If i put the second variable prior to the first one it just affect itself, but if in the current disposition it gives the error for both variables.

**Expected behavior**
In order to avoid the use `context.read(StateNotifierProvider)`, we should have a way to get both the state and the notifier in the same widget without having problems.

Thanks.

**Comment by rrousselGit** [comment]
The variable name you picked is not available
That's a Dart error

```dart
// DOn't:

**Comment by SalahAdDin** [comment]
@rrousselGit Sorry, i wasted your time, my mistake.
