### ISSUE TITLE
Access state class without context

### ISSUE THREAD

**Issue by ffpetrovic** [rrousselGit/river_pod#455]
In one file I'm making an instance of `dio`. 

```
final authClient = Dio(...);
```

I'm also adding interceptors to it
```
onError: (e) { ... }
```

In that interceptor I'm checking whether the error is an Unauthorized exception. If it is, then I need to call log out, which is in my `userStateProvider`. How can I call a method from my provider from this interceptor, considering I have no context. What approach should I use?

**Comment by rrousselGit** [comment]
Instead create your `Dio` in a `Provider` so that it can use `ref` to read other providers.

**Comment by ffpetrovic** [comment]
Works perfectly, thanks! This is more or less what I went with.

```
final clientProvider = Provider<Dio>((ref) {
  final baseDio = addInterceptors(Dio(), ref.read);

  return baseDio;
});
```

Thanks for your time and work!
