### ISSUE TITLE
The current StateNotifierProvider api documentation shows StreamProvider doumentation

### ISSUE THREAD

**Issue by Abhilash-Chandran** [rrousselGit/river_pod#46]
**A documentation issue**
When checking the api documentation for `StateNotifierProvider` the documentation currently shown describes  the `StreamProvider` instead.

This is a documentation or documentation generation issue.
**Screen Shot**

![image](https://user-images.githubusercontent.com/4489849/87247391-e3b76c80-c453-11ea-91bf-827a5a7e1d74.png)

**Comment by rrousselGit** [comment]
Thanks!

Fixed in 0.5.1
