### ISSUE TITLE
Running on chrome throws error

### ISSUE THREAD

**Issue by kamami** [rrousselGit/river_pod#460]
When running my app in chrome with "flutter run -d chrome", I get following error:

```
The following UnsupportedError was thrown building UncontrolledProviderScope:
Unsupported operation: Platform._operatingSystem

The relevant error-causing widget was:
  UncontrolledProviderScope
  file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_riverpod-0.14.0+1/lib/src/framework.dart:220:12
```

**Comment by rrousselGit** [comment]
Do you have a full stacktrace and a way to reproduce the issue?

Riverpod doesn't rely on `Platform`.

**Comment by kamami** [comment]
This is the complete error message. Comes up everytime I want to start the app.

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following UnsupportedError was thrown building UncontrolledProviderScope:
Unsupported operation: Platform._operatingSystem

The relevant error-causing widget was:
  UncontrolledProviderScope
  file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_riverpod-0.14.0+1/lib/src/framework.dart:220:12

When the exception was thrown, this was the stack:
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49     throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/io_patch.dart 244:5                  _operatingSystem
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/io/platform_impl.dart 56:40                                         get operatingSystem
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/io/platform.dart 64:45                                              get _operatingSystem
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 825:8  get
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/io/platform.dart 80:40                                              get operatingSystem
packages/platform/src/interface/local_platform.dart 21:45                                                                     get operatingSystem
packages/platform/src/interface/platform.dart 41:42                                                                           get isAndroid
packages/flutter_local_notifications/src/flutter_local_notifications_plugin.dart 43:17                                        private
packages/flutter_local_notifications/src/flutter_local_notifications_plugin.dart 56:39                                        get _instance
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 825:8  get
packages/flutter_local_notifications/src/flutter_local_notifications_plugin.dart 27:48                                        new
packages/aschaffenburger_geheimnisse/main.dart 50:7                                                                           new
packages/aschaffenburger_geheimnisse/main.dart 39:32                                                                          createState
packages/flutter/src/widgets/framework.dart 4584:23                                                                           new
packages/flutter/src/widgets/framework.dart 916:38                                                                            createElement
packages/flutter/src/widgets/framework.dart 3536:39                                                                           inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                                                                           updateChild
packages/flutter/src/widgets/framework.dart 4520:16                                                                           performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                                                                            rebuild
packages/flutter/src/widgets/framework.dart 4474:5                                                                            [_firstBuild]
packages/flutter/src/widgets/framework.dart 4469:5                                                                            mount
packages/flutter_riverpod/src/framework.dart 284:11                                                                           mount
packages/flutter/src/widgets/framework.dart 3541:13                                                                           inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                                                                           updateChild
packages/flutter/src/widgets/framework.dart 4520:16                                                                           performRebuild
packages/flutter/src/widgets/framework.dart 4667:11                                                                           performRebuild
packages/flutter/src/widgets/framework.dart 4189:5                                                                            rebuild
packages/flutter/src/widgets/framework.dart 4474:5                                                                            [_firstBuild]
packages/flutter/src/widgets/framework.dart 4658:11                                                                           [_firstBuild]
packages/flutter/src/widgets/framework.dart 4469:5                                                                            mount
packages/flutter/src/widgets/framework.dart 3541:13                                                                           inflateWidget
packages/flutter/src/widgets/framework.dart 3306:18                                                                           updateChild
packages/flutter/src/widgets/binding.dart 1182:16                                                                             [_rebuild]
packages/flutter/src/widgets/binding.dart 1153:5                                                                              mount
packages/flutter/src/widgets/binding.dart 1095:16                                                                             <fn>
packages/flutter/src/widgets/framework.dart 2647:19                                                                           buildScope
packages/flutter/src/widgets/binding.dart 1094:12                                                                             attachToRenderTree
packages/flutter/src/widgets/binding.dart 933:24                                                                              attachRootWidget
packages/flutter/src/widgets/binding.dart 915:7                                                                               <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 48:19          internalCallback

An this is my pubspec.yaml:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.2
  cloud_firestore: ^1.0.3
  google_maps_flutter: ^2.0.3
  material_floating_search_bar: ^0.3.3
  audioplayers: ^0.18.3
  flutter_html: ^2.0.0-nullsafety.0
  location: ^4.1.1
  flutter_local_notifications: ^5.0.0
  geofence_service: ^2.0.5
  cached_network_image: ^3.0.0
  snapping_sheet: ^3.0.0+2
  flutter_riverpod: ^0.14.0+1
  flutter_polyline_points: ^1.0.0
  permission_handler: ^7.0.0
  throttling: ^1.0.0

**Comment by rrousselGit** [comment]
From the stacktrace, it appears that the source of the issue is flutter_local_notifications, used in one of your StatefulWidget

**Comment by kamami** [comment]
That was the issue! Thanks
