### ISSUE TITLE
Reading a provider inside another stateNotifier

### ISSUE THREAD

**Issue by bhanuka96** [rrousselGit/river_pod#465]
What is the best practice reading provider inside another stateNotifier?

Currently, I am using this way. It's working fine. What is the best practice for this?

```
final purchaseRepositoryProvider = Provider<PurchaseRepository>((ref) => PurchaseRepository(Dio()));

final purchaseNotifierProvider = StateNotifierProvider((ref) =>PurchaseNotifier(ref));
```

ref is used for `refresh`. I can use `refresh` inside `ProviderListener`. I didn't use it because I need to wait until the data is refresh.
```
class PurchaseNotifier extends StateNotifier<PurchaseState> {
  final PurchaseRepository _purchaseRepository;
  final ProviderReference ref;

  PurchaseNotifier(this.ref) : super(PurchaseInitial());
  
    Future<void> purchase(Map<String, dynamic> values) async {
    try {
      state = PurchaseLoading();
      final PurchaseSubmitModel? data = await _purchaseRepository.purchase(accessToken, values);
      await ref.container.refresh(myPurchaseFutureProvider);
      await ref.container.refresh(pendingPurchaseFutureProvider);
      state = PurchaseLoaded(data);
    } on NetworkException {
      state = PurchaseError("Couldn't fetch Purchase. Is the device online?");
    } catch (e) {
      print('Error is : $e');
      state = PurchaseError("$e");
    }
  }
```

**Comment by julienlebren** [comment]
What is the purpose of these two lines?

```dart
      await ref.container.refresh(myPurchaseFutureProvider);
      await ref.container.refresh(pendingPurchaseFutureProvider);
```

**Comment by bhanuka96** [comment]
@julienlebren two different APIs

**Comment by julienlebren** [comment]
I don't think this is a good practice to call `refresh` here, there is probably a way to refresh it automatically.
Could you show the init code of `myPurchaseFutureProvider` and `pendingPurchaseFutureProvider` so I can tell you the best rewrite?

**Comment by rrousselGit** [comment]
> Currently, I am using this way. It's working fine. What is the best practice for this?

That's alright. Passing `ref` to StateNotifiers is the recommended solution.
