### ISSUE TITLE
How to initialize a provider with custom values.

### ISSUE THREAD

**Issue by zommerberg** [rrousselGit/river_pod#469]
Currently it is not explained how someone can possibly initialize a `ChangeNotifier` with custom values coming from e.g `shared_preferences` or `flutter_secure_storage`.

Example: 
I am getting the value `isLoggedIn` from `shared_preferences`  or `flutter_secure_storage` when initializing the app, I want to pass this value to a provider so it is globally available across the app. The only way I was able to do this is by using `FutureBuilders` and `initState`.

Code:
```

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  const storage = secure_storage.FlutterSecureStorage();
  String isLoggedIn = await storage.read(key: "isLogedIn");

  runApp(ProviderScope(
    child: MyApp(
      isLoggedIn: isLoggedIn,
    ),
  ));
}


class MyApp extends StatefulWidget {
  final bool isLoggedIn;

  MyApp(
      {Key key,
      @required this.isLoggedIn})
      : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();
    Future.microtask(() => context
        .read(utilsProvider)
        .initProvider(widget.isLoggedIn));
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'My App',
      ...
    );
  }
}

```

Notice how I am setting the provider value in initState instead of using `.family` or `overrides`.

In the original provider we could easily do this on provider initialization like that: 
```
ChangeNotifierProvider<UtilsProvider>(
            create: (_) => UtilsProvider(isLoggedIn))
```

The way I am initializing it is hacky and I may be missing something, but if there is no other way to initialize that we should at least document the hack above.

**Comment by nwparker** [comment]
Not sure if this is a better way, but you can see this:
https://github.com/rrousselGit/river_pod/issues/202#issuecomment-731585273

**Comment by nwparker** [comment]
Actually, I think the best solution might be [ScopedProvider](https://pub.dev/documentation/riverpod/latest/riverpod/ScopedProvider-class.html)

**Comment by rrousselGit** [comment]
https://github.com/rrousselGit/river_pod/issues/202#issuecomment-731585273 is indeed the correct solution. So I'm going to close this issue in favor of the other issue
