### ISSUE TITLE
Using flutter_riverpod: ^0.14.0+3 and flutter_bloc ^7.0.0

### ISSUE THREAD

**Issue by Orlyga01** [rrousselGit/river_pod#470]
Hi,
When using both packages on the same project, the context.read function is not recognized

**Comment by eyesoffish** [comment]
```dart
import 'package:flutter_bloc/flutter_bloc.dart' show BlocConsumer, BlocProvider;
```

**Comment by Orlyga01** [comment]
Hi eyesoffish, so I've updated the import, as you've advised. 
Looks like the read is getting to the correct function.
But - 
the  context .read(myProvider) returns null,  while myProvider is defined as global and is not null

**Comment by rrousselGit** [comment]
>  context .read(myProvider) returns null

if it returns null, chances are that your provider returned null. Could you share it?

**Comment by Orlyga01** [comment]
Thanks for your hint,  I found that in the myNotifier I didn't initialize a state - setting null in the super:
```
class MyNotifier extends StateNotifier<MyState> {
  MyNotifier () : super(null);
```
This indeed fixed the null problem.
Now I'm facing the following problem:
when trying context.read(myNotifiyer).getFunction()
```
Exception has occurred.
NoSuchMethodError (NoSuchMethodError: Class 'MyInitialize' has no instance method 'seFunction'.
Receiver: Instance of 'MyInitialize'
```
This is my UI code:
```
body: ProviderListener(
              provider: myNotifierProvider,
              onChange: (context, state) {
                if (state is MyError) {
                  showMessage(state.message, context);
                }
              },
              child: Consumer(builder: (context, watch, child) {
                final state = watch(myNotifierProvider);
if (state is MyInitialize) {
                  context.readmyNotifierProvider).setFunction();...
```
this is the notifier class
```class MyNotifier extends StateNotifier<MyState> {
  MyNotifier() : super(MyInitialize());

  Future<void> setFunction() async {
    try {
      state = MyLoading();
...

**Comment by TimWhiting** [comment]
Your error references seFunction instead of setFunction. Looks like a typo to me, maybe you didn't save or need to restart the app?

**Comment by Orlyga01** [comment]
Thanks for your comment. Its actually not the original code, I've changed the function name here, but in my app, the name of the function is the same... I've updated the code in my post above.

**Comment by TimWhiting** [comment]
Are you using Riverpod ^0.14.0

If so when you read the notifier you need to do this
```dart
context.read(myNotifierProvider.notifier).setFunction()
```

See the migration guide on riverpod.dev for more information on the changes in 0.14.0

**Comment by Orlyga01** [comment]
Thanks Tim, this has fixed the issue, and forced me to read the release notes. :-)
Next I'm now dealing with the following problem after calling my function:
So myFunction looks like that:
``` Future<void> myFunction() async {
    try {
      state = MyLoading();...
```
and the StatefullWidget UI looks like this:
``` if (state is MyInitialize) {
                  context
                      .read(MyNotifierProvider.notifier)
                      .setFunction();
                  return EmptyWidget();
                }
                if (state is MyLoading) {
                   return some Widget...
                } 
                }'''
when trying to set the state in the setFunction  I get this error: 
```FlutterError (setState() or markNeedsBuild() called during build.```
I dont use setState or initState anywhere in my code

**Comment by elianmortega** [comment]
Hello @Orlyga01 can you share more code from the state notifier and the UI part giving the error?

**Comment by Orlyga01** [comment]
Sure so this is my full SteteNofier:
`class GroupNotifier extends StateNotifier<GroupState> {
  final FirebaseGroupRepository _groupRepository;
  GroupNotifier(this._groupRepository) : super(GroupInitialize());

  Future<void> setGroupById(String groupid) async {
    try {
      state = GroupLoading();   -----------!!!!!!THIS IS CAUSING THE ERROR!!!--------------
      Group group = await _groupRepository.get(groupid);
      if (group != null) {
        log("group-controller - group loaded:" + group.name);
        state = GroupLoaded(group, null);
      }
    } catch (e) {
      state = GroupError(e.code() ?? e.message ?? e.toString());
    }
  }
}`
 and the UI is: 
`
final groupRepositoryProvider = Provider<FirebaseGroupRepository>(
  (ref) => FirebaseGroupRepository(null),
);

final groupNotifierProvider =
    StateNotifierProvider<GroupNotifier, GroupState>((ref) {
  return GroupNotifier(ref.watch(groupRepositoryProvider));
});

class GroupContainer extends StatefulWidget {
  final String groupId;
  final bool fromCreate;

  GroupContainer({
    Key key,
    this.groupId,
    this.fromCreate,
  }) : super(key: key);

  @override
  _GroupContainerState createState() =>
      _GroupContainerState(groupId, fromCreate);
}

class _GroupContainerState extends State<GroupContainer> {
  final String groupId;
  final bool fromCreate;

  Group group;

  _GroupContainerState(this.groupId, this.fromCreate);
  GlobalKey formKey = GlobalKey<FormState>();
 

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
        onWillPop: _onBackPressed(),
        child: Scaffold(
            appBar: AppBar(
              title: Text(appBarTitle),
            ),
            body: ProviderListener(
              provider: groupNotifierProvider,
              onChange: (context, state) {
                if (state is GroupError) {
                  showMessage(state.message, context);
                }
              },
              child: Consumer(builder: (context, ScopedReader watch, child) {
                assert(context != null);
                final state = watch(groupNotifierProvider);
                if (state is GroupLoaded) {
                  group = state.group;
                  appBarTitle = group.name;
                   return FilteredGroup()
                  
                }
                if (state is GroupInitialize) {
                  context
                      .read(groupNotifierProvider.notifier)
                      .setGroupById(groupId);
                  EmptyWidget();
                }
                if (state is GroupError) {
                } else {
                  EmptyWidget();
                }
              }),
            )));
    
  }
}`

**Comment by Orlyga01** [comment]
Thank you Elian, I've change my code so now we have:

```body: ProviderListener(
              provider: groupNotifierProvider,
              onChange: (context, state) {
                if (state is GroupError) {
                  showMessage(state.message, context);
                } else if (state is GroupInitialize) {
                  context
                      .read(groupNotifierProvider.notifier)
                      .setGroupById(groupId);
                  return EmptyWidget();
                }
              },
```
I see a state coming in "GroupInitialize" But the onChange event is not fired

**Comment by elianmortega** [comment]
In that case, as you want to call the function first thing for this new page,

I'll recommend calling the function before the page navigation. So in this case I can imagine you're navigating to the `GroupContainer` page so just call the function from the notifier before navigating like this:

```dart
{
  context
    .read(groupNotifierProvider.notifier)
    .setGroupById(groupId);
  Navigator.push(
    context,
    MaterialPageRoute(builder: (context) => GroupContainer(
      fromCreate: any,
      groupId: any,
     )),
  );
}

```

**Comment by TimWhiting** [comment]
Since you are using a parameter to define what you want, I would personally use a family.

Notifier
```dart
class GroupNotifier extends StateNotifier<GroupState> {
  final FirebaseGroupRepository _groupRepository;
  final String groupId;
  GroupNotifier(this._groupRepository, this.groupId) : super(GroupLoading()){
    initialize();
  }

  Future<void> initialize() async {
    try {
      Group group = await _groupRepository.get(groupId);
      if (group != null) {
        log("group-controller - group loaded:" + group.name);
        state = GroupLoaded(group, null);
      }
    } catch (e) {
      state = GroupError(e.code() ?? e.message ?? e.toString());
    }
  }
}
final groupNotifierProviderFamily =
    StateNotifierProvider<GroupNotifier, GroupState, String>((ref, groupID) {
  return GroupNotifier(ref.watch(groupRepositoryProvider), groupID);
});
```
Widget
```dart
class GroupContainer extends StatefulWidget {
  final String groupId;
  final bool fromCreate;

  GroupContainer({
    Key key,
    this.groupId,
    this.fromCreate,
  }) : super(key: key);

  @override
  _GroupContainerState createState() =>
      _GroupContainerState(groupId, fromCreate);
}

class _GroupContainerState extends State<GroupContainer> {
  final String groupId;
  final bool fromCreate;

  Group group;

  _GroupContainerState(this.groupId, this.fromCreate);
  GlobalKey formKey = GlobalKey<FormState>();
 

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
        onWillPop: _onBackPressed(),
        child: Scaffold(
            appBar: AppBar(
              title: Text(appBarTitle),
            ),
            body: Consumer(builder: (context, ScopedReader watch, child) {
                assert(context != null);
                final state = watch(groupNotifierProvider(groupId));
                if (state is GroupLoaded) {
                  group = state.group;
                  appBarTitle = group.name;
                   return FilteredGroup()
                }
                if (state is GroupLoading) {
                  CircularProgressIndicator();
                }
                if (state is GroupError) {
                } else {
                  EmptyWidget();
                }
              }),
            ));
    
  }
}
```

See the [family](https://riverpod.dev/docs/concepts/modifiers/family) documentation for more info.

**Comment by rrousselGit** [comment]
Closing as it seems to have been answered.

At the same time, using version 1.0.0-dev.x, there is no-longer a conflict between `context.read` from provider and `ref.read` from Riverpod.
