### ISSUE TITLE
Add a provider-like Selector

### ISSUE THREAD

**Issue by zommerberg** [rrousselGit/river_pod#472]
I've found many use cases where `useProvider` (or ref.watch in the future) from riverpod_hooks cannot be used since I am inside a StatefullWidget.

Would be very beneficial to add the provider-like `Selector` that can be used within a StatefullWidget and a StatelessWidget.

The idea of this Selector is the same as in Provider, we should be able to listen to a specific value and re-build the wrapped widget only when that value changes.

**Comment by rrousselGit** [comment]
> since I am inside a StatefullWidget.

You can use `StatefulHookWidget`, which allows using both `useProvider` and stateful widgets.

**Comment by zommerberg** [comment]
Did not know about that, this solves most of my use cases, however having a Selector would still be beneficial in case wo do not want to split the widget. 

What do you think?

**Comment by ldasilva-net** [comment]
I must know... If you use Hooks, why do you need StatefulWidgets?

**Comment by zommerberg** [comment]
@ldasilva-net  I have cases where a have a list of components and each component has its own state.

**Comment by rrousselGit** [comment]
Hooks should be able to replace all StatefulWidgets use-cases. 

But anyway, a `Selector` is not needed. `Consumer` is designed to support selectors too (although will be available only in the next update)

You will be able to do:

```
ref.watch(provider.select(...))
```

So I'm going to close this
