### ISSUE TITLE
how to refresh provider using timer?

### ISSUE THREAD

**Issue by bhanuka96** [rrousselGit/river_pod#478]
Is there any way to `refresh` the provider using a timer?

It's not refreshing

```
  @override
  void initState() {
    super.initState();
     context.refresh(bookState).timeout(Duration(seconds: 5));
  }
```

```
final bookState = FutureProvider<BookModel>((ref) async {
  return getBook();
});
```

**Comment by rrousselGit** [comment]
I don't see a Timer in your example. Could you explain more about it?

**Comment by iamarnas** [comment]
@rrousselGit He trying to use `Future` timeout method (onTimeout). I'm not with my pc, looks like he need serious examples.

**Comment by bhanuka96** [comment]
@rrousselGit yes, I didn't use `timer.periodic`. my problem is why is not working? (`.timeout(Duration(seconds: 5));`)

And also, what is the best practice for that?

**Comment by rrousselGit** [comment]
You did a timeout, but it's just not doing anything.

If you want to do something on timeout, you need to follow that code with a catchError:

```dart
future.timeout(duration).catchError((err) {
  context.refresh(provider);
})
```

**Comment by bhanuka96** [comment]
@rrousselGit I need to `refresh` API every 5 seconds. That's why I need to use this.

**Comment by rrousselGit** [comment]
In this case, you could use `StreamProvider`:

```dart
final _every5Seconds = StreamProvider<void>((ref) {
  return Stream.periodic(Duration(seconds: 5));
});

final bookState = FutureProvider<BookModel>((ref) async {
  // watching this will cause the provider to be re-evaluated every 5 seconds
  ref.watch(_every5Seconds);

  return getBook();
});
```

**Comment by bhanuka96** [comment]
@rrousselGit Thank you so much

**Comment by bhanuka96** [comment]
@rrousselGit I got this error when click restart the page. Restart the page mean, 

```
//same Page
Navigator.of(context).pushNamedAndRemoveUntil('/dashboardPage', (Route<dynamic> route) => false);
```

`[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: setState() or markNeedsBuild() called during build.`

can I add something like this?

```
  @override
  void initState() {
    super.initState();
    if(!mounted) return;
    context.refresh(bookState);
  }
```

**Comment by bhanuka96** [comment]
@rrousselGit I didn't get the above issue when using `timer`. and also remove `_every5Seconds ` state. can you give me the best way to handle this kind of case?

```
 _timer = Timer.periodic(Duration(seconds: 5), (timer) {
      if(!mounted) return;
      context.refresh(bookState);
    });
```

```
  @override
  void dispose() {
    _timer?.cancel();
    super.dispose();
  }
```

**Comment by iamarnas** [comment]
@bhanuka96 HI,
The best and safest way to handle this case with `StateNotifier` or `ValueNotifier` because you can control the timer on any state changes and will rebuild only aspected widgets unlike as `StatefulWidget`. For example, if you want to save your API calls, you can stop the `Timer` when the app stoped and continue when the app on the resume.

***StateNotifier with Timer:***
```dart
class CounterNotifier extends StateNotifier<int> {
  Timer _timer;

  CounterNotifier() : super(0) {
    startTimer();
  }

  // Function to reload data periodically.
  void onTick(Timer timer) {
    state = timer.tick;
  }

  void startTimer() {
    if (_timer?.isActive ?? false) return;
    _timer = Timer.periodic(const Duration(seconds: 1), onTick);
  }

  void stopTimer() {
    _timer?.cancel();
  }

  @override
  void dispose() {
    stopTimer();
    super.dispose();
  }
}
```
Then from everywhere, you can control your Counter state.
```dart
// Start timer.
context.read(counterTimer).startTimer(),
// Stop timer.
context.read(counterTimer).stopTimer(),
```
>***Note:*** Also, StateNotifier will allow you to put another provider inside the state  over `ProviderReference`

If you do not care about your API calls you can run a timer inside the `StatefulWidget` or use `Stream.periodic()`
> This may look like a boilerplate, but the boilerplate code always has a reason.

**Comment by bhanuka96** [comment]
@iamarnas Thank you so much
