### ISSUE TITLE
Documentation issue about state notifier provider

### ISSUE THREAD

**Issue by ivyxjc** [rrousselGit/river_pod#479]
https://github.com/rrousselGit/river_pod/blob/2ade9b2e43ca20ba0707df1684f62e851c914fa9/packages/riverpod/lib/src/state_notifier_provider.dart#L68

Is this documentation correct?

As I see, `context.read(todosProvider)` will return the type `List<Todo>` other than `TodoNotifier`.

**Comment by rrousselGit** [comment]
Looks like outdated code. Thanks for the report.

**Comment by rrousselGit** [comment]
Fixed, Thanks !
