### ISSUE TITLE
Allow optional minimum load time for AsyncValue.when

### ISSUE THREAD

**Issue by AlexHartford** [rrousselGit/river_pod#48]
I love how concise and safe the behavior of AsyncValue is for handling success, loading, and error states.  However, when loading only takes a split second, it looks a bit jumpy when going from the loading state to the success state.

I was wondering if having an optional parameter to the loading function allowing for a minimum time spent loading would be a good idea just so things don't appear as jittery once the data is loaded.

Prior to adopting Riverpod, I was using a FutureBuilder on my splash screen to force it to wait 2 seconds before displaying the app content.  That doesn't quite work when the parent context is responsible for where the user is routed.

In this example, the splash screen is shown for around 100ms before being redirected to the Login or Home page:
```dart
return authProvider.when(
  data: (user) => user == null ? Login() : Nav(),
  loading: () => Splash(),
  error: (err, stack) => Center(child: Text('Error: $err')),
);
```

**Comment by rrousselGit** [comment]
You could do something like

```dart
final auth = useProvider(authProvider);

final future = useMemoized(() => Future.delayed(seconds:2));
final snapshot = useFuture(future);
if (snapshot.connectipnState!= done)
  return Splash();

return auth.when(...)
```

**Comment by AlexHartford** [comment]
Thanks, that works. I will probably turn this into a hook.
