### ISSUE TITLE
No default behavior specified for ScopedProvider

### ISSUE THREAD

**Issue by JoseGeorges8** [rrousselGit/river_pod#480]
**Describe the bug**
According to the API reference, one can pass `null` to ScopeProvider if the behavior will always be overriden:

```
final example = ScopedProvider<int>(null);
```

However in my code is throwing `No default behavior specified for ScopedProvider` for when calling `context.read` within a Dialog.

**To Reproduce**

```
ListView.builder(
        itemCount: schedules.length,
        itemBuilder: (context, index) {
          final schedule = schedules[index];
          return ProviderScope(
            overrides: [
              currentScheduleProvider.overrideWithValue(schedule),
            ],
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                HookBuilder(
                  builder: (context) {
                    final currentSchedule = useProvider(currentScheduleProvider);
                    // THIS HERE WORKS FINE
                    final scheduleTimes = useProvider(crewScheduleTimeListProvider(currentSchedule));

                    return Column(
                      children: scheduleTimes
                          .map(
                            (scheduleTime) => ListTile(
                              selected: scheduleTime.selected,
                              onTap: () {
                               // This opens a dialog, within the dialog, the currentScheduleProvider throws the exception
                                showCrewScheduleTimeForm(context, crewScheduleTime: scheduleTime);
                              },
                            ),
                          )
                          .toList(),
                    );
                  },
                ),
              ],
            ),
          );
        },
      ),
```

**Expected behavior**
Expected the scopeProvider to work as usual within the dialog

**Comment by TimWhiting** [comment]
Dialogs' context are typically not from the local tree, since they are displayed above it (as a separate navigation context). This is likely the issue. Can you show more of how you are actually showing the dialog. You probably just need to pass the schedule to the dialog manually, or add another ProviderScope with the override in the dialog itself.

**Comment by JoseGeorges8** [comment]
Mmm I see. the usage of the dialog is very simple so no need to share it since is pretty clear that the difference in context between the dialog and the scope is the issue.

**Comment by rrousselGit** [comment]
As Tim said, your Provider is overriden for the ListView, not the dialogs, since they are in a different branch of the widget tree.

Your `showCrewScheduleTimeForm` should also add a `ProviderScope` that overrides that `ScopedProvider`.
