### ISSUE TITLE
not compatible with flutter_hooks ^0.17.0

### ISSUE THREAD

**Issue by kamyar75** [rrousselGit/river_pod#482]
**Describe the bug**

**To Reproduce**

<Please add a small sample to that can be executed to reproduce the problem. As a general rule, 100 lines is the maximum>
Because hooks_riverpod 0.14.0+3 depends on flutter_hooks ^0.16.0 and no versions of hooks_riverpod match >0.14.0+3 <0.15.0, hooks_riverpod ^0.14.0+3 requires flutter_hooks ^0.16.0.
So, because riverpod_test1 depends on both hooks_riverpod ^0.14.0+3 and flutter_hooks ^0.17.0, version solving failed.
pub get failed (1; So, because riverpod_test1 depends on both hooks_riverpod ^0.14.0+3 and flutter_hooks ^0.17.0, version solving failed.)

**Expected behavior**

**Comment by rrousselGit** [comment]
A new version was released that fixed the dependency issue
