### ISSUE TITLE
Accessing a StateNotifier with context.read

### ISSUE THREAD

**Issue by scopendo** [rrousselGit/river_pod#483]
**Is your feature request related to a problem? Please describe.**

Recently, Riverpod was changed so that `watch(myStateNotifierProvider)` returns the state rather than the notifier, requiring the lesser used syntax `watch(myStateNotifierProvider.notifier)` to watch the state notifier itself.

Whilst this is understandable, it also followed that reading the state notifier via the context changed from `context.read(myStateNotifierProvider)` to `context.read(myStateNotifierProvider.notifier)`.

If we accept that it is a bad practice to call context.read to get the state, then it feels like small boilerplate in widget callback methods like onPressed or onTap.

**Describe the solution you'd like**

Should `context.read(myStateNotifierProvider)` always return the state notifier itself?

**Comment by AlexHartford** [comment]
That seems really confusing to me. People are already getting this mixed up, why make it more complex?

Also, why do you say is `context.read(StateNotifier)` to retrieve the state bad practice? As long as you are not using `context.read` within the build method there's no harm done.

**Comment by rrousselGit** [comment]
A core design of `read` vs `watch` is that they both return the same thing. This proposal goes against this principle.
While this is more boilerplat-ish, potential confusion is not worth a few extra characters.

So I'm going to close this.
