### ISSUE TITLE
useTextEditingController(text: "foo") initializes without the text

### ISSUE THREAD

**Issue by gysipos** [rrousselGit/river_pod#486]
**Describe the bug**
Hi!
I use hooks_riverpod, and when creating a `TextEditingController` with `useTextEditingController`, it seems like the `text:` optional argument does not have any effect, it always gives back a TextEditingController with an initial value of ""

**To Reproduce**

inside the build method of a HookWidget:
`
String? foo = "foo";
final fooController = useTextEditingController(text: foo);
print(fooController.text);
`
prints ""

**Expected behavior**
I would expect it to print `"foo"`

**Comment by AlexHartford** [comment]
This isn't a bug involving riverpod, I would recommend closing this and [opening the issue in flutter_hooks](https://github.com/rrousselGit/flutter_hooks/issues).

**Comment by gysipos** [comment]
My mistake, thank you, will do that!
