### ISSUE TITLE
FutureProvider caches exeptions

### ISSUE THREAD

**Issue by ablbol** [rrousselGit/river_pod#487]
I have a FuturProvider that is supposed to get a list of users using REST API. and when I read the FutureProvider while there is no internet connection, I get an exception (which is expected) but when I turn the network connection on and request data again, I still get the same exception which means that the result is cached even if the result is exception.  I am using 
```
ref.maintainState = true;
```

to make sure I cache data.  Is there a way to cache data but not exceptions in the FutureProvider?

Here is how the provider looks like.

```
final listProfilesProvider =
    FutureProvider.autoDispose.family<List<Profile>, SearchQuery>(
  (ref, searchQuery) {
    ref.maintainState = true;
    return ref
        .watch(dataServiceProvider)
        .listProfiles(searchQuery: searchQuery);
  },
);
```

Thanks

**Comment by rrousselGit** [comment]
Place the "ref.maintainState" after the future is awaited

**Comment by ablbol** [comment]
I am sorry, I not sure I understand.  So in this Provider, what should I do?

```
final listProfilesProvider =
    FutureProvider.autoDispose.family<List<Profile>, SearchQuery>(
  (ref, searchQuery) {
    ref.maintainState = true;
    return ref
        .watch(dataServiceProvider)
        .listProfiles(searchQuery: searchQuery);
  },
);
```

**Comment by ablbol** [comment]
I ended up with this code 

```
final listProfilesProvider =
    FutureProvider.autoDispose.family<List<Profile>, SearchQuery>(
  (ref, searchQuery) async {
    ref.onDispose(() => print('===> disposed - listProfilesProvider'));
    final list = await ref
        .watch(dataServiceProvider)
        .listProfiles(searchQuery: searchQuery);
    ref.maintainState = true;

    return list;
  },
  name: 'listProfilesProvider',
);

```


Thanks so much for your help.

**Comment by ablbol** [comment]
The problem now is that the FutureProvider gets disposed every time.

**Comment by rrousselGit** [comment]
Maybe you can instead start with "maintainState=true"

Then catch the error, and on error set it to false

**Comment by ablbol** [comment]
That is exactly what I did before going to sleep and it works.  Thanks so much for all your help.

```
final listProfilesProvider =
    FutureProvider.autoDispose.family<List<Profile>, SearchQuery>(
  (ref, searchQuery) async {
    ref.onDispose(() => print('===> disposed - listProfilesProvider'));
    ref.maintainState = true;

    try {
      final list = await ref
          .watch(dataServiceProvider)
          .listProfiles(searchQuery: searchQuery);
      return list;
    } catch (e) {
      ref.maintainState = false;
      rethrow;
    }
  },
  name: 'listProfilesProvider',
);

```
