### ISSUE TITLE
FutureProvider not listening to another provider changes

### ISSUE THREAD

**Issue by mohanasundaramn** [rrousselGit/river_pod#490]
**Describe the bug**
FutureProvider not listening to another provider changes.

I have 2 Page **LeadListPage**, **AddEditLeadPage**, Leads are fetched using FutureProvider and populated in the leadsListPage.
user can create a new lead by going to AddEditLeadPage where he fills the form and submit it. once the form submitted successfully server sends 200 ok response I am trying to re-fetch the leads(in order to show updated leads) and route the user back to the leads list screen.

I am not sure the way I am trying to re-fetch data using future provider is right to wrong. it would be really helpful if you could help me with this.

what is the right way to re-fetch data using `FutureProvider`

**To Reproduce**
```Dart
class LeadsNotifier extends StateNotifier<DateTime> {
  LeadsNotifier() : super(DateTime.now());

  void updateDate(DateTime date) {
    state = date;
  }
}
```
```Dart
final fetchLeadsProvider = FutureProvider.autoDispose<List<LeadModel>>((ref) async {
  final _leadsService = ref.read(leadsServiceProvider);
  final date = ref.watch(leadsProvider);
  print("fetchLeadsProvider: $date");
  final from =
      (Jiffy(date)..startOf(Units.DAY)).dateTime.toUtc().toIso8601String();
  final to = (Jiffy(date)..endOf(Units.DAY)).dateTime.toUtc().toIso8601String();
  final response = await _leadsService.fetchLeads(from, to);
  return response;
});
```
LeadListPage
```Dart
class LeadListPage extends HookWidget {
  @override
  Widget build(BuildContext context) {
    final _leadsState = useProvider(leadsProvider);
    final leads = useProvider(fetchLeadsProvider);
    final _leadsProvider = useProvider(leadsProvider.notifier);

    return Scaffold(
       body: leads.when(
        data: (data)=>SuccessWidget(),
        loading: ()=>Loading(), 
        error: (err, stck)=> ErrorWidget(),
       ); 
    );
}
```

somewhere in another provider
```Dart
// tried to update date to listen for changes
void onSubmit(){
_leadsNotifier.updateDate(DateTime.now());
}

// tried to refresh via context refresh
void onSubmit(){
final container = ProviderContainer();
container.refresh(fetchLeadsProvider);
}
```
**Expected behaviour**
FutureProvider needs to fetch updated data from the server.

**Comment by rrousselGit** [comment]
> ```dart
> void onSubmit(){
> final container = ProviderContainer();
> container.refresh(fetchLeadsProvider);
> }
> ```

You cannot create a new `ProviderContainer` like this. You could instead call `context.refresh`
