### ISSUE TITLE
AnimatedList with riverpod

### ISSUE THREAD

**Issue by ablbol** [rrousselGit/river_pod#492]
I have a list of items that I am getting from Firestore database and would like to show them as ListTile's.  The list will update if a new item is added or deleted to Firestore database.  I would like to use AnimatedList to animate the add / delete of an item.  I have no issue with the delete part.  But how do I know when an Item was added to the list??

I was thinking to use ProviderListener but it gives you the full list after being modified.  I need to know which item was added or deleted.

Thanks

**Comment by rrousselGit** [comment]
Firestore exposes events for add/remove/update events. You could also use the document IDs to know.

Riverpod is not directly related to Firestore or your business logic. So this is for you to decide
