### ISSUE TITLE
[Question] Watching a provider does not return a new GraphQL client correctly

### ISSUE THREAD

**Issue by SalahAdDin** [rrousselGit/river_pod#497]
**Describe the bug**
We are using [`graphql`](https://pub.dev/packages/graphql/versions/5.0.0-nullsafety.5) to connect our application with our **GraphQL** backend API and **Riverpod** to provide a client to our repositories. Right now, our is an authentication workflow where we put a provider with the token, that can be updated when the user logs in, a client provider, which must be update once the token is updated/removed.

Everything is ok till the moment to making a request with the authentication header: even though the token is provided, calling a new request with a repository whos required the updated client(including the token) give us an error. 

**To Reproduce**

This is the token provider: 
```dart
final StateProvider<String> tokenProvider =
    StateProvider<String>((_) => '', name: "Token Provider");
```
This is the client provider:
```dart
final graphQLClientProvider = Provider<GraphQLClient>(
  (ref) {
    final String token = ref.watch(tokenProvider).state;

    print(Colorize(token).lightBlue());

    final Link _link = HttpLink(
        // String.fromEnvironment('API_URL'),
        // '$backendUrl/graphql',
        'http://192.168.1.36:1337/graphql',
        defaultHeaders: {
          if (token != '') 'Authorization': 'Bearer $token',
        });

    return GraphQLClient(
      cache: GraphQLCache(),
      link: _link,
    );

  },
  name: "GraphQL Client Provider",
);
```

Function, with `await profileRepository.findByUserId(sessionUser.id)` requiring the updated client:
```dart
final Map<String, dynamic> rawUser = await authRepository.signIn(
          identifier: username, password: password) as Map<String, dynamic>;
      User sessionUser = User.fromJson(rawUser);
      if (sessionUser.confirmed != false) {
        tokenController.state = sessionUser.token!;
        final Profile sessionUserProfile =
            await profileRepository.findByUserId(sessionUser.id);
        sessionUser = sessionUser.copyWith(profile: sessionUserProfile);
      }
      await dataStore.writeUserProfile(sessionUser);
      userController.state = sessionUser;
      state = const AuthState.loggedIn();
```

At fist, the cliente is created without any token(no authentication header), later at logging in the user, the token provider is updated with the value, triggerings, methinks, and update on the client provider.

As you can see here, inspecting the "newly" created  client we see it does not include any authentication header:
![image](https://user-images.githubusercontent.com/5034215/119981826-c08fa000-bfc6-11eb-8f2e-745e2bfc62e7.png)

We thought it was not working, but after review [this issue](https://github.com/rrousselGit/river_pod/issues/496?fbclid=IwAR3L-0nzmyEqFfF00i3GU-bzR8OCpE7rtzDAelpxOzIAiCiqFgLxhTCKCjw), it seem the token update triggers a change on the client, but this change does not reflex any authentication header on the client.

We checked it by creating a new client provider who includes the token at the beggining: it reflex the authentication token and gives a correct client which avoids us to connection errors.

**Expected behavior**
After refreshing/updating the token, a new or updated correct client should be provided.

**Comment by rrousselGit** [comment]
The issue appears to be caused by the ProfileRespository class. Could you share it?

It may be that the provider that creates this class does not "watch" the GraphQL client, so it keeps using the previous client instance.

**Comment by SalahAdDin** [comment]
Yeah, I think the problem is the second one, or the client is misformed in some point, the `ProfileRepository` class is as follows:
```dart
class GraphQLProfileRepository implements ProfileRepository {
  GraphQLProfileRepository({required this.client}) : super();

  final GraphQLClient client;
}
```

And its provider is:
```dart
final profileRepositoryProvider = Provider<ProfileRepository>(
  (ref) =>
      GraphQLProfileRepository(client: ref.watch(graphQLClientProvider)),
  name: 'Profile Repository Provider',
);
```

It is supposed the provider will be called after changing the authentication token (triggering the client to be "updated") and getting a new client with the authorization client included, rather getting a "new" client, but misformed as far as we can understand.

**Comment by rrousselGit** [comment]
Thanks

Could you provide a way to reproduce the issue? Some code that I can execute (but not a full project)

**Comment by SalahAdDin** [comment]
> Thanks
> 
> Could you provide a way to reproduce the issue? Some code that I can execute (but not a full project)

It woul be hard to do since it is part of a project which includes a private backend *GraphQL* **API**.

**Comment by SalahAdDin** [comment]
Well, we solved it by reading the client instead to watching its provider in boths authentication notifier/repository and profile provider/repository.
