### ISSUE TITLE
conditional provider like with Provider Package

### ISSUE THREAD

**Issue by logemann** [rrousselGit/river_pod#50]
**Is your feature request related to a problem? Please describe.**

I cant find a way to add a provider based on the value of a stream (in this case, the value of a firebase auth).

**Describe the solution you'd like**

Take this from provider package. This widgets sits on top of MaterialApp and get a builder which in fact is the whole app. So its a way to "inject" providers (here a firestore db provider with a valid connection based on user credentials) after  a successful login. 

```
class AuthWidgetBuilder extends StatelessWidget {
  const AuthWidgetBuilder({Key key, @required this.builder}) : super(key: key);
  final Widget Function(BuildContext, AsyncSnapshot<User>) builder;

  @override
  Widget build(BuildContext context) {
    final authService = Provider.of<AuthService>(context, listen: false);
    return StreamBuilder<User>(
      stream: authService.onAuthStateChanged,
      builder: (BuildContext context, AsyncSnapshot<User> snapshot) {
        final User user = snapshot.data;
        if (user != null) {
          return MultiProvider(
            providers: <SingleChildCloneableWidget>[
              Provider<User>.value(value: user),
              ProxyProvider<User, FirestoreDatabase>(
                update: (_, User user, __) => FirestoreDatabase(uid: user.uid),
              )
            ],
            child: builder(context, snapshot),
          );
        }
        return builder(context, snapshot);
      },
    );
  }
}
```

**Additional context**

I think "emulating" ProxyProvider in Riverpod should be quite easy with the "ref" variable but the whole concept of conditional providers is not clear. Perhaps i am missing something very basic here.

**Comment by rrousselGit** [comment]
You could do:

```dart
final auth = Provider((ref) => AuthService());

final db = StreamProvider((ref) async* {
  await for (final user in ref.read(auth).onAuthStateChanged) {
    yield FirestoreDatabase(uid: user.uid);
  }
});

final user = StreamProvider((ref) async* {
  await for (final user in ref.read(auth).onAuthStateChanged) {
    yield user;
  }
});
```

**Comment by logemann** [comment]
This looks pretty nice. I assume that you can put those in global scope right? As with other providers...
