### ISSUE TITLE
Type Error in ref.watch(ChangeNotifierProvider.autoDispose)

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [rrousselGit/river_pod#501]
**Describe the bug**

I am experiencing a type error to use `ref.watch` with a `ChangeNotifierProvider.autoDispose`:

```
The argument type 'AutoDisposeChangeNotifierProvider<Foo extends AutoDisposeChangeNotifierProvider>' can't be assigned to the parameter type 'AlwaysAliveProviderBase<Object?, dynamic>'.
```

So the error is:

> The argument type 'AutoDisposeProvider' can't be assigned to the parameter type 'AlwaysAliveProviderBase'.

**To Reproduce**

```dart
final foo = ChangeNotifierProvider.autoDispose<Foo>((ref) {
  return Foo();
});

class Foo extends ChangeNotifier {
  bool get baz => false;
}

final bar = Provider<bool?>((ref) {
  return ref.watch(foo).baz;
});
```

**Comment by creativecreatorormaybenot** [comment]
I assumed that `bar` would automatically auto dipose as well, however, that is not the case. In order to watch a `Provider.autoDispose` in another provider, we need to mark the other provider as auto dispose as well :)

```dart
final bar = Provider.autoDispose<bool?>((ref) { // added .autoDispose
  return ref.watch(foo).baz;
});
```

---

## [Docs](https://riverpod.dev/docs/concepts/modifiers/auto_dispose#the-argument-type-autodisposeprovider-cant-be-assigned-to-the-parameter-type-alwaysaliveproviderbase)

I know this is also mentioned in the [docs here](https://riverpod.dev/docs/concepts/modifiers/auto_dispose#the-argument-type-autodisposeprovider-cant-be-assigned-to-the-parameter-type-alwaysaliveproviderbase), however, SEO for that is terrible (it took me 30 mintes to find it), so I wanted to create an issue for SEO :)

**Comment by rrousselGit** [comment]
I wish we could provide custom compilation errors
