### ISSUE TITLE
requested:[USERNAME] or team-review-requested:[TEAMNAME]

### ISSUE THREAD

**Issue by brandonblackwater64** [rrousselGit/river_pod#502]
**Describe what scenario you think is uncovered by the existing 

> examples/articles[requested:[USERNAME] or team-review-requested:[TEAMNAME]]() **

A clear and concise description of the problem that you want explained.

**Describe why existing examples/articles do not cover this case**
Explain which examples/articles you have seen before making this request, and
why they did not help you with your problem.

**Additional context**
Add any other context or screenshots about the documentation request here.
Bug reports

**Comment by brandonblackwater64** [comment]
Report legal issue's

**Comment by rrousselGit** [comment]
Closing as the form is not completed correctly. Feel free to open a new karate if you still have some problem
