### ISSUE TITLE
Use Riverpod in an App with GetIt and BLoC while migrating

### ISSUE THREAD

**Issue by David-Mou** [rrousselGit/river_pod#503]
**Is your feature request related to a problem? Please describe.**
Currently I have a kind of big app using Flutter BLoC as state management. I'm thinking in moving to Riverpod, but I need a smooth migration, making BLoC/GetIt and Riverpod live together for a while.

New features will be written in Riverpod while old ones will be migrated slowly. In this case, it could happen that a service/repository consumed by a BLoC will be replaced from GetIt to Provider. The problem is that I don't have a context neither a ProviderScope inside the BLoC to read it.

**Describe the solution you'd like**
A way to access current providers from BLoC while migrating.

There are some approaches [here](https://github.com/rrousselGit/river_pod/issues/337) and [here](https://github.com/rrousselGit/river_pod/issues/295), but it looks as a global ProviderContainer is not a good practice.

**Describe alternatives you've considered**
I'm considering having a ProviderContainer as global while migrating is done using an UncontrolledProviderScope. After migrating, move to a regular ProviderScope.

**Comment by iamarnas** [comment]
@David-Mou Hi! A personal question. I wonder who forced you migrate from the Flutter bloc to Riverpod?

**Comment by David-Mou** [comment]
Just exploring possibilites and also reduce the boilerplate.

Apart of that, I like more how Riverpod is handling the state management.

**Comment by rrousselGit** [comment]
Could you explain specifically what you would like?

Is it being able to watch package:provider's providers inside package:riverpod's providers?

**Comment by David-Mou** [comment]
Current situation:

```dart
class Repository {
 ...
}

class SomeBloc extends Bloc<Event, State> {
    SomeBloc(Repository repository)  {}
}

GetIt.registerSingleton<Repository>(Repository());
GetIt.registerFactory<SomeBloc>(() => SomeBloc(GetIt<Repository>()));
```

What I will have while migrating:

```dart
class Repository {
 ...
}

// GetIt.registerSingleton<Repository>(Repository()); <- This is now provided by provider
final repositoryProvider = Provider((_) => Repository());

class SomeBloc extends Bloc<Event, State> {
    // I want to get here the repository currently provided by repositoryProvider
    SomeBloc(Repository repository)  {}
}

GetIt.registerFactory<SomeBloc>(() => SomeBloc(GetIt<Repository>()));
```

I hope this clarify the situation. 

While creating this example I realize that I could avoid the factory from GetIt and create manually the BLoC in the widget tree, making the widget a ConsumerWidget and passing the ref to the BLoC created... Would this be the best practice?

**Comment by rrousselGit** [comment]
Is there a reason why `SomeBloc` would not be in a Riverpod provider too?

**Comment by Moussenger** [comment]
If I don't misunderstand how Riverpod works, that code will generate a singleton for the BLoC. 

That means that I always have the same instance of the BLoC when I return again to the same screen instead of start again from initial state...

Could we replicate that factory behaviour with `autodispose`?

**Comment by David-Mou** [comment]
If I don't misunderstand how Riverpod works, that code will generate a singleton for the BLoC. 

That means that I always have the same instance of the BLoC when I return again to the same screen instead of start again from initial state...

Could we replicate that factory behaviour with `autodispose`?

**Comment by rrousselGit** [comment]
Yes autoDispose should do the trick

**Comment by David-Mou** [comment]
Thanks! This should work as expected then!
