### ISSUE TITLE
Best way to get cached data from local storage while waiting for the network

### ISSUE THREAD

**Issue by Moussenger** [rrousselGit/river_pod#504]
**Is your feature request related to a problem? Please describe.**
It's a common pattern in mobile applications to have locally cached data to improve the app's speed, performance, and UX. The common scenario is to load the data already in the cache while the network request is being processed, usually showing to the user some kind of loading in a corner of the screen to indicate that kind of background work, but allowing her to keep using the app.

When the network's request has finished, the screen gets updated with new data.

**Describe the solution you'd like**
You can get cachedData in the `loading` state of the `AsyncValue` in a new type of `AsyncValue` object. Something like this:

```dart
final cachedMessagesProvider = FutureProvider((ref) async => await loadDataFromLocalStorage());

final messagesProvider = CachedFutureProvider((ref) {
    ref.cachedData = await ref.read(cachedMessagesProvider);
    
    return await loadDataFromNetwork();
});

Widget build(BuildContext, ScopedReader watch) {
  CachedAsyncValue<Messages> messagesValue = watch(messagesProvider);

  return messagesValue.when(
    loading: (cachedMessages) => MessagesList(cachedMessages, loading: true),
    error: (err, stack) => Text('Error: $err'),
    data: (messages) => MessagesList(messages, loading: false),
  );
}
```

**Describe alternatives you've considered**
What I was thinking about (that I am not still totally sure this will be a good idea), is to have two different providers, one for cached data and another one for the network's call. Cached data will be an `AlwaysAliveProvider` while the network's call will live in an `autodispose`.  Each time the user enters the screen, the cached data will be shown, a new network provider state will be generated to make the call (because the `autodispose`) and then the cached data provider will be refreshed with new data. Let me write the pseudocode to clarify:

```dart
final cachedMessagesProvider = FutureProvider((ref) async => await loadDataFromLocalStorage());

final networkMessagesProvider = FutureProvider.autodispose((ref) {
    final data = await loadDataFromNetwork();
    
    await saveDataInCache(data);
    
    ref.read<cachedMessagesProvider>().refresh();

   return data;
});

Widget build(BuildContext, ScopedReader watch) {
  //I'm not sure about this as several rebuilds could be done because cache being updated after network finish.
  final cachedData = watch(cachedMessageProvider);
  final networkData = watch(networkMessagesProvider);

  return networkData.when(
    loading: () => const MessagesList(messages: cachedData.data, loading: true), //  I could have a problem because data could still not be available in first frames.
    error: (err, stack) => Text('Error: $err'),
    data: (messages) => MessagesList(messages: messages, loading: false), 
  );
}
```

**Comment by julienlebren** [comment]
🖐

Something may be wrong in this part of the code:
> ```dart
> Widget build(BuildContext, ScopedReader watch) {
>   CachedAsyncValue<Messages> messagesValue = watch(messagesProvider);
> 
>   return messagesValue.when(
>     cache: (cachedMessages) => MessagesList(cachedMessages),
>     loading: () => const CircularProgressIndicator(),
>     error: (err, stack) => Text('Error: $err'),
>     data: (messages) => MessagesList(messages),
>   );
> }
```

The problem with you `when` dispatch is that when it will load new data, it will display a `CircularProgressIndicator` instead of displaying the cached data. 

I think the alternative you provide is the good way to handle a cache, that is using the `loading` handler of `when` to display the cached data.

Additionally, note that when using something like **Firestore** for database, the cache is handled automatically and the data displayed which will be displayed first comes from the local cache while the network request is processed.

**Comment by Moussenger** [comment]
> Something may be wrong in this part of the code:
> 
> >

You are totally right, sorry. Already updated the code with the one I wanted to post:

```dart
Widget build(BuildContext, ScopedReader watch) {
  CachedAsyncValue<Messages> messagesValue = watch(messagesProvider);

  return messagesValue.when(
    loading: (cachedMessages) => MessagesList(cachedMessages, loading: true),
    error: (err, stack) => Text('Error: $err'),
    data: (messages) => MessagesList(messages, loading: false),
  );
```

**Comment by julienlebren** [comment]
Well, with this updated code, you can consider to do things without any new provider option.
Just build your own state class, for example with the `freezed` package from @rrousselGit 

```dart
@freezed
abstract class MyState with _$MyState {
  const factory MyState.loading(List< Messages >? cachedMessages) = _Loading;
  const factory MyState.data(List<Messages> data) = _Data;
  const factory MyState.error(String error) = _Error;
}
```

Your store managing the data can extend `StateNotifier<MyState>` and handle the cached data, load new data, etc.

So you can use this code:
```dart
return messagesValue.when(
    loading: (cachedMessages) => MessagesList(cachedMessages, loading: true),
    error: (error) => Text('Error: $error'),
    data: (messages) => MessagesList(messages, loading: false),
  );
````

**Comment by iamarnas** [comment]
And how it will indicate to the user when data is loading?

**Comment by julienlebren** [comment]
> And how it will indicate to the user when data is loading?

As far as I know, there is a `loading` state in the code I provided 🤨
It can be used to display a loading indicator somewhere in the view.

> return messagesValue.when(
>    forceRefresh: true,
>    initialData: (cachedMessages) => MessagesList(cachedMessages),
>   loading: () => const CircularProgressIndicator(),
>    error: (err, stack) => Text('Error: $err'),
>    data: (messages) => MessagesList(messages),
>  );

As I said above, this code won't work. 
When does the `initialData` state is supposed to be shown?
The initial data will be instantly hidden when state moves to `loading` and will display a `CircularProgressIndicator`.

I use the solution that I provided in many widgets and it works like a charm, that's why I replied to this question.

**Comment by iamarnas** [comment]
@julienlebren Ok

> ```dart
> return messagesValue.when(
>     loading: (cachedMessages) => MessagesList(cachedMessages, loading: true),
>     error: (error) => Text('Error: $error'),
>     data: (messages) => MessagesList(messages, loading: false),
>   );
> ```

But as I see you not provide a loading indicator to the UI. What would happen on the first load when both is is null or the user deleted cached data?
Use operator DataWidget `??` LoadingWidget ?

**Comment by rrousselGit** [comment]
> But as I see you not provide a loading indicator to the UI. What would happen on the first load when both is null or the user deleted cached data?

The `MessageList` class would show a loading indicator if `loading: true` and `cachesMessages: null`

**Comment by julienlebren** [comment]
> But as I see you not provide a loading indicator to the UI. 
> What would happen on the first load when both is null or the user deleted cached data?

There is no ui code in the code I provided, in fact you can do whatever you want with the `loading` state, ie display a loading indicator if `List<Messages>?` is null (that's the reason of the `?`).

**Comment by iamarnas** [comment]
@julienlebren
> There is no ui code in the code I provided...

Ohh... Then is ok. Sorry for misunderstanding.

**Comment by julienlebren** [comment]
No worries, aren't we here to help each other? 😉

**Comment by David-Mou** [comment]
@julienlebren I like your solution. Thanks a lot for the comments!

**Comment by Moussenger** [comment]
@julienlebren I like a lot your solution. Thanks to all of you for the comments!

**Comment by om-ha** [comment]
@Moussenger @julienlebren @iamarnas 

Hey guys, apologies for pinging you.

Can you please share implementation of `CachedAsyncValue`?
