### ISSUE TITLE
StreamProvider.last doesn't provide the last value of the stream

### ISSUE THREAD

**Issue by nank1ro** [rrousselGit/river_pod#508]
**Describe the bug**
StreamProvider.last doesn't provide the last value of the stream as expected.
Instead it returns each value of the stream in order of how it is added.

**To Reproduce**
```dart
test('test', () {
      final StreamController<int> _streamController = StreamController();
      final ProviderContainer providerContainer = ProviderContainer(
        overrides: [
          countStreamProvider.overrideWithProvider(StreamProvider<int>((ref) {
            return _streamController.stream;
          }, name: 'testProvider')),
        ],
      );

      _streamController.add(1);
      _streamController.add(2);
      _streamController.add(3);

      expect(providerContainer.read(countStreamProvider.last), completion(3));
    });
```

**Expected behavior**
I expected that `StreamProvider.last` returns `3`, instead it completed to `1`.
If I add `await providerContainer.read(countStreamProvider.last);` before the expect I get back `2`.
If I add one more line like above I get the expected result `3`.

For now I fixed using: 
```dart
expect(providerContainer.read(countStreamProvider.stream).skip(2), emits(3));
```

**Comment by rrousselGit** [comment]
The issue appears to be your test instead.

By default, streams queue their events. So even if you called `add` 3 times at once, the value aren't received at the same time.
A proof would be:
```dart
import 'dart:async';

void main()async {
  final StreamController<int> _streamController = StreamController();

  _streamController.add(1);
  _streamController.add(2);
  _streamController.add(3);
  
  _streamController.stream.listen((value) {
    print('received $value');
  });
  
  print('a');
  await Future.value();
    print('b');
  await Future.value();
    print('c');
  await Future.value();
}
```

This prints:

```
a
received 1
b
received 2
c
received 3
```


You may want to use a `StreamController.broadcast` instead

**Comment by nank1ro** [comment]
Sorry I didn't think the problem was the behavior of the streams in dart.
I'm a little disappointed with the behavior it has, as by testing real code I can't have to "count" how many events to ignore.

I tried the same code I showed you above with the BehaviorSubject of RxDart and it works fine as I expected, but I don't want to use another state manager in addition to Riverpod.

Do you have any suggestions on how to do it in pure Dart (maybe with the help of Riverpod) without adding too much boilerplate?

**Comment by rrousselGit** [comment]
I'm not quite sure. Maybe you could share why this is an issue for you?

**Comment by nank1ro** [comment]
Because the `add` method of the stream controller is not a future, so I thought that the listeners would be notified synchronously.

But I still don't understand why if I run
```
_streamController.add(1);
await Future.value();
_streamController.add(2);
await Future.value();
_streamController.add(3);
await Future.value();
```
has not effect, I still get `1` in the expect, while
```
await providerContainer.read(countStreamProvider.last);
```
works fine

**Comment by rrousselGit** [comment]
This all depends on when you call `.last`


If you read it before a value is emitted, the future will resolve with the very next value received. So if you do:

```dart
final future = read(provider.last);

controller.add(1);
await
controller.add(2);
await

print(await future);
```

you'll get `1`, not `2`

That is expected because when the future was created, no value was emitted yet.

**Comment by nank1ro** [comment]
Thank you for your help! I really appreciate it. If you want you can close the issue
