### ISSUE TITLE
Add stream, future, statenotifier variants of ScopedProvider

### ISSUE THREAD

**Issue by Nolence** [rrousselGit/river_pod#509]
Hi ! I've been playing around riverpod for a while and have tried many things to see what feels most natural. One thing that I found surprising is that `ScopedProvider`s are discouraged in favor of `.family`s. Personally I find scoped providers much easier to use and it's clear to see where they break.

I understand that riverpod likely wants to avoid people filing issues about not finding the proper context for their provider in a dialog sheet or whatever but that seems like it can be fixed by an error report saying they're likely in the wrong part of the tree or similar.

One suggested alternative is saw was use Provider's with null values to achieve a similar functionality to `ScopedProvider`s

[from comment](https://github.com/rrousselGit/river_pod/issues/144#issuecomment-695798306)
```dart
final databaseProvider = Provider<FirestoreDatabase>((ref) {
  final auth = ref.watch(authStateChangesProvider);

  if (auth.data?.value?.user?.id != null) {
    return FirestoreDatabase(auth.data.value.user.id);
  }
  return null;  
});
```

The null value would tell us that there is no database. However, now, everywhere in the app that we need use that database we now need to check null. If it's a handful of times, no issue. But any more and it's an annoyance -- I ended up defining a UI helper function that would handle a null provider value in portions of the app I was certain it could never be null (while still avoiding force unwrapping).

```dart
// In profile, where a null user makes no sense
final user = useProvider(userProvider);

return user.when(/** Handle all cases of UI */);
```

With ScopedProvider's, the user is overridden with a non-null user. Declarative auth will handle moving the user out if they ever go null.

Another suggestion around ScopedProviders is to instead use a `family`. However, I have personally found myself passing through the values for family's through multiple levels of the widget tree just to be used in a `family` variant. I know unidirectional data helps for readable code but I rather just setup the provider once where it has all its parameters available rather than later after having moved its parameters through several layers.

**Describe the solution you'd like**
It'd be great if there were variants for all provider types that were ScopedProvider. I personally wanted to create a ScopedProvider that was a StreamProvider but that's not officially supported (perhaps because ScopedProviders hold no state I think) and their documentation is also very sparse.

Personally, I don't really mind the current `family` solution that much. I'd just like to hear more arguments against ProviderScopes.

**Comment by rrousselGit** [comment]
The reason this wasn't implemented was because of technical difficulties.

But after some thoughts, I found a solution and this will be implemented in the 1.0 of Riverpod (with ScopedProvider being removed)

**Comment by julienlebren** [comment]
> The reason this wasn't implemented was because of technical difficulties.
> 
> But after some thoughts, I found a solution and this will be implemented in the 1.0 of Riverpod (with ScopedProvider being removed)

Is there some place where you already explained the upcoming changes in 1.0?
I’m interested in the removal of ScopedProvider because I use it a lot currently (essentially for list tiles but also in custom uses which seem like workarounds).

**Comment by rrousselGit** [comment]
Not yet, since it's still subject to change.



> I’m interested in the removal of ScopedProvider because I use it a lot currently

This change means you would be able to scope _anything_.
So you will be able to replace `ScopedProvider` with `Provider` for the same functionality.

**Comment by julienlebren** [comment]
Great, I was thinking a few days ago that I would love to have StateProvider which is scoped to simplify some state management issue in a view.
Can’t wait for 1.0! Thank you for this great work.

**Comment by rrousselGit** [comment]
Note that this is not yet implemented. The idea I have to make this work may very well not work, so don't get your hopes too high :smile:

**Comment by emallay** [comment]
@rrousselGit - My brain has been conditioned by decades of marketing to only expect hype. If you keep insisting on honesty and reality in your comments my cerebral cortex will probably seize up. 😬

**Comment by Nolence** [comment]
![ZomboMeme 05062021120811.jpg](https://user-images.githubusercontent.com/29642168/120901302-31ead680-c5f7-11eb-9bfe-b543a1055c11.jpg)

**Comment by julienlebren** [comment]
> Note that this is not yet implemented. The idea I have to make this work may very well not work, so don't get your hopes too high 😄

Too late, I already commented all my ScopedProviders with @depcreated Migrate to Riverpod 1.0 🙃

**Comment by Nolence** [comment]
As everything is scopeable in `^1.0.0` I'm going to close this

Thanks !
