### ISSUE TITLE
No file or variants found for asset: assets/configurations.json in marvel example app

### ISSUE THREAD

**Issue by bhanuka96** [rrousselGit/river_pod#516]
I try to run marvel example app. but said "No file or variants found for asset: assets/configurations.json in marvel example app"

**Comment by julienlebren** [comment]
As you can see, _assets/configurations.json_ is in the [.gitignore file].(https://github.com/rrousselGit/river_pod/blob/master/examples/marvel/.gitignore)

You need to create your own configurations.json file as mentioned in the _README_:
[https://github.com/rrousselGit/river_pod/tree/master/examples/marvel#installation](https://github.com/rrousselGit/river_pod/tree/master/examples/marvel#installation)
