### ISSUE TITLE
FutureProvider stuck on loading state

### ISSUE THREAD

**Issue by patdgeerico** [rrousselGit/river_pod#517]
I am using future provider in my app to display login page when there is data and error while it shows a loading page while fetching data. The problem is immediately the page loads it shows the loading page. Here is my code
my provider
`final loginProvider = FutureProvider.family((ref, UserInput input) async {
  return await ref
      .read(authRepositoryProvider)
      .doLogin(input.email, input.password);
});`
 my dologin function 
` Future<dynamic> doLogin(String email, String password) async {
    try {
      final response = await _read(dioProvider)
          .post('$baseUrl/login', data: {'email': email, 'password': password});
      final data = Map<String, dynamic>.from(response.data);
      return data;
    } on DioError catch (e) {
      return BadRequestException(e.error);
    } on SocketException {
      return 'No Internet Connection';
    }
  }`

then my ui 
` Widget build(BuildContext context) {`

    `var userInput =
        UserInput(emailEditingController.text, passwordEditingController.text);
    final login = useProvider(loginProvider(userInput));
    return login.when(
      data: (user) => Login(emailEditingController, passwordEditingController),
      loading: () => const ProgressIndication(),
      error: (error, stack) {
        if (error is DioError) {
          return Login(emailEditingController, passwordEditingController);
        } else {
          return Login(emailEditingController, passwordEditingController);
        }
      },
    );
  }`

**Comment by rrousselGit** [comment]
Have you double-checked that your future complete (and doesn't fail)?

**Comment by patdgeerico** [comment]
Okay so i just tried debugging and i noticed that i get 
`Invalid Request: Http status error [429]` that shows the user has sent too many requests.

**Comment by rrousselGit** [comment]
Did you maybe forget to override ==/hashCode in your `UserInput` class?

**Comment by patdgeerico** [comment]
That did the trick though. I used equatable to handle it and it worked fine.

**Comment by patdgeerico** [comment]
I have another issue but i will open another issue for that. Thank you
