### ISSUE TITLE
Onchange provider function returns loading state alone

### ISSUE THREAD

**Issue by patdgeerico** [rrousselGit/river_pod#519]
I am using provider listener to get the state value and then return a snackbar when state has error or navigate to another page when the state has completed value.
Here is my ui

    `return ProviderListener<LoginState>(
      provider: loginControllerProvider,
      onChange: (BuildContext context, value) {
        if (value.loginStatus == Status.COMPLETED) {
          print('redirect');
        }
        if (value.loginStatus == Status.ERROR) {
          print('error');
        } 
        if (value.loginStatus == Status.LOADING) {
          print('loading');
        } 
      },`

Here is my provider

     final loginControllerProvider =
    StateNotifierProvider.autoDispose<LoginController, LoginState>(
        (ref) => LoginController(ref.read));

Here is my statenotifier

    class LoginController extends StateNotifier<LoginState> {
    LoginController(this._read) : super(LoginState.initial());

    final Reader _read;

    void login(String email, String password) async {
    state = state.copyWith(loginStatus: Status.LOADING, isAuthenticated: false);
    final response =
        await _read(authRepositoryProvider).doLogin(email, password);
    if (response is AppException) {
      state = state.copyWith(
          loginStatus: Status.ERROR,
          error: response.toString(),
          isAuthenticated: false);
    } else {
      state =
          state.copyWith(loginStatus: Status.COMPLETED, isAuthenticated: true);
     }
    }
    }

And finally my state

    enum Status { INITIAL, LOADING, COMPLETED, ERROR }

      class LoginState extends Equatable {
      final Status loginStatus;
      final String? error;
      final bool isAuthenticated;

      LoginState(
          {required this.loginStatus, this.error, required this.isAuthenticated});

        factory LoginState.initial() {
           return LoginState(loginStatus: Status.INITIAL, isAuthenticated: false);
        }

       LoginState copyWith(
           {required Status loginStatus,
           String? error,
            required bool isAuthenticated}) {
               return LoginState(
               loginStatus: loginStatus,
              error: error,
            isAuthenticated: isAuthenticated);
       }

      @override
        List<Object?> get props => [loginStatus, error, isAuthenticated];
    }

What i am trying to do is print loading if the state is loading, print error if the state is error and completed if the state is completed. But the onchange method only prints loading. In my controller method the state changes accordingly as it should.

**Comment by tbm98** [comment]
@patdgeerico do you have a minimal repo to reproduce this issue?

**Comment by patdgeerico** [comment]
@tbm98 no i do not. I know the issue is listeners are only fired once after every state change. When i try returning state from inside the listener i get loading state return value

**Comment by FetFrumos** [comment]
I have same issue

**Comment by iamarnas** [comment]
@patdgeerico 🖐️

You have bad copyWith method. 

```dart
LoginState copyWith({
       required Status loginStatus,
       String? error,
        required bool is Authenticated, 
}) {
       return LoginState(
        loginStatus: loginStatus,
        error: error,
        isAuthenticated: isAuthenticated, 
 );
}
```
###It should be:
```dart
LoginState copyWith({
       required Status loginStatus,
       String? error,
        required bool isAuthenticated, 
}) {
       return LoginState(
        loginStatus: loginStatus ?? this.loginStatus,
        error: error ?? this.error,
        isAuthenticated: isAuthenticated ?? this.isAuthenticated, 
 );
}
```

**Comment by patdgeerico** [comment]
@iamarnas thanks but i am pretty sure the copyWith method works just fine as i am using null safety and handling that already so there is no need for the null check with ??

**Comment by patdgeerico** [comment]
> I have same issue. this is very critical, if such a basic thing does not work - the package cannot be used in a production app.

I have been on this for almost a week. so saddening

**Comment by iamarnas** [comment]
> @iamarnas thanks but i am pretty sure the copyWith method works just fine as i am using null safety and handling that already so there is no need for the null check with ??

the `copyWith` method uses this operator `??`  not really for null control, it says with what value you want to override the state. In you code you use only one value inside `copyWith` method. Maybe some one can explain better how `copyWith` method work.

**Comment by iamarnas** [comment]
@patdgeerico it's the same with Consumer?

**Comment by tbm98** [comment]
@patdgeerico I just test your code and found problems.
you can see my repo [here](https://github.com/tbm98/flutter_app_bug_report/blob/main/lib/issue_pages/provider_listener_issue.dart)

it always fire loading state because this line
 `state = state.copyWith(loginStatus: Status.LOADING, isAuthenticated: false);`

and I think it not fire `redirect` or `error` state because this line `final response =
    await _read(authRepositoryProvider).doLogin(email, password);` throw error and stop before update state
clone my repo and try :D

**Comment by iamarnas** [comment]
@tbm98 @patdgeerico I can accept it too. I also just tested his code and found the same problem. If i return a boolean with `final response = await _read(authRepositoryProvider).doLogin();` it work without issues.

**Comment by iamarnas** [comment]
Here is my example:
```dart
// LoginController provider.
final loginControllerProvider =
    StateNotifierProvider.autoDispose<LoginController, LoginState>(
        (ref) => LoginController(ref.read));

class LoginController extends StateNotifier<LoginState> {
  LoginController(this._read) : super(LoginState.initial());

  final Reader _read;

  Future<void> login() async {
    state = state.copyWith(status: LoginStatus.loading, isAuthenticated: false);
    final response = await _read(authRepositoryProvider).doLogin();

    if (!response) {
      state = state.copyWith(
        status: LoginStatus.error,
        error: response.toString(),
        isAuthenticated: false,
      );
    } else {
      state = state.copyWith(
        status: LoginStatus.completed,
        isAuthenticated: true,
      );
    }
  }
}

// LoginState model.
enum LoginStatus { initial, loading, completed, error }

class LoginState extends Equatable {
  final LoginStatus status;
  final String? error;
  final bool isAuthenticated;

  const LoginState({
    required this.status,
    this.error,
    required this.isAuthenticated,
  });

  factory LoginState.initial() {
    return const LoginState(
      status: LoginStatus.initial,
      isAuthenticated: false,
    );
  }

  LoginState copyWith({
    String? error,
    required LoginStatus status,
    required bool isAuthenticated,
  }) {
    return LoginState(
      error: error,
      status: status,
      isAuthenticated: isAuthenticated,
    );
  }

  @override
  List<Object?> get props => [status, error, isAuthenticated];
}

// AuthRepository class.
final authRepositoryProvider = Provider((ref) => AuthRepository());

class AuthRepository {
  Future<bool> doLogin() async {
    await Future.delayed(const Duration(milliseconds: 500));
    return false;
  }
}
```

**Comment by patdgeerico** [comment]
> @patdgeerico I just test your code and found problems.
> you can see my repo [here](https://github.com/tbm98/flutter_app_bug_report/blob/main/lib/issue_pages/provider_listener_issue.dart)
> 
> it always fire loading state because this line
> `state = state.copyWith(loginStatus: Status.LOADING, isAuthenticated: false);`
> 
> and I think it not fire `redirect` or `error` state because this line `final response = await _read(authRepositoryProvider).doLogin(email, password);` throw error and stop before update state
> clone my repo and try :D

Yeah that line is there to show a loading action in this case for a network call. Removing it basically will not show the network call when i try to do a login action

**Comment by patdgeerico** [comment]
> Here is my example:
> 
> ```dart
> // LoginController provider.
> final loginControllerProvider =
>     StateNotifierProvider.autoDispose<LoginController, LoginState>(
>         (ref) => LoginController(ref.read));
> 
> class LoginController extends StateNotifier<LoginState> {
>   LoginController(this._read) : super(LoginState.initial());
> 
>   final Reader _read;
> 
>   Future<void> login() async {
>     state = state.copyWith(status: LoginStatus.loading, isAuthenticated: false);
>     final response = await _read(authRepositoryProvider).doLogin();
> 
>     if (!response) {
>       state = state.copyWith(
>         status: LoginStatus.error,
>         error: response.toString(),
>         isAuthenticated: false,
>       );
>     } else {
>       state = state.copyWith(
>         status: LoginStatus.completed,
>         isAuthenticated: true,
>       );
>     }
>   }
> }
> 
> // LoginState model.
> enum LoginStatus { initial, loading, completed, error }
> 
> class LoginState extends Equatable {
>   final LoginStatus status;
>   final String? error;
>   final bool isAuthenticated;
> 
>   const LoginState({
>     required this.status,
>     this.error,
>     required this.isAuthenticated,
>   });
> 
>   factory LoginState.initial() {
>     return const LoginState(
>       status: LoginStatus.initial,
>       isAuthenticated: false,
>     );
>   }
> 
>   LoginState copyWith({
>     String? error,
>     required LoginStatus status,
>     required bool isAuthenticated,
>   }) {
>     return LoginState(
>       error: error,
>       status: status,
>       isAuthenticated: isAuthenticated,
>     );
>   }
> 
>   @override
>   List<Object?> get props => [status, error, isAuthenticated];
> }
> 
> // AuthRepository class.
> final authRepositoryProvider = Provider((ref) => AuthRepository());
> 
> class AuthRepository {
>   Future<bool> doLogin() async {
>     await Future.delayed(const Duration(milliseconds: 500));
>     return false;
>   }
> }
> ```

Okay let me try this.

**Comment by patdgeerico** [comment]
Okay so i think i know where the error is coming from. i have a builder that is showing different pages based on the current state and on of those pages include the login page that has the listener. So i removed the builder and just returned the login page with the listener the snackbar is called as it should be. I just have to figure another way to achieve what i want to achieve. Thanks everyone
