### ISSUE TITLE
How to use a future provider within a future provider?

### ISSUE THREAD

**Issue by JoseGeorges8** [rrousselGit/river_pod#524]
I usually find myself doing things like this:

I have class A, and B:

```
class A {
}

class B {
}

```

Then I have some FutureProvider for A:

```

final providerA = FutureProvider<A>((ref) {
    return fetchA();
})

```

And then I need A to fetch a List of B, so this is what I do:

```
final providerB = FutureProvider<B>((ref) {
   final asyncA = ref.watch(providerA);
   A valueA;

   asyncA.whenData((value) => valueA = value);
   if(valueA != null)
        return fetchB(valueA);

    return null;
});
```

is there a better way to do this? I don't want to *await* for the future because there are cases where providerB might just be a different provider type.

**Comment by rrousselGit** [comment]
You can do:

```dart
final providerB = FutureProvider<B>((ref) async {
   A value = await ref.watch(providerA.future);

```

>  don't want to await for the future

You have to somewhere. Since it's a future, you have to handle loading/error cases

**Comment by JoseGeorges8** [comment]
But what I meant with "don't want to await for the future" is that some cases a **FutureProvider** won't be used, so await is not available.

**Comment by rrousselGit** [comment]
You can still use "future.then"

**Comment by rrousselGit** [comment]
Closing as this was answered
