### ISSUE TITLE
How to read an existing family instance without re-instance.

### ISSUE THREAD

**Issue by HealingW** [rrousselGit/river_pod#529]
How to read an existing family instance without re-instance.

This is my code

provider A

`final A =
      ChangeNotifierProvider.autoDispose.family<ProviderA, String>((ref, campusId) => ViewModelA(id: id));`

provider B

`final B = ChangeNotifierProvider.autoDispose.family<ProviderB, String>((ref, otherField) {
    return ProviderB(paramA: otherField, paramB: ref.read(A));
});`

I want to useProvider(A) in HookWidget but don't want to pass the family parameter. What should I do?

**Comment by rrousselGit** [comment]
I don't understand the question.

What does re-instance mean here?



> I want to useProvider(A) in HookWidget but don't want to pass the family parameter. What should I do?

The parameter is required. You need to pass it

**Comment by HealingW** [comment]
Sorry, I use language translation to communicate with you. Maybe my meaning is ambiguous.
and thank your reply.

Re-instance means that when my widget is rebuilt, usePorvider(A(param)) returns to a new state, and the previous state disappears.

`class ChildWidget extends HookWidget {
  final String id;

  ChildWidget({required this.id});

  @override
  Widget build(BuildContext context) {
    final viewModel = useProvider(ProviderA('id'));

    useEffect(() {
      viewModel.initData();
    }, []);

    return Some Widget ...
  }
}`

**Comment by rrousselGit** [comment]
That shouldn't be the case.

Are you sure that the param is the same and/or override ==?
Alternatively if your provider uses `autoDispose`, maybe it was disposed?

**Comment by HealingW** [comment]
I seem to understand what you are saying, but I am a little confused.
Do you mean so?

`final A = ChangeNotifierProvider.autoDispose.family<ProviderA, String>((ref, campusId) {
    // Determine whether the parameters are equal
   return  ViewModelA(id: id);
});`

Or do you have a relevant example? This can make me clearer.
thanks.

**Comment by HealingW** [comment]
I checked the provider and there is no dispose

**Comment by HealingW** [comment]
The problem has been solved. I also understand what you mean.

And thank you for your contribution. Compared with provider, it has many advantages and makes me more happy when writing code.
