### ISSUE TITLE
[1.0.0] Missing ConsumerStatefulWidget

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [rrousselGit/river_pod#532]
The CHANGELOG states:

> Added `ConsumerStatefulWidget` + `ConsumerState`, a variant of `StatefulWidget`s that have access to a `WidgetRef`.

However, searching the API of `flutter_riverpod: 1.0.0-dev.1` reveals that this is not true.

**Comment by creativecreatorormaybenot** [comment]
(No criticism intended. I think either it was forgotten to be committed or the CHANGELOG needs to be updated - for now).

**Comment by rrousselGit** [comment]
It seem that I forgot to export it

Should be fixed in a few minutes

**Comment by creativecreatorormaybenot** [comment]
I reckoned that would be the case :)

**Comment by rrousselGit** [comment]
Should be fixed in 1.0.0-dev+1
