### ISSUE TITLE
[Request Example] can add advance example using streamProvider?

### ISSUE THREAD

**Issue by bhanuka96** [rrousselGit/river_pod#536]
I cannot find any advance example related to `streamProvider`.  

I saw a small example on the [documentation](https://pub.dev/documentation/riverpod/latest/riverpod/StreamProvider-class.html)

**Comment by smiLLe** [comment]
Do you have a specific use case you cannot implement? Or are you trying to help improve the documentation?

**Comment by bhanuka96** [comment]
> Do you have a specific use case you cannot implement? Or are you trying to help improve the documentation?

I tried to implement `streamProvider`. But I cannot find any **advance** example related to `streamProvider`. Most advanced examples like [this](https://github.com/rrousselGit/river_pod/tree/master/examples) used `FutureProvider` and other providers. There is no any **advance** example using `streamProvider`. That's why I raised this issue

**Comment by julienlebren** [comment]
[Here is one sample project which shows how to implement it](https://github.com/bizz84/starter_architecture_flutter_firebase/blob/master/lib/app/home/jobs/jobs_page.dart)

PS: Link is available from "Third parties examples" on the official doc...

**Comment by bhanuka96** [comment]
@smiLLe @julienlebren I wrote some example code using StreamPrivider. Can you help me to improve this code?

I am not sure is it possible to use it without `StreamController`? I mean using `riverpod` mechanism. What is the best practice using riverpod?.

**PriceRepository**

```
class PriceRepository {
  PriceRepository();
  
  final _socketResponse = StreamController<NewPriceModel>();

  void Function(NewPriceModel) get addResponse => _socketResponse.sink.add;

  Stream<NewPriceModel> get getResponse => _socketResponse.stream;

  void dispose() {
    _socketResponse.close();
  }

  void getPrices() async {
    Socket socket = io('http://localhost:3000',
        OptionBuilder()
            .setTransports(['websocket']).build());

    socket.onConnect((_) {
      print('connect');
      socket.emit('msg', 'test');
    });

    socket.on('update', (data) {
      addResponse(newPriceModelFromJson(data));
    });

    socket.onDisconnect((_) => print('disconnect'));
  }
}
```

**Price Repo Provider**
```
final priceServiceProvider = Provider<PriceRepository>((ref) {
  return PriceRepository();
});
```

**StreamProvider** 

```
final priceProvider = StreamProvider.autoDispose<NewPriceModel>((ref) {
  ref.maintainState = true;
  final activityService = ref.watch(priceServiceProvider);
  activityService.getPrices();
  return activityService.getResponse;
});
```

**Comment by Moussenger** [comment]
> **StreamProvider** 
> 
> ```
> final priceProvider = StreamProvider.autoDispose<NewPriceModel>((ref) {
>   ref.maintainState = true;
>   final activityService = ref.watch(priceServiceProvider);
>   activityService.getPrices();
>   return activityService.getResponse;
> });
> ```

Why do you maintain state at the beginning of the `StreamProvider.autoDispose`? Wouldn't that the same of `StreamProvider` without `autodispose`?

**Comment by bhanuka96** [comment]
@Moussenger okay I removed `ref.maintainState = true;`

**Comment by rrousselGit** [comment]
The entire provider devtool is implemented using Riverpod by chaining Stream/FutureProviders https://github.com/flutter/devtools/tree/master/packages/devtools_app/lib/src/provider

That should serve as a good example, so I will close this
