### ISSUE TITLE
ConsumerWidget documentation doesn't match with Api Reference

### ISSUE THREAD

**Issue by eugenio-tesio** [rrousselGit/river_pod#537]
This documentation

https://riverpod.dev/docs/concepts/reading#consumerwidget

doesn't match with this

https://pub.dev/documentation/flutter_riverpod/latest/flutter_riverpod/ConsumerWidget-class.html

**Comment by rrousselGit** [comment]
The api reference is using 0.14.0

The documentation is using 1.0.0-dev.x

So this is expected

**Comment by eugenio-tesio** [comment]
Oh, sorry, My mistake.
