### ISSUE TITLE
analyzer complains at useStreamController() with "Close instances of `dart.core.Sink`."

### ISSUE THREAD

**Issue by aoatmon** [rrousselGit/river_pod#544]
**Describe the bug**
big change I just missed something, nevertheless
analyzer is upset if I use in a `HookWidget`

```dart
    final controller = useStreamController();
``` 

> Close instances of `dart.core.Sink`.

![image](https://user-images.githubusercontent.com/85128136/123652005-997df580-d834-11eb-90b1-8c84e30b2f0e.png)

**To Reproduce**

```console
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-EE)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.57.1)
[✓] Connected device (2 available)

• No issues found!
```
```yaml
  flutter_hooks: ^0.17.0
  hooks_riverpod: ^0.14.0
```

**Expected behavior**
analyzer showing some love

**Comment by rrousselGit** [comment]
The problem is the analyzer, not Riverpod/Hooks.

There is nothing I can do. Consider disabling the lint
