### ISSUE TITLE
Factory Provider

### ISSUE THREAD

**Issue by srikrsna** [rrousselGit/river_pod#548]
**Is your feature request related to a problem? Please describe.**
I have an existing app which uses StateNotifiers for managing state. It uses GetIt for resolving dependencies. I wanted to replace this with river pod (compile time safety and easy to implement lazy loading).

In the current setup, within  say MasterDetailView it currently is as follows,

```dart
class _ArticlesPageState extends State<ArticlesPage>
    with ArticlesProvider {
  late ArticlesFilter filter;
  late ArticlesNotifier articlesNote;

  @override
  void initState() {
    super.initState();
    articlesNote = GetIt.I<ArticlesNotifier>();
    updateFilter(
      ArticlesFilter(parent: widget.parent, pageSize: 20)..freeze(),
    );
  }

  void updateFilter(ArticlesFilter fil) {
    filter = fil;
    articlesNote.reload(filter);
  }

  void create(BuildContext context) {
    context.showFormDialog(FormDialog<Article>(
      actionText: 'Create',
      builder: (context, mt) => ArticleForm(article: mt),
      initialValue: Article(id: widget.parent),
      onSubmit: articlesNote.create,
    ));
  }

  void openDetail(BuildContext context, String id) {
    articlesNote.reFetch(id);
    MasterDetailRouter.setDetail(context, id);
  }

  @override
  void dispose() {
    articlesNote.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return LimitedBox(
      maxHeight: MediaQuery.of(context).size.height,
      child: MasterDetailRouter(
        masterBuilder: buildMaster,
        detailBuilder: buildDetail,
      ),
    );
  }

  Widget buildMaster(BuildContext context) {
    return StateNotifierBuilder<AsyncValue<ListArticlesResponse>>(
      stateNotifier: articlesNote,
      builder: (context, state, _) {
        return state.when(
          error: (e, _) => Text('$e'),
          loading: () => Center(child: CircularProgressIndicator()),
          data: (data) {
            // 
          },
        );
      },
    );
  }

  Widget buildDetail(BuildContext context, String id) {
    return SelectStateNotifierBuilder<AsyncValue<ListArticlesResponse>>(
      stateNotifier: articlesNote,
      selector: (data) => { return date.firstWhere((e) => e.id == id); },
      builder: (context, state, _) {
        return state.when(
          error: (e, _) => Text('$e'),
          loading: () => Center(child: CircularProgressIndicator()),
          data: (data) {
            // 
          },
        );
      },
    );
  }
}
```

I am unable to do so for 2 reasons:
* The (context as WidgetRef).read only works if the element is ConsumerElement. Which it does not need.
* There is no factory constructor similar to GetIt.

**Describe the solution you'd like**
* Bring back the context extensions which were removed in 1.0.0.dev-2 or a version of them.
* I want to propose a factory modifier which creates a new instance whenever requested.

**Describe alternatives you've considered**

Alternative for context problem: Define my own extension.
```dart
extension RiverPodExtensions on BuildContext {
  T read<T>(ProviderBase<T> provider) {
    return ProviderScope.containerOf(this, listen: false).read(provider);
  }
}
```
Alternative to Factory, Use a family modifier and pass a random string each time and hope they don't collide
```dart
articlesNote = context.read(articles("random string"));
```

**Additional context**
I tried using ConsumerWidget. It forces me to rebuild the router as well. If I use two Consumers for builder and detail. It disposes them each time they switch. So I have to decide between a memory leak and momentary bad state.

**Comment by rrousselGit** [comment]
`context.read` is no longer feasible once a common source of bug is fixed, which is why `ref.read` was introduced.

Similarly a provider that already creates a new state is anti-pattern with Riverpod.
If you want a new state, use a different provider, `ref.refresh` or `family`

**Comment by srikrsna** [comment]
> `context.read` is no longer feasible once a common source of bug is fixed, which is why `ref.read` was introduced.

Can you point me to relevant issue/discussion so that I can understand this better. I was able to use it without any issue with the extension I made. Will there be a problem with continuing to use that extension?





> Similarly a provider that already creates a new state is anti-pattern with Riverpod.

I understand that. A majority of applications wouldn't need the optimisations I require. Can you guide me as to how I can implement my own Provider or may be a modifier in this case?

**Comment by davidmartos96** [comment]
@srikrsna If I understood correctly you want to obtain an instance of ArticlesNotifier as done in get_it without context.
You can do so with the 1.0.0, now there is a `ConsumerStatefulWidget` and a `ConsumerState` which has access to the `ref`. Then you can do:

```dart
@override
void initState() {
    super.initState();
    articlesNote = ref.read(articlesNotifierProvider);
}
```

**Comment by srikrsna** [comment]
@davidmartos96 Thanks! that I have just found out. I will definitely look into it.

My other argument is for creating unique instances on each call of read. Although for most applications this will only add unnecessary complexity. I think it better suites Flutter. React uses `memo` to avoid rendering child components of a stateful widget if their props match. As far as I understand, Flutter doesn't have/do anything like that. It re-renders the entire widget tree. So my approach of managing the life cycle in a top level widget and subscribing to selected changes in its children will be optimal.

**Comment by srikrsna** [comment]
Examples of the same pattern being used in Flutter SDK:

[PaginatedDataTable's DataSource](https://api.flutter.dev/flutter/material/DataTableSource-class.html)
[MultiChildLayoutDelegate](https://api.flutter.dev/flutter/rendering/MultiChildLayoutDelegate-class.html)

Both of them take a listenable rather than forcing the user to rebuild the entire widget tree.

**Comment by rrousselGit** [comment]
This is in direct opposition with what I want to do with Riverpod.

Riverpod is a reactive caching framework. If we remove the caching by creating a new state everytime, Riverpod doesn't make much sense

**Comment by srikrsna** [comment]
@rrousselGit I am not asking to remove the caching functionality. As I said, for the majority of applications Riverpod is a great fit in its current state.  I am only asking guidance on implementing a modifier. Doesn't need to be added to Riverpod.

Riverpod which I believe is comparable to [Recoiljs](https://recoiljs.org/) is well suited for React like rendering technique (`memo`). Flutter on the other hand is fast enough for this to work despite not having something like `memo`. But there are situations where this is expensive and is advised (even according to Flutter SDK) to use the approach similar to MultiChildLayoutDelegate.

I see great value in Riverpod even if it doesn't cache. It would still be reactive. It is great as an elegant, testable compile time dependency solution. Plus it makes lazy loading in Flutter Web so much easier as all the dependencies are linked at compile time. 

Truth be told I first came across recoiljs and wanted something similar in Flutter. I dropped the idea thinking it would be very difficult without power of typescript to implement (chaining modifiers). But you were able to create this despite Dart's type system and I just want to know how to extend it a little.

**Comment by rrousselGit** [comment]
Maybe I am missing something. Are you trying to use providers for local widget state instead of shared state?

**Comment by srikrsna** [comment]
I am trying to replicate Provider's behaviour.

```dart
ChangeNotifierProvider.value(
   value: noti,
   child: StaticChild(
        ....
       Consumer(
             deeplyNestedWidgetOne,
       )
       Consumer(
             deeplyNestedWidgetTwo,
       )
    )
);
```

Two deeply nested widgets have a common ancestor and share state. In the above scenario, Only the relevant parts would be built without affecting the static portions of the widget tree. The lifecycle of the notifier is managed by the Provider at the top.

**Comment by rrousselGit** [comment]
The v1.0 of Riverpod supports nesting any provider. So you can do exactly that

**Comment by srikrsna** [comment]
> The v1.0 of Riverpod supports nesting any provider.

I'm not sure how, but I'll wait for release and documentation and revisit this if necessary. Thank you for patiently answering  my queries

**Comment by rrousselGit** [comment]
I'll close this since I do not intend on adding this feature.
