### ISSUE TITLE
[hooks_riverpod] how to 'watch' a provider in a 'HookWidget'

### ISSUE THREAD

**Issue by aoatmon** [rrousselGit/river_pod#550]
**Describe what scenario you think is uncovered by the existing examples/articles**

given a provider

```dart
final fooPod = Provider.autoDispose<StreamController>(
  (ref) {
    final controller = StreamController();
 
    ref.onDispose(() {
      print('###### DISPOSING #######');
      controller.close();
    });
   
    return controller;
  },
);

final barPod = Provider<ValueNotifier<int>>(
(ref) {
    final notifier = ValueNotifier<int>(0);
    return notifier;
  },
);

```

and a `HookWidget`

```dart
class FooWidget extends HookWidget {
  @override
  Widget build(BuildContext context) {
    final foo = useProvider(fooPod);
    final bar = useProvider(barPod);
    foo.stream.listen((event) => bar.value++);
    return Container();
  }
}

```

the provider is disposed immediately and not when the widget is disposed

**Describe why existing examples/articles do not cover this case**
 the example [provided](https://pub.dev/packages/hooks_riverpod)
 

>  ```dart
>  class Example extends ConsumerWidget {
>   @override
>   Widget build(BuildContext context, ScopedReader watch) {
>     final count = watch(counterProvider);
>     return Text(count.toString());
>   }
> }
>  ```

doesn't describe how to interact with `useProvider`

**Additional context**
https://stackoverflow.com/questions/68174761/how-to-watch-a-provider-in-a-hookwidget

**Comment by rrousselGit** [comment]
That isn't the case.

Are you sure that it isn't that your FooWidget gets disposed?

**Comment by aoatmon** [comment]
I didn't use the streamcontroller directly, was though another provided that 

- wasn't `autodispose`
- was reading the fooPod with `read` and not `watch`

thank you for looking it up, and apologize for the inconvenience
