### ISSUE TITLE
hooks_riverpod 1.0.0-dev.2 The context does not have a read method

### ISSUE THREAD

**Issue by miaosun009** [rrousselGit/river_pod#551]
hooks_riverpod 1.0.0-dev.2
The context does not have a read method

![image](https://user-images.githubusercontent.com/17589354/123830162-a1718e80-d935-11eb-9075-4fb8d76c6229.png)

**Comment by TimWhiting** [comment]
Use `ref.read` instead

**Comment by miaosun009** [comment]
> 使用`ref.read`替代

How to achieve the effect of Provider.of<T>(context,listen:false) in Provider

**Comment by miaosun009** [comment]
> Use `ref.read` instead

How to achieve the effect of Provider.of<T>(context,listen:false) similar to Provider

**Comment by TimWhiting** [comment]
That is what `ref.read` does, `ref.watch` achieves the effect of `Provider.of(context, listen: true)`

**Comment by davidmartos96** [comment]
In any case, watch out when using read in the build method. The widget will not rebuild when the value changes and you may not want that. 
If you want to react to changes you should use `ref.watch`. And if you want to obtain the value once without listening it's good practice to do it inside `initState`. The build method can get called at any time by the Flutter framework

**Comment by miaosun009** [comment]
> That is what `ref.read` does, `ref.watch` achieves the effect of `Provider.of(context, listen: true)`

When I need to read a provider in a dart class, I can't get Ref. what should I do?

```
class MyClass{
 T getInfo(BuildContext context){
        final info = Provider.of(context, listen: false).info;
        retrun info;
   }
}
```

**Comment by rrousselGit** [comment]
Pass a WidgetRef or ProviderRef to the class/function

**Comment by miaosun009** [comment]
> Pass a WidgetRef or ProviderRef to the class/function

![image](https://user-images.githubusercontent.com/17589354/123911379-4f208400-d9ae-11eb-8d9c-162b03f8a3a2.png)
Is that all right?

**Comment by rrousselGit** [comment]
No, you shouldn't do that. Get a WidgetRef or ProviderRef

**Comment by miaosun009** [comment]
> No, you shouldn't do that. Get a WidgetRef or ProviderRef
Is it possible to support the use of read in a manner similar to that shown in the picture below？
![image](https://user-images.githubusercontent.com/17589354/124102355-df37f980-da92-11eb-984a-1608420aa1a1.png)

**Comment by miaosun009** [comment]
> No, you shouldn't do that. Get a WidgetRef or ProviderRef

Is it possible to support the use of read in a manner similar to that shown in the picture below？

![image](https://user-images.githubusercontent.com/17589354/124102355-df37f980-da92-11eb-984a-1608420aa1a1.png)

**Comment by rrousselGit** [comment]
Riverpod purposefully does not do that.

This is anti-pattern / bad practice.

**Comment by rrousselGit** [comment]
Closing as this is expected
