### ISSUE TITLE
Get watch without Consumer Widget

### ISSUE THREAD

**Issue by danieldoddjr** [rrousselGit/river_pod#552]
**Is your feature request related to a problem? Please describe.**
I keep running into the need to watch outside of the widget tree

**Describe the solution you'd like**
Something like "ProviderContainer()" but instead of only read have watch also.

**Describe alternatives you've considered**
Cant think of any that would help when needing to access state and provide changes when they happen in business logic.

**Comment by rrousselGit** [comment]
I do not understand. What exactly are you trying to do?

**Comment by danieldoddjr** [comment]
We have hit this a few times. Currently we are trying to watch for the state of display mode to update an extension to the ColorScheme. In our case it is just one of two strings "light" or "dark" and a turnary operator to select what color to use based on said display mode. 

```
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'AppThemeChangeNotifier.dart';

extension CustomColorScheme on ColorScheme {
  Color get success => ProviderContainer().read(appThemeChangeNotifier).getThemeMode == 'light' ? Color(0xffE1E1E1) : Color(0xff222222);
}
```

This need to notice when a change in display mode happens in the change notifier.

**Comment by danieldoddjr** [comment]
I have a way to get this to work without watch. I make the change notifier a global variable and then use it in my business logic and also pass it via riverpods.

```
AppThemeChangeNotifier appThemeChangeNotifierGlobal = AppThemeChangeNotifier();
final appThemeChangeNotifier = ChangeNotifierProvider((ref) => appThemeChangeNotifierGlobal);
```

Not ideal but it works!

**Comment by davidmartos96** [comment]
Why not have a successColor getter inside your ChangeNotifier? That way you are forced to watch for changes in the notifier to access the property.

**Comment by danieldoddjr** [comment]
Extending the ColorScheme is nicer for our UI devs as they can use "Theme.of(context).success" like all the other default theme styles.

**Comment by rrousselGit** [comment]
> We have hit this a few times. Currently we are trying to watch for the state of display mode to update an extension to the ColorScheme. In our case it is just one of two strings "light" or "dark" and a turnary operator to select what color to use based on said display mode.
> 
> ```
> import 'package:flutter/material.dart';
> import 'package:flutter_riverpod/flutter_riverpod.dart';
> import 'AppThemeChangeNotifier.dart';
> 
> extension CustomColorScheme on ColorScheme {
>   Color get success => ProviderContainer().read(appThemeChangeNotifier).getThemeMode == 'light' ? Color(0xffE1E1E1) : Color(0xff222222);
> }
> ```
> 
> Read does not work when a change in display mode happens in the change notifier.

Creating a ProviderContainer like this is an anti-pattern and you have a memory leak

You should instead do something like `ref.watch(appThemeChangeNotifier).success`

**Comment by davidmartos96** [comment]
@danieldoddjr Then you could have a wrapper over ThemeData or a custom Inherited Widget instead of a provider

**Comment by danieldoddjr** [comment]
#

> > We have hit this a few times. Currently we are trying to watch for the state of display mode to update an extension to the ColorScheme. In our case it is just one of two strings "light" or "dark" and a turnary operator to select what color to use based on said display mode.
> > ```
> > import 'package:flutter/material.dart';
> > import 'package:flutter_riverpod/flutter_riverpod.dart';
> > import 'AppThemeChangeNotifier.dart';
> > 
> > extension CustomColorScheme on ColorScheme {
> >   Color get success => ProviderContainer().read(appThemeChangeNotifier).getThemeMode == 'light' ? Color(0xffE1E1E1) : Color(0xff222222);
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Read does not work when a change in display mode happens in the change notifier.
> 
> Creating a ProviderContainer like this is an anti-pattern and you have a memory leak
> 
> You should instead do something like `ref.watch(appThemeChangeNotifier).success`

This was just an example to illustrate the issue. How do you propose I get "ref" in the CustomColorScheme?

**Comment by rrousselGit** [comment]
You will need a tree.
Either the provider tree or the widget tree. You can't do without any of them 

So either within a Consumer or a Provider.

The correct place for this logic is most definitely inside the appTheme provider

**Comment by danieldoddjr** [comment]
I dont think putting an extension in a change notifier is the right call here. It sounds like if I need to use an extension riverpods is not the right solution. It can work if I make the change notifier as a global variable though and that does cover some other issues we have had in dealing with watch on data repositories.
