### ISSUE TITLE
Update partial value in FutureProvider without refresh.

### ISSUE THREAD

**Issue by barabanskii** [rrousselGit/river_pod#553]
It will be good to have the opportunity to update the value in FutureProvider without refreshing it.

Description. Let's say we have FutureProvider<List<User>> and some users have changed their names. How can I update those users in the provider?

**Comment by rrousselGit** [comment]
This wouldn't be a Future anymore, but a Stream.

**Comment by rrousselGit** [comment]
I'll close this, since there's nothing doable here. You could switch to a StreamProvider or StateNotifierProvider instead
