### ISSUE TITLE
Select inside Provider

### ISSUE THREAD

**Issue by Poweranimal** [rrousselGit/river_pod#555]
**Describe what scenario you think is uncovered by the existing examples/articles**
Can one use a `select` statement inside a Provider?

**Describe why existing examples/articles do not cover this case**
The current documentation only showcases `watch` statements inside a provider, but no mention of `select` statements.

**Additional context**
Example:
```dart
final clientProvider = Provider<Client>((ref) {
    final baseUrl = ref.watch(configProvider).baseUrl;
    return Client(baseUrl: baseUrl);
})
```
I wonder, if one could replace the `final baseUrl = ref.watch(configProvider).baseUrl ;` with a `select` statement that only refreshes the provider on a `baseUrl` value change.

**Comment by davidmartos96** [comment]
You can do that with riverpod 1.0.0-dev https://pub.dev/packages/flutter_riverpod/versions/1.0.0-dev.2

Extracted from the changelog:

![image](https://user-images.githubusercontent.com/22084723/123972807-7af63680-d9bb-11eb-8dce-afaa3506ace9.png)

**Comment by Poweranimal** [comment]
Thanks, this looks promising.
But us something similar also possible with major version 0.x.x?

**Comment by rrousselGit** [comment]
Closing since this is part of 1.0.0
