### ISSUE TITLE
State Management with reusability

### ISSUE THREAD

**Issue by trevhud** [rrousselGit/river_pod#558]
A coworker new to riverpod said it reminds him of redux (in a bad way). I love it so far but can see similar potential for loss in widget reusability.

Is there a way to get the best of both worlds and have universal state management, through StateNotifierProviders for example, but also be able to explicitly pass data through to child widgets via their constructors?

Is it just a matter of using watch/useProvider on the parent level and passing the data into stateless child widgets? Will these widgets still be reactive and build with the latest data from the StateNotifier's state?

What about for reads? Would it be a callback passed into the child widget from the parent that does the read using its (the parent's) context?

I haven't seen this pattern anywhere and I was hoping someone could weigh in on whether it makes sense or it's an antipattern.

Thanks @rrousselGit and the community!

**Comment by rrousselGit** [comment]
> Is it just a matter of using watch/useProvider on the parent level and passing the data into stateless child widgets? Will these widgets still be reactive and build with the latest data from the StateNotifier's state?

Indeed it is.

You can decouple a widget from its dependency on Riverpod by receiving the different values from parameters (including potential "onTap" callbacks).
Rebuilds with ref.watch will continue to work as expected

**Comment by trevhud** [comment]
Perfect, thanks @rrousselGit !
