### ISSUE TITLE
package:flutter_riverpod/all.dart should be removed

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [rrousselGit/river_pod#561]
### Problem

My IDE still sometimes makes me import `package:flutter_riverpod/all.dart`, obviously resulting in this warning:

> 'package:flutter_riverpod/all.dart' is deprecated and shouldn't be used. use `flutter_riverpod/flutter_riverpod.dart` instead. (Documentation)

### Solution

I am thinking, with `riverpod: 1.0.0`, we have the opportunity to get rid of the unidiomatic library and only keep the new one.

**Comment by rrousselGit** [comment]
The `all.dart` is removed in the 1.0.0-dev version, so I will close this.

**Comment by creativecreatorormaybenot** [comment]
@rrousselGit was it already removed in the first preview version? Because then I feel bad about opening the issue 🙈 

I thought I opened it after seeing `package:flutter_riverpod/all.dart` in the preview version.

**Comment by rrousselGit** [comment]
I don't remember :shrug:
