### ISSUE TITLE
Marvel sample uses code that documentation says we shouldn't write

### ISSUE THREAD

**Issue by wujek-srujek** [rrousselGit/river_pod#569]
The sample code
https://github.com/rrousselGit/river_pod/blob/bcb76e2eb4f2d331bac1d179a730c755ae7257e8/examples/marvel/lib/src/screens/character_detail.dart#L49
and
https://github.com/rrousselGit/river_pod/blob/bcb76e2eb4f2d331bac1d179a730c755ae7257e8/examples/marvel/lib/src/screens/home.dart#L36
(possibly more places ass well) uses `read` within a provider, while the documentation FAQ https://riverpod.dev/docs/concepts/combining_providers#can-i-read-a-provider-without-listening-to-it explicitly says this should not be done (with a fat red fiery warning): DON'T CALL READ INSIDE THE BODY OF A PROVIDER.

Have best practices changed and the code is not in sync with the docs, or am I misunderstanding something?

**Comment by rrousselGit** [comment]
Good catch, fixed
