### ISSUE TITLE
'overrideWithValue' doesn't influence providers watching the overridden provider

### ISSUE THREAD

**Issue by wujek-srujek** [rrousselGit/river_pod#575]
I'm using version 1.0.0-dev.2.

There are 2 providers: `iProvider` which provides an `int`, and `wrapperProvider` which provides something else based on the value from `iProvider` - in the sample below a simple object that wraps the `int`. `iProvider` returns `0` by default, but it is overridden (using `overrideWithValue`) near the top of the widget tree to return `17`. Then, in the UI itself, 2 values are displayed: the `i` value returned by `iProvider`, and the wrapper value returned by `wrapperProvider`.

The two values differ: the value returned from `iProvider` returns the overridden value of `17`, while the object returned by `wrapperProvider` contains the default value of `0`.

The same behavior can be reproduced if `overrideWithProvider` instead of `overrideWithValue` is used.

It seems overriding a provider that other providers watch has no effect on these watching providers.

**To Reproduce**

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return const ProviderScope(
      child: MaterialApp(
        home: Page(i: 17),
      ),
    );
  }
}

class Page extends StatelessWidget {
  final int i;

  const Page({required this.i});

  @override
  Widget build(BuildContext context) {
    return ProviderScope(
      overrides: [
        iProvider.overrideWithValue(i),
      ],
      child: Scaffold(
        body: Consumer(
          builder: (context, ref, _) {
            final i = ref.watch(iProvider);
            final wrapper = ref.watch(wrapperProvider);

            return Center(
              child: Text(
                'Good:  $i\n' // 17
                'Wrong: ${wrapper.i}', // 0
              ),
            );
          },
        ),
      ),
    );
  }
}

// Riverpod.

final iProvider = Provider<int>((ref) => 0);

@immutable
class Wrapper {
  final int i;

  const Wrapper(this.i);
}

final wrapperProvider = Provider<Wrapper>(
  (ref) {
    final i = ref.watch(iProvider);
    return Wrapper(i);
  },
);
```

**Expected behavior**

I expect the two values `i` from `iProvider` and `wrapper.i` from `wrapperProvider` to have the same value as `wrapperProvider` should get the overridden value for `iProvider`.

**Comment by rrousselGit** [comment]
This is expected.
You should override the providers that depends on the overriden provider too

**Comment by wujek-srujek** [comment]
Ok, this is of limited help then, and clearly not what I had hoped for for my use case.

**Comment by imtoori** [comment]
I was expecting this to be working as well :/

**Comment by rrousselGit** [comment]
That's not feasible.

But the linter catches this. Enable it to avoid the mistake

**Comment by hampsterx** [comment]
hmm I have done like so with `AutoDisposeFutureProviderFamily` in my tests..

```
ProviderScope(
              overrides: [
                abc.overrideWith((ref) => MockABC()),
  // These need to be reinitialized because they depend on the above!

    xyz.overrideWithProvider(xyz.call),
```

Eg `xyz` relied on `abc` provider and its fine.

however trying this with `AutoDisposeFutureProvider` no worky

```
   xyz.overrideWithProvider(xyz.call),
```

`overrideWithProvider` deprecated and `call` undefined. 

what am I doing wrong here?

I have to say it makes testing far harder having to override mocked out providers especially if not familiar with codebase and seen the requirement heh

**Comment by hampsterx** [comment]
ahh as long as my providers use `dependencies:` everything is fine testing wise, joy~
