### ISSUE TITLE
Changing a single index value in a nested list

### ISSUE THREAD

**Issue by varunbhalerao56** [rrousselGit/river_pod#577]
**Describe the bug**
I have an object called "BuyForm" and it has other objects inside it "ProductStep" and "ApplicantInfo". I am using StateNotifierProvider to edit the values and everything. Once the form is complete I am the "BuyForm" to a List<BuyForm>  

I also have a function that duplicates the "BuyForm" in the list with a different uid which I am using to edit the specific form. The values in applicant info get edited as expected. But the ones with the "ProductStep"  don't.  The "ProductStep" object has a list of Products. But when I change the quantity of those products or edit any values, it edits all products that are the same in the list even though I am targeting a specific uid.

Sorry if this is very confusing, just unsure on how to explain.

**To Reproduce**

```
///this will be in the state notifier provider and changing
///a single `objectC` in `List<ObjectC>` in `MainObject` in `List<MainObject>` causes the error
List<MainObject> mainObject = [];


class MainObject {
  ObjectA? objectA;
  ObjectB? objectB;
}

class ObjectA {
  String? name; //editing this will work fine
}

class ObjectB {
  String? name; //editing this will work fine
  List<ObjectC>? ids; //changing this will change all the values with same values in other
}

class ObjectC {
  String? id;
}
```

**Expected behavior**
Change the single value of the nested object's list.

**Comment by rrousselGit** [comment]
Did you somehow mutate an object instead of making a copy of it?

**Comment by varunbhalerao56** [comment]
> Did you somehow mutate an object instead of making a copy of it?

@rrousselGit Yes I did, I figured out the solution by making another copy of the list in a new list and then using that. But not sure if that's the best method.
