### ISSUE TITLE
Provider depending on scoped Provider sees wrong value in 1.0.0-dev.2

### ISSUE THREAD

**Issue by ngg** [rrousselGit/river_pod#578]
**Describe the bug**

If I use version `1.0.0-dev.2` and a `Provider` depends on another `Provider` which is overridden using `ProviderScope`, then it sees the default value instead of the overridden.

**To Reproduce**

The following code works with `flutter_riverpod: ^0.14.0` and each list element shows `OK $index`:
```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final indexProvider = ScopedProvider<int>((watch) => -1);
final stringProvider =
    ScopedProvider<String>((watch) => watch(indexProvider).toString());

class ItemWidget extends ConsumerWidget {
  const ItemWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, ScopedReader watch) {
    final index = watch(indexProvider);
    final str = watch(stringProvider);

    if (index.toString() == str) {
      return Text("OK $index");
    } else {
      return Text("BAD $index != $str");
    }
  }
}

void main() {
  runApp(
    ProviderScope(
      child: MaterialApp(
        home: Scaffold(
          body: ListView.builder(
              itemBuilder: (context, index) => ProviderScope(
                    overrides: [indexProvider.overrideWithValue(index)],
                    child: ItemWidget(),
                  )),
        ),
      ),
    ),
  );
}
```

When I try to update the same code to `flutter_riverpod: ^1.0.0-dev.2` then `stringProvider` sees that `indexProvider` has the default value of `-1`, resulting in `BAD $index != -1` errors:
```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final indexProvider = Provider<int>((ref) => -1);
final stringProvider =
    Provider<String>((ref) => ref.watch(indexProvider).toString());

class ItemWidget extends ConsumerWidget {
  const ItemWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final index = ref.watch(indexProvider);
    final str = ref.watch(stringProvider);

    if (index.toString() == str) {
      return Text("OK $index");
    } else {
      return Text("BAD $index != $str");
    }
  }
}

void main() {
  runApp(
    ProviderScope(
      child: MaterialApp(
        home: Scaffold(
          body: ListView.builder(
              itemBuilder: (context, index) => ProviderScope(
                    overrides: [indexProvider.overrideWithValue(index)],
                    child: ItemWidget(),
                  )),
        ),
      ),
    ),
  );
}
```

**Comment by rrousselGit** [comment]
This is expected.

You need to override both the scoped provider and the providers that depends on it.

**Comment by amitkot** [comment]
@rrousselGit how would this work in case there is a complicated Provider that depends on a very simple Scoped Provider?

I have a complicated provider that builds the view model for one of my screens. I want to use a localized string in this provider, so I wrap the Screen widget with a ProviderScope that overrides that string. According to what you wrote in the above comment my approach would not work as I will also need to override the complicated provider somehow when I override the simple string provider?

Something along the lines of:

```dart
final stringProvider = Provider<String>((ref) => throw UnimplementedError());

final viewModelProvider = StreamProvider.autoDispose.family<ScreenViewModel, String>((ref, id) {
  final str = ref.watch(stringProvider);
  // ... (complicated implementation)
});

class Screen extends HookConsumerWidget {
  const Screen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final id = ...;
    return ProviderScope(
      overrides: [
        stringProvider.overrideWithValue(AppLocalization.of(context).someString),
      ],
      child: ScreenContents(
        viewModel: ref.watch(viewModelProvider(id)),
      ),
    );
  }
}
```

**Comment by rrousselGit** [comment]
Yes.

If you override a scoped provider, you need to also override the providers that depends on it.

**Comment by amitkot** [comment]
This design decision makes it very hard to use scoped providers in complicated scenarios, no?

In my case I decided instead to use a `StateProvider` that returns an empty string by default and I use a `useEffect` call to run a Future.microtask that updates the `StateProvider` to the localized string.
It works but a scoped provider would have probably been a cleaner solution.

**Comment by ngg** [comment]
I really liked the idea of scoped providers, but this makes them unusable for larger applications (at least in our use-case). Now I'm thinking about passing everything in parameters to widgets, but that will be really ugly. I think this decision needs to be reconsidered...

**Comment by rrousselGit** [comment]
This isn't a "decision". There's simply no way around it.
