### ISSUE TITLE
Can nested ProviderScope override provider?

### ISSUE THREAD

**Issue by nogaten** [rrousselGit/river_pod#586]
**Describe the bug**
I'm using riverpod 1.0.0-dev.3.
I cannot override the provider when using nested ProviderScope.

**To Reproduce**
```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:riverpod/riverpod.dart';

final valueProvider = Provider<int>((ref) => throw UnimplementedError());

final isEvenProviderFamily = Provider.family.autoDispose<bool, int>((ref, value) => value.isEven);

final isEvenProvider = Provider.autoDispose<bool>((ref) {
  final value = ref.watch(valueProvider);
  return ref.watch(isEvenProviderFamily(value));
});

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ProviderScope(
      child: MaterialApp(
        home: MyHomePage(),
      ),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView.builder(
        itemCount: 10,
        itemBuilder: (context, i) {
          return ProviderScope(
            overrides: [
              valueProvider.overrideWithValue(i),
            ],
            child: ListItem(),
          );
        },
      ),
    );
  }
}

class ListItem extends ConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final value = ref.watch(valueProvider);
    final isEven = ref.watch(isEvenProvider);
    return ListTile(
      title: Text('$value.isEven: $isEven'),
    );
  }
}
```

**Expected behavior**
Is it possible to override the provider in nested ProviderScope?

**Comment by julienlebren** [comment]
Your provider `isEvenProvider` is watching `valueProvider` outside the scope.
I don't understand your code, why is there `isEvenProvider` and `isEvenProviderFamily`?

I think this is overcomplicated, because you could simply do:
class ListItem extends ConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final value = ref.watch(valueProvider);
    final isEven = ref.read(isEvenProviderFamily(value));
    return ListTile(
      title: Text('$value.isEven: $isEven'),
    );
  }
}

**Comment by nogaten** [comment]
I'm watching isEvenProvider under child ProviderScope.

**Comment by julienlebren** [comment]
You override `valueProvider` in your child `ProviderScope` but `isEvenProvider` watches the value of `valueProvider` which is defined in the root `ProviderScope`.

**Comment by nogaten** [comment]
I understand your comment. Thank you.
