### ISSUE TITLE
autoDispose not working with maintainState = true

### ISSUE THREAD

**Issue by bhanuka96** [rrousselGit/river_pod#589]
Is there any way to `dispose` this FutureProvider when user `logout`? 

Because I need to reduce API calls that's why I set `ref.maintainState = true`. But when the user log-out I need to `dispose` it. Otherwise wrong data is displayed.

```
final userServiceProvider = Provider.autoDispose<UserRepository>((ref) {
  return UserRepository(Dio());
});

final userFutureProvider = FutureProvider.autoDispose<UserModel?>((ref) async {
  ref.maintainState = true;
  .... some logic is here
  return user;
});
```

**Comment by rrousselGit** [comment]
You can't both have "maintainState true" and expect the state to automatically be disposed

You will need to remove the maintainState call

**Comment by bhanuka96** [comment]
@rrousselGit Thanks for your quick reply. Please let me know is there any way to disable API calls when user login.
