### ISSUE TITLE
It's possible to only update needed property  ?

### ISSUE THREAD

**Issue by zgramming** [rrousselGit/river_pod#59]
In **todos** [example](https://github.com/rrousselGit/river_pod/blob/f6da62c101ed19a9ecf186f84ad790fd83a301b6/examples/todos/lib/todo.dart#L36-L48) , to only update property **completed** we should defined another property again . It's possible to only updated only needed  property ?  something like this : 

```
 state = [
      for (final todo in state)
        if (todo.id == id)
          Todo(
            completed: !todo.completed,
          )
        else
          todo,
    ];
```
already try this approach,but make property another **completed** null.  Is this really the way it works?

Because i have alot of property and only need update 1 of them. But i should defined another property again. 

### My example
```
state = [
      for (final item in state)
        if (item.idUtang == idUtang)
          UtangModel(
            idUtang: item.idUtang,
            pembertang: item.pembertang,
            pengutang: item.pengutang,
            totalUtang: item.totalUtang,
            sisaUtang: item.sisaUtang,
            status: '1',
            keterangan: item.keterangan,
            tglKembali: item.tglKembali,
            selfie: item.selfie,
            createdDate: item.createdDate,
            ttd: item.ttd,
          )
        else
          item
    ];
```

Thank's.

**Comment by rrousselGit** [comment]
The recommendation would be to implement a copyWith method

A good solution for that is to use  https://github.com/rrousselGit/freezed which generates it for you.

So you'd have:
```dart
state = state.copyWith(status: '1')
```

**Comment by zgramming** [comment]
@rrousselGit  after learning about this package,  `copyWith` dont have named parameter or should type manually ?  `ctrl + space` not showing it. 

### UtangModel.dart

```
@freezed
abstract class UtangModel with _$UtangModel {
  const factory UtangModel({
    String idUtang,
    UserGoogleModel pembertang,
    UserGoogleModel pengutang,
    String totalUtang,
    String sisaUtang,
    DateTime tglKembali,
    String status,
    String keterangan,
    String selfie,
    String ttd,
    DateTime createdDate,
  }) = _UtangModel;
  factory UtangModel.fromJson(Map<String, dynamic> json) => _$UtangModelFromJson(json);
}

```

**Comment by rrousselGit** [comment]
You're facing this issue https://github.com/rrousselGit/freezed/issues/137

It's a bug in the auto completion

**Comment by zgramming** [comment]
@rrousselGit  glad to hear , i think i can close this now.

**Comment by Parkar99** [comment]
> @rrousselGit glad to hear , i think i can close this now.

You can use `copyWith.call()` to have autocomplete. `freezed` delegates the call to `copyWith()` to the `call()` method so it should work the same
