### ISSUE TITLE
Protesting Removal of useProvider and HookWidget

### ISSUE THREAD

**Issue by wazini-john** [rrousselGit/river_pod#590]
In `hooks_riverpod` `1.0.0-dev.4` .. You are removing  `useProvider` . Most of us moved from provider to riverpod to reduce the boilerplate code. Can you please bring it back ? 
It's removal will break more than 10 apps my team and I have put into production already.

You were selling `riverpod` as `provider but different`. I see no difference in deprecating some core functionalities. Bring back `HookWidget`

PLEASE @rrousselGit

**Comment by smiLLe** [comment]
It is not like you have to migrate until tomorrow or your apps stop working....

**Comment by wazini-john** [comment]
@smiLLe I know but what if there's a bug fix or a new feature on a new version that we need in our apps. Picturing those scenarios we can't upgrade because of the missing `HookWidget`

**Comment by wazini-john** [comment]
Flutter hooks... used by hooks_riverpod... was created to sort of emulate React Hooks which uses the `use` keyword. Why remove the `useProvider` hook ?

**Comment by smiLLe** [comment]
It is not that huge change
```dart
class Example extends HookConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    useState(...);
    int count = ref.watch(counterProvider);
    ...
  }
}
```

**Comment by wazini-john** [comment]
What about `FutureProvider` and `StreamProvider`

```
class Example extends HookWidget {
  @override
  Widget build(BuildContext context) {
    // useState(...);
    final future = useProvider(myFutureProvider);
    return future.when(
        data: (data) {
          return Container();
        },
        loading: () => CircularProgressIndicator(),
        error: (e, s) => Text("error"));
  }
}

```

**Comment by rrousselGit** [comment]
All hooks works within HookConsumerWidget. Including useFuture

**Comment by smiLLe** [comment]
```dart
class Example extends HookConsumerWidget  {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // useState(...);
    final future = ref.watch(myFutureProvider);
    return future.when(
        data: (data) {
          return Container();
        },
        loading: () => CircularProgressIndicator(),
        error: (e, s) => Text("error"));
  }
}


```

**Comment by wazini-john** [comment]
@rrousselGit ... Is `useProvider` still there ?

**Comment by wazini-john** [comment]
Can't `HookWidget` and `HookConsumerWidget` coexist ?

**Comment by smiLLe** [comment]
You will use `ref.watch` in favor of `useProvider`.
You will use `HookConsumerWidget` in favor of `HookWidget` when you want to watch a provider.
So why do you still need `useProvider` in that case?

**Comment by matpag** [comment]
> Can't `HookWidget` and `HookConsumerWidget` coexist ?

It would only add confusion and the migration is pretty easy.
Finally with Riverpod 1.0.0 we are getting e cleaner API surface without multiple ways to do the same thing.

**Comment by wazini-john** [comment]
@smiLLe The addition of `WidgetRef`

**Comment by smiLLe** [comment]
@rrousselGit  What is the prefered way of using a provider in a custom hook?

**Comment by julienlebren** [comment]
It's a matter of unifying the syntax for listening providers. See #335

**Comment by rrousselGit** [comment]
> What is the prefered way of using a provider in a custom hook?

Passing `ref` as parameter to the hook.

> @rrousselGit ... Is `useProvider` still there ?

No.

But you can make it yourself

With the current dev release, a `useProvider` would be:

```dart
T useProvider<T>(ProviderBase<T> provider) {
  final context = useContext();
  final container = ProviderScope.containerOf(context);
  
  final result = useState<T?>(null);

  useEffect(() {
    final sub = container.listen<T>(provider, (value) => result.value = value);
    return sub.close;
  }, [container, provider]);

  return result.value as T;
}
```


I may or may not add it to `hooks_riverpod` again. We'll see.

**Comment by smiLLe** [comment]
@rrousselGit Why is there no `final ref = useProviderRef()`? Because of inconsitent API or is it just not possible?

**Comment by TimWhiting** [comment]
The useRef route seems like it would give a more consistent API and make it so you can watch providers without the hook restrictions. If you were to add a hook back into hooks_riverpod I would vote for that option.

**Comment by rrousselGit** [comment]
A useRef requires significant work

**Comment by venkatd** [comment]
@wazini-john I just migrated our app to the latest hooks_riverpod and I believe the new version without `useProvider` is the superior to what was there before. Here are some reasons for it:

* `ref.watch` is **much** clearer than `useProvider`. As someone reading the code and for new developers, when they see `ref.watch` in a provider OR a widget, they can assume the rebuild logic and return value is the same. The additional characters typed `WidgetRef ref` and `ConsumerHookWidget` do not justify a 2nd abstraction to read and understand. I have experienced this first hand when educating developers on how to use providers inside other providers vs. how to use providers inside a build method.
* Separating business logic from UI logic becomes easier. If I want to clean up my build method, then you can see a number of `ref.watch` calls in the build method. These can easily get pulled into their own provider.
* You can write your own `useProvider` if you really want to. (I would recommend against doing so unless you see a major benefit.)

And if we are talking about the migration process:

* The actual migration process is very mechanical. We have a fairly large app and it took me about 90 minutes to do the whole migration.
* We started using riverpod before it was 1.x. This means we have agreed to breaking changes for the advantage of allowing riverpod to converge on the best API possible before it hits 1.x. I and many members of the community are willing to invest some time in migrating our code for the benefit of a better api long term.

**Comment by wazini-john** [comment]
`useProvider` should be brought back in `hooks_riverpod` and `ref.watch` should be part of `flutter_riverpod` by convention

**Comment by wazini-john** [comment]
@venkatd We have 10 apps in production currently and working on 3. Migrating all of them would be such a hustle unless there is a `hooks migrate` command

**Comment by rrousselGit** [comment]
> * Separating business logic from UI logic becomes easier. If I want to clean up my build method, then you can see a number of `ref.watch` calls in the build method. These can easily get pulled into their own provider.

Didn't think of that one!

Sounds like "extract as Provider" would be cool 😊

**Comment by rrousselGit** [comment]
> @venkatd We have 10 apps in production currently and working on 3. Migrating all of them would be such a hustle unless there is a `hooks migrate` command

The migration will take a second. There is a command line that does everything for you.

**Comment by wazini-john** [comment]
Will the functionality be brought back ?

**Comment by rrousselGit** [comment]
The functionality never left. Only the syntax changed, but you can still do exactly the same thing

**Comment by wazini-john** [comment]
`ref.watch` sounds and looks like it belongs to `flutter_riverpod`.  The hook version should be `useProvider`

**Comment by venkatd** [comment]
@wazini-john there is `HookConsumerWidget` which replaces the need for `useProvider`. Here's an example below...

BEFORE:
```
class AuthenticatedScreen extends HookWidget {
  AuthenticatedScreen({required this.child});

  final Widget child;

  @override
  Widget build(BuildContext context) {
    final authState = useProvider(authStateProvider);

    if (authState is AuthStateSignedIn) {
      return _AuthenticatedAppDependencies(child: child);
    }

    return authState is AuthStateUnknown
        ? LoadingOverlay(showSpinner: false)
        : SignInScreen();
  }
}
```

AFTER:
```dart

class AuthenticatedScreen extends HookConsumerWidget {
  AuthenticatedScreen({required this.child});

  final Widget child;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final authState = ref.watch(authStateProvider);

    if (authState is AuthStateSignedIn) {
      return _AuthenticatedAppDependencies(child: child);
    }

    return authState is AuthStateUnknown
        ? LoadingOverlay(showSpinner: false)
        : SignInScreen();
  }
}
```

As you can see, it's the same number of lines of code. And it's clearer because it uses the same `ref.watch` we are used to in provider declarations.

**Comment by wazini-john** [comment]
What if the code contains `useState`?

**Comment by smiLLe** [comment]
@wazini-john Using `HookConsumerWidget` you can use hooks like `useState` and still use `ref.watch` for providers

**Comment by rrousselGit** [comment]
Closing since this discussion should be inside the RFC instead #335
