### ISSUE TITLE
Reader not working inside class

### ISSUE THREAD

**Issue by leornt** [rrousselGit/river_pod#597]
**Describe the bug**
I've created my class and just trying to read the value of my provider inside it, not working at all
```
I/flutter ( 5367): NoSuchMethodError: The method 'call' was called on null.
I/flutter ( 5367): Receiver: null
I/flutter ( 5367): Tried calling: call<Object>(Instance of 'ChangeNotifierProvider<BlocProfile>')
```

**To Reproduce**
Global Var
```dart
blocProfile = ChangeNotifierProvider((ref) => BlocProfile()),
```
API file
```dart
class API {
    Reader read;
    
    void test() {
        print(read(blocProfile).user);
    }
}
```

**Expected behavior**
It should return my user object, as it works inside the own bloc (ChangeNotifierProvider) file

**Comment by rrousselGit** [comment]
It seems you forgot to initialize the "read" variable.

**Comment by leornt** [comment]
And how should I do it the right way? Cause this exact code works inside other `ChangeNotifierProvider` files

**Comment by wujek-srujek** [comment]
Are you somehow assigning anything to `read` externally? Like doing:
```dart
final bb = BlocBase();
bb.read = ... // <= assignment here
...
bb.initNavigator() // <= call here
```
Apart from something like this, there is no way this code works as `read` would never be initialized, so `null` by default.

**Comment by leornt** [comment]
Nope, I just assign the `Reader read;` there's no other code that change this var, there's only my pointer file, I'll post the code here as well
```dart
final blocProfile = ChangeNotifierProvider((ref) => BlocProfile()),
```
This is the file that I use to define the references as global vars

**Comment by rrousselGit** [comment]
You need to do:

```dart
final blocProfile = ChangeNotifierProvider((ref) => BlocProfile(ref.read)),

class BlocProfile extends ChangeNotifier {
  BlocProfile(this.read);

  final Reader read;
}
```

**Comment by leornt** [comment]
Okay, I tried to initialize the `Reader` inside the Bloc files by using like
```dart
class BlocProfile extends BlocBase {
  BlocProfile(read) : super(read);

  bool isLoading = false;
}
```

Nothing changed at all, everything keeps working as before
But how I'm suppose to use this inside my API class? Cause this class does't extends ChangeNotifier nor have a Reader initialized. Do I need to pass the Reader as an argument to it? Or there's a simple way?

**Comment by leornt** [comment]
I've found a solution, just don't know if its a good one, but how about using [one_context](https://pub.dev/packages/one_context) and just call like
```dart
OneContext().context.read(blocLogin).isLoading
```

Like I said, it works, I just don't know if its something good

**Comment by rrousselGit** [comment]
This is anti-pattern.
You should pass the ref to the constructor

**Comment by leornt** [comment]
So, you're basically suggesting that I create the Reader in the pointer, pass it in the bloc constructor, and then pass it to the stream constructor, then to te API constructor, just to achieve the same result as 1 line of code would?
Like... Shouldn't be an easier way to do it using the own lib?
Something like `GlobalReader(blocLogin).isLoading` idk... We don't have the context everywhere, and the same argument in a lot of functions inside the code is like passing all my API data through arguments, it defeats the purpose of using ChangeNotifier doesn't?

**Comment by rrousselGit** [comment]
👋 
I'll close this since this was answered.
