### ISSUE TITLE
Misleading documentation, context.read function unavailable

### ISSUE THREAD

**Issue by incloudss** [rrousselGit/river_pod#598]
Hi,
I am migrating toward newest version of riverpod, and i encountered couple problems. 
First, there is `build(BuildContext context)` method as documentation says:
<img src="https://user-images.githubusercontent.com/78504503/125055729-cf7a6f80-e0a7-11eb-9ae1-099666ee05fa.png" width="400" height="300" />
We need to add second parameter `WidgetRef` to overriden build method.
Secondly, there is no `BuildContext.read` method available in `HookConsumerWidget`. I've imported those two references mentioned in documentation, and still getting error that method is not available. Should I use WidgetRef.read instead?

**Comment by rrousselGit** [comment]
The website is not updated yet.

**Comment by essarn** [comment]
> The website is not updated yet.

What does the new syntax look like for reading a provider?

**Comment by rrousselGit** [comment]
Extend  any of `ConsumerWidget` / `ConsumerStatefulWidget` / `HookConsumerWidget` and use their `ref` parameter for `ref.read`

**Comment by rrousselGit** [comment]
The widget is now up-to-date, showing the new syntax. So I will close this
