### ISSUE TITLE
Adding flutter riverpod to the project results in failed debug of the app

### ISSUE THREAD

**Issue by MkamaAFM** [rrousselGit/river_pod#599]
### Steps to produce the problem:

1. Create new project
2. Add flutter_riverpod package on the project
3. import flutter_riverpod to any of dart file on lib folder, example main.dart, using `import 'package:flutter_riverpod/flutter_riverpod.dart';`
4. debug the project on any device or supported browser.

No problem on flutter doctor, other packages works fine, I've tried on two projects today.

### Here is the cmd line texts and the failed results

C:\Users\AFM\Desktop\WORKS\Flutter\inventory>flutter pub add flutter_riverpod
Resolving dependencies...
  async 2.6.1 (2.7.0 available)
  charcode 1.2.0 (1.3.1 available)
+ flutter_riverpod 0.14.0+3
+ freezed_annotation 0.14.2
+ json_annotation 4.0.1
  meta 1.3.0 (1.7.0 available)
+ riverpod 0.14.0+3
+ state_notifier 0.7.0
  test_api 0.3.0 (0.4.1 available)
Downloading riverpod 0.14.0+3...
Changed 5 dependencies!

C:\Users\AFM\Desktop\WORKS\Flutter\inventory>flutter run -d windows
Launching lib\main.dart on Windows in debug mode...
../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_riverpod-0.14.0+3/lib/src/builders.dart : error : The control character U+0000 can only be used in strings and comments. [C:\Users\AFM\Desktop\WORKS\Flutter\inventory\build\windows\flutter\flutter_assemble.vcxproj]
../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_riverpod-0.14.0+3/lib/src/change_notifier_provider/base.dart(11,25): error GB1B8BC88: Method not found: 'ChangeNotifierProviderFamilyBuilder'. [C:\Users\AFM\Desktop\WORKS\Flutter\inventory\build\windows\flutter\flutter_assemble.vcxproj]
../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_riverpod-0.14.0+3/lib/src/change_notifier_provider/base.dart(14,30): error GB1B8BC88: Method not found: 'AutoDisposeChangeNotifierProviderBuilder'. [C:\Users\AFM\Desktop\WORKS\Flutter\inventory\build\windows\flutter\flutter_assemble.vcxproj]
../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_riverpod-0.14.0+3/lib/src/change_notifier_provider/auto_dispose.dart(15,25): error GB1B8BC88: Method not found: 'ChangeNotifierProviderFamilyBuilder'. [C:\Users\AFM\Desktop\WORKS\Flutter\inventory\build\windows\flutter\flutter_assemble.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'C:\Users\AFM\Desktop\WORKS\Flutter\inventory\build\windows\CMakeFiles\545453ec04d441b9a2dfa2291298d380\flutter_windows.dll.rule;C:\Users\AFM\Desktop\WORKS\Flutter\inventory\build\windows\CMakeFiles\bb2df1a40a81d146f38d85a3a9929a79\flutter_assemble.rule' exited with code 1. [C:\Users\AFM\Desktop\WORKS\Flutter\inventory\build\windows\flutter\flutter_assemble.vcxproj]
Building Windows application...
Exception: Build process failed.

**Comment by rrousselGit** [comment]
Make sure to run "pub get"

**Comment by MkamaAFM** [comment]
> Make sure to run "pub get"

I've done that more than twice.

**Comment by MkamaAFM** [comment]
For anyone facing this issue, delete riverpod folder (for me "flutter_riverpod" folder) from pub.dartlang.org folder, then run "flutter pub get" on your project which is having riverpod package, then try to debug your project again.

I don't know why this problem keeps appearing only for flutter_riverpod package, maybe it is my PC which has a problem

**Comment by rrousselGit** [comment]
A shorthand for what you describe may be "flutter pub cache repair"

In any case since it seems that the issue was resolved, I will close this
