### ISSUE TITLE
Explicit Dependency / Factories

### ISSUE THREAD

**Issue by TimWhiting** [rrousselGit/river_pod#6]
**Is your feature request related to a problem? Please describe.**
Yes.
The problem is that I want to be able to debug a mobile multiplayer game application by having two copies of it side by side in a flutter desktop application.

**Describe the solution you'd like**
I want to be able to override one provider, and any provider that depends on it is also overridden. Essentially I want to give each instance of the application a unique id, and then use the same set of providers that depend on that unique ID but have the reference to them result in a different set of providers per unique ID.

**Describe alternatives you've considered**
Currently I override the unique ID provider for each subtree and also have to override all providers that depend on the unique ID. The issue with this is that it creates a lot of code bloat in the widget tree (at the place I'm overriding).  It also makes it not compile-safe, since I can't know for sure if I've overridden all of the providers that I need to.

The ideal solution would be to just need to override the unique ID provider, and all providers that depend on it are automatically resolved to a different instance of the provider. (I understand why this is not the case, since some providers are meant to be singletons, rather than factories).

I was using this library as soon as I watched your youtube video introducing this. I'm so glad to see the progress and continued work on this! Back then there was no Computed or Families, which both seem to sort of address this problem.

However, using families mean everywhere I obtain a provider, I also have to obtain the unique ID provider to reference the provider I actually want.
I could solve this by using a Computed that computes the provider I want based on the unique ID provider. However, this means that for every provider I want duplicated I have to create a computed to go along with it. As well as in the documentation of computed it mentions that it might get called multiple times, even if the inputs haven't changed.

**Additional context**
Here is my provider dependency diagram.
Multiplayer ID is the unique ID that I've been talking about.
![gamestate](https://user-images.githubusercontent.com/15617545/85443885-02aa9900-b54f-11ea-8498-78f37c8e6e3d.png)

**Proposed Solution**
I think I would propose an argument to the providers. uniqueForDependencies or keys, that would make them resolve to different providers if the set of uniqueForDependencies / keys are different. Similar to the keys argument of flutter_hooks.

i.e.
```dart
// Providers
final idProvider = Provider((_) => 1)
final storageProvider = Provider((ref) => StorageProvider(ref), uniqueForDependencies: [idProvider])

class StorageProvider {
  ProviderReference ref;
  Box box;
  StorageProvider(this.ref){
   init();
  }
  Future<void> init() async {
    box = Hive.box('${ref.read(idProvider).value}');
  }
  String get clientId => box.get('clientId');
}

// Widget tree
void main() => runApp(
ProviderScope(
  child: Row(
    children: [
      // App id == 1
      MyApp(), 
      ProviderScope(
        child: MyApp(),
        overrides: [
           // App id == 2
           // Overriding id Provider should also override storage provider for this subtree
           idProvider.overrideForSubtree(Provider((_) => 2))
         ],
      ),
    ],
  ),
));

class MyApp extends HookWidget {
  // Inside my app
  Widget build(BuildContext context){
    // This resolves to a different instance of storage provider per MyApp instance.
    final storage = useProvider(storageProvider);
    print(storage.clientId);
    // gets client id from one storage box within one MyApp instance
    // and a different client id from a different storage box within the other MyApp instance.
  } 
}
```

**Comment by rrousselGit** [comment]
Thanks for the issue!
This is something I've been thinking of a few times. 

I'm not exactly sure about it, because it makes the provider resolution slower as we need to do a recursion to check that none of its dependencies are overridden

**Comment by rrousselGit** [comment]
It's worth noting that if you override your provider at the root of your app, this applies the change for _everything_. 

Would this work in your case?
Or do you actually override a provider for a specific widget tree? 

If so, why do you need to do that override?

**Comment by TimWhiting** [comment]
I just updated the diagram and the code example for reference to address your questions.

As far as your first comment about the provider resolution; could the results of the resolution be cached in some way so that you don't have to do the recursion every time? Such as just collapsing the recursion into a list, and make sure those providers haven't been overridden since the last build.

As far as your second comment. I'm not sure if I understand what you are trying to say.
I need a root ProviderScope for providing some common things for both (the server config & service). I need the rest of my providers to be overridden, but since they all depend on one provider (unique id). I want some way to specify that they need to be unique depending on the unique id provider in their scope.
So, I'm pretty sure the answer to your question is that I actually do override a provider for a specific widget tree. (but in my case the widget tree is a material app).

**Comment by rrousselGit** [comment]
Don't worry too much about the implementation. It's definitely doable to do the recursion only the first time
Once a provider's state was instantiated, all future reads hit a cache.

The issue is the first read. We still want it to be as fast as possible.

But I agree with you. This feature is likely needed. I just need some time thinking about how it could be in its ideal state.

**Comment by rrousselGit** [comment]
I wonder if maybe we instead want a `ComputedFuture` / `ComputedStateNotifier` / ...

```dart
final idProvider = Provider((_) => 1)
final storageProvider = Computed((read) {
  return StorageProvider(read(idProvider));
});
```

and have a hook-like rule for `read`, where we cannot call it conditionally – then track the dependencies used inside the function body.

**Comment by TimWhiting** [comment]
Exactly. I think that is what this is requesting. A way to have a StateNotifierProvider or FutureProvider that tracks what is being used like a Computed. Is this possible?

**Comment by rrousselGit** [comment]
We can do it for cases where `ref.read` is called within the body of the provider:

```dart
final a= Provider(...);
final b = Provider((ref) {
  return Something(ref.read(a));
});
```

On the other hand, if `ref.read` is called asynchronously after the object creation (like when `ref` is passed to the object), that won't be feasible.

**Comment by TimWhiting** [comment]
Ah, that is just what I was going to ask. What if the ones that you want to track are called synchronously, but providers that you don't care about tracking being called asynchronously?

**Comment by TimWhiting** [comment]
Essentially I would like a `read` and a `ref`.

**Comment by rrousselGit** [comment]
That's feasible but sounds oddly confusing.

Having `ref.read` behave differently based on where it's called sounds like a bad idea.
And having `read` vs `ref.read` sound confusing too.

**Comment by rrousselGit** [comment]
Maybe we could go with:

```dart
final a= Provider(...);
final b = Provider.scoped((ref, read) {
  // No ref.read method available
  // read can only be called within the body of the provider

  return Something(read(a));
});
```

But still, that sounds confusing.

**Comment by TimWhiting** [comment]
Hmm
```
final a= Provider(...);
final b = ComputedProvider((ref, computedReader) {
  return Something(ref, computedReader(a));
});

/// Or

final b = Provider.scoped((ref, key) {
  return Something(ref, key(a));
});

/// Or

final b = Provider.factory((ref, key) {
  return Something(ref, key(a));
});

```

**Comment by rrousselGit** [comment]
Another path is to go for:

```dart
final idProvider = Provider((_) => 1)
final storageProvider = Provider((ref) => StorageProvider(ref), uniqueForDependencies: [idProvider])
```

but have a linter warn for missing dependencies inside `uniqueForDependencies`.

**Comment by TimWhiting** [comment]
I honestly like that idea better. I'd prefer to mention what I want to be unique on explicitly like that.

**Comment by TimWhiting** [comment]
Another pattern that this opens up is something like the following:

```dart
final allContacts = [Contact(), ....];
final indexProvider = Provider((_) => 1)
final contactProvider = FamilyProvider<Contact>((_, index) => allContacts[index]);
final currentContactProvider = Provider((ref) => contactProvider(ref.read(indexProvider)), uniqueForDependencies: [indexProvider])
```

A way to combine the family and unique for dependencies would make this pattern even better.

**Comment by rrousselGit** [comment]
Another though is to have:


```dart
@scoped
final idProvider = Provider((_) => 1)

final storageProvider = Provider((ref) {
  ref.read(idProvider); // warns, avoid ref.read on @scoped providers

  // equivalent to ref.read, but can be called only within. the provider's body
  // If the dependency listened is overridden, this provider will be overridden too
  ref.track(idProvider);
});
```

**Comment by rrousselGit** [comment]
> A way to combine the family and unique for dependencies would make this pattern even better.
> 
> I know you can do this using a ProviderFamily by passing the index around your widget tree. But that seems kind of clunky sometimes to me. Especially if you want to change the index from lower in the tree.

Computed sounds more logical:

```dart
final allContacts = [Contact(), ....];
final indexProvider = StateProvider((_) => 1)
final contactProvider = ProviderFamily<Contact, int>((_, index) => allContacts[index]);
final currentContactProvider = Computed((read) => read(contactProvider(ref.read(indexProvider))));
```

**Comment by TimWhiting** [comment]
Oh, I like adding `ref.track` and the lint annotation.

**Comment by TimWhiting** [comment]
> Computed sounds more logical:
> 
> ```dart
> final allContacts = [Contact(), ....];
> final indexProvider = StateProvider((_) => 1)
> final contactProvider = ProviderFamily<Contact, int>((_, index) => allContacts[index]);
> final currentContactProvider = Computed((read) => read(contactProvider(read(indexProvider))));
> ```

Yes, but what if the thing you were computing was not just a plain dart object, but rather a provider of some sort. i.e. `StateNotifier`, does that approach work in that case?

**Comment by rrousselGit** [comment]
> Yes, but what if the thing you were computing was not just a plain dart object, but rather a provider of some sort. i.e. StateNotifier, does that approach work in that case?
i.e.

Make another family for the notifier

```dart
final allContacts = [Contact(), ....];
final contactProvider = Provider.family<Contact, int>((_, index) => allContacts[index]);

final contactEditorProvider = StateNotifierProvider.family<ContactEditorProvider, int>((ref, index) {
  final contact = ref.read(contactProvider(index));
  return ContactEditorProvider(contact);
});

final indexProvider = StateProvider((_) => 1)
final currentContactEditorProvider = Computed((read) => read(contactEditorProvider(read(indexProvider)).state));
```

**Comment by TimWhiting** [comment]
Okay, that's how you would do that. Thanks, I'm sure that will come in handy sometime!

**Comment by TimWhiting** [comment]
Question, does the family providers dispose of their cache at any point if the providers are not used anymore? From looking at the source code it didn't look like it. What if the user has scrolled through 100s of contacts or whatever is in a family?

**Comment by rrousselGit** [comment]
The parameters passed to families are never destroyed.
But the state associated to a parameter may get destroyed, when combined with `.autoDispose`

```dart
Provider.autoDispose.family<Foo, int>((ref, id) {...});
```

**Comment by rrousselGit** [comment]
This will likely change in the future. I'm thinking about how to fix that.

It's not critical though

**Comment by rrousselGit** [comment]
So...
Imo the true solution is using families:

```dart
final idProvider = Provider((ref) => 1);
final storageFamily = Provider.family<Storage, int>((ref) => Storage(id));


final currentId = useProvider(idProvider);
useProvider(storageProvider(currentId));
```

This doesn't require using overrides, which I think makes things easier to understand.
The problem is the verbosity of consuming the provider.

Maybe we can have some utilities to "bind" a family to a provider – like:


```dart
final userProvider = Provider((ref) => User(id: 42));

final _storageFamily = Provider.family<Storage, int>((ref) => Storage(id));
final storageProvider = _storageFamily.bind((read) => read(userProvider).id);

....

useProvider(storageProvider);
// Equivalent of:
useProvider(storageProvider(useProvider(userProvider).id));
```

This solves the UI reading the family without the UI.
The remaining question is how can another provider read a `.family(...).bind`

**Comment by rrousselGit** [comment]
Other thought on the `.scoped`, by splitting the creation into two callbacks instead of one:

```dart
final userProvider = Provider((ref) => 1);

final storageProvider = Provider.scoped<Storage, int>(
  (ref, id) => Storage(id),
  from: (read) => read(userProvider).id,
);

final otherProvider = Provider.scoped<Other, Storage>(
  (ref, storage) => Other(storage),
  from: (read) => read(storageProvider),
);
```

The `from:` function would be pure function, and whenever one of the dependencies used inside `from:`  is overridden, the associated provider is overridden too.

**Comment by rrousselGit** [comment]
A more flexible implementation of the previous `.scoped` may be:

```dart
final userProvider = Provider((ref) => 1);

final storageProvider = Provider.scoped<Storage>((read) {
  final user = read(userProvider);

  return (ref) => Storage(user.id);
});

final otherProvider = Provider.scoped<Other>((read) {
  final user = read(userProvider);
  final storage = read(storageProvider);

  return (ref) => Other(storage, user);
});
```

Or alternatively:

```dart
final userProvider = Provider((ref) => 1);

final storageProvider = Provider.scoped<Storage, User>(userProvider, (ref, user) {
  return Storage(user.id);
});

final otherProvider = Provider.scoped2<Other, Storage, User>(storageProvider, userProvider, (ref, storage, user) {
  return Other(storage, user);
});
```

I like both of these approaches.

The former is more flexible but scary looking and can be misused.
The latter is easier to use but a bit verbose and requires `scoped` vs `scoped2` vs `scopedX`.

In any case, this is similar to the `uniqueDependencies` proposal – but safer as doesn't need a linter.

**Comment by TimWhiting** [comment]
I agree it can be solved using families. However, the issue is that I would have to have lines like this in almost every widget. 

```dart
final currentId = useProvider(idProvider);
useProvider(storageProvider(currentId));
```

Or pass down the id through every widget constructor. And I would have families depending on families and just passing the id all the way up the family chain.

The bind syntax would make the above more reasonable, but still I would prefer one line to define my provider rather than creating a family + a bind for each provider I have. The issue with using computed for the binding portion is then you can't depend on the computed in a provider. (As far as I've tried at least).

As far as your last proposal, I prefer the first alternative, unless the types can be inferred. Requiring `scoped` ... `scopedX` is also a downside of the second proposal.

**Comment by rrousselGit** [comment]
By the way @TimWhiting, do you _really_ need the override  feature for this?

I'm thinking that this problem could be heavily simplified without the ability to locally override a provider

**Comment by TimWhiting** [comment]
I'm not tied to the idea of overriding, what did you have in mind?

**Comment by rrousselGit** [comment]
The only reason we do not have a ComputedFuture/..., or a Provider.scoped (with the "ref.track") is because we can override a provider for part of the subtree. 

It makes things bloody difficult to know where in the graph of ProviderScope should a Computed-like be inserted.

**Comment by TimWhiting** [comment]
Makes sense. Would there be a good equivalent for testing if you remove overriding, and add in the ComputedFuture / provider.scoped? I guess there could be a flag for test mode in the top of the tree, and the computed providers could choose whether to insert a mock or a real service depending on the flag. The issue with that is that it brings your testing logic (mocks) into your actual application.

But what if you let people override still for testing, but not at any level or any subtree. That way you only have to replace providers 1 for 1, and not worry about individual subtrees.

**Comment by rrousselGit** [comment]
Overrides would still be there, but only global to the entire app

**Comment by TimWhiting** [comment]
Thinking some more, how would you accomplish what I am looking for without overrides for a specific tree? I have essentially 2 MyApp instances side by side in a row. They have nothing different passed into their constructor and they use the same providers. How does one resolve to one set of providers (computed or scoped) and the other resolve to a different set?

**Comment by rrousselGit** [comment]
I'm currently making a separate issue to explain my entire plan

The basic idea is:
- all existing providers can only be overridden globally
- add ComputedChangeNotifier/ComputedFuture/...
- add a third kind of value, that can be locally overridden locally in a widget tree, but is just a simple value with no extra fancy thing.

The last one would be:

```dart
final appId = ScopedProvider<int>();


routes: {
  '/': (_) => ProviderScope(overrides: [appId.overrideAs(42)], child: App()),
  '/settings': (_) => ProviderScope(overrides: [appId.overrideAs(21)], child: App()),
}
```

Where `ScopedProvider` **cannot** be obtained using `ref.read`.

Instead, it would have to be reconciled by the widget tree, so:

```dart
final appIdProvider = ScopedProvider<int>();
final appProvider = StateNotifierProvider.family<App, int>((ref, id) {});

...
final appId = useProvider(appIdProvider);
final app = useProvider(appProvider(appId));
```

**Comment by TimWhiting** [comment]
Okay, yeah, a separate local provider that has to be either provided or resolved in the tree seems like the best solution. In fact while thinking about how to deal with no overriding, I thought that I could always use the old provider package to only provide something to a specific portion of the tree. Seems like that ability to explicitly say where to provide what is still useful, though I really like how riverpod gets most of the providers out of being explicitly stated in the ui tree.

I just shared a repository with a simple counter example app that mimics what I'm doing right now with my games app, but on a smaller scale. Feel free to mess around with it when you are trying this out.

**Comment by rrousselGit** [comment]
Agreed.
But it's probably better to implement a ScopedProvider used like other providers in riverpod, rather than using package:provider

The fact that we can't provide two values of the same type is very limiting in this situation, as we only want to expose primitives.
We could have a clash if we have two values like `appId` exposed. And it overall fits with the package anyway

**Comment by TimWhiting** [comment]
Agreed
