### ISSUE TITLE
Issue with Providing to MaterialApp Router

### ISSUE THREAD

**Issue by bbrosius** [rrousselGit/river_pod#600]
I'm having a strange issue when trying to provide a class to Flutter's navigation 2.0. 

In my main flutter widget I'm using UncontrolledProviderScope so that I can create a Container (instantiated outside of the build method) that I can use to pass in my AppRouterDelegate as needed by the new navigator. Build method is here. 

```
@override
  Widget build(BuildContext context) {
    print("MAin build");
    return FutureBuilder(
      // Initialize FlutterFire:
      future: _initialization,
      builder: (context, snapshot) {
        // Once complete, show your application
        if (snapshot.connectionState == ConnectionState.done ||
            snapshot.hasError) {
          if (kDebugMode && Config.platform != Platform.web) {
            //TODO: Turn this off for first release leave in now

            FirebaseCrashlytics.instance.setCrashlyticsCollectionEnabled(true);
          }
          return UncontrolledProviderScope(
              container: container,
              child: ProviderListener(
                provider: pageChangeProvider,
                onChange: (context, dynamic page) {
                  observer.analytics.setCurrentScreen(screenName: page);
                },
                child: MaterialApp.router(
                  routeInformationParser: AppRouteInformationParser(),
                  routerDelegate: container.read(appRouterProvider),
                  title: 'OneVue',
                  theme: ThemeData(
                    primarySwatch: Colors.blue,
                    visualDensity: VisualDensity.adaptivePlatformDensity,
                    canvasColor: Colors.transparent,
                  ),
                ),
              ));
        }

        // Otherwise, show something whilst waiting for initialization to complete
        return SplashScreen();
      },
    );
  }

```
But what happens is the build method is called twice when the app starts. I believe it's because Flutter starts the app then rebuilds main when the screen size is determined. On the second time, the main build method is called the app fails with an error that my RouterDelegate has been disposed. 

> The following assertion was thrown building IconTheme(color: Color(0xdd000000)):
> A AppRouterDelegate was used after being disposed.
> 
> Once you have called dispose() on a AppRouterDelegate, it can no longer be used.
> The relevant error-causing widget was
> MaterialApp
> lib/main.dart:57
> When the exception was thrown, this was the stack
> #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure>
> package:flutter/…/foundation/change_notifier.dart:117
> #1      ChangeNotifier._debugAssertNotDisposed
> package:flutter/…/foundation/change_notifier.dart:123
> #2      ChangeNotifier.removeListener
> package:flutter/…/foundation/change_notifier.dart:195
> #3      _RouterState.didUpdateWidget
> package:flutter/…/widgets/router.dart:569

It's unclear to me why the AppRouter is being disposed of in this case. I can get past the error if I turn my app router class into a singleton with a factory constructor, but that seems like that could have unintended consequences. 

Here is the declaration of my AppRouterProvider 

```
final appRouterProvider = ChangeNotifierProvider((ref) => AppRouterDelegate(
    ref.watch(sessionManagerProvider),
    ref.watch(authServiceProvider),
    ref.watch(mainScreenCoordinatorProvider),
    ref.watch(searchBarVMProvider),
    ref.watch(contentScreenCoordinatorProvider),
    ref.watch(tSettingsContentCoordinatorProvider)));
```

I guess my core question is what is the correct way to handle this with Riverpod? Should I be declaring my provider differently or is a singleton necessary here?

**Comment by rrousselGit** [comment]
The snippet you gave seem unrelated with the issue.

It is possible that your ChangeNotifier was simply disposed because a `ref.watch` caused it to rebuild, but some async code used the previously created notifier.

**Comment by bbrosius** [comment]
Hey sorry, should have updated the issue. I've done more research on this. Here is the process in general terms. 

If you read the Flutter navigation 2.0 documentation (admittedly it's lacking so that might be part of the problem), you are encouraged to make your appRouterProvider outside of the widget build method so that it doesn't get rebuilt.

In our code, I would like to use riverpod to provide the appRouter largely because it needs to watch other providers in our app. 
The problem I'm hitting is I don't fully control the lifecycle of the navigation. And so what's happening in the app at some point our appRouterProvider is recreated but flutter tries to update the old instance of the router. 

So I guess the question is there a way to prevent disposal on a provider? Right now I've made the appRouterClass a singleton with a factory constructor that the provider calls. But I'm not sure if that is a bad practice or will cause an issue with Riverpod that I'm not thinking of. It certainly feels a little clunky.

**Comment by rrousselGit** [comment]
As I mentioned, it's likely that one of the `ref.watch` caused your ChangeNotifier to rebuild. If you don't want that, you can consider using `ref.watch(provider.select(...))` or `ref.listen`
