### ISSUE TITLE
Stream provider Unhandled Exception: setState() or markNeedsBuild() called during build on refresh

### ISSUE THREAD

**Issue by imcouri** [rrousselGit/river_pod#603]
I'm trying to implement pagination for a firebase chat app using stream notifier.  I watch for the value of the query limit provider in the stream provider and add 25 to the query limit value whenever the user reaches the top of the page.

Whenever the query limit value changes and I scroll up to see the loaded messages I get this error: 

`[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: setState() or markNeedsBuild() called during build.
This UncontrolledProviderScope widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  UncontrolledProviderScope
The widget which was currently being built when the offending call was made was:
  ChatRoomPage
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4217:11)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4232:6)
#2      ProviderElement._debugMarkWillChange.<<…>
flutter: Instance of 'Error'
flutter: #0      StateNotifier.state= (package:state_notifier/state_notifier.dart:173:7)
#1      StateController.state= (package:riverpod/src/state_provider.dart:23:31)
#2      ChatRepository.getChats (package:twotim/repositories/chatRepository.dart:60:37)
#3      chatProvider.<anonymous closure> (package:twotim/pages/chat/chatRoom.dart:44:45)
#4      AutoDisposeStreamProvider.create (package:riverpod/src/stream_provider/auto_dispose.dart:16:74)
#5      ProviderElement._runStateCreate (package:riverpod/src/framework/base_provider.dart:854:39)
#6      ProviderElement.flush (package:riverpod/src/framework/base_provider.dart:620:11)
#7      ProviderSubscription.flush (package:riverpod/src/framework/base_provider.dart:428:23)
#8      _ConsumerState.build (package:flutter_riverpod/src/consumer.dart:281:15)
#9      StatefulElement.build (package:flutter/src/widgets/framework.dart:4691:27)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4574:15)
#11     StatefulElem<…>` 

Code : 

`
Stream<List<dynamic>> getChats(RoomData roomData){

    int limit = _watch(chatQueryLimitProvider).state; //query limit
    int messageCount = _read(roomMessageCountProvider).state;// the number of messages in this room
      if(messageCount != null && _read(isLastPageProvider).state == false){
        if(limit-25 > messageCount){
          _read(isLastPageProvider).state = true; // stops the scroll controller from calling this function again
          limit = messageCount; //sets the limit to the total number of messages in the current chat room if limit is bigger than the total number of messages
        }
      }

    final stream = FirebaseFirestore.instance.collection('chats').doc(roomData.roomID).collection('messages').limit(limit).orderBy('created_at',descending: true).snapshots();//snapshot of the messages of the current room

    return stream.map((snapshot){
      _read(roomMessageCountProvider).state = snapshot.size; // updates the total message count to the current number of messages in the snapshot
      return snapshot.docs.map((doc){
          var messageType = doc.data()['mediaType']; // image, null(text message), audio, video
          if(messageType == 'null'){
            return types.TextMessage(
              author: types.User(
                id: doc.data()['user'].toString(),
                firstName: roomData.members[doc.data()['user']].username,
                imageUrl: roomData.members[doc.data()['user']].pfpUrl,
              ),
              createdAt: doc.data()['created_at']?.toDate()?.millisecondsSinceEpoch,
              id: doc.id,
              text: doc.data()['message'],
            );
          }
          else{
            if(messageType == 'image'){
              return types.ImageMessage(
                size: 1,
                height: 10,
                width: 10,
                author: types.User(
                  id: doc.data()['user'].toString(),
                  firstName: roomData.members[doc.data()['user']].username,
                  imageUrl: roomData.members[doc.data()['user']].pfpUrl,
                ),
                createdAt: doc.data()['created_at']?.toDate()?.millisecondsSinceEpoch,
                id: doc.id,
                uri: doc.data()['media'],
              );
            }
          }
    }).toList();}
    );

  }`

stream provider : 

`final chatProvider = StreamProvider.autoDispose<List<dynamic>>((ref){

    RoomData roomData = ref.read(currentRoomIdProvider).state; // current room
    int limit = ref.watch(chatQueryLimitProvider).state;
    return ref.read(chatRepositoryProvider).getChats(roomData,limit);

});`

**Comment by rrousselGit** [comment]
This is voluntary. You are not allowed to modify providers inside providers and widgets life-cycles.

Looking at the stacktrace, either you have a StatefulWidget/Consumer that is modifying a provider, or your `chatProvider` is modifying another provider.

**Comment by rrousselGit** [comment]
👋 
I'll close this since this was answered. Feel free to create a new issue if you still have the problem 😄
