### ISSUE TITLE
Possible Typo In Example

### ISSUE THREAD

**Issue by Juliotati** [rrousselGit/river_pod#604]
## Typo on comment
```dart
// If you uses flutter_hooks
```

### Additional context
![image](https://user-images.githubusercontent.com/59662912/125289874-9fd19e80-e317-11eb-9de6-867f8a5772b7.png)

**Comment by rrousselGit** [comment]
This seem to have been fixed already, and you probably saw the doc of the v0.14.x instead of v1.0.0-dev

So I will close this.
