### ISSUE TITLE
How to listen to state chage inside another StateNotifier provider?

### ISSUE THREAD

**Issue by 2shrestha22** [rrousselGit/river_pod#605]
**Describe what scenario you think is uncovered by the existing examples/articles**
I came from Flutter Bloc where we can listen to another bloc and yield state accordingly. I want to listen to change in FilterProvider inside my FilteredListProvider. Would you provide how can I achieve this?

**Describe why existing examples/articles do not cover this case**
These are what I have done already. But this way `ClientFilteredListNotifier` recreated in every change in FilterState. Is it okay? If not how can we do this better way?
```dart
final clientFilterProvider =
    StateProvider<ClientFilter>((ref) => ClientFilter.initial());
```

```dart
final clientFilteredListProvider =
    StateNotifierProvider<ClientFilteredListNotifier, ClientFilterListState>(
  (ref) {
    final clientRepo = ref.watch(clientListingRepoProvider);
    final filter = ref.watch(clientFilterProvider).state;
    return ClientFilteredListNotifier(clientRepo, filter);
  },
);
```
```dart
class ClientFilteredListNotifier extends StateNotifier<ClientFilterListState> {
  ClientFilteredListNotifier(this._clientListingRepo, this._filter)
      : super(ClientFilterListState.loading()) {
    getClients(_filter);
  }

  final ClientListingRepo _clientListingRepo;
  final ClientFilter _filter;

  Future<void> getClients(ClientFilter filter) async {
    state = ClientFilterListState.loading();
    final eitherFailureOrList = await _clientListingRepo.getClients(
      type: filter.clientType,
      searchQuery: filter.filterString,
    ); //Todo change client type

    state = eitherFailureOrList.fold(
      (l) => ClientFilterListState.error(NetworkExceptions.getErrorMessage(l)),
      (r) => ClientFilterListState.data(customerList: r),
    );
  }
}
```

**Additional context**
Add any other context or screenshots about the documentation request here.

**Comment by iamarnas** [comment]
You can read all providers by passing the `ref` object as parameter. [Example](https://riverpod.dev/docs/concepts/reading#reading-a-provider-inside-another-provider). 

```dart
final userRepositoryProvider = Provider((ref) => UserRepository());

final userControllerProvider = StateNotifierProvider((ref) {
  return UserController(
    // Read userRepositoryProvider and create a UserController from the result
    repository: ref.watch(userRepositoryProvider),
  );
});
```

**Comment by 2shrestha22** [comment]
@iamarnas Thanks for responding. But passing `ref` also cause Provider class to rebuild.

**Comment by tabernerojerry** [comment]
@2shrestha22 you can pass as ref.read check it here: https://riverpod.dev/docs/concepts/combining_providers

**Comment by 2shrestha22** [comment]
@tabernerojerry No I need to watch t
filter provider. I am asking for solution where  `ClientFilterListNotifer` will not re-created. I want to listen inside StateNotifer. I may be searching for different solution other than Riverpod😅. May be listening to stream inside StateNotifier may work.  I have to try. Currently I am using Future Provider instead of StateNotifer. 😀

**Comment by rrousselGit** [comment]
Note that for a filter, you do not need to use a StateNotifier.
FutureProvider like you mentioned is more than enough:

```dart
final clientFilterProvider =
    StateProvider<ClientFilter>((ref) => ClientFilter.initial());

final clientFilteredListProvider = FutureProvider<List<Client>>((ref) async {
  final clientRepo = ref.watch(clientListingRepoProvider);
  final filter = ref.watch(clientFilterProvider).state;

  return clientRepo.getClients(
    type: filter.clientType,
    searchQuery: filter.filterString,
  );
);
```

**Comment by 2shrestha22** [comment]
> > Thanks for responding. But passing `ref` also cause Provider class to rebuild.
> 
> This should not be the case. Only if you call `ref.watch` will the Provider be rebuilt. You can call `ref.read` to read other providers without an issue. This is why it is common to pass the `ref.read` function to a Provider and not `ref.watch`

Sorry for my incomplete reply. I need to watch filterProvider so I must need to use ref.watch() inside stateNotifierProvider. I wanted to say if I pass ref and use ref.listen() my stateNotiferProvider will rebuild. But I just replied with short text. 😅

**Comment by rrousselGit** [comment]
Using `ref.watch` is not necessary

The v1 version exposes `ref.listen`:

```dart
StateNotifierProvider((ref) {
  ref.listen(clientFilterProvider, (filter) {
    print('filter changed');
  });
  
  return Notifier();
}
```

This won't rebuild `Notifier` when `clientFilterProvider` changes.

**Comment by 2shrestha22** [comment]
> Note that for a filter, you do not need to use a StateNotifier.
> FutureProvider like you mentioned is more than enough:
> 
> ```dart
> final clientFilterProvider =
>     StateProvider<ClientFilter>((ref) => ClientFilter.initial());
> 
> final clientFilteredListProvider = FutureProvider<List<Client>>((ref) async {
>   final clientRepo = ref.watch(clientListingRepoProvider);
>   final filter = ref.watch(clientFilterProvider).state;
> 
>   return clientRepo.getClients(
>     type: filter.clientType,
>     searchQuery: filter.filterString,
>   );
> );
> ```

Thank you

**Comment by 2shrestha22** [comment]
> Using `ref.watch` is not necessary
> 
> The v1 version exposes `ref.listen`:
> 
> ```dart
> StateNotifierProvider((ref) {
>   ref.listen(clientFilterProvider, (filter) {
>     print('filter changed');
>   });
>   
>   return Notifier();
> }
> ```
> 
> This won't rebuild `Notifier` when `clientFilterProvider` changes.

Wow seem nice. I have not yet tried v1. In this case how can I call getClient() which is inside StateNotifierProvider? Previously I were passing `Filter` to `StateNotifierProvider` like this.
```dart
class ClientFilteredListNotifier extends StateNotifier<ClientFilterListState> {
  ClientFilteredListNotifier(this._clientListingRepo, this._filter)
      : super(ClientFilterListState.loading()) {
    getClients(_filter);
  }

  final ClientListingRepo _clientListingRepo;
  final ClientFilter _filter;

  Future<void> getClients(ClientFilter filter) async {
    state = ClientFilterListState.loading();
    final eitherFailureOrList = await _clientListingRepo.getClients(
      type: filter.clientType,
      searchQuery: filter.filterString,
    ); //Todo change client type

    state = eitherFailureOrList.fold(
      (l) => ClientFilterListState.error(NetworkExceptions.getErrorMessage(l)),
      (r) => ClientFilterListState.data(customerList: r),
    );
  }
}
```

**Comment by rrousselGit** [comment]
You can do:

```dart
final provider = StateNotifierProvider<ClientFilteredListNotifier, ClientFilterListState>((ref) {
  final notifier = ClientFilteredListNotifier(...);

  ref.listen(anotherProvider, (value) {
    notifier.getClients(filter);
  });

  return notifier;
});

**Comment by otto-dev** [comment]
I have a situation where I end up with this:

```
ref.listen(foo, (_, __) => stateNotifier.recompute());
ref.listen(bar, (_, __) => stateNotifier.recompute());
ref.listen(baz, (_, __) => stateNotifier.recompute());
ref.listen(config.select((v) => v.someInt), (_, __) => stateNotifier.recompute());
```

`recompute` is throttled, and it can update the state multiple times (first using a cache, then live data from the backend...), so I can't simply use a `FutureProvider` with a single async function that does `ref.watch` on all the dependencies. Am I doing this right or is there a better pattern that I'm missing?

**Comment by TimWhiting** [comment]
2 potential ways of improving the code.

Make sure you pass the Ref to the stateNotifier, and then do these listen calls in the stateNotifier's Constructor.
Once you have passed the Ref you can also create a method on the stateNotifier to listen and recompute.

```dart
class YourStateNotifer extends StateNotifier<YourState> {
   YourStateNotifier(this.ref): super(YourState.default()) {
     recomputeOnChange(foo);
     recomputeOnChange(bar);
     recomputeOnChange(baz);
     recomputeOnChange(config.select((v) => v.someInt));
   }
   final Ref ref;

   void recomputeOnChange<T>(ProviderListenable<T> provider) {
     ref.listen(provider, (_, __) => recompute());
   }
}
```

But if you are recomputing on all of these changes (If recomputing resets the state of the stateNotifier), why are you not just watching?

**Comment by otto-dev** [comment]
Thanks @TimWhiting!

> why are you not just watching

Because I need to throttle the calls to `recompute`, and for that I need to maintain internal, mutable state inside the `StateNotifier`, which I can only do if I avoid `watch`.

Now, the irony is, `Notifier` (opposed to `StateNotifier`) allows me to main internal state and `.watch`, but not to `.listen`. So I will rewrite the above logic with `watch` and `Notifier`.

For other, a link to our relevant discussion: https://github.com/rrousselGit/riverpod/discussions/1963
