### ISSUE TITLE
How best to use Riverpod to manage state of ListView items

### ISSUE THREAD

**Issue by davebound** [rrousselGit/river_pod#608]
Hi All,

I'm struggling to figure out how to use Riverpod for the following scenario. 

I have a ListView where the children are Containers with a button inside.

When the button is pressed, I want to change the colour of that container. I want that colour to be stored in a piece of state using a Riverpod provider.

There is another button outside the list. When that is pressed, it should change the color of ALL the containers.

![image](https://user-images.githubusercontent.com/18735591/125645215-f4a23016-4f8d-43a0-8e28-af058d6cde4d.png)

It feels like I need a Change/StateNotifierProvider *for each* container. Do I use families for this? How would I tie a particular piece of state to its associated container?

And how would the red button access all of the states to change the colour of all?

As a bonus, I would also like the red button to be notified when one of the green buttons changes the color of its container

Many thanks

**Comment by rrousselGit** [comment]
Hello!
This sort of question is probably a better fit on StackOverflow

**Comment by davebound** [comment]
Ok, thx Remi - done + making progress: https://stackoverflow.com/q/68380827/10927806

**Comment by rrousselGit** [comment]
Closing as it was answered on SO
