### ISSUE TITLE
[Question] ProviderReference removed in ProviderContainer

### ISSUE THREAD

**Issue by davidmartos96** [rrousselGit/river_pod#61]
I was taking a look at the progress in the new branch `merge_computed_and_provider` and I noticed that the commit 04315760904138665b003d0aa6f6ba84be846775 has removed the getter for the `ProviderReference` in the `ProviderContainer` class, breaking the Marvel example test in the process, which was doing the following:

```dart
final container = ProviderContainer();
final client = FakeDio();
final repository = MarvelRepository(container.ref, client: client);
```

I was wondering what would be the new way of doing this inside the tests now. 
I'm sure you are planning to update/fix the examples, but I was just curious :sweat_smile:

**Comment by rrousselGit** [comment]
To be fair I removed it thinking it was probably not needed.

The way I'd probably go with it is expose `client` with a provider:

```dart
final httpClient = Provider((_) => Dio());
```

then override it inside tests:

```dart
final container = ProviderContainer(overrides: [
  httpClient.overrideWithValue(FakeDio()),
]);
```

**Comment by rrousselGit** [comment]
In any case, with the current changed `container.ref` is daily simple to implement manually:

```dart
final refProvider = Provider((ref) => ref);
final container = ProviderContainer();

final ref = container.read(refProvider);
```

**Comment by davidmartos96** [comment]
Makes sense to use override in the container. I wasn't thinking about that.
Thanks Remi!
