### ISSUE TITLE
Add listener Widget 

### ISSUE THREAD

**Issue by tbm98** [rrousselGit/river_pod#62]
**Is your feature request related to a problem? Please describe.**
I want to pass event from `provider` to `widget`
issue related: #21 

**Describe the solution you'd like**
Create a widget like `BlocListener`.
It can pass events to widget then I can do something like navigation, showDialog ...... 

**Current solution**
Create a Stream in Provider and listen it in StatefulWidget or Hooks widget.

**Comment by rrousselGit** [comment]
If I understand correctly, what you want is:

```dart
return ProviderListener<Value>(
  provider: myProvider,
  onChange: (context, value) {
    showDialog(...); 
  },
);
```

Is that it?

**Comment by tbm98** [comment]
Yes. Concept of blocListener is here https://pub.dev/documentation/flutter_bloc/latest/flutter_bloc/BlocListener-class.html

**Comment by eggnstone** [comment]
> **Is your feature request related to a problem? Please describe.**
> I want to pass event from `provider` to `widget`
> issue related: #21
> 
> **Describe the solution you'd like**
> Create a widget like `BlocListener`.
> It can pass events to widget then I can do something like navigation, showDialog ......

The new version 1.0 has something pretty nice:
https://pub.dev/documentation/flutter_riverpod/1.0.0-dev.1/flutter_riverpod/WidgetRef/listen.html
