### ISSUE TITLE
AsyncValue data function callback never executed when used from onPressed

### ISSUE THREAD

**Issue by angelcervera** [rrousselGit/river_pod#628]
**Describe the bug**
The data callback function is never called when using the provider from the onPressed function.
The next example reproduces the error. The provider is working fine when is not used from the onPressed callback.

In the next example:
1. `loading` function executed and print "Loading..."
2. `print(str);` from the provided is executed and printing `From the onPress` so the Future finishes successfully.
3. data callback defined in the AsyncValue is never executed.

Note that in the example, the family provided is defined as <void, String> because in my use case, the future is not returning anything, but I need to know that it finished fine. I tested using <String, String> and it is the same case.

**To Reproduce**

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() {
  runApp(ProviderScope(child: MaterialApp(home: Scaffold(body: Center(child: MyHomeAsyncValue()),))));
}

final voidFutureProvider = FutureProvider.autoDispose.family<void, String>((ref, str) {
  return Future.delayed(Duration(seconds: 5), () { print(str); });
});

class MyHomeAsyncValue extends StatelessWidget {
  const MyHomeAsyncValue({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Consumer(
      builder: (context, watch, child) => ElevatedButton(
        child: Text('Call'),
        onPressed: () {
          watch(voidFutureProvider("From the onPress")).when(
            data: (value) => print("Done from the button!!!"),
            loading: () => print("Loading...."),
            error: (error, stackTrace) => print("Error $error"),
          );
        },
      ),
    );
  }
}
```

**Expected behavior**
1. `loading` function executed and print "Loading..."
2. `print(str);` from the provided is executed and printing `From the onPress` so the Future finishes successfully.
3. data callback defined in the AsyncValue must be executed.

**Versions**
flutter_riverpod: ^0.14.0+3

**Comment by rrousselGit** [comment]
This is not how `AsyncValue` works.
`when` does not "listen" to data/loading/error. It's a switch-case on the current state.

What you want is instead:

```dart
onPressed: () async {
  final value = await context.read(futureProvider.future);
}
```

**Comment by angelcervera** [comment]
Thanks for your fast response!
So in my case, it is something like this:
```dart
        onPressed: () {
          final value = context.read(voidFutureProvider("From the onPress").future);
          value
              .then((value) =>  print("Done from the button!!!"))
              .onError((error, stackTrace) => print("Error $error"));
        },
```

Tested and working!

Maybe it would be good to explain this in the documentation. Commented with other people and they expected the same callback behavior as me. Anyway, I'm not an expert in Dart or Flutter, so maybe it is our fault.

Thanks again.
