### ISSUE TITLE
[QUESTION] SatateListenerProvider with family

### ISSUE THREAD

**Issue by buraktabn** [rrousselGit/river_pod#649]
**Describe why existing examples/articles do not cover this case**
I could not find anything about using `StateNotifierProvider` with `family` in the [docs](https://riverpod.dev/docs/concepts/modifiers/family).

```dart
static final provider =
    StateNotifierProvider
        .autoDispose
        .family<ListingState, ListingModel, String?>((ref, profession) => ListingState(profession));
```

In my `ConsumerWidget`, I want to access the state and edit the state. To get the state:
```dart
final listingState = ref.watch(ListingState.provider(profession));
```

My question is to edit the state, I need to call the `.notifier`. I could only do that while passing an argument again.
```dart
final listingStateNotifier = ref.watch(ListingState.provider(profession).notifier);
```
Is this the right way of doing this? If so, it doesn't feel right. Even though passing the same argument, would changing the state using `listingStateNotifier` effects the state on `listingState`?

**Additional context**
```yaml
dependencies:
  flutter:
    sdk: flutter
    
  flutter_riverpod: ^1.0.0-dev.6
```

**Comment by wujek-srujek** [comment]
This is the right thing to do, you need to tell the container exactly which provider you want, as you can have many providers of the same type with different parameters (you don't have a single provider, you can have a 'family' of them).
Yes, you will get the right provider instance and you will change the correct state. As long as Riverpod can find the right one, I think you need to override `operator==` and `hashCode` for it, as described here https://riverpod.dev/docs/concepts/modifiers/family#parameter-restrictions.

**Comment by buraktabn** [comment]
Thanks for the answer, it cleared a lot. I've got a new question now. If I want to use `listingState` in some other widgets and I don't have access to the `profession` argument, how can this be done?

Passing down the `profession` argument would work. I'm just wondering that what would be the best practice here.

**Comment by TimWhiting** [comment]
You can have `profession` be in a provider and override it for the subtree using `ProviderScope` with whatever the parameter should be for that subtree. Or you can just pass it down like you mention.
