### ISSUE TITLE
[hooks_riverpod: ^1.0.0-dev.6] widgetRef.refresh(futureProvider) throws exception

### ISSUE THREAD

**Issue by 2shrestha22** [rrousselGit/river_pod#652]
**Describe the bug**
`widgetRef.refresh(futureProvider)` throws `Exception: futureProvider is not called earlier`.

**To Reproduce**
`onRefresh: () async => widgetRef.refresh(futureProvider)`
Without async gives error:
`The argument type 'FutureProvider<DateRange>' can't be assigned to the parameter type 'ProviderBase<Future<void>>'`

```dart
class Dashboard extends ConsumerWidget {
  const Dashboard({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context, WidgetRef widgetRef) {
   return RefreshIndicator(
    onRefresh: () async => widgetRef.refresh(futureProvider), // this lline
   child: AnotherConsumerWidget()
 }
}
```
futureProvider
```dart
final futureProvider = FutureProvider<DateRange>(
  (ref) async {
    final repo = ref.watch(dateRangeFilterRepoProvider);

    final dateRange = await repo.getDateRange();
    return dateRange;
  },
);
```
**Expected behavior**
We need a documentation about using `widgetRef.refresh()`
#335

**Comment by rrousselGit** [comment]
This is expected. 

`ref.refresh(futureProvider)` returns `AsyncValue<Model>` but `onRefresh` expects `Future<void>`


Chances are you want to do:

```dart
onRefresh: () {
  ref.refresh(futureProvider);
  return ref.read(futureProvider.future);
}
```
