### ISSUE TITLE
[1.0.0-dev.6] How display value with select?

### ISSUE THREAD

**Issue by xaatw0** [rrousselGit/river_pod#658]
**Describe the bug**
Provider.select should not change bool value.  Otherwise, add a function.

**To Reproduce**
```
final counterProvider = StateProvider((ref) => 0);

class SelectExample extends ConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    bool isAbove5 = ref.watch(counterProvider.select((s) => s.state > 5));
    return Text('Is counter > 5 ? $isAbove5');
  }
}

onPress:(){
ref.watch(counterProvider).state++;
}
```

**Expected behavior**
Is counter > 5 ? 0
Is counter > 5 ? 0
Is counter > 5 ? 0
Is counter > 5 ? 0
Is counter > 5 ? 0
Is counter > 5 ? 0
Is counter > 5 ? 6
Is counter > 5 ? 7

**Real behavior**
Is counter > 5 ? false
Is counter > 5 ? false
Is counter > 5 ? false
Is counter > 5 ? false
Is counter > 5 ? false
Is counter > 5 ? false
Is counter > 5 ? true
Is counter > 5 ? true

**Comment by TimWhiting** [comment]
Select selects a subset of the state to watch for changes, it is not intended to return the original state. However, you can always do a `ref.read` if you want the original state but don't want the widget to rebuild.

**Comment by rrousselGit** [comment]
It sounds like you do not want to use select at all.

```dart
final count = ref.watch(counter).state;
final isAbove5 = count > 5;

```

**Comment by xaatw0** [comment]
Thank you for your answer. However, I still don't understand it.
I'm trying to understand how to stop rebuild widget using select, based on the following manual.
I can get the isAbove5, but how do I use that for stopping rebuilding?

https://riverpod.dev/docs/concepts/reading/
Using this syntax, our widget will rebuild only if the isAbove5 variable changes. Which means that if the counter changes from 1 to 2, this will not cause our widget to rebuild.

**Comment by rrousselGit** [comment]
The problem is your example, which is anti-pattern.

If your widget is printing the counter, it should rebuild whenever that counter changes. So select purposefully won't allow you to do that.
What exactly are you trying to achieve?

**Comment by xaatw0** [comment]
>What exactly are you trying to achieve?
I would like to know how to use 'select.'
From the manual, I thought 'select' was a function to stop rebuilding under certain conditions, but am I wrong?

**Comment by rrousselGit** [comment]
Select does stop rebuilding under certain conditions.

In your example, which is:

```dart
    bool isAbove5 = ref.watch(counterProvider.select((s) => s.state > 5));
```

then a provider update will rebuild the widget only when isAbove5 changes.

What doesn't make sense is that your widget is selecting "isAbove5", but is printing the counter itself.

**Comment by xaatw0** [comment]
Thank you for your kind response.

If I can use 'select' like below, I can understand it.

```
class SelectExample extends ConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    int value = ref.watch(counterProvider.filter((s) => s.state > 5)).state;
    return Text('count value: $value');
  }
}
```

If filter is true, the widget will be rebuild. If false, it will not be rebuild.
I cannot understand how to handle isAbove5 to stop rebuilding.

**Comment by rrousselGit** [comment]
select is not a filter. It is equivalent to listening to changes on the selected value.

So if you did `final name = ref.watch(userProvider.select((user) => user.name))`, the widget would rebuild only when the user name changes.

So select is indeed a way to filter rebuilds. On the other hand, it does not behave like you mentioned.
What you are asking for is voluntarily not allowed

**Comment by xaatw0** [comment]
Thank you for a good example. It make me sence.
In your example, without 'select' riverpod watch a change of user.
With 'select', riverpod watch the change of user.name. Am I right?

I changed my example code. It rebuilt the widget.


```
class User {
  int id;
  String name;
  User(this.id, this.name);
}

final userProvider = StateProvider<User>(
  (ref) => User(0, "userName"),
);

onPressed: () {
  int id = ref.watch(stateProvider).state;
  String userName = "user$id";
  ref.watch(userProvider).state.name = userName;
},

class SelectExample extends ConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    String userName = ref.watch(userProvider.select((user) => user.state.name));
    return Text("select: $userName");
  }
}
```


If I changed the part of onPressed like below, the widget is not rebuilt.

```
int id = ref.watch(stateProvider).state;
ref.watch(userProvider).state.id = id;
```


Thank for your help for Remi and Tim! I am very glad to communicate with the famous author of riverpod!
