### ISSUE TITLE
[1.0.0-dev.6] No context.read extension in the latest dev version

### ISSUE THREAD

**Issue by omensight** [rrousselGit/river_pod#659]
[Description]
This and the main page of riverpod.dev says that the context have a read extension method, but now with the latest version this extension method doesn't exist anymore, so I would like to know what is the new aproach to read a StateNotifier<T> and call a method of its own.
https://pub.dev/documentation/flutter_riverpod/latest/flutter_riverpod/Consumer-class.html

**Comment by rrousselGit** [comment]
Using `Consumer` you can do:

```
Consumer(
  builder: (context, ref) {
    Button(onPressed: () => ref.read(provider.notifier).doSomething())
  }
)
