### ISSUE TITLE
Confusing syntax to manually dispose a provider 

### ISSUE THREAD

**Issue by wujek-srujek** [rrousselGit/river_pod#662]
**Describe the bug**

There are two ways to call `dispose`:
```dart
ref.read(provider).dispose();
```
and
```dart
ref.read(provider.notifier).dispose();
```
Both compile.

1. Which one should be used?
2. Why are there 2 of them? Both seem to be doing the same thing (i.e. dispose the provider in the example below).
3. Why does `ref.read(provider.notifier)` compile,  why is there the `notifier` word even though it is not a `StateNotifierProvider` - unless it is unrelated, but in this case it would be confusing.

**To Reproduce**

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() {
  runApp(ProviderScope(
    child: SampleApp(),
  ));
}

class SampleApp extends ConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: TextButton(
            onPressed: () {
              print(ref.read(provider).state);
              ref.read(provider).dispose();
              // ref.read(provider.notifier).dispose();
              print(ref.read(provider).state);
            },
            child: Text('Click me'),
          ),
        ),
      ),
    );
  }
}

final provider = StateProvider<List<String>>(
  (ref) {
    ref.onDispose(() {
      print('onDispose');
    });
    return [];
  },
);
```

**Expected behavior**

There is only one simple way of disposing a provider.

**Comment by rrousselGit** [comment]
> There are two ways to call `dispose`:
> 
> ```dart
> ref.read(provider).dispose();
> ```
> 
> and
> 
> ```dart
> ref.read(provider.notifier).dispose();
> ```

None of them are valid usage. You disposed the class but didn't dispose the provider.

You are not supposed to call `dispose`. That's the role of the provider. Disposing the provider will dispose the StateNotifier.


There is no such thing as manually disposing a provider at the moment.

**Comment by wujek-srujek** [comment]
Ok, makes sense as I don't recollect reading about it in the docs. There probably should be a comment on the method like:
```
Only meant for internal use.
```
or similar to avoid confusion.

You wrote:
```
Disposing the provider will dispose the StateNotifier.
```
But I don't have a `StateNotifier` anywhere in my example?

**Comment by rrousselGit** [comment]
> But I don't have a StateNotifier anywhere in my example?

You do. StateProvider creates a StateNotifier. That dispose function is the StateNotifier's dispose method.

**Comment by wujek-srujek** [comment]
Got it, thanks

**Comment by wujek-srujek** [comment]
@rrousselGit Just one more question, you wrote:
```
You disposed the class but didn't dispose the provider.
```
What do you mean by 'dispose the class'?

**Comment by rrousselGit** [comment]
You disposed the StateNotifier. StateNotifier has a dispose method, which is what you called.

This is unrelated to disposing providers. 

That's like if you did:

```dart
final provider = Provider((ref) => StreamContoller());

...

ref.read(provider).close(); // call StreamController.close
```

Riverpod has no idea that you called this method.
