### ISSUE TITLE
pub.score deduction for not using latest dependency for hooks

### ISSUE THREAD

**Issue by neiljaywarner** [rrousselGit/river_pod#671]
riverpod gets dinged for not having latest dependencies
-- eg https://pub.dev/packages/hooks_riverpod/score is 120
and 
can we please have an update that gets full marks for this even before 1.0 if possible - since 1.0 will probably have breaking changes being a major update.

thank you

**Comment by rrousselGit** [comment]
with hooks_riverpod 0.14.0+5 this should be fixed
