### ISSUE TITLE
Clearing state of all used providers

### ISSUE THREAD

**Issue by sderungs99** [rrousselGit/river_pod#676]
**Describe what scenario you think is uncovered by the existing examples/articles**
Is there a way how the state of all used providers can be reset? My use case is that not all my providers are using the autoDispose modifier, but I need to reset their state based on a certain event (e.g. when the active user logs out of my app).

**Describe why existing examples/articles do not cover this case**
Documentation describes the use case for autoDispose, but not how to dispose all providers programmatically

**Additional context**
I did ask the same question on stackoverflow (https://stackoverflow.com/questions/68690021/clear-state-in-providers-when-using-flutter-and-riverpod), but as you can see, no good answers there.

**Comment by rrousselGit** [comment]
You can call `context.refresh` on the providers of your choice

**Comment by sderungs99** [comment]
Thanks, although I was hoping there would be a way where this can be done without explicitly telling each provider to refresh. On stackoverflow, you answered a similar question, but related to the Provider package: https://stackoverflow.com/questions/57776375/clear-state-in-flutter-when-using-provider

The same thing couldn't be applied somehow to Riverpod, right?

**Comment by davidmartos96** [comment]
> Thanks, although I was hoping there would be a way where this can be done without explicitly telling each provider to refresh. On stackoverflow, you answered a similar question, but related to the Provider package: https://stackoverflow.com/questions/57776375/clear-state-in-flutter-when-using-provider
> 
> The same thing couldn't be applied somehow to Riverpod, right?

You could apply the same trick with keys in riverpod. The key would be in the top level ProviderScope which is the widget that holds the state of the providers

**Comment by rrousselGit** [comment]
> Thanks, although I was hoping there would be a way where this can be done without explicitly telling each provider to refresh. On stackoverflow, you answered a similar question, but related to the Provider package: https://stackoverflow.com/questions/57776375/clear-state-in-flutter-when-using-provider
> 
> The same thing couldn't be applied somehow to Riverpod, right?

This isn't a good approach to begin with.


What's wrong with passing the provider that needs to be refreshed? Why is that problematic for you?

**Comment by sderungs99** [comment]
Thank you for taking the time to look at this! :-)

Suppose I have an application with a login screen, a screen that shows animals I own and a screen that shows cars I own. When signing in with my user ID, my animals are shown and I can switch over to the screen that shows my cars. As my animals and cars almost never change, I don't use autoDispose on those providers (StateNotifierProvider), so that it only fetches data from the API when I access those pages the first time.

Now suppose that my wife is using this same app on the same device. So I log out of the app, my wife logs in with a different user ID. When accessing the animals page, she can see the animals I own rather than her own and when she is accessing the cars page, she can see the cars I own rather than her (as the providers don't refresh).

In sudo code, this looks something like this:

AuthController:
```
final authControllerProvider =
    StateNotifierProvider<AuthController, AuthModel?>(
        (ref) => AuthController(ref.read));

class AuthController extends StateNotifier<AuthModel?> {
  AuthController(this._read) : super(null);

  final Reader _read;

  Future<void> signIn(String email, String password) async {
      state = await _read(authRepositoryProvider).signIn(email, password);
  }

  Future<void> signOut() async {
    final _authRepository = _read(authRepositoryProvider);
    await _authRepository.signOut(state!.token);
    state = null;
  }
}
```

CarsController:
```
final carsControllerProvider = StateNotifierProvider<
    CarsController,
    AsyncValue<List<CarsModel>>>((ref) => CarsController(ref.read));

class CarsController
    extends StateNotifier<AsyncValue<List<CarsModel>>> {
  CarsController(this._read) : super(const AsyncValue.loading()) {
    myCars();
  }

  final Reader _read;

  Future<void> myCars({bool isRefreshing = false}) async {
    if (isRefreshing) {
      state = const AsyncValue.loading();
    }
  
      final cars = await _read(carsRepositoryProvider).myCars();
      state = AsyncValue.data(cars);
  }
}
```

With this, my thinking is that in the AuthController.signOut() function I should somehow be able to reset the state of the carsControllerProvider (and any other StateNotifierProviders I have). Is my thinking wrong?

**Comment by rrousselGit** [comment]
> With this, my thinking is that in the AuthController.signOut() function I should somehow be able to reset the state of the carsControllerProvider (and any other StateNotifierProviders I have). Is my thinking wrong?


This behaviour can be achieved without "resetting _all_ providers".

You may use `ref.watch` to voluntarily cause a provider to rebuild when a value changes, even if it doesn't use the said value.

So if you want to rebuild your `CarsController` when the user changes, your `carsControllerProvider` could do:


```dart
final carsControllerProvider = StateNotifierProvider<CarsController,  AsyncValue<List<CarsModel>>>((ref) {
  ref.watch(authControllerProvider); // rebuild the CarsController when the user changes
  return CarsController(ref.read);
});
```

**Comment by sderungs99** [comment]
awesome, thank you so much, this works and makes total sense!

**Comment by valaugustusbonite** [comment]
Hi @rrousselGit ! A bit late to the discussion but I have a situation very similar to @sderungs99 's.

Assume the same situation as above, I do not want to use `.autoDispose` to avoid having to recall the API after calling it the first time. So you could say I "cached" the data already. And when using `ref.watch(authProvider)` to a data provider, similar to the carsController above, I could simply rebuild and "reset" the data whenever  a user logs out and a different user logs in.

Given that, what would be the drawback to this? Without autoDispose, if I am not mistaken, the provider object still exists somewhere (and as stated in the documentation, it could cause memory leaks), so how do you go about this? 

Or should I just worry about this IF I combine this with a `.family` modifier, then I should heavily consider using `.autoDispose`? Thanks!

**Comment by ojm-it** [comment]
@rrousselGit I have the same question

**Comment by thorgexyz** [comment]
@rrousselGit 

> You may use ref.watch to voluntarily cause a provider to rebuild when a value changes, even if it doesn't use the said value.

As StreamProviders cache the latest emitted value, this can lead to problems, or? We had a case where the StreamProvider was providing the doc stream of the new user doc but emitted the last value of the previous user doc.

**Comment by Nidal-Bakir** [comment]
@rrousselGit 

I'm new to riverpod, and I do not know what the implications of dining that! I used to do that when I was using `Bloc` but I do not now what will happen if I do that!


``` dart 
import 'package:flutter/material.dart';
import 'package:get_it/get_it.dart';

import '../../injection_container/injection_container.dart';

class RestartApp extends StatefulWidget {
  final Widget child;

  const RestartApp({Key? key, required this.child}) : super(key: key);

  static void restart(BuildContext context) {
    context.findRootAncestorStateOfType<_RestartAppState>()!._restart();
  }

  @override
  State<RestartApp> createState() => _RestartAppState();
}

class _RestartAppState extends State<RestartApp> {
  var _key = UniqueKey();

  void _restart() async {
    await GetIt.I.reset(); // reset all the app dependencies 
    await init(); // init the app dependencies.

    setState(() {
      _key = UniqueKey();
    });
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      key: _key,
      child: widget.child,
    );
  }
}


```

* In main.dart

``` dart 
 runApp(RestartApp(child: ProviderScope(child: App())));
```


``` dart 
// When logout or login/register
RestartApp.of(context).restart();
```

**Comment by andy-tmpt-me** [comment]
@Nidal-Bakir thank you for this suggestion. I was looking for the same thing just now.

@rrousselGit I am loving Riverpod--very grateful for your work on this package.

Yes, it's true that you can call `ref.watch(authControllerProvider);` to create a dependency on the auth state in each provider. However, if any of the providers in the application forgets to add this call, then the app will potentially leak one user's data to another. @Nidal-Bakir 's approach is safer if there are many different providers that access permissioned data.
