### ISSUE TITLE
Global stateProvider and prevent non visible page update?

### ISSUE THREAD

**Issue by BigGitWorld** [rrousselGit/river_pod#678]
Hi everyone.

I am using Riverpod as state management package in my flutter application.

I have 2 pages (A, B).
PageA has a button and when user click on it, page B will be open:
```
Navigator.of(context).pushNamed(...);
```

I want to have a waiting mode in all my pages. So I have used one boolean provider for circularProgressIndicator for my project to keep loading in my app. In fact I am watching this provider in both page A and B.

```
final loadingProvider = StateProvider<bool>((_) => false);

//In both page :
final loading = watch(loadingProvider);
```

Therefore when state of this provider is changed in page B, widget tree of page A will be updated too.

How can I prevent page A from updating its widget tree when its not visible?

```
//In page B (This causes both page are updated)
loading.state = true;
```

**Comment by rrousselGit** [comment]
In this case you shouldn't use a single boolean for your entire application.

Instead have one per page
