### ISSUE TITLE
[1.0.0-dev.6] watch not causing rebuild for StateNotifierProvider

### ISSUE THREAD

**Issue by aliak00** [rrousselGit/river_pod#685]
**Describe the bug**
I have one widget where on a click I'm calling `ref.read(configProvider).name = 'bar';` and in the main `App` widget I'm watching `ref.watch(configProvider);`. When I change the value of `name`, the watcher does not get rebuilt.

Side note: I'm a little confused with the provider types. Is the `StateProvider` only for primitive types (i.e. value types) and the `StateNotifierProvider` for non-value types.

**To Reproduce**

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() {
  runApp(
    ProviderScope(
      overrides: [configProvider.overrideWithValue(ConfigNotifier(Config('foo')))],
      child: MyApp(),
    ),
  );
}

class MyApp extends ConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final name = ref.watch(configProvider).name;
    print(name);
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Center(
        child: TextButton(
          child: Text(name),
          onPressed: () {
            ref.read(configProvider).name = 'bar';
          },
        ),
      ),
    );
  }
}

class Config {
  String name;
  Config(this.name);
}

class ConfigNotifier extends StateNotifier<Config> {
  ConfigNotifier(Config state) : super(state);
}

final configProvider = StateNotifierProvider<ConfigNotifier, Config>((_) => throw UnimplementedError());

```

**Expected behavior**
I expect the top level `build` method to rerun when the text button is clicked.

**Comment by smiLLe** [comment]
You want to set `ConfigNotifier .state` to a new config rather than updating `config.name`

**Comment by aliak00** [comment]
Thanks @smiLLe! Ok so.... not a bug then!

Is there a way to not set the entire object and have the watchers be rebuilt? Say the `Config` object has a lot more properties, and I want some widgets rebuilt when any one of them change.

**Comment by smiLLe** [comment]
For `StateNotifier` you want to set `.state` to a new object :) I recommend you have a look at https://github.com/rrousselGit/freezed which makes updating your Config properties more easy.

**Comment by aliak00** [comment]
Closing as it's not a bug.
