### ISSUE TITLE
Update of state multiple nested class data

### ISSUE THREAD

**Issue by pishguy** [rrousselGit/river_pod#692]
after searching on many tutorial i can't update nested class data with this implementation, here i have a `OrderStructure` with a two field such as `title` and list of `products` which this `product` is another list named `services` which i defined on parent class

first of all when user click on button i save `title` and empty `product`'s service

```dart
void increment(int productId, int serviceId, int serviceCost) {
  final found = state.products.indexWhere((product) => product.id == productId);
  if (found < 0) {
    final List<SelectedProductServices> _s = [];
    _s.add(SelectedProductServices(serviceId, 1, serviceCost));
    state = OrderStructure(
      state.title
      [...state.products, SelectedProducts(productId, _s)],
    );
  }
```
now when `found` is equal or bigger than `0`, i should find `product` with passed `productId` and inside this search i should find `service`, if it saved before `cost` should be increment` otherwise it should insert new data in `products`

this is my code which i can't complete that and that has error and another problem is incrementing `count`

```dart
state = OrderStructure(state.title, [
  ...state.products,
  for (final product in state.products)
    if (product.id == productId)
      for (final service in product.services)
        if (service.id == serviceId)
          SelectedProducts(
              /* ------------------------------------------------------------- PROBLEM :[service.count++] */
              state.products, [...service, SelectedProductServices(service.id, service.count++, service.cost)])
        else
          ...state.products
]);
```

data classes structure:

```dart
class OrderStructure {
  final String title;
  final List<SelectedProducts> products;

  const OrderStructure(this.title,this.products);
}

class SelectedProducts {
  final int id;
  final List<SelectedProductServices> services;

  SelectedProducts(this.id, this.services);
}

class SelectedProductServices {
  final int id;
  final int count;
  final int cost;

  const SelectedProductServices(this.id, this.count, this.cost);
}
```

**Comment by TimWhiting** [comment]
Your count variable is final so you cannot increment it like that. I think you are trying to do `service.count + 1` there.

**Comment by pishguy** [comment]
@TimWhiting 

yes, i changed that, how can i resolve this problems?

> error: Spread elements in list or set literals must implement 'Iterable'
> error: The argument type 'List<SelectedProducts>' can't be assigned to the parameter type 'int'. 

thanks in advance

**Comment by TimWhiting** [comment]
You are trying to assign a list to an int, and have wrong types everywhere.
I think this is what you are trying to do.
```dart
final newState =  OrderStructure(state.title, [
  ...state.products,
  for (final product in state.products)
    if (product.id == productId)
      for (final service in product.services)
        if (service.id == serviceId)
          SelectedProducts(
             serviceId, [...product.services, SelectedProductServices(service.id, service.count+1, service.cost)])
]);
if (!newState.products.contains(productId) || !newState.products.firstWhere((p) => p.id == productId).services.contains(serviceId)){
  // Add new
  newState.products.add(SelectedProducts(serviceId, SelectedProductServices(serviceId, 1, cost)));
}
state = newState;
```

Something like this.

**Comment by pishguy** [comment]
@TimWhiting 

errors gone, thank you very much, in this part of code:

```dart
for (final product in state.products)
  if (product.id == productId)
    for (final service in product.services)
      if (service.id == serviceId)
        SelectedProducts(serviceId,
            [...product.services, SelectedProductServices(service.id, service.count + 1, service.cost)])
```
if `product` exists, that create another a product in list and after that i have multiple `product` as same id

i tried to fix that and solve problem. but i can't. could you help me please?
thanks

**Comment by TimWhiting** [comment]
```dart
final newState =  OrderStructure(state.title, []);
for (final product in state.products){
  if (product.id == productId) {
    if (product.services.contains((s) => s.id == serviceId) {
        final service = product.services.firstWhere((s) => s.id == serviceId);
        newState.products.add(SelectedProducts(
             productId, [...product.services.where((s) => s.id != serviceId), SelectedProductServices(service.id, service.count+1, service.cost)]));
    } else {
      newState.products.add(SelectedProducts(
             productId, [...product.services, SelectedProductServices(serviceId, 1, cost)]));
    }
  } else {
    newState.products.add(product);
  }
}
if (!newState.products.contains(productId) || !newState.products.firstWhere((p) => p.id == productId).services.contains(serviceId)){
  // Add new
  newState.products.add(SelectedProducts(serviceId, SelectedProductServices(serviceId, 1, cost)));
}
state = newState;
```

This is some pretty complex update logic.I wouldn't do it using the for / if inside of collections. This is best done imperatively. In any case you should be asking these kinds of questions on StackOverflow or Discord, since it is not an issue with Riverpod.

**Comment by pishguy** [comment]
@TimWhiting 

I ask in StackOverflow with 500 bounty to find which one can help me resolve this problem

thanks

**Comment by pishguy** [comment]
@TimWhiting i found what was problem, that was `contains` which it doesn't work and couldn't find in nested class data, i changed it to `any`

thanks so much
