### ISSUE TITLE
In Riverpod 1.0.0-dev.7 ProviderObserver.didUpdateProvider is called also when StateProvider has same value as before.

### ISSUE THREAD

**Issue by rydmike** [rrousselGit/river_pod#694]
## Description 

When using Riverpod 1.0.0-dev.7 setting the value of a `StateProvider` the `ProviderObserver.didUpdateProvider` is called for a `StateProvider` also when the value has not been changed. Docs say:

```dart
/// An object that listens to the changes of a [ProviderContainer].
///
/// This can be used for logging or making devtools.
abstract class ProviderObserver { ... }
```

This implies that if there is **no** change the observer should not be called since it has not changed. This needs a fix imo, or documentation improvement. Personally I think it would be more logical and useful for the intended purpose of a `ProviderObserver` if it was not called at all in this case.

Related issue: https://github.com/rrousselGit/river_pod/issues/693

## To Reproduce

Please see this simple counter example repo: https://github.com/rydmike/pods_obs_issue

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() {
  runApp(
    ProviderScope(
      observers: <ProviderObserver>[ProvidersObserver()],
      child: MyApp(),
    ),
  );
}

final StateProvider<int> counterProvider =
    StateProvider<int>((StateProviderRef ref) {
  return 0;
}, name: 'counter');

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Riverpod 1.0.0-dev.7 Issue'),
    );
  }
}

class MyHomePage extends ConsumerWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '${ref.watch(counterProvider).state}',
              style: Theme.of(context).textTheme.headline4,
            ),
            SizedBox(height: 16),
            ElevatedButton(
              onPressed: () {
                debugPrint('Set to ZERO');
                ref.read(counterProvider).state = 0;
              },
              child: Text('Reset to ZERO'),
            )
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          ref.read(counterProvider).state++;
        },
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

/// ProvidersObserver used in this demo to debugPrint changes.
class ProvidersObserver extends ProviderObserver {
  @override
  void didUpdateProvider(ProviderBase<dynamic> provider, Object? previousValue,
      Object? newValue, ProviderContainer container) {
    if (newValue is StateController && previousValue is StateController) {
      debugPrint('Provider is StateController: '
          '${provider.name ?? provider.runtimeType} \n'
          'new value: ${newValue.state}\n'
          'previous value: ${previousValue.state}');
    }
  }
}
```

When clicking the (+) button the observer is called value is set to 1.
When pushing the **Reset to ZERO** and values was not zero before, the Observer is called.
When pushing the **Reset to ZERO** and values was already zero, the Observer is called.

```
Reloaded 1 of 582 libraries in 407ms.
flutter: Provider is StateController: counter 
flutter: new value: 1
flutter: previous value: 1
flutter: Set to ZERO
flutter: Provider is StateController: counter 
flutter: new value: 0
flutter: previous value: 0
flutter: Set to ZERO
flutter: Provider is StateController: counter 
flutter: new value: 0
flutter: previous value: 0
flutter: Set to ZERO
```

## Expected behavior

When clicking the (+) button the observer is called value is set to 1.
When pushing the **Reset to ZERO** and value was not zero before, the Observer is called.
When pushing the **Reset to ZERO** and values was already zero, the Observer is **NOT** called.

```
Restarted application in 591ms.
flutter: Provider is StateController: counter 
flutter: new value: 1
flutter: previous value: 0
flutter: Set to ZERO
flutter: Provider is StateController: counter 
flutter: new value: 0
flutter: previous value: 1
flutter: Set to ZERO
flutter: Set to ZERO
```

**Comment by rrousselGit** [comment]
This is expected. The observer is called whenever you call `state=`, which will cause widgets to rebuild.

**Comment by rydmike** [comment]
Sure, but from an observer usability point of view it makes no sense with the used StateProvider.

**Comment by rrousselGit** [comment]
Agree to disagree

**Comment by rydmike** [comment]
In combination with https://github.com/rrousselGit/river_pod/issues/693 this will force us to maintain the previous state separately so we can avoid doing things in the observer, if the state of the StateProvider was not changed. Not very usable considering the intended purpose of the observer.

**Comment by rydmike** [comment]
> Agree to disagree

Sure 🤷🏻‍♂️ no worries. 

It still makes using the Observer much less useful to "observe real changes that are of interest" and only actually do things when such changes really happened. It now gets triggered when there is no real use for it when it comes to StateProviders and because of https://github.com/rrousselGit/river_pod/issues/693 there is not even inside the Observer any way of checking if it really needs to do any work, you just always have to do it, even if nothing changed, which is a bit suboptimal imo.

**Comment by rrousselGit** [comment]
Observers aren't for listening to changes on a state.

If you want to do that, use `ref.listen`, which offers what you want:

```dart
ref.listen(stateProvider.select((c) => c.state.count), (count) {
  // count changed
});
```

**Comment by rydmike** [comment]
Thanks Remi and yes I know. 
However, in this particular case we preferred to not create a listener for every `StateProvider` (a lot of them, more than 50) to listen to their changes individually. The Observer actually does this job quite nicely, and we can log and store changes to all of them in one small compact location. 

I admit it is rare that a StateProvider is ever set to the same value that it had before, so it is not like the Observer does a lot of extra things that is not really needed, but it happens, rarely though, so not really a major thing, just a tiny bit suboptimal.

We also did not want to make the StateProviders, property values in a `StateNotifierProvider` instead, since that would force me to filter on each of them to ensure we rebuild only when each single value in it changes, doable sure, but I would also need a filter on each property value to just listen to each individual property value when it was changed to only then do the needed work. This is also quite tedious. The `ProviderObserver` is imo a very convenient way to do it 😃 

It is kind of nice and super convenient for doing something like this (a bit simplified):

```dart
/// RiverPod provider observer used to store the state of selected Riverpod
/// StateProviders and debugPrint changes to them in debug mode.
class ProviderStateObserver extends ProviderObserver {
  @override
  void didUpdateProvider(ProviderBase provider, Object? previousValue,
      Object? newValue, ProviderContainer container) {
    // If it is one of the StateProviders that we are interested in,
    // it will be of type StateController.
    if (newValue is StateController) {
      // If it is one that we have a named key for, we will store it in Hive.
      if (KeyStore.defaults.containsKey(provider.name)) {
        // Log the new value, just a debugPrint for now and in DebugMode builds only.
        if (kDebugMode) {
          debugPrint('Provider: ${provider.name ?? provider.runtimeType} '
              'value: ${newValue.state}');
        }
        // Store the new value in our Hive box.
        hiveStore.put(provider.name, newValue.state);
      }
    }
  }
}
```

**Comment by rrousselGit** [comment]
If that's for serialization, why not make a custom StateController and use StateNotifierProvider? Same effect but you'd have more control over what you can do

**Comment by rrousselGit** [comment]
I'll close this. I don't think ProviderObserver life-cycles should behave differently than ref.listen & co.

Maybe you instead want StateProvider to filter values using ==.

That wouldn't do anything for #693 though.
