### ISSUE TITLE
Where should I put Computed?

### ISSUE THREAD

**Issue by tbm98** [rrousselGit/river_pod#7]
As far as I know, `Computed` is like a filter and it only calculates and notifies `Consumer` when there's a change. So in case I have a complex state, I need a lot of `Computed`, should I set my `Computed` as global variables or set it as static variables or something else?
If I set as global variables, I can't remember them all 😕

**Comment by rrousselGit** [comment]
You could set them as static variables on your Model

Like:

```dart
class MyNotifier extends StateNotifier {
  static final myComputed =Computed(...)
}
```

Or keep them all in the same file

**Comment by tbm98** [comment]
Is there any memory problem if I have many static variables ?

**Comment by rrousselGit** [comment]
No. That's the same thing as using global variables.

**Comment by tbm98** [comment]
Yep. Thanks!
I'll use static variables

**Comment by kaboc** [comment]
What if it's not global nor static?
For example, is it also fine to use `Computed` in every method where the value is necessary, like the way we use `select()` of the provider package?
My concern is especially whether the computed is disposed of and stops listening properly at/after the end of each method scope.

```dart
class Counter with ChangeNotifier {
  int value1;
  int value2;

  ...
}

...

@override
Widget build(BuildContext context) {
  final computed = Computed((read) => read(counterProvider).value1);
  return Text('value: ${read(computed)});
}
```

**Comment by rrousselGit** [comment]
Bad idea, at least for now.
A Computed isn't fully destroyed when no-longer used. It'll likely change in the future, but for now you'd have a leak

**Comment by rrousselGit** [comment]
If you want a "select", there's one for hooks:

```
useProvider(myProvider.select((value) => value.foo))
```

**Comment by kaboc** [comment]
OK, I'll think about using hooks, hoping it'll be improved in the future.
Thanks anyway!

**Comment by rrousselGit** [comment]
What is your need to begin with?

**Comment by tbm98** [comment]
Hi.
I not found `select` function on provider
<img width="692" alt="Screen Shot 2020-06-24 at 5 08 16 PM" src="https://user-images.githubusercontent.com/52562340/85536663-7dea7880-b63d-11ea-8747-f26d5f53858a.png">

**Comment by kaboc** [comment]
@rrousselGit 
My notifiers extending `ChangeNotifier` (not `StateNotifier`) have more than one properties, so I use `select()` to pick out only part of them for efficiency, preventing unnecessary rebuilds. If the same control is not possible with `Computed`, all computed values have to be declared globally or as static properties of some class(es), which will end up in having a long declaration list of Computed...

But it may not be so bad. Probably I'm just having some difficulty at the moment accepting that `Computed` and `select()` seem similar but are used differently.

**Comment by kaboc** [comment]
@tbm98 
Have you imported `hooks_riverpod` correctly ?

**Comment by tbm98** [comment]
@kaboc no, but I think `select` function only in `ChangeNotifier`

**Comment by rrousselGit** [comment]
> But it may not be so bad. Probably I'm just having some difficulty, at this early stage, accepting the fact that Computed and select() seem similar but are used differently. I'll get used to it soon.

Computed is cached and shared
select is local and not cached

**Comment by kaboc** [comment]
Got it. I'll tell it to myself again and again until I accept it.
