### ISSUE TITLE
ProviderScope's overrides doesn't get updated when a widget rebuilds

### ISSUE THREAD

**Issue by michalkubizna** [rrousselGit/river_pod#700]
**Describe the bug**
ProviderScope's overrides doesn't get updated when a widget rebuilds

**To Reproduce**

In this case when the widget rebuilds "1" gets printed but not "123". Because of that scopedFoodProvider deosn't get updated with new values when new data gets pulled from the database. 

```
print(1);
    return ProviderScope(
      overrides: [
        scopedFoodProvider.overrideWithProvider(Provider((ref) {
          print(123);

          return Food.copy(food);
        })),
      ],

```

**Comment by rrousselGit** [comment]
This is the expected behavior of "overrideWithProvider", which caches the computation. 

You may instead want to use "overrideWithValue", which does what you described

**Comment by michalkubizna** [comment]
Thanks!
