### ISSUE TITLE
How to sync/access a value of a provider b/w flutter and pure dart

### ISSUE THREAD

**Issue by prateekmedia** [rrousselGit/river_pod#701]
Alternate Title:
How to use a WidgetRef even after getting disposed or how to stop it from being disposed on page pop.

**Describe the bug**
Let's say initial value of a StateNotifier was x.

When I change it to y and then access it using consumer hook widget ref then it returns y.

But when I access it using ProviderContainer(), then it returns x (i.e initial value).

Used in flutter:
```dart
ref.watch(myProvider);
```

Used in dart:
```dart
container.watch(myProvider)
```
**Expected behavior**
They both should return the same value.

**Comment by davidmartos96** [comment]
If you are creating a ProviderContainer yourself, you shouldn't do that. You are essentially creating a different universe of providers with their respective initial values. Instead, read the provider values with a ref object.

**Comment by prateekmedia** [comment]
@davidmartos96  How to use ref objects with pure dart, I am writing code inside a function, so I don't have access to ref object.

**Comment by davidmartos96** [comment]
Then you need to pass a ref as a parameter to your function.
Alternatively, if this function is inside a class created within a provider, you can pass the ref as a constructor argument to then use it from inside.

**Comment by prateekmedia** [comment]
@davidmartos96 I tried that, but when the widget disposed the ref also got disposed, but my function contains a running task(downloading a file) and at the same time updating the value of the download.

**Comment by davidmartos96** [comment]
I'm not sure what you mean. Do you have some code as an example?

**Comment by prateekmedia** [comment]
Here is my code explained:

- I use dio package to download a files and then update the value of the bytes received and total bytes in state notifier provider.

This is a continuous process so it will required the ref to be alive even when HookConsumerWidget is disposed.

Code here 

https://github.com/prateekmedia/appimagepool/blob/10aa863308ded3d632bd74b9f0e6b3d7e6eddfd1/lib/widgets/download_button.dart#L155

**Comment by davidmartos96** [comment]
You could place the download logic inside a notifier and use the ref that you get in the provider callback, that way you can make sure that the ref is alive.you shouldn't rely on a widget ref after executing any await. It's similar to the Buildcontext in that sense.

**Comment by prateekmedia** [comment]
> You could place the download logic inside a notifier and use the ref that you get in the provider callback, that way you can make sure that the ref is alive. You shouldn't rely on a widget ref after executing any await. It's similar to the Buildcontext in that sense.

Thanks @davidmartos96 I will look into it.
