### ISSUE TITLE
Is ScopedReader going away with version 1.0.0?

### ISSUE THREAD

**Issue by mark8044** [rrousselGit/river_pod#702]
First thank you for this amazing project.  It has been an absolute game changer!

I have been successfully been using `0.14.0+3` without a problem.  

My app mainly gets its data via `ConsumerWidget` which then populates my UI from that data

```
class NewsScreenConsumer extends ConsumerWidget {
  NewsScreenConsumer(this._scrollController, this.idnum);
  ScrollController _scrollController;
  String idnum;

  @override
  Widget build(BuildContext context, ScopedReader watch)
  {

    /// PROVIDER SETUP
   final data = watch(newsProvider(idnum));

   return (.... UI ...)
}
}
```

#### But I have now come across a situation where I needed to use this structure inside a `StatefulWidget` #### 
(mainly I am trying to attach scrollcontroller listeners) to list views and came across a problem with losing scroll to top functionality (its a long story, but I might be able to solve it by using `PrimaryScrollController.of(context)`.  But I digress...

So I came across some SO posts saying there is a `ConsumerStatefulWidget` inside the `1.0.0` version?  I'm not sure if that is true, but I tried the `1.0.0-dev.7` and my app immediately has a lot of errors everywhere 
`error: Undefined class 'ScopedReader'.` and `error: The method 'read' isn't defined for the type 'BuildContext'.`

As a matter of future proofing my app for riverpod 1.0.0 is ScopedReader going away?

**Comment by mark8044** [comment]
Ok after some research the answer to my own question seems to be **YES**

I'll leave this issue open incase I've made some glaring mistake

It looks like `ScopedReader` is going away so it might be best to stop including it in apps?

Using `1.0.0` What I've been able to do is change my code as follows and it seems to work

```
class NewsScreenConsumer extends ConsumerStatefulWidget {
  NewsScreenConsumer({Key? key, required this.scrollController, required this.idnum}) : super(key: key);
  ScrollController scrollController;
  String idnum;

  @override
  _NewsScreenConsumerState createState() => _NewsScreenConsumerState();
}

class _NewsScreenConsumerState extends ConsumerState<NewsScreenConsumer> {

  @override
  Widget build(BuildContext context)
  {

    /// PROVIDER SETUP
   final data = ref.watch(newsProvider(widget.idnum));

   return (.... UI ...)
}
}
```

And in regards to `context.read` that seems to be gone as well.

I was able to get it working with a combination of `ref.refresh(newsProvider(idnum)).fetchData;` when I'm using it in the initState and `ref.watch(newsProvider(idnum)).fetchData` in the build context

**Comment by TimWhiting** [comment]
I'm not the author so I can't say if there will be many more changes. But I don't think there will be a lot. There is a migration tool to automate most of the migration. Check out https://pub.dev/packages/riverpod_cli (the dev version), or install via: `dart pub global activate riverpod_cli 1.0.0-dev.6`, and then run `riverpod migrate` (probably safest to do on a branch of your code so you can revert if you need to). However, there is at least one change that I know is coming down the pipeline that hasn't been merged / published yet relating to the AsyncValue class, so I suggest maybe waiting for that, unless you don't really use AsyncValue / FutureProvider / StreamProvider, or are willing to migrate it manually when those changes come.

**Comment by rrousselGit** [comment]
You can use ConsumerWidget instead of ConsumerStatefulWidget if you don't need a StatefulWidget.

But otherwise yes, the syntax you used is correct, and indeed ScopedReader is going away.
