### ISSUE TITLE
ref.listen inside StateNotifier

### ISSUE THREAD

**Issue by arnoutvandervorst** [rrousselGit/river_pod#705]
I'm trying to listen to a StreamProvider inside a StateNotifier to load new messages and append them to the already existing list to enable paged loading using Firestore. Before Riverpod 1.0.0 I was using a StreamSubscription, which works, but I would like to switch over to ref.listen to allow a StreamProvider rather than having to manage the subscription inside the StateNotifier. However, when using ref.listen, I don't understand this compile-time error, what am I doing wrong and how should I solve this?

The argument type 'AutoDisposeStreamProvider<List<DocumentSnapshot<Message>>>' can't be assigned to the parameter type 'AlwaysAliveProviderListenable<List<DocumentSnapshot<Message>>>'.

```dart
class GroupMessagesStateNotifier extends StateNotifier<GroupMessagesState> {
  StreamSubscription<List<QueryDocumentSnapshot<Message>>>? _streamSubscription;
  ProviderRefBase ref;
  String groupId;

  GroupMessagesStateNotifier(
    this.ref,
    this.groupId,
  ) : super(
          GroupMessagesState(),
        ) {
    groupId = groupId;

    loadFirstPage();
  }

  @override
  void dispose() {
    _streamSubscription?.cancel();
    super.dispose();
  }

  Future<void> loadFirstPage() async {
    state = state..status = MessagesStatus.loading;

    // Compile error:
    ref.listen<List<DocumentSnapshot<Message>>>(
      GroupMessage.firstPageStreamProvider(groupId),
      (value) {},
    );

// Want to replace this:
    _streamSubscription = GroupMessage.collRef(groupId)
        .orderBy(fnDocCreatedAt, descending: true)
        .limit(messageTake)
        .snapshots()
        .map((list) => list.docs)
        .listen(
      (documentSnapshots) {
        if (documentSnapshots.isEmpty) {
          state = state..status = MessagesStatus.done;
          return;
        }

        state = state
          ..startAfterDocument = documentSnapshots.last
          ..messages = documentSnapshots.mapToList
          ..status = MessagesStatus.data;
      },
    );
  }

  Future<void> loadMore() async {
    if (state.startAfterDocument == null) {
      return;
    }

    state = state..status = MessagesStatus.loading;

    _streamSubscription = GroupMessage.collRef(groupId)
        .orderBy(fnDocCreatedAt, descending: true)
        .startAfterDocument(state.startAfterDocument!)
        .limit(messageTake)
        .snapshots()
        .map((list) => list.docs)
        .listen(
      (documentSnapshots) {
        if (documentSnapshots.isEmpty) {
          state = state..status = MessagesStatus.done;
          return;
        }

        state = state
          ..startAfterDocument = documentSnapshots.last
          ..messages = [
            ...state.messages,
            ...documentSnapshots.mapToList,
          ]
          ..status = MessagesStatus.data;
      },
    );
  }

  void addMessageToStart(Message message) {
    state = state
      ..messages = [
        message,
        ...state.messages,
      ];
  }

  void refresh() {
    loadFirstPage();
  }
}
```

And my StreamProvider:
```dart
  static final firstPageStreamProvider = StreamProvider.family
      .autoDispose<List<DocumentSnapshot<Message>>, String>(
    (ref, groupId) => collRef(groupId)
        .orderBy(fnDocCreatedAt, descending: true)
        .limit(messageTake)
        .snapshots()
        .map((list) => list.docs),
  );
```

**Comment by davidmartos96** [comment]
It's possible that you are listening an auto dispose provider from a non auto dispose one. Check out this part in the docs: https://riverpod.dev/docs/concepts/modifiers/auto_dispose/#the-argument-type-autodisposeprovider-cant-be-assigned-to-the-parameter-type-alwaysaliveproviderbase

**Comment by arnoutvandervorst** [comment]
Yes I'm aware of that constraint, however how would the compiler know that, since I'm listening inside a StateNotifier which is not yet linked to any provider.

The actual provider using the StateNotifier IS autoDispose btw:
```dart
  static final stateNotifierProvider = StateNotifierProvider.family
      .autoDispose<GroupMessagesStateNotifier, GroupMessagesState, String>(
    (ref, groupId) => GroupMessagesStateNotifier(ref, groupId),
  );
```

**Comment by arnoutvandervorst** [comment]
Also, in 0.14, it compiled using ref.watch, but then it didn't work the way I wanted as the ref.watch caused the entire StateNotifier to be rebuilt, I just want to listen to the stream inside the StateNotifier and process the resulting data. I've not yet found a really elegant way of doing pagination with Firestore using a DocumentSnapshot as bookmark. Using a StreamSubscription is currently the best I can do but it seems bloated.

**Comment by davidmartos96** [comment]
> The actual provider using the StateNotifier IS autoDispose btw:

Oh, then I'm not sure what could it be. It looks very related though

Yes, watch will rebuild the notifier. You are telling riverpod that your notifier depends on what you are watching. Listen just notifies you about a change, which is what you need.

Maybe other people or Remi can help you about the compile time error.

**Comment by rrousselGit** [comment]
Sounds like you typed the "ref" object as `ProviderRefBase` instead of `AutoDisposeProviderRefBase`

The former doesn't allow auto-dispose providers, the latter do.

**Comment by arnoutvandervorst** [comment]
Thanks for the reply Remi, if I type the ref as you suggest, then I get the following compile message:

The argument type 'AutoDisposeStreamProvider<List<DocumentSnapshot<Message>>>' can't be assigned to the parameter type 'ProviderListenable<List<DocumentSnapshot<Message>>>'.

**Comment by rrousselGit** [comment]
That's because your provider is a StreamProvider, so the value exposed is an AsyncValue

Which means ref.listen should be typed as:

```dart
ref.listen<AsyncValue<List<DocumentSnapshot>>>(streamprovider, (snapshot) {

});
```

**Comment by arnoutvandervorst** [comment]
Ah of course! Thanks!

**Comment by arnoutvandervorst** [comment]
Seems like this syntax is broken in 1.0.0 stable? AutoDisposeProviderRefBase is no longer available, should I use AutoDisposeProviderRef instead?

Also, after upgrading from dev11 to 1.0.0, this error is generated by the analyzer:
The argument type 'void Function(AsyncValue<List<DocumentSnapshot<Earning>>>?)' can't be assigned to the parameter type 'void Function(AsyncValue<List<DocumentSnapshot<Earning>>>?, AsyncValue<List<DocumentSnapshot<Earning>>>)'.

```dart```
ref.listen<AsyncValue<List<DocumentSnapshot<Earning>>>>(
      Earning.pageStreamProvider(state),
      (snapshot) {
        snapshot.when<void>(
          data: (documentSnapshots) {
            if (documentSnapshots.isEmpty) {
              state = state.copyWith(status: LoadingStatus.empty);
            } else {
              state = state.copyWith(
                startAfterDocument: documentSnapshots.last,
                entries: documentSnapshots.mapToList,
                status: LoadingStatus.data,
              );
            }
          },
          loading: () => state = state.copyWith(status: LoadingStatus.loading),
          error: (err, stack) => LogService.providerError(err, stack),
        );
      },
    );

**Comment by TimWhiting** [comment]
This is because listen now contains both the current and previous values:

```dart
ref.listen<AsyncValue<List<DocumentSnapshot<Earning>>>>(
      Earning.pageStreamProvider(state),
      (previous, snapshot) {
        snapshot.when<void>(
          data: (documentSnapshots) {
            if (documentSnapshots.isEmpty) {
              state = state.copyWith(status: LoadingStatus.empty);
            } else {
              state = state.copyWith(
                startAfterDocument: documentSnapshots.last,
                entries: documentSnapshots.mapToList,
                status: LoadingStatus.data,
              );
            }
          },
          loading: () => state = state.copyWith(status: LoadingStatus.loading),
          error: (err, stack) => LogService.providerError(err, stack),
        );
      },
    );
```

And yes, use `AutoDisposeProviderRef` instead of `AutoDisposeProviderRefBase`

**Comment by rrousselGit** [comment]
> AutoDisposeProviderRefBase is no longer available

ProviderRefBase was renamed to Ref.
So AutoDisposeRef.

Alternatively you can use AutoDisposeStateNotifierProviderRef. Although it's not necessary in your case
