### ISSUE TITLE
How does one update/read a provider outside of a widget in 1.0.0?

### ISSUE THREAD

**Issue by mark8044** [rrousselGit/river_pod#709]
I'm in the process of converting my app from riverpod `0.14.0` to `1.0.0` and came across this snag.

I've so far been reading my providers without a consumer widget, by using `context.read()`.

Now with `1.0.0` I've been converting my  `StatefulWidget` to `ConsumerStatefulWidget` and I can continue to read/manipulate my providers with `ref.read` for the most part.

But I also have some functions outside of a widget which I was formerly able to read/update with `.read` but how do I access now with `1.0.0`?

WIth 0.14.0 this worked ==>
```
MyRequest(String url, {map = ''})  async {
...
    navigatorKey.currentContext!.read(uploadProgressProvider).state = _percent;
...
}
```

Now with `1.0.0` I cannot figure how to update that `uploadProgressProvider` ?  Its a provider which holds an integer value that is updated with an http-send and that is then read and displayed in my UI

**Comment by TimWhiting** [comment]
Either you need to pass a `WidgetRef` into the function that used to take the `BuildContext`, or you need to wrap the class that used the `BuildContext` with a provider and pass the `ProviderRef` into the class. Hard to know what to do in your situation, because there is not enough context in what you are trying to do and where you are doing it. Basically you need to use a Provider or ConsumerWidget or ConsumerStatefulWidget.

**Comment by mark8044** [comment]
> Either you need to pass a `WidgetRef` into the function that used to take the `BuildContext`, or you need to wrap the class that used the `BuildContext` with a provider and pass the `ProviderRef` into the class. Hard to know what to do in your situation, because there is not enough context in what you are trying to do and where you are doing it. Basically you need to use a Provider or ConsumerWidget or ConsumerStatefulWidget.

Dang.

The function is just a void function used for HTTP communication.

Before, I was able to basically use the `context.read` as a sort of "global variable" in my layman's terms.

I guess that's simply not possible anymore is what you are saying?

For now I've done what you said and I passed `ref` into my function and it is working (much appreciated!) but it doesn't "feel" right.  I feel like I'm overlooking something?

**Comment by TimWhiting** [comment]
If it is a HTTP request, I would wrap it in a FutureProvider.

**Comment by rrousselGit** [comment]
> For now I've done what you said and I passed ref into my function and it is working (much appreciated!) but it doesn't "feel" right. I feel like I'm overlooking something?

You're probably overthinking.

As long as you're not passing the ref from one widget to another, there's nothing wrong.

**Comment by mark8044** [comment]
> > For now I've done what you said and I passed ref into my function and it is working (much appreciated!) but it doesn't "feel" right. I feel like I'm overlooking something?
> 
> You're probably overthinking.
> 
> As long as you're not passing the ref from one widget to another, there's nothing wrong.

@TimWhiting @rrousselGit 

Ok so what I've found while doing some googling is creating some kind of global variable in main.dart like this:
```
final globalriverpod = ProviderContainer();
```
and now within my void function I can successfully play with my providers 
```
globalriverpod.read(uploadProgressProvider).state;
```

Is this horribly wrong?

The reason I'm still pursuing this is that I have another case where I have multiple void functions calling each other and passing my `ref` variable between them all is becoming way to cumbersome

**Comment by rrousselGit** [comment]
This is a bad idea.

You shouldn't create a ProviderContainer.

**Comment by mark8044** [comment]
> This is a bad idea.
> 
> You shouldn't create a ProviderContainer.

Fair enough, do you think passing the `ref` between my void functions is the way to go?  Theres about 3 of them :)

**Comment by rrousselGit** [comment]
It'd alright.

But chances are there's a way to do without.
For example, your functions could be methods on an object that has a "ref" instead.
Typically a StateNotifier

**Comment by mark8044** [comment]
> It'd alright.
> 
> But chances are there's a way to do without.
> For example, your functions could be methods on an object that has a "ref" instead.
> Typically a StateNotifier

Heres what I'm up to, if you don't have time for this don't even worry about it, but figure I'll show you where I'm getting stuck

Im uploading an image and showing the progress of that upload in a widget



#### main.dart declaration ####
```
final realTimeUploadProgressValueProvider = StateProvider((ref) => 0.0);
final navigatorKey = GlobalKey<NavigatorState>();

class MyApp extends StatelessWidget{
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {

    return  MaterialApp(
          (...)
          navigatorKey: navigatorKey
          (...);
  }
}
```

#### a user picks an image from the gallery and then the picker runs this function to process the image ####
```
Future<Map<String, dynamic>> imageUpload(File file)
async {

  ...
  String fileName = file.path.split('/').last;
  var finalData = {
    'imageupload' : await MultipartFile.fromFile(file.path, filename:fileName),
  };

  MarkUploadProgress(); /// This is a widget which appears on the screen and displays a progress circle

    final response = await appPostRequest(thisUrl, map:finalData); /// This is a custom void function that uploads the image

 return response;
}
```



## this is where I'm stuck --> ##
#### this is the appPostRequest() function which does the http upload ####
```
appPostRequest(String daUrl, {map = ''})  //data is in the form of a map
async {

  optionsPost.baseUrl = daUrl;
  var dio = Dio(optionsPost);

  dio.interceptors.add(CookieManager(cookieJar));

  var formData = FormData.fromMap(map);

  var _res;

  _res = await dio.post(daUrl, data: formData, onSendProgress: (int send, int total)
  {
    var _percent = send / total;   /// This is the percent of the file that's been upload

    ///TODO  FIX THIS BASED ON WHAT RIVERPOD GUYS SAY
    navigatorKey.currentContext!.read(realTimeUploadProgressValueProvider).state = _percent;   /// This is where Im stuck, this no longer works with version 1.0.0 and I can't find a way to upload the value of my provider here
    
  });

  return _res;
}
```

#### this is the MarkUploadProgress() widget in case it matters ####
```
void MarkUploadProgress() async {
  showGeneralDialog(
    context: navigatorKey.currentContext!,
    pageBuilder: (_, __, ___) {
      return Material(
        child: (...)
                child: RealTimeProgressValue() /// This is the ConsumerWidget which pulls the real time image upload progress value
      );
    },
    transitionBuilder: (...)
  );
}
```

#### The final UI for the widget ####
```
class RealTimeProgressValue extends ConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // Listens to the value exposed by counterProvider
    var count = ref.watch(realTimeUploadProgressValueProvider).state;
    var countInteger = count*100;

    return Stack(
      alignment: Alignment.center,
      children: [
        SizedBox(
          width:94.0,
          height:94.0,
          child: CircularProgressIndicator(
              strokeWidth: 1,
              value:count
          ),
        ),

      ],
    );

  }
}
```

**Comment by TimWhiting** [comment]
```dart
final uploadServiceProvider = Provider((ref) => UploadService(ref.read));

class UploadService {
  final Reader read;
  UploadService(this.read);
  Future<void> appPostRequest(String daUrl, {map = ''})  async {
    optionsPost.baseUrl = daUrl;
    var dio = Dio(optionsPost);
  
    dio.interceptors.add(CookieManager(cookieJar));
  
    var formData = FormData.fromMap(map);
  
    var _res;
  
    _res = await dio.post(daUrl, data: formData, onSendProgress: (int send, int total)
    {
      var _percent = send / total;   /// This is the percent of the file that's been upload
      read(realTimeUploadProgressValueProvider).state = _percent;       
    });
  
    return _res;
  }

}

```

**Comment by mark8044** [comment]
> ```dart
> ```dart
> final uploadServiceProvider = Provider((ref) => UploadService(ref.read));
> 
> class UploadService {
>   final Reader read;
>   UploadService(this.read);
>   Future<void> appPostRequest(String daUrl, {map = ''})  async {
>     optionsPost.baseUrl = daUrl;
>     var dio = Dio(optionsPost);
>   
>     dio.interceptors.add(CookieManager(cookieJar));
>   
>     var formData = FormData.fromMap(map);
>   
>     var _res;
>   
>     _res = await dio.post(daUrl, data: formData, onSendProgress: (int send, int total)
>     {
>       var _percent = send / total;   /// This is the percent of the file that's been upload
>       read(realTimeUploadProgressValueProvider).state = _percent;       
>     });
>   
>     return _res;
>   }
> 
>   Future<Map<String, dynamic>> imageUpload(File file) async {
>     String fileName = file.path.split('/').last;
>     var finalData = {
>       'imageupload' : await MultipartFile.fromFile(file.path, filename:fileName),
>     };
>   
>   
>    final response = await appPostRequest(thisUrl, map:finalData); /// This is a custom function that uploads the image
>   
>    return response;
>   }
> }
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> Then in your widget:
> ```dart
> ref.read(uploadServiceProvider).imageUpload(file);
> ```
> ```

Thanks for the code!!

Evaluating it now, I just didn't want to leave you hanging. 

Its not exactly working for a few reasons (you have appPostRequest as a `void` but then have it returning `_res` for example), so I'm working on it now to get it to work  but getting caught up

But as far as I understand it you are trying to make my entire upload scheme work via a provider? kinda cool... let me see if I can get this to work

**Comment by mark8044** [comment]
> ```dart
> ```dart
> final uploadServiceProvider = Provider((ref) => UploadService(ref.read));
> 
> class UploadService {
>   final Reader read;
>   UploadService(this.read);
>   Future<void> appPostRequest(String daUrl, {map = ''})  async {
>     optionsPost.baseUrl = daUrl;
>     var dio = Dio(optionsPost);
>   
>     dio.interceptors.add(CookieManager(cookieJar));
>   
>     var formData = FormData.fromMap(map);
>   
>     var _res;
>   
>     _res = await dio.post(daUrl, data: formData, onSendProgress: (int send, int total)
>     {
>       var _percent = send / total;   /// This is the percent of the file that's been upload
>       read(realTimeUploadProgressValueProvider).state = _percent;       
>     });
>   
>     return _res;
>   }
> 
>   Future<Map<String, dynamic>> imageUpload(File file) async {
>     String fileName = file.path.split('/').last;
>     var finalData = {
>       'imageupload' : await MultipartFile.fromFile(file.path, filename:fileName),
>     };
>   
>   
>    final response = await appPostRequest(thisUrl, map:finalData); /// This is a custom function that uploads the image
>   
>    return response;
>   }
> }
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> Then in your widget:
> ```dart
> ref.read(uploadServiceProvider).imageUpload(file);
> ```
> ```

Ok this is my fault, I should have included the entire chain of code, the `imageUpload` is called from a series of other functions, so your `ref.read` doesn't work.  I will have to pass `ref` through so many functions to get it to the finish line.  LOL


```
Future<void> avatarProcess(XFile image)
async {

  if (image != null) {

    var croppedFile = await ImageCropper.cropImage(
        sourcePath: image.path,
        androidUiSettings: AndroidUiSettings(
            toolbarTitle: 'Cropper',
            toolbarColor: Colors.deepOrange,
            toolbarWidgetColor: Colors.white,
            initAspectRatio: CropAspectRatioPreset.original,
            lockAspectRatio: true),
        iosUiSettings: IOSUiSettings(
            minimumAspectRatio: 1.0,
            aspectRatioLockEnabled: true
        )
    );

     if (croppedFile != null) { await imageUpload(croppedFile); }

  }


}
```

which is in turn called from this function

```
void showPickerAvatar(context, callback) {

  final ImagePicker _picker = ImagePicker();

  showModalBottomSheet(
    useRootNavigator: true,
      context: context,
      builder: (BuildContext bc) {
        return SafeArea(
          child: Container(
            child: new Wrap(
              children: <Widget>[
                new ListTile(
                    leading: new Icon(Icons.photo_library),
                    title: new Text('Photo Library'),
                    onTap: () async {

                      final XFile? image = await _picker.pickImage(source: ImageSource.gallery);

                      if (image != null) {
                        await avatarProcess(image);
                        callback();
                      }

                      Navigator.of(bc).pop();

                    }),
                new ListTile(
                  leading: new Icon(Icons.photo_camera),
                  title: new Text('Camera'),
                  onTap: () async {

                    final XFile? photo = await _picker.pickImage(source: ImageSource.camera);

                    if (photo != null) {
                      await avatarProcess(photo);
                      callback();
                    }

                    Navigator.of(bc).pop();

                  },
                ),
              ],
            ),
          ),
        );
      }
  );
}


```

**Comment by TimWhiting** [comment]
I would expect `showPickerAvatar` to be a method in a ConsumerWidget or StatefulConsumerWidget where you have easy access to a WidgetRef or can easily pass a WidgetRef in. I would expect `avatarProcess` to be a method in a service provider such as the upload service provider in the example. So you really shouldn't have to pass ref everywhere, except maybe to a method in a ConsumerWidget

**Comment by mark8044** [comment]
In the end it was just easier to pass `ref` through the series of widgets and its working--- thanks everyone for the help and even the existence of riverpod which has saved me a lot of headaches!

**Comment by davidmartos96** [comment]
@mark8044 Watch out passing the ref though widgets, that could get you into trouble hard to debug.

Instead of this:
MyContainer(ref: ref)

Make a different consumer widget to obtain the ref.

**Comment by mark8044** [comment]
> @mark8044 Watch out passing the ref though widgets, that could get you into trouble hard to debug.
> 
> Instead of this:
> MyContainer(ref: ref)
> 
> Make a different consumer widget to obtain the ref.

Thanks for the suggestion, but it sounds like I have no choice but to pass the ref through these Functions since they have no way of knowing the context?  Up above @rrousselGit says its ok to pass ref around like this.  I agree I don't necessarily like to pass the ref like that because its hard to trace it all back, but he's right and its working perfectly fine now
