### ISSUE TITLE
StateNotifierProvider.family.autoDispose causes grey screen on Flutter Web (Release build)

### ISSUE THREAD

**Issue by HiroshiHorie** [rrousselGit/river_pod#71]
**Describe the bug**

I am not sure this is a Flutter bug or Riverpod bug.

When using StateNotifierProvider.family.autoDispose, it causes a grey screen on Flutter Web. **Only happens on Release build**, Debug is fine. If I don't use autoDispose it is also fine. I think I didn't experience this before the family.autoDispose style new syntax. My current work-around is not to use autoDispose.

I get this on the web console:
``Another exception was thrown: Instance of 'minified:iu<void>'``

**Possibly related:**
1. [flutter web : Another exception was thrown: Instance of 'minified:aM<void>'](https://github.com/flutter/flutter/issues/47880)
2. [How to fix the “minified:aq<void>” flutter web error](https://stackoverflow.com/questions/59239793/how-to-fix-the-minifiedaqvoid-flutter-web-error)
> In my case, it was an static method uninitialized unexpectedly that triggered this issue. Seems like a webdev bug , only failed on web release build.

**To Reproduce**

1. use ``StateNotifierProvider.family.autoDispose``
2. build with flutter web release mode

Regards

Using:
```
Flutter 1.21.0-1.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision f25bd9c55c (3 weeks ago) • 2020-07-14 20:26:01 -0400
Engine • revision 99c2b3a245
Tools • Dart 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)
```

**Comment by rrousselGit** [comment]
This is a bug in  dart2js https://github.com/dart-lang/sdk/issues/41449


Try upgrading your sdk to the latest version possible

**Comment by rrousselGit** [comment]
I will close this as it isn't an issue with Riverpod but the Dart SDK. If the issue persists, ping the Dart team on https://github.com/dart-lang/sdk/issues/41449

**Comment by venkatd** [comment]
Has anyone found a workaround? I'm on a pretty recent version (1.22.0-1.0.pre) but I am still having the exception on web.

I saw a comment here https://github.com/dart-lang/sdk/issues/41449#issuecomment-655654274 but was unable to get my build working properly. I may not be understanding their exact recommendation though.

**Comment by rrousselGit** [comment]
There's a workaround here: https://github.com/rrousselGit/river_pod/blob/master/examples/marvel/lib/src/screens/character_detail.dart#L36

**Comment by venkatd** [comment]
Great, thanks!

**Comment by Kleak** [comment]
when we use useListenable in release mode it seems to drop some type also.

**Comment by Albert-Jan** [comment]
Currently facing the same issue. I only get this issue when trying to run it in production. Any update on this?

**Comment by rrousselGit** [comment]
Instead do `AutoDisposeStateNotifierFamily` for now.

The bug is in Dart. I can't do anything

**Comment by jaredweinfurtner** [comment]
> Instead do `AutoDisposeStateNotifierFamily` for now.
> 
> The bug is in Dart. I can't do anything

This doesn't work in:

```
Flutter 3.3.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision eb6d86ee27 (9 days ago) • 2022-10-04 22:31:45 -0700
Engine • revision c08d7d5efc
Tools • Dart 2.18.2 • DevTools 2.15.0
```

The only thing that appears to work is removing the `autoDispose` entirely.
