### ISSUE TITLE
.watch properly works for a floatingActionButton but not for Appbar actions ? 

### ISSUE THREAD

**Issue by mark8044** [rrousselGit/river_pod#718]
I have the following bit of code (cut short for space reasons, full code can be provided if needed)

```
    return WillPopScope(
      onWillPop: _onWillPop,
        child: Scaffold(
            appBar: AppBar(
              title: Text('Title')
              actions: <Widget>[
                MyUserIcon()
              ],
            ),
            floatingActionButton:
            (int.parse(ref.watch(globalUserDataProvider).userid) > 0) ?
            FloatingActionButton( ...) 
            : null,
            body: Stack( ... )
```

When my `globalUserDataProvider` is updated, my `FloatingActionButton` updates in realtime and I see the button appear or disappear depending on if `userid` is > 0.  Thats working great, looks and runs amazingly!

#### However ####
I also have a user Icon sitting in the appbar in the actions area `MyUserIcon()`.  This part does not update in realtime when the `globalUserDataProvider` is updated

Here is the `MyUserIcon()` widget condensed.  In order to keep things small in this report, Ive replaced the actual images with Text widgets here, `User is NOT logged in` and `User is logged in`.

What should be happening is those text widgets should update in real-time when `globalUserDataProvider` is updated, but they aren't changing

Is this something to do with my code or to do with the structure of riverpod do you think?

```

class MyUserIcon extends ConsumerStatefulWidget {
  MyUserIcon({Key? key, this.callback}) : super(key: key);

  @override
  _MyUserIconState createState() => _MyUserIconState();
}


class _MyUserIconState extends ConsumerState<MyUserIcon> with WidgetsBindingObserver {

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance!.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance!.removeObserver(this);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {

    var data = ref.watch(globalUserDataProvider);


    return
      Container(
          child:Row(
            children: [
              IconButton(
                padding: EdgeInsets.zero,
                icon:
                (int.parse(ref.watch(globalUserDataProvider).userid) > 0)
                    ?
                Container(margin:EdgeInsets.fromLTRB(0.0, 0, 5.0, 4.0),
                    child: ClipRRect(borderRadius: BorderRadius.circular(100.0),
                        child:
                        (int.parse(ref.watch(globalUserDataProvider).userid) > 0) ?
                        Text('User is logged in')
                            :
                            Text('User is NOT logged in')
                    ))
                    :
                Text('User is NOT logged in')
                onPressed: () async {
...
                },
              ),
            ],
          )
      );

  }
}
```

**Comment by rrousselGit** [comment]
Hello!

I do not understand your code. But what is `globalUserDataProvider`? Chances are the problem is in your provider, not the widget.

**Comment by mark8044** [comment]
> Hello!
> 
> I do not understand your code. But what is `globalUserDataProvider`? Chances are the problem is in your provider, not the widget.

Hey!

Its a `ChangeNotifierProvider`

```
final globalUserDataProvider = ChangeNotifierProvider<GlobalUserData>((ref) {
  return GlobalUserData();
});


class GlobalUserData with ChangeNotifier{
  static var _userId = '0';
  static var _userAvatar = '';

  String get userid => _userId;
  String get useravatar => _userAvatar;

  static setUserData(String a, String b) {
    _userId = a;
    _userAvatar = b;
  }

}
```

I thought the problem might be that I am not doing a `notifyListeners()` call inside my `setUserData` that is the problem right?

As some background I am setting this data from a void Function that is not in my widget tree `  GlobalUserData.setUserData(_newuserid, _newuseravatar);` so I had to set `setUserData` to a static variable for it to work.

But when I made it into a `static` then I am not allowed to use `notifyListeners()`.

What is interesting about all this is going back to my first post, the `ref.watch(globalUserDataProvider).userid` still seems to work in my `floatingActionButton`

**Comment by rrousselGit** [comment]
It's quite likely that the lack of a notifyListeners is the issue, yes.

As for why you were not able to call `notifyListeners`, chances are you're trying to modify the state while widgets are building, which is not allowed. You may need to use `addPostFrameCallback`
