### ISSUE TITLE
Naming of 'family'

### ISSUE THREAD

**Issue by josh-burton** [rrousselGit/river_pod#723]
I've just started using riverpod, and really like it. Feels like Provider but a bit more flexible.

The naming of the `family` method confuses me though. It's not obvious to me what it does right away, and I wonder if something like `withValue` might be a better name and since riverpod is still pre 1.0 it could still be changed.

I'm sure you have a really good reason for naming it family though!

**Comment by rrousselGit** [comment]
"family" is the named used for a similar pattern in React.

It represents the fact that this doesn't define _one_ provider, but rather a group of providers that are closely related with each others ... like a family.

**Comment by TimWhiting** [comment]
In the docs you could also mention that it cover the use case of a factory which I think is a question I see asked here a lot.

**Comment by josh-burton** [comment]
> "family" is the named used for a similar pattern in React.
> 
> It represents the fact that this doesn't define _one_ provider, but rather a group of providers that are closely related with each others ... like a family.

Is that accurate with the usage of `family`?

The docs say: 
```
.family, which allows creating a provider from external parameters.

```

Is that creating a family of providers, or creating just one provider from multiple values?

**Comment by rrousselGit** [comment]
Think of `Provider.family<Param, Value>` as a `Map<Param, Provider<Value>>`


And think of `ref.watch(provder(param))` as a map access like `map[param]`

So if you do:

```dart
final a = ref.watch(provider('a'));
final b = ref.watch(provider('b'));
```

you're effectively reading two completely different providers.

**Comment by josh-burton** [comment]
ok yep that makes sense. I've figured out family is rarely what I need to use, as it makes it difficult to look up the same provider from multiple places.

e.g.
I can't just create a provider once using `ref.watch(myProvider('a'))`, and then look it up later using `ref.watch(myProvider)`. This does make sense but wasn't obvious at first as the docs point to family as the way to provide parameters to a provider.

Instead what I'm using and is working well is a ProviderScope and overriding a dummy provider with the actual implementation:

```
final assetsDetailViewModel = Provider<AssetDetailViewModel>((ref) {
  throw UnimplementedError();
});

...
ProviderScope(
          overrides: [
            assetsDetailViewModel.overrideWithProvider(ChangeNotifierProvider<AssetDetailViewModel>(
              (ChangeNotifierProviderRef ref) => AssetDetailViewModel(
                asset,
              ),
            )),
          ],
          child: Builder(builder: (context) {
            return AssetDetailBottomSheet(asset: asset);
          }),
        );
      },
```

This works really well, but at first feels a bit hacky. I wonder if it might be worth documenting an approach like this?

**Comment by mark8044** [comment]
I'll chime in that  the name`family` clicked immediately for me and worked perfectly right out of the box and my app is now littered with its use.  Seamless and without problems and was the game-changing feature for riverpod over provider for my case at least.

I vote to keep it as is :)

**Comment by rrousselGit** [comment]
:wave:
I'll close this since it seems like it's not gaining much traction.
