### ISSUE TITLE
Crash when use provider.overrideWithValue with OpenContainer animation

### ISSUE THREAD

**Issue by tbm98** [rrousselGit/river_pod#732]
it crashes when I use OpenContainer animation to open a Page, this page use provider.overrideWithValue, overrideWithProvider is ok.

it is also ok when I use 
```
Navigator.push(context, MaterialPageRoute(builder: (context) {
                    return Page;
                  }));
```

https://user-images.githubusercontent.com/52562340/131950024-d57a8fa9-bddb-4a75-b79a-faecdee70e81.mov

minimal repo: [here](https://github.com/tbm98/flutter_app_bug_report)

Riverpod: 1.0.0 dev-7
animations: 2.0.1
flutter: dev 2.6.0-0.0.pre

**Comment by rrousselGit** [comment]
I will investigate, but your example is misusing `overrideWithValue`

Doing:

```dart
ProviderScope(
  overrides: [
    counterProvider.overrideWithValue(CounterNotifier(11))
  ],
  child: Counter(),
),
```

is illegal, since your StateNotifier will never be disposed, and whenever your widget rebuilds your counter will lose its state,

**Comment by tbm98** [comment]
So in what case should I use `overrideWithValue `?

**Comment by rrousselGit** [comment]
Either the value you're passing is stateless & override == (ints, strings, ...)

Or the value is cached (possibly with a StatefulWidget).

**Comment by tbm98** [comment]
Yes. Thank you!

**Comment by tbm98** [comment]
Hi @rrousselGit.
I can see this issue no longer exists on stable 2.5.2 and riverpod dev 11. Is this safe to close for now?
