### ISSUE TITLE
Please dumb down the official examples

### ISSUE THREAD

**Issue by nyck33** [rrousselGit/river_pod#735]
**Describe what scenario you think is uncovered by the existing examples/articles**
A clear and concise description of the problem that you want explained.
Firstly, it seems the author is brilliant and this library is tremendously useful for Flutter developers.
However, the official examples are extremely difficult to follow for novices like myself as they include many tricks for optimization which I believe should be left out or provided in a separate file.  
As-is, I cannot even get it running having to edit the `pubspec.yaml` and even simple issues like the button colors not appearing correctly possibly due to FlatButton not being used anymore and trying to replace it with ElevatedButton.  Also having everything crammed into two files in the todos example makes it very difficult so I tried to separate into many files (one class per file) which I believe is more standard for Flutter developers.  
Thus, I can imagine someone brilliant like the author just whipping this out very quickly but please keep in mind those of us who are less capable when presenting examples. 

**Describe why existing examples/articles do not cover this case**
Explain which examples/articles you have seen before making this request, and
why they did not help you with your problem.
The todos example is just way too complicated.  I was able to follow another todos tutorial which was simpler on orders of magnitude.

**Additional context**
Add any other context or screenshots about the documentation request here.

**Comment by wilpar** [comment]
Fully agree.   When all you want is a form...  it's overkill.  I ended up just using setState for my form fields.  Maybe this is preferred? Don't know.

**Comment by thanh-vo-opun-ai** [comment]
Maybe the author does not have time to update the example!
You can folk the example and create pr right?

**Comment by TimWhiting** [comment]
I recommend checking out flutter_hooks for local state. Riverpod is meant more for app state (apis, dependency injection, etc) and not local state (animations, forms, etc). Not that you can't do the latter with Riverpod, it is just overkill for it. setState works if you don't want to use  flutter_hooks.

**Comment by rrousselGit** [comment]
> However, the official examples are extremely difficult to follow for novices like myself as they include many tricks for optimization which I believe should be left out or provided in a separate file.

Which trick/optimization are you referring to?

> I cannot even get it running having to edit the pubspec.yaml

Could you clarify the issue with the pubspec.yaml?

> even simple issues like the button colors not appearing correctly possibly due to FlatButton not being used anymore and trying to replace it with ElevatedButton.

Could you expand on that too? I don't see what this is referring to.

> Also having everything crammed into two files in the todos example makes it very difficult so I tried to separate into many files (one class per file) which I believe is more standard for Flutter developers.

The examples are using the standard of the Flutter Framework, which is split by features rather than split by split by type.
This is the recommended folder architecture when using Riverpod, and as such worthy of being used by the examples IMO.

What would you change exactly?

**Comment by nyck33** [comment]
Firstly, I want to apologize for some of the inconsistencies above which resulted from not updating this issue after hearing back from @rrousselGit  on updating Flutter to make examples run.  Thus, that takes care of the issue with `pubspec.yaml` ( I  was trying to run it after only downloading the todos folder rather than the entire repo for Riverpod).  Second with tricks/optimizations I understand what is being done and explained now that I had time to go through Riverpod documentation multiple times while building my own Todo app so they are probably okay if others also get deeper into the documentation.
The button issue was probably related to me trying to use the folder on its own, after making some very rookie mistakes in trying to edit the files so it would run.
I understand now this is how Flutter using Riverpod should be organized and am thankful for your advice here on this point.
However, I am currently running into the following error when running on my device:

```


```
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following StateNotifierListenerError was thrown while handling a gesture:
At least listener of the StateNotifier Instance of 'StateController<TodoListFilter>' threw an
exception
when the notifier tried to update its state.

The exceptions thrown are:

'package:riverpod/src/framework/scheduler.dart': Failed assertion: line 29 pos 12: '!_disposed':
tried to emit updates with a disposed Scheduler
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      _ProviderScheduler._scheduleTask (package:riverpod/src/framework/scheduler.dart:29:12)
#3      _ProviderScheduler.scheduleProviderRefresh
(package:riverpod/src/framework/scheduler.dart:25:5)
#4      ProviderElementBase.markMustRecomputeState
(package:riverpod/src/framework/base_provider.dart:642:27)
#5      ProviderElementBase._didChangeDependency
(package:riverpod/src/framework/base_provider.dart:758:5)
#6      ProviderElementBase.notifyListeners
(package:riverpod/src/framework/base_provider.dart:737:22)
#7      _listenStateProvider.listener (package:riverpod/src/state_provider.dart:66:9)
#8      StateNotifier.state= (package:state_notifier/state_notifier.dart:214:31)
#9      StateController.state= (package:riverpod/src/state_provider.dart:25:31)
#10     Toolbar.build.<anonymous closure> (package:todos/main.dart:185:39)
#11     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
#12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:193:24)
#13     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
#14     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#15     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:267:7)
#16     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
#17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:444:20)
#18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
#19     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
#20     GestureBinding._handlePointerEventImmediately
(package:flutter/src/gestures/binding.dart:374:7)
#21     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#24     _rootRunUnary (dart:async/zone.dart:1444:13)
#25     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#27     _invoke1 (dart:ui/hooks.dart:185:10)
#28     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#29     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)

When the exception was thrown, this was the stack:
#0      StateNotifier.state= (package:state_notifier/state_notifier.dart:227:7)
#1      StateController.state= (package:riverpod/src/state_provider.dart:25:31)
#2      Toolbar.build.<anonymous closure> (package:todos/main.dart:185:39)
#3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:193:24)
#5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
#6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
#7      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:267:7)
#8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
#9      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:444:20)
#10     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
#11     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
#12     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
#13     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
#14     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
#15     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
#19     _invoke1 (dart:ui/hooks.dart:185:10)
#20     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
#21     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
(elided 3 frames from dart:async)

Handler: "onTap"
Recognizer:
  TapGestureRecognizer#0a04a
════════════════════════════════════════════════════════════════════════════════════════════════════
W/IInputConnectionWrapper(15440): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(15440): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(15440): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(15440): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(15440): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(15440): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(15440): endBatchEdit on inactive InputConnection
I/TextInputPlugin(15440): Composing region changed by the framework. Restarting the input method.
W/IInputConnectionWrapper(15440): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(15440): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(15440): getTextAfterCursor on inactive InputConnection
E/flutter (15440): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:riverpod/src/framework/scheduler.dart': Failed assertion: line 29 pos 12: '!_disposed': tried to emit updates with a disposed Scheduler
E/flutter (15440): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (15440): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (15440): #2      _ProviderScheduler._scheduleTask (package:riverpod/src/framework/scheduler.dart:29:12)
E/flutter (15440): #3      _ProviderScheduler.scheduleProviderRefresh (package:riverpod/src/framework/scheduler.dart:25:5)
E/flutter (15440): #4      ProviderElementBase.markMustRecomputeState (package:riverpod/src/framework/base_provider.dart:642:27)
E/flutter (15440): #5      ProviderElementBase._didChangeDependency (package:riverpod/src/framework/base_provider.dart:758:5)
E/flutter (15440): #6      ProviderElementBase.notifyListeners (package:riverpod/src/framework/base_provider.dart:737:22)
E/flutter (15440): #7      ProviderElementBase.setState (package:riverpod/src/framework/base_provider.dart:597:7)
E/flutter (15440): #8      ProviderElement.setState (package:riverpod/src/provider/base.dart:262:11)
E/flutter (15440): #9      StateNotifierProvider.create.listener (package:riverpod/src/state_notifier_provider/base.dart:66:11)
E/flutter (15440): #10     StateNotifier.state= (package:state_notifier/state_notifier.dart:214:31)
E/flutter (15440): #11     TodoList.add (package:todos/todo.dart:29:5)
E/flutter (15440): #12     Home.build.<anonymous closure> (package:todos/main.dart:106:53)
E/flutter (15440): #13     EditableTextState._finalizeEditing (package:flutter/src/widgets/editable_text.dart:1945:27)
E/flutter (15440): #14     EditableTextState.performAction (package:flutter/src/widgets/editable_text.dart:1804:9)
E/flutter (15440): #15     TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1389:37)
E/flutter (15440): #16     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:386:55)
E/flutter (15440): #17     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:379:34)
E/flutter (15440): #18     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:379:35)
E/flutter (15440): #19     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:376:46)
E/flutter (15440): #20     _invoke2.<anonymous closure> (dart:ui/hooks.dart:205:15)
E/flutter (15440): #21     _rootRun (dart:async/zone.dart:1428:13)
E/flutter (15440): #22     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (15440): #23     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (15440): #24     _invoke2 (dart:ui/hooks.dart:204:10)
E/flutter (15440): #25     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
E/flutter (15440): #26     _Channel.push (dart:ui/channel_buffers.dart:132:31)
E/flutter (15440): #27     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
E/flutter (15440): #28     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544:22)
E/flutter (15440): #29     _dispatchPlatformMessage (dart:ui/hooks.dart:92:31)
E/flutter (15440): 
W/IInputConnectionWrapper(15440): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(15440): endBatchEdit on inactive InputConnection

Another exception was thrown: At least listener of the StateNotifier Instance of 'TodoList' threw an
exception
W/IInputConnectionWrapper(15440): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(15440): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(15440): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(15440): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(15440): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(15440): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(15440): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(15440): endBatchEdit on inactive InputConnection
I/TextInputPlugin(15440): Composing region changed by the framework. Restarting the input method.
W/IInputConnectionWrapper(15440): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(15440): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(15440): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(15440): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(15440): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(15440): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(15440): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(15440): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(15440): endBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(15440): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(15440): endBatchEdit on inactive InputConnection
I/TextInputPlugin(15440): Composing region changed by the framework. Restarting the input method.
W/IInputConnectionWrapper(15440): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(15440): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(15440): getTextAfterCursor on inactive InputConnection
E/flutter (15440): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:riverpod/src/framework/scheduler.dart': Failed assertion: line 29 pos 12: '!_disposed': tried to emit updates with a disposed Scheduler
E/flutter (15440): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (15440): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (15440): #2      _ProviderScheduler._scheduleTask (package:riverpod/src/framework/scheduler.dart:29:12)
E/flutter (15440): #3      _ProviderScheduler.scheduleProviderRefresh (package:riverpod/src/framework/scheduler.dart:25:5)
E/flutter (15440): #4      ProviderElementBase.markMustRecomputeState (package:riverpod/src/framework/base_provider.dart:642:27)
E/flutter (15440): #5      ProviderElementBase._didChangeDependency (package:riverpod/src/framework/base_provider.dart:758:5)
E/flutter (15440): #6      ProviderElementBase.notifyListeners (package:riverpod/src/framework/base_provider.dart:737:22)
E/flutter (15440): #7      ProviderElementBase.setState (package:riverpod/src/framework/base_provider.dart:597:7)
E/flutter (15440): #8      ProviderElement.setState (package:riverpod/src/provider/base.dart:262:11)
E/flutter (15440): #9      StateNotifierProvider.create.listener (package:riverpod/src/state_notifier_provider/base.dart:66:11)
E/flutter (15440): #10     StateNotifier.state= (package:state_notifier/state_notifier.dart:214:31)
E/flutter (15440): #11     TodoList.add (package:todos/todo.dart:29:5)
E/flutter (15440): #12     Home.build.<anonymous closure> (package:todos/main.dart:106:53)
E/flutter (15440): #13     EditableTextState._finalizeEditing (package:flutter/src/widgets/editable_text.dart:1945:27)
E/flutter (15440): #14     EditableTextState.performAction (package:flutter/src/widgets/editable_text.dart:1804:9)
E/flutter (15440): #15     TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1389:37)
E/flutter (15440): #16     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:386:55)
E/flutter (15440): #17     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:379:34)
E/flutter (15440): #18     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:379:35)
E/flutter (15440): #19     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:376:46)
E/flutter (15440): #20     _invoke2.<anonymous closure> (dart:ui/hooks.dart:205:15)
E/flutter (15440): #21     _rootRun (dart:async/zone.dart:1428:13)
E/flutter (15440): #22     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (15440): #23     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (15440): #24     _invoke2 (dart:ui/hooks.dart:204:10)
E/flutter (15440): #25     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
E/flutter (15440): #26     _Channel.push (dart:ui/channel_buffers.dart:132:31)
E/flutter (15440): #27     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
E/flutter (15440): #28     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544:22)
E/flutter (15440): #29     _dispatchPlatformMessage (dart:ui/hooks.dart:92:31)
E/flutter (15440): 
W/IInputConnectionWrapper(15440): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(15440): endBatchEdit on inactive InputConnection

Another exception was thrown: At least listener of the StateNotifier Instance of 'TodoList' threw an
exception

Another exception was thrown: setState() or markNeedsBuild() called during build.
```
Finally another issue I noticed with this example as well as my own Todo app (https://github.com/nyck33/todo_riverpod_freezed) is that if I move away from the app for example go to the Android home screen and then come back, the app state is reset to the starting state.  I know about Shared Preferences, saving to a database but that seems like a lot of work to save state when the app is not closed, just moved away from.  Please clarify if Riverpod has a way of saving state when the user moves away.

**Comment by rrousselGit** [comment]
What you're describing is a bug that was fixed earlier today, but the fix isn't published yet.

**Comment by rrousselGit** [comment]
> Please clarify if Riverpod has a way of saving state when the user moves away.

Not at the moment, no. But maybe in the future

**Comment by nyck33** [comment]
I found a really good article on data persistence with Riverpod: https://medium.com/@mxiskw/flutter-pragmatic-architecture-using-riverpod-123ae11a8267
