### ISSUE TITLE
ChangeNotifierProvider disposes of the ChangeNotifier when it's previous is swapped even if not auto disposed

### ISSUE THREAD

**Issue by nibuen** [rrousselGit/river_pod#738]
**Describe the bug**
ChangeNotifierProvider disposes of the ChangeNotifier when it's previous is swapped even if not auto disposed:

```
mixin _ChangeNotifierProviderStateMixin<T extends ChangeNotifier?>
    on ProviderStateBase<T, T> {
  @override
  void valueChanged({T? previous}) {
    if (createdValue == previous) {
      return;
    }
    previous?.removeListener(_listener);
    previous?.dispose();
    exposedValue = createdValue;
    createdValue?.addListener(_listener);
  }
...
```
**To Reproduce**

Use a StreamProvider that can supply ChangeNotifiers that

```
final selectedKidProvider = FutureProvider<Kid>((ref) async {
  return await ref.watch(kidProvider);
});

final kidProvider = ChangeNotifierProvider<Kid>(
  (ref) {
    return ref.watch(selectedKidStreamProvider).when(
        data: (data) {
          //debugPrint("new data ${data.firstName}");
          return data;
        },
        loading: () => Kid(firstName: "new", registered: false),
        error: (e, s) => Kid(firstName: "new", registered: false));
  },
);
```

**Expected behavior**
Should only dispose of the ChangeNotifier if using autoDispose.

**Comment by rrousselGit** [comment]
You are misusing providers.  You should not return an existing ChangeNotifier. Rather, you should always create a new one.

So your "when(data)" is not allowed, and you should instead create the `Kid` object within the provider.

**Comment by nibuen** [comment]
Ok, so the general rule is the providers own the lifecycle of the object despite if autodispose is used or not?

It would still be nice to reuse long lived change notifiers, but I suppose that may ok against there original intention that I am not aware of though.
