### ISSUE TITLE
Error: method not found: 'Object.hash'

### ISSUE THREAD

**Issue by nyck33** [rrousselGit/river_pod#739]
**Describe the bug**
I cloned the repo so I can run the Marvel example, ran `flutter pub get`, put the `configurations.json` in `assets`, cd'ed to `examples/marvel` and ran `flutter run`.  
I get an error:
```
../../packages/riverpod/lib/src/common.dart:173:30: Error: Method not found: 'Object.hash'.
  int get hashCode => Object.hash(runtimeType, value);                  
                             ^^^^                                       
../../packages/riverpod/lib/src/common.dart:374:30: Error: Method not found: 'Object.hash'.
  int get hashCode => Object.hash(runtimeType, previous);               
                             ^^^^                                       
../../packages/riverpod/lib/src/common.dart:415:30: Error: Method not found: 'Object.hash'.
  int get hashCode => Object.hash(runtimeType, error, stackTrace);      
                             ^^^^                                       
                                                                        
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/home/nobu/snap/flutter/common/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1035
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildDebug'.              
> Process 'command '/home/nobu/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 38s                                                     
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        42.4s
Exception: Gradle task assembleDebug failed with exit code 1
```

**To Reproduce**

<Please add a small sample to that can be executed to reproduce the problem. As a general rule, 100 lines is the maximum>

Please see above.

**Expected behavior**

I was hoping to run the Marvel example.

**Comment by rrousselGit** [comment]
See #726
You need to upgrade your flutter sdk

**Comment by nyck33** [comment]
I'm sorry, I should run it twice or thrice as the first time I ran `flutter upgrade`, it gave me some short message so I thought it was already up-to-date but right now I can see it downloading 2.5.  Thanks again.

**Comment by rrousselGit** [comment]
Flutter 2.5 should indeed fix the problem

**Comment by Josiassejod1** [comment]
doesn't work for me, I want to reopen this


<img width="562" alt="Screen Shot 2021-09-29 at 3 03 59 PM" src="https://user-images.githubusercontent.com/12024422/135354937-70c376f9-7c80-4619-9fb0-498b6fc9c7c2.png">
l

**Comment by Josiassejod1** [comment]
<img width="793" alt="Screen Shot 2021-09-29 at 3 05 46 PM" src="https://user-images.githubusercontent.com/12024422/135355121-7734c721-465d-4fad-9221-6e8cbf20ff0b.png">

**Comment by iamarnas** [comment]
> <img width="793" alt="Screen Shot 2021-09-29 at 3 05 46 PM" src="https://user-images.githubusercontent.com/12024422/135355121-7734c721-465d-4fad-9221-6e8cbf20ff0b.png">
> 

@Josiassejod1 Try Flutter clean, remove `pubspec.lock` file and run `pub run`

**Comment by darshakpranpariya** [comment]
> > <img alt="Screen Shot 2021-09-29 at 3 05 46 PM" width="793" src="https://user-images.githubusercontent.com/12024422/135355121-7734c721-465d-4fad-9221-6e8cbf20ff0b.png">
> 
> @Josiassejod1 Try Flutter clean, remove `pubspec.lock` file and run `pub run`

It doesn't help me.
P.S. I am using flutter 2.2.3
