### ISSUE TITLE
Can not update another provider state inside FutureProvider

### ISSUE THREAD

**Issue by hazzo** [rrousselGit/river_pod#749]
**Describe the bug**
In riverpod 1.0.0-dev.5 I was able to modify a provider state inside a `FutureProvider` but in versión 1.0.0-dev.7 the following error is been thrown: `Providers are not allowed to modify other providers during their initialization`

**To Reproduce**

```dart
final futureProvider =
    FutureProvider.autoDispose<void>((AutoDisposeProviderRef ref) async {
    UiProvider _uiProvider = ref.watch(uiProvider.notifier);

  _uiProvider.showGlobalLoader(); --> This modifies state
  await asyncTask();
});
```

**Expected behavior**
Before triggering an async task I would like update the state of another provider.

**Comment by rrousselGit** [comment]
As per the error message, this is expected.

You shouldn't modify providers like that, and should update your code to use a different solution.
