### ISSUE TITLE
ref.listen gives error on family StateProvider

### ISSUE THREAD

**Issue by LucaCras** [rrousselGit/river_pod#750]
**Describe the bug**
Using ref.listen gives an error when trying to listen to a state (family) provider:

The argument type 'StateProvider<double>' can't be assigned to the parameter type 'ProviderListenable<double>'.

**To Reproduce**
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.0-dev.7

`var someNumberProvider = StateProvider.family<double, String>((ref, id) => 1.0);`
`ref.listen<double>(someNumberProvider(id), (double value) => print(value));`

**Expected behavior**
No error.

**Comment by rrousselGit** [comment]
The correct syntax is:

```dart
ref.listen<StateController<double>>(...)
```

**Comment by rrousselGit** [comment]
👋 
I'll close this since this was answered. Feel free to create a new issue if you still have the problem 😄
