### ISSUE TITLE
OverrideWith〜 is not working with StateNotifierProvider 

### ISSUE THREAD

**Issue by Umigishi-Aoi** [rrousselGit/river_pod#755]
flutter_riverpod 1.0.0-dev.7

OverrideWithProvider & OverrideWithValue  is not working with StateNotifierProvider.

Here is the sample code of this issue. 

```Dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final counterProvider = StateNotifierProvider<MyStateNotifier, Counter>(
    (ref) => MyStateNotifier(Counter(0, 0)));

void main() {
  WidgetsFlutterBinding.ensureInitialized();

  MyStateNotifier myStateNotifier = MyStateNotifier(Counter(0, 0));
  myStateNotifier.increment();

  runApp(ProviderScope(overrides: [
    counterProvider.overrideWithProvider(StateNotifierProvider((ref)=>myStateNotifier)),
    // counterProvider.overrideWithValue(myStateNotifier),
  ], child: const MyApp()));
}

class MyApp extends ConsumerWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return MaterialApp(
      home: Scaffold(
        body: SafeArea(
          child: Center(
            child: Column(
              mainAxisSize: MainAxisSize.max,
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Text(
                    "counterFirst is ${ref.watch(counterProvider).counterFirst}"),
                Text(
                    "counterSecond is ${ref.watch(counterProvider).counterSecond}"),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

class MyStateNotifier extends StateNotifier<Counter> {
  Counter counter;

  MyStateNotifier(this.counter) : super(counter);

  void increment() {
    counter = Counter(counter.counterFirst + 1, counter.counterSecond + 1);
  }
}

class Counter {
  int counterFirst;
  int counterSecond;

  Counter(this.counterFirst, this.counterSecond);
}
```
If override was working, this result will show "counterFirst is 1 ,counterSeconde is 1 ".
But this result is "counterFirst is 0 ,counterSeconde is 0 ". 
So, overrideWithProvider is not worked.
This is same by using overrideWithValue.

I wanted initialize StateNotifierProvider with StateNotifier's method before runApp.
But I couldn't. 
So, I write this issue.

It's lucky that I found this solution.

Take out the StateNotifier's State, and override with StateNotifier initialized with it.

Here is the solution.

```Dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final counterProvider = StateNotifierProvider<MyStateNotifier, Counter>(
    (ref) => MyStateNotifier(Counter(0, 0)));

void main() {
  WidgetsFlutterBinding.ensureInitialized();

  MyStateNotifier myStateNotifier = MyStateNotifier(Counter(0, 0));
  myStateNotifier.increment();

  Counter counter = myStateNotifier.counter;      //*****NEW*****

  runApp(ProviderScope(overrides: [
    counterProvider.overrideWithProvider(StateNotifierProvider((ref)=>MyStateNotifier(counter))), //*****Modify*****

  ], child: const MyApp()));
}

//*****same as above*****
//...
```

This result shows that StateNotifierProvider can't override directly with initialized StateNotifier .

Is this expected?

**Comment by ebelevics** [comment]
Well I'm trying right now solve issue with insert value from outside. At first I tried using family modifier, but it's so redundant that you have to reference every read or watch method with exact parameter (in my case id). It gets even more complicated when you have multiple related parameters which is shared across multiple nested screens, for example: task/$id/something/$id/something-else/$id. So in order to get task id from taskProvider in deepest page I have to pass this id across the pages or else somethingElseProvider won't be this exact task Id related, but a new one.

Then I found that you can achieve this with ProviderScope by overriding default value, for example ` final taskIdProvider = Provider.autoDispose<int?>((_) => null);`. But then I found post that you have to also override all dependent providers or used provider won't be overridden in other providers. 

Also I get errors: `The following StateError was thrown building UncontrolledProviderScope(dirty):
Bad state: Tried to read a provider from a ProviderContainer that was already disposed
`

**Comment by TimWhiting** [comment]
This is a known issue that dependent providers need to be overridden. @rrousselGit is considering a few possibilities of how to make that easier, but for now you will just need to handle it. The reading a ProviderContainer that was already disposed was recently fixed on the master branch I think. I don't think the fix has been published, but you should be able to add riverpod as a git dependency until then.

**Comment by ebelevics** [comment]
Ok, thanks for quick reply

**Comment by TimWhiting** [comment]
@rrousselGit 
I feel like families have a common use case of creating another provider for the parameter and then overriding it -- effectively creating a scoped provider for a subbranch of the widget tree when multiple subtrees are alive at the same time and require a different instance of the same provider. Could that pattern be made easier?

```dart
final myFamilyProvider = Provider.family.scoped<String, Something>((ref, id) => Something(id));

ProviderContainer(
  overrides: [ 
    // Automatically overrides myFamilyProvider with itself
    myFamilyProvider.paramProvider.overrideWith('something'),
  ],
);
// Desugars to ref.watch(myFamilyProvider(ref.watch(myFamilyProvider.paramProvider)));
ref.watch(myFamilyProvider.scopedProvider) 
```

**Comment by ebelevics** [comment]
@TimWhiting 

May I ask how you add git dependency to pubspec.yaml
Below for example didn't work
 flutter_riverpod:
    git:
      url: git://github.com/rrousselGit/river_pod.git

**Comment by TimWhiting** [comment]
```yaml
flutter_riverpod:
  git:
    url: git://github.com/rrousselGit/river_pod.git
    path: packages/flutter_riverpod
riverpod:
  git:
    url: git://github.com/rrousselGit/river_pod.git
    path: packages/riverpod
```

**Comment by ebelevics** [comment]
After digging hard and trying out lot of solutions, I found and created one that I was looking for a long time. What it does, it exposes current active provider and I am able to call function to change its state with needed values at any time. I tried then depend other providers to taskProvider and it seems that taskProvider now does preserve it's updated state.

The solution is super simple, but it does the job, tho it needs more testing.

Below is Widget code to modify your state with specific values. 
```
class MyScopeProvider extends ConsumerStatefulWidget {
  final Function(WidgetRef) call;
  final Widget child;
  MyScopeProvider({required this.call, required this.child, Key? key})
      : super(key: key);

  @override
  _MyScopeProviderState createState() => _MyScopeProviderState();
}

class _MyScopeProviderState extends ConsumerState<MyScopeProvider> {
  @override
  void initState() {
    Future.delayed(Duration.zero, () async => widget.call(ref));
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return widget.child;
  }
}
```

And here is real life scenario where I want to call API function to get task specific information.
```
  if (settings.name == TaskScreen.routeName) {
    final taskId = settings.arguments as int;

    return MyScopeProvider(
      call: (ref) => ref.read(taskProvider.notifier).getTask(taskId),
      child: TaskViewScreen(),
    );
  }
```

**Comment by rrousselGit** [comment]
As Tim mentioned, this is indeed "expected".
There is no way to change this behaviour as is, but I will try to make this an error.
