### ISSUE TITLE
onChange on ProviderListener is never called when state changes to quickly

### ISSUE THREAD

**Issue by 2shrestha22** [rrousselGit/river_pod#756]
**Describe the bug**
As `ProviderLlistener` describes `onChange` is only called at most per frame it should be called after last state change. But `onChange` is never called when I don't have `Futures` in my provider. I am trying to check the authentication state and push new page according to the `AuthState`. So my initial state will be `Unknown`. `SharedPreference` is already initialized so it is no `Future` anymore so checking for `BearerToken` and state change will be quickly and finally no `onChange` is called. So I am always stucked at `SplashScreen`. It took me hours to figure it out and then manually added `Future.delayed(const Duration(seonds:1))` to make `onChange` to work.

**To Reproduce**
Here is my `SessionProvider`
```dart

final sessionProvider = StateNotifierProvider<SessionProvider, AuthState>(
    (ref) => SessionProvider(const AuthState.unknown()));

class SessionProvider extends StateNotifier<AuthState> {
  SessionProvider(AuthState state) : super(state) {
    checkAuthState();
  }

  Future<void> checkAuthState() async {
    // Here without this Future onChange will not work
    await Future.delayed(const Duration(seconds: 1));
    final String? res =
        SharedPrefHelper.instance.get(Config.userSessionKey) as String?;

    if (res == null) {
      state = const AuthState.unauthenticated();
    } else {
      final userSession =
          UserSession.fromJson(jsonDecode(res) as Map<String, dynamic>);
      if (userSession.expiresAt.difference(DateTime.now()) >
          const Duration(days: 1)) {
        // token has greater than one day to expire
        // token is not still expired so we can login
        state = AuthState.authenticated(userSession);
      } else {
        // token expiry date is less than a day so it is safe to relogin
        state = const AuthState.unauthenticated();
      }
    }
  }
}
```
Here is my `SplashPage`
```dart

class SplashPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ProviderListener<AuthState>(
      onChange: (context, authState) {
        logger.d(authState);
        authState.when(
          unknown: () {
            logger.d('AuthStateUnknown');
            // do nothing
          },
          authenticated: (userSession) {
            logger.d('AuthStateAuthenticated');

            // TODO replace page regarding user type
            switch (userSession.userType) {
              case UserType.delivery:
                // TODO: replace driver page
                context.router.replace(const DriverHomePageRoute());
                break;
              // TODO add other push condition as user type
            }
          },
          unauthenticated: () {
            logger.d('UnAuthStateAuthenticated');

            // TODO replace with login page
            context.router.replace(const LoginByPhoneRoute());
          },
        );
      },
      provider: sessionProvider,
      child: Scaffold(),
    );
  }
}
```
Here is how I have initialized `SharedPreference` so I don't need to await for the Future for example reading initial state from sharedPreference in StateNotifer.
```dart
class SharedPrefHelper {
  SharedPrefHelper._();

  static SharedPreferences? _sharedPreferences;

  static SharedPreferences get instance {
    if (_sharedPreferences == null) {
      throw Exception(
          'SharedPrefHelper is not initialized. Be sure to initialize it with SharedPrefHelper.init()');
    } else {
      return _sharedPreferences!;
    }
  }

  static Future<void> init() async {
    _sharedPreferences = await SharedPreferences.getInstance();
  }
}
```
**Expected behavior**
`onChange` should be called for the final state change.

**Comment by rrousselGit** [comment]
Hello!

Could you update your code to not depend on any external code and be as simple as possible? I cannot execute this, which makes it harder to understand the issue.

**Comment by 2shrestha22** [comment]
Ok, I am reproducing this issue without any package and will share with you.

**Comment by 2shrestha22** [comment]
Hi @rrousselGit here is minimal app to reproduce this issue.
https://github.com/2shrestha22/riverpod_issue_756

**Comment by TimWhiting** [comment]
This is because the initial state of the provider is what it is once it finishes creating the provider. Riverpod doesn't listen to the MyProvider until the constructor has finished and since you are running checkAuthState synchronously in the constructor, and there is no await, then the checkAuthState method runs synchronously. Therefore there is no change in state. 

Two ways to make this work
1. either always run checkAuthState asynchronously
```dart
MyProvider(state) : super(state) {
    scheduleMicrotask(() => checkAuthState());
}
```
or 2. use a declarative navigation solution, with redirection or something based off of the actual state, not changes in state. (i.e. using the state to determine which page to build).

Obviously solution 1 is simpler, but using a declarative navigation solution in general will make sure that you are always in sync with your data and you won't run into these kinds of logical errors.

**Comment by 2shrestha22** [comment]
@TimWhiting thank you for the answer. I was unaware about these and never faced this since generally I had used asynchronous function. Solution 1 fits for me. Is there any other way in provider to invoke a function just after finished creating it, if I don't know?

**Comment by TimWhiting** [comment]
```dart
final myProvider = StateNotifierProvider<MyProvider, AuthState>((ref) {
      final provider = MyProvider(AuthState.unknown);
      Future.delayed(Duration(milliseconds: 10), () => provider.checkAuthState());
      return provider;
  });
```
This is another way you could do it.

In general it depends on your use case. You might want to have the call to `ref.checkAuthState()` in your `SplashPage` `initState` / `didChangeDependencies`, or as part of a pull-to-refresh.

@rrousselGit Maybe a `ref.postCreate((provider) => provider.checkAuthState());` function could be added, seeing as this is a common pattern that I've seen several questions about?

**Comment by rrousselGit** [comment]
"postCreate" wouldn't work as you'd expect it to, since either it wouldn't be able to modify providers or it would execute before the listener is registered, changing nothing.

I'd also suggest using declarative navigation if possible.

**Comment by 2shrestha22** [comment]
thank you both of you.

**Comment by TimWhiting** [comment]
@2shrestha22 / @rrousselGit  Will you close the issue now seeing as this is answered?
