### ISSUE TITLE
Access computed in initState

### ISSUE THREAD

**Issue by essarn** [rrousselGit/river_pod#76]
Is it possible to access an `Computed` provider in `initState`?

**Comment by rrousselGit** [comment]
No

Consider using 0.6.0-dev

**Comment by essarn** [comment]
Found a workaround for my problem but how would it work in the dev build?

**Comment by smiLLe** [comment]
@essarn There is no `Computed` in 0.6.0-dev anymore. Instead you can just use `Provider` and i think you want to `context.read($provider)` in `initState`

**Comment by rrousselGit** [comment]
Indeed 👍

Consider posting your workaround here for others. 
But overall, this issue shouldn't be an issue anymore as part of 0.6.0-dev, so I'll close this

**Comment by essarn** [comment]
Hello again, just one question regarding the original question.

Can you give an example of an computed equivalent with using a provider?

**Comment by rrousselGit** [comment]
You can see the to-do example, with the "filtered Todos" provider

**Comment by essarn** [comment]
> You can see the to-do example, with the "filtered Todos" provider

Thanks!
