### ISSUE TITLE
how to watch provider with hooks_riverpod package?

### ISSUE THREAD

**Issue by BigGitWorld** [rrousselGit/river_pod#763]
Hi.
I'm using the below versions:
```
flutter_hooks: ^0.17.0
hooks_riverpod: ^0.14.0+4
```

I know with the ``flutter_riverpod`` package:
- I can extends my class from ConsumerWidget to have a ``ScopedReader watch`` argument in the ``build(context, watch)`` mehod.
- I can wrap my widget by the ``Consumer`` widget to have ``watch`` object in its ``builder``.

Questions:
why there is not any ``HookConsumerWidget`` class at the ``hooks_riverpod`` package?
So how can I watch a provider with the hooks_riverpod?
Do I have to use ``Consumer`` widget again?

I think documentation is not updated.

**Comment by smiLLe** [comment]
There is a `HookConsumerWidget`
https://github.com/rrousselGit/river_pod/blob/master/packages/hooks_riverpod/lib/src/consumer.dart#L10

**Comment by jeanbatm** [comment]
You can use useProvider instead of watch:
https://pub.dev/documentation/hooks_riverpod/latest/hooks_riverpod/useProvider.html

**Comment by rrousselGit** [comment]
The documentation is using the version 1.0.0-dev.7, which changed the syntax by removing `useProvider` in favour of `HookConsumerWidget`.

You used the version 0.14.x, hence the problem. So this is expected :)
