### ISSUE TITLE
ConsumerStatefulWidget removed?

### ISSUE THREAD

**Issue by daniel-hopkins** [rrousselGit/river_pod#764]
**Additional context**
[ConsumerStatefulWidget](https://riverpod.dev/docs/concepts/reading#extending-consumerstatefulwidgetconsumerstate-instead-of-statefulwidgetstate) code samples here don't seem to work. 
Has it been deprecated? I didn't see anything in the changelog about it. 
What would be the preferred replacement scenario?

**Comment by rrousselGit** [comment]
What version are you using?

`ConsumerStatefulWidget` is part of the dev release 1.0.0-dev.7. But it isn't part of the version 0.14.x

**Comment by daniel-hopkins** [comment]
> What version are you using?

`flutter_riverpod: ^0.14.0+3`

Thanks for the quick reply.
I'll try out the dev version and see how it goes.
