### ISSUE TITLE
Feature request: Prevent Lists retrieved through Riverpod from being mutable 

### ISSUE THREAD

**Issue by ken-ng-esotec** [rrousselGit/river_pod#765]
Hello, first off want to thank you for all the brilliant packages you've brought out.

I came across a very deadly bug today where I changed a `List` without intending to. Usually I am able to spot these errors if they occur inside a StateNotifier but I did not expect it to be coming from inside a Flutter Widget (see below). I took a long time digging through my code to find out the source of the error and finally arrived at that line.

Is there any way we can prevent the likelihood of these bugs through improvements in the library, or can you think of anything else I could do?

``` 
   final itemsSubjected =
    ref.watch($interactionsState.select((value) => value.itemsSubjected));
   
   final interactionsWithoutMatches = useState([]);

   // Version 1: interactionsWithoutMatches.value get's the correct value BUT unintended mutation of the itemsSubjected state (this negatively impacted other pages and it took me a long time to find out why in our huge repo)
    useEffect(() {
      if (itemsSubjected.isNotEmpty) {
        interactionsWithoutMatches.value = itemsSubjected
          ..removeWhere((e) => matchesNotifier.getHasMatched(e.performer));
      }
    }, [itemsSubjected]);

   // Version 2: interactionsWithoutMatches.value get's the correct value AND no dangerous side-effect
    useEffect(() {
      if (itemsSubjected.isNotEmpty) {
        interactionsWithoutMatches.value = [...itemsSubjected]
          ..removeWhere((element) => matchesNotifier.getHasMatched(element.performer));
      }
    }, [itemsSubjected]);
```

I think if the library could somehow prevent the List from being directly mutable - enforce making a clone - then that would work wonders for bug prevention when handling Lists in our state. I can't think of any reasons why we would want to mutate the original list when we can make copies.

**Comment by TimWhiting** [comment]
I personally use an immutable list implementation such as IList from fast_immutable_collections package. But you could also make sure that you always wrap your list in List.unmodifiable. https://api.flutter.dev/flutter/dart-core/List/List.unmodifiable.html

**Comment by rrousselGit** [comment]
There's sadly nothing Riverpod can do, since Riverpod doesn't know what's the content of your objects.

At best, Riverpod could have providers/select wrap List instances inside an `UnmodifiableListView`. But that could be undesired, considering it would prevent legitimate modifications.

**Comment by ken-ng-esotec** [comment]
My debugging solution is to try to use regex searches more e.g. `itemsSubjected\s*[.]{1,2}` which would help filter potential scenarios that could mutate the state. Thanks for the pointers

**Comment by rrousselGit** [comment]
I will close this issue since there's nothing Riverpod can realistically do. Feel free to open a new issue if you have any concrete solution in mind

**Comment by ken-ng-esotec** [comment]
That's fine :) however, I would like to suggest us to improve the documentation to warn users when operating with lists. I will submit some suggestions. Thoughts on this approach?

**Comment by TimWhiting** [comment]
@ken-ng-esotec I'm sure a PR with documentation updates for this would be accepted.
