### ISSUE TITLE
Will the pull-to-refresh / retry-on-error documentation be completed?

### ISSUE THREAD

**Issue by Reprevise** [rrousselGit/river_pod#768]
The documentation is empty (https://riverpod.dev/docs/cookbooks/refresh/) and it would be nice to see it completed especially since that's what I'm trying to implement right now.

**Comment by rrousselGit** [comment]
In due time, yes.

Although TD;DR, this is about `ref.refresh(provider)`, which does most of the job.



Closing in favour of https://github.com/rrousselGit/river_pod/issues/85
