### ISSUE TITLE
select on specific field of an Object in form of AsyncValue<Object>

### ISSUE THREAD

**Issue by BigGitWorld** [rrousselGit/river_pod#769]
Hi.
I have a ``StreamProvider`` to listen changes of a specific row in my (moor) database table:
```
final dbStreamProvider = StreamProvider.family<Object, String>((ref, columnValue) {
  return ref.watch(dbProvider).ObjectDao.watchByColumnX(columnValue);
});
```
So I have a AsyncValue<Objec> in my widget :
```
final dbStreamProvider = ref.watch(dbStreamProvider(columnValue));
``` 
Now I want to only update UI if a specific column of my object is changed, So I want to use ``select`` : 
```
final dbStreamProvider = ref.watch(dbStreamProvider(columnValue).select((value) => ???));
```
How do I have to specify a field of my object instead of ```???``` in the above code?

**Comment by rrousselGit** [comment]
You can use `whenData`

```dart
final dbStreamProvider = ref.watch(dbStreamProvider(columnValue).select((value) => value.whenData((data) => data.property);
```

**Comment by BigGitWorld** [comment]
@rrousselGit  thank you.
Can I listen two property by one provider?
for example, I have two boolean property that I want to listen their change by the below provider:
```
final dbStreamProvider = ref.watch(dbStreamProvider(columnValue).select((value) => value.whenData((data) => (data.property1 || data.property2));
```
Is the above true?

**Comment by rrousselGit** [comment]
No, use select twice

**Comment by BigGitWorld** [comment]
thanks
