### ISSUE TITLE
StateProvider is missing AutoDisposeFamily

### ISSUE THREAD

**Issue by smiLLe** [rrousselGit/river_pod#77]
**Describe the bug**
`StateProvider.family.autoDispose` does not exist

Version: 0.6.0-dev+2

**Comment by rrousselGit** [comment]
Intersting. There is `.autoDispose.family`

**Comment by smiLLe** [comment]
Ohhhhh, i was always using `family.autoDispose` on other providers, haha.

**Comment by rrousselGit** [comment]
I'll add it anyway for consistency
