### ISSUE TITLE
Add ref.onCancel / ref.onResume for when all listeners are removed / one is added

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/river_pod#779]
Similar to `ref.onDispose`, this `ref.onCancel` would allow performing actions when all listeners are removed, and `ref.onResume` would trigger when a listener is added after all were previously removed.

This can be particularly helpful when combined with `ref.maintainState` to perform advanced operations, such as keeping a provider alive for X seconds after it is no-longer listened.

**Comment by tbm98** [comment]
Hi. I think sometimes I want a `onCancel` on 
a keepAlive provider (not auto dispose) to know all listeners are removed or not. What do you think?

**Comment by rrousselGit** [comment]
This won't be specific to autoDispose

**Comment by rrousselGit** [comment]
I don't see a clear use-case for `onResume`, so I'm probably not going to add it for now.

If you need it, please make a new issue explaining the use-case
