### ISSUE TITLE
contex.read has dissapear

### ISSUE THREAD

**Issue by arcas0803** [rrousselGit/river_pod#782]
**Describe the bug**
When I tried to access context.read, it does not lead me to do it.

**To Reproduce**

Flutter_riverpod: DEV_7
imports are ok.
The only way to access is by de ref in a consumer widget.

**Expected behavior**
It should appear.
I don't know if is a change from the previous version. I have read the changelog and does not appear.

**Comment by rrousselGit** [comment]
context.read has been removed.

Instead use ConsumerWidget

**Comment by arcas0803** [comment]
OK
