### ISSUE TITLE
Add an asynchronous StateNotifier

### ISSUE THREAD

**Issue by ryicoh** [rrousselGit/river_pod#784]
**Is your feature request related to a problem? Please describe.**
It's related to this Issue. #57, #329

https://github.com/rrousselGit/river_pod/issues/57#issuecomment-663048181
```dart
class Whatever extends StateNotifier<AsyncValue<int>> {
  Whatever(): super(const AsyncValue.loading()) {
    _fetch();
  }

  Future<void> _fetch() async {
    state = const AsyncValue.loading();
    state = await AsyncValue.guard(() => fetch());
  }
}
```
This solution is good. However, other providers do not allow synchronous calls.

```dart
// Good within the widget.
Widget build(context, ref) {
  final w = ref.watch(whatever);
  ...
}

// Other providers can't get initialized objects synchronously.
final other = FutureProvider((ref) async {
  final w = await ref.watch(whatever.future);
                                     _______
  ...
});
```

**Describe the solution you'd like**

I made the draft here.
https://github.com/ryicoh/future_state_notifier/blob/85b65cc7c2f96887dcb1442df5945831464623a0/lib/future_state_notifier.dart#L6
```dart
abstract class FutureStateNotifier<T> extends StateNotifier<AsyncValue<T>> {
  final lock = Lock();
  final once = SyncOnce();

  FutureStateNotifier() : super(const AsyncValue.loading());

  Future<void> initState();

  Future<void> initStateOnce() async {
    await once(initState);
  }

  Future<void> setState(Future<T> Function() future) async {
    lock.synchronized(() async {
      if (state != const AsyncValue.loading()) {
        state = const AsyncValue.loading();
      }
      state = await AsyncValue.guard(future);
    });
  }
}
```

Example of `Counter`
https://github.com/ryicoh/future_state_notifier/blob/85b65cc7c2f96887dcb1442df5945831464623a0/test/future_state_notifier_test.dart#L33

If this provider is to be used within another provider:
https://github.com/ryicoh/future_state_notifier/blob/85b65cc7c2f96887dcb1442df5945831464623a0/lib/future_state_notifier.dart#L33

If this provider is to be used within a flutter widget:
https://github.com/ryicoh/future_state_notifier/blob/85b65cc7c2f96887dcb1442df5945831464623a0/lib/future_state_notifier.dart#L38

I know that the combination of "StateNotifier" and "FutureNotifier" does not result in "Async.loading()" when the state is updated.
https://github.com/ryicoh/future_state_notifier/blob/85b65cc7c2f96887dcb1442df5945831464623a0/test/future_state_notifier_test.dart#L87

**Comment by rrousselGit** [comment]
Closing since this is supported directly by `StateNotifierProvider` now thanks to extension methods.

So creating a `StateNotifier<AsyncValue<...>>` will give access to `.future`/`.stream`

**Comment by maks** [comment]
@rrousselGit I think maybe I'm missing something here, I see how to use AsyncValue to wrap state to a StateNotifier, but what if I have a `StateNotifierProvider` that depends on another Provider that is a `FutureProvider`, eg.
```
final authServiceProvider = FutureProvider<AuthService>((ref) async {

...

final settingsViewModelProvider = StateNotifierProvider<SettingsViewModel, SettingsState>((ref) {
  final auth = await ref.watch(authServiceProvider);
  return SettingsViewModel(authService: auth, state: const SettingsState());
});
```
How can I do the above as I'd need to make the  `settingsViewModelProvider` in order to be able to make the closure async in order to await on my watching the `authServiceProvider`?

**Comment by maks** [comment]
Actually I've ended up just doing this:
```
final settingsViewModelProvider = StateNotifierProvider<SettingsViewModel, SettingsState?>((ref) {
  final auth = ref.watch(authServiceProvider);
  return SettingsViewModel(authService: auth.value, state: const SettingsState(wifiOnly: true));
});
```
and making my `SettingsViewModel` accept a nullable `authService` but I'm not sure if I'm doing something not quite right here.

**Comment by maks** [comment]
btw I have looked at #57 and #127 but I don't think they cover quite the same use case, as to me they seem to be about the `StateNotifier`s State being a AsyncValue whereas here, I have another provider as dependency and it happens to be a `FutureProvider`.

**Comment by om-ha** [comment]
> ```dart
> final settingsViewModelProvider = StateNotifierProvider<SettingsViewModel, SettingsState?>((ref) {
>   final auth = ref.watch(authServiceProvider);
>   return SettingsViewModel(authService: auth.value, state: const SettingsState(wifiOnly: true));
> });
> ```

I agree with @maks here, and my use case is exactly like the above

**Comment by om-ha** [comment]
> Closing since this is supported directly by `StateNotifierProvider` now thanks to extension methods.
> 
> So creating a `StateNotifier<AsyncValue<...>>` will give access to `.future`/`.stream`

@rrousselGit can you please point us where those extension methods are located?

I tried to look in the repo for `on StateNotifierProvider` but to no avail.

I need something like `FutureProvider` + `StateNotifierProvider` -- more like a `FutureStateNotifierProvider`.

**Comment by om-ha** [comment]
Actually, I just found the answer hidden in a changelog:

https://github.com/rrousselGit/riverpod/blob/master/packages/riverpod/CHANGELOG.md#general-changes

It is now possible to "await" all providers that emit an AsyncValue (previously limited to FutureProvider/StreamProvider). This includes cases where a StateNotifierProvider exposes an AsyncValue:

```dart
class MyAsyncStateNotifier extends StateNotifier<AsyncValue<MyState>> {
  MyAsyncStateNotifier(): super(AsyncValue.loading()) {
    // TODO fetch some data and update the state when it is obtained
  }
}

final myAsyncStateNotifierProvider = StateNotifierProvider<MyAsyncStateNotifier, AsyncValue<MyState>>((ref) {
  return MyAsyncStateNotifier();
});

final someFutureProvider = FutureProvider((ref) async {
  MyState myState = await ref.watch(myAsyncStateNotifierProvider.future);
});
```

**Comment by gmkado** [comment]
Did this feature go away?  I'm on `hooks_riverpod: ^2.1.1` and get this error:
> The getter 'future' isn't defined for the type 'StateNotifierProvider<MyAsyncStateNotifier, AsyncValue<MyState>>'.

**Comment by rrousselGit** [comment]
Yes, it never reached the stable release

Use AsyncNotifier instead
