### ISSUE TITLE
UI not updating on 1.0.0-dev.9

### ISSUE THREAD

**Issue by vigneshksaithal** [rrousselGit/river_pod#797]
**Describe the bug**
UI not updating when the state is changed.

**To Reproduce**

Provider:

`void _updateTotalAmount(double amount) {
    state.totalAmount += amount;
  }`

Consumer: 

`Consumer(
builder: (context, ref, child) {
    final totalAmount =
                              ref.watch(transactionProvider).totalAmount;
                          return Text(
                            '₹ $totalAmount',
                            style: const TextStyle(
                              fontSize: 26,
                              fontWeight: FontWeight.w500,
                            ),
                          );
                        },
                      ),`

**Comment by strigePC** [comment]
You may use `copy_with_extension_gen` or `freezed` library that will generate `.copyWith()` method for you. If you don't want to use external libraries, just add the method yourself. You may look at Flutter's theme `copyWith()` methods [here](https://api.flutter.dev/flutter/widgets/IconThemeData/copyWith.html) for reference

**Comment by vigneshksaithal** [comment]
Thanks @strigePC  & @rrousselGit . Now I got to know how to use copyWith.  

 **For anyone beginners like me who want to know how to update state in riverpod please refer this video :** https://www.youtube.com/watch?v=vD-I1ARIMnk
