### ISSUE TITLE
Read original `Provider` from `Override`

### ISSUE THREAD

**Issue by jimmy-robert** [rrousselGit/river_pod#8]
**Is your feature request related to a problem? Please describe.**
Not sure if it should be a bug or a feature request, but I can't read the original `Provider` from `Override`.

For example:

```dart
final nameProvider = Provider<String>((ref) => 'John Doe');

final emphasisProvider = Provider<String>((ref) {
  final name = ref.read(nameProvider).value;
  return '$name!';
});

// ...

ProviderScope(
  child: Column(
    children: <Widget>[
      // Displays `John Doe`
      Consumer((context, read) => Text(read(nameProvider))),
      // Displays `John Doe!`
      Consumer((context, read) => Text(read(emphasisProvider))),
      ProviderScope(
        overrides: [
          nameProvider.overrideAs(emphasisProvider),
        ],
        // Displays `null!` instead of `John Doe!`
        child: Consumer((context, read) => Text(read(nameProvider))),
      ),
    ],
  ),
)

```
**Describe the solution you'd like**
Read original `Provider` value instead of returning null.

**Comment by rrousselGit** [comment]
Why are you overriding "name" as "emphasis"?

**Comment by jimmy-robert** [comment]
Why not? 🙂 It is just a simple example here, but there can be cases where I want to override a behavior to add some features but still calling the original provider (e.g: modify a real HTTP response, transform a value, ...).

I think I would use this for mocks but it can still be used for real use cases I guess.

**Comment by rrousselGit** [comment]
For sure. I'm just trying to understand the use-case as much as possible.
To make sure that there isn't a different solution that we could take

**Comment by rrousselGit** [comment]
Note that you could do it with two providers:

```dart
final provider = Provider((ref) => 'Foo');
final originalProvider = Provider((ref) => ref.read(provider).value);
```

So when you override `provider`, `originalProvider` is still not overriden

**Comment by tbm98** [comment]
I think use-case of  `overrideAs` is for testing and both of them should be unrelated to each other.

**Comment by rrousselGit** [comment]
Closing for now as I don't think this is truly needed since there are other solutions, and implementing that would decrease overall performances.
