### ISSUE TITLE
In `flutter_riverpod: ^0.6.0-dev+3` i can't use the computed?

### ISSUE THREAD

**Issue by rustiever** [rrousselGit/river_pod#80]
Im using flutter_riverpod: ^0.6.0-dev+3 in my project, and i can't find the computed method !

in flutter_riverpod: ^0.5.1 i can find the computed method but in dev i could not find even if i use flutter LSP throws me an error

why is that? please help me if i'm wrong!

**Comment by preetjdp** [comment]
Not a bug. It's been removed in 0.6.0
More in the changelog

https://github.com/rrousselGit/river_pod/blob/master/packages/flutter_riverpod/CHANGELOG.md

**Comment by rrousselGit** [comment]
In 0.6.0, all providers are computed

Before:

```dart
final bar = StateNotifierProvider(...);

final foo = Computed((watch) {
  final value = watch(bar.state);
});
```

after:


```dart
final bar = StateNotifierProvider(...);

final foo = Provider.autoDispose((ref) {
  final value = ref.watch(bar.state);
});
```

**Comment by rustiever** [comment]
Ohh sorry for misunderstanding, thnks for clarification 👍
