### ISSUE TITLE
ReordableListView - ProviderScope was rebuilt with a different ProviderScope ancestor

### ISSUE THREAD

**Issue by marinkobabic** [rrousselGit/river_pod#803]
**Describe the bug**
When the item in the ReordableListView uses ProviderScope and so also ScopedProvider, the the following code fails
```
      if (scope?.container != _debugParentOwner) {
        throw UnsupportedError(
          'ProviderScope was rebuilt with a different ProviderScope ancestor',
        );
      }
```

**To Reproduce**
The issue occurres only if the application uses multiple ProviderScopes which is the normal case when ScopedProvider is in place. I have one ProviderScope on the Page level and one on the application level. When build is executed then the ProviderScope of the Page is used. As soon as user wants to move the item to a different position, then the ProviderScope on the page level seems not anymore to be available because of the changed widget tree. So the ProviderScope of the application is taken which leads to a mismatch in the code above.

If works perfect as soon as I remove the ProviderScope on the page level. 

**Expected behavior**
Would be great if you keep the default behavior, but you should provide an option to suppress the error above. It's clear that this can lead to many side effects, but without the flag the whole solution does not work. I haven't found a way to prevent ReordableListView to rebuild the widget when moving around. New flag would give the developer the responsibility and more control about the behavior.

**Comment by rrousselGit** [comment]
Moving a `ProviderScope` is not supported. This isn't an error that can be ignored

You shouldn't hit this issue if you do not use `GlobalKey`
