### ISSUE TITLE
Need to set the minimum version of Dart =>2.14.0

### ISSUE THREAD

**Issue by nikitadol** [rrousselGit/river_pod#806]
`Object.hash` was added in `2.14.0`, so now on version `2.13.4` `pub get` works fine, but the code is not building

**Comment by davidmartos96** [comment]
@nikitadol If you are already using Flutter 2.5.0+, could you share the error you are getting?

**Comment by davidmartos96** [comment]
@nikitadol Oh I see what you mean now. Yes, the pubspec should specify Dart 2.14
