### ISSUE TITLE
UI is not updating [ hooks_riverpod: ^0.14.0+3 ]

### ISSUE THREAD

**Issue by Shiba-Kar** [rrousselGit/river_pod#807]
**Describe the bug**
The state changes but the UI does not update once I do a hot reload the sate reflects properly

**To Reproduce**

**Consuming Widget**
![code-snapshot](https://user-images.githubusercontent.com/24454722/136768237-847f2670-71bf-4d9e-a68e-3e7649f3a46a.png)

**StateNotifier**

![code-snapshot](https://user-images.githubusercontent.com/24454722/136768581-5c0dc89c-3ec3-4540-ab12-73aaa2ba863e.png)

```[√] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.22000.194], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] IntelliJ IDEA Community Edition (version 2021.2)
[√] VS Code, 64-bit edition (version 1.61.0)
[√] Connected device (3 available)

environment: sdk: ">=2.7.0 <3.0.0"
```

**Comment by rrousselGit** [comment]
Don't do:

```dart
final followers = state;
followers.add(<item>)
state = followers;
```


Instead do:

```dart
state = [
  ...state,
  <item>
]
```
