### ISSUE TITLE
UI not updating after moving from hooks_riverpod 0.12.1 to 0.13.1

### ISSUE THREAD

**Issue by danielnordh** [rrousselGit/river_pod#808]
**A StateProvider that was updating UI in hooks_riverpod 0.12.1 no longer does so after updating to 0.13.1**

I can't see any breaking changes mentioned in the change log.
Not sure why this stopped working between these versions.

The provider is defined in one class:
```
final currentTransactionProvider = StateProvider<CurrentTransaction>((ref) {
  final _currentTransaction = CurrentTransaction();
  return _currentTransaction;
});
```

And used in a HookBuilder:
`final currentTransactionController = useProvider(currentTransactionProvider);`

A slider is used to update a value in the Provider (this works as expected):
```
onChanged: (value) {
   final transactionState = currentTransactionController.state;
   transactionState.amount = value?.toInt()?.toUSDCBigInt() ?? BigInt.zero;
   currentTransactionController.state =  transactionState;
},
```

It is then used to update the slider position:
`value: (currentTransactionController.state.amount / BigInt.from(1E6)).toDouble(),`

and display the value in a Text:
```
Text(currentTransactionController.state.amount.dollarString(),
   key: ValueKey<String>(currentTransactionController.state.amount.dollarString()),
),
```

**Expected behavior**
Updating the state of the Provider should trigger a rebuild of the HookBuilder and child widgets.

**Comment by rrousselGit** [comment]
You can look into Freezed, to generate a "copyWith" method

**Comment by danielnordh** [comment]
For anyone else that runs into this, here's what I changed to get it working.

Instead of the one Provider before, I used `StateNotifierProvider`, `StateNotifier` with an `updateAmount` method:
```
final currentTransactionProvider = StateNotifierProvider<CurrentTransactionNotifier>(
        (ref) => CurrentTransactionNotifier());

final currentTransactionAmountProvider = Provider<BigInt>(
    (ref) => ref.watch(currentTransactionProvider.state).amount);

class CurrentTransactionNotifier extends StateNotifier<CurrentTransaction> {
  CurrentTransactionNotifier() : super(CurrentTransaction(BigInt.zero));

  void updateAmount(BigInt newAmount) {
    state = CurrentTransaction(newAmount);
  }
}
```

I moved the UI code into a `ConsumerWidget`, and watch the `amount`:
```
class CustomSlider extends ConsumerWidget {
  @override
  Widget build(BuildContext context, ScopedReader watch) {
    final BigInt amount = watch(currentTransactionAmountProvider);
    return MyActualSliderWidgetGoesHere();
  }
}
```

In the Slider I can then use `amount` for reading, and update like this in the `onChanged`:
```
value: (amount / BigInt.from(1E6)).toDouble(),
onChanged: (value) {
   context.read(currentTransactionProvider).updateAmount(value?.toInt()?.toUSDCBigInt() ?? BigInt.zero);
},
```

I didn't want to use Freezed and have to go through a build for such a simple thing. In my case I only ever need to update the one value, so I simply create a new object with the new value rather than copy, other's might need a normal class copyWith method.

I had trouble using the copy/copyWith functions I found elsewhere, probably due to the way I was constructing my class with a fixed value. I changed this to needing an external value on creation and that made it work.
