### ISSUE TITLE
Unwanted State Rebuilds

### ISSUE THREAD

**Issue by preetjdp** [rrousselGit/river_pod#81]
**Describe the bug**
Riverpod Version -> 0.6.0-dev+3

**Context**
The task is to listen to two Providers namely `FirebaseAuthProvider` and a `PageControllerProvider`., use the data to determine: continue being in the IntroFlow or show the HomePage.

**Snippet for the Provider**:
https://github.com/preetjdp/YouOweMe/blob/5e51fb2f6132e637ad447273419f4360a27ad1d4/mobileApp/lib/ui/IntroFlow/providers.dart#L18-L45

**The Problem**
When the user sign's in, i.e., the `FirebaseUserProvider` returns a new value the widget where the data is being used gets rebuild., 

**The Snippet where the provider is used**:
https://github.com/preetjdp/YouOweMe/blob/5e51fb2f6132e637ad447273419f4360a27ad1d4/mobileApp/lib/ui/IntroFlow/introFlow.dart#L22-L45

**My Hypothesis**
I believe the provider gets reset since I see the loading widget on the screen.

**Example**
<img height="400px" src="https://user-images.githubusercontent.com/27439197/90276551-be1de880-de81-11ea-9654-d10e79372fc9.gif">

**Comment by rrousselGit** [comment]
That's expected.
You used ref.watch, and the vslue exposed by that provider changed

Chances are that you don't want ref.watch(firebaseUserProvider)  but instead ref.watch(firebaseUserProvider.stream)

**Comment by preetjdp** [comment]
I was not aware that StreamProviders were supposed to be listened in this manner.

When do I use 
`ref.watch(firebaseUserProvider.stream)`

and when do I use

`ref.watch(firebaseUserProvider)`

Could you clear out the distinction between them?

**Comment by preetjdp** [comment]
Also the same question for Hooks

Do I use `useProvider(authValidatorProvider)`

Or `useProvider(authValidatorProvider.stream)`

**Comment by rrousselGit** [comment]
It really depends on what you are trying to do

Listening to `streamProvider` synchronously returns the latest value emitted by the stream

Listening `streamProvidier.stream` obtains a broadcast stream

**Comment by rrousselGit** [comment]
Closing since this is working as expected
