### ISSUE TITLE
Update ref.watch(StateProvider) to return the state instead of StateController

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/river_pod#828]
@rrousselGit 
I wonder with this change would it be appropriate to also change StateProvider to have

ref.watch(stateProvider.notifier); returns the StateController, watches when the provider rebuilds
ref.watch(stateProvider.controller); returns the StateController, watches when the state changes
ref.watch(stateProvider); returns the State of the StateController watches when the state changes

This way users can listen to stateProvider and actually get the previous value of the state, rather than the StateController reference which remains the same. Or if StateController can keep the previous state it would accomplish the same purpose. I know you can just create a subclass of StateNotifier, but it seems like more work and refactoring (from a StateProvider), than it should be just to get the previous value.

_Originally posted by @TimWhiting in https://github.com/rrousselGit/river_pod/issues/827#issuecomment-945847107_

**Comment by artificerchris** [comment]
I'm in favor of this. Right now I'm stuck trying to figure out why a Widget I have doesn't change when I assign a new state to the StateController my provider returns. The value gets updated, but no rebuild happens, even though I'm listening to the StateProvider, not its notifier or anything like that.
