### ISSUE TITLE
Implement angular_riverpod

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/river_pod#83]
Since Riverpod does not depend on Flutter, we could use Riverpod in AngularDart

**Comment by rrousselGit** [comment]
Note: if you want this, make sure to :+1: the issue (and potentially make recommendations)

While cool, this is a low priority for me, as I have some doubts about whether people actually care or not.

Remember: all the time spent on this is time that I could spend on something else, such as:
- devtools
- documentation
- more examples

**Comment by venkatd** [comment]
Disclaimer: I'm probably biased since we don't use anguar_riverpod.

I think adding angular_riverpod to your priorities could slow down iteration of riverpod. It's one more thing to maintain while the api and docs are still stabilizing.

**Comment by rrousselGit** [comment]
Clearly, this isn't useful

So I'll close this.

If anyone wants to pick it up, feel free to contact me :smile:
