### ISSUE TITLE
testing family provider after overrideWithProvider was removed (> 1.0.0-dev.8)

### ISSUE THREAD

**Issue by ghost** [rrousselGit/river_pod#834]
**Describe what scenario you think is uncovered by the existing examples/articles**
It would be nice to explain how to test a family provider after overrideWithProvider disappeared (Riverpod version > 1.0.0-dev.8).

For instance, I have the following provider:
```
final channelProvider = Provider.autoDispose.family<IOWebSocketChannel, HttpParam>((ref, httpParam) {
    return IOWebSocketChannel.connect('ws://${httpParam.ip}:$port/v1/${httpParam.path}');
  });
```

The way I would test it before 1.0.0-dev.8, is to override it in a ProviderContainer that way:
```
class MockWebSocketOnDone extends Mock implements IOWebSocketChannel {
  MockWebSocketOnDone();

  Stream<dynamic> stream =
      Stream<int>.periodic(Duration(seconds: 1), (x) => x).take(0);
}
```

In a test:
```
final container = ProviderContainer(
  overrides: [
    channelProvider.overrideWithProvider(
      (HttpParam _httpParam) => Provider.autoDispose(
        (ref) => MockWebSocketOnDone(),
      ),
    ),
  ],
);
```

Since 1.0.0-dev.8, I can't find a way to do it, since overrideWithProvider is gone and overrideWithValue is not available as well (for family providers only).

**Describe why existing examples/articles do not cover this case**
I read the "testing" section of the official documentation (https://riverpod.dev/docs/cookbooks/testing) but no family provider is tested there.

**Comment by TimWhiting** [comment]
`channelProvider(arguments).overrideWithValue` should be available.

For now you can pin your dependency to a prior version. Remi is thinking about adding overrideWithProvider back for some cases for riverpod 1.0.0.
