### ISSUE TITLE
Is object instantiation with Reader reference preferred over constructor injection?

### ISSUE THREAD

**Issue by madvib** [rrousselGit/river_pod#84]
Using the `read` method inside of a provider body is discouraged according to the [docs](https://riverpod.dev/docs/concepts/combining_providers#can-i-read-a-provider-without-listening-to-it), but the reason for this is unclear to me.

Is there a discernible difference in behavior between the following snippets?  

```dart
final myServiceProvider = Provider((ref.read) => MyService(ref.read));


//initialization within constructor
MyService(Reader read)
: api=read(apiProvider);
```
```dart
final myServiceProvider = Provider(
    (ref) => MyService(api: ref.read(apiProvider)));
```

I don't have as much of an issue with passing the reader given that riverpod is compile safe, but constructor injection does have the advantage of making dependencies more explicit. Is this indeed an anti-pattern and if so why?

**Comment by rrousselGit** [comment]
There aren't many reasons.
I just found the code more readable when reading providers, but that's about it.

**Comment by madvib** [comment]
Thanks for getting back to me.  The docs do seem to suggest that this causes unwanted rebuilds.

It may cause less confusion to highlight passing a reference as the idiomatic way to go about instantiation rather than labeling all calls to read inside a provider as a bad practice.

**Comment by rrousselGit** [comment]
>  The docs do seem to suggest that this causes unwanted rebuilds.

What are you referring to? Because it doesn't

**Comment by madvib** [comment]
>**DON'T** call [read] inside the body of a provider

> If you want to avoid unwanted rebuilds of your object, see [My provider updates too often, what can I do?](#my-provider-updates-too-often-what-can-i-do)

That is at least how I interpret the above, sorry if I am missing something.

**Comment by rrousselGit** [comment]
Ah, this is referring to "if you used `read` instead of `watch` to filter rebuilds, don't do that and instead see [link]"

Is that a better wording?

**Comment by madvib** [comment]
OK I understand and yes that is much more clear.  Just a nit but I think that concept would be much more clear either in it's own info message box or perhaps above the code block in that section.  Happy to make a pr if that'd help

**Comment by rrousselGit** [comment]
Done :smile:
