### ISSUE TITLE
Add `provider.selectAsync` which returns a future for awaiting AsyncValue

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/river_pod#851]
While `await FutureProvider.future` is convenient, one issue is that currently there is no way to filter rebuilds of the future is recreated but the result didn't change.

To solve this, we could add a `selectAsync` which would allow selecting the result of a `Future`, allowing:

```dart
final provider = FutureProvider<Person>(...)

final another = FutureProvider((ref) async {
  Future<String> name = ref.watch(provider.selectAsync((Person p) => p.name));
}
```

Doing so would rebuild `another` only when the `provider` emits a `Person` with a different `name`.

**Comment by ebelevics** [comment]
It seems that this work
```
    ref.listen<AsyncValue<ChatState>>(chatProvider, (previous, next) {
      state = state..chatRoom = next.value!.chatRooms.firstWhere((c) => c.uuid == chatUUID);
    });
```
while this doesn't trigger
```
    ref.listen<Chat>(
        chatProvider.select((v) =>
            v.whenData((data) => data.chatRooms.firstWhere((c) => c.uuid == chatUUID)).value!),
        (previous, next) {
      state = state..chatRoom = next;
    });
```
is regarded to lack of provider.selectAsync.

P.S. also is there a way to listen to dependency provider without reinstantiating StateNotifier in chatRoomProvider declaration with ref.watch(chatProvider)? I wanted to take chatProvider live data to rebuild state of ChatRoomNotifier accordingly. But as I put ref.watch(chatProvider) in chatRoomProvider's declaration, returned ChatRoomNotifier is always reinstantiated with state change, which caused a lot of weird behaviors, mostly isMounted and ChatRoomNotifier streamControllers.add exceptions. The above first example did the job, but is there a cleaned or appropriate way to do this?
For example if we could pass into StateNotifier ref.listener(chatUuidProvider) and observe to changes inside the class as LiveData, that would preserve StateNotifier instance.
