### ISSUE TITLE
404 links in documentation

### ISSUE THREAD

**Issue by esDotDev** [rrousselGit/river_pod#855]
On the page: https://riverpod.dev/docs/concepts/reading https://pub.dev/documentation/flutter_riverpod/latest/flutter_riverpod/ConsumerState-class.html and https://pub.dev/documentation/flutter_riverpod/latest/flutter_riverpod/ConsumerStatefulWidget-class.html are resolving to 404 errors

**Comment by rrousselGit** [comment]
With the 1.0.0 release, that shouldn't be an issue anymore. Thanks for the report!
