### ISSUE TITLE
should use only one StateNotifierProvider or multiple providers, and each provider should keep some of the state.

### ISSUE THREAD

**Issue by tbm98** [rrousselGit/river_pod#86]
Should I use only one StateNotifierProvider for per screen? Or is it a split state for multiple providers?

**Comment by rrousselGit** [comment]
You can use as many providers as you want. I don't really like the "one provider per screen" idea, but this isn't a strong requirement.

I don't think the documentation can give you an answer to this question, since this is mostly your decision to make

**Comment by tbm98** [comment]
Yep. Maybe I will need to do more examples to be able to decide how to use them properly.
Thanks!
