### ISSUE TITLE
Make autoDispose customizable like a cachePolicy

### ISSUE THREAD

**Issue by FXschwartz** [rrousselGit/river_pod#863]
**Is your feature request related to a problem? Please describe.**
AutoDispose is great but sometimes when it's related to a service call like to a Firestore database, I would like to not completely limit the call from happening again, but instead just add some type of delay to keep my database reads down.

**Describe the solution you'd like**
I would love some way to optionally specify how long before a provider needs to refetch a piece of data instead of giving me the last known value. To keep database reads down I could set it to 10 seconds, so if the user navigates back to a screen that calls that provider within that timeframe the provider would use the already pulled value from cache otherwise if after the 10 seconds then it would pull fresh data.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by rrousselGit** [comment]
Closing in favour of #779
