### ISSUE TITLE
ref.refresh not working with FutureProvider.future

### ISSUE THREAD

**Issue by TimWhiting** [rrousselGit/river_pod#875]
Here is a reproducible sample for that issue I was talking about. Click the button and you'll get the exception after the delay. Click it again, and it returns immediately with the exception and does not execute the body of the provider again. It's making it hard to debug my FutureProviders with hot-reload, since I can't fix the exception and have the provider refresh/ rerun. For now I've converted to a simple StateNotifier with a Future method, but obviously that doesn't keep the state around for me when I don't want to refresh.

```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() {
  runApp(ProviderScope(child: MaterialApp(home: Home())));
}

bool first = true;
final testProvider = FutureProvider((ref) async {
  await Future.delayed(const Duration(seconds: 2), () {});
  if (first) {
    first = false;
    null!;
  }
  return 'hi';
});

class Home extends ConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      body: const Center(
        child: Text('Sample'),
      ),
      floatingActionButton: Builder(builder: (context) {
        return FloatingActionButton(
          onPressed: () async {
            try {
              final value = await ref.refresh(testProvider.future);
              ScaffoldMessenger.of(context).showSnackBar(SnackBar(
                  content: Text(value), duration: Duration(seconds: 1)));
            } catch (e) {
              ScaffoldMessenger.of(context).showSnackBar(SnackBar(
                  content: Text(e.toString()), duration: Duration(seconds: 1)));
            }
          },
          child: const Icon(Icons.add),
        );
      }),
    );
  }
}
```

**Comment by rrousselGit** [comment]
Oh you're refreshing `.future` instead of the provider itself

Yeah this isn't going to work. I'll see what I can do

**Comment by csbence10** [comment]
Hi!

Same here. I found `context.refresh` is no longer available which I've used so far. (I've used `0.14.0+2` until now).
`ref.refresh` doc still says `context.refresh`
```
...
return RefreshIndicator(
       onRefresh: () => context.refresh(productsProvider),
...
```

Is it a typo?

I tried a similar simple example as @TimWhiting mentioned above. That's what I get when watching the `FutureProvider` and after calling `ref.refresh(intProvider.future)`:
```
flutter: {
  "provider": "FutureProvider<int>",
  "newValue": "AsyncData<int>(value: 10)"
}
flutter: {
  "provider": "AsyncValueAsFutureProvider<int>",
  "newValue": "Instance of 'Future<int>'"
}

```

Also tried awaiting the `Future`, no success.

**Comment by TimWhiting** [comment]
@csbence10 
For now this should work
```dart
ref.refresh(intProvider)
await ref.read(intProvider.future)
```

**Comment by antoinepemeja** [comment]
Hello, same issue for me, since 1.0.0 it's broken.
I tried your code @TimWhiting but doesn't work.
I'm trying to find a way to keep the loader active during the refresh.

**Comment by TimWhiting** [comment]
@antoinepemeja Can you provide more explanation on what you are trying to do like a simple code snippet?

**Comment by antoinepemeja** [comment]
Hello,

Finally your tips works, during writing my code example to comment this thread I saw that it works.
BTW, I add my comment, maybe it can help for other.

My code with Riverpod 0.14.0+3

```dart

final itemsRiverPod = FutureProvider<List<Item>>((ref) async {
  final _itemsPresenterRiverPod = ref.watch(itemsPresenterRiverPod);
  List<Item> _items = [];
  _items = await _itemsPresenterRiverPod.fetchItems();
  return Future.value(_items);
});

class ListScreen extends ConsumerWidget {

  @override
  Widget build(BuildContext context, ScopedReader watch) {
    final futureAsyncValue = watch(itemsRiverPod);
    return Scaffold(
      body: RefreshIndicator(
        onRefresh: () async {
          await context.refresh(itemsRiverPod);
        },
        child: Center(
          child: futureAsyncValue.when(
            data: (data) => PageContainer(child: ListView.builder(
              itemCount: data.length,
              itemBuilder: (BuildContext context, int index) {
                return Card(
                  child: Column(children: <Widget>[
                    ListTile(
                    title: AppText(text: '${data[index].title}'),
                    subtitle: Text('${data[index].subtitle}'),
                    onTap: (){

                    },
                    ),
                  ],)
                );
              })),
            loading: () => CircularProgressIndicator(),
            error: (e, st) => Text('Error: $e'),
          ),
        ),
      ),
    );
  }
}
```

Video (everything is normal) :

https://user-images.githubusercontent.com/752689/141644822-82816361-b049-4243-9e65-dc95460a4be0.mp4

So after Riverpod 1.0.0 migration, I have this logic warning :

<img width="364" alt="Screenshot 2021-11-13 at 08 12 42" src="https://user-images.githubusercontent.com/752689/141645072-ee34d5cd-d92d-46dd-8f82-85e2d2baaa8d.png">

And I have this logic behaviour during the pull to refresh (pull to refresh loader doesn't waiting the end of the future) :

https://user-images.githubusercontent.com/752689/141645114-fe26b907-65ad-4812-a781-58ce4c982290.mp4

Then I change my code to integrate your tips :

```dart
onRefresh: () async {
    ref.refresh(itemsRiverPod);
    await ref.read(itemsRiverPod.future);
}
```

and now I have the correct behaviour during the pull to refresh.

The entire code with Riverpod 1.0.0 :

```dart

  final itemsRiverPod = FutureProvider<List<Item>>((ref) async {
    final _itemsPresenterRiverPod = ref.watch(itemsPresenterRiverPod);
    List<Item> _items = [];
    _items = await _itemsPresenterRiverPod.fetchItems();
    return Future.value(_items);
  });

  class ListScreen extends ConsumerWidget {

    @override
    Widget build(BuildContext context, WidgetRef ref) {
      final futureAsyncValue = ref.watch(itemsRiverPod);
      return Scaffold(
        body: RefreshIndicator(
          onRefresh: () async {
            ref.refresh(itemsRiverPod);
            await ref.read(itemsRiverPod.future);
          },
          child: Center(
            child: futureAsyncValue.when(
              data: (data) => PageContainer(child: ListView.builder(
                itemCount: data.length,
                itemBuilder: (BuildContext context, int index) {
                  return Card(
                    child: Column(children: <Widget>[
                      ListTile(
                      title: AppText(text: '${data[index].title}'),
                      subtitle: Text('${data[index].subtitle}'),
                      onTap: (){
                        onItemTap('${data[index].title}');
                      },
                      ),
                    ],)
                  );
                })),
              loading: () => CircularProgressIndicator(),
              error: (e, st) => Text('Error: $e'),
            ),
          ),
        ),
      );
    }
  }
```

Thank you

**Comment by antoinepemeja** [comment]
Hello, finally I make a mistake, I still have the problem, I don't know if my code example can help you to show why is wrong ? thank you

**Comment by NickBalnaves** [comment]
I'm getting a similar issue with FutureProvider autoDispose. When the FutureProvider is set to autoDispose then the FutureProvider seems to not restart, just returns it's cached value

**Comment by chengyuhui** [comment]
This does not work at all because of type mismatch:
```dart
final likelistFamily =
    FutureProvider.family<SongListResult, String>((ref, id) async {
  return PlaylistApi.likedSongs(id);
});

Future<void> _refresh() {
   return ref.refresh(likelistFamily(widget.id));
}
```
gives
```
The argument type 'FutureProvider<SongListResult>' can't be assigned to the parameter type 'ProviderBase<Future<void>>'.
```

Change the code to refresh the future does make the code compile, but it seems that this is not the correct way to use it.
The migration guide and changelog does not mention `refresh`, so I'm wondering what to do.

**Comment by scopendo** [comment]
Out of interest, how would this work if the provider were instead a `StateNotifierProvider<StateNotifier<AsyncValue<T>>, AsyncValue<T>>`, where you'd want to wait for the AsyncLoading state to change to AsyncData (or AsyncError)?

**Comment by rrousselGit** [comment]
@scopendo all providers that emit an AsyncValue expose a ".future"

So you can use that for StateNotifierProvider too

**Comment by scopendo** [comment]
Thanks, @rrousselGit – my oversight – I was looking for the future on the StateNotifier rather than the provider 👍

**Comment by baku-apps** [comment]
This seems to be back again in 1.0.4. 

`final result = await ref.refresh(provider.future)` does not seem to refresh;

**Comment by andreadaoud** [comment]
Hi @rrousselGit,

> all providers that emit an AsyncValue expose a ".future"

I would like to ask if this is still true?

I have a `StaticNotifier` which is defined like this:

```dart
class ClientChannelNotifier extends StateNotifier<AsyncValue<ClientChannel>>
```

And defined a provider like this:

```dart
final myProvider = StateNotifierProvider<ClientChannelNotifier, AsyncValue<ClientChannel>>((ref) {
```

I would like to know how to get a future from this provider? `myProvider.future` does not seem to work. Thanks for your reply in advance!

**Comment by rrousselGit** [comment]
> I would like to ask if this is still true?

No

The expected solution now is to use the new `AsyncNotifier` instead of `StateNotifier`. That's basically the fusion of FutureProvider & StateNotifier

**Comment by vektemok** [comment]
https://riverpod.dev/docs/case_studies/pull_to_refresh don't updated state
