### ISSUE TITLE
hooks_riverpod 0.14.0+5 incompatible with freezed_annotation 0.15.0 ?

### ISSUE THREAD

**Issue by zondaOf2012** [rrousselGit/river_pod#876]
In my pubspec.yaml :

dependencies:
**freezed_annotation: ^0.15.0
hooks_riverpod: ^0.14.0+5**
....

 flutter pub get 

 **cause an error:**

> Because no versions of hooks_riverpod match >0.14.0+5 <0.15.0 and hooks_riverpod 0.14.0+5 depends on riverpod ^0.14.0+3, hooks_riverpod ^0.14.0+5 requires riverpod ^0.14.0+3.
> Because riverpod 0.14.0+3 depends on freezed_annotation ^0.14.0 and no versions of riverpod match >0.14.0+3 <0.15.0, riverpod ^0.14.0+3 requires freezed_annotation ^0.14.0.
> Thus, hooks_riverpod ^0.14.0+5 requires freezed_annotation ^0.14.0.
> So, because vlian_flutter depends on both freezed_annotation ^0.15.0 and hooks_riverpod ^0.14.0+5, version solving failed.
> pub get failed (1; So, because vlian_flutter depends on both freezed_annotation ^0.15.0 and hooks_riverpod ^0.14.0+5, version solving failed.)
> 

**So，I had to use freezed_annotation: ^0.14.0**

**Comment by rrousselGit** [comment]
The version 0.14.x is outdated. I'd suggest migrating to newer versions (1.0.0)
