### ISSUE TITLE
How to do we find if a provider from a family exits in context

### ISSUE THREAD

**Issue by vin-fandemand** [rrousselGit/river_pod#878]
**Is your feature request related to a problem? Please describe.**
When we use a family of providers, and say we use a `String id` to identify each provider in the family, the `context.read()` might return null or error when the provider with that id does not exist in the tree. Is there a way to check if a provider actually exist in the context or ref so that the code doesn't fail with a null while trying to read.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rrousselGit** [comment]
There is no such that. What do you mean by "so that the code doesn't fail with a null while trying to read"?

**Comment by rrousselGit** [comment]
I don't plan on adding such feature for now, so I'll close this issue

**Comment by rrousselGit** [comment]
With 2.1.0, you will now be able to do:

```dart
ref.exists(provider);
container.exists(provider);
widgetRef.exists(provider);
```
