### ISSUE TITLE
OverrideWithProviderMixin not working on web

### ISSUE THREAD

**Issue by TimWhiting** [rrousselGit/river_pod#880]
Error on master flutter channel using web

Uncaught TypeError: framework.OverrideWithProviderMixin$ is not a function
    at :44719/packages/riverpod/src/state_provider.dart.lib.js:539

I'm guessing this is a dart issue?

**Comment by TimWhiting** [comment]
I actually am getting this on flutter stable as well.

**Comment by rrousselGit** [comment]
Sounds like a Dart issue. There's no native code after-all. So if something doesn't work on web, that's not Riverpod's fault

**Comment by TimWhiting** [comment]
I'm going to close this, as I'm unable to reproduce on other machines. I'll restart the one I had issues with

**Comment by TheJulianJES** [comment]
This seems to be the same issue as: https://github.com/rrousselGit/river_pod/issues/889

**Comment by TimWhiting** [comment]
I'm guessing it's a dart issue with web. I can see if I can create a simple reproducible issue for the dart team.

**Comment by jbremmer** [comment]
Anyone able to establish flutter and riverpod versions that work together to continue with development before this is getting fix ?

**Comment by metafounder** [comment]
@jbremmer  flutter_riverpod: ^1.0.0-dev.11

**Comment by jbremmer** [comment]
@metafounder I'm on

flutter --version

```
Flutter 2.7.0-3.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision fc7015e35a (13 days ago) • 2021-10-27 15:18:41 -0700
Engine • revision a75e3b80f9
Tools • Dart 2.15.0 (build 2.15.0-178.1.beta)

```
flutter pub deps
```
|-- flutter_riverpod 1.0.0
|   |-- collection...
|   |-- flutter...
|   |-- meta...
|   |-- riverpod 1.0.0
|   |   |-- collection...
|   |   |-- meta...
|   |   '-- state_notifier...
|   '-- state_notifier 0.7.1
|       '-- meta...
```

with the version 

flutter_riverpod: ^1.0.0-dev.11

this will lead me to same situation with the error `Uncaught TypeError: framework.OverrideWithProviderMixin$ is not a function`

then switching to 
flutter_riverpod: 1.0.0-dev.11

yields bunch of build time errors.

**Comment by metafounder** [comment]
oh ok, mine is (which is working together with `flutter_riverpod: ^1.0.0-dev.11` ): 

```
Flutter 2.5.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 3595343e20 (6 weeks ago) • 2021-09-30 12:58:18 -0700
Engine • revision 6ac856380f
Tools • Dart 2.14.3
```

**Comment by ChiragKr04** [comment]
So the people who are still facing issue with the same problem.
Problem: It occurs to be dart sdk problem with web on stable channel version : 2.5._ and above. There is nothing wrong with riverpod itself.
Workaround: You need to switch from `stable channel` to `master channel`.
