### ISSUE TITLE
When would ^1.0.0-dev (with the officially documented version now) release be available for use ?

### ISSUE THREAD

**Issue by vin-fandemand** [rrousselGit/river_pod#881]
**Describe what scenario you think is uncovered by the existing examples/articles**
A clear and concise description of the problem that you want explained.

**Describe why existing examples/articles do not cover this case**
Explain which examples/articles you have seen before making this request, and
why they did not help you with your problem.

**Additional context**
Add any other context or screenshots about the documentation request here.

**Comment by rrousselGit** [comment]
It is available for use right now

As for a stable release, hopefully, today. I'm implementing https://github.com/rrousselGit/river_pod/issues/828 which is a bit tedious. Once it's done, I'll make a stable release

**Comment by rrousselGit** [comment]
1.0.0 is available, so I'll close this
