### ISSUE TITLE
How to emulate overrideWithProvider via new overrideWithValue API

### ISSUE THREAD

**Issue by xal** [rrousselGit/river_pod#887]
**Describe what scenario you think is uncovered by the existing examples/articles**
overrideWithValue replaced overrideWithProvider in 1.x-dev releases. However, in some cases old approach works better. 
For example:
- multi-module project
- A - REST API library module which has dioProvider with default Dio implementation
- B - app module which depends on A and wants to override Dio implementation for A with own dioProvider(which will be used in other places too)

**Describe why existing examples/articles do not cover this case**
Documentation should have examples about how to emulate the old approach via new overrideWithValue or support both variants

P.S. Thanks for your work. Riverpod is amazing

**Comment by TimWhiting** [comment]
overrideWithProvider was added back in

**Comment by rrousselGit** [comment]
`overrideWithProvider` was added back, so you can still use it.
