### ISSUE TITLE
`dependencies` requirement false positive?

### ISSUE THREAD

**Issue by davidmartos96** [rrousselGit/river_pod#892]
**Describe the bug**
Hello, I've encountered with an issue in a specific situation when using the `dependencies` parameter for a scoped provider.
In the following example, an assert throws because `someServiceProvider` is not added as a dependency, even though this provider is not overridden. 
Is this a false positive error? I thought you should only declare the dependencies of the providers that get overridden.

**To Reproduce**

```dart
import 'package:riverpod/riverpod.dart';
import 'package:test/test.dart';

void main() {
  test('test case', () {
    final parent = ProviderContainer();
    final container = ProviderContainer(
      parent: parent,
      overrides: [
        toOverride.overrideWithValue(4),
      ],
    );

    final notifier = container.read(myNotifierProvider.notifier);
    notifier.someMethod();
  });
}

final someServiceProvider = Provider((ref) => SomeService());
final toOverride = Provider<int>((ref) => throw Exception("not initialized"));

final myNotifierProvider = StateNotifierProvider(
  (ref) {
    final val = ref.watch(toOverride);
    return MyNotifier(ref, val);
  },
  dependencies: [toOverride],
);

class MyNotifier extends StateNotifier<int> {
  MyNotifier(this.ref, int val) : super(val);

  final StateNotifierProviderRef ref;

  void someMethod() {
    final service = ref.read(someServiceProvider);
    // ...
  }
}

class SomeService {}
```

**Comment by rrousselGit** [comment]
This is expected. The fact that someServiceProvider is not scoped doesn't matter. It still isn't in "dependencies"

When specifying "dependencies", all dependencies must be listed, whether they are scoped or not.

**Comment by davidmartos96** [comment]
Thanks Remi!
Unfortunately, this seems inconvenient and error prone (reading a new non declared service) for Notifiers scoped to a screen.
Maybe it would be better to use a family instead? 
There are cases where I don't have an identifier for the family, so it feels weird to use it. Can a random number as a family key be used for this kind of situations?

**Comment by rrousselGit** [comment]
It's not really inconvenient/error prone. Keep in mind that there is a definitive plan to implement a lint rule for this, which would have an auto-fix

The current situation is only temporary.

But yeah, if you can avoid using scoping, do so.

Maybe consider an enum instead of a random number as family key

**Comment by rrousselGit** [comment]
Closing since this is expected
