### ISSUE TITLE
flutter_riverpod v1.0.0 stop the app from starting on web 

### ISSUE THREAD

**Issue by MkamaAFM** [rrousselGit/river_pod#901]
The issue #889 stops me from continuing with my app, should I rollback to previous version until it gets resolved, or is there temporally solution to this.

My app will be mostly used as web app, I started the project while debugging through windows app, so I didn't notice this issue. I already progressed so far, and most of my app's logic depends on riverpod.

**Comment by daniellampl** [comment]
Duplicated #889
