### ISSUE TITLE
Is there any way to handle the error in FutureProvider?

### ISSUE THREAD

**Issue by fanchungchit** [rrousselGit/river_pod#908]
Here's my code
```dart
final provider = FutureProvider((ref) async {
  return await FirebaseFirestore.instance.collection('Data').get();
});
```
When the user does not have right to access this documents, a error will be thrown, but it seems the error does not catch by the 
```dart
ref.watch(provider).when(error: (e, stack) {return Text('$e'})
```

Is there any ways to do so?
Thanks.

**Comment by rrousselGit** [comment]
The error should be caught

Are you sure that an error is thrown? And if so, how are you using ref.watch? It's possible that you are misusing it.

**Comment by fanchungchit** [comment]
Here's my code and the screenshot
'''dart
final itemsProvider = FutureProvider((ref) async {
  return await FirebaseFirestore.instance
      .collection('Orgs/${ref.watch(userProvider).orgIds.first}/Items')
      .get();
});

class ItemView extends ConsumerWidget {
  const ItemView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Item View'),
      ),
      body: ref.watch(itemsProvider).when(
          data: (data) => const Text('have access'),
          error: (e, stack) => const Text('No access'),
          loading: () => const Center(
                child: CircularProgressIndicator.adaptive(),
              )),
    );
  }
}
'''dart
<img width="1173" alt="Screenshot 2021-11-10 at 10 00 47 AM" src="https://user-images.githubusercontent.com/66772739/141035871-e6ab2808-be8f-44d9-b58d-aa608d943a89.png">

**Comment by TimWhiting** [comment]
If you press continue in the debugger, does the error show properly in the body of the scaffold. I think this is just the IDE stopping on an exception that is about to be caught by the provider.

**Comment by fanchungchit** [comment]
> If you press continue in the debugger, does the error show properly in the body of the scaffold. I think this is just the IDE stopping on an exception that is about to be caught by the provider.

Everything work after untick the BREAKPOINTS. Thank you.
<img width="310" alt="Screenshot 2021-11-10 at 10 46 24 AM" src="https://user-images.githubusercontent.com/66772739/141040443-fbf63c5b-9593-4df1-b436-72f16c8ef127.png">
