### ISSUE TITLE
Missing light mode style for highlighted source code

### ISSUE THREAD

**Issue by richardjharris** [rrousselGit/river_pod#911]
https://riverpod.dev/docs/cookbooks/testing#overriding-the-behavior-of-a-provider-during-tests

The highlighted lines here appear in dark grey even with light mode enabled. They look fine in dark mode.

**Comment by creativecreatorormaybenot** [comment]
I think the title could also be "highlighted source code not legible in light mode":

<img width="841" alt="Screen Shot 2021-11-12 at 10 46 24" src="https://user-images.githubusercontent.com/19204050/141454844-332608b0-7a94-4f32-a2c8-c1a9ad066a2e.png">
<img width="841" alt="Screen Shot 2021-11-12 at 10 46 28" src="https://user-images.githubusercontent.com/19204050/141454849-a13e878e-b34f-4f24-adb2-7cccdc2e8ea7.png">
