### ISSUE TITLE
context.read() missing after upgraded from riverpod 0.14.0+3 to 1.0.0

### ISSUE THREAD

**Issue by davebound** [rrousselGit/river_pod#912]
My code used   `context.read()`    in quite a few places while on riverpod 0.14.0+3 but having upgraded to 1.0.0 I'm getting:

`The method 'read' isn't defined for the type 'BuildContext'.
Try correcting the name to the name of an existing method, or defining a method named 'read'.`

What am I missing?

Thx

**Comment by davebound** [comment]
Oh ok its #335 and #899.

Is there a link to how to migrate anywhere please?

**Comment by rrousselGit** [comment]
Use ConsumerWidget + ref.read

**Comment by Somtobro** [comment]
The people in charge of this package lack market strategy...Asper zerooo..your market sense is zero...how can you make such changes in this package like this....do you know how big my project is...I'm switching to flutter bloc or redux as soon as possible ...wtf so I can't use context.read any more so now I have to always wrap in ConsumerWidget what is I want to do context.read(a).state?...:...does that need a consumer wiget????

You guys are good developers, I totally agree... but your business sense is Zero , I assure you if you keep making these kind of drastic changes people will stop using this package..Even bloggers are tired of updating their blogs anytime you guys make update ....common buckle up..my project had 3k+ errors on updating package ...do you know how discouraging that looks....bye bye
..BloC is the way!!!!!!

**Comment by iamarnas** [comment]
@Somtobro 🤦‍♂️ Do you think migrate to to Block or Redux take less time than correct new changes 😅

**Comment by rrousselGit** [comment]
I'll say it again for reference:

The migration can be done automatically for you using a command line.
Do:

```sh
dart pub global activate riverpod_cli
riverpod migrate
```
