### ISSUE TITLE
Missing state type in a snippet in StateProvider documentation 

### ISSUE THREAD

**Issue by swavkulinski** [rrousselGit/river_pod#918]
StateProvider documentation states in a snippet in line 52:

`final productsProvider = StateNotifierProvider<ProductsNotifier>((ref) => ProductsNotifier());`
[https://github.com/rrousselGit/river_pod/blob/master/packages/riverpod/lib/src/state_provider.dart](url)

Is there a state type missing or intention was to use different provider?

**Comment by Hamza-Imran75** [comment]
The documents are not yet updated to version 1.0

**Comment by swavkulinski** [comment]
Got that, I think this one is wrong anyway.

**Comment by rrousselGit** [comment]
This is incorrect. The docs are up-to-date, and that snippet has a bug. I'll fix it
