### ISSUE TITLE
Lack of market stratgy

### ISSUE THREAD

**Issue by Somtobro** [rrousselGit/river_pod#922]
The people in charge of this package lack market strategy...Asper zerooo..your market sense is zero...how can you make such changes in this package like this....do you know how big my project is...I'm switching to flutter bloc or redux as soon as possible ...wtf so I can't use context.read any more so now I have to always wrap in ConsumerWidget what is I want to do context.read(a).state?...:...does that need a consumer wiget????

You guys are good developers, I totally agree... but your business sense is Zero , I assure you if you keep making these kind of drastic changes people will stop using this package..Even bloggers are tired of updating their blogs anytime you guys make update ....common buckle up..my project had 3k+ errors on updating package ...do you know how discouraging that looks....bye bye
..BloC is the way!!!!!!

**Comment by davidmartos96** [comment]
@Somtobro To be fair, you are judging a situation that I don't feel is true.
Remi always stated it was an experimental package as an alternative to provider. You chose to use such package on your project.
Regarding breaking changes, that's the nature of software development, even more when it's in active development. RFCs issues have been opened to gather feedback from the community before going ahead with such changes, and even a migration tool has been written to make those breaking changes automatically.

**Comment by Somtobro** [comment]
@davidmartos96 Bro, I get where you can coming from...I totally understand, but what you don't know is that most people who use flutter use it for scale projects and most times they are self taught developers....These people ,including myself, do not follow news update, they just want to come and see the package fine and good to go..therefore the company should at least think the users of the package...We don't really appreciate having to use migration tools and stuff like that... I can't really explain what in trying to say...but the point is they should think like the users more...consumers don't care about what is going on...I know it's selfish but thats how users are....Again I can't really explain this point but just be open minded about it and you should get what I'm trying to say
..

**Comment by iamarnas** [comment]
I just want to wish easy migration to Bloc 🙃

**Comment by davidmartos96** [comment]
@Somtobro I understand, breaking changes are always a pain, but they are unavoidable. The difference here is that those changes have been made months after the initial experimental release of riverpod. Certain features planned for the future wouldn't really work with the BuildContext approach, and many people were confused with the different ways to read a provider.
Not doing a breaking change, could actually harm the future progress of the package. So better make those changes before a stable release.

And remember that even Bloc or the Flutter framework have breaking changes every once in a while

**Comment by daniellampl** [comment]
That's the risk of using libraries, that are not yet considered fully stable or experimental, my friend. Either you wait for its stable release or you live with eventually appearing breaking changes.

**Comment by rrousselGit** [comment]
Don't forget that the entire migration is done automatically for you by the command line:

```dart
dart pub global activate riverpod_cli
riverpod migrate
```

That will fix the errors for you.

**Comment by iamarnas** [comment]
Looks like you missed this -> [Is it safe to use Riverpod in production](https://github.com/rrousselGit/river_pod#is-it-safe-to-use-in-production)
Upcoming new syntax for flutter bloc 8 -> [This is a must read for those planning to upgrade to bloc v8.0.0](https://twitter.com/felangelov/status/1455237583609413642)

To make your big project depend on third part packages is your choice and you cant avoid changes.
> Pro tip: Always handle local state with setState and for global prefer ValueNotifier or ChangeNotifier. All other state managers use only with more complicated situations.

**Comment by Somtobro** [comment]
@rrousselGit okay cool...will try that out

**Comment by Ehesp** [comment]
If you want to be in full control of package upgrades and breaking changes, build everything yourself from scratch.

Building OSS is not easy. Have some respect.

**Comment by mikehardy** [comment]
We should probably only stick to really stable things with a proven track record of zero carrying cost, like I don't know COBOL.

Oh wait https://en.wikipedia.org/wiki/COBOL#Compatibility_issues

Nope, no escape. Awesome there's a command line migration tool.

**Comment by arnoutvandervorst** [comment]
At least python 2 to 3 was easy.
