### ISSUE TITLE
Clarify rules/concepts re number of Providers/StateNotifiers can be used across app data without missing updates

### ISSUE THREAD

**Issue by callagga** [rrousselGit/river_pod#928]
When designing an App with multiple tables (e.g. say including depth in parent/child arrangement, e.g. TodosDataSet => TodoLists => TodoItems) documentation to understand how many Providers and StateNotifiers there can be without "missing updates".   

Some items/questions within this:

[A] Application with no persistance to database say

- By "missing updates" I am thinking if you had a separate StateNotifier with a Provider for each "table" on it's own then this may be indepentant islands of state, so updating a parent StateNotifier may not trigger updates to children StateNotifiers? 
- For example in my example (TodosDataSet => TodoLists => TodoItems) would the "rules" be: 
  - only one (1) state notifier that covers all these "tables" so they are one "set" of data? (e.g. one state notifier that has within it's state all levels of data, so TodosDataSet, TodoLists and TodoItems)
  - can have as many StateNotifierProvider's as you wish that refernce the single StateNotifier? As the actual state all comes from the single StateNotifier? 

[B] Application with data persisted somewhere (e.g. local SQLite database say)

- I am assuming you may need to decide whether your app is really going to use StateNotifier data, with the underlying persistance layer just being there to "save" when the used decided to "save" data.   
- Assuming for the purpose of this item however you assume the concept is to automatically "persist" data as changes occur.  What would be the rules around how many StateNotifiers and StateProviders could be used here to ensure no "update notifications" are missed? 
- For example should there be only one StateNotifier for the whole database, I'm hoping no. But if you have multiple StateNotifiers for each section of the application/database schema, how do ensure that an update to StateNotifier_A triggers an update to StateNotifier_B?  
- Example:  Say in the app (represented in the database tables) there is a ability to indicate what categories for todo lists a user can see in the UserStateNotifier, but then how does it trigger the TodoDatasetStateNotifier to ensure the scope of Todolist to be shown is correctly changed.  

Hope this makes sense.

**Comment by rrousselGit** [comment]
> so updating a parent StateNotifier may not trigger updates to children StateNotifiers?

What does this mean exactly? There should never be a situation where you'll obtain outdated data in Riverpod. If a parent updates, the children will too

**Comment by callagga** [comment]
Perhaps a bit of Newbie question so apologies of so. One way to cast it is, if you have an app to build with say 20 or so database tables, then you are then deciding how to map these to StateNotifiers and Providers, how would you decide how many to have?  For example one state notifier to cover whole app?  (Say using freezed to represent all data)

**Comment by rrousselGit** [comment]
There's no real answer to that. It depends on so many things
But I'd heavily advise against having everything in a single provider.

In general it is better to split your code is numerous providers. This separate responsibilities

**Comment by callagga** [comment]
ok - If that's ok I'll try to think of a sample app and post back here with a couple of specific questions....that highlight the principles questions in my head...

**Comment by rrousselGit** [comment]
:wave:

This issue seems stale. In the lack of an answer, I'll close it. If you still want something to be covered, please open a new issue while making sure you clarified the questions :smile:
