### ISSUE TITLE
Unable to use ConsumerStatefulWidget

### ISSUE THREAD

**Issue by LaTrita97** [rrousselGit/river_pod#929]
Hi guys I have a problem with the `flutter_riverpod` library.

I don't understand why when I use `ConsumerStatefulWidget` instead of `StatefulWidget` the class is not recognized.

I use version `1.0.0` of the library.

Please, someone can help me to understand what I wrong?

Much appreciated.

**Comment by daniellampl** [comment]
Could you please provide some code in which you face this problem?

In the meantime, please make sure `flutter_riverpod` is added in your `pubspec.yaml` under `dependencies` and not `dev_dependencies`.

**Comment by LaTrita97** [comment]
In the changelog it says 
Added `ConsumerStatefulWidget` + `ConsumerState`, a variant of `StatefulWidgets` that have access to a `WidgetRef`.

How I have to use it?

I've replaced the `extends StatefulWidget` with `extends ConsumerStatefulWidget`.

**Comment by daniellampl** [comment]
You also have to replace `State` with `ConsumerState`

**Comment by LaTrita97** [comment]
Excuse me but I still do not understand, here is a sample code:
```
class HomePage extends ConsumerStatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends ConsumerState<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

I got this error: `Classes can only extend other classes`.
It seems that the Library doesn't have `ConsumerStatefulWidget` and `ConsumerState` classes.

It's normal?

**Comment by daniellampl** [comment]
I assumed you only replaced `StatefulWidget` with `ConsumerStatefulWidget`.

The way you use it is correct and should work just fine (at least for me). 

Are you able to call `context.read` or `context.watch` elsewhere in your project?

**Comment by LaTrita97** [comment]
Now I succeed to use it.
I didn't notice that I was overwriting the library with another version.
Now it works perfectly, sorry Daniel, my fault🤦🏻‍♂️.

**Comment by ABHIJEETKATARE** [comment]
> Now I succeed to use it. I didn't notice that I was overwriting the library with another version. Now it works perfectly, sorry Daniel, my fault🤦🏻‍♂️.

hi sir ,i am also facing the same issue- ConsumerStatefulWidget is not getting recognized by flutter can u help me out to solve this problem please.
