### ISSUE TITLE
useProvider inside ListView.builder - itemBuilder

### ISSUE THREAD

**Issue by arnoutvandervorst** [rrousselGit/river_pod#93]
**Describe what scenario you think is uncovered by the existing examples/articles**
How do I watch a provider inside the buildcontext provided by the ListView.builder itemBuilder property?

**Comment by rrousselGit** [comment]
For ListView.builder, use Consumer or HookBuilder

```dart
builder:(context, index) {
  return HookBuilder(
    builder: (context) {
      useProvider(...) 
    }, 
   );
}
```

But my general recommendation would be to do like in the to-do list example, and create a new widget for the list item instead.

**Comment by rrousselGit** [comment]
Closing as this is technically covered by the to-do list and marvel examples
