### ISSUE TITLE
a hacky way to set state using provider, ie. ref.read(someProvider.notifier).state = someState;

### ISSUE THREAD

**Issue by nyck33** [rrousselGit/river_pod#931]
```
Widget build(BuildContext context) {
    ref.read(userProvider.notifier).state = user;  //here!
    final checkuser = ref.read(userProvider.notifier).state;
    return Scaffold(
      //appBar: AppBar(),
      endDrawer: MyDrawer(),
      body: FirstScreen(user: user),
      bottomNavigationBar: MyBottomNavigationBar(selectedIndex: 0),
    );
  }
```
But now I heard the state is actually just `ref.read(userProvider)` and to call methods in the StateNotifier, use `ref.read(userProvider.notifier)`.

And to also use `watch` rather than `read` for easier debugging later.  

Is it safe to say, these calls should be made in the same place in the code as `setState(){}` would be?
I'm having a super difficult time with the transition from login to homescreen where I'm trying to initialize the state of my user and UI based on the login data.

If possible, please make some documentation on this specific case.  I have a Reddit post: https://www.reddit.com/r/flutterhelp/comments/quypl5/riverpod_when_do_you_use_provider_to_set_state/?utm_source=share&utm_medium=web2x&context=3

**Comment by rrousselGit** [comment]
Doing this inside `build` is a really bad idea.

It sounds like your architecture is not correct. You should have a better place for modifying this provider than doing it here.
