### ISSUE TITLE
Document the removal of context.read

### ISSUE THREAD

**Issue by doppio** [rrousselGit/river_pod#939]
When upgrading Riverpod to 1.0, I discovered that the `BuildContext.read` extension had been removed. It took me a while of hunting through the Riverpod documentation, repository, changelog, and Discord server to eventually find that it had indeed been removed and that Consumer widgets should be used instead to obtain a `ref`.

While the "[Reading a provider](https://riverpod.dev/docs/concepts/reading#obtaining-a-ref-from-a-widget)" article describes the correct way to read a provider, it doesn't explicitly mention the removal of `context.read`. It might be useful to, at least temporarily, call it out as a breaking change in the documentation. Maybe the CHANGELOG.md should mention it if it's not appropriate for the documentation.

If it's already mentioned somewhere that I missed, maybe it should be updated to specifically mention the terms "context.read" or "BuildContext.read" since it's not easily searchable. I see that multiple people have opened issues related to this breaking change, which hints to me that it needs better documentation.

**Comment by lucavenir** [comment]
I had this exact problem while migrating to Riverpod 1.0.0, where I had to unexpectedly change a lot of my `StatelessWidget`s into `ConsumerWidget`s.

**Comment by erfanegtfi** [comment]
I think using  context.read() is much better than changing all StatelessWidgets/StatefullWidgets  to ConsumerWidgets

**Comment by doppio** [comment]
@erfanegtfi This ticket is about the need for better documentation about the change, not about the change itself. There are other tickets where that has been discussed.

**Comment by lucavenir** [comment]
@doppio do you mind linking here some of those?

**Comment by doppio** [comment]
Sure, see #335, #899, #910, #912,

**Comment by daniellampl** [comment]
> I think using context.read() is much better than changing all StatelessWidgets/StatefullWidgets to ConsumerWidgets. How we can read providers without using ConsumerWidgets?

Though accessing `read` and `write` via the `BuildContext` might be the easiest way it has its limitations and won't scale in the long run. Here is an explanation by the author: https://github.com/rrousselGit/river_pod/issues/335#issuecomment-925333300

**Comment by knightowlRaising** [comment]
Yea but still how we can read providers without using ConsumerWidgets? Suppose if I want to call an API in init state.
