### ISSUE TITLE
Adding the lazy attribute allows the provider to disable the lazy load feature.

### ISSUE THREAD

**Issue by tbm98** [rrousselGit/river_pod#94]
The current provider only instantiates when used. but there are a few cases where I want it to be initialized before use, like `lazy: false`.

**Comment by smiLLe** [comment]
Mhhh but you can basically 
```dart
runApp(ProviderScope(child:
HookBuilder(builder: (context) {
  useProvider(provider);
  return MyApp();
}))));`

**Comment by mono0926** [comment]
Consumer version:

```dart
runApp(
  ProviderScope(
    child: Consumer(
      (context, watch) {
        watch(provider);
        return MyApp();
      },
    ),
  ),
);
```

**Comment by rrousselGit** [comment]
The lazy parameter is simple impossible to implement for numerous technical reasons. 

So the approach mentioned by @smiLLe and @mono0926 is the best

**Comment by tbm98** [comment]
Yep. 😅
