### ISSUE TITLE
Provider unexpectedly recomputes after its screen is disposed.

### ISSUE THREAD

**Issue by lucavenir** [rrousselGit/river_pod#943]
**Context**
Note. I'm unsure if the following is a bug; I can say that  this behavior, to me, is unexpected. The following happens in a production app. I'm using Riverpod since July, I just love it.

My app simply uses `watch` onto a `authProvider`: when it's `null`, then we're not logged in.
Otherwise, `authProvider` has a valid User object inside.
```
final authProvider = StateProvider<String?>((ref) {
  // This mocks a log-in auth provider
  // If state == null, we're in a log-out state
  // otherwise, we've logged in with `state` as our user
  return null;
});
```

Therefore, the following works just fine:
```
class MyHomePage extends ConsumerWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return ref.watch(authProvider) == null
        ? const LoginScreen()
        : const HouseListScreen()
  }
}
```

Now, in my `HouseListScreen` I have a list of elements that depends on the `User` that is logged in; of course, I `watch` such list with a provider:
```
final listProvider = Provider<List<String>>((ref) {
  // This mocks a list of something that belongs to the user
  final user = ref.watch(authProvider);

  if (user == null) {
    // This shouldn't happen at all.
    throw "Can't read user's stuff if you're not logged in.";
  }

  return [
    "This",
    "That",
    "This other thing",
  ];
});
```
 Finally, there's a `drawer` that lets my log-out if I click on a button. Easy.
```
TextButton(
    onPressed: () async {
        Navigator.popUntil(context, (_) => false);
        ref.read(authProvider.notifier).state = null;
        await Navigator.pushNamed(context, '/');
    },
    child: Text(
        'Logout!',
        style: Theme.of(context).textTheme.headline4,
    ),
),
```
**Expectations**
When I click on the log out button, after the `authProvider` is set back to `null`, I'd expect my `MyHomePage` Widget to rebuild and show the `LoginScreen()`. I also expect the `listProvider` to be disposed as no one listens to it anymore (we've unmounted the `HouseListScreen()` from the stack) and therefore I wouldn't expect a re-calculation of this provider.

**Bug Behavior**
Again, I'm unsure if this is a bug or if I'm doing something wrong.
What happens is that `listProvider` is recomputed AFTER the screen disposal and therefore throws the exception I've set above ("Can't read user's stuff if you're not logged in."), since `user==null` is now `true`.

After this `throw`, the expected screen pops up as intended, so this is not a critical error for my App.

**To Reproduce**
I've recreated this behavior in the following 100 lines of code:
```
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() {
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'A riverpod test',
      theme: ThemeData(
        primarySwatch: Colors.orange,
      ),
      home: const MyHomePage(),
      routes: {
        LoginScreen.routeName: (_) => const LoginScreen(),
        HouseListScreen.routeName: (_) => const HouseListScreen(),
      },
    );
  }
}

class MyHomePage extends ConsumerWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return ref.watch(authProvider) != null
        ? const HouseListScreen()
        : const LoginScreen();
  }
}

final authProvider = StateProvider<String?>((ref) {
  // This mocks a log-in auth provider
  // If state == null, we're in a log-out state
  // otherwise, we've logged in with `state` as our user
  return null;
});

class LoginScreen extends ConsumerWidget {
  static const routeName = '/login';

  const LoginScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      appBar: null,
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('Ok, this will mock a log-in action'),
            const SizedBox(height: 50),
            TextButton(
              onPressed: () {
                ref.read(authProvider.notifier).state = 'User';
              },
              child: const Text('Login!'),
            ),
          ],
        ),
      ),
    );
  }
}

final listProvider = Provider<List<String>>((ref) {
  // This mocks a list of something that belongs to the user
  final user = ref.watch(authProvider);

  if (user == null) {
    throw "Can't read user's stuff if you're not logged in.";
  }

  return [
    "This",
    "That",
    "This other thing",
  ];
});

class HouseListScreen extends ConsumerWidget {
  static const routeName = '/list';

  const HouseListScreen({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final houses = ref.watch(listProvider);

    return Scaffold(
      appBar: AppBar(
        title: const Text("My list of things"),
      ),
      drawer: TextButton(
        onPressed: () async {
          Navigator.popUntil(context, (_) => false);
          ref.read(authProvider.notifier).state = null;
          await Navigator.pushNamed(context, '/');
        },
        child: const Text('Logout!'),
      ),
      body: Center(
        child: ListView(
          children: <Widget>[
            Text(
              'This is the list of things',
              style: Theme.of(context).textTheme.headline4,
            ),
            const SizedBox(height: 55),
            for (var i = 0; i < houses.length; i++) Text(houses[i]),
          ],
        ),
      ),
    );
  }
}
```

Let me know if this is a documentation-related problem or an actual bug. Again, to me this behavior is unexpected.

**Comment by daniellampl** [comment]
This behavior is intended because all the listeners of the `authProvider` will get informed about the modification to `null`, not just the one in the `MyHomePage`.

Because the check whether the user is null or not inside the `listProvider` is for security reasons, I would suggest you either return an empty array, if the user is not authenticated, or not check the user inside the `listProvider` at all. Your `MyHomePage` is already doing so.

**Comment by lucavenir** [comment]
I get what you say and for sure I'll do that.

But hasn't `listProvider` been disposed before it could get notified because of:
```
          Navigator.popUntil(context, (_) => false);
```
I'd expect `listProvider` to be disposed since no one is listening to it anymore.
_Then_, I'm updating the `authProvider` with:
```
          ref.read(authProvider.notifier).state = null;
```

And at that point I'd expect every listener to be recomputed. I guess my question is: why is `listProvider` listening at that point?

**Comment by daniellampl** [comment]
Use the `.autoDispose` modifier on the `listProvider` to destroy its state if it is not used anymore

https://riverpod.dev/docs/concepts/modifiers/auto_dispose/

**Comment by lucavenir** [comment]
I tried this approach before, but it doesn't really make a difference when it comes to this problem.
Furthermore, aren't `Provider`s in a disposed already when no one listens to them?

I spent the last minutes trying again on the above example, it still throws at that line.
Here's the updated code:

```
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

void main() {
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'A riverpod test',
      theme: ThemeData(
        primarySwatch: Colors.orange,
      ),
      home: const MyHomePage(),
      routes: {
        LoginScreen.routeName: (_) => const LoginScreen(),
        HouseListScreen.routeName: (_) => const HouseListScreen(),
      },
    );
  }
}

class MyHomePage extends ConsumerWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return ref.watch(authProvider) != null
        ? const HouseListScreen()
        : const LoginScreen();
  }
}

final authProvider = StateProvider<String?>((ref) {
  // This mocks a log-in auth provider
  // If state == null, we're in a log-out state
  // otherwise, we've logged in with `state` as our user
  return null;
});

class LoginScreen extends ConsumerWidget {
  static const routeName = '/login';

  const LoginScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      appBar: null,
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('Ok, this will mock a log-in action'),
            const SizedBox(height: 50),
            TextButton(
              onPressed: () {
                ref.read(authProvider.notifier).state = 'User';
              },
              child: const Text('Login!'),
            ),
          ],
        ),
      ),
    );
  }
}

final listProvider = Provider.autoDispose<List<String>>((ref) {
  // This mocks a list of something that belongs to the user
  final user = ref.watch(authProvider);

  if (user == null) {
    throw "Can't read user's stuff if you're not logged in.";
  }

  return [
    "This",
    "That",
    "This other thing",
  ];
});

class HouseListScreen extends ConsumerWidget {
  static const routeName = '/list';

  const HouseListScreen({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final houses = ref.watch(listProvider);

    return Scaffold(
      appBar: AppBar(
        title: const Text("My list of things"),
      ),
      drawer: TextButton(
        onPressed: () async {
          Navigator.popUntil(context, (_) => false);
          ref.read(authProvider.notifier).state = null;
          await Navigator.pushNamed(context, '/');
        },
        child: const Text('Logout!'),
      ),
      body: Center(
        child: ListView(
          children: <Widget>[
            Padding(
              padding: const EdgeInsets.all(15),
              child: Text(
                'This is the list of things',
                style: Theme.of(context).textTheme.headline4,
              ),
            ),
            const SizedBox(height: 55),
            for (var i = 0; i < houses.length; i++)
              InkWell(
                onTap: () {},
                child: Text(houses[i]),
              ),
          ],
        ),
      ),
    );
  }
}
```

**Comment by daniellampl** [comment]
No, the 'Provider' will kind of "hold" the last value it had without disposing it if you don't add the `.autoDispose` modifier to the provider's definition.

Take a look at this example and execute it with and without the '.autoDipose' modifier:

```

final testProvider = Provider<String>((ref) {
  ref.onDispose(() {
    // will only get called if you use the autoDispose modifier.
   // give it a try ;}
    print("dispose");
  });
  return "hello";
});

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends ConsumerStatefulWidget {
  const MyHomePage({
    Key? key,
  }) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends ConsumerState<MyHomePage> {
  bool _showtext = true;

  @override
  Widget build(BuildContext cobntext) {
    return Scaffold(
      appBar: AppBar(title: const Text("Riverpod is cool")),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            _showtext
                ? Consumer(
                    builder: (_, WidgetRef ref, __) {
                      return Text(ref.watch(testProvider));
                    },
                  )
                : Container(),
            ElevatedButton(
              onPressed: () {
                // remove the watched text from the widget tree
                setState(() {
                  _showtext = !_showtext;
                });
              },
              child: const Text('show/unshow text'),
            )
          ],
        ),
      ),
    );
  }
}

```

The 'ref.onDispose' inside the 'testProvider' will only get called if you add the modifier to the provider.

**Comment by lucavenir** [comment]
I see, thank you. Three provider's life cycle is still unknown to me at this point. Where can I read about it?

As for this issue, the `autoDispose` won't do.

**Comment by lucavenir** [comment]
Also I thought of this:

If `user` was `null`, returning an empty list instead of throwing will eventually lead to unexpected bugs.
That `throw` statement is there for a reason: I don't want my dev team or myself to read that provider if I'm not logged in.

That's simply bad design if you really think about it.

**Comment by daniellampl** [comment]
As far as I know, there is no documentation about the lifecycle of a provider.

I have no idea what your real-life scenario is like, so I can't tell you if it is a good fit or not.

**Comment by lucavenir** [comment]
Yeah sorry if I sounded rude but for security reasons in my scenario other providers depends on that. There's the list, and then every element of the list triggers a whole new business logic.

So if I let an empty list slip trough, there's a high chance this will lead to unwanted behavior in the future.

The thing is, by reading all of your great input, I can't understand this behavior. Even by disposing this provider, it still gets re-computed after the pop() method.

Have you tried my updated code? I added autoDispose methods there.

**Comment by rrousselGit** [comment]
> I get what you say and for sure I'll do that.
> 
> But hasn't `listProvider` been disposed before it could get notified? I'd expect this because of:
> 
> ```
>           Navigator.popUntil(context, (_) => false);
> ```
> 
> I'd expect `listProvider` to be disposed since no one is listening to it anymore. _Then_, I'm updating the `authProvider` with:
> 
> ```
>           ref.read(authProvider.notifier).state = null;
> ```

The gist of the issue is here. Your assumption that `listProivder` is not listened anymore is wrong. It **is** listened at the moment that the provider rebuilt.

Your problem is that `Navigator.popUntil` unmounts the widgets that listen to `listProvider` **after** `listProvider` has updated.   
Bear in mind that `popUntil` doesn't unmount widgets synchronously. Instead, that happens the next frame. But then by that time, your provider has updated

There's not much Riverpod can do here.

**Comment by lucavenir** [comment]
Thank you A TON for clarifying this, I know it's a edge case but it bugged me as I wasn't confident onto why this was happening.

Thanks again.

**Comment by rrousselGit** [comment]
Why was this re-opened?

**Comment by lucavenir** [comment]
I'm in doubt if open a new similar one or to deepen this question since I developed a workaround to be used that didn't work anymore.

Basically this issue was about Riverpod updating providers before the Router pops a route.
This was bad in my application since this fired some async requests that were linked such providers.

Back in november I used to implement a workaround that it seemed to be working, but now I had to deeply refactor my whole production app since it wasn't enough.

This is being re-opened since the issue #1169 was linked to this and I was thinking to update this with a reproducible example of my new issue. I managed to implement another workaround (via Discord) but I need to know what the best practice is.

**Comment by rrousselGit** [comment]
This issue would solve itself by gracefully handling provider dispose before the future completes, and maybe debouncing the request.

I assume that you're currently doing:

```dart
final provider = FutureProvider((ref) {
  return networkRequest(ref.watch(otherProvider));
});
```

But you could implement:
- debouncing
- pending request cancellation

by doing:

```dart
final provider = FutureProvider.autoDispose((ref) {
  final cancelToken = CancelToken(); // from dio for cancellation network request
  ref.onDispose(cancelToken.dispose);

  final other = ref.watch(otherProvider);
  await Future.delayed(Duration(milliseconds: 250)); // debounce the request

  if (cancelToken.isCancelled) throw StateException('aborted');

  return networkRequest(ref.watch(otherProvider), cancelToken: cancelToken);
});
```


This would both fix your issue and:
- if `otherProvider` changes multiple times in a quick succession, only one request will be made
- if the widgets listening to the network request are unmounted before the request completes, the network request is aborted

**Comment by lucavenir** [comment]
Thanks a ton, but besides the debouncing (that I didn't know of - so thank you again!), I already implemented this solution in a slighter different way (this example is shown on the docs).
Indeed, that's the workaround I came up with back some months ago, but it still not working 100% of the time and as of now I'm unsure why.

Here's the pseudocode of the solution I came up with - pretty similar to yours:
```
final provider = FutureProvider.autoDispose((ref) {
  final cancelToken = dio.CancelToken();
  ref.onDispose(() => cancelToken.cancel());

  final other = ref.watch(otherProvider);  // This is null iff no house is selected
  if (other == null) {
    // This means that the user de-selected the current house
    // and this provider shouldn't be doing anything at this point

    return some-default-value;  // Or we could throw, return null...
  }

  return networkRequest(other, cancelToken: cancelToken);
});
```

What happens is that sometimes, i.e. in some very RARE cases, when entering the new route and after waiting for the request to complete, me and my tester colleague get to see the `some-default-value` on screen **instead of the true network response**. This, as you could imagine, could very bad in this production app.

This is why I'm trying to build a reproducible example and why I re-opened this issue. Thanks for answering tho, I hope I get to the bottom of this soon.
