### ISSUE TITLE
Stateprovider  the incoming and outgoing values can be different

### ISSUE THREAD

**Issue by okerivy** [rrousselGit/river_pod#953]
**Is your feature request related to a problem? Please describe.**

`Stateprovider` is very convenient for some simple value processing, and there is no need to create other classes

**But I want whether the incoming and outgoing values can be different.**

1. Define provider
`final alphaProvider = StateProvider<int>((ref) => 0);`

2. Use in Widget:  set value 1000
`ref.read(alphaProvider.state).state = 1000;`

3. Use in Widget:  get value 1000，not [0...1]
`final value =ref.watch(alphaProvider);`

**Describe the solution you'd like**

If I want to get a value of 0-1, I have to deal with it in Widget
```
final value = ref.watch(alphaProvider);
final alpha = min(255, max(0, value)) / 255.0;
```

**Describe alternatives you've considered**

Can I convert the incoming value to another value? For example, convert to a double value between 0 and 1.
`final alphaProvider = StateProvider<int>((ref) => min(255, max(0, value)) / 255.0);`

**The purpose of this is to put the processing of the value directly into the definition, so that it can be used directly without further processing.**

Thanks

**Comment by rrousselGit** [comment]
This is not a thing, no.

For complex use cases you should make a StateNotifier and switch to StateNotifierProvider.

**Comment by rrousselGit** [comment]
I'll close this as I have no plan for implementing such a thing.

`StateProvider` is voluntarily restricted to very simple use-cases. For anything more advanced, use `StateNotifierProvider`
