### ISSUE TITLE
I can't invoke method  from  StateNotifier's classes in another StateNotifier class

### ISSUE THREAD

**Issue by Abouassi98** [rrousselGit/river_pod#974]
![image](https://user-images.githubusercontent.com/53384802/144121877-fb2b7fa1-dd4c-48f0-bea5-0833e30fc806.png)
 
![image](https://user-images.githubusercontent.com/53384802/144122100-e8401da4-2453-4975-87c9-69801e0867fe.png)

   AutoDisposeStateNotifierProvider<SharedPref, Object?>((ref)=>ref.notifier.getSharedHelper());
 this method doesn't run

**Comment by rrousselGit** [comment]
That's not how `ref.notifier` works. It's used to obtain the notifier you created before, but here your provider doesn't create any
To begin with, you're not allowed to create providers inside methods like you did. They should always be globals.

You likely want to pass an `AutoDisposeRef ref` to your `LoginNotifier`, then use it to call `ref.read(sharedPref)`
