### ISSUE TITLE
How can I use alternative to setstate((){}) in HookConsumerWidget ?

### ISSUE THREAD

**Issue by Abouassi98** [rrousselGit/river_pod#984]
![image](https://user-images.githubusercontent.com/53384802/144481209-b2046360-1288-466b-ac55-c1c5ba7922d9.png)

I need to rebuild screen to show new value of imagepicker

**Comment by rrousselGit** [comment]
You can use `useState`

**Comment by Abouassi98** [comment]
![image](https://user-images.githubusercontent.com/53384802/144483393-5acb0fc7-4707-4f9a-b954-1739dc73e83b.png)


nothing change

**Comment by Abouassi98** [comment]
![Uploading image.png…]()

nothing change

**Comment by Abouassi98** [comment]
![image](https://user-images.githubusercontent.com/53384802/144487617-415c9ed1-ea08-4f53-897d-75c53a8fa1cf.png)

nothing change

**Comment by rrousselGit** [comment]
You can't do `imagePicker.value != File('')`. 

`File` does not override ==. So `File('') == File('')` return false
