### ISSUE TITLE
Should we create a feature to refresh the whole providers?

### ISSUE THREAD

**Issue by tbm98** [rrousselGit/river_pod#99]
In the case of switching accounts, for example, all data should be refreshed.

The current solution is to create something like accountProvider. and all other providers need to watch for the change of accountProvider and update accordingly.

**Comment by tbm98** [comment]
> You can't call `context.refresh` on all the involved providers?

try to imagine I have a lot of providers, each time I want to refresh all I have to find all of the providers so calling context.refresh is really a problem.

**Comment by rrousselGit** [comment]
Refreshing **all** the providers is not really sustainable

I don't see an issue with refreshing multiple providers manually. What is your concern besides the number of lines?

**Comment by tbm98** [comment]
If I have to refresh all providers, this requires me to do one of two things: either I create a function and there will implement context.refresh all providers, and each time I add the relevant provider, I have to update this function, or I have to find all the related providers to refresh them, the providers are not in the same place so finding them is annoying.
Both methods have their own problems.
It would be easier if there was a full refresh feature.
example:
```dart

final providerKey = ...
ProviderScope (key: providerKey, child: MyApp ());

// refresh all
providerKey.currentState.refresh ()
```

**Comment by rrousselGit** [comment]
Why do you want to refresh **all** providers, rather than only a few specific providers?

I don't understand what you are trying to do/what problem you want to solve

**Comment by tbm98** [comment]
As mentioned above, the problem really only occurs in certain specific cases, like switching users and loading all kinds of related information. In this case, no data is reused.

**Comment by rrousselGit** [comment]
ref.watch should handle that automatically

**Comment by tbm98** [comment]
I know. perhaps the programmer should solve this problem himself
